msupply-foundation/open-msupply

- client/README.md
- client/package.json
- client/packages/host/package.json
- client/packages/host/public/config.js
- client/packages/host/public/config.local.js
- client/packages/host/webpack.config.js
- package.json
Fixes #9 
( the incorrectly named branch is because of repo confusion soz )
Adds a `start-local` and `start-remote` script, and an alias for `yarn start` which gives you the remote, or `config.js` version. Technically the `remote` option can be local too, if you choose to update the config file, but let's ignore that for now.
Currently when running the remote server locally I get this, which is not caused by this PR.. local server was working on Thursday 🤷 
```
ERROR actix_http::h1::dispatcher] stream error: Request parse error: Invalid Header provided
```
> yarn start local script

- client/package.json
- client/packages/common/package.json
- client/packages/common/src/ui/components/navigation/Tabs/TabKeybindings.tsx
- client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/InboundLineEdit.tsx
Fixes #35 
My summary is 'stale closure' 🙄 
The effect which assigns the keyboard handler needs to be updated when the array of draft items changes, otherwise it just adds one to the original list..
Slightly different with stocktakes, as that has another layer of components which also works around the problem.
> Adding inbound batches

- client/packages/common/src/intl/context/IntlContext.tsx
- client/packages/host/package.json
Fixes #72 
The cause is [this change](https://github.com/openmsupply/open-msupply/blob/8ea07ec316298c8998f7c11cc6c0285338e3863d/client/packages/common/src/intl/context/IntlContext.tsx#L42) 
I've tested by running locally with `cargo run` and compiling a release build and loading the server-hosted version. Both work fine - so I'm not sure of the reason for the change.
> Fix language resource path

- client/packages/host/package.json
closes #64 
as per issue, I messed up a conflict resolution during merge, and here is reason why i removed yarn clean in the first place: https://github.com/openmsupply/open-msupply/commit/cd831cd4b957263f7396a8354b734c95db979cb8
Thanks @mark-prins for noticing here: https://github.com/openmsupply/open-msupply/pull/41/files#r884355521, and i should have tried to build before merging that PR
> Remove yarn clean from host package.json

- server/repository/src/tests.rs
Closes: #90 
This test is disabled when running tests using in 'memory' sqlite.
When running in memory sqlite uses a shared cache and returns an SQLITE_LOCKED response when two threads try to write using the shared case concurrently
https://sqlite.org/rescode.html#locked
We are relying on busy_timeout handler to manage the SQLITE_BUSY response code in this test and there's no equivalent available for shared cache connections (SQLITE_LOCKED).
If we were to shared cache in production, we'd probably need to use a mutex to protect the database connection.
> Disable deadlock test for sqlite 'in memory'

- server/repository/src/database_settings.rs
- server/server/src/sync/central_data_synchroniser.rs
Closes #85 
Now that I've done, this I'm not sure it's needed? The r2d2 errors seem sufficient?
@mark-prins you mentioned this on the demo server. Did you see any r2d2 errors on demo?
Example error with postgres:
```
[2022-06-07T03:15:59Z ERROR r2d2] connection to server at "localhost" (::1), port 5432 failed: Connection refused
Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
Is the server running on that host and accepting TCP/IP connections?
thread 'main' panicked at 'Failed to connect to postgres database omsupply-database - timed out waiting for connection: connection to server at "localhost" (::1), port 5432 failed: Connection refused
Is the server running on that host and …
```
> Improve logging when unable to connect to database

- server/cli/Cargo.toml
- server/server/src/sync/translation_central/mod.rs
closes #97 
There is zip file in the issue, looks better now
[out.txt.zip](https://github.com/openmsupply/open-msupply/files/8852401/out.txt.zip)
Still quite a few warnings/errors:
* 3 stores ignored, those are system store
* MastListNameJoin foreign key violation (name with id doesn't exist)
* number records (that we don't want to integrate yet, although some requisitions in there, we only handle request_requisition and response_requisition https://github.com/openmsupply/open-msupply/issues/69
* decimal points in item_line : /
* a bunch of name store joins with no name (patients, which are integrating in remote, but queried in translations, it's ok to ignore those, although we should query buffer if we doing this sort of check)
* name store join for system name
* invoice lines linked to …
> 97 update output during sync

- server/graphql/core/src/loader/document.rs
- server/graphql/document/src/lib.rs
- server/graphql/document/src/queries/document.rs
- server/repository/src/db_diesel/document.rs
- server/service/src/document/document_service.rs
@andreievg did we discuss the return type for single node endpoints? did we plan to update it? Did we got a conclusion? In this PR I return a `Result<Option<DocumentNode>>` so either node is found or not and the remaining DB error is returned as a standard error.
Existing way would be: 
```rust
#[derive(Union)]
pub enum DocumentResponse {
Error(NodeError),
Response(DocumentNode),
}
```
What do you think?
Closes #113
> 113 document endpoint

- server/report_builder/README.md
- server/report_builder/src/build.rs
Needed to eventually ref to existing, common report definition, e.g. to have a common icon or header for all reports.
Closes #71
> Add reference support to the report builder

- client/packages/host/webpack.config.js
Fixes #120 
Webpack config had changed with the recent upgrade.
> Retain .gitignore on build

- client/packages/common/src/types/schema.ts
- client/packages/inventory/src/Stocktake/DetailView/AppBarButtons.tsx
- client/packages/invoices/src/InboundShipment/DetailView/AppBarButtons.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/AppBarButtons.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/AppBarButtons/AppBarButtons.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/AppBarButtons/AppBarButtons.tsx
- client/packages/system/src/Report/api/hooks/document/useReports.ts
- client/packages/system/src/Report/api/operations.generated.ts
- client/packages/system/src/Report/api/operations.graphql
- client/packages/system/src/Report/components/ReportSelector.tsx
- server/graphql/reports/src/reports.rs
- server/repository/migrations/postgres/2022-03-15T10-00_report_table/up.sql
- server/repository/migrations/sqlite/2022-03-15T10-00_report_table/up.sql
- server/repository/src/database_settings.rs
- server/repository/src/db_diesel/report.rs
- server/repository/src/db_diesel/report_row.rs
- server/server/src/sync/translation_central/mod.rs
- server/server/src/sync/translation_central/report.rs
- server/server/src/sync/translation_central/test_data/mod.rs
- server/server/src/sync/translation_central/test_data/report.rs
- server/service/src/report/dummy_reports.rs
- server/service/src/report/report_service.rs
- Pull reports from central server
- Better match column names from existing report table (category -> context)
- Rename category -> context in API and FE / update schema
- Split Invoice context into Inbound and OutboundShipment
Closes #139
> 139 pull central report records

- server/cli/src/cli.rs
- server/service/src/login.rs
Fixes #175 
An oldie but a goodie.. 
The API allows insensitive logins - it was after that, where we lookup the user in our database which was failing.
Rather than make the db lookup insensitive, I've put the responsibility back on the API - if that authenticates ok, then we simply use the same username which it returns, as that will be consistent.  Using the user supplied username introduces the variability.
> Take username from server

- server/graphql/core/src/loader/document_registry.rs
- server/graphql/core/src/loader/loader_registry.rs
- server/graphql/core/src/loader/mod.rs
- server/graphql/document/src/queries/document_registry.rs
- server/graphql/document/src/types/document_registry.rs
- server/repository/src/db_diesel/document_registry.rs
- server/service/src/document/document_registry/mod.rs
For example, this makes it convenient to get all encounter types for a
given program.
Also simplify the query error type.
#32
> Add children node to the document registry node

- server/Cargo.lock
- server/configuration/base.yaml
- server/server/Cargo.toml
- server/server/src/lib.rs
Closes #131 
Save machine UUID instead of randomly generating it. Works for Linux, Windows and Mac (only tested on Mac so far 🤔 )
> Save machine UUID

- server/repository/src/db_diesel/user_row.rs
Fixes #175 
Using a case-insensitive comparison for username rather than the Eq trait.
Tested using sqllite and postgres, with and without 4D running.
> Case insensitive login

- server/service/src/auth.rs
- server/service/src/auth_data.rs
This avoid problems in the UI, i.e. since a dummy user was used with the
flag the UI doesn't behave as expected.
With this patch its possible to do unauthenticated API calls, e.g. for
debugging or testing while having a working UI with normal token
authentication.
> Only evaluate the debug_no_access_control flag if no token is provided

- server/server/src/sync/sync_api_v5.rs
Shows something like:
[2022-06-22T02:57:10Z ERROR server] Failed to perform the initial sync:
Failed to pull central sync records - status: 401, code: site_incorrect_hardware_id, message: Site hardware ID does not match
instead of just "unauthorized"
> Better sync api error message

- client/packages/inventory/src/Stocktake/api/hooks/line/useStocktakeDeleteSelectedLines.ts
Fixes #158 
Does what it says on the tin
> Prevent deleting lines from disabled stocktake

- client/packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.ts
- client/packages/host/src/components/AppDrawer/AppDrawer.tsx
- client/packages/inventory/src/Stocktake/DetailView/ContentArea/ContentArea.tsx
- client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts
- client/packages/inventory/src/Stocktake/DetailView/DetailView.tsx
- client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEdit.tsx
- client/packages/inventory/src/Stocktake/ListView/CreateStocktakeButton.tsx
- client/packages/inventory/src/Stocktake/api/api.ts
- client/packages/inventory/src/Stocktake/api/hooks/document/useInsertStocktake.ts
- client/packages/system/src/Item/Components/StockItemSelectModal/StockItemSelectModal.tsx
- client/packages/system/src/Item/api/api.ts
- client/packages/system/src/Item/api/hooks/index.ts
- client/packages/system/src/Item/api/hooks/useStockItemsWithStockLines/index.ts
- client/packages/system/src/Item/api/hooks/useStockItemsWithStockLines/useStockItemsWithStockLines.tsx
Fixes #243 
and https://github.com/openmsupply/open-msupply-internal/issues/7
Creates stocktake lines for each available stock line, if there are any for the items selected.
Sets the counted quantity to be the available quantity, as does mSupply.
Have also tweaked the grouping display, so that it shows `[multiple]` a little more, and adds the quantities ( even though this is dodgy, given pack sizes )
> create rows with stock lines if available

- client/package.json
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditTable.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/utils.ts
Fixes #266 
Patch release to fix the outbound placeholder row issue.
Setting the `isUpdated` flag on placeholder rows that have `isCreated` false (i.e. are sent by the server) and have a value of `0` - when a quantity is allocated to a stock line row.
This then will send a delete request for that unallocated row, when the allocated row is inserted or updated.
> 266 os placeholder rows

- server/repository/src/db_diesel/user_row.rs
- server/repository/src/lib.rs
- server/service/src/user_account.rs
Closes (Yet Again) #175 
The case insensitive like approach (previously implemented) allows a user to login with partial username using an sql wildcard match (if central server is not available). E.g. `adm%` instead of `admin`. They still need to provide the correct password, but you could try things like a%,b%...z% with a list of common passwords hoping to login as someone.
**Note: Tests are failing on this branch but seems to be log related not my changes...**
Login tested in sqlite locally with no central server
> sql_function! macro to allow lowercase comparison for usernames.

- client/packages/system/src/Name/api/api.ts
Fixes #273 
Rather than update `DEFAULT_PAGINATION_LIMIT` in `filter_sort_pagination` I've pushed the implementation to the client and specified a greater limit.
> Increase name query limit

- client/packages/common/src/localStorage/keys.ts
- client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteList.tsx
- client/packages/common/src/ui/layout/tables/components/Cells/CheckboxCell/EnabledCheckboxCell.tsx
- client/packages/common/src/ui/layout/tables/components/Cells/CheckboxCell/index.ts
- client/packages/common/src/ui/layout/tables/context/hooks/useIsGrouped.ts
- client/packages/inventory/src/Stocktake/DetailView/ContentArea/ContentArea.tsx
- client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEdit.tsx
- client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx
Fixes #200 
Disables the row, while displaying the details of each column.
Have also chucked in these ones:
- When selecting items as part of stocktake creation, the list scrolls to the top (thanks @clemens-msupply for spotting that!)
- The groupBy should default to true (that's for @adamdewey)
> Stocktake show lines

- client/packages/invoices/src/OutboundShipment/DetailView/Footer/StatusChangeButton.tsx
- server/repository/src/db_diesel/filter_sort_pagination.rs
- server/repository/src/db_diesel/invoice_line.rs
- server/service/src/invoice/outbound_shipment/update/generate.rs
- server/service/src/invoice/outbound_shipment/update/mod.rs
- server/service/src/invoice/outbound_shipment/update/validate.rs
closes #274 
* Existing check for unallocated lines when status of outbound shipment is changed 'above' new (allocated +), would only check for unallocated lines with non zero quantity
* Zero quantity unallocated lines are trimmed when status changed to to allocated +
* Update useStatusChangePlaceholderCheck to allow placeholder with numberOfPacks === 0
> 274 Trim unallocated lines with zero quantity

- client/packages/system/src/Patient/CreatePatientModal/CreatePatientModal.tsx
- client/packages/system/src/Patient/ListView/AppBarButtons.tsx
- client/packages/system/src/Patient/hooks/useCreatePatientStore.ts
This avoids doing unnecessary API calls and getting into an inconsistent
state.
Also add a safety check to not get into an invalid patient state. (This fix somehow solved it but I had another case where update was called without setting the patient first which resulted navigating to an undefined value -> crash...)
#280
> Only mount CreatePatientModal when it suppose to be shown

- client/packages/common/src/hooks/useUrlQuery/useUrlQueryParams.ts
closes: #265 
There is probably a better way to solve this, but would require a bit of refactoring, so thought to keep it simple.
> 265 Don't change sort direction when useUrlQueryParam mounts

- server/repository/src/database_settings.rs
- server/repository/src/tests.rs
Unscientific benchmark for running the tests:
- memory: 28s
- sqlite: 1m39s
- postgres: 1m58s
Related to #128
> Fix warnings for the memory feature

- client/packages/common/src/hooks/useUrlQuery/useUrlQueryParams.ts
- client/packages/inventory/src/Stocktake/api/hooks/document/useStocktakes.ts
- client/packages/inventory/src/Stocktake/api/hooks/line/useStocktakeRows.ts
- client/packages/invoices/src/InboundShipment/api/hooks/document/useInbounds.ts
- client/packages/invoices/src/OutboundShipment/api/hooks/document/useOutbounds.ts
- client/packages/invoices/src/OutboundShipment/api/hooks/line/useOutboundRows.ts
- client/packages/requisitions/src/RequestRequisition/api/hooks/document/useRequests.ts
- client/packages/requisitions/src/ResponseRequisition/DetailView/columns.ts
- client/packages/requisitions/src/ResponseRequisition/api/hooks/document/useResponses.ts
- client/packages/system/src/Item/api/hooks/useItems/useItems.ts
- client/packages/system/src/Location/api/hooks/document/useLocations.ts
- client/packages/system/src/MasterList/DetailView/columns.ts
- client/packages/system/src/MasterList/api/hooks/document/useMasterLists.ts
- client/packages/system/src/Name/api/hooks/document/useNames.ts
- client/packages/system/src/Stock/ListView/ListView.tsx
- client/packages/system/src/Stock/api/hooks/document/useStockLines.ts
closes: #291 
Had to change initialSorKey to initialSort (since we need to also specify direction to be descending for createdDatetime).
By full reload I just mean refreshing the page (or even better copying url and pasting it in another tab)
> 291 change default sort for list of invoices, requisitions and stocktake

- client/packages/common/src/hooks/useUrlQuery/useUrlQueryParams.ts
- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/localStorage/keys.ts
- client/packages/common/src/ui/layout/tables/columns/PaginationRow/PaginationRow.tsx
- client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx
- client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/InboundLineEditForm.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditForm.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/columns.ts
- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEditForm.tsx
- client/packages/system/src/Item/Components/StockItemSearchInput/StockItemSearchInput.tsx
Fixes #302 
Some minor fixes, bundled together in one PR.
The pagination is a bit of a quick and dirty - am saving to localStorage for that one, on the understanding that you'd want to retain the option set. If the value is in the URL then it won't be retained for you. Have also set that as a general option - so it will apply to all paginated data tables 🤷 
The stocktake change is fairly sensible, I think.
Likewise the outbound placeholder row changes.
Then there's the auto-open of the item autocomplete when creating inbound, outbound and internal orders. This is something that we've tried before - and the issue is that the Popper displays incorrectly positioned. I've worked around that by making the open state controlled ( which it partly was anyway ) and delaying the open by 300ms.
> Misc Ux issues

- server/cli/Cargo.toml
- server/graphql/Cargo.toml
- server/graphql/batch_mutations/Cargo.toml
- server/graphql/core/Cargo.toml
- server/graphql/general/Cargo.toml
- server/graphql/invoice/Cargo.toml
- server/graphql/invoice_line/Cargo.toml
- server/graphql/location/Cargo.toml
- server/graphql/reports/Cargo.toml
- server/graphql/requisition/Cargo.toml
- server/graphql/requisition_line/Cargo.toml
- server/graphql/stocktake/Cargo.toml
- server/graphql/stocktake_line/Cargo.toml
- server/graphql/types/Cargo.toml
- server/report_builder/Cargo.toml
- server/repository/Cargo.toml
- server/server/Cargo.toml
- server/service/Cargo.toml
Closes #303 
Doc tests slow down testing when not used.
This change improves test time by around 15s with `--features=memory`
> Disable doc tests for crates that don't use them

- server/repository/src/database_settings.rs
Fixes #222 
Along the way, I made it easier for those who are setting up postgres. If you specify a database which doesn't exist, but credentials which can create, then the server will create the database for you. Just as good as sqlite now!
Have also added in Clemens' temporary fix, since I am already patching demo and AV to use this.. postgres doesn't run on windows without it.
Note: test[4] fails with `FATAL:  database "[username]" does not exist` which isn't accurate. not concerned enough to look further into that one
> Create postgres database if it doesn't exist

- client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEditForm.tsx
- server/service/src/sync_processor/requisition/common.rs
> Requisition fixes

- server/Cargo.lock
- server/cli/Cargo.toml
- server/cli/src/cli.rs
- server/repository/src/db_diesel/unit_row.rs
- server/server/Cargo.toml
- server/server/src/main.rs
- server/service/Cargo.toml
- server/service/src/sync/central_data_synchroniser.rs
- server/service/src/sync/remote_data_synchroniser.rs
- server/service/src/sync/synchroniser.rs
- server/service/src/sync/test/pull_and_push.rs
- server/service/src/sync/translation_and_integration.rs
- server/util/Cargo.toml
- server/util/src/lib.rs
- server/util/src/logger.rs
closes: #241 
closes: #229 
* Removed excessive integration and translation result (should just be a summary of errors and success counts), and use env_logger (now common in utils) to see why check_records_against_database fails
* Added integration transactions and test
* Remote and Central errors to use this error for nicer console printing. I think we should try and use thiserror (since it's easy to define console friendly messages and it keeps the original error) as much as possible and only use anyhow in dynamic context (i.e. translations use anyhow, i think it should be common serde error variant, database variant and another variant for generic anyhow). It's a very good idea to keep errors types for matching and to log as much information as possible from the start (we had many …
> 241 reinstate sync integration transaction and errors

- server/cli/src/refresh_dates.rs
- server/repository/src/db_diesel/name_store_join.rs
- server/repository/src/db_diesel/sync_buffer.rs
- server/service/src/sync/mod.rs
- server/service/src/sync/test/mod.rs
- server/service/src/sync/test/pull_and_push.rs
- server/service/src/sync/test/test_data/invoice.rs
- server/service/src/sync/test/test_data/invoice_line.rs
- server/service/src/sync/test/test_data/mod.rs
- server/service/src/sync/test/test_data/name_store_join.rs
- server/service/src/sync/test/test_data/requisition.rs
- server/service/src/sync/test/test_data/requisition_line.rs
- server/service/src/sync/translation_and_integration.rs
- server/service/src/sync/translations/invoice.rs
- server/service/src/sync/translations/invoice_line.rs
- server/service/src/sync/translations/name_store_join.rs
- server/service/src/sync/translations/requisition.rs
- server/service/src/sync/translations/requisition_line.rs
closes: #246 
I am not sure if name_store_join can be toggled without deleting it.
Also we should eventually add a condition to check that delete remote records are from foreign sites.
Added TODO for both of the above, and added checkbox for them in the epci
Should be pretty straight forward. I had one issue with postgres tests not passing in `pull_and_push` for delete integration, sync buffer rows are upserted with 'DELETE' action, and since they already have integartion_datetime set, those were not updated and deletes were not being integrated, fixed but made an issue to look at this in other areas: https://github.com/openmsupply/open-msupply/issues/247
> 246 handle sync remote data deletes

- server/repository/src/db_diesel/name_store_join.rs
- server/repository/src/db_diesel/sync_buffer.rs
- server/repository/src/mock/mod.rs
- server/service/src/sync/test/mod.rs
- server/service/src/sync/test/pull_and_push.rs
- server/service/src/sync/test/test_data/mod.rs
- server/service/src/sync/test/test_data/number.rs
- server/service/src/sync/test/test_data/special/mod.rs
- server/service/src/sync/test/test_data/special/name_to_name_store_join.rs
- server/service/src/sync/test/test_data/store.rs
- server/service/src/sync/translation_and_integration.rs
- server/service/src/sync/translations/mod.rs
- server/service/src/sync/translations/special/mod.rs
- server/service/src/sync/translations/special/name_to_name_store_join.rs
closes: #250 
I think this is where Visitor pattern shines, it's only benefit as far as I can see (dynamically loading visitors, which we don't really use in sync), enforcing certain interface for developers to use, fragment complex operation into seperate steps (which would mean in this case, don't exist on the first match of translation). I could have added this to name translation, but I think it just make the method more crowded, and since this translation operation will eventually be removed it's better to do it in its own step. Thus had to modify integration slightly to allow all translators to try and translate.
Also added extra_data to sync pull test object.
Quite please that translation visitor interface makes this quite easy and clean
> 250 name is customer and supplier to reflect in name store join

- server/service/Cargo.toml
- server/service/src/lib.rs
- server/service/src/sync/central_data_synchroniser.rs
- server/service/src/sync/sync_api_v3.rs
- server/service/src/sync/sync_api_v5.rs
- server/service/src/sync/test/integration/central_server_configurations.rs
- server/service/src/sync/test/integration/invoice.rs
- server/service/src/sync/test/integration/location.rs
- server/service/src/sync/test/integration/mod.rs
- server/service/src/sync/test/integration/number.rs
- server/service/src/sync/test/integration/remote_sync_integration_test.rs
- server/service/src/sync/test/integration/requisition.rs
- server/service/src/sync/test/integration/stock_line.rs
- server/service/src/sync/test/integration/stocktake.rs
- server/service/src/sync/test/mod.rs
closes #255
some of these changes feel a bit dirty, but I think it might be ok for tests for now.
requires this central branch: https://github.com/sussol/msupply/compare/feature/sync-v5...feature/sync-v5-test-temp (will be PRed).
Should be able to run integration test with rust analyzer or from command line, as per comment (need a datafile with a sync site, should work on empty data files with a sync site).
```
// SYNC_SITE_PASSWORD="pass" SYNC_SITE_NAME="demo" SYNC_URL="http://localhost:2048" NEW_SITE_PASSWORD="pass" cargo test sync_integration_test --features integration_test
// OR in VSCODE settings if using rust analyzer:
// "rust-analyzer.runnableEnv": { "SYNC_URL": "http://localhost:2048", "SYNC_SITE_NAME": "demo","SYNC_SITE_PASSWORD": "pass", "NEW_SITE_PASSWORD": "pass"}
// …
```
> 255 update existing sync integraiton tests

- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/hooks/usePackSizeController.tsx
Fixes #350 
The issue is that the pack size options include `Any` if expired lines are present. The only reason I could see for this is to provide an option which enables the expired line if the expired line has a different pack size ( if the pack size is the same, then you can already allocate from it ).
In the example given, an expiry date had been entered incorrectly ( `03/0024` ) and so the `Any` option was shown, even though all pack sizes were `20`.
examples:
All the same pack size, with an expired stock line:
Different pack size on the expired line:
When `Any` is selected, the expired line is available for allocation:
> OS pack size selection

- server/graphql/document/src/lib.rs
- server/graphql/document/src/mutations/encounter/insert.rs
- server/graphql/document/src/mutations/encounter/mod.rs
- server/graphql/document/src/mutations/encounter/update.rs
- server/graphql/document/src/mutations/mod.rs
- server/service/src/auth.rs
- server/service/src/document/encounter/encounter_schema.rs
- server/service/src/document/encounter/insert.rs
- server/service/src/document/encounter/mod.rs
- server/service/src/document/encounter/update.rs
- server/service/src/document/mod.rs
- server/service/src/document/program/mod.rs
- server/service/src/document/program/upsert.rs
- server/service/src/document/schemas/encounter.json
- server/service/src/service_provider.rs
Add endpoint to insert and update a patient encounter.
Testing setup to add an encounter for a patient (first add program and then add encounter under this program):
```graphql
mutation MyMutation($storeId: String, $programType: String, $programData: JSON, $encounterType: String, $encounterData: JSON, $encounterDataUpdate: JSON) {
insertProgram(input: {type: $programType, patientId: "patient1", data: $programData, schemaId: "e7df3c13-b6eb-4883-8f00-be3b526b7c6b"}, storeId: $storeId) {
... on DocumentNode {
id
name
}
}
insertEncounter(input: {type: $encounterType, patientId: "patient1", data: $encounterData, schemaId: "5a2959fd-a456-4ff4-b219-d72d907d438f", programType: $programType}, storeId: $storeId) {
... on DocumentNode {
id
name
}
}
}
```
with vars (schema id need to be looked up …
> 326 encounter endpoints

- client/packages/common/src/ui/components/buttons/standard/DialogButton.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/ItemCharts/ConsumptionHistory.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
- client/packages/requisitions/src/RequestRequisition/api/api.ts
- client/packages/requisitions/src/RequestRequisition/api/hooks/index.ts
- client/packages/requisitions/src/RequestRequisition/api/hooks/line/index.ts
- client/packages/requisitions/src/RequestRequisition/api/hooks/line/useDeleteRequestLine.ts
- client/packages/system/src/Item/api/api.ts
- client/packages/system/src/Item/api/hooks/useStockItemsWithStats/useStockItemsWithStats.tsx
- server/service/src/requisition_line/chart/mod.rs
- server/service/src/requisition_line/chart/stock_evolution.rs
Fixes #317 
The other item, of "Print > does not seem to be working" required a database migration on the demo server.
> Internal order fixes

- server/Cargo.lock
- server/android/src/android.rs
- server/server/Cargo.toml
- server/server/src/lib.rs
- server/service/src/settings.rs
Fixes #221 
I was hoping to just use `machine_uid::get()` and fetch from settings if that failed - but the android build wouldn't compile if `machine_uid` was included, so I've had to make it a little more specific than I'd like.
Have tested on android and the setting is updated, and makes it through to 4D:
also ran the server locally with these changes and it still works
> Add android ID

- server/service/src/sync/test/integration/central/master_list.rs
- server/service/src/sync/test/integration/central/mod.rs
- server/service/src/sync/test/integration/central/name_and_store_and_name_store_join.rs
- server/service/src/sync/test/integration/central/report.rs
- server/service/src/sync/test/integration/central/test.rs
- server/service/src/sync/test/integration/central/unit_and_item.rs
- server/service/src/sync/test/integration/central_server_configurations.rs
- server/service/src/sync/test/integration/errors.rs
- server/service/src/sync/test/integration/mod.rs
- server/service/src/sync/test/test_data/item.rs
- server/service/src/sync/translations/item.rs
- server/util/src/json.rs
- server/util/src/lib.rs
closes: #327 
Branch wouldn't compile. Full changes and branch to use locally when reviewing is form this [PR](https://github.com/openmsupply/open-msupply/pull/335), which also has a [README.md](https://github.com/openmsupply/open-msupply/blob/a83bdbade3259bd5122e846b1e7f9ea6100f8c8a/server/service/src/sync/test/integration/README.MD)
Using `SyncRecordTester` which relies on existing mechanism of checking `IntegrationRecords` deletes and upserts against database
> 327 central sync integration test

- client/packages/common/src/ui/components/loading/BasicSpinner/BasicSpinner.tsx
- client/packages/common/src/ui/forms/JsonForms/JsonForm.tsx
- client/packages/common/src/ui/forms/JsonForms/components/Array.tsx
- client/packages/common/src/ui/forms/JsonForms/components/Text.tsx
- client/packages/common/src/ui/forms/JsonForms/useJsonForms.tsx
Fixes #371 
To make the form submission nicer to use, I've swapped out the `onBlur` for a debounced update. I like it better 🤷 
To make the PR much harder to read, I've refactored the hook - that file was too large for my taste and was doing too many things. I've lifted out the majority of the JSX into a new component.
Also disabled the save button when there's nothing to save, as it was, you clicked `Save` and it closed the form without saving. Minor thing, but that means the button doesn't say what it does.
Another minor tweak - have changed the cancel method; that was navigating back one, which was odd when you were on a page and then updated the URL to navigate to a patient. I've changed to an explicit navigate back to the list, as that is the expectation, I think.
When I first hit …
> Form submit

- client/packages/common/src/styles/RTLProvider.tsx
- client/packages/common/src/styles/theme.ts
- client/packages/common/src/ui/components/portals/DetailPanel/DetailPanel.tsx
- client/packages/host/src/components/AppDrawer/AppDrawer.tsx
- client/packages/host/src/components/NotFound.tsx
- client/packages/host/src/components/Viewport.tsx
Fixes #412 
Have removed the unnecessary usages of `vh` as a css unit and in the single instance where it is still required, have used `window.innerHeight` instead.  
Also added a resize listener so that you can rotate the tablet without the app height going strange.
> App height on mobile

- client/packages/common/src/ui/forms/JsonForms/JsonForm.tsx
- client/packages/common/src/ui/forms/JsonForms/components/Boolean.tsx
- client/packages/common/src/ui/forms/JsonForms/components/index.ts
Partly fixes https://github.com/openmsupply/open-msupply/issues/368 by adding a boolean switch control.
Integer control will be added later when needed (currently not in the current schema)
> 368 more std json forms controls

- client/packages/common/src/hooks/useUrlQuery/useUrlQuery.ts
Closes #397 
The trade off is that the sort history isn't logged as separate navigation - so you cannot sort by column a, then column b, then go 'Back' and show the list sorted by column a.
Without the change you can navigate to the previous sort option, but then to get back to the list view you need to be very, very patient and click many times.
Exhibit A:
> Fix the navigation history

- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/ui/forms/JsonForms/JsonForm.tsx
- client/packages/common/src/ui/forms/JsonForms/components/IdGenerator.tsx
- client/packages/common/src/ui/forms/JsonForms/components/index.ts
- server/service/src/sync/program_schemas/patient_ui_schema.json
Add a configurable control to generate an id. Haven't polished it too much since I like to get some feedback from @richardmoizeau first.
@CarlosNZ would your lib help here?
To test:
- delete existing DB file and resync (or [omsupply-database.zip](https://github.com/openmsupply/open-msupply/files/9245678/omsupply-database.zip) )
- select a patient and fill hand and birth order
- Generate button should no be enabled and you can generate the specialized it
Future work: to generate a program enrolment id we would add access to the store name and to a backend managed program enrolment counter
Closes #433
> Add a configurable ID generator control

- client/packages/common/src/ui/layout/tables/DataTable.tsx
- client/packages/common/src/ui/layout/tables/components/DataRow/DataRow.stories.tsx
- client/packages/common/src/ui/layout/tables/components/DataRow/DataRow.test.tsx
- client/packages/common/src/ui/layout/tables/components/DataRow/DataRow.tsx
- client/packages/common/src/ui/layout/tables/types.ts
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/hooks/usePackSizeController.test.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/utils.test.ts
Closes #462 
Adds tooltip support - and doesn't use that for any existing screens 😁 
You can see the behaviour with the story.. or just wait until this is merged and then develop gets merged into the feature branch 🤷 
I targeted develop so that I could get the functionality merged into both branches. perhaps a bad idea?
It has resulted in an offroad to fix up the tests, so there is some benefit
> tooltip for datarow

- server/graphql/core/src/generic_filters.rs
- server/repository/src/db_diesel/filter_sort_pagination.rs
- server/repository/src/diesel_macros.rs
- server/service/src/document/patient/search.rs
Fixes #484 
Extends the `SimpleStringFilter` in order to support case-insensitive equality comparisons.
Thought about just using a `StringFilter` with `starts_with` and `ends_with` but thought that an actual insensitive equality would be useful elsewhere, so went down that path. Suggestions welcome!
> add insensitive equality filter

- client/packages/common/src/intl/utils/DateUtils.ts
- client/packages/common/src/ui/forms/JsonForms/components/Boolean.tsx
- client/packages/common/src/ui/forms/JsonForms/components/DateOfBirth.tsx
- server/service/src/sync/program_schemas/patient_ui_schema.json
- Use start of the year when selecting DOB by age
- Automatically set the dateOfBirthIsEstimated flag
- Take readonly option into account in the boolean control (unused but kept it in anyway)
Also removed the Patient name title from the patient details forms
Part of #464
> 464 dob improvments

- client/packages/common/src/utils/pricing/PricingUtils.ts
- client/packages/invoices/src/OutboundShipment/api/api.ts
Fixes #455 
though it leaves open the question of why? 
When inserting we supply the percentage as a float, when updating we use a `TaxInput` struct
```
export type InsertOutboundShipmentServiceLineInput = {
...
tax?: InputMaybe<Scalars['Float']>;
...
```
vs.
```
export type UpdateOutboundShipmentServiceLineInput = {
...
tax?: InputMaybe<TaxInput>;
...
```
> Send tax on insert of OS service lines

- client/packages/common/src/authentication/AuthContext.tsx
- client/packages/common/src/authentication/api/api.ts
- client/packages/common/src/intl/locales/en/app.json
- client/packages/common/src/ui/components/modals/AlertModal/AlertModal.tsx
- client/packages/common/src/ui/components/modals/AlertModal/AlertModalProvider.tsx
- client/packages/host/src/components/AuthenticationAlert.tsx
Fixes #498 
A quick mangle of the `permission_type` caused an issue for me
```
ALTER TABLE user_permission  ALTER COLUMN "permission" TYPE text  USING permission::text;
update user_permission 
set "permission" = 'QUERY'
where "permission" ='LOG_QUERY';
```
Gives an error:
```
react_devtools_backend.js:4026 Error: DBError {
msg: "DIESEL_DESERIALIZATION_ERROR",
extra: "\"Unrecognized enum variant: 'QUERY'\"",
}
at handleResponseError (GqlContext.tsx:55:9)
at GqlContext.tsx:99:11
```
Have added a server error type, and am setting that when the `me` query fails with an error. Am also writing the error to console to help with debugging.
> Handle server errors

- server/repository/migrations/postgres/2021-12-10T10-00_number_table/up.sql
- server/repository/migrations/sqlite/2021-12-10T10-00_number_table/up.sql
- server/repository/src/db_diesel/number_row.rs
- server/repository/src/mock/number.rs
- server/service/Cargo.toml
- server/service/src/number.rs
- server/service/src/sync/integration_tests/number.rs
- server/service/src/sync/translation_remote/number.rs
- server/service/src/sync/translation_remote/test_data/mod.rs
- server/service/src/sync/translation_remote/test_data/number.rs
Closes #298
Closes #468 
Closes #442 
- Test for concurrent 'next_number' requests for both insert (First number) and update (subsequent numbers) cases
-  The fix is to do most of the work in the repository layer relying on the 'returning' feature from postgres and sqlite to return the data from any updated or inserted rows.
- Add unique constraint to db
Things get a little funky in the insert case as postgres rolls back the transaction if there is a unique constraint violation without `ON CONFLICT DO NOTHING` which isn't supported in sqlite.
> 132 serial numbers postgres

- client/packages/common/src/intl/locales/en/patients.json
- client/packages/common/src/intl/utils/DateUtils.ts
- client/packages/common/src/types/schema.ts
- client/packages/system/src/Encounter/DetailView/DetailView.tsx
- client/packages/system/src/Encounter/api/api.ts
- client/packages/system/src/Encounter/api/hooks/document/index.ts
- client/packages/system/src/Encounter/api/hooks/document/useEncounter.ts
- client/packages/system/src/Encounter/api/hooks/document/useUpsertEncounter.ts
- client/packages/system/src/Encounter/api/hooks/index.ts
- client/packages/system/src/Encounter/api/operations.generated.ts
- client/packages/system/src/Encounter/api/operations.graphql
- client/packages/system/src/Patient/Encounter/DetailModal.tsx
- client/packages/system/src/Patient/ProgramEnrolment/api/api.ts
- client/packages/system/src/Patient/ProgramEnrolment/api/operations.generated.ts
- client/packages/system/src/Patient/ProgramEnrolment/api/operations.graphql
- server/graphql/document/src/mutations/encounter/insert.rs
- server/graphql/document/src/mutations/encounter/update.rs
- server/graphql/document/src/mutations/program_enrolment/insert.rs
- server/graphql/document/src/mutations/program_enrolment/update.rs
- server/graphql/document/src/queries/encounter.rs
- server/graphql/document/src/queries/patient.rs
- server/graphql/document/src/queries/program_enrolment.rs
- server/graphql/document/src/types/program_enrolment.rs
- server/service/src/document/encounter/mod.rs
- server/service/src/document/encounter/query.rs
- server/service/src/document/program/mod.rs
- server/service/src/document/program/query.rs
Closes #526 
Updated the create modal. 
There's two problems still outstanding:
- the `id` returned by the 'create encounter' api method, is not the id for the encounter. not sure what it is..
- the wrong id is causing problems on the encounter detail view now.. the page re-renders infinitely
I'll revisit those issues when I can. Just popping the changes into a PR now in case you want to use them.
> Create encounter modal

- client/packages/system/src/Encounter/DetailView/DetailView.tsx
- client/packages/system/src/Encounter/api/hooks/document/useEncounter.ts
Fixes #557 
The other API get requests throw an error when the ID is invalid - but the encounter endpoint helpfully does not.
The encounter detail page gets `undefined` for the encounter object, but the query is not in an error state and so will requery and return undefined again. React is unable to use undefined as a stable reference and can't determine that the result is the same, so renders again.
What happens in the other areas of the site is that the query errors, we catch and return an empty object to use as a reference at the cache level and the query is in an error state, so doesn't requery. 
To work around the difference, I've changed the encounter fetch to use a mutation, and am directly calling that only when the requested id changes using an effect. That way the returned data …
> Invalid encounter rerender

- client/packages/common/src/authentication/AuthContext.tsx
- client/packages/common/src/authentication/api/api.ts
- client/packages/common/src/authentication/api/hooks/useUserDetails.ts
- client/packages/common/src/authentication/api/operations.generated.ts
- client/packages/common/src/authentication/api/operations.graphql
- client/packages/common/src/authentication/hooks/index.ts
- client/packages/common/src/authentication/hooks/usePermissionCheck.ts
- client/packages/common/src/authentication/index.ts
- client/packages/common/src/types/schema.ts
- client/packages/common/src/ui/components/navigation/AppNavLink/AppNavLink.tsx
- client/packages/host/src/Admin/Settings.tsx
- client/packages/host/src/components/AppDrawer/AppDrawer.tsx
- client/packages/host/src/components/AuthenticationAlert.tsx
- client/packages/host/src/components/Footer/StoreSelector.tsx
Closes #252 
The changes here
- on login, fetches user permissions and adds to the user object
- on store change does the same
- conditionally hides the Admin nav link if you do not have the `SERVER_ADMIN` permission
- `userA` has `SERVER_ADMIN` permission
- `userB` does not have `SERVER_ADMIN` permission
- `userC` has access to multiple stores. In `storeA` they have `SERVER_ADMIN` permission, in `storeB` they don't
> Make use of user permissions

- client/packages/system/src/Patient/api/hooks/utils/usePatientApi.ts
Fix some api key invalidation problems (enrolment list didn't get updated).
Think the api hooks should somehow be unified in the future, for now I just manually set the correct keys in the existing hook.
Closes #569
> Use correct keys as used in other api

- server/server/src/lib.rs
- server/service/src/processors/mod.rs
closes #575 
These branch may not compile, check out [head PR here](https://github.com/openmsupply/open-msupply/pull/587) for full changes of transfer logic (if you are viewing/testing overall changes). PR changes will be done to that branch, with link to commit in comments they address.
* Added processor driver and triggers
* Added a test initialisation helper to generate service provider and processor_handle 
* Added a couple of new cursors for shipment and requisition transfer
> 575 processor driver

- server/service/src/sync/remote_data_synchroniser.rs
- server/service/src/sync/translations/invoice_line.rs
closes #582 
These branch may not compile, check out [head PR here](https://github.com/openmsupply/open-msupply/pull/587) for full changes of transfer logic (if you are viewing/testing overall changes). PR changes will be done to that branch, with link to commit in comments they address.
* When pushing sync record we now filter change log for records belonging to current site
* When invoice lines are coming from another site, we don't get stock line and location, so foreign key constraint is violated, thus we want to set them to None if it's foreign site record. This logic was added to invoice line translator, and while I was doing that outsourced field name translation to serde.
* Also adjusted some of the translation form om_fields, which are nullable, and don't need special serde …
> 582 update sync to use filtered changelog

- server/service/src/sync/test/integration/transfer/requisition.rs
- server/service/src/sync/test/integration/transfer/shipments.rs
closes #584 
These branch may not compile, check out [head PR here](https://github.com/openmsupply/open-msupply/pull/587) for full changes of transfer logic (if you are viewing/testing overall changes). PR changes will be done to that branch, with link to commit in comments they address.
* Removed empty_data_time_as_option serde translation helper, as it was use on `om_` fields only which are nullable
* Changed create sync site in integration tests to use new 4d mSupply endpoint, which uses internal 4d mSupply unit test helpers that create sync site (there is more that needs to be done then just creating site and linking visibility, `cache` needs to be refreshed in mSupply)
* Created a helper to create and initialise two sync sites for transfer test
* Used `RequisitionTransferTester` and …
> 584 transfer integration tests

- client/packages/common/src/hooks/useConfirmOnLeaving/useConfirmOnLeaving.ts
- client/packages/host/webpack.config.js
Fixes #565 
Ideally I'd use the standard confirmation modal - but due to where the confirmOnLeaving hook is called, the required react context isn't available. So for now have gone full ugly:
the 'reload' version is also a system dialog, which makes the above slightly better:
As an aside, have also fixed the css issue which causes this in the hosted version of the site:
> Add confirmation alert for react router navigation

- client/packages/common/src/ui/components/navigation/Tabs/DetailTabs.tsx
- client/packages/system/src/Encounter/DetailView/Footer.tsx
- client/packages/system/src/Encounter/DetailView/Toolbar.tsx
- client/packages/system/src/Encounter/ListView/ListView.tsx
- client/packages/system/src/Encounter/ListView/columns.ts
- client/packages/system/src/Encounter/index.ts
- client/packages/system/src/Encounter/utils.ts
- client/packages/system/src/Patient/Encounter/ListView.tsx
Closes #548 
Rationalises the encounter list views - with a little fix-up along the way.
- Fixed the start time column, which was showing blank
- Used the same columns in both encounter list views
- Added the current tab to the URL query params, so that refreshing the page or returning to the page will show the correct tab
- Updated the encounter detail view cancel button action; now navigates back rather than always showing the encounter list
- Fixed the encounter detail view toolbar which was no longer showing the details
> 548 encounter list view

- server/service/Cargo.toml
- server/service/src/sync/api/common_records.rs
- server/service/src/sync/api/core.rs
- server/service/src/sync/api/error.rs
- server/service/src/sync/api/get_central_records.rs
- server/service/src/sync/api/get_queued_records.rs
- server/service/src/sync/api/get_site_info.rs
- server/service/src/sync/api/get_site_status.rs
- server/service/src/sync/api/mod.rs
- server/service/src/sync/api/post_initialise.rs
- server/service/src/sync/api/post_queued_records.rs
- server/service/src/sync/central_data_synchroniser.rs
- server/service/src/sync/mod.rs
- server/service/src/sync/remote_data_synchroniser.rs
- server/service/src/sync/site_info.rs
- server/service/src/sync/synchroniser.rs
- server/service/src/sync/test/integration/central_server_configurations.rs
- server/service/src/sync/test/integration/errors.rs
- server/util/Cargo.toml
- server/util/src/error.rs
- server/util/src/lib.rs
closes #659 (this is to link the issue, there is a series of PR, as described in the issue)
[HEAD PR LINK](https://github.com/openmsupply/open-msupply/pull/679)
Tidy up thiserror derives/annotation
* Previously was constantly stringifying source error, this is not needed since we can print source errors automatically (anyhow actually does this, but also added generic error formatter), see comment in self review
* Flatten Mapped error straight into sync api error
* Wanted url in SyncApiError, thus made it a wrapper around SyncApiErrorVariant
* Adde SyncErrorCodeV5 to map to expected central server error (this can be tested in the future
Used `from` and `?` to make sync code more readable (this is a pattern we've gone away from, instead using `map_err`, I would like to reinstate it, might …
> 659.1 sync api error improvements

- client/packages/common/src/ui/forms/JsonForms/JsonForm.tsx
- client/packages/common/src/ui/forms/JsonForms/components/Text.tsx
- server/service/src/sync/init_programs_data.rs
- server/service/src/sync/program_schemas/hiv_care_encounter.json
- server/service/src/sync/program_schemas/hiv_care_encounter_ui_schema.json
Closes #645 
Have converted the four properties to be string rather than numeric in order to allow for the customised formatting.
Then had to extend the text control, so that the UI Schema could supply the required width ( otherwise the numeric inputs were too narrow, the text ones too wide 🙄 )
Then had to support custom errors, to override the `must match pattern [regex]` format that ajv outputs. This overriding isn't the best - tried `ajv-errors` and various other options, but nothing was working. Unfortunately it seems that this json forms package doesn't support the options available elsewhere.
Have used a per-keyword mapping for errors, so there is some flexibility.
Unfortunately the programschemas repo is using a generator which doesn't support custom annotations, so these errors …
> Support custom errors, update the format of some physical exam elements

- server/cli/src/refresh_dates.rs
- server/repository/migrations/postgres/2021-12-25T10-00_item_stats/up.sql
- server/repository/migrations/sqlite/2021-12-25T10-00_item_stats/up.sql
- server/repository/src/db_diesel/consumption.rs
- server/repository/src/db_diesel/stock_movement.rs
- server/service/src/item_stats.rs
closes #684 
It turns out that when we switched to decimals for number of packs the aggregate views also changed to use decimals, but db diesel definitions were still expecting integers (so tests were failing in postgres and itemStats query wasn't working)
* For postgres changed to cast `quantity` to BigInt (since number_of_pack * pack_size should always be whole pack anyways, if it isn't it's ok to round)
* When I was doing above I saw a lot of duplication so created `invoice_line_stock_movement` view, which is used in other view (shouldn't have any performance drawbacks since views are just aliases for select statements)
* Used i64 vs i32 in in diesel schema (had to actually downcast one to i32 from i64, so decided to change and use bigint i64 everywhere)
* Fixed postgres test in …
> 684 fix item stats with postgres feature

- client/packages/common/src/ui/components/inputs/CurrencyInput/CurrencyInput.tsx
- client/packages/common/src/ui/layout/tables/components/Cells/CurrencyInputCell/CurrencyInputCell.tsx
- client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NonNegativeDecimalCell.tsx
Fixes #706 
A few issues with the currency input component. I've removed the buffering, as I think it is not required from my reading of the component. The `defaultValue` prop provides what the buffer was. 
The primary issue was the conversion to a `Number` which meant that if you type `0` then `.` the value is set to `0` because the string `0.` is converted to a number. Then if you type `5` you get a value for the input of `5` rather than the `0.5` that you may have wanted.
Have tested using French and English settings, and checked the storybook and the stocktake usage. all working now.
> currency input issues

- server/server/src/lib.rs
Fixes #749 
The settings are now required by `static_files::files` but were not added to the request, which causes the handler to throw the error noted in the issue. Since the settings are passed in to the `start_server` I've just cloned them and added in to the app data.
> Add settings to actix server

- client/packages/common/src/types/schema.ts
- client/packages/host/src/CommandK.tsx
- client/packages/host/src/components/AppDrawer/SyncNavLink.tsx
- client/packages/host/src/components/Sync/Sync.tsx
- client/packages/system/src/Name/api/api.ts
- server/graphql/general/src/queries/names.rs
- server/graphql/general/src/queries/tests/names.rs
- server/graphql/types/src/types/name.rs
- server/repository/src/db_diesel/name.rs
- server/schema.graphql
Closes #756 
The outbound shipments allow zero stock quantity lines, so that you can specify placeholder rows. So that one should remain. Couldn't repro the tab issue - for me, the `Details` is underlined.
Also have removed two console errors that have popped in:
```Failed prop type: Invalid prop `children` supplied to `ForwardRef(Tooltip)`. Expected an element that can hold a ref. Did you accidentally use a plain function component for an element instead?```
and another one about invalid DOM nesting
> Testing feedback issues #2

- client/packages/common/src/intl/context/IntlContext.tsx
- client/packages/common/src/intl/context/browserLanguageDetector.ts
Fixes #754 
The language detector allows caching of the selected language by i18next. Removing the detector also removes the caching, and the page is reloaded on language change, to allow for LTR <> RTL changes.
> Cache selected language

- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/ui/forms/JsonForms/components/Text.tsx
- server/service/src/sync/program_schemas/hiv_care_encounter.json
- server/service/src/sync/program_schemas/patient.json
Part of #655 
Don't show regex to the user but show some examples (when available)
> Use schema examples if there is a pattern error

- build/windows/omsupply_server.suf
Fixes #746 
A global variable was being set on initialisation and not being updated to reflect the user choice ( when run as a new install rather than an upgrade )
> Postgres installer

- client/packages/common/src/ui/forms/JsonForms/components/Text.tsx
Part of #655 
Width was missing in the option definition and the examples array was validated as non-optional.
> Fix Text option type and type validation

- server/service/src/invoice/outbound_shipment/update_name/generate.rs
Closes #806
Linked invoice id wasn't being cleared so invoices were being duped when processors are fired
> Clear linked invoice id when changing name

- server/graphql/programs/src/mutations/delete_document.rs
- server/graphql/programs/src/mutations/encounter/insert.rs
- server/graphql/programs/src/mutations/encounter/update.rs
- server/graphql/programs/src/mutations/insert_document_registry.rs
- server/graphql/programs/src/mutations/patient/insert.rs
- server/graphql/programs/src/mutations/patient/update.rs
- server/graphql/programs/src/mutations/program_enrolment/insert.rs
- server/graphql/programs/src/mutations/program_enrolment/update.rs
- server/graphql/programs/src/mutations/undelete_document.rs
- server/graphql/programs/src/mutations/update_document.rs
- server/graphql/programs/src/queries/document.rs
- server/graphql/programs/src/queries/document_history.rs
- server/graphql/programs/src/queries/document_registry.rs
- server/graphql/programs/src/queries/encounter.rs
- server/graphql/programs/src/queries/encounter_fields.rs
- server/graphql/programs/src/queries/patient.rs
- server/graphql/programs/src/queries/patient_search.rs
- server/graphql/programs/src/queries/program_enrolment.rs
- server/graphql/programs/src/queries/program_event.rs
- server/service/src/auth.rs
The mapping of user permission to service capabilities is done in a single place now. This de-couples user permissions from what can be done in the service.
> Extend PermissionDSL to be able to describe dynamic permissions

- client/packages/common/src/ui/forms/JsonForms/JsonForm.tsx
- client/packages/common/src/ui/forms/JsonForms/components/Autocomplete.tsx
- client/packages/common/src/ui/forms/JsonForms/components/ConditionalSelect.tsx
- client/packages/common/src/ui/forms/JsonForms/components/Text.tsx
- client/packages/common/src/ui/forms/JsonForms/components/index.ts
- client/packages/system/src/Patient/JsonForms/useJsonForms.tsx
- client/packages/system/src/Patient/PatientView/PatientView.tsx
- server/service/src/sync/program_schemas/patient_ui_schema.json
Part of #655
- Adds an Autocomplete control
- Adds a ConditionalSelect control
- Use these controls to select province and district
The Autocomplete component supports a "freeStyle" mode which allows users to select from a dropdown as well as entering some text. This made this component a bit more complicated than expected. The build in freeSolo option worked but the onChange callback wasn't called when changing focus, i.e. the form data wasn't updated after entering the text. Furthermore, you have to handle a `string|DisplayOption` type when the input changed since the freeSolo option is always a string...
I tried to quickly write a test for it but had some problem to drill down to the right components to do the actions. Any experience with it? otherwise I will try again later.
> 655 conditional text input

- .github/workflows/client-bundle-size-diff.yaml
- client/package.json
- client/packages/host/package.json
- client/packages/host/webpack.config.js
Fixes #836 
HMR builds with webpack in develop mode, which was running the bundle analyzer due to our `!!isProduction` config.
Have shifted to an explicit build script
> Disable bundleAnalyzerPlugin

- server/server/src/lib.rs
- server/service/src/report/html_printing.rs
- server/service/src/static_files.rs
Two issues:
- headless chrome requires an absolute path (at least here)
- the server Data settings are needed by the static file service
> Fix cli report printing

- client/packages/common/src/intl/currency/currency.ts
- client/packages/common/src/intl/locales/es/app.json
- client/packages/common/src/intl/locales/es/common.json
- client/packages/common/src/intl/locales/tet/app.json
- client/packages/common/src/intl/locales/tet/common.json
- client/packages/common/src/intl/utils/DateUtils.ts
- client/packages/common/src/intl/utils/IntlUtils.ts
- client/packages/common/src/utils/testing/testing.tsx
- client/packages/host/src/components/LanguageMenu.tsx
Fixes #877 
Adds Tetum and Spanish options to the menu. 
Have added a couple of example translations to test that it is working.
> Add options to language menu

- client/packages/common/src/ui/forms/JsonForms/components/DateTime.tsx
- server/service/src/sync/program_schemas/hiv_care_program.json
- server/service/src/sync/program_schemas/hiv_care_program_ui_schema.json
- server/service/src/sync/program_schemas/hiv_testing_program_ui_schema.json
Fix #835 
Just allows the "DateTime" widget to be used but only show the "Date" part to the user. By default, the saved date will be the current date/time, but if a date is selected it will store the time component as "midnight" on the selected date (because any further precision would be misleading).
Ideally, we'd just use the "Date" widget most of the time, but this is for cases where we want to capture the full date time but without burdening the user with a "time" selector (such as the "Enrolment Date" option in Program enrolment form)
Note -- there is some Prettier auto-formatting changes in the JSON here which we probably don't want. We should probably co-ordinate our configurations to avoid this.
> #835 Implement "Date only" option for "DateTime" widget

- client/packages/common/src/ui/components/inputs/CurrencyInput/CurrencyInput.tsx
- client/packages/common/src/ui/components/inputs/Select/Select.tsx
- client/packages/common/src/ui/components/inputs/TextInput/BasicTextInput.tsx
Closes #861 
Will need to update programs with develop again after this is merged.
- Added blue underline when text + select components are in focus
- Also changed the currency input to have blue underline on focus or grey underline on hover
- Disabled underline if there's an error, so that the focus underline doesn't overlap with error border
> #861 Highlight current Text box

- server/service/src/sync/sync_serde.rs
- server/service/src/sync/test/test_data/invoice.rs
- server/service/src/sync/test/test_data/requisition.rs
- server/service/src/sync/test/test_data/requisition_line.rs
- server/service/src/sync/test/test_data/stocktake.rs
- server/service/src/sync/translations/activity_log.rs
- server/service/src/sync/translations/invoice.rs
- server/service/src/sync/translations/invoice_line.rs
- server/service/src/sync/translations/name.rs
- server/service/src/sync/translations/report.rs
- server/service/src/sync/translations/requisition.rs
- server/service/src/sync/translations/requisition_line.rs
- server/service/src/sync/translations/stock_line.rs
- server/service/src/sync/translations/stocktake.rs
- server/service/src/sync/translations/stocktake_line.rs
Fixes #818
- `empty_str_as_option_generic` new deserializer. Handles empty string values for generic type. `Option<T>` I think you could say.
- Fixes all all the `om_*` fields of type `Option<NaiveDateTime>` when the JSON value is `""`
- Fixes all all the `om_*` fields of type `Option<SomeEnum>` when the JSON value is `""`. E.g `om_status` and `om_type`.
> 818 sync translation handle empty datetime strings

- client/packages/system/src/Patient/Components/EncounterSearchInput/EncounterSearchInput.tsx
- client/packages/system/src/Program/Components/ProgramOptionRenderer.tsx
Fix #834 
Very quick fix -- just remove the UI element and make the remaining "Checked" column centered, as discussed in [this comment](https://github.com/openmsupply/open-msupply/issues/834#issuecomment-1326958182).
Is that the only place where this appears?
> 834 Remove code from Program Selector UI

- client/packages/programs/src/JsonForms/components/IdGenerator.tsx
- server/service/src/sync/program_schemas/patient.json
- server/service/src/sync/program_schemas/patient_ui_schema.json
Replaces PR #955
Closes #655 
After [rethinking that one](https://github.com/openmsupply/open-msupply/pull/944#discussion_r1050164902), it seems to make more sense to have the ID generator handle a numeric input part rather than changing the Number control to output strings.
Which is actually a much simpler change and keeps each control more focused on what it should be doing.
> 655 id generator can handle numeric values

- client/packages/common/src/ui/components/navigation/Tabs/DetailTabs.tsx
Closes #777
Uses solution suggested by @mark-prins to trigger the underline indicator to recalculate its position.
> #777 Tab indicator correctly moves when Details panel is opened

- server/.gitignore
- server/report_builder/README.md
- server/report_builder/src/build.rs
- server/report_builder/src/cli.rs
- server/report_builder/src/lib.rs
- server/report_builder/src/print.rs
Improves some cli options to be more flexible where report_builder outputs are stored.
This was required to make some helper scripts for building/testing reports in the private report repo: https://github.com/openmsupply/open-msupply-reports 
Please follow instructions in the open-msupply-reports repo for testing. Feedback for the new repo welcome!
Closes #956
> 956 report cli improvements

- server/graphql/general/src/queries/tests/activity_log.rs
- server/graphql/types/src/types/activity_log.rs
Closes #910 
Seems like this is mostly related to the Activity log -- the back-end type was a NaiveDateTime rather than a UTC timestamp. 
I've made the small change to the back-end and it's showing correctly in the "Outbound shipment" UI as per the original screenshot.
@DhanyaHerath is there any other places specifically this could still be wrong that I should check?
> #910 Timestamp fixes

- server/README.md
- server/graphql/lib.rs
The main culprit was the async_graphql::extensionsLogger, I removed it and the custom ResponseLogger. I first just wanted to comment it out but it would be a little bit messy because the comment would needed at multiple places. @andreievg do you think it is worth it to put some more afford in to make it easy to get it back when needed?
Closes #841
> 841 remove graphql request logging

- client/packages/programs/src/JsonForms/common/components/Text.tsx
- server/service/src/sync/program_schemas/patient.json
- server/service/src/sync/program_schemas/patient_ui_schema.json
First part of #838.
This just adds functionality for multi-line text input fields. I'll add the more substantial "Notes" component next, which will be a wrapper for existing components including this one.
Turns out we don't need to make a new component for multi-line -- it's easy just to pass the "multiline" and "rows" properties to the existing `DetailInputWithLabelRow` component.
> #838(1) Multi-line text input support

- server/service/src/sync/sync_buffer.rs
- server/service/src/sync/test/integration/README.MD
- server/service/src/sync/test/integration/remote/activity_log.rs
- server/service/src/sync/test/integration/remote/invoice.rs
- server/service/src/sync/test/integration/remote/mod.rs
Fixes #977 
Adds a couple of lines to fix a compilation issue, and tidies a few :nits
Requires [the associated mSupply PR](https://github.com/sussol/msupply/pull/12016) to be in place before testing
> Activity log change

- client/packages/common/src/ui/components/inputs/CurrencyInput/CurrencyInput.tsx
- client/packages/common/src/ui/components/inputs/TextInput/BasicTextInput.tsx
- client/packages/common/src/ui/components/inputs/TextInput/numeric/NumericTextInput.tsx
Fix #893.
Initially tried adding this to just the "NumericTextInput" component, but then thought that it probably makes sense to auto-select text for all input fields. Does this seem reasonable to everyone else? @mark-prins @Chris-Petty
> #893 Select text on input focus

- client/packages/electron/src/electron.ts
Closes #1001 
And, yes, changed some spellings which the vs code extension picked up.
> Desktop: filter for ipv4 addresses

- client/packages/common/src/styles/theme.ts
- client/packages/common/src/ui/components/domain/Dashboard/StatsPanel.tsx
- client/packages/common/src/ui/components/navigation/AppNavLink/AppNavLink.tsx
- client/packages/common/src/ui/components/navigation/AppNavSection.tsx
- client/packages/common/src/ui/components/navigation/ExternalNavLink.tsx
- client/packages/common/src/ui/components/navigation/index.ts
- client/packages/common/src/ui/icons/ExternalLink.tsx
- client/packages/common/src/ui/icons/Icon.stories.tsx
- client/packages/common/src/ui/icons/index.ts
- client/packages/common/src/ui/layout/tables/components/DataRow/DataRow.tsx
- client/packages/host/src/components/AppDrawer/AppDrawer.tsx
- client/packages/host/src/components/Navigation/CatalogueNav.tsx
- client/packages/host/src/components/Navigation/DistributionNav.tsx
- client/packages/host/src/components/Navigation/InventoryNav.tsx
- client/packages/host/src/components/Navigation/ReplenishmentNav.tsx
Fixes #856 for general items. There's a couple to address in the features branch too.
**Menu**
**Dashboard**
**tables**
**Site**
- The footer text is jammed together ( storename username )
**Other components**
- Autocomplete - highlight the search terms when filtering, perhaps bold the search characters?
- Date picker - is the selected date colour the primary? it doesn't look right
> UI review Items part I

- client/packages/common/src/types/schema.ts
- client/packages/system/src/Item/api/hooks/useStockItemsWithStats/useStockItemsWithStats.tsx
- client/packages/system/src/Log/api/operations.generated.ts
- server/graphql/general/src/queries/names.rs
- server/repository/src/migrations/v1_01_01/mod.rs
- server/service/src/sync/test/test_data/name_store_join.rs
- server/service/src/sync/translations/name_store_join.rs
Fixes #986 
Have added a filter to the name list query, when `is_supplier` or `is_customer` is set in the filter. If however, someone queries for a specific id, then no filter is applied - I don't want to mess with filter functionality.
The situation requires a specific set up: in my test db ( same as demo site ) the store Kopu is a supplier and customer of itself, and that shows as an entry in `name_store_join` which has the store linked to itself. This is the same in mSupply - so wouldn't be a translation / sync error.
> Filter current store from customer & supplier lists

- client/packages/common/src/styles/theme.ts
- client/packages/common/src/ui/components/navigation/AppNavLink/AppNavLink.tsx
- client/packages/common/src/ui/components/navigation/AppNavSection.tsx
- client/packages/host/src/components/AppDrawer/AppDrawer.tsx
- client/packages/host/src/components/Navigation/CatalogueNav.tsx
Closes #1018 
Changes as requested. Not sold on the use of the primary colour on the selected parent, but see what you think 😃.
The highlights are back to the white, which was in, and changed in the previous PR following feedback. Once again, see what you think.
Samples:
Dashboard selected:
Dashboard selected: Customers hovered:
Outbound selected, Requisitions hovered:
> Update navigation style

- server/service/src/item.rs
closes #1040 
Made an android [built](https://drive.google.com/file/d/1CtYhwR0JXSzIrjPHy6o-DecV14_3fxxK/view?usp=share_link), still not sure why in built version served through remote server we not getting `toast` error but just `loading` display
> Update back end pagination of item to match front end

- server/service/src/sync/test/integration/errors.rs
- server/service/src/sync/test/integration/mod.rs
- server/service/src/sync/test/integration/remote/invoice.rs
- server/service/src/sync/test/integration/remote/mod.rs
- server/service/src/sync/test/integration/remote/stocktake.rs
- server/service/src/sync/translations/invoice.rs
closes #1045 
Sync settings need to be in database when syncing, added in both types of integration tests
Tax field is not nullable in mSupply, for now not testing `None` variant for tax. (this potentially affects UI if `null` on tax is shown differently to 0, but not much can be done unless new om_tax field is added to transact)
Added inventory adjustments to tests, which also required `name` to be inventory adjustments (otherwise invoice translation fails as it is quite strict on types, i.e. invoices with inventory adjustment name will only match `sc` or `si` type). This required knowing what inventory adjustment name is, and since test data is generated before sync, have to patch test data for InventoryAddition/Reduction after first sync (when inventory adjustment name is known)
Did a …
> 1045 fix sync integration tests

- client/packages/programs/src/JsonForms/common/components/Array/common.tsx
Fix for #1015 
This causes a config error for a string array (if I don't miss anything)...
> Make the array `detail` option optional. Not needed for enum arrays.

- server/server/Cargo.toml
- server/server/src/lib.rs
Tested on windows:
- `cargo build` works now
- `cargo build --features discovery` keeps fails
> Add a discovery flag (workarround for windows build problems)

- client/packages/common/src/types/schema.ts
- client/packages/inventory/src/Stocktake/DetailView/AppBarButtons.tsx
- client/packages/invoices/src/InboundShipment/DetailView/AppBarButtons.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/AppBarButtons.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/AppBarButtons/AppBarButtons.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/AppBarButtons/AppBarButtons.tsx
- client/packages/system/src/Patient/PatientView/AppBarButtons.tsx
- client/packages/system/src/Report/api/api.ts
- client/packages/system/src/Report/api/hooks/document/useReports.ts
- client/packages/system/src/Report/api/hooks/utils/usePrintReport.ts
- client/packages/system/src/Report/api/operations.generated.ts
- client/packages/system/src/Report/api/operations.graphql
- client/packages/system/src/Report/components/ReportArgumentsModal.tsx
- client/packages/system/src/Report/components/ReportSelector.tsx
- server/report_builder/arguments.json
Adds the UI part for report arguments.
- Show a JSONForms modal to retrieve report arguments (if the reports requires some)
- Print the report with the arguments
- Testing: there is demo report (select a patient -> print) that takes an argument. The report query uses this argument...
TODOs:
- Move common JSONForms control out of the programs packages.
- Move program patient report to make use of the secondary context
Closes #1027 
Closes #946
> 1027 report arguments UI

- server/graphql/general/src/queries/names.rs
- server/graphql/general/src/queries/tests/names.rs
- server/graphql/programs/src/queries/patient.rs
- server/repository/src/db_diesel/item.rs
- server/repository/src/db_diesel/name.rs
- server/repository/src/db_diesel/program_enrolment_row.rs
- server/repository/src/diesel_macros.rs
- server/repository/src/mock/test_name_query.rs
- server/service/src/programs/patient/query.rs
Part of #1014 
- Add an `identifier` filter to search names / patient by (`code` OR `national_health_number` OR `program_patient_id`)
- Make `apply_simple_string_or_filter!` more low level. Previously it operated on two table columns. Now it just works like `apply_simple_string_filter!` only with `or_filter`, `apply_simple_string_or_filter` is than used in the repo to have ORs for three table columns for the identifier filter.
- ORs need to be applied before AND queries. A test and fix has been applied for the `item` table `code_or_name` filter.
Note, with the dynamic diesel `or_filter` and `filter` method you can't actually do arbitrary AND / OR filters (I previously thought you can). For example: (a OR b) AND (c OR d) can't be expressed; …
> 1014 patient search query

- client/packages/common/src/intl/locales/en/distribution.json
- client/packages/common/src/ui/components/modals/AlertModal/AlertModalProvider.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/AppBarButtons/CreateShipmentButton.tsx
Fixes #1021 
The message was correct and misleading at the same time.
Have created a new message which explains the situation when all supply quantity values are zero, and have updated the wording of the previous message.
Have also fixed the onOk handler, so that you don't get redirected to login
> Update Create Shipment message

- client/packages/common/src/types/schema.ts
- client/packages/dashboard/src/api/api.ts
- client/packages/dashboard/src/api/hooks/index.ts
- client/packages/dashboard/src/api/hooks/statistics/index.ts
- client/packages/dashboard/src/api/hooks/statistics/useItemCounts.ts
- client/packages/dashboard/src/api/operations.generated.ts
- client/packages/dashboard/src/api/operations.graphql
- client/packages/dashboard/src/widgets/StockWidget.tsx
- client/packages/system/src/Log/api/operations.generated.ts
- server/graphql/general/src/lib.rs
- server/graphql/general/src/queries/item_counts.rs
- server/graphql/general/src/queries/mod.rs
- server/repository/src/db_diesel/item.rs
- server/repository/src/db_diesel/name.rs
- server/repository/src/test_db/mod.rs
- server/service/src/dashboard/item_count.rs
- server/service/src/dashboard/mod.rs
- server/service/src/service_provider.rs
Closes #927 
Adds a query for the three item count values and updates f/e to use the query instead of iterating over all items manually.
There's one change to functionality - in the current version we are including in the low stock total items which have `0` AMC but have stock on hand. This was useful when data was still in a test state, but now I would expect consumption to be accurate and AMC populated. Correct me if wrong here.
> Create item counts dashboard query

- server/repository/src/db_diesel/invoice_line_row.rs
- server/service/src/invoice/inbound_shipment/update/mod.rs
Closes #1049 
- Update tax and total_after_tax separately from whole row update
- Added tests to ensure duplicate stock lines don't get created when tax has been changed on invoice lines
> 1049 duplicate stock lines created when received in an inbound shipment

- client/packages/android/app/src/main/assets/capacitor.config.json
- client/packages/android/capacitor.config.ts
Fixes #997 
This resolves the issue for me - the capacitor configuration option `allowNavigation` defines which urls are handled within the webview. The wildcard tells capacitor to open all links in the webview, when we only want the bundle to load. Internal navigation should be handled by react router once the bundle is loaded.
Have tested loading local and remote server bundles and they load fine, with external links ( e.g. the docs ) loading in chrome rather than the app.
> Android external links

- server/service/src/stocktake/update.rs
Closes #937 
Location, batch, pack size, cost and sell prices per pack for stock lines can now be updated in stocktake
> Update information for stock line when updated in stocktake

- client/packages/common/src/intl/locales/en/patients.json
- client/packages/system/src/Encounter/DetailView/Toolbar.tsx
- client/packages/system/src/Patient/Encounter/CreateEncounterModal.tsx
- server/service/src/sync/init_programs_data.rs
- server/service/src/sync/program_schemas/hiv_care_encounter.json
- server/service/src/sync/program_schemas/hiv_care_program.json
- server/service/src/sync/program_schemas/hiv_care_program_ui_schema.json
- server/service/src/sync/program_schemas/hiv_testing_encounter.json
Just putting this in Draft for now cos there's a couple of things not working properly (doesn't currently compile in front-end).
@clemens-msupply Could use your help figuring out how to add the "clinician" property to the "Encounter" type. You'll notice in "CreateEncounterModal" that there is an error with `draft?.clinician` as property is not defined in "EncounterFragment", but this comes from database types as far as I could tell.
Also -- I'm currently just saving the whole "clinician" object in the Encounter document, but should it also be at the "root" level of the Encounter data?
Currently this is very basic -- it just displays a "clinician" drop-down on the Encounter create modal, and then displays that value on the Encounter details page. Should this be editable on the Details …
> #926 Practitioner input

- client/packages/invoices/src/OutboundShipment/DetailView/ContentArea.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/columns.ts
Closes #1120 
Outbound shipment lines return correct unit quantity now when grouped by item + show location, item unit and sell price on expansion
> #1120 If you group rows by item, the unit quantity of each batch shows the total for item rather than the batch

- decisions/store-preferences.md
closes #1087 
Something that I wanted to add to KDD but didn't. In general I think we should be very conservative with the use of dynamic structures, like key value store, I think they add a vector for future confusion and errors and can easily be misused. I think we should aim to minimise risk of code changes made b new and less experienced developers. 
For me an example of where key value store should not have been used is SyncSettings, I think it should have been a new one row table, this would completely remove the need to map structures like we are doing below, and would make code more readable and extendable: 
https://github.com/openmsupply/open-msupply/blob/3bd37669303668ba6907f49c21eae4b7ad7970a0/server/service/src/settings_service.rs#L32-L99
> Add KDD for store preferences

- server/service/src/sync/test/test_data/name_store_join.rs
- server/service/src/sync/translations/name_store_join.rs
Fixes #1085 
Pretty much does what it says on the tin.
> Delete inactive name store joins

- server/Cargo.lock
- server/README.md
- server/server/Cargo.toml
- server/server/src/discovery.rs
- server/server/src/lib.rs
Fixes #1058 
Implemented dns-sd using astro and removed the `discovery` feature.
Astro was throwing this error at times on mac:
```
2023-02-06 18:10:41.420171 ERROR astro_dnssd::os::apple::register - Error processing: -65563, exiting thread  /Users/m2/.cargo/registry/src/github.com-1ecc6299db9ec823/astro-dnssd-0.3.2/src/os/apple/register.rs:156
2023-02-06 18:10:41.420497 ERROR server::discovery - Error registering discovery: ServiceError(-65563)  server/src/discovery.rs:32
```
I've implement `target_os` specific versions. Didn't find the cause of the above error - and though we aren't specifically using macOS servers.. might as well have it working just in case.
> Enable discovery in windows server

- client/packages/common/src/ui/forms/Detail/InputWithLabelRow.tsx
- client/packages/programs/src/JsonForms/common/components/Boolean.tsx
- client/packages/programs/src/JsonForms/common/components/Number.tsx
- client/packages/programs/src/JsonForms/common/components/Text.tsx
- client/packages/programs/src/JsonForms/components/DateOfBirth.tsx
- client/packages/programs/src/JsonForms/components/IdGenerator.tsx
Couldn't stand the misalignment anymore so at least fixed some issues...
@mark-prins could you please check my change to the common InputWithLabelRow?
> Use same margins and gaps for JsonForms components

- server/cli/src/cli.rs
- server/service/src/sync/synchroniser.rs
- server/service/src/sync/test/pull_and_push.rs
- server/service/src/sync/translation_and_integration.rs
closes: #976 
Implementation as per issue description, remove transaction from initialisation integration
Easy way to test would be to run the following on your data file (will add lots of invalid records, causing inner transactions to be rolled back). Try initialisation on this branch (should take less then a minute to do `integration` step. Try initialisation on develop (it would take more then a minute, quite a lot more)
```
For (i; 1; 50000)
$item:=ds.item.new()
$item.ID:=UUID_generate
$item.item_name:=UUID_generate
$item.code:=UUID_generate
$item.type_of:="general"
$item.unit_ID:="invalid"
$item.save()
End for 
```
> 976 remove transaction from sync initialisation integration

- server/repository/src/database_settings.rs
- server/service/src/processors/transfer/shipment/test.rs
- server/service/src/sync/sync_buffer.rs
- server/service/src/sync/test/integration/central/inventory_adjustment_reason.rs
- server/service/src/sync/test/integration/central/mod.rs
- server/service/src/sync/test/integration/central/test.rs
- server/service/src/sync/test/integration/remote/invoice.rs
- server/service/src/sync/test/integration/remote/stock_line.rs
- server/service/src/sync/test/integration/remote/stocktake.rs
- server/service/src/sync/test/integration/remote/test.rs
- server/service/src/sync/test/test_data/stock_line.rs
- server/service/src/sync/translations/stock_line.rs
closes: #976 
Further work to fix integration tests, was just going to fix compilation errors, but saw quite a few places where sync could break:
* If stockline name_id is empty 
* Any invoice lines with optionID (since we were integration inventory adjustment reason after invoice line
Also found that stocktake tests were not being run and found.
Added database name to console log, needed this to connect to correct test database (to debug test failure issue)
> 976 2 integration tests

- client/packages/requisitions/src/RequestRequisition/DetailView/AppBarButtons/UseSuggestedQuantityButton.tsx
Closes #1138 
Disable `Use Suggested Quantities` button if status is sent
> #1138 Can still click 'Use Suggested Quantities' button after an Internal Order has been sent

- client/packages/common/src/intl/locales/en/distribution.json
- client/packages/requisitions/src/ResponseRequisition/DetailView/AppBarButtons/CreateShipmentButton.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/Toolbar.tsx
Closes #1078 
- Disabled `Create Shipment` button on Requisitions if requisition is finalised.
- Added warning message if no outbound shipment has been created for requisition
Users can create multiple shipments from one requisition so should the warning message always be on...? 🤔
> #1078 Can try to create an outbound shipment from a customer requisition when finalised (+ UI is a little confusing) 

- client/packages/common/src/intl/locales/en/inventory.json
- client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEdit.tsx
- server/graphql/stocktake_line/src/mutations/insert.rs
- server/graphql/stocktake_line/src/mutations/update.rs
- server/repository/src/db_diesel/invoice_line.rs
- server/service/src/stocktake_line/insert.rs
- server/service/src/stocktake_line/update.rs
- server/service/src/stocktake_line/validate.rs
Closes #1147
- Throw error for stock line if counted number of packs is less than number of packs in new outbound shipments 
- Return simple error message in UI
- Create an outbound shipment, and issue stock (leaving only 1). Can follow https://github.com/openmsupply/open-msupply/issues/1147 until step two. 
- Do a stocktake. counted number of packs > available stock on hand
- See error
> 1147 negative available number of packs 

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
- To speed up dev processes:  
- The person making the PR is the expert on their own code. They know a lot more about it than the person reviewing, and transferring that knowledge helps speed up the review process. 
- Having a template means you don't have to think about what details you need to add - it's there for you to check. 
- We're open source - having a template for outside contributors will help get the details we need without multiple back and forths. 
References: https://www.awesomecodereviews.com/pull-request-template/
* A PR template
* A new feature issue template 
* A bug issue template
> Add GitHub pr and issue templates

- client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
- server/service/src/invoice_line/inbound_shipment_line/generate.rs
- server/service/src/invoice_line/inbound_shipment_line/insert/generate.rs
- server/service/src/invoice_line/inbound_shipment_line/insert/mod.rs
- server/service/src/invoice_line/inbound_shipment_line/update/generate.rs
- server/service/src/invoice_line/inbound_shipment_line/update/mod.rs
- server/service/src/processors/transfer/shipment/common.rs
- server/service/src/processors/transfer/shipment/create_inbound_shipment.rs
- server/service/src/processors/transfer/shipment/update_inbound_shipment.rs
Closes #973
- Inbound shipment lines will recalculate relevant fields to be in packs of one 
- Relevant fields will also be recalculated when an outbound shipment is sent to a store with pack to one preference turned on.
> 973 pack to one preference

- server/service/src/processors/transfer/requisition/create_response_requisition.rs
- server/service/src/processors/transfer/requisition/test.rs
Fixes #1142 
Rename response requisition to internal order in transfer comment
> #1142 Response requisition auto generated comment

- client/packages/common/src/intl/locales/en/app.json
- client/packages/common/src/intl/utils/IntlUtils.ts
- client/packages/common/src/types/schema.ts
- client/packages/host/src/components/Footer/Footer.tsx
- client/packages/host/src/components/Footer/LanguageSelector.tsx
- client/packages/host/src/components/LanguageMenu.tsx
- server/graphql/types/src/types/user.rs
- server/repository/migrations/postgres/2022-10-27T09-15_v103/up.sql
- server/repository/src/db_diesel/user_row.rs
- server/repository/src/migrations/v1_01_03/mod.rs
- server/service/src/login.rs
Fixes #1164 
Adds the link between central server and the site - if a user has Tetum as their language in mSupply and they login to omSupply, the site now sets the language correctly.
An additional task, which Chris requested in the comments, was to easily select language; and to select language when you are not a site administrator.
To that end.. there's now a language icon and name shown beside the username:
The tooltip shows what you can do:
Which is this:
You will need to use the [#12353-Add-Tetum-language](https://github.com/sussol/msupply/tree/%2312353-Add-Tetum-language) branch in order to test the mSupply integration
Once that is configured, change a user to be Tetum and login as that user.
The omSupply site will show in Tetum and the language shown in the footer should also show …
> Tetum language support part II

- client/packages/common/src/types/schema.ts
- server/graphql/programs/src/mutations/encounter/insert.rs
- server/graphql/programs/src/mutations/encounter/update.rs
- server/graphql/programs/src/queries/encounter.rs
- server/graphql/programs/src/types/encounter.rs
- server/graphql/programs/src/types/program_enrolment.rs
- server/repository/migrations/postgres/2022-06-07T16-00_create_program_enrolment_table/up.sql
- server/repository/migrations/postgres/2022-06-07T17-00_create_encounter_table/up.sql
- server/repository/migrations/sqlite/2022-06-07T16-00_create_program_enrolment_table/up.sql
- server/repository/migrations/sqlite/2022-06-07T17-00_create_encounter_table/up.sql
- server/repository/src/db_diesel/document.rs
- server/repository/src/db_diesel/encounter.rs
- server/repository/src/db_diesel/encounter_row.rs
- server/repository/src/db_diesel/name.rs
- server/repository/src/db_diesel/program_enrolment_row.rs
- server/service/src/programs/encounter/encounter_fields.rs
- server/service/src/programs/encounter/encounter_updated.rs
- server/service/src/programs/encounter/insert.rs
- server/service/src/programs/encounter/update.rs
- server/service/src/programs/program_enrolment/program_enrolment_updated.rs
- server/service/src/sync/init_programs_data.rs
- server/service/src/sync/program_schemas/report_gbv.json
Closes #1202 
Adds a GBV report and adds a filter for filtering encounter document data. This is done by doing a string search in the JSON data. However, I think this could be done using the building json functions in sqlite as well as postgres in a fairly DB agnostic way in the future....
For testing: fill some fields in the GBV section in the HIV care encounter. The values from the latest encounter should show up in the report.
> 1202 GBV report

- server/Cargo.lock
- server/service/Cargo.toml
- server/service/src/report/html_printing.rs
This should fixes #1184 
Printing a report with the report build was still working for me.
> Updated `headless_chrome` dependency

- client/.storybook/main.js
- client/.storybook/manager-head.html
- client/.storybook/preview.js
- client/.storybook/theme.js
- client/packages/common/src/ui/components/buttons/FlatButton/FlatButton.stories.tsx
Fixes #1206
- Adds support for material UI props if the component props are extending from a material interface
- Changes the text colour to something readable ( white looks better in the sidebar, but is unreadable in the menu and addons window )
- Adds select / radio button selection for enumerated props
- Adds description and default column for controls
As an example - this is the `FlatButton` control, which now has the colour options as radio buttons, the description and default columns shown and the boolean 'disabled' selectable.
Run `yarn storybook` from the `/client` folder
> Enhanced material-ui and storybook integration

- client/packages/programs/src/JsonForms/common/components/Number.tsx
- client/packages/system/src/InventoryAdjustmentReason/Components/InventoryAdjustmentReasonSearchInput.tsx
Fixes #1205
Following on from #1241 - this PR is to left-align the `Number` JSONForms component. 
Also brought through the change from [Roxy's comment](https://github.com/openmsupply/open-msupply/pull/1241/files#r1118146638)
- Inbound shipment should show required indicator as it does before the PR
- Look at patient details: the `Birth Order` should align left, not right
Manual testing, this one is alignment / UI
> update number display

- client/packages/common/src/ui/components/modals/AlertModal/useAlertModal.ts
- client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditForm.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/Footer/StatusChangeButton.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditForm.tsx
- server/report_builder/README.md
Fixes #1137 
The `OK` button event on the OS status change alert modal was not being set and therefore retained the previous action, of a redirect to login, if the button is clicked after the user has been logged out due to inactivity.
🎩 tip to @andreievg for spotting the full scenario!
Easiest way to repro 
- Login to the site
- Open dev tools, Application, Cookies and click on localhost ( if running locally )
- Delete the Auth cookie
- Wait a minute
- Click ok on the prompt, login again
- Go to Outbounds > click on an outbound
- Allocate some quantity to a placeholder
- Click on `Confirm Allocated`
then wait for this
I spotted some offroads, as noted.
> User incorrectly redirected to login screen 

- client/packages/programs/src/JsonForms/common/components/Date.tsx
- client/packages/programs/src/JsonForms/common/components/DateTime.tsx
Fixes #1205
After merging #1244 I noticed the Date inputs:
This PR adds the changes from #1244 to make them look like:
> Json form component alignment

- server/service/src/sync/init_programs_data.rs
Fixes #1110
As discussed in [this comment](https://github.com/openmsupply/open-msupply/issues/1110#issuecomment-1421841322), this PR just adds some empty info to the contact details for the related people, which prevents the warning in the original issue .
Delete database, re-start server, then go to "Patients". The default patients "Tina Ling" and "Andy Cook" should be able to be viewed and switched away from (change tab) without any edit change warning.
There's probably a better way to do this. It would be acceptable to have the array initialised with an empty object `[ { } ]` rather than adding "None" to every field, but couldn't figure out how to do that in Rust.
> #1110 add empty contact details to init persons

- server/Cargo.lock
- server/server/Cargo.toml
- server/server/src/discovery.rs
- server/server/src/lib.rs
Fixes #1064 
I've been hitting the seg fault a lot lately, and wanted to get a more permanent fix in place, so I tried the astro-dnssd implementation on macOS and it worked fine. 
So, just swapped out the `async-dnssd` for `astro-dnssd` 
Run the server a few times, and see if it crashes 🤷 
Check that discovery is working from a macOS machine. You can try a tablet, or the desktop app or `dns-sd -Q _omsupply._tcp.local ANY` from a terminal.
> Use astro-dnssd for discovery

- client/packages/android/app/src/main/java/org/openmsupply/client/NativeApi.java
Fixes #1188 
Started looking into registering for events / actions in order to save and restore the app state and URL. 
Then found that the `handleOnStart` method of plugins is called when resuming; simply checking the loaded URL tells us if this is the initial load or a resume.
So.. check the URL on start, and if we have the default url run through the current process of
- display the splash screen
- wait for the server to respond
- redirect to `/android`
and if we are resuming, don't bother with all that.
Have checked that closing the app does log you out; clearing app data gets you back to the initial splash screen process etc.
https://user-images.githubusercontent.com/9192912/222315385-562908e5-a1fa-4bdc-ad4f-50518f80e003.mp4
Have played around to check behaviour:
- switched between …
> Remember android app state when switching apps

- client/packages/android/app/src/main/java/org/openmsupply/client/CertWebViewClient.java
- client/packages/android/app/src/main/java/org/openmsupply/client/NativeApi.java
- client/packages/common/src/ui/icons/MSupplyGuy.tsx
- server/android/src/android.rs
Fixes #1298 
The issue is a strange behaviour in the webView - refreshing a page ( either with `window.location.reload()` or `navigate(0)` ) will reload *and* open the URL in a browser.
The change here is to overload the URL handling in the webView and if the URL is local, do not open in a browser.
You'll need an android build.
Try the two actions in the issue, as well as a baseline external URL handling one:
- Change language (either the footer, or the admin > language selection)
- Create an outbound shipment from a customer requisition
- Open the docs: this should open in a browser
> 1298 android url handling

- client/packages/common/src/intl/locales/en/patients.json
- client/packages/programs/src/JsonForms/useJsonForms.tsx
- client/packages/system/src/Patient/CreatePatientModal/CreatePatientModal.tsx
- client/packages/system/src/Patient/CreatePatientModal/PatientFormTab.tsx
- client/packages/system/src/Patient/PatientView/PatientView.tsx
Fixes #1285 
I think this should fix the immediately reported problem from #1285, but it was only happening intermittently for me, so not 100% sure. However, it does fix the other two problems I noted on that thread and so I think it takes care of the main problem too. 
I think it was all due to the infinite re-render caused by the `setPatient` method causing a change in `patient` even though no actual data had changed, which in turn caused `setPatient` to re-run when the component re-rendered, etc. 
This is a problem I've encountered before -- when a state object changes its instance (due to a new object being created with ` {...originalState, ...newState }`) but not actually having any new data. It can be fixed by doing a deep equality check (in this case with `lodash`), but I feel like …
> #1285 Fix for unable to create new patient

- client/packages/common/src/api/GqlContext.tsx
- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/intl/locales/en/dashboard.json
- client/packages/common/src/types/exceptions.ts
- client/packages/common/src/types/index.ts
- client/packages/common/src/ui/components/domain/Dashboard/StatsPanel.tsx
- client/packages/dashboard/src/api/api.ts
- client/packages/dashboard/src/api/hooks/statistics/useItemCounts.ts
- client/packages/dashboard/src/api/hooks/statistics/useStockCounts.ts
- client/packages/dashboard/src/api/hooks/utils/useDashboardApi.ts
- client/packages/dashboard/src/widgets/StockWidget.tsx
- client/packages/invoices/src/InboundShipment/Dashboard/Widget.tsx
- client/packages/invoices/src/InboundShipment/api/hooks/index.ts
- client/packages/invoices/src/InboundShipment/api/hooks/utils/index.ts
- client/packages/invoices/src/InboundShipment/api/hooks/utils/useInboundApi.ts
- client/packages/invoices/src/InboundShipment/api/hooks/utils/useInboundCounts.ts
- client/packages/invoices/src/OutboundShipment/Dashboard/Widget.tsx
- client/packages/invoices/src/OutboundShipment/api/hooks/index.ts
- client/packages/invoices/src/OutboundShipment/api/hooks/utils/index.ts
- client/packages/invoices/src/OutboundShipment/api/hooks/utils/useOutboundApi.ts
- client/packages/invoices/src/OutboundShipment/api/hooks/utils/useOutboundCounts.ts
Fixes #1224 
There's a few file changes, but don't be put off! 
Essentially this is picking up on existing work, fixing an incorrect implementation in it and extending to a newer query that missed out on the change.
The process is:
- the `GqlContext` has a list of api calls which might throw a permission error but should not show an alert if they do ( the `itemCounts` dashboard query needed to be added to this list )
- the api calls should provide an `onError` which swallows the error ( note that errors are still logged to console, as an fyi )
- the `isError` prop is set on the `useQuery` response and this can be used to modify the UI response
As an extension to the current process, I've added a message when you don't have permission to view the stats. Simply hiding the panels ( previous …
> Handle dashboard errors

- client/packages/host/src/Admin/Settings.tsx
- client/packages/host/src/components/AppVersion.tsx
- client/packages/host/src/components/Initialise/Initialise.tsx
- client/packages/host/src/components/Initialise/InitialiseLayout.tsx
- client/packages/host/src/components/Login/LoginLayout.tsx
Fixes #1297 
The version info was using absolute positioning to get it to stick to the bottom right of the screen. Have refactored the layout to use flex.
Checked on android and in a browser with various screen sizes. Examples below are android screenshots:
**Login**
**Initialise**
**Settings**
> Remove absolute positioning of version info

- client/packages/common/src/intl/locales/en/inventory.json
- client/packages/inventory/src/Stocktake/ListView/CreateStocktakeButton.tsx
- server/repository/src/db_diesel/master_list_line.rs
Fixes #1300 
The default pagination limit causes issues again.
Have removed the pagination from the method fetching master list lines, and checked all usages of this method. the `query_by_filter` fn is only used when adding items from master lists, so this change will fix a few issues.
Have also added the comment generation, done in the f/e so that it is translatable.
Checked the delete, which now shows the correct count.
**Counts**
**Delete**
**Comments**
Bonus!
Noticed that if there are no locations, you see this:
Which I've upgraded to this:
As per the issue:
- create a stocktake, noting the numbers next to the master list names.
- Try to create from master list, and from location - check the comments.
- Delete lines from a list, when there are more than 100 lines
I never use this …
> Incorrect number in stocktake creation display

- client/packages/common/src/intl/locales/en/common.json
- client/packages/system/src/Patient/CreatePatientModal/DefaultCreatePatientJsonForm.ts
- server/service/src/sync/program_schemas/patient_creation_ui_schema.json
Fixes #1359
Rename all `National Health ID` to `National ID (NID)
> 1359 Programs: patient detailed view's header => remove "Health" from National Health ID

- client/packages/programs/src/JsonForms/components/AdherenceScore.tsx
- client/packages/programs/src/JsonForms/components/EncounterLineChart.tsx
- client/packages/programs/src/api/hooks/document/useEncounterPrevious.ts
- server/service/src/sync/init_programs_data.rs
- server/service/src/sync/program_schemas/hiv_care_encounter_ui_schema.json
Fixes #1340
Fixes #920
- For #1340 it was just about fixing a recent variable rename
- While doing it I also quickly fixed the live data update for graphs
- Then I noticed an inconsistency with the Adherence score control, e.g. in the UI the `Pill Count (at last visit end):` was displayed from the previous event but the adherence score still used the previous encounter. (The previous encounter may not have an previous count though which leads to inconsistent results. Using the event makes it more robust...) The Adherence score control can not take the `previous pill count` from the previous encounter or from the previous event.
> 1340 adherence score graph

- client/packages/requisitions/src/RequestRequisition/api/hooks/line/useRequestLines.ts
Fixes #1368
Fixes the leading 0 problem as described in [the issue](#1368). 
Also -- since @alainsussol was attempting to filter by digits, it would suggest he was trying to search for a code, so I've expanded the filter to match **code** as well as item **name**. This also makes it consistent with the item filter on the Catagloue -> Items page.
Create a new Internal Order as per issue steps. You should be able to filter added items by name or code, and starting the filter string with a `0` shouldn't make any difference.
> #1368 Leading 0 in filter fix

- client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NonNegativeDecimalCell.tsx
- client/packages/common/src/utils/numbers/NumUtils.ts
- client/packages/invoices/src/InboundShipment/DetailView/SidePanel/PricingSection.tsx
- client/packages/invoices/src/InboundShipment/DetailView/modals/InboundServiceLineEdit/useDraftServiceLines.ts
- client/packages/invoices/src/InboundShipment/DetailView/modals/InboundServiceLineEdit/useServiceLineColumns.tsx
- client/packages/invoices/src/InboundShipment/DetailView/modals/TaxEdit.tsx
- client/packages/invoices/src/InboundShipment/api/operations.generated.ts
- client/packages/invoices/src/InboundShipment/api/operations.graphql
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundServiceLineEdit/useDraftServiceLines.ts
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundServiceLineEdit/useServiceLineColumns.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/modals/TaxEdit.tsx
Fixes #1240 
This will disable the Tax pen icon disable for the Service charges section
~Considering the workflow of Outbound > Service charges section, This does not get enabled at all so considering that, thinking is, The service charges are yet to get applied.~
~So, Have disabled the Tax pen icon on Inbound shipment as well.~
~Also, It seems, Service charge is per line, Does not make sense though, and there is no handler in Backend to the best of my understanding.~
The issue is the GraphQl Typename.
> #1240 Inbound shipment service charge tax pen icon glitch with calculating Service price total on fly

- server/repository/migrations/postgres/2022-01-27T08-00_create_changelog_table/up.sql
- server/repository/migrations/postgres/2022-03-27T10-00_update_changelog_upsert_with_sync_function/down.sql
- server/repository/migrations/postgres/2022-03-27T10-00_update_changelog_upsert_with_sync_function/up.sql
- server/repository/migrations/postgres/2022-04-01T12-00_create_clinician_trigger/up.sql
- server/repository/migrations/postgres/2022-04-27T13-05_create_document_trigger/up.sql
- server/repository/migrations/postgres/2023-03-05-205307_create_name_trigger/up.sql
- server/repository/migrations/sqlite/2022-04-27T13-05_create_document_trigger/up.sql
Fixes #1384
- Update document trigger to update `is_sync_update`
- For Postgres, create a common update function and us it for clinician, name and document
- all involved triggers (clinician, name, document) are not currently in develop and can be modified directly in the base schemas
> 1384 is sync update triggers

- client/packages/common/src/intl/utils/DateUtils.ts
- client/packages/common/src/ui/components/inputs/DatePickers/BaseDatePickerInput/BaseDatePickerInput.tsx
- client/packages/common/src/ui/components/inputs/DatePickers/DatePickerInput/DatePickerInput.tsx
- client/packages/inventory/src/Stocktake/DetailView/Toolbar.tsx
Additional fix to #1356 to handle manual date entry in updated DatePicker component. 
Have already implemented this in Programs branch, so this is just replicating some of that functionality (as the programs branch obviously won't be merged here for a while).
The basic idea is that the "BaseDatePicker" component keeps its own internal state for the current input value, and only executes the parent component's `onChange` method if the internal date is a valid date. It shows an error state if not.
Also includes debouncing.
Tested with the DatePicker for Stocktakes and the Expiry date edit in stocktake lines. You should be able to use either the GUI picker or manually type the date.
@mark-prins if you're happy with this, please merge it straight to your branch.
> #715 Fix for manual entry in DatePicker

- server/service/src/report/default_queries.rs
Fixes #1319 
Ability to use the default query for Outbound and Inbound invoices, take off to have a new .graphql
> #1319 extending default query to have store logo with name address 1 and 2

- client/packages/common/src/intl/locales/en/common.json
- client/packages/invoices/src/InboundShipment/DetailView/modals/InboundServiceLineEdit/InboundServiceLineEdit.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundServiceLineEdit/OutboundServiceLineEdit.tsx
Fixes #1351 
- If no service charges (Outbound and Inbound):
- Add charges will be disabled
- With text `There are no service charges assigned to this store`
- If service charges exist (Outbound and Inbound):
- Add charges will be enable
- With text `Nothing here`
Require to setup central, Remote with client and follow below:
- If no service charges (Outbound and Inbound):
- Add charges will be disabled
- With text `There are no service charges assigned to this store`
- If service charges exist (Outbound and Inbound):
- Add charges will be enable
- With text `Nothing here`
> #1351 no service charge improvement

- server/service/src/sync/init_programs_data.rs
- server/service/src/sync/program_schemas/hiv_care_encounter.json
Fixes #1403
Make `regimen status` a required field since there is a continued option for it. If Regimen Status isn't updated to continued and other fields in the ARV/Medication has been edited, then the user cannot save the form since the previous status will trigger the `New ARV Regimen` and `Regimen Reason` to become required fields even if it is still hidden.
> 1403 Form expects required fields to be filled out even if it is hidden 

- client/packages/common/src/ui/components/inputs/TextInput/TextInput.stories.tsx
- client/packages/common/src/ui/components/inputs/TextInput/numeric/NonNegativeIntegerInput.tsx
- client/packages/common/src/ui/components/inputs/TextInput/numeric/NonNegativeNumberInput.tsx
- client/packages/common/src/ui/components/inputs/TextInput/numeric/NumericTextInput.tsx
- client/packages/common/src/ui/components/inputs/TextInput/numeric/PositiveNumberInput.tsx
- client/packages/common/src/ui/layout/tables/columns/EditableQuantityColumn.tsx
- client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/PositiveNumberInputCell.tsx
- client/packages/host/src/Admin/SyncSettings.tsx
- client/packages/programs/src/JsonForms/common/components/Number.tsx
- client/packages/programs/src/JsonForms/components/QuantityDispensed.tsx
- server/service/src/sync/init_programs_data.rs
- server/service/src/sync/program_schemas/hiv_care_encounter.json
- server/service/src/sync/program_schemas/hiv_care_encounter_config.json
Fixes #1353
The actual change as per the issue is just a small tweak to the HIV Care Encounter schema. 
However, I noticed in the process of doing this that number inputs weren't clearable -- i.e. if you select the value and push "delete", it gets set to `0`, not an empty input. For non-required inputs, you should always be able to clear them, just like text inputs, and we don't want users putting `0` if the value is not actually zero. So I've updated the number inputs to reset their value back to `undefined` when cleared.
The side-effect of this is that there are a lot of places these number inputs are used, and they all required some kind of tweak -- I've either set them to allow `undefined` values, or adjusted their functionality to only update the value if the input is not …
> #1353 use numbers for measurements, update number inputs

- client/packages/common/src/ui/components/charts/ValueBar/ValueBar.stories.tsx
- client/packages/common/src/ui/components/charts/ValueBar/ValueBar.tsx
- client/packages/common/src/ui/components/charts/ValueBar/index.ts
- client/packages/common/src/ui/components/charts/index.ts
- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/ItemCharts/StockDistribution.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/ReponseStats/RequestStoreStats.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/ReponseStats/ResponseStoreStats.tsx
Fixes #873
- Extracts the ValueBar component from StockDistribution, RequestStoreStats, ResponseStoreStats  in client/packages/host, and moved it to /common/src/ui/components/charts/
- An option has been added to include or remove the starting and trailing Divider as this was also floating around in each of the components where it was before.  Defaults are leave off Divider at the start, and include Divider at the end of ValueBar.
- Adds Storybook for Charts
- No functional logic was changed.
- Tests are visual. i.e navigating to Replenishment>Internal Orders, selecting an order with "Draft" status.  Find an order with detail lines where AMC > 0.
- Not sure my naming convention of "startDivider" and "endDivider" are very descriptive in the ValueBar component.
- The strength of this …
> 873 extract value bar component

- client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NonNegativeDecimalCell.tsx
- client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx
- client/packages/system/src/InventoryAdjustmentReason/Components/InventoryAdjustmentReasonSearchInput.tsx
Fixes #1465
Allows adjustment reason when counted quantity is zero (fixing `rowData.countedNumberOfPacks || rowData.snapshotNumberOfPacks` when countedNumberOfPacks is zero)
Using Adjustment enum type to handle adjustment, to simplify adjustment representation
Bonus: Fixes countedNumberOfPacks being wiped when it's set to 0
For adjustment reason not available when counted quantity is zero:
* Datafile with positive and negative inventory adjustment reasons set up
* Try setting number of packs to zero (in stocktake) when snapshot number of packs is not zero, should be able to set correct reason
For counted number of packs wiped when set to zero:
* Set number of packs to non zero value in stocktake
* Focus out of the input
* Focus back in the input and set number of packs to 0, it should not …
> 1465 allow inventory adjsutment reason when counted quantity is 0

- server/service/src/sync/init_programs_data.rs
- server/service/src/sync/program_schemas/hiv_care_program.json
- server/service/src/sync/program_schemas/hiv_care_program_ui_schema.json
Fixes #1475 
Hides fields related to `Prior exposure to ART - Transfer in with records` if `Transfer in with records` isn't selected
Enrol a patient into HTC program and select `Transfer in with records` in `Prior exposure to ART` field
> 1475 Programs: changes in "Referral or Transfer In Details" section of the HIV Care & Treatment enrolment form 

- client/packages/host/src/components/AppDrawer/SyncNavLink.tsx
Fixes #1469
Fixed when looking at something else, so have put in a PR. Sorry for the distraction.
The problem is that the sync count is coming through as a string, i.e. `'0'` the Badge component won't show `0` by default, but the string is being shown.
Have parsed as a number to prevent the 0 showing.
Take my word for it? 🤷 It's only showing up sometimes. I passed in the value `'0'` to the `badgeContent` prop when testing
> Don't show 0 sync badge

- client/packages/common/src/ui/components/inputs/DatePickers/BaseDatePickerInput/BaseDatePickerInput.tsx
- client/packages/programs/src/JsonForms/common/components/Date.tsx
- client/packages/programs/src/JsonForms/common/components/DateTime.tsx
Fixes #1494.
The JSONForms "Date" component was not using the common "BaseDatePicker", which had recently been updated to handle manual date entries more gracefully. So have replaced the "DatePicker" in "Date" to use that instead. Very little needed to be changed to make it work with it.
- Can manually enter date of birth in the "New Patient" modal (first screen)
- Other JSONForm Date inputs (including DOB) work correctly.
> #1494 Date input fix

- client/package.json
- client/packages/android/package.json
Fixes #1546 
Just have to move the dependency to the root - it was in the android package, but required by `useNativeClient` and therefore used by the electron package.
Try running the desktop package
> Fix electron dependency

- .gitignore
- client/.eslintrc.js
- client/packages/common/src/intl/utils/DateUtils.ts
- client/packages/common/src/ui/forms/Detail/InputWithLabelRow.tsx
- client/packages/programs/src/JsonForms/common/components/Array/EnumArray.tsx
- client/packages/programs/src/JsonForms/common/components/Array/FirstItemArray.tsx
- client/packages/programs/src/JsonForms/common/components/Array/common.tsx
- client/packages/programs/src/JsonForms/common/components/Autocomplete.tsx
- client/packages/programs/src/JsonForms/common/components/Boolean.tsx
- client/packages/programs/src/JsonForms/common/components/ConditionalSelect.tsx
- client/packages/programs/src/JsonForms/common/components/Select.tsx
- client/packages/programs/src/JsonForms/components/AdherenceScore.tsx
- client/packages/programs/src/JsonForms/components/IdGenerator.tsx
- client/packages/programs/src/JsonForms/components/PreviousEncounterField.tsx
- client/packages/programs/src/JsonForms/components/QuantityDispensed.tsx
- client/packages/programs/src/JsonForms/components/Search/SearchWithDocumentSource.tsx
- client/packages/programs/src/JsonForms/components/Search/SearchWithUserSource.tsx
- client/packages/system/src/Patient/Encounter/CreateEncounterModal.tsx
Fixes #1525
Most of the changes are schema-only, and are done in the programschemas repo. This just includes code changes that were required for a couple of them to work, namely:
- Change "Create Encounter" modal to only collect date, not times (and generate a default start time of the current time)
- Don't add trailing ":" to component labels if they already end with punctuation (e.g. "?")
Run `./dev_server_schema_update.sh` script from programschemas repo to update local server database, then Testing Program enrolments and encounters should work as per the issue requests.
**Enrolment**:
**Encounter**
The ":" at the end of component labels was hard-coded in each component. I've made a little utility function `labelWithPunctuation` to only append this when the label doesn't already have a …
> #1525 HIV Testing enrolment/encounter updates

- server/service/src/auth.rs
There where a problem in the programs branch where a user (Admin) had more than 100 permissions and some permissions got not evaluated. This quick fix queries all entries from the DB. Though I also apply this to `develop` in case we run into it here as well...
> Query all user permission without pagination

- client/packages/common/src/ui/components/inputs/DatePickers/BaseDatePickerInput/BaseDatePickerInput.tsx
- client/packages/common/src/ui/components/inputs/DatePickers/DatePickerInput/DatePickerInput.tsx
- client/packages/common/src/ui/components/inputs/TextInput/BasicTextInput.tsx
- client/packages/common/src/ui/forms/Detail/InputWithLabelRow.tsx
- client/packages/programs/src/JsonForms/common/components/Autocomplete.tsx
- client/packages/programs/src/JsonForms/common/components/Boolean.tsx
- client/packages/programs/src/JsonForms/common/components/ConditionalSelect.tsx
- client/packages/programs/src/JsonForms/common/components/Select.tsx
- client/packages/programs/src/JsonForms/common/components/Text.tsx
- client/packages/programs/src/JsonForms/components/AdherenceScore.tsx
- client/packages/programs/src/JsonForms/components/DateOfBirth.tsx
- client/packages/programs/src/JsonForms/components/IdGenerator.tsx
- client/packages/programs/src/JsonForms/components/ProgramEvent.tsx
- client/packages/programs/src/JsonForms/components/QuantityDispensed.tsx
- client/packages/programs/src/JsonForms/components/Search/SearchWithDocumentSource.tsx
- client/packages/programs/src/JsonForms/components/Search/SearchWithUserSource.tsx
- client/packages/system/src/Clinician/ClinicianSearchInput.tsx
- client/packages/system/src/Patient/Encounter/CreateEncounterModal.tsx
Fixes #1255
Previously only about 60% of the components were using the `DetailInputWithLabelRow` wrapper even though they all tried to match the column widths for the label and input to varying degrees of success. Now they all do, which means we can adjust layout widths globally if we need to, plus they should all have consistent widths now.
Load some of the forms, and switch branch between this one and `feature/programs`. The UI should look the same, or slightly better (text input widths should match the others).
> #1255 JSONForms component consistency

- client/packages/common/src/ui/components/navigation/AppNavLink/AppNavLink.tsx
Fixes #1469 
When the badge is not shown, the class `MuiBadge-invisible` is applied. This is applying `transform: scale(0) translate(50%, -50%);` - and we are overriding the transform in the `sx` prop.
Have excluded the invisible class when applying the new transform css.
Unsure why it was showing only sometimes - it shows up in the current develop, but was working correctly previously. 
This fix is working for me 🤷 
> Update badge style

- client/packages/requisitions/src/RequestRequisition/api/hooks/line/useRequestLines.ts
- client/packages/requisitions/src/ResponseRequisition/ListView/Toolbar.tsx
- client/packages/requisitions/src/ResponseRequisition/api/hooks/line/useResponseLines.ts
Fixes #1543 
- Protect the APP panicking if searching line is by *
- On request order lines
- Fixes the searching of lines by item code when item code have a 0 in it
- was resetting to blank so searching got broken
- On a response line
- Same as request order line
- Added a searching by item code and name
- Setup omsupply
- Require
- Response order with lines
- Have some item with item code that has 0
- Request order with lines
- Have some item with item code that has 0
> #1543 request response searching line

- client/packages/common/src/intl/locales/en/common.json
Fixes #1541 
- Changes the label from Sync password to Site password
> #1541 sync password to site password

- client/packages/common/src/authentication/api/hooks/useLogin.ts
- client/packages/common/src/hooks/useDialog/useDialog.tsx
- client/packages/common/src/intl/currency/currency.ts
- client/packages/common/src/intl/number/IntlNumber.ts
- client/packages/common/src/intl/utils/DateUtils.ts
- client/packages/common/src/intl/utils/IntlUtils.ts
- client/packages/common/src/styles/RTLProvider.test.tsx
- client/packages/common/src/styles/RTLProvider.tsx
- client/packages/common/src/styles/useAppTheme.ts
- client/packages/common/src/ui/components/buttons/FlatButton/FlatButton.tsx
- client/packages/common/src/ui/components/buttons/standard/ShrinkableBaseButton.tsx
- client/packages/common/src/ui/components/buttons/standard/SplitButton.stories.tsx
- client/packages/common/src/ui/components/modals/BasicModal/BasicModal.tsx
- client/packages/host/src/components/Footer/Footer.tsx
- client/packages/host/src/components/Footer/LanguageSelector.tsx
- client/packages/host/src/components/LanguageMenu.tsx
- client/packages/system/src/Clinician/ClinicianSearchInput.tsx
- client/packages/system/src/Encounter/DetailView/DetailView.tsx
- client/packages/system/src/Encounter/DetailView/Toolbar.tsx
- client/packages/system/src/Patient/Encounter/CreateEncounterModal.tsx
- client/packages/system/src/Patient/ProgramEnrolment/Components/ListView.tsx
- client/tsconfig.json
Bit offtrack here, but just doing this quickly as discussed [here](https://github.com/openmsupply/open-msupply/pull/1563#discussion_r1171935055)
Just refactors the `IntlUtils` into a single hook `useIntlUtils` that returns all relevant values and methods, namely: 
**Values**
- defaultLanguage: 'en',
- isRtl,
- currentLanguage,
- languageOptions,
- currentLanguageName,
**Methods**
- changeLanguage,
- getLocaleCode,
- getUserLocale,
- setUserLocale,
- getLocalisedFullName,
A couple of the existing methods were no longer needed, or could be simplified too. (in particular, there's no need to return the whole `i18n` object now. I think it's tidier and more consistent now.
> the functions aren't all hooks in the IntlUtils tho - so I would just expose the hook based items. Otherwise you are …
> Refactor intl utils

- server/Cargo.lock
- server/windows/Cargo.toml
- server/windows/src/windows.rs
Fixes #1284
Changed the `expect` to a match and within the error check, instantiate the `eventlog` crate and log the error to the Application event log.
You'd need to build on windows, create a service using the `omsupply_service.exe`, add a configuration which is invalid and try to start the service.
You'll get and entry in the event log, like so:
Note: I used `sc` to create a service:
```
sc create oms-test --binpath= "[insert path here]\omsupply_service.exe"
```
and to delete after:
```
sc delete oms-test
```
> Windows event logging

- client/packages/system/src/Patient/Encounter/CreateEncounterModal.tsx
- server/repository/migrations/postgres/2022-06-07T17-00_create_encounter_table/up.sql
- server/repository/migrations/sqlite/2022-06-07T17-00_create_encounter_table/up.sql
- server/repository/src/db_diesel/encounter_row.rs
- server/service/src/programs/encounter/encounter_schema.rs
- server/service/src/programs/encounter/encounter_updated.rs
- server/service/src/programs/schemas/encounter.json
Fixes #1612
Set an encounter location (the store id) when creating an encounter. This information is needed, e.g. for the central encounters report where encounters from multiple stores are reported.
> 1612 encounter store

- client/packages/requisitions/src/ResponseRequisition/DetailView/Toolbar.tsx
Fixes #1622
Removes duplicate info panel in response requisition.
Go to a response requisition and you should only see one info panel. 
Wasn't sure which one we wanted to remove, so I just kept the latest one..
or
> 1622 Warning shown twice in Response Requisition

- client/packages/electron/src/electron.ts
Fixes #1625 
The call to `discovery.start()` is kicking off a process which results in an unhandled exception in a promise. This is already caught by the electron process and suppressed.. but the message in the error has changed slightly and we aren't suppressing any more.
I've just relaxed the condition a little. Tried for some time to fix dnssd and looked at other people's forks for various issues.. but no luck. have just gone with the suppression.
Run `yarn electron:build` and run the result. Popping up the error every time for me atm.
> Update electron error check

- client/packages/common/src/ui/components/buttons/standard/BaseButton.tsx
- client/packages/common/src/ui/components/buttons/standard/ShrinkableBaseButton.tsx
Fixes #1642
Adds a key down event handler for the `BaseButton` and `ShrinkableBaseButton` which is what the allocate button is using.
> onClick on Enter

- client/packages/programs/src/JsonForms/components/ProgramEvent.tsx
- client/packages/system/src/Encounter/utils.ts
- client/packages/system/src/Patient/CreatePatientModal/PatientResultsTab.tsx
The exhaustive check at the end of the switch statement was effectively disabled by the type cast `as never`. Removing this revealed a bug, i.e. the default case was not handled. When TypeScript complains it's usually right; don't silence it :)
> Fix unhandled switch case

- server/repository/src/db_diesel/stock_line.rs
Fixes #1664 
Remove pagination from stock line loader (since stocktake line was getting stock line info)
If you change this limit to 3
https://github.com/openmsupply/open-msupply/blob/a88030a2e156a5b149958edb2be07d3f48338bb7/server/repository/src/db_diesel/filter_sort_pagination.rs#L211
Create stocktake with more then 3 stock lines, without this change stocktake will freeze
TODO: Create an issue to check all other loaders for this (and remove pagination from service): https://github.com/openmsupply/open-msupply/issues/1687
> 1664 Remove pagination from stock line loader

- server/service/src/sync/test/test_data/requisition_line.rs
- server/service/src/sync/translations/requisition_line.rs
Fixes https://github.com/openmsupply/open-msupply-internal/issues/27
item name is added when pushing requisition line to central
Setup remote authorisation, see item name for requisition line in remote authorisation web app shows correctly.
You can use this data file (or instructions), https://drive.google.com/drive/u/1/folders/1-5JlYyYA5jArUl6LbSAvH3qsWE--nO2I, probably easier to change program supplier store to test site, initialise test site, create program requisition from test store to program supplier store
> 27(internal) Add itemName when pushing requisition line

- server/service/src/requisition/program_settings/map.rs
Fixes #1653
Periods are paginated and sorted in program settings API
Configure program requisitions, create lots of periods before and after current date, should only see 3 available periods before now and 3 available periods after now.
Can use this data file: https://drive.google.com/drive/u/1/folders/1-5JlYyYA5jArUl6LbSAvH3qsWE--nO2I
You can adjust existing periods down and create new periods, try test site test store and emergency or normal order (see how it affects the periods shown, should only see max 6 periods (and they should be `centered` around current date and sorted in ASC order)
> 1653 Sort and paginate periods for program internal order

- client/packages/requisitions/src/RequestRequisition/ListView/ProgramRequisitionOptions.tsx
- client/packages/requisitions/src/RequestRequisition/api/operations.generated.ts
- client/packages/requisitions/src/RequestRequisition/api/operations.graphql
- client/packages/system/src/Name/Components/index.ts
- server/repository/src/db_diesel/name.rs
- server/repository/src/db_diesel/program_requisition/program_supplier.rs
- server/service/src/requisition/program_settings/mod.rs
Fixes #1655 
When creating program requisition, supplier input is the same style as when creating general input and stores/names are enforced.
Also make sure we are filtering suppliers (for program requisitions) that are is_supplier.
Setup program requisitions, make sure more then one supplier is configured for a program and as suppliers for a store, toggled `hold` on one, see it being disabled in input when creating program internal order.
Can use data file here: https://drive.google.com/drive/u/1/folders/1-5JlYyYA5jArUl6LbSAvH3qsWE--nO2I, would need to sync test site and make test2 is supplier. Check when creating test store program requisition with supplier on hold.
> 1655 Program requisition creation to restrict supplier on hold

- client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts
Fixes #1703 
Added `item unit` column on stock take line details
> #1703 added unit column

- client/packages/system/src/Stock/Components/StockLineForm.tsx
Fixes #1702 
Sets stock location to state, so that it changes on UI when user changes locations
- Have stock line with location already saved 
- Go to edit stock
- Change location and see it reflected in UI
> 1702 When editing stock, the location field doesn't retain the new location choice when there is already an assigned location

- client/packages/requisitions/src/ResponseRequisition/DetailView/Toolbar.tsx
Fixes #1708 
Fixes the slowness on editing or adding Customer ref on response order
Don't understand what would be the difference between using BasicTextInput and BufferedTextInput, but using `BufferedTextInput` solved the issue.
> #1708 - Customer ref entering is slow on response order

- client/packages/common/src/hooks/useQueryParams/types.ts
- client/packages/common/src/types/schema.ts
- client/packages/requisitions/src/RequestRequisition/DetailView/AppBarButtons/AddFromMasterListButton.tsx
- client/packages/system/src/MasterList/Components/MasterListSearchModal/MasterListSearchModal.tsx
- client/packages/system/src/MasterList/api/api.ts
- client/packages/system/src/MasterList/api/hooks/document/useMasterListsAll.ts
- client/packages/system/src/MasterList/api/hooks/utils/useMasterListApi.ts
- server/graphql/general/src/queries/master_list.rs
- server/graphql/general/src/queries/tests/master_lists.rs
- server/repository/src/db_diesel/master_list.rs
- server/service/src/requisition/request_requisition/add_from_master_list.rs
Fixes #1697 
Restricts the list of master lists which is shown when using a general internal order.
Adds a check to the 'addFromMasterList' mutation which also checks. This returns the 'master list not in this store' error, as I thought the event unlikely enough to warrant a new error variant. 
Configured multiple master lists for a store, with some program lists among them.
Check that you can create a program based internal order, and that you can add to a general order from master lists - but only lists which are not program lists.
> restrict program master lists when creating internal orders

- client/packages/system/src/MasterList/api/api.ts
Fixes #1743 
- Only loads master list that belong to the store in `Internal Order -> Add from Master List`
- Have multiple master lists: some belonging to the store and some not.
- Create an Internal Order from Master List
- Should only see the master lists that belong to that store
> 1743 Restrict master list visibility by store in internal order

- client/packages/common/src/utils/environment/EnvUtils.ts
Fixes #1745
- Use the correct route for dashboards and add back the location doc https://docs.msupply.foundation/docs/inventory/locations/
- Dashboard -> Docs
> 1745 Doc is linked to wrong page 

- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditTable.tsx
Fixes #1700
The function which updates the draft outbound lines was capturing the array of lines when it is first rendered and wasn't being updated. This means that when the placeholder row is updated, the values allocated to each row are based on the values when the table is first rendered.
To prevent this - have added the `allocatedQuantity` to the dependencies of the callback which is used by the placeholder row. When any row is updated, the onChange used by the placeholder row is updated, to reflect the current values of the rows.
As per the issue: add a new item, add a value to the placeholder. edit any other row. edit the placeholder.
Previously - this would result in `0` for all non-placeholder rows.
> Prevent captured enclosure when updating placeholder

- server/service/src/requisition/program_settings/map.rs
Fixes #1756
Only show 2 max historical and future periods
> 1756 [User Training Feedback] program orders: user should only select 2 periods before now and 2 periods after now

- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/intl/locales/fr/common.json
- client/packages/requisitions/src/RequestRequisition/DetailView/columns.ts
Fixes #1761
Add approved quantity of packs to Internal Order detail view
> 1761 [User Training Feedback] Internal Order list view: new column for authorised quantity in packs (same as requested packs) 

- client/packages/inventory/src/Stocktake/DetailView/Toolbar.tsx
- client/packages/inventory/src/Stocktake/api/hooks/line/useStocktakeRows.ts
Fixes #1758
Adds filter to Stocktake items/lines. Have basically just copied it exactly from the Internal Order item filter. As with that one, it doesn't change the database query, it just filters the full list of results (since line queries aren't paginated).
Go to a Stocktake detail view. Check the filter works.
> #1758 Stocktake items filter

- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/hooks/useOutboundLineEditRows.ts
Fixes #1694 
The function which checks to see if a scanned barcode line exists is only checking existence, and needs to also check validity.
The issue which Richard encountered was that the scanned stock line was unable to be used. When you scan, the matching line is highlighted and all other lines are disabled. The problem here is that the scanned line is disabled ( due, in his case, to a different pack size ). This results in all lines being disabled.
To test: 
Run the desktop version using `yarn electron:start-local`
Using a stocktake, add stock for an item and two batch lines with different pack sizes.
Add a barcode for that item, for the second batches' pack size. Use the GTIN value of `0109501101530003` and batch of `B090`.
Create an outbound shipment, add that item. Allocate some …
> Barcode scanning: detect invalid lines in outbound line edit

- build/windows/omsupply_desktop.suf
- build/windows/omsupply_server.suf
- build/windows/omsupply_standalone.suf
Fixes #1723 
Adds an incoming firewall rule for the server port to both the server and standalone installers.
For the rule to be applied, the firewall service requires restarting, so that happens too.
On uninstall, the rules are removed.
For the standalone and desktop installers I've added the rules which were added when the app was first run - I thought that if we add the rules, then the user won't get prompted.
Have created installers and tested on a couple of different machines. 
> Add firewall rules

- client/packages/common/src/types/schema.ts
- client/packages/invoices/src/OutboundShipment/DetailView/AddFromScannerButton.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEdit.tsx
- client/packages/invoices/src/OutboundShipment/api/api.ts
- client/packages/invoices/src/OutboundShipment/api/hooks/utils/useBarcode.ts
- client/packages/invoices/src/OutboundShipment/api/index.ts
- client/packages/invoices/src/OutboundShipment/api/operations.generated.ts
- client/packages/invoices/src/OutboundShipment/api/operations.graphql
- server/graphql/general/src/lib.rs
- server/graphql/general/src/mutations/barcode.rs
- server/graphql/general/src/queries/barcode.rs
- server/graphql/tests/report_default_queries.rs
- server/graphql/types/src/types/barcode.rs
- server/repository/src/db_diesel/barcode.rs
- server/repository/src/db_diesel/barcode_row.rs
- server/repository/src/db_diesel/requisition/requisition_row.rs
- server/repository/src/db_diesel/stock_line.rs
- server/repository/src/migrations/v1_01_12/barcode_sync.rs
- server/repository/src/migrations/v1_01_12/mod.rs
- server/repository/src/mock/barcode.rs
- server/service/src/barcode.rs
- server/service/src/stock_line/update.rs
- server/service/src/sync/test/test_data/barcode.rs
- server/service/src/sync/translation_and_integration.rs
- server/service/src/sync/translations/barcode.rs
Fixes #1748 
Implement the `is_sync_update` for barcodes.
Also renames the `value` column to `gtin`
As per the issue - running two sites from the same datafile. Create a barcode and sync it around.
> Make barcode sync finite

- client/packages/inventory/src/Stocktake/ListView/CreateStocktakeButton.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/AppBarButtons/AddFromMasterListButton.tsx
- client/packages/system/src/MasterList/api/api.ts
- client/packages/system/src/MasterList/api/hooks/document/useMasterListsAll.ts
Fixes #1780 
The outbound shipment master list query was using a filter that had `existsForName` with the customer name, and `existsForStore` for the current store. These two things cannot exist together, and no lists are returned.
The change came in because the internal order filter was incorrect.
Have updated internal orders and outbound shipments and tested.
Outbound shipments should show all lists which are valid in the customer store.
Internal orders show all lists which are valid in the current store and are not programs.
Stocktakes show all lists which are valid in the current store.
> Return master lists for outbound shipments

- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEdit.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditTable.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/utils.ts
Fixes #1779
Remove allocated packs where ever used
> 1779 [User Training Feedback] OUTBOUND SHIPMENT : Placeholder lines are in units when allocated lines are in packs

- client/packages/electron/src/electron.ts
Fixes #1783 
Prompts the user if there is a fingerprint change and asks them to accept it. This is how it looks in development mode on a mac:
Windows version is being built.
For reference - the [message box options](https://www.electronjs.org/docs/latest/api/dialog#dialogshowmessageboxbrowserwindow-options)
Just tested on mac, with a windows server. 
Connected, then stopped the server, changed the cert and started the server again.
> Ask user about fingerprint change

- client/packages/requisitions/src/RequestRequisition/api/hooks/utils/useRequestApi.ts
Fixes #1810 
Just changed the cache key for program settings, so that it depends on the internal order base key, which is invalidated on successful delete of an internal order.
- Create an internal order using a program
- Delete it
- Create a new one using the same period
> Invalidate program settings on delete

- server/service/src/processors/mod.rs
- server/service/src/processors/test_helpers.rs
- server/service/src/processors/transfer/requisition/test.rs
- server/service/src/processors/transfer/shipment/test.rs
Fixes #1523
I was running into this quite consistency now... I first tried to just retry the `check_{*} ` methods in the tests. This worked, but it required to change the semantics of the check methods, e.g. they needed to return a bool to indicated that they should be retried (unwinding the panic didn't work because a mut reference to the Tester was used).
In this PR I just look at the processor queue and wait till the processor handled everything. I used some code from the processor but the usecase is slightly different for which reason I copied the code rather than refactor the processor to have something like an "is_done()" method.
> 1523 wait for processor fix

- client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditForm.tsx
Fixes #1808
Adds item unit to the stocktake line modal
Go to a stocktake line and see item unit
> 1808 [Deployment Feedback] Add "Unit" to stocktake modal 

- client/packages/android/app/src/main/java/org/openmsupply/client/CertWebViewClient.java
- client/packages/android/app/src/main/java/org/openmsupply/client/NativeApi.java
Fixes #1704
Remove the path that was introduced in:
https://github.com/openmsupply/open-msupply/pull/1452
@mark-prins I couldn't figure out why it was added, and it doesn't seem to be used anywhere (?)
In `packages/android/app/src/main/java/org/openmsupply/client/CertWebViewClient.java` there is the code:
```java
@Override
public boolean shouldOverrideUrlLoading(WebView view, WebResourceRequest request) {
// reloading a page ( javascript: navigate(0) or window.location.reload() )
// will not only reload, but will open the URL in a browser tab
// for local URLs we don't want this to happen!
Uri url = request.getUrl();
if(url.toString().startsWith(this.nativeApi.getServerUrl())) {
return false;
}
return bridge.launchIntent(url);
}
```
and `this.nativeApi.getServerUrl()` returned …
> Remove path from the server url

- client/packages/common/src/ui/components/buttons/standard/ButtonWithIcon.tsx
- client/packages/electron/src/keyboardScanner/README.md
- client/packages/electron/src/keyboardScanner/keyboardScanner.ts
- client/packages/invoices/src/OutboundShipment/DetailView/AddFromScannerButton.tsx
Fixes #1837 
When the barcode scanner is in continuous scanning mode ( such as used in outbound shipments ), the following happens:
- The user clicks the `Scan` button
- This button is therefore focussed, due to the click
- if the scanner sends an `Enter` key, the button is clicked again, as it responds to `Enter` keypress events
This turns off scanning. If the barcode is scanned again without the user interacting with the page, then the button receives `Enter` again, is clicked, the scanning starts, and the buffered barcode data sent.
The change in this PR is to `blur` the button on press. It means that an `Enter` from the scanner does not stop the scanning.
- Configure the scanner in keyboard mode (see #1804)
- Open an outbound shipment, and press `Scan`
- Scan a code (I tested using a …
> Continuous scanning with keyboard scanner

- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/intl/locales/fr/common.json
- client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx
Fixes #1822 
Adds a new translation item for stocktake number of packs.
**Inbound Shipment**
**Stocktake**
Manual testing - opening stocktake and inbound shipment and changing languages.
Don't think it necessary to update for this
> Add number of packs translation to stocktakes

- client/packages/common/src/hooks/useNativeClient/useNativeClient.ts
Fixes #1803 
Currently, if you have `autoconnect` set, and have a previous server, then the native client requires finding the server using dnssd before allowing you to connect.
The dnssd package will attach to active network adapters - if all interfaces are inactive there is simply no response from dnssd and therefore the previous server isn't discovered and you never connect. Even though the server is up and responding to requests.
This change is to simply fetch the server URL to test if it is active. If you get a valid response, then connect. If not, show the 'unable to find server' message.
It's much quicker and resolves the issue with disconnected networks.
**To test** 
Note: You can use v1.1.14-rc3, downloadable from jenkins.
- Install the standalone or desktop version ( the change …
> Remove need for dnssd when connecting to previous server

- client/packages/common/src/intl/locales/en/distribution.json
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEdit.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditForm.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/utils.test.ts
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/utils.ts
Fixes #1717 
Allows over-allocation when the pack size requires it. When this happens, displays a message to the user warning them.
I've updated the test suite to accomodate the change in logic and have simplified the allocation routine in utils, didn't need to be as complex as it was.
One strange thing in the original issue which I could not replicate - the pack size controller should only show `100` if all stock lines have pack size of `100`. For my tests, I've added a stock line with pack size of `1` so that the `Any` option is available. This change only applies when `Any` is used, and units are being allocated.
A demo of the process:
https://github.com/openmsupply/open-msupply/assets/9192912/e9c41636-be0c-407c-b8b5-145f9d2605c0
`yarn test …
> Adjust outbound shipment allocation and display info message

- client/packages/android/app/src/main/java/org/openmsupply/client/NativeApi.java
- client/packages/common/src/hooks/useNativeClient/types.ts
- client/packages/common/src/hooks/useNativeClient/useNativeClient.ts
- client/packages/common/src/ui/discovery/DiscoveredServers.tsx
- client/packages/common/src/ui/discovery/ServerDiscovery.tsx
- client/packages/electron/src/electron.ts
- client/packages/electron/src/home.tsx
- client/packages/electron/src/preload.ts
- client/packages/host/src/components/Android.tsx
Fixes #1856 
Implements the SSL handling by pushing the check into the native layer.
This also provides a fix for the scenario where
- server discovery page is shown, a server (a) is found
- server (a) shuts down
- user clicks server (a) on the discovery page
- On windows, start a server, both with and without certificates.
- Connect, then close the desktop version and disconnect the network. Start the desktop again. Should connect.
- Start a server, open the desktop client
- stop the server, click on it in the discovery list
- Start android in server mode, connect to the local server
- close android, disable network and open again
> Handle no network when running SSL

- client/packages/common/src/utils/BarcodeScannerContext.test.ts
- client/packages/common/src/utils/BarcodeScannerContext.tsx
Fixes #1859 
Enables the scanner for android devices.
As an aside, I was testing 2D codes and these do scan correctly on android! 🎉 
I did have to implement a small fix for the parsing of Data Matrix codes. Have tested using these, and they all work now:
Refer to the [parsing library ](https://www.npmjs.com/package/gs1-barcode-parser-mod#about-the-structure-of-gs1-barcodes) for the code parsing, and to the [scanning library](https://github.com/zxing-js/library) for the supported formats
Run on android. e.g. from the client directory:
```
yarn android:build:debug
adb install -r ./packages/android/app/build/outputs/apk/debug/open-msupply-1.1.14-debug.apk
```
and try to scan a barcode. Should be enabled in the edit stock modal and outbound shipment detail pages.
> Enable android barcode scanner

- server/service/src/sync/api/error.rs
- server/service/src/sync/api/get_site_status.rs
- server/service/src/sync/remote_data_synchroniser.rs
- server/service/src/sync/sync_status/logger.rs
- server/service/src/sync/sync_status/test.rs
- server/service/src/sync/synchroniser.rs
PR is to Main branch
Partially Fixes: https://github.com/openmsupply/open-msupply-internal/issues/30
Added polling to initialisation end point, so that if there is a connection error during initialisation, we can poll for initialisation to complete, and pressing 'retry' in UI will not restart initialisation. I am not happy with this as a permanent fix, will add a better `way` to the [underlying issue](https://github.com/openmsupply/open-msupply-internal/issues/30#issuecomment-1567639141). But for now this should deal with connection error during initialisation (without needing to re-initialise): 
As per replication instructions in the first comment: https://github.com/openmsupply/open-msupply-internal/issues/30#issue-1712907706.
Here are the changes for the tests: …
> OMI30 - Poll for initialisation

- client/packages/common/src/intl/locales/en/inventory.json
- client/packages/system/src/Stock/Components/Repack/RepackModal.tsx
Fixes #1877 
Use a different alert message if everything in the stock line has been repacked and close the modal
Repack everything in a stock line to see message.
> 1877 Display alert when all packs from stock line has been repacked

- client/packages/common/src/hooks/useDialog/useDialog.tsx
- client/packages/common/src/types/schema.ts
- client/packages/inventory/src/Stocktake/DetailView/AppBarButtons.tsx
- client/packages/invoices/src/InboundShipment/DetailView/AppBarButtons.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/AppBarButtons.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/AppBarButtons/AppBarButtons.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/AppBarButtons/AppBarButtons.tsx
- client/packages/system/src/Report/components/ReportSelector.tsx
- client/packages/system/src/Stock/Components/Repack/RepackModal.tsx
- package.json
- server/graphql/reports/src/reports.rs
- server/graphql/types/src/types/repack.rs
- server/repository/src/db_diesel/report_row.rs
- server/repository/src/migrations/mod.rs
- server/repository/src/migrations/v1_01_15/mod.rs
- server/repository/src/migrations/v1_01_15/repack_report.rs
- server/service/src/sync/translations/report.rs
Fixes #1445 
Sync repack reports from central. Add the print button on the repack modal to print out a repack. Also added some more information to the endpoint for the [print report](https://github.com/openmsupply/open-msupply-reports/issues/30).
- Add the repack report from above link to central reports.
- Sync.
- Create a repack, click on the packed line and click print.
- The print button looks disabled with styling but isn't actually disabled... tried disabling all the button components in the ReportSelector but doesn't seem to want to disable??? 👀
> 1445 repack print

- client/packages/common/src/ui/layout/tables/columns/types.ts
- client/packages/common/src/ui/layout/tables/components/Cells/TextInputCell/TextInputCell.tsx
- client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx
Fixes #1498
The default behaviour of the `TextInputCell` is to auto focus if this is the first cell in the first row.
However.. the stocktake input modal has a checkbox in the first column!
Have added an option for the cell to specify whether it is auto focussed or not, and in the case of the stocktake modal, have set this for the first row, second column.
Add a stocktake which has multiple lines:
- On clicking on the first line, the batch input of the first row should have focus.
- On clicking OK & Next, the batch input of the first row should have focus.
> Focus the batch input of the first row in a stocktake

- client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEdit.tsx
- client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useStocktakeLineEdit.ts
Fixes #1662 
I was only able to replicate the issue by adding a delay to the save mutation, such as:
```
std::thread::sleep(std::time::Duration::from_secs(1));
```
to line 87 in `server/graphql/batch_mutations/src/batch_stocktake.rs`
Disable the OK and OK & Next buttons if the mutation is in progress already.
Also renamed the `isLoading` variable to `isSaving` to make things clearer
delay the server, or use a slow server. Hastily click the ok button when adding a new stocktake_line
> Prevent duplicate save requests for stocktake_lines

- client/packages/system/src/Patient/CreatePatientModal/CreatePatientModal.tsx
- client/packages/system/src/Patient/PatientView/Footer.tsx
Fixes #1884 
Set a delay on the okay button to allow patient states to be updated.
Create a patient and press okay straight away. All inputted fields should be populated in the Patient View
> 1884 Patient creation: input data loss when searching for a patient to quickly

- server/graphql/programs/src/lib.rs
- server/graphql/programs/src/queries/document_registry.rs
- server/service/src/auth.rs
Fixes #1827
Filter query document registries by store id 
Remove `DocumentQuery` permissions for store and call document registries query for that store... shouldn't see any...
> 1827 Filter document_registry queries by store permissions

- .github/workflows/build-mac-demo.yaml
- build/mac/README.md
- build/mac/build.sh
- build/mac/get_name.sh
- build/mac/instructions.txt
Fixes #1553
PRd to main, will need to be merged to main and then to develop and be in any branch that is being built with this method
I've been playing around with this here: https://github.com/andreievg/open-msupply-actions-test/actions, it's made to run manually, branch can be selected (also can select `intel` or `arm` architecture, and if demo data file should be included or not) 
* Added action and modified build script, see self review comments
Can create your own fork, with these changes and try running action (it takes quite awhile). You should see artefact, can download it, double click on `open_msupply_server.sh` and allow to run in security settings, and server should launch and open a browser (it would run on default port, so may open browser but the server may fail to start)
I …
> 1553 Add mac build for demo action

- server/service/src/sync/api/get_site_info.rs
- server/service/src/sync/api/get_site_status.rs
- server/service/src/sync/remote_data_synchroniser.rs
- server/service/src/sync/settings.rs
- server/service/src/sync/sync_status/test.rs
Fixes https://github.com/openmsupply/open-msupply-internal/issues/30
Need this central [PR](https://github.com/openmsupply/msupply/pull/13111) with this change [update compatibility](https://github.com/openmsupply/msupply/compare/%2313101-sync-v5-init-status-improvements...13101-Update-compatibility), so best to use [this branch](https://github.com/openmsupply/msupply/tree/13101-Update-compatibility)
* Parse initialisation status from site end point
* Check site before attempting to post initialisation and only post initialisation if it hasn't been started yet
This PR improves on the test done in this [PR](https://github.com/openmsupply/open-msupply/pull/1865)
* Shouldn't work with lower version of mSupply
* Same test as [previous …
> OMI30 Sync initialisation resilience to connection loss

- client/packages/common/src/ui/components/inputs/DatePickers/BaseDatePickerInput/BaseDatePickerInput.tsx
Fixes #1833
- Sets internal state from parent if value has been changed.
Change age input in patient view multiple times and see if date of birth updates.
> 1833 Entering the patient age doesn't change the date 

- client/packages/common/src/intl/locales/en/patients.json
- client/packages/system/src/Patient/Encounter/CreateEncounterModal.tsx
- client/packages/system/src/Patient/Encounter/EncounterSearchInput.tsx
- client/packages/system/src/Patient/PatientView/AppBarButtons.tsx
Fixes #1467 
`Add Encounter` button is only disabled if the patient is enrolled in no programs.
If the patient is enrolled in any programs but the programs are inactive then a message will be displayed to let the user know which programs are inactive (in red text as shown below)
Enrol patient into any program.
Change the status of the program to anything but `Active`
Click on `Add Encounter` button
See inactive programs in red in the dropdown list
> 1467 Can create Encounter for a program which the patient isn't enrolled in

- client/packages/system/src/Patient/Encounter/CreateEncounterModal.tsx
Fixes #1846 
Adds a note component to the `Create Encounter` modal which will display in the Encounter -> Side Panel note component. Currently only a single note component is implemented for Encounters... Might want to change this to display as an array, so users can see initial notes as well as updated notes. 
Create an encounter with some note
See note displayed in the side panel when redirected
> 1846 Add note input field when creating a new encounter

- client/packages/android/README.MD
- client/packages/electron/package.json
- server/.gitignore
- server/Cargo.lock
- server/android/Cargo.toml
- server/android/README.md
- server/android/src/android.rs
- server/cli/Cargo.toml
- server/cli/src/cli.rs
- server/configuration/example.yaml
- server/graphql/general/src/lib.rs
- server/graphql/general/src/mutations/log.rs
- server/graphql/general/src/queries/log.rs
- server/server/Cargo.toml
- server/server/src/lib.rs
- server/server/src/logging.rs
- server/server/src/main.rs
- server/service/Cargo.toml
- server/service/src/log_service.rs
- server/service/src/settings.rs
- server/service/src/sync/api/post_initialise.rs
- server/windows/src/windows.rs
Fixes #1916
Change the log crate as suggested [here](https://github.com/openmsupply/open-msupply/pull/1897#discussion_r1228834457). This crate allows `log_level` to be updated at runtime, though server will still need to be restarted. Though, the LogSettings can be saved to `key_value_store` and `log_level` update can be moved out of the `start_server` method to allow `log_level` to update without having to restart the server. 
When the log file has exceeded the file size, it is compressed, so have added a check in `get_log_content` to decompress the file to allow content to be fetched.
- Probably best to use a bigger data file so logs get split, then call log endpoints to see information such as log_files/contents.
- Test on Android as well. Initialise on Android -> Go to Admin -> Show …
> 1916 change log crate 

- client/packages/programs/src/JsonForms/components/IdGenerator.tsx
Fixes #1841
Wasn't getting the jittering... The text state was just not changing for me at all. Updating the debouncedText input with the generated ID.
Generate an id for the patient
Save patient information 
Go back to same patient and generate a new id
Text component should now update with new generated id
Save patient info
See new id has been saved
> 1841 ID Generator reverts to previous value 

- client/packages/common/src/utils/index.ts
- client/packages/common/src/utils/item/ItemUtils.ts
- client/packages/common/src/utils/item/index.ts
- client/packages/inventory/src/Stocktake/api/hooks/line/useStocktakeRows.ts
- client/packages/requisitions/src/RequestRequisition/api/hooks/line/useRequestLines.ts
- client/packages/requisitions/src/ResponseRequisition/api/hooks/line/useResponseLines.ts
Fixes #1773 
Moved `useItemFilter` and `matchItem` to common. 
Test if item search functionality is still working in requisitions and stocktake
> 1773 Refactor "useItemFilter" to common hook

- client/packages/common/src/hooks/useDeleteConfirmation/useDeleteConfirmation.ts
Fixes #1807
Show snack if inbound shipment line cannot be deleted.
- Create a manual inbound with any item
- Confirm delivered (this will create a stock line for the item)
- Create a stocktake with said item and change stock (change counted packs)
- Go back to the manual inbound invoice that was created and try to delete line
- See snack
> 1807 Show error when deleting inbound line that is already used 

- client/packages/common/src/intl/locales/en/programs.json
- client/packages/programs/src/JsonForms/common/JsonForm.tsx
- client/packages/programs/src/JsonForms/common/components/Array/KeyedItemArray.tsx
- client/packages/programs/src/JsonForms/common/components/Array/index.ts
- client/packages/programs/src/JsonForms/components/Search/Search.tsx
- client/packages/programs/src/JsonForms/components/Search/SearchWithPatientContactSource.tsx
- server/service/src/programs/patient/patient_schema.rs
- server/service/src/programs/patient/patient_updated.rs
- server/service/src/programs/patient/upsert.rs
- server/service/src/programs/program_enrolment/program_schema.rs
- server/service/src/programs/schemas/patient.json
- server/service/src/programs/schemas/program_enrolment.json
Fixes #1661
This PR goes together with the `1661-contact-info` branch in the schema repository and the latest develop branch for mSupply.
- Removes the family object from the patient schema
- Adds a `contacts` array to the patient schema
- Adds a `contacts` array to the enrolment schema
- Adds a new generic JSONForms control which is used to display and edit an entry from the contacts array
- Add a search component to lookup an entry from the patient contacts
The RelatedPerson has a `category` field now. This can, for example, be used to mark a contact as "Mother" or "Next of Kin". The "Next of Kin" can then be picked from the contacts list using the category field.
However, there is still the `relationship` field which can be used, for example, like:
```ts
{
category: 'NextOfKin', …
```
> 1661 contact info

- client/packages/programs/src/JsonForms/common/components/Array/Notes.tsx
- client/packages/programs/src/JsonForms/common/hooks/useDebouncedTextInput.ts
Part of #1925 
The Note component now only updates its data if there was some text change. This avoids automatic edits for imported data. For example, visiting a patient with an imported note (but with missing note timestamp and author) caused the component to automatically updated the document data without user interaction.
> 1925 note component reduce data updates

- client/packages/programs/src/JsonForms/components/DateOfBirth.tsx
Related to #1842
While looking at 1842 I noticed that large age values are not correctly displayed (partially hidden). This can be quite confusing. I slightly increase the input width to be able to show values up to 1000 years.
> Increase age input text to be able to display age values > 99

- server/service/src/dashboard/stock_expiry_count.rs
Fixes #1819 
Count expired stocks also counted stock lines with 0 number of packs. Have added check to filter out stock lines with 0 available number of packs, and also added a test.
- Run tests
OR
- Use stocktake to create some expired stock.
- Go to dashboard and see expired count. 
- Go back to stocktake and put expired stock line's counted packs to 0.
- Go back to dashboard and see new expired count.
> 1819 [Deployment Feedback] Dashboard page (welcome screen) doesn't update 

- client/packages/common/src/intl/locales/en/common.json
- client/packages/system/src/Report/ListView/ListView.tsx
Fixes #1683 
Adds a simple spinner modal while fetching the report data.
Follow `png/TestingSetupInstructions.md` from the schema repository and the print reports from the printing menu.
It also helps to use to import some data using the import script from `png/date_import` to increase the time needed for the reports.
> Add spinner modal while printing

- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditTable.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/utils.ts
- client/packages/invoices/src/OutboundShipment/api/api.ts
Fixes #1894 
The placeholder row `numberOfPacks` is set to `0` when creating [newDraftOutboundLines](https://github.com/openmsupply/open-msupply/blob/develop/client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/utils.ts#L74) and then lines are allocated quantities. The issue arises because the previous placeholder line has a non-zero quantity, but the new placeholder row is not allocated, and therefore does not have `isUpdated` set.
This change is to check for the specific case and set the `isUpdated` flag if there is a previous placeholder quantity which is no longer required. There's a subsequent change to allow deleting of placeholder rows.
As per the issue - create an outbound with a placeholder row. Allocate in the modal - if all of the placeholder quantity is …
> Delete unwanted placeholder rows

- client/packages/common/src/authentication/api/operations.generated.ts
- client/packages/common/src/authentication/api/operations.graphql
- client/packages/common/src/types/schema.ts
- client/packages/host/src/components/AppDrawer/AppDrawer.tsx
- client/packages/host/src/components/Navigation/DispensaryNav.tsx
- client/packages/system/src/Patient/ListView/ListView.tsx
- client/packages/system/src/Patient/PatientView/AppBarButtons.tsx
- client/packages/system/src/Patient/PatientView/PatientView.tsx
- server/graphql/types/src/types/store_preference.rs
- server/repository/src/db_diesel/store_preference_row.rs
- server/repository/src/migrations/v1_02_00/mod.rs
- server/repository/src/migrations/v1_02_00/store_preference.rs
- server/service/src/sync/test/test_data/store_preference.rs
- server/service/src/sync/translations/store_preference.rs
Fixes #1947
Hides all program related components with store preference. 
Will need [this branch](https://github.com/openmsupply/msupply/tree/%2313221-omSupply-store-preference-for-Programs-module) for testing.
Make sure all program related things are hidden if omSupply: uses Program module is not configured for store.
> 1947 decouple programs module from dispensary mode check

- client/package.json
- client/packages/common/src/hooks/useNativeClient/types.ts
- client/packages/common/src/hooks/useNativeClient/useNativeClient.ts
- client/packages/common/src/intl/locales/en/app.json
- client/packages/common/src/ui/discovery/DiscoveredServers.tsx
- client/packages/common/src/ui/discovery/ServerDiscovery.tsx
- client/packages/host/src/components/Android.tsx
Fixes #1915
Have added a message and button, which will allow changing from client to server mode.
This only shows when the discovery page is unable to find a server using discovery. If the user is expecting to find a server on the network and it isn't shown, I don't think it's helpful to switch to the local server mode.
The result is a screen like this (emulated version):
I'm not finding any servers on my emulator, so have used that to test. 
If you cannot connect to the local server, a toast is shown - for that I was using the web version and browsing to `/discovery` after setting `discoveryTimedOut` to true in order to show the error.
> Android: reset mode option

- build/windows/omsupply-build.bat
- build/windows/omsupply-desktop-build.bat
- build/windows/omsupply-postgres-build.bat
- build/windows/omsupply-prepare.bat
- build/windows/omsupply-sqlite-build.bat
Fixes #2005 
I was unable to get the secondary batch files to report failures correctly, so have removed them and lifted the calls up to the main batch. This is now working, in that a cargo build failure or copy failure will stop the build, raise the error and prevent the installers from building.
The omsupply-prepare.bat has been kept though: running that with `call` rather than `start /wait` results in the main batch completing at the end of the `yarn install`. Similarly, if the code is within the batch, the same result. There's something with the `yarn` command that ends the process.
I've run some builds. you'll see them on jenkins. Simply switch to this branch and create a tag to see it happen.
> Notify if build fails on jenkins

- client/packages/invoices/src/InboundShipment/DetailView/SidePanel/PricingSection.tsx
- client/packages/invoices/src/InboundShipment/ListView/ListView.tsx
- client/packages/invoices/src/utils.ts
Fixes #1699 
Shows automatically created inbound shipments as enabled in the list view.
- Create an outbound shipment from store A to store B and set status to `Shipped`
- Change to store B and view the list of inbound shipments
- See that the shipment is not greyed out in the list
- Observe that you cannot edit the shipment, but you can change the status (and the info message is shown)
- Change status to `Delivered` : can now edit details (and shows in the list as editable)
- Change status to `Verified`: cannot edit details (and shows in list and non-editable)
> Show auto created inbound shipments as enabled in list view

- package.json
- server/repository/src/db_diesel/changelog/changelog.rs
- server/service/src/processors/transfer/requisition/mod.rs
- server/service/src/processors/transfer/requisition/test.rs
This is a patch PR to main
Fixes https://github.com/openmsupply/open-msupply-internal/issues/33
Filters out deletes from requisition processor.
This fixes sync freezing that was described in the issue (btw, this was validated with a custom build)
Sync was freezing because of deleted records being processed in requisition processor (only deleted requisitions were in changelog for processing)
https://github.com/openmsupply/open-msupply/blob/4e8bc15d60be9a5f5e630f0eb1c70fb443b496e2/server/service/src/processors/transfer/requisition/mod.rs#L113
Above line will continue, and not update cursors:
https://github.com/openmsupply/open-msupply/blob/4e8bc15d60be9a5f5e630f0eb1c70fb443b496e2/server/service/src/processors/transfer/requisition/mod.rs#L131-L136
Why does sync stop thought ? It looks like …
> OMI33 requisition processor to ignore deleted requisitions

- server/repository/src/db_diesel/clinician.rs
- server/repository/src/db_diesel/clinician_row.rs
- server/repository/src/db_diesel/clinician_store_join_row.rs
- server/repository/src/db_diesel/document.rs
- server/repository/src/db_diesel/name_row.rs
- server/repository/src/db_diesel/name_store_join.rs
- server/repository/src/mock/mod.rs
- server/repository/src/mock/name_store_join.rs
- server/repository/src/mock/test_name_query.rs
- server/repository/src/mock/test_name_store_id.rs
- server/service/src/document/document_service.rs
- server/service/src/invoice/prescription/update/mod.rs
- server/service/src/invoice/prescription/update/validate.rs
- server/service/src/programs/encounter/validate_misc.rs
- server/service/src/programs/patient/patient_updated.rs
- server/service/src/sync/integrate_document.rs
- server/service/src/sync/test/mod.rs
- server/service/src/sync/test/test_data/name.rs
- server/service/src/sync/test/test_data/name_store_join.rs
- server/service/src/sync/test/test_data/special/name_to_name_store_join.rs
- server/service/src/sync/translation_and_integration.rs
- server/service/src/sync/translations/clinician.rs
- server/service/src/sync/translations/clinician_store_join.rs
- server/service/src/sync/translations/document.rs
- server/service/src/sync/translations/name.rs
- server/service/src/sync/translations/name_store_join.rs
Fixes #1933
Issue descrbes the reason for this change.
For Clinician, ClinicianStoreJoin, Name, NameStoreJoin and Document, align with is_sync_update logic for Requisition and Barcode:
* Remove is_sync_update field from base row type
* Add another diesel type with just id and is_sync_update field
* Add a method that updates is_sync_update field for the record
* Have a seperate upsert and sync_upsert method in repository, the later is used during sync (`translation_and_integration.rs`) instead of toggling is_sync_update to false or true through the whole codebase.
* Document repo is slightly different, there is insert method instead upsert, for other repos basically copy paste chagnes from Requisition and Barcode repo.
* Also patient update was touched (the method that turns document to …
> 1933.1 Align is sync update common

- client/packages/invoices/src/InboundShipment/DetailView/Toolbar.tsx
Fixes #1984
Don't allow user to change suppliers if the inbound shipment was created from an outbound shipment.
> 1984 I can change the Supplier on an Inbound Shipment created as part of a stock transfer 

- server/service/src/sync/test/integration/central/name_and_store_and_name_store_join.rs
- server/service/src/sync/test/integration/remote/clinician.rs
- server/service/src/sync/test/integration/remote/patient_name_and_store_and_name_store_join.rs
- server/service/src/sync/test/mod.rs
Fixes #1933
Need branch in this PR: https://github.com/openmsupply/msupply/pull/13364
Integration test fixes. Don't need to set is_sync_update anymore. Also fix compilation warning.
As per: https://github.com/openmsupply/open-msupply/blob/cf9131dfa99a27f7c407a0f99d4eba9ca2622110/server/service/src/sync/test/integration/README.MD#L47
Run: 
```bash
SYNC_SITE_PASSWORD="pass" SYNC_SITE_NAME="demo" SYNC_URL="http://localhost:2048" cargo test integration_sync  --features integration_test && SYNC_SITE_PASSWORD="pass" SYNC_SITE_NAME="demo" SYNC_URL="http://localhost:2048" cargo test integration_sync  --features integration_test, postgres
```
Integration tests pass for me
> Fix integration tests

- client/.vscode/launch.json
Don't know if anybody else had this problem but this fixes the problem that I can't debug using chrome.
This would add a ChromeDevProfile into the home directory though. Happy to choose a different name or location...
> Add user-data-dir to chrome debugging settings

- .gitignore
- server/Cargo.lock
- server/repository/Cargo.toml
- server/repository/build.rs
- server/repository/src/mock/mod.rs
- server/repository/src/test_db/constants.rs
- server/repository/src/test_db/mod.rs
- server/repository/src/test_db/postgres.rs
- server/repository/src/test_db/sqlite.rs
- server/service/src/number.rs
- server/service/src/processors/transfer/requisition/mod.rs
- server/service/src/processors/transfer/shipment/mod.rs
- server/service/src/requisition_line/response_line_stats/mod.rs
- server/service/src/test_helpers.rs
Fixes #2036 
- Caches sqlite DB for testing (DBs are cached by: migration version and if all mock data is used)
- Invalidates cache when migrations or mock data changes (using build.rs)
- Fixes sqlite memory tests
- Updates postgres tests
- When migration or mock filed have been changed, a marker file is put in all existing test_output directory indicating that the cache needs to be invalidated
- When creating a test DB: If marker file exists delete existing template DBs and the marker file
- If no template DB exists create a new one and use it for the test
- Run sqlite tests (should already be faster than before)
- Second run should be much faster since all DB are cached now
- touch a migration file or a mock file, the cache should be invalidated and template file deleted before running …
> 2036 cached test db templates

- client/packages/programs/src/JsonForms/components/EncounterLineChart.tsx
Fixes #1844
Adds the default domain when the data is unable to provide the y-axis domain values.
Create a new encounter for a patient who has only just enrolled. Then add some data and ensure that the y axis shows correctly when data is available.
I've used the range 0-100 for the defaults, even though this won't be sensible for all charts.
> Provide y-axis defaults

- client/packages/system/src/Patient/CreatePatientModal/DefaultCreatePatientJsonForm.ts
Fixes #2055
Transgender was removed from GenderInput and `Transgender Female and Transgender Male` have been added instead, so have fixed the Gender selection in Patient Creation modal. Have updated schema repo to reflect this as well.
> 2055 App crash while creating transgender patients 

- server/repository/src/test_db/constants.rs
Fix warnings
[allow(dead_code)] is needed since this file is used in build.rs as well, i.e. we can't disable by feature.
> Fix warnings

- client/packages/inventory/src/Stocktake/api/hooks/line/useStocktakeRows.ts
- client/packages/requisitions/src/RequestRequisition/DetailView/columns.ts
- server/graphql/invoice_line/src/mutations/prescription_line/insert.rs
Fixes #1982
Change the sort order for item names in stocktake view to ascending.
> 1982 Default sort for items when adding from master lists should be A--> Z rather than Z --> A 

- server/repository/src/db_diesel/document_registry_config.rs
- server/service/src/programs/ProgramEvents.md
- server/service/src/programs/update_program_document.rs
Updates the docs for the program events and the event config.
Only one minor code change: I noticed that the vector of conditions is optional which doesn't make sense and isn't used.
> Update docs and make condition vector non-optional

- server/service/src/programs/patient/patient_updated.rs
- server/service/src/programs/patient/upsert.rs
- server/service/src/sync/integrate_document.rs
Fixes #2046
Saves supplying store for patients when created on omSupply so that it shows/hides the patients if the `Patients created in other stores not visible in this store` pref is ON/OFF
Make sure both stores are `dispensaries`
> 2046 Patient created in oms are not syncing well to mSupply Desktop

- package.json
- server/service/src/sync/test/test_data/store_preference.rs
- server/service/src/sync/translations/store_preference.rs
Fixes #2083
As per commit comment, also did re-export of reference data (that's how i found the original issue)
Open [this data file](https://github.com/openmsupply/open-msupply/files/12354644/2083-706.4DD.zip) with 7.6 version of mSupply. 
initialise omSupply, try to add inbound shipment with line of pack size > 1, pack size should be changed to 1 after ok is pressed. (this doesn't happen on current main)
> 2083 Fix sync with pre 7.7 version of msupply

- client/packages/common/src/authentication/AuthContext.tsx
- client/packages/common/src/authentication/api/hooks/useLogin.ts
- client/packages/common/src/localStorage/keys.ts
- client/packages/host/src/components/Login/hooks.ts
Fixes #2099
The issue raised is due to the most recent credentials being a single object. If you are switching users then the previous user's store was being set as the current store. This overrides the user's default store - which is only used when the user hasn't previously logged in.
The change is to store every user's store when they login, and then match the username when setting the current store. If the user does not have a recent entry, then their default store is used.
You'll need at least two users, with one of them having multiple stores available.
- Clear local storage: `localStorage.removeItem('@openmsupply-client/mru/credentials');`
- Login as user_a, see that they are assigned their default store
- logout, login as user_b, see that they are assigned their default store
- …
> User should be logged in to their default store

- client/packages/programs/src/JsonForms/common/components/Array/FirstItemArray.tsx
- client/packages/programs/src/JsonForms/common/components/Array/KeyedItemArray.tsx
- client/packages/programs/src/JsonForms/common/components/Array/common.tsx
Fixes #2093 
I also added a workaround that avoid creating empty array entries for FirstItemArray and KeyedItemArray. This avoids data editing without user input, e.g. user visits the form and data is modified because an empty object had been added to the array.
- Create a new patient with minimal details
- Check in the history that contacts and contactDetails arrays are empty.
- Re-visit patient, data shouldn't be automatically modified.
- Update contact details and enter next of kin details
- Check that changes are made correctly (history view)
> 2093 keyed item array fix

- client/packages/common/src/hooks/useDebounce/index.ts
- client/packages/common/src/hooks/useDebounce/useDebounceCallback.ts
- client/packages/common/src/hooks/useDebounce/useDebouncedValueCallback.test.tsx
- client/packages/common/src/hooks/useDebounce/useDebouncedValueCallback.ts
- client/packages/common/src/ui/components/inputs/SearchBar/SearchBar.tsx
- client/packages/system/src/Patient/Components/utils.ts
Fixes #2116 
My previous fix to 'correct' the debounceCallback hook has caused trouble.
I've reverted that change, which fixes this issue. 
Then I've implemented a new hook, which debounces the callback function in a way that I would expect it to - so that the search functions can use it. The trouble with the original hook is that it is recreated when the dependencies change, which resulted in a search being called on every keystroke. The new hook will wait for a time to elapse and execute the callback once, with the final value. This is better when calling a search api.
Follow the steps in the issue, when changing values in stock lines for outbound shipments and prescriptions.
Then try to search for a patient in the create prescription modal. The search api endpoint should only be called …
> Improve debouncing

- server/graphql/general/src/queries/stock_counts.rs
Fixes #2123 
The `expiring_soon` count is including stock which is already expired, though the wording change on the dashboard says that the stock is expiring in the next month.
Have reduced the expiring count by the count of expired stock, giving this:
or
> Exclude expired when counting expiring stock

- server/service/src/programs/program_enrolment/upsert.rs
Related to #2023
While doing #2023 I noticed that you get an error when enrolling a mSupply patient without a document. This PR checks if the patient exists and not if the patient document exists. For example, enrolling a patient from the Harry P dataset will now work without first editing the patient details.
> Fix program enrolment for a patient that doesn't has a document

- client/packages/system/src/Encounter/ListView/ListView.tsx
- client/packages/system/src/Patient/Encounter/ListView.tsx
- client/packages/system/src/Patient/ProgramEnrolment/Components/ListView.tsx
Fixes #2144
Uses the pagination from useUrlQueryParams for encounter and program enrolment lists.
Testing:
- pagination, filter, and sort works for both encounter lists and the program enrolment list
> Use pagination from useUrlQueryParams

- client/packages/programs/src/index.ts
- client/packages/programs/src/utils.ts
- client/packages/system/src/Encounter/ListView/columns.ts
- client/packages/system/src/Patient/ProgramEnrolment/Components/ListView.tsx
Fixes #1270 
Only display events with a type starting with "status".
Also fixes the use of a hook which was passed as a function...
For testing, create a remote server with program config, e.g. `./dev_server_schema_update.sh`
- Enrol into HIV Care and create an encounter way in the base, e.g. a year back
- In ARV medication section dispense some pills
- In Viral Load section enter some VL results
- Enrolment list should show "LTFU"
- Encounter list should show "VL Result"
> Only show events that have type starting with "status"

- client/packages/system/src/MasterList/Components/MasterListSearchModal/MasterListSearchModal.tsx
Fixes #1666
Refetch MasterList every time the modal is opened.
> #1666 Master lists in outbound shipment doesn't update when changing supplier

- client/packages/inventory/src/Stocktake/ListView/ListView.tsx
- client/packages/invoices/src/InboundShipment/ListView/ListView.tsx
- client/packages/invoices/src/OutboundShipment/ListView/ListView.tsx
- client/packages/invoices/src/Prescriptions/ListView/ListView.tsx
- client/packages/requisitions/src/RequestRequisition/ListView/ListView.tsx
- client/packages/system/src/Item/ListView/ListView.tsx
- client/packages/system/src/Location/ListView/ListView.tsx
- client/packages/system/src/Location/api/api.ts
- client/packages/system/src/Location/api/operations.generated.ts
- client/packages/system/src/Location/api/operations.graphql
- client/packages/system/src/MasterList/ListView/ListView.tsx
- client/packages/system/src/Name/ListView/ListView.tsx
- client/packages/system/src/Patient/ListView/ListView.tsx
- client/packages/system/src/Patient/ProgramEnrolment/Components/ListView.tsx
- client/packages/system/src/Report/ListView/ListView.tsx
Fixes #1693 
Add offset and first to locations hook to get the ListView to paginate properly.
> 1693 For locations, limit of records per page doesn't seem to be respected

- client/packages/common/src/ui/components/navigation/Tabs/ModalTab.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/ReponseStats/ResponseStoreStats.tsx
Fixes #2145
Quick fix -- seems to work fine after removing the `height: "100%"` props from ModalTabs. Not sure if this might cause problems somewhere else -- can you think of why it might have been necessary @mark-prins 
Tested on Firefox and Chrome, in Requisitions -> requisition -> item line modal.
Please see if you can think of any potential regressions.
> Fix requested quantity display in Firefox

- client/packages/invoices/src/InboundShipment/api/hooks/document/useNextItem.ts
Fixes #2151 
Make `Ok & Next` button go to the next item on the list even if the list has been resorted for inbound invoices.
> 2151 When lines are sorted, the Ok&Next button should respect the sorted sequence in Inbound shipment

- server/service/src/login.rs
Fixes #2173 
Found while checking out #2106 
Map `AddPatient` permission since users might be allowed to add patients but not edit them 🤷🏻  + fix mis-mapped `AddStocktakeLines` permission
Should be able to add a patient without edit patient permission
> 2173 Add missing AddPatient Permission

- client/packages/programs/src/JsonForms/common/components/Array/Notes.tsx
Fixes #2141
Updated the check to actually *use* the maxAge value (instead of the hard-coded 1 day), and use `Infinity` as a fallback if `maxAge` is not specified (i.e. can always be edited)
Tested with "Notes" on Patient JSON Form (PNG schema).
- Checked correct behaviour with new notes (can be edited) and after setting the created date to more than one day
- Manually changed UI JsonSchema to remove `maxAge` property --notes are always editable
> #2141 Fix Notes maxAge edit restriction

- client/packages/programs/src/JsonForms/components/EnrolmentId.tsx
- client/packages/programs/src/JsonForms/useJsonForms.tsx
- client/packages/programs/src/api/api.ts
Fixes #2170
Add missing control for the HIV testing encounter. The control shows the enrolment ID of a certain enrolment type.
This control will also be needed for contact tracing entries. However, it will some tweaking to get the contact's patient id then...
Create a HIV testing encounter adn got to: "Hiv Testing" and select Result "Positive". The ART Number should show up (but blank).
Enrol into a the HIV care encounter and assign a enrolment id during enrolment. Going back to the testing encounter, the ART Number should now show a value.
> Add a EnrolmentId control

- server/repository/src/migrations/v1_02_00/sensor.rs
- server/repository/src/mock/mod.rs
- server/repository/src/mock/temperature_breach.rs
- server/repository/src/mock/temperature_breach_config.rs
- server/repository/src/mock/temperature_log.rs
- server/service/src/sync/test/mod.rs
- server/service/src/sync/test/test_data/mod.rs
- server/service/src/sync/test/test_data/temperature_breach.rs
- server/service/src/sync/test/test_data/temperature_breach_config.rs
- server/service/src/sync/test/test_data/temperature_log.rs
- server/service/src/sync/translation_and_integration.rs
- server/service/src/sync/translations/mod.rs
- server/service/src/sync/translations/temperature_breach.rs
- server/service/src/sync/translations/temperature_breach_config.rs
- server/service/src/sync/translations/temperature_log.rs
Fixes part of #1955
Add in sync for `temperature_log`, `temperature_breach` and `temperature_breach_config`
Just the automated tests, like any other sync table
> 1955 temperature sensor sync for temperature logs and breaches

- client/packages/common/src/utils/arrays/ArrayUtils.ts
- client/packages/system/src/Item/Components/ItemVariant/PackUnitQuantityCell.tsx
- client/packages/system/src/Item/Components/ItemVariant/PackUnitSelectCell.tsx
- client/packages/system/src/Item/Components/ItemVariant/index.ts
- client/packages/system/src/Item/ListView/ListView.tsx
- client/packages/system/src/Item/api/operations.generated.ts
- client/packages/system/src/Item/api/operations.graphql
- client/packages/system/src/Item/context/useUnitVariant.ts
- server/cli/src/refresh_dates.rs
- server/graphql/general/src/queries/item_variant.rs
Fixes #2156
Add drop down unit variant selector to item list and adjusts quantities based on the selected variant. Also moved sync log datetime to be excluded in refresh date cli, see test description.
Initialise from reference data:
```
cargo run --bin remote_server_cli -- initialise-from-export -n reference1
```
then refresh dates
```
cargo run --bin remote_server_cli -- refresh-dates
```
Check out item view as per screenshot above, try changing unit variants, see stats column reflect selected variant. Also selected variant will be saved, but not in app data (not on refresh, but if navigating to another page through menu), saving userSelected through app data will be added in next task, I added this to epic (btw without user selected, should default to calculated by server, as per mock …
> Add drop down unit variant selector

- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/types/schema.ts
- client/packages/system/src/Item/Components/ItemVariant/PackUnitCell.tsx
- client/packages/system/src/Item/Components/ItemVariant/PackUnitQuantityCell.tsx
- client/packages/system/src/Item/Components/ItemVariant/PackUnitSelectCell.tsx
- client/packages/system/src/Item/ListView/ListView.tsx
- client/packages/system/src/Item/api/operations.generated.ts
- client/packages/system/src/Item/api/operations.graphql
- client/packages/system/src/Item/context/useUnitVariant.ts
- client/packages/system/src/Stock/ListView/ListView.tsx
- server/graphql/general/src/queries/item_variant.rs
Fixes #2176
Simplifies and aligns pack unit display, as per this comment https://github.com/openmsupply/open-msupply/pull/2157#pullrequestreview-1603540024
Initialise from reference data:
```
cargo run --bin remote_server_cli -- initialise-from-export -n reference1
```
Then look at items in stock view and in item list view, you should see the following:
* If there is a unit variant matching item and packs size, it should show variant short name (mock variants are here: https://github.com/openmsupply/open-msupply/blob/daae2622b06ea64ccaadf5ba8888069f3b58e541/server/graphql/general/src/queries/item_variant.rs#L18)
* if there is a unit name, show as 1 tab instead of just tab (or 100 tabs etc)
* if there isn't a unit name, show 1 unit (or 100 units etc)
> Improve pack unit display

- client/packages/common/src/ui/components/inputs/Autocomplete/Autocomplete.stories.tsx
- client/packages/common/src/ui/components/inputs/Autocomplete/Autocomplete.tsx
- client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteWithPagination.tsx
- client/packages/common/src/ui/components/inputs/Autocomplete/components.tsx
- client/packages/common/src/ui/components/inputs/Autocomplete/index.ts
- client/packages/common/src/utils/arrays/ArrayUtils.ts
- client/packages/system/src/Item/Components/StockItemSearchInput/StockItemSearchInput.tsx
- client/packages/system/src/Item/Components/StockItemSearchInput/hooks.ts
- client/packages/system/src/Item/api/hooks/useItemStockOnHand/useItemStockOnHand.tsx
- client/packages/system/src/Item/api/operations.generated.ts
- client/packages/system/src/Item/api/operations.graphql
- package.json
Fixes #2158 
- Loads stock items asynchronously with the help of pagination for a large dataset
- Handles search to the back when a user types in the autocomplete field
Follow the reproducible steps in the #2158 to test
We faced the same issue in the [health supply hub](https://github.com/openmsupply/health-supply-hub/issues/1030) and thought to solve with same approach here as well by async loading of autocomplete list records with the help of the pagination.
or
> 2158 fix stock item search autocomplete limit list with pagination

- client/packages/common/src/intl/locales/en/dispensary.json
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEdit.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/hooks/useDraftOutboundLines.tsx
- client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/PrescriptionLineEditForm.tsx
Fixes #2210 
Display no stock available message for prescription and outbound shipments (see screenshots below). Have also hid the prescriptions note component if there is no stock line for that item.
> 2210 The "no stock available" message needs to be set for prescriptions

- client/packages/common/src/types/schema.ts
- client/packages/programs/src/JsonForms/components/AdherenceScore.tsx
- client/packages/programs/src/api/api.ts
- client/packages/programs/src/api/hooks/document/useProgramEnrolments.ts
- client/packages/programs/src/api/operations.generated.ts
- client/packages/programs/src/api/operations.graphql
- client/packages/system/src/Encounter/ListView/columns.ts
- client/packages/system/src/Patient/ProgramEnrolment/Components/ListView.tsx
- server/graphql/programs/src/lib.rs
- server/graphql/programs/src/queries/program_event.rs
- server/graphql/types/src/types/program/encounter.rs
- server/graphql/types/src/types/program/program_enrolment.rs
- server/graphql/types/src/types/program/program_event.rs
- server/repository/src/db_diesel/program_event.rs
Various changes needed for reports.
- Add option to filter by data
- For consistency use ProgramEventResponse for active_program_events and program_events (all UI updates are because of this)
- Update/add active_start_datetime, active_end_datetime fields in ProgramEventNode
Part of https://github.com/openmsupply/open-msupply-reports/issues/35
- Programs and encounters should still show without error (e.g. for HIV care)
> Add programEvents node to the EncounterNode + misc related updates

- client/packages/common/src/intl/locales/en/replenishment.json
- client/packages/common/src/types/schema.ts
- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/ItemCharts/ConsumptionHistory.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/ItemCharts/StockDistribution.tsx
- client/packages/requisitions/src/RequestRequisition/api/operations.generated.ts
- client/packages/requisitions/src/RequestRequisition/api/operations.graphql
- server/graphql/types/src/types/item_chart.rs
- server/graphql/types/src/types/requisition_line.rs
- server/service/src/requisition_line/chart/mod.rs
Fixes #2194 #2195 
Added the next month to the chart; so the chart now shows 13 months - the current month, 11 months of historical data and a projection for next month.
Found that the `is_current` property was not set correctly, so have fixed that and added support for it in the front end.
Unable to replicate the issue with the bar chart though. and the internal order mentioned in the issue has had the item removed.
I took a backup of the demo server and tested against that. You should be able to replicate by adding a large quantity of an item to an outbound shipment and setting the status to picked.
> Update internal order consumption chart

- client/packages/common/src/intl/locales/en/distribution.json
- client/packages/requisitions/src/ResponseRequisition/DetailView/Footer/Footer.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/Footer/StatusChangeButton.tsx
Fixes #1737
Confirmation message suddenly started working again... but have added an extra message if the requisition hasn't been fully supplied to make it clearer to users...
> 1737 Requisitions - Confirmation message on Finalisation

- server/service/src/stocktake/update.rs
Fixes #1302
Prune uncounted stocktake lines on finalisation... not pruning lines with counted_nums == snapshot_num for now since technically they counted it... Open for discussion~
> 1302 Uncounted stocktake lines should be pruned on finalise

- client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEdit.tsx
- client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useStocktakeLineEdit.ts
Fixes #1117
Quick fix 😆 ... Add new batch to the top instead of the bottom
> 1117 When you add a new batch to a stocktake line, it gets added to the end (and is hard to notice)

- client/packages/common/src/intl/locales/en/dispensary.json
- client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/PrescriptionLineEditForm.tsx
- client/packages/invoices/src/Prescriptions/DetailView/columns.ts
Fixes #2235
Rename note to directions
> 2235 Rename the "Notes" field on prescriptions to be "Directions"

- client/packages/common/src/types/schema.ts
- client/packages/programs/src/JsonForms/components/AdherenceScore.tsx
- client/packages/programs/src/JsonForms/components/EnrolmentId.tsx
- client/packages/programs/src/JsonForms/components/ProgramEvent.tsx
- client/packages/programs/src/api/api.ts
- client/packages/programs/src/api/operations.generated.ts
- client/packages/programs/src/api/operations.graphql
- server/graphql/types/src/types/program/program_event.rs
Fixes more points of #2103
- Display partner HTC number (currently not working because we don't record a number right now, please ignore for now...)
- Display partner ART number
- Display HTC testing result
- Display HTC testing result date
**please use the `2103-show-partner-htc-art-info` branch in the schema repo**
- Enrol a patient A into an ART program and assign an enrolment id
- Enrol patient A into testing program, create a testing encounter (encounter must be in the past) and enter HIV test results
- Go to a second patient B and add a contact tracing entry
- Link patient A to the contact trace of patient B
-  Go to the Tracking Outcome section of the contact tracing form. There should be three new controls displaying the previously entered information about the partner
> 2103 show partner htc art info

- server/graphql/programs/src/mutations/patient/insert.rs
- server/service/src/programs/patient/insert_patient.rs
- server/service/src/programs/patient/mod.rs
- server/service/src/programs/patient/update_patient.rs
Fixes #2236
The patient's full name wasn't being updated even though their first name and last name have, so have updated their full name too.
> 2236 Edits to patient names don't seem to update on past prescriptions

- client/packages/invoices/src/OutboundShipment/api/api.ts
Fixes #2221 
Fix the logic for getting `deleteOutboundShipmentUnallocatedLines` array to delete placeholder while saving outbound shipment line with stock.
1. Go to outbound shipments
2. Add items from master list
3. Edit item that has stock, allocate quantity
4. Click OK > back in the list the placeholder will be replaced by the line with stock filled in
> 2221 Remove placeholder on editing outbound shipment stock

- client/packages/system/src/Patient/ListView/AppBarButtons.tsx
- client/packages/system/src/Patient/PatientView/Footer.tsx
- server/service/src/apis/permissions.rs
- server/service/src/login.rs
Fixes #2106
Separates the QueryPatient Permission from MutatePatient Permission.
Needs [this branch from mSupply](https://github.com/openmsupply/msupply/tree/%2313592-View-patient-permission-based-on-Edit-patient-details-user-permission) to test. Should still be able to view patients
Probably should be merged into main? And needs above branch before merge
> 2106 Separate QueryPatient permission from EditPatient

- client/packages/common/src/ui/layout/tables/context/TableContext.tsx
- client/packages/common/src/ui/layout/tables/context/hooks/index.ts
- client/packages/common/src/ui/layout/tables/context/hooks/useRowHighlight.tsx
- client/packages/common/src/ui/layout/tables/index.ts
- client/packages/inventory/src/Stocktake/DetailView/ContentArea/ContentArea.tsx
- client/packages/inventory/src/Stocktake/DetailView/DetailView.tsx
- client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEdit.tsx
Fixes #2226 
A change was made to the highlighting of row styles in the `StocktakeLineEdit` which reset the styles of all rows.
I've reverted that change to fix the problem raised in the issue.
The change had also broken the 'highlight on Ok' feature, so I've fixed that.
As a bonus, I've fixed the highlighting so that it now works when the rows are grouped by item too.
I then went and refactored to make the highlighting function available for other lists of data, because I think the highlight is pretty neat.
https://github.com/openmsupply/open-msupply/assets/9192912/0cb863bd-79dd-4ae4-88b3-3ca3a373d3a3
Edit a stocktake which has placeholder rows. Click on a row and then click `OK` on the modal.
This will
- retain the blue for placeholder rows
- show a 1.5s highlight animation on the …
> Fix stocktake row highlight and placeholder colour

- client/packages/programs/src/JsonForms/common/JsonForm.tsx
- client/packages/programs/src/JsonForms/common/components/Array/Notes.tsx
- client/packages/programs/src/JsonForms/components/EnrolmentId.tsx
- client/packages/programs/src/JsonForms/components/ProgramEvent.tsx
- client/packages/programs/src/JsonForms/useJsonForms.tsx
Bug fix from #2067
For contact tracing, the components displayed the data from a random patient if the patient wasn't linked yet...
- Enrol at least one patient into ART program enrolment.
- Create a contact trace for this patient (or a different patient) without linking it to a patient
- In the "Tracking Outcome" section the last four field should be empty (not like in the screenshot)
> Fix lookup when patient id is not found

- client/packages/common/src/ui/layout/tables/DataTable.tsx
Fixes #2248 
Stops the shaking by disabling the viewport when expando is being used. It's the combination of having an expandable row expanded and scrolling down which triggers the viewport, this re-renders, but the expanded row isn't expanded, then it is, then it re-renders etc.
The fix is based on the assumption that the data table usages which have an expando row are smaller in size and won't need the viewport to speed up loading. The viewport renders only those rows which are visible on screen - when you scroll, the next set of rows is rendered. This greatly speeds up the render for long lists, but does have some drawbacks
Apologies for picking up a non-triaged issue.. it seemed like a serious enough one to warrant the attention.
> Stop the data table shakes

- client/packages/common/src/plugins/components/PluginLoader.tsx
- client/packages/common/src/plugins/components/PluginProvider.tsx
- client/packages/common/src/plugins/hooks/usePluginColumns.ts
- client/packages/common/src/plugins/hooks/usePluginElements.tsx
- client/packages/common/src/plugins/index.ts
- client/packages/common/src/plugins/types.ts
- client/packages/common/src/plugins/utils.tsx
- client/packages/common/src/utils/BarcodeScannerContext.tsx
- client/packages/host/src/plugins/useInitPlugins.ts
Fixes #2250
Updates the types - and changes the component and column plugins to be an async function which returns a promise.
The local and remote are then treated similarly, and the column and component plugins are also treated in the same way as each other.
I've also tweaked the error handling, so that the PluginLoader doesn't throw and error if there's a problem in the async method call.
I've used the plugin example branch to test, and have broken the plugins to check that the error handling works.
> Change plugin types

- client/packages/common/src/ui/forms/Detail/InputWithLabelRow.tsx
- client/packages/programs/src/JsonForms/common/JsonForm.tsx
- client/packages/programs/src/JsonForms/common/styleConstants.ts
Fixes #2128
I'm not particularly thrilled with this approach, but I can't see a better way to target the JSONForms Material-UI containers without creating custom renderers for each, which would be overkill for such minor tweaks.
Adds a maxWidth to the form columns so it looks a bit better when there's only one column.
Have also played with the heading styles a bit so they stay more closely tied to their contents. Open to suggestions as to whether this is better or not (I think it is in most cases, but there's bound to be exceptions).
How it looks now with a single column:
And with multiple columns:
Test single column by re-initialising DB with no Programs data.
Test multi-column by running the programschema script to add Programs data
Check that this hasn't caused problems elsewhere.
> #2128 Improve JSON Forms column layout

- client/packages/common/src/ui/components/inputs/SearchBar/SearchBar.tsx
Fixes #2205
The changing width of the search button prevents the action on the end adornment. Personally, I'd be happy to remove the width change, but I've retained it, and added a delay to the width transition.
Note: I tried taking [this fix](https://github.com/openmsupply/health-supply-hub/issues/1006) but the input adornment does not make a difference in our case.
Try to search, clear the search input. The input should clear even if the input has focus.
> Fix the searchbar clear button

- client/packages/system/src/Location/ListView/LocationEditModal/LocationEditModal.tsx
Fixes #1605 
Remove leading and trailing whitespaces from location name and code to ensure that the Ok/Ok & Next button still stays disabled if users just put whitespace for name and code
> Remove whitespace from location name and code

- client/packages/programs/src/JsonForms/common/JsonForm.tsx
Fixes #2294
Very small tweak to address an oversight from #2259. I've now moved the `alignItems: 'flex-start'` property inside the "class" definition so it doesn't affect everything, only the actual input elements.
Checked visually the layout of:
- Encounter summary bubbles -- displays at it did before
- Patient view when limited patient data (base info only) -- displays as it did as a result of #2259
> #2294 Fix Encounter layout regression

- server/service/src/sync/translations/report.rs
Fixes #2331 
This fixes an issue on the demo server where report with argument schemas went missing. Just tested on the ,new program demo and this fixes the issue.
> Add missing integration dependency

- client/packages/inventory/src/Stocktake/DetailView/Toolbar.tsx
- server/service/src/stocktake/insert.rs
Fixes #2289
Disable stocktake date in stocktake detail view.. Also noted that the date isn't being saved right now... Should it be the same as created datetime for now?
> 2289 Stocktake : Modifiable stocktake date

- client/packages/common/src/utils/environment/EnvUtils.ts
- client/packages/host/src/components/AppDrawer/AppDrawer.tsx
- client/packages/host/src/utils.ts
Fixes #2243 
Adds a custom hook to detect if the user device is mobile. Maybe there is something like this already in the app? I couldn't see it though. 
You can test this by going to dashboard, opening dev tools, and selecting a mobile (ipad) dimensions.
Try interacting with the appbar as outlined in the video of #2243 
You can then compare develop branch to this branch, and see the functionality difference.
There is a risk that the mobile checking isn't an exhaustive list, so might need to be updated.
Alternatively, we could use a package like https://www.npmjs.com/package/react-device-detect
I also wondered if there were other mouse specific interactions which wouldn't be appropriate for mobile which could also benefit from this hook, but can't see anything at a glance.
> Add useDeviceDetect hook. Fix wrong navigation

- client/packages/common/src/ui/components/domain/Dashboard/StatsPanel.tsx
- client/packages/common/src/ui/components/navigation/AppNavLink/SimpleLink.tsx
- client/packages/common/src/ui/components/navigation/AppNavLink/StyleFreeLink.tsx
- client/packages/dashboard/src/widgets/DistributionWidget.tsx
- client/packages/dashboard/src/widgets/ReplenishmentWidget.tsx
- client/packages/dashboard/src/widgets/StockWidget.tsx
Fixes #2212 
Adds links to dashboard 
I've made a generic link component which doesn't add the usual mui Link styling.
Maybe it is better to put this only in the StatsPanel component as this is the only place it is being used currently.
> 2212 add links to headings in dashboard

- client/packages/common/src/intl/locales/en/common.json
- client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts
- client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts
- client/packages/invoices/src/OutboundShipment/DetailView/columns.ts
- client/packages/invoices/src/Prescriptions/DetailView/columns.ts
Fixes #2278
Adds a location column to the stocktake detail view, fixed [multiple] showing up for empty reasons, added [multiple] to translation and show [multiple] for invoice lines that have batches in different locations in inbound, outbound and prescriptions
Louisa suggested that the locations column for stocktake be moved to the left of `code`, but that would be inconsistent with our other views, so unsure if we should move or not... Locations still seem viewable when I view on a tablet screen size, so might be alright?
> 2278 Location function in stocktake

- client/packages/common/src/ui/components/inputs/CurrencyInput/CurrencyInput.tsx
Fixes #2328 
Adds an intermediate currency input state which allows decimal inputs
Parses a formatted currency to the StockLineRowFragment type.
You can test this by trying to type decimals into the stock line details modal
I don't really understand how I've gotten this to work, and would love if anyone would be willing to explain to me (if they have time.
Specifically I'm struggling to understand why it is allowing decimals, but not other inputs ie '/'
I also don't have a clear understanding of the {...restOfProps} passing into StyledCurrencyInput. There are so many props! 
was the displaying value being passed in this massive lump of props initially?
> Add preliminary raw currency state which allows decimal point

- client/packages/common/src/types/schema.ts
- client/packages/programs/src/hooks/usePatientStore.ts
- client/packages/system/src/Patient/CreatePatientModal/PatientFormTab.tsx
- client/packages/system/src/Patient/DefaultPatientSchema.json
- client/packages/system/src/Patient/DefaultPatientUISchema.json
- client/packages/system/src/Patient/PatientView/PatientView.tsx
- client/packages/system/src/Patient/api/operations.generated.ts
- client/packages/system/src/Patient/api/operations.graphql
- server/graphql/programs/src/mutations/patient/insert.rs
- server/graphql/programs/src/mutations/patient/update.rs
- server/service/src/programs/patient/insert_patient.rs
- server/service/src/programs/patient/update_patient.rs
Fixes #2333 
Adds extra fields to patient create and update forms.
Adds these fields to the graphql insert and update schema
Also adds isDeceased and dateOfDeath to graphql schema (minor fix)
There is currently no validation for address or phone number.
I considered adding a simple regex expression for phone number, but now I wonder if it would be better to leave for a separate issue where a new plugin could be added for validation in case something more dynamic is required for localisations.
> 2333  add new fields to patient window

- server/service/src/sync/settings.rs
Fixes #2304
To be reviewed together with the mSupply PR: https://github.com/openmsupply/msupply/pull/13759
Reproduce problem:
- Checkout omSupply `develop`
- Checkout mSupply `V7-07-00`
- Try to sync -> no names should be synced and there should be error msg in the logs
Actual test:
- Checkout mSupply `2304-update-api-versions`
- Try to sync -> should fail with version mismatch error
- Checkout this branch -> sync should work now and (names are in the DB)
> Update sync api version

- client/packages/common/src/ui/components/inputs/CurrencyInput/CurrencyInput.tsx
Fixes #2328 
I had a look at the merged fix for the above issue, and now that I've poked around, think that I have a simpler solution. 
As noted in the PR comments, the original issue is that the text value of the input field is being parsed as a number and this is fed back to the input `value` prop. The net effect is that typing in `2.` will set the input value to `2` and then if you type another digit, the decimal separator is 'lost'. 
Rather than store the value in local state, I've removed the `value` prop which is passed into the CurrencyInput component. That is now used to set the DefaultValue if a default is not provided, and is otherwise ignored. The input is already handling state internally, so there's no need to lift that out.
Try to type a decimal currency into any of the …
> Simplify currency fix

- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/ui/components/inputs/TextInput/BasicTextInput.tsx
- client/packages/common/src/ui/components/inputs/TextInput/numeric/NumericTextInput.tsx
- client/packages/common/src/ui/layout/tables/components/index.tsx
- client/packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.ts
- client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/InboundLineEdit.tsx
- client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabLayout.tsx
- client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
- client/packages/invoices/src/InboundShipment/DetailView/modals/utils.ts
- client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/PrescriptionLineEditForm.tsx
- client/packages/invoices/src/index.ts
- client/packages/system/src/Item/Components/ItemVariant/PackUnitEntryCell.tsx
- client/packages/system/src/Item/Components/ItemVariant/index.ts
- client/packages/system/src/Item/Components/index.ts
- client/packages/system/src/Item/context/useUnitVariant.ts
Fixes #2208
https://github.com/openmsupply/open-msupply/assets/26194949/1f9a7342-af49-4179-87bb-b347e4faec08
Creates input for pack size, using unit packs configurations.
If unit pack variants are configured for item, then a select drop down is added. (for now inbound shipment only, but should also be in stocktake).
Also uses unit variant 'active' packSize, if exists, in favour to defaultPackSize on item.
init database with: `cargo run --bin remote_server_cli -- initialise-from-export -n reference1`
Create new inbound shipment and add lines, for [these items](https://github.com/openmsupply/open-msupply/blob/182464d70543241a42b96b5e825912d58b335fa0/server/graphql/general/src/queries/item_variant.rs#L18) a drop down should be added. Drop down current variant should match the pack size that …
> 2208 add pack entry

- client/packages/common/src/hooks/useBreadcrumbs/useBreadcrumbs.tsx
- client/packages/common/src/ui/components/navigation/Breadcrumbs/Breadcrumbs.tsx
- client/packages/host/src/routers/DispensaryRouter.tsx
- client/packages/system/src/ContactTrace/DetailView/DetailView.tsx
Fixes #2322
Adds another route which will redirect `/dispensary/contact-trace` to the patient list view.
Add a contact, and click on the breadcrumb:
- Root part ( saying 'Contact Tracing' ) takes you to a list of patients
- Patient name takes you to the patient detail view
> Add routing for contact-trace

- server/graphql/general/src/queries/plugin.rs
- server/server/src/static_files.rs
- server/service/src/plugin_files.rs
Fixes #2191 
Changes in this PR
- Rename `find_file` to `find_plugin` in `plugin_files.rs`
- add an unwrap 
- Remove `clone` 
- Remove method 
- Don't have optional filename
and not changed:
- Don't validate plugin exists in rest plugins endpoint
because the `plugin.json` is required and the plugin won't load without it.
You can query the plugins:
```
query plugins {
plugins {
config
name
path
}
}
```
and that should still work. ( you may want to copy the plugins from `feature/front-end-plugins-example` )
You can also request a specific plugin e.g. `http://localhost:8000/plugins/ShippingStatus/ShippingStatus.js`
and can also get an invalid response if you request something that doesn't exist.
or
> review changes

- client/packages/programs/src/JsonForms/common/components/CategorizationTabLayout.tsx
Fixes #1268
Fixes width of component changing because of error
> 1268 Error changes size of component

- client/packages/programs/src/JsonForms/common/components/Date.tsx
- client/packages/programs/src/JsonForms/components/DateOfBirth.tsx
Fixes #2316 
Initially I was curious as to why the patient form was using the 'Date' component rather than the 'DateOfBirth' picker component to set the patient's DOB.
In the end I opted to go for changing just the 'Date' component rather than 'DateOfBirth'  as the 'DateOfBirth' component includes an age display that might not fit with the patient form.
The clearing button is very unobtrusive as it is part of the date picker modal, and seems like it wouldn't ever be obtrusive.
Possibly this could also be used in the dateOfBirth date picker component in a future issue? (I'm not sure where this is currently being used)
Adds  simple fix to clear date
> Update date component

- client/packages/invoices/src/OutboundShipment/DetailView/Toolbar.tsx
Fixes #2393
Disable customer name if outbound shipment has been created from a requisition
> 2393 Customer Name to be locked in and non-changeable when you select create shipment 

- server/service/src/sync/test/integration/remote/activity_log.rs
- server/service/src/sync/translations/program_requisition_settings.rs
Fixes #2407 
Make the storeTags optional. Reason is that mSupply can't handle and empty storeTags object right now.
> Make store tags optional

- client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/BreachIcon.tsx
- client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/BreachPopover.tsx
- client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/TemperatureChart.tsx
- client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/useTemperatureChartData.ts
- client/packages/coldchain/src/Monitoring/api/TemperatureBreach/operations.generated.ts
- client/packages/coldchain/src/Monitoring/api/TemperatureBreach/operations.graphql
- client/packages/coldchain/src/Monitoring/api/TemperatureLog/operations.generated.ts
- client/packages/coldchain/src/Monitoring/api/TemperatureLog/operations.graphql
Fixes #2369
The temperature logs query was loading a `sensor` for each log entry. 
Each `sensor` would then load the `latest_temperature_log` which queried `temperature_log`s from the database, with a filter and sort to fetch the latest one.
The end result was that a query for 100 temperature logs would run 100 database queries for temperature logs. Slimming down the graphQL query has resulted in an almost instant query response.
Fetch a list of temperature logs (the `Log` or `Chart` tabs) and see how long that takes. Try again with this branch.
You could also put a `println` into the `temperature_log` query to see how often this is called.
> Remove recursive loading in temperature logs

- client/packages/common/src/authentication/api/hooks/useLogin.ts
- client/packages/common/src/localStorage/keys.ts
- client/packages/common/src/localStorage/useLocalStorage.ts
- client/packages/system/src/Item/context/useUnitVariant.ts
Part of #2313 
Stores the user selected variant in the local storage. This is stored per user and per store.
Create a database like:
`cargo run --bin remote_server_cli -- initialise-from-export -n reference1`
and manually apply sql:
```sql
INSERT INTO pack_unit ("id", "item_id", "short_name", "long_name", "pack_size") VALUES ('amo-one', 'E43D125F51DE4355AE1233DA449ED08A', 'tab', 'tablet', 1);
INSERT INTO pack_unit ("id", "item_id", "short_name", "long_name", "pack_size") VALUES ('amo-ten', 'E43D125F51DE4355AE1233DA449ED08A', 'blist of 10 tabs', 'blister of 10 tablets', 10);
INSERT INTO pack_unit ("id", "item_id", "short_name", "long_name", "pack_size") VALUES ('amo-50', 'E43D125F51DE4355AE1233DA449ED08A', 'box of 5 blist', 'box of 5 blist', 50);
INSERT INTO pack_unit ("id", "item_id", …
```
> Store user selected variants in the local storage

- client/packages/coldchain/src/Monitoring/ListView/TemperatureBreach/TemperatureBreachList.tsx
- client/packages/coldchain/src/Monitoring/api/TemperatureBreach/operations.generated.ts
- client/packages/coldchain/src/Monitoring/api/TemperatureBreach/operations.graphql
- client/packages/coldchain/src/Monitoring/api/TemperatureLog/operations.generated.ts
- client/packages/coldchain/src/Sensor/api/api.ts
- client/packages/common/src/types/schema.ts
- server/graphql/sensor/src/mutations/update.rs
- server/graphql/temperature_breach/src/lib.rs
- server/graphql/types/src/types/temperature_breach.rs
- server/repository/src/db_diesel/temperature_breach_row.rs
- server/repository/src/migrations/v1_05_00/cold_chain.rs
- server/repository/src/migrations/v1_05_00/permissions_preferences.rs
- server/repository/src/migrations/v1_05_00/sensor.rs
- server/repository/src/mock/temperature_breach.rs
- server/server/src/cold_chain/sensor.rs
- server/service/src/sensor/tests/update.rs
- server/service/src/sensor/update.rs
- server/service/src/sync/test/test_data/temperature_breach.rs
- server/service/src/sync/translations/temperature_breach.rs
Fixes #2405 
Rename duration fields in temperature breach to include unit.
Should threshold_min/max on temperature_breach also be renamed to add temperature? It took me a bit of browsing around to find out what the thresholds were for.
Also, temperature breach config got deleted in a PR a while back.... so can rename the duration fields for that when it get re-implemented..
> 2405 Rename duration fields to also include the unit

- client/packages/coldchain/src/Sensor/Components/SensorLineForm.tsx
- client/packages/common/src/utils/functions/ApiUtils.tsx
- client/packages/system/src/Location/Components/LocationSearchInput.tsx
- client/packages/system/src/Location/ListView/Toolbar.tsx
Fixes #2418 
I also noticed that this happens when you try to delete a location which is assigned to a sensor:
- When there are no locations, display a message saying that there are no locations
- Make the 'Remove' option, well, optional (only implemented for Sensors, so only enabled for them)
- Make the 'Remove' option look nicer
- Fix the removal of locations for sensors
- Catch the location delete error (bonus task)
---
**No locations**
---
**Locations, none selected**
---
**Locations, with one selected**
Try to assign locations to a sensor, then remove.
Check stock line editing and repacks - these will not have the 'remove' option ( it doesn't work for them, so needed removing! )
Check when there are no locations
> LocationSearchInput fixes

- client/packages/coldchain/src/Sensor/ListView/AppBarButtons.tsx
- client/packages/coldchain/src/Sensor/ListView/ListView.tsx
- client/packages/common/src/intl/locales/en/common.json
- client/packages/config/src/config.ts
- server/Cargo.lock
- server/Cargo.toml
- server/cli/Cargo.toml
- server/graphql/form_schema/Cargo.toml
- server/graphql/repack/Cargo.toml
- server/graphql/reports/Cargo.toml
- server/report_builder/Cargo.toml
- server/repository/Cargo.toml
- server/server/Cargo.toml
- server/server/src/lib.rs
- server/server/src/upload_fridge_tag.rs
- server/service/Cargo.toml
- server/service/src/sensor/berlinger.rs
- server/service/src/static_files.rs
- server/util/Cargo.toml
- server/util/src/file.rs
- server/util/src/lib.rs
Fixes #2420 
Add upload fridgetag button to top left of sensor list. When fridgetag file is selected it will be uploaded and then integrated.
It's branched from this PR: ~~https://github.com/openmsupply/open-msupply/pull/2421 please see description there~~ https://github.com/openmsupply/open-msupply/pull/2383.
This PR also not directly related changes:
* anyhow dependency moved to workspace 
* created prepare file dir utility, since I saw common functionality when looking up static file for reference
I used [the blank test data file](https://drive.google.com/drive/u/1/search?q=simple%20sync), turned on vaccine module preference for the store. Synced, then went to sensor list, pressed the fridge tag button and used this file: https://github.com/openmsupply/temperature-sensor/blob/main/data/ …
> 2420 upload fridge tag data

- client/packages/common/src/hooks/useUrlQuery/useUrlQueryParams.ts
- client/packages/common/src/utils/formatters/formatters.test.ts
- client/packages/common/src/utils/formatters/formatters.ts
- client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts
Fixes #2429 
Return iso string to api for datetime and fix tests
> 2429 change formatter.naive date time to formatter.to iso string

- client/packages/host/src/Host.tsx
- client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts
- client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts
- client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditForm.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/columns.ts
- client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/PrescriptionLineEditForm.tsx
- client/packages/invoices/src/Prescriptions/DetailView/columns.ts
- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEditForm.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/columns.ts
- client/packages/requisitions/src/ResponseRequisition/DetailView/columns.ts
- client/packages/system/src/Item/Components/index.ts
- client/packages/system/src/Item/DetailView/DetailView.tsx
- client/packages/system/src/Item/ListView/ListView.tsx
- client/packages/system/src/Item/api/hooks/usePackUnits/usePackUnits.ts
- client/packages/system/src/Item/context/useUnitVariant.ts
- client/packages/system/src/Stock/ListView/ListView.tsx
Part of #2313
Fetches and caches the pack units on first use.
A bit different to what suggested in the TODO, so just a draft. Idea is to use tan stack query to cache the pack units for an hour and then just use `usePackUnits` in `useUnitVariant`.
Some drawbacks though:
1) pack units are cached in tanstack AND in the `useUnitStore`
2) the initial use will be slower since the query has to run first
So actually think doing the query at startup is better. However, doing the initial call in `useLogin` or `useAuthContext` also doesn't seem right (both are quite "clean" right now doing just login/auth, and both are in `common`). So wonder if this solution is good enough.
> Use tanstack to cache pack units

- client/packages/coldchain/src/Monitoring/ListView/TemperatureBreach/Toolbar.tsx
- client/packages/coldchain/src/Monitoring/ListView/TemperatureLog/Toolbar.tsx
- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/intl/locales/en/inventory.json
- client/packages/common/src/types/schema.ts
- client/packages/system/src/Stock/Components/Toolbar.tsx
- client/packages/system/src/Stock/ListView/ListView.tsx
- client/packages/system/src/Stock/api/hooks/line/useStockLines.ts
- server/graphql/stock_line/src/lib.rs
- server/repository/src/db_diesel/stock_line.rs
- server/service/src/stock_line/tests/query.rs
Fixes #1727
Refactors stock line filters to match how filters look in other parts of UI and add location name search
Not too sure about the filter by master list for stock view though... since we don't show master list name or anything as a column and seems weird to me to be able to filter an invisible column 🤔
> 1727 filter view stock list by master list & location

- client/packages/programs/src/JsonForms/common/components/Autocomplete.tsx
Part of #2329
For the HIV contact tracing I tried to keep the original codes which are stored in original data, e.g. "C" for a "Children" relationship.
This PR replaces the existing `values` option for the Autocomplete control with a `show` option similar to the `show` option of the Select control. I thought it would be nice to have the same option and to be able to customize how thing are displayed and how they are stored.
However, there is one problem. The contact tracing table column now shows "C" instead of "Children". Had a chat with Richard, and he was fine with it. If this is a problem we can still update the UI schema to use the display options...
> Let Autocomplete use the same show option as the Select component

- client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/TemperatureChart.tsx
- client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/useTemperatureChartData.ts
- server/server/src/cold_chain/temperature_breach.rs
Fixes #2440
- For the chart - determines the min and max temperature values, then sets the y axis domain to be 2° either side of those values, with a 2° and 8° default
- The missing temperature is because a breach was uploaded which did not have an associated log entry. The CCA is uploading logs first, so this should not be a valid scenario. Have added a check - that when you upload a breach; with this PR when you upload a breach, the ID must be attached to an existing log entry. 
For the chart, you need a sensor which does not exceed the 8°C threshold. 
You may find it useful to use this version of the database:
[dump-omsupply_cold_chain-202311071455.backup.zip](https://github.com/msupply-foundation/open-msupply/files/13274661/dump-omsupply_cold_chain-202311071455.backup.zip)
In the opua …
> Cold chain: handle data issues

- server/service/src/sync/api/core.rs
Fixes #2197 
Send a more descriptive app name based on android or pc
> 2197 Use descriptive app-name http header in sync

- client/packages/common/src/ui/components/inputs/Select/Select.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditForm.tsx
- client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/PrescriptionLineEditForm.tsx
Fixes #2455
Only show `clear selection` if there is more than one option and don't allow clearing for outbound/prescription pack size since user has to select one anyway... Branched off develop since this issue shows up here as well (:
> 2455 Clear selection shouldn't show if there is only one pack size

- client/packages/common/src/ui/layout/tables/DataTable.tsx
- client/packages/system/src/Item/api/api.ts
- client/packages/system/src/Item/api/hooks/useDefaultServiceItem/useDefaultServiceItem.tsx
- client/packages/system/src/Item/api/hooks/useItems/useItems.ts
Fixes #2467
Removes the restriction in the item list, which was only showing STOCK items
Removes the check for a 'default' service item which matches the code to be 'service'
Tested using the site, to see if I can add service charges now.
> Remove some service items restrictions

- server/Cargo.lock
- server/Cargo.toml
- server/graphql/core/Cargo.toml
- server/graphql/programs/Cargo.toml
- server/service/src/stocktake/update.rs
Fixes #2469
Updates async-std dependency
Try using main version of rust analyzer with 1.73.0 of rust. Without this change rust analyzer fails (i.e. no annotation, no cmd + click navigation). With this change should work (after restarting vs code)
> 2469 fix rust analyzer stack overlfow

- client/packages/system/src/Name/Components/NameOptionRenderer/NameOptionRenderer.tsx
- client/packages/system/src/Name/Components/NameRenderer/NameRenderer.tsx
- client/packages/system/src/Name/Components/NameRenderer/index.ts
- client/packages/system/src/Name/Components/index.ts
- client/packages/system/src/Name/DetailModal/DetailModal.tsx
- client/packages/system/src/Name/ListView/ListView.tsx
Fixes #1641 
Add the home icon to the supplier/customer list and modal
> 1641 suppliers/customer list: add the "house" icon to the names using mSupply 

- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/ui/components/buttons/standard/SplitButton.tsx
- client/packages/invoices/src/InboundShipment/DetailView/Footer/StatusChangeButton.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/Footer/StatusChangeButton.tsx
- client/packages/invoices/src/Prescriptions/DetailView/Footer/StatusChangeButton.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/Footer/StatusChangeButton.tsx
Fixes #1400
Disable confirmation buttons if no lines for:
- Outbound Shipment
- Inbound Shipment 
- Internal Order
- Prescriptions
- Create an invoice/requisition for any of the above
- See that the status confirmation button is disabled
> 1400 Can send internal orders without lines

- client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/TemperatureChart.tsx
Fixes #2483 
Adds the 2°C and 8°C y axis numbers. unfortunately it required a lot more work than expected, as you cannot get the generated ticks, or have multiple yAxis components.
I've implemented the horizontal lines and the ticks, which allows for formatting control as well as determining the number of horizontal lines. It's looking pretty good now:
Have checked using local data. Here's a 4BK which has some data in it, if that helps:
[oms_cold_chain[0016].4BK.zip](https://github.com/msupply-foundation/open-msupply/files/13358980/oms_cold_chain.0016.4BK.zip)
> Add ticks to the yaxis to show 2° and 8°

- client/packages/common/src/ui/components/modals/ConfirmationModal/ConfirmationModal.tsx
- client/packages/common/src/ui/components/modals/ConfirmationModal/ConfirmationModalContext.ts
- client/packages/common/src/ui/components/modals/ConfirmationModal/ConfirmationModalProvider.tsx
- client/packages/common/src/ui/components/modals/ConfirmationModal/useConfirmationModal.ts
- client/packages/common/src/ui/icons/Help.tsx
- client/packages/common/src/ui/icons/Icon.stories.tsx
- client/packages/common/src/ui/icons/index.ts
- client/packages/requisitions/src/RequestRequisition/DetailView/AppBarButtons/UseSuggestedQuantityButton.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/AppBarButtons/CreateShipmentButton.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/AppBarButtons/SupplyRequestedQuantityButton.tsx
Fixes #2497
- Created a new icon
- Added icon to storybook
- Updated the confirmation modal to default to the new icon
- Added ability to set the icon when using `useConfirmationModal`
- Used the info icon in suggested quantity and create shipment buttons. All other usages were using the heading 'Are you sure?' (or similar) and it made sense to have them as a question mark
No change for these two:
All others:
Check a few confirmation modals.. and that storybook shows the new icon.
> Confirmation modal icon

- client/packages/common/src/intl/locales/en/common.json
- client/packages/system/src/Encounter/ListView/Toolbar.tsx
- client/packages/system/src/Patient/Encounter/CreateEncounterModal.tsx
Fixes #2415
- Changed the encounter modal date to include date time selection since the start time for this was being funky in detail view.
- Have left the detail view date time separate since it's recording two different values: start and end date times.  
- Create an Encounter
- See the date time change in modal
Couldn't find anymore date time components but lemme know if I missed any (: 
Also not related but while playing with the filters for encounters... I noticed that maybe we want a filter that can filter by startDatetime: afterOrEqualTo and endDatetime: beforeOrEqualTo... idk if it's useful but makes sense to me...
> 2415 Unify programs and coldchain time component 

- client/packages/android/app/src/main/java/org/openmsupply/client/CertWebViewClient.java
- client/packages/android/app/src/main/java/org/openmsupply/client/NativeApi.java
Fixes #2526
Two fatal exceptions observed when running the android app without a network
- `CertWebViewClient.shouldOverrideUrlLoading` was raising an Exception about String.length() of a null object
- `NativeApi.java` also raised a null object Exception in the `getHostAddress` call
Turning off wifi on the tablet and starting the app was enough to have the app crash. 
I've cleared app data and run in both Client and Server modes, without a network when displaying the list of servers, only `127.0.0.1` is available - which is a bit of an issue if you are configuring cold chain, but then the network isn't available so cold chain wouldn't be able to connect anyway!
I've uploaded a debug apk file (open-msupply-1.5.00-debug.apk) to a [google drive …
> Prevent android crashing when network disabled

- client/packages/common/src/utils/numbers/NumUtils.ts
- client/packages/programs/src/JsonForms/components/BMI.tsx
Fixes https://github.com/msupply-foundation/programschemas/issues/4
This was actually an issue in the BMI control and not in the schema config. I.e. the issue is in the wrong repo.
- create 2 encounters
- In first encounter: set height
- In second encounter: set weight -> BMI should be calculated
- unset weight -> BMI should be cleared
- Back in first encounter: unset height. In the second encounter setting a weight shouldn't calculate the BMI because there is no height value 
- Test other combinations...
> 4 unset bmi when no height weight

- server/service/src/sync/translations/master_list.rs
Fixes #2534
Make inactive optional in master list translation...
> Make inactive optional in translation

- client/packages/common/src/intl/locales/en/common.json
Fixes #2516 
Quick change to `label.patient-id`.
- Go to patient
- Click filters
- See rename
> Rename patient patient id filter name #2516

- client/packages/system/src/Item/Components/ItemOptionRenderer/ItemOptionRenderer.tsx
Fixes #1764
For the `StockItemSearchInput` make the `item.code` space a little wider, and add in overflow hidden, with an ellipsis. 
Have also added a tooltip to the row, in case the code is obscured.
In the screenshot `Acetylsalicylic Acid 100mg tabs` has a strangely long code. The `Amoxicillin 250mg tabs` has also had the name elongated to show that this is wrapping correctly. 
The tooltip is also shown, where you can see the full item code.
I've changed the code and name of items to check the overlap.
> Prevent item code overlapping

- client/packages/common/src/types/schema.ts
- client/packages/system/src/Item/DetailView/DetailView.tsx
- client/packages/system/src/Item/DetailView/Tabs/MasterLists.tsx
- client/packages/system/src/MasterList/api/api.ts
- client/packages/system/src/MasterList/api/hooks/document/index.ts
- client/packages/system/src/MasterList/api/hooks/document/useMasterListsByItemId.ts
- client/packages/system/src/MasterList/api/hooks/index.ts
- client/packages/system/src/MasterList/api/operations.generated.ts
- client/packages/system/src/MasterList/api/operations.graphql
- server/graphql/general/src/queries/master_list.rs
- server/repository/src/db_diesel/item.rs
- server/repository/src/db_diesel/master_list.rs
Fixes #2488
- Load master lists that contain the item in `Item -> Master List` tab.
> 2488 item -> master list tab shows all master lists

- client/packages/common/src/ui/components/inputs/Filters/FilterMenu.tsx
- client/packages/system/src/Patient/ListView/Toolbar.tsx
Fixes #2514
Allows default filters
> 2514 Patient list view: have some default filter auto selected

- client/packages/common/src/intl/locales/en/programs.json
- client/packages/programs/src/JsonForms/components/BloodPressure.tsx
- client/packages/programs/src/JsonForms/components/index.ts
- client/packages/programs/src/JsonForms/useJsonForms.tsx
Fixes #2513 
Sets up a custom control for `blood pressure`. This control shows systolic and diastolic values next to each other separated by `/` which is normal(?) since blood pressure is usually shown as e.g. 120/80. And also doesn't prompt error if none of these values are set.
https://github.com/msupply-foundation/open-msupply/assets/61820074/1ce2cb6d-409b-4aa6-a210-0436b70b35a0
> 2513 count spinner control needs an option to unset the value

- package.json
- server/service/src/sync/sync_serde.rs
- server/service/src/sync/translations/invoice.rs
This is exploratory version to temporary fix this issue and help us identify the origin of the problem: https://github.com/msupply-foundation/open-msupply-internal/issues/37
A test APK based on this branch can be found with [this link](https://www.dropbox.com/scl/fi/3oiuudim2no0vvg98v8jg/open-msupply-1.5.01-release.apk?rlkey=kkej90s8r9zut5n9lf2ahfatr&dl=1)
Or use this QR code (just open camera and it should give an option to navigate to browser and download), might be easier to use drop box link if you using MDM to update the tablets.
To test, try the data file and site mentioned in the issue, you should see historic outbound shipments starting at serial number 1 (as oppose to missing outbound shipments and serial numbers starting > 1),  during initial sync these warnings should be …
> Ignore time deserialisation in sync and add logging for invoice serialisation in sync

- server/repository/src/migrations/v1_06_00/mod.rs
- server/repository/src/migrations/v1_06_00/patient_id_indices.rs
- server/repository/src/mock/mod.rs
Fixes #2604 
Add some indices to speed up report queries. I experimented with secondary indices like (patient_id, type, active_start_datetime) but it didn't improve things consistently. For this reason I decided for a smaller index. If needed a more optimized index can be create at a later point.
As a reference the report I was working on took about 17sec to query and is now down to <1s.
> 2604 add patient id indices

- package.json
- server/graphql/types/src/types/name.rs
- server/repository/src/db_diesel/name.rs
- server/repository/src/db_diesel/name_row.rs
- server/repository/src/migrations/mod.rs
- server/repository/src/migrations/v1_05_04/mod.rs
- server/service/src/programs/patient/patient_updated.rs
- server/service/src/sync/test/test_data/name.rs
- server/service/src/sync/translations/name.rs
Fixes #2618
Add custom data field (text) to name table, add translations for custom data for sync, expose in API. Clear integration_time for name records in sync buffer, so that they are re-integrated on startup
* Add custom data to name in mSupply ( first in preferences add “custom fields” to name, then for a name add custom data )
* Start previous version of omSupply (prior to 1.5.04), sync
* Stop previous version of omSupply and start new version of omSupply
* Use name API, see custom field being populated (without re-sync)
* Update custom field on name, sync, see it being updated in API
This PR is for main branch, with version increase for migration, I'll make a build as soon as it's merged, and deploy on demo server that requires it (DJ)
> 2618 sync and expose custom data on name

- client/packages/common/src/hooks/useUrlQuery/useUrlQueryParams.ts
- client/packages/common/src/types/schema.ts
- client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditForm.tsx
- client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/InboundLineEditForm.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditForm.tsx
- client/packages/system/src/Item/Components/ItemOptionRenderer/ItemOptionRenderer.tsx
- client/packages/system/src/Item/Components/StockItemSearchInput/StockItemSearchInput.tsx
- client/packages/system/src/Item/api/operations.generated.ts
- client/packages/system/src/Item/api/operations.graphql
- client/packages/system/src/Item/types.ts
- client/packages/system/src/Item/utils.ts
Fixes #2614
The current item i.e. the selected value in the autocomplete, is picked from the list of available items which is fetched with the `useItemStockOnHand` hook. If you have more than 500 items available, and the current item is further than position 500 when the list is sorted by name, then that item won't be in the first set of paginated results.
This means that the item won't be shown in the disabled autocomplete component.
The fix here is to also fetch the current item by id, and add that to the list of items. This list is already unique by id, so we won't be adding a duplicate. When editing a stocktake or OS line, the selected items aren't changeable, so the input will be disabled when showing the current item. This means that the position in the list is also not important. …
> Display current item in OS and Stocktake when you have many items in the system

- client/packages/common/src/intl/utils/DateUtils.ts
- client/packages/common/src/intl/utils/IntlUtils.ts
- client/packages/common/src/styles/ThemeProvider.tsx
- client/packages/common/src/ui/components/inputs/DatePickers/DatePickerInput/DatePickerInput.tsx
- client/packages/common/src/ui/components/inputs/DatePickers/DateTimePickerInput/DateTimePickerInput.tsx
- client/packages/programs/src/JsonForms/common/components/Date.tsx
- client/packages/programs/src/JsonForms/components/DateOfBirth.tsx
Fixes #2600
The LocalizationProvider defaults to en-US (https://mui.com/x/react-date-pickers/adapters-locale/#getting-started)
Use the selected language instead.
Use localized format instead of hard coded format.
Changing the browser language between en-US and en-GB/en-NZ should change date format in:
- Encoutner header
- Encounter list view
- JSON forms controls
> 2600 fix datetime display

- client/packages/programs/src/JsonForms/stripEmptyAdditions.test.ts
- client/packages/programs/src/JsonForms/stripEmptyAdditions.ts
- client/packages/programs/src/JsonForms/useJsonForms.tsx
Fixes #2510
Strips all empty objects before comparing initial data to the modified data. This makes it actually much nicer to use now.
- Create a new HIV care encounter. Navigate to the different bubbles, the save button should stay disabled.
- In the same encounter modify some value and revert -> save button should revert to disabled.
- Navigate to patient detail view and do similar test, i.e. reverted edits should not leave the save button enabled
> Strip empty additions before comparing data and initial data

- server/repository/src/db_diesel/stock_line.rs
- server/repository/src/mock/mod.rs
- server/repository/src/tests.rs
- server/service/src/sync/translations/stock_line.rs
Fixes #2626 (will change the scope of that issue to stockline and make issues for other tables)
Makes the translator use the `StockLineRepository` rather than `StockLineRowRepository` to get the correct item_id.
Running tests
> 2626 item merge sync push translators item

- client/packages/common/src/ui/layout/tables/components/Cells/LocationCell.tsx
- client/packages/common/src/ui/layout/tables/components/Cells/index.ts
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/columns.ts
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/hooks/useOutboundLineEditRows.ts
- client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/PrescriptionLineEdit.tsx
- client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/columns.ts
- client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/hooks/usePrescriptionLineEditRows.ts
- client/packages/invoices/src/Prescriptions/api/api.ts
- client/packages/invoices/src/Prescriptions/api/hooks/line/usePrescriptionSaveLines.ts
- client/packages/invoices/src/StockOut/utils.tsx
Fixes #2628
A couple of issues identified:
- The status of a new prescription is still `New` when it comes to checking if we can update or insert lines with zero quantity. Unfortunately, prescriptions auto update the status to `Picked` but this happens at the time of saving, so lines are not pruned, but should be
- Stock lines that are for on hold locations cannot be used, but were available to be selected, manually and automatically
- Errors in the batch mutation are not shown to the user
I've addressed those issues, viz:
- display errors (and yes, this could be neater; ideally the API would be easier to surface the error from)
- prevent on hold locations from being selected
- prune zero quantity lines in prescriptions, regardless of status
Now, the stock lines which have an on-hold …
> show errors and prevent location on hold allocation

- server/repository/src/db_diesel/item_link_row.rs
- server/repository/src/tests.rs
- server/service/src/sync/sync_buffer.rs
- server/service/src/sync/synchroniser.rs
- server/service/src/sync/test/integration/central/master_list.rs
- server/service/src/sync/test/integration/central/unit_and_item.rs
- server/service/src/sync/test/integration/remote/program_requisition.rs
- server/service/src/sync/test/mod.rs
- server/service/src/sync/translation_and_integration.rs
- server/service/src/sync/translations/mod.rs
- server/service/src/sync/translations/special/item_merge.rs
- server/service/src/sync/translations/special/mod.rs
- server/service/src/sync/translations/special/name_to_name_store_join.rs
Fixes #2554
- adds an item merge translator and handles merge message types throughout sync.
- merge message order does not matter, will still chain merges correctly.
Regarding message order the problem is as follows...
Items A, B and C, each with corresponding links:
```
A->A
B->B
C->C
```
and 2 messages to merge
```
A->B
B->C
```
In that order all works well, we'd end up with
```
// First message integrated (A->B)
A->B
B->B
C->C
// Second message integrated (B->C)
A->C
B->C
C->C
```
But if the messages are in reverse order we risk:
```
// First message integrated (B->C)
A->A
B->C
C->C
// Second message integrated (A->B)
A->B
B->C
C->C
```
So now link A is pointing to item B, which is no longer a valid item! So to ensure that the link is already updated correctly regardless of order we …
> 2554 item merge handle sync merge messages

- client/packages/common/src/types/schema.ts
- client/packages/system/src/Stock/ListView/ListView.tsx
- client/packages/system/src/Stock/api/api.ts
- server/graphql/stock_line/src/lib.rs
- server/repository/src/db_diesel/stock_line.rs
Fixes #2633
Allow stock to be sort by location code... Did it by code since location code is the only thing shown under the location column.
> 2633 location sort function

- server/repository/src/migrations/v1_06_00/changelog_deduped.rs
- server/repository/src/migrations/v1_06_00/mod.rs
Fixes #2688 
Replaces the existing view:
```sql
CREATE VIEW changelog_deduped AS
SELECT t1.cursor,
t1.table_name,
t1.record_id,
t1.row_action,
t1.name_id,
t1.store_id,
t1.is_sync_update
FROM changelog t1
WHERE t1.cursor = (SELECT max(t2.cursor) 
from changelog t2
where t2.record_id = t1.record_id)
ORDER BY t1.cursor;
```
with 
```sql
CREATE VIEW changelog_deduped AS
SELECT c.cursor,
c.table_name,
c.record_id,
c.row_action,
c.name_id,
c.store_id,
c.is_sync_update
FROM (
SELECT record_id, MAX(cursor) AS max_cursor
FROM changelog
GROUP BY record_id
) grouped
INNER JOIN changelog c
ON c.record_id = grouped.record_id AND c.cursor = grouped.max_cursor
ORDER BY c.cursor;
```
The first view query was a problem for both, sqlite and postgres. Now the query seems to be fast so I haven't experimented …
> Rework the changelog_deduped view

- client/packages/system/src/ContactTrace/DetailView/DetailView.tsx
- client/packages/system/src/ContactTrace/DetailView/Footer.tsx
- client/packages/system/src/Encounter/DetailView/DetailView.tsx
- client/packages/system/src/Encounter/DetailView/Footer.tsx
- client/packages/system/src/Patient/ProgramEnrolment/Components/DetailModal.tsx
Fixes #2512 
Use loading buttons for encounter, contact trace and program enrolment saving.
> 2512 missing progress indication when saving an patient/encounter/enrolment

- client/packages/common/src/hooks/useUrlQuery/useUrlQuery.ts
- client/packages/common/src/ui/components/navigation/Tabs/DetailTabs.tsx
Fixes #2431 
- Removes the tab specific code from useUrlQuery and moves it to DetailTabs (tab query is set when changing the tab)
- Remembers query parameters for each tab (only for as long as being on the tab view)
For the second point, is this actually something we want to have or should I revert to the old behaviour where all filter params are reset when changing between tabs?
Best to be tested with a cold chain dataset (Monitoring tabs)
https://github.com/msupply-foundation/open-msupply/files/13303292/oms_cold_chain.zip
- Set filter for each tab and move back and forth between tabs
> Move tab logic from useUrlQuery to DetailTabs

- client/packages/requisitions/src/RequestRequisition/ListView/CreateRequisitionModal.tsx
Fixes #2608
Enables background click or tap closing for Internal Orders modal.
A number of other modals are closed by clicking outside (such as inbound shipment modal). This matches this pattern.
An alternative option would be to add a cancel button - though this may be more confusing? I'm not sure.
You can test this by going to
- Replenishment
- Internal Orders
- Create new
- Clicking outside (or tapping on table) to close the modal
> 2608 add cancel buttons to modals

- server/service/src/sync/translations/requisition_line.rs
Fixes #2636 
Changes `requisition_line` translation to look up item_id from the related `ItemLinkRow` instead of using it directly (because it's really `item_link_id` at the moment).
Automated Tests
> 2636 requisition_line.item_id translation from item_link

- server/repository/src/migrations/v1_06_00/clinician_store_join_add_clinician_link_id.rs
- server/repository/src/migrations/v1_06_00/encounter_add_clinician_link_id.rs
- server/repository/src/migrations/v1_06_00/invoice_add_name_link_id.rs
- server/repository/src/migrations/v1_06_00/invoice_line_add_item_link_id.rs
- server/repository/src/migrations/v1_06_00/item_add_is_active.rs
- server/repository/src/migrations/v1_06_00/master_list_line_add_item_link_id.rs
- server/repository/src/migrations/v1_06_00/master_list_name_join_add_name_link_id.rs
- server/repository/src/migrations/v1_06_00/name_store_join_add_name_link_id.rs
- server/repository/src/migrations/v1_06_00/name_tag_join_add_name_link_id.rs
- server/repository/src/migrations/v1_06_00/requisition_add_name_link_id.rs
- server/repository/src/migrations/v1_06_00/stock_line_add_item_link_id.rs
- server/repository/src/migrations/v1_06_00/stocktake_line_add_item_link_id.rs
Fixes #2698 
Tweaking the migrations for `feature/merging` to make sure indexes are created for postgres, not just sqlite.
Test pass
> 2698 merging feature fix indexes

- server/service/src/sync/translations/stock_line.rs
- server/service/src/sync/translations/stocktake_line.rs
Fixes #2626
Makes the translator use the `StocktakeLineRepository` rather than `StocktakeLineRowRepository` to get the correct item_id.
Running tests
> 2637 stocktake line translator push correct item

- client/packages/common/src/intl/utils/DateUtils.ts
- client/packages/common/src/ui/components/inputs/DatePickers/DateTimePickerInput/DateTimePickerInput.tsx
Fixes #2712 #2713
The DateTimePickerInput was failing to parse the date - the default format of `P p` is used to both format a date object to a string and to parse the date string.
However, the parse was failing silently with the result that the input was setting the date value to `null` on a blur event, resetting the input value.
The fix, for me at least, is to provide a locale to the `parse` call.
An alternative is to set the date format at `dd/MM/yyyy HH:mm` as this works for parsing as well. However, I thought it best to use the local regional format if possible. I've tried setting my OS regional settings to something different, however this has no effect.
As per the issues, focus on a date input and then click elsewhere, triggering a blur event.
If the input is populated with a date, …
> Parse dates in date filter

- client/packages/coldchain/src/Sensor/ListView/ListView.tsx
- client/packages/common/src/intl/locales/en/coldchain.json
- server/Cargo.lock
- server/graphql/types/Cargo.toml
- server/graphql/types/src/types/sensor.rs
Fixes #2717
The replacement to `mSupply RTMD` I've made a front end substitution - this is because the concern was a f/e display issue, and the current method of formatting (`Formatter.enumCase`) would not provide the correct result (mSupply). I thought that by using a translation, we could (a) display in a local language if required and (b) update when the PM whimsy strikes.
The serial replacement however, has been done in the GQL query so that it is handled for both the sensor detail modal and the list view:
(the list is slightly visible behind the modal)
Check the sensor list and detail views
> Replace manufacturer

- client/packages/coldchain/src/Monitoring/ListView/TemperatureBreach/useAcknowledgeBreachModal.tsx
- client/packages/common/src/intl/locales/en/coldchain.json
Fixes #2718
If you try to acknowledge an ongoing breach, a message is shown and the `OK` button is not enabled:
Try to acknowledge an ongoing breach
> Prevent acknowledgment of ongoing breaches

- server/server/src/cold_chain/temperature_breach.rs
Fixes #2704
Ignore the breach acknowledgement status sent by the CCA via the API
Send a breach using the API
- new breaches: unacknowledged is always true
- updated breaches: unacknowledged remains as it was
- the comment entered by a user won't be overwritten by the CCA API call either
here's my postman collection which has the login and breach creation calls:
[Cold Chain.postman_collection.json](https://github.com/msupply-foundation/open-msupply/files/13943252/Cold.Chain.postman_collection.json)
> Ignore acknowledge status from CCA

- client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/TemperatureChart.tsx
- client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/useTemperatureChartData.ts
- client/packages/coldchain/src/Monitoring/ListView/TemperatureLog/Toolbar.tsx
Fixes #2700 
Defaults the filter dates and times for the charts, and updates the max date values for the filters.
View the chart! by default you'll see entries going back in time (for one day) from now
> Change the default dates for temperature chart

- client/packages/coldchain/src/Monitoring/ListView/TemperatureBreach/TemperatureBreachList.tsx
- client/packages/coldchain/src/Monitoring/ListView/TemperatureLog/TemperatureLogList.tsx
Fixes #2716
Reverts the change to the log column and changes the breach column as per [this comment](https://github.com/msupply-foundation/open-msupply/issues/2716#issuecomment-1896599128)
* the log list should show `temperature` 
* the breach list should show `max / min` along with a description
> Rename temperature columns

- server/repository/src/db_diesel/contact_trace.rs
- server/repository/src/db_diesel/contact_trace_row.rs
- server/repository/src/db_diesel/item.rs
- server/repository/src/db_diesel/name.rs
- server/repository/src/migrations/v1_06_00/contact_trace_link_id.rs
- server/repository/src/migrations/v1_06_00/mod.rs
- server/repository/src/mock/mod.rs
- server/repository/src/mock/name.rs
- server/repository/src/tests.rs
Fixes #2683 
This was tricky one because the contact_trace table has a reference to two name_id and the used diesel version doesn't support joining a table twice. The solution was to create view that does all the joining. On the plus side the Rust changes are comparatively small and the link logic is completely hidden in the repository layer.
Added some mock functionality to update name_links (simulate merges). Just saw in another PR that there was something similar for items (?). Might have to align it, let me know what you think.
Also did some clean up where name_link were updated twice...
> 2683 name merge contact trace

- client/packages/common/src/api/GqlContext.tsx
- client/packages/common/src/authentication/AuthContext.tsx
- client/packages/common/src/authentication/api/api.ts
- client/packages/common/src/authentication/api/hooks/useLogin.ts
- client/packages/common/src/authentication/hooks/usePermissionCheck.ts
- client/packages/common/src/intl/locales/en/app.json
- client/packages/common/src/localStorage/keys.ts
- client/packages/host/src/Host.tsx
- client/packages/host/src/QueryErrorHandler.tsx
- client/packages/host/src/components/AuthenticationAlert.tsx
- client/packages/host/src/components/ErrorAlert.tsx
- client/packages/host/src/components/Login/Login.tsx
Fixes #2710
Have made the error display more prominent. The server error was being caught already, but the heading was still 'Authentication Error' and I wasn't stopping to read the text.
So the change here is to upgrade the heading to 'Server Error' and also include the text, in the error colour, as below:
While it isn't the prettiest - it should be a situation that no normal user would see, only developers. I didn't want to parse the error object coming back from the server, which is text by the time we get it.
As per the issue - delete a column, and login to see the fun.
> Display server error

- server/repository/src/db_diesel/name_store_join.rs
- server/service/src/sync/translations/name_store_join.rs
- server/service/src/sync/translations/special/name_to_name_store_join.rs
Fixes #2749
Create a join that also returns `name_row` and use that to get the correct name_id.
- Run tests
> Name merging name store join.name id translator get actual name.id

- client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/useTemperatureChartData.ts
- client/packages/common/src/intl/utils/DateUtils.ts
Fixes #2757 
When either part of the date filter was null, the date value was being set to the current datetime ( to the nearest millisecond ) which updates the filter and causes `TemperatureChart` to re-render, causing the `Toolbar` to re-render which updates the filter.
To fix, I've lifted out the to/from date extraction, rounded off the time to the nearest second and memoised the resulting date strings.
The original repro step has been fixed, sorry. This is what I've been doing:
- On the Temperature Chart, click on the from (or to) date
- click on the day part of the day, hit `del`
- the page then re-renders, you'll see lots and lots of api requests for the `temperatureChart` query
One concern, if you clear the 'from' date it defaults to a day ago, but doesn't tell you that it has. …
> Fix for Temperature Chart date filter

- client/packages/coldchain/src/Monitoring/api/TemperatureNotification/hooks/document/useTemperatureNotifications.ts
- client/packages/common/src/api/GqlContext.tsx
Fixes #2762
Adds a regular refetch of notifications (breaches & excursions) so that if the site ends up in a state like the one in the issue (a breach is identified but no notification shown) then a refetch will happen and the notification will be shown.
Have also disabled the cache for that query - though I'm concerned that the notification query is a little slow, so I set the refetch to be five minutes. Didn't want it to be called too often.
Not sure if you'll be able to recreate the scenario in the issue - I wasn't able to.
You can check that the site will fetch notifications every 5 minutes ( reduce the polling interval if you are impatient )
> Refetch notifications

- server/repository/src/mock/mod.rs
- server/repository/src/mock/test_requisition_service.rs
- server/service/src/requisition/request_requisition/add_from_master_list.rs
- server/service/src/requisition/request_requisition/batch.rs
- server/service/src/requisition/request_requisition/delete.rs
- server/service/src/requisition/request_requisition/update/test.rs
- server/service/src/requisition/request_requisition/use_suggested_quantity.rs
- server/service/src/requisition/response_requisition/create_requisition_shipment/test.rs
- server/service/src/requisition/response_requisition/supply_requested_quantity.rs
- server/service/src/requisition/response_requisition/update.rs
- server/service/src/requisition_line/chart/mod.rs
- server/service/src/requisition_line/request_requisition_line/delete.rs
- server/service/src/requisition_line/request_requisition_line/insert.rs
- server/service/src/requisition_line/request_requisition_line/update.rs
- server/service/src/sync/translations/requisition.rs
Fixes #2746
Makes the translator use the `RequisitionRepository` rather than `RequisitionRowRepository` to get the correct name_id.
- Run tests
> Name merging requisition.name id translator get actual name.id

- server/graphql/location/src/mutations/delete.rs
- server/graphql/stock_line/src/mutations/update.rs
- server/repository/src/db_diesel/stock_line.rs
- server/service/src/sync/translations/stock_line.rs
Fixes #2750
Make sure `StockLine` translator pushes correct name id.
Run tests
> Name merging: stock_line.supplier_id translator get actual name.id

- server/repository/src/db_diesel/changelog/changelog.rs
- server/repository/src/db_diesel/changelog/test.rs
- server/repository/src/migrations/v1_07_00/mod.rs
- server/service/src/sync/sync_status/test.rs
Fixes #2607
Remembers latest changelog and delete all changelog entries created during the merge migrations.
@Chris-Petty do we need to test this a bit more? or do you think it should be ok. For example, are there any cases where a migration change need to be synced?
Probably good to wrap all merge migrations into a function to group them by feature and to not accidentally put an unrelated migration in (after moving to 1.7 https://github.com/msupply-foundation/open-msupply/issues/2733)...
> 2607 drop migration changelog rows

- client/packages/common/src/ui/components/inputs/Filters/TextFilter.tsx
Fixes #2822
If you enter a value into a text filter and then slowly press backspace, deleting each character in turn, then the filter works correctly.
If you do what I think is more normal, and mash backspace repeatedly until the text is cleared, then the first letter of the query remains.
This is because the url query is cleared immediately and then the debounced call fires and sets the query to be the final character in the search text. I've removed the inconsistent behaviour.
As above, try clearing search text quickly using backspace and see what happens.
> Backspace too quickly and the query is incorrect

- server/graphql/general/src/queries/tests/master_lists.rs
- server/repository/src/db_diesel/item.rs
- server/repository/src/db_diesel/master_list_line.rs
- server/repository/src/db_diesel/master_list_line_row.rs
- server/repository/src/mock/full_master_list.rs
- server/repository/src/tests.rs
- server/service/src/dashboard/item_count.rs
- server/service/src/invoice/inbound_shipment/add_from_master_list.rs
- server/service/src/invoice/outbound_shipment/add_from_master_list.rs
- server/service/src/requisition/request_requisition/add_from_master_list.rs
- server/service/src/stocktake/insert.rs
- server/service/src/sync/test/test_data/master_list_line.rs
- server/service/src/sync/translations/master_list_line.rs
Part of #2759
This one introduces a proper MasterListLine domain object. This actually follows the idea of a repository more closely to make the DB layer independent of the rest of the system. Maybe we should have done this for other repos as well?
We could even make MasterListLineRow private to the repo and change all usages to MasterListLine...
> Rename item_link_id for MasterListLineRow

- server/configuration/example.yaml
- server/repository/src/database_settings.rs
Fixes #817 
Adds .sqlite to sqlite database names if .sqlite isn't already the suffix
You can test this by running Cargo run to create a new db with different name configurations in local.yaml.
A new database should be added with .sqlite appended.
> Add appending to database name

- client/packages/common/src/authentication/api/operations.generated.ts
- client/packages/common/src/authentication/api/operations.graphql
- client/packages/common/src/intl/currency/currency.test.tsx
- client/packages/common/src/intl/currency/currency.ts
- client/packages/common/src/types/schema.ts
- client/packages/common/src/ui/components/inputs/CurrencyInput/CurrencyInput.tsx
- server/graphql/general/src/queries/currency.rs
- server/graphql/types/src/types/user.rs
- server/repository/src/db_diesel/currency.rs
- server/repository/src/db_diesel/currency_row.rs
- server/repository/src/migrations/v1_07_00/currency.rs
- server/service/src/sync/test/test_data/currency.rs
- server/service/src/sync/translations/currency.rs
Fixes #2827
Removes `is_active` from currency... add sort by `is_home_currency` and store's `currency_code` to `UserNode` and finally separate currency from language.
Default currency: `USD/NZD`
- Run frontend tests with `yarn test`
> 2827 separate currency from language

- .github/workflows/pr-issue-label-sync.yaml
Fixes #2852
Adds a workflow that links related issue and copies labels and milestone to the PR. 
When I made this script I did it repo agnostic. It's been in use in our mSupply repo for a year or 2?
We can only test it works here by merging this PR and then seeing what happens if you open a PR, or close/reopen a PR. Actions are such a pain...
> 2852 create github action pr-issue-label-sync.yaml

- client/packages/android/app/src/main/assets/capacitor.config.json
- client/packages/android/app/src/main/java/org/openmsupply/client/NativeApi.java
- client/packages/android/app/src/main/res/values/strings.xml
- client/packages/android/capacitor.config.ts
- client/packages/host/src/components/Android.tsx
- client/packages/host/src/components/Login/LoginLayout.tsx
- package.json
Fixes #2867 
Fixes #2793 
Fixes #2784
The primary issue is that when there is no network, the call to `serviceInfo.getHost()` returns null. We then try to call `getHostAddress()` on the result which crashes the app.
I also noticed that the login screen looks squashed in portrait orientation, so have tweaked that:
From this
to this:
And while I was at it, did the change for #2793 too.
A couple of scenarios:
**One**
- enable network
- start the app and select server mode
- initialise the tablet
- login
- disable network
- try to do something
**Two**
- Close the app
- disable the network
- open the app
Check that, when the network is enabled, you can see the local IP as the server info - but the API calls are made to `localhost`:
When the network is not enabled, the IP resolution cannot …
> Android issues when running offline

- client/packages/requisitions/src/RequestRequisition/api/hooks/document/useDeleteSelectedRequisitions.ts
Fixes #2776 
Enables the query for requests, so we have some data to match the selected lines to.
https://github.com/msupply-foundation/open-msupply/assets/55115239/f5f4218f-e619-4165-8e6c-15125e0cc5e3
1. Go to 'Internal Orders'
2. Select any order/s with status = 'Draft'
3. Select dropdown > ' Delete lines'
4. See delete confirmation modal, select Ok
5. Line is deleted
Unsure if the request was disabled for any reason? Wondered if the automatic query was being disabled to reduce the load time, with the intention of calling it manually at the time it was actually needed, but I don't see that pattern anywhere else in the code...
> 2776 cannot select and delete internal orders

- .github/workflows/pr-issue-label-sync.yaml
Fixes #2871
I had to test in a separate repo to refine this...
[`pull_request`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request) seems to strictly work for only the default branch no matter what I do.
[`pull_request_target`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target) describes allowing running actions from different forks. But IDK, it seems to allow for branches other than the default. I'd have thought branches within the same repo wouldn't be considered a fork (pretty sure fork is a github term for essentially cloning a whole repository into a different org/user's repos, not a git term).
That said, `pull_request_target` has security warnings:
> Warning: For workflows that are …
> 2871 fix label sync action for non default branch PRs

- client/README.md
- server/README.md
#Fixes #2895
Adds instructions around setting up a remote site for omSupply in your local mSupply instance for initial sync.
N/A
> 2895 add set up steps for msupply remote site

- server/server/src/cold_chain/sensor.rs
- server/server/src/cold_chain/temperature_breach.rs
- server/server/src/cold_chain/temperature_log.rs
#2720 
Adds `error!` log messages on errors saving data from the API.
Returns an http error status when there's an error for a single row.
The cold chain app logic seems to only retry sending if there's an API error, so if a single record fails and it gets a 200 reponse from open-mSupply it might not re-send.
```typescript
function* syncSensors({
payload: { sensorUrl },
}: PayloadAction<SyncSensorsActionPayload>): SagaIterator {
const syncQueueManager: SyncQueueManager = yield call(getDependency, 'syncQueueManager');
const syncOutManager: SyncOutManager = yield call(getDependency, 'syncOutManager');
try {
const totalRecordsToSend: number = yield call(syncQueueManager.lengthSensors);
let iter = totalRecordsToSend;
do {
const syncLogs: Sensor[] = yield call(syncQueueManager.nextSensors); …
```
> Add logging on Temperature Logs and Temperature Breaches API Errors

- client/packages/common/src/intl/locales/en/app.json
- client/packages/common/src/intl/locales/en/common.json
- server/repository/src/database_settings.rs
- server/service/src/sync/synchroniser.rs
Fixes #1786
Wait a little longer for the time out (30s rather than 15s) and update the error message to 
`The central server took too long integrating pushed records. Please retry later.`
I had to force the issue in code - by preventing the early return, adding a delay to the mSupply API and reducing the timeout value.
I think it's ok to glance at this and approve without testing, which is problematic. Perhaps @clemens-msupply has a dataset which causes the issue, if you want to test?
> Wait a little longer for sync push timeout

- server/graphql/types/src/types/temperature_breach.rs
- server/server/src/cold_chain/temperature_log.rs
Fixes #2720
Creates temporary breach records if a temperature log references a breach that doesn't already exist.
This shouldn't be necessary with other code changes in CCA, but did solve a problem for me with breaches created before the app was integrated with Open-mSupply...
Should we include this code? Or just rely on the CCA app update?
I had to add Excusion to the frontend as a breach type, panic seemed to extreme a response to this!
> 2720 cold chain missing data create temporary breaches

- client/packages/requisitions/src/RequestRequisition/DetailView/columns.ts
- client/packages/requisitions/src/ResponseRequisition/DetailView/columns.ts
Fixes #2823
Fixes the overlapping column header/checkbox for Requisition detail view.
Very tiny fix, just disabled the width and let it determine it automatically. I could just set a bigger width (change from 100 to 150, say), but I'm just copying what has been done for Internal orders.
@roxy-dao I think the scroll bar is a bit of a red herring -- I get the horizontal scroll bar fine when I narrow the window (in all browsers)
> Make final column auto-width

- client/packages/common/src/hooks/useDebounce/useDebouncedValueCallback.ts
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEdit.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditForm.tsx
- client/packages/invoices/src/StockOut/utils.tsx
Fixes #2727
Debounces the issue quantity change to allow entry of multi-digit values.
currently, if you have a range of unhelpful pack sizes available, then the allocation logic will round up your quantity, overwriting the entered digits and preventing you from entering in the desired quantity.
* Have some stock for an item, which has pack sizes other than `1`
* Create an outbound shipment, add that item
* Issue a quantity for a number which contains multiple digits and starts with `1` e.g. `10` or `105` etc.
> Outbound shipment allocation - unable to type multi digit quantities

- client/packages/common/package.json
- client/packages/common/src/intl/utils/DateUtils.test.ts
- client/packages/common/src/intl/utils/DateUtils.ts
- client/packages/common/src/utils/formatters/formatters.test.ts
- client/packages/programs/src/JsonForms/common/components/Date.tsx
- client/packages/programs/src/JsonForms/components/DateOfBirth.tsx
- client/yarn.lock
Add timezone agnostic function for datetime picker
Fixes #2912 
Adds a function to convert date only strings to a ISO date for the start of day in users' local time rather than UTC local time.
Using normal naive date time functions caused issue when timezones behind UTC were used, which caused the date to be displayed as the previous day.
Go to patients -> open patient create modal or patient detail view
Change the DOB of a patient and see it show as the correct day in the modal / detail view.
Still in draft - other use cases for date input to be added.
> 2912 add timezone agnostic date time for picker

- server/repository/src/db_diesel/patient.rs
Fixes #2994
Use name_dsl instead of program_enrolment_dsl since program enrolment doesn't have patient id anymore.
1. Make sure program enrolment name filter is still working
2. Make sure it builds
>  2994 New program enrolment name is breaking build

- client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/PrescriptionLineEdit.tsx
- client/packages/invoices/src/Prescriptions/api/api.ts
Fixes #2996
The prescription mutation behaves differently for the new status / first item added, in that the status is also updated.
This has been changed, I've put the status update into the same batch mutation that inserts the new prescription line and testing this version I've been unable to reproduce the issue.
Tested using the debug build in [this folder](https://drive.google.com/open?id=1Ax4J-x4-ZXbyOzpM_VixVGQ9WxW4jn2Q&usp=drive_fs). The apk is `open-msupply-1.6.02-debug.apk` and is signed with the release key, so that you can update over a release version without uninstalling.
Have run in server mode, sync'd with a datafile with 50k+ patients ([this datafile](https://drive.google.com/file/d/1fdoYKhSzlEZz645DJGiZvB0B05JJAGkB/view?usp=drive_link)) and created a prescription. Closed …
> Consolidate prescription mutations

- server/Cargo.lock
- server/Cargo.toml
- server/cli/Cargo.toml
- server/graphql/form_schema/Cargo.toml
- server/graphql/plugin/Cargo.toml
- server/graphql/programs/Cargo.toml
- server/report_builder/Cargo.toml
- server/server/Cargo.toml
- server/service/Cargo.toml
Part of #2883 
I removed all openssl dependencies for the server and replaced it by rusttls. This is more likely to build on macos.
This might require extra testing?
> Remove openssl as a dependency (to fix Android build on Macs)

- server/repository/src/migrations/v1_07_00/barcode_add_manufacturer_link_id.rs
- server/service/src/sync/translations/barcode.rs
Fixes #3005
Ignore the typo in the branch... Removed the postgres constraint on barcode manufacturer link id... This constraint expects the column to be NOT NULL, and if this field is often missing in the barcode then safe to remove. Not sure why it doesn't bug for other FK's that are nullable though.... but they seem to be migrating fine so far?
> 3005 Remove constraint on barcode manufacturer link id

- client/packages/system/src/Patient/PatientView/AddButton.tsx
Fixes #653 
Set the selected SplitButton option depending on the active patient program tab.
Change between different tabs while being on the patient page. The "Add" button at the top should update.
> Update the "Add" SplitButton dependent on the active tab

- client/packages/android/build_remote_server_libs.sh
- server/Cargo.lock
- server/Cargo.toml
- server/cli/Cargo.toml
- server/graphql/form_schema/Cargo.toml
- server/graphql/plugin/Cargo.toml
- server/graphql/programs/Cargo.toml
- server/report_builder/Cargo.toml
- server/server/Cargo.toml
- server/service/Cargo.toml
The remaining issue was that ring 0.16.20 was not compiling correctly. To make it work some env variables needed to be pointed to the correct AR and CC binaries.
Fixes #2883
The remaining issue was that ring 0.16.20 was not compiling correctly. To
make it work some env variables needed to be pointed to the correct AR
and CC binaries.
Note, this might break the compilation using the older Rust and ndk versions, but I think if this patch is working for everybody we should just require the latest versions.
- Install Android NDK 26.1.10909125
- Update to latest Rust (`rustup default stable`)
- Delete the `client/packages/android/server-lib` directory 
- Update your NDK_BIN env variable to the correct (check it points to the new ndk 26: `echo $NDK_BIN`)
- Compile the apk `yarn …
> Add support to build Android with ndk 26 and Rust 1.76

- server/service/src/sync/test/integration/README.md
- server/service/src/sync/test/integration/central/document_registry.rs
- server/service/src/sync/test/integration/central/form_schema.rs
- server/service/src/sync/test/integration/central/inventory_adjustment_reason.rs
- server/service/src/sync/test/integration/central/master_list.rs
- server/service/src/sync/test/integration/central/name_and_store_and_name_store_join.rs
- server/service/src/sync/test/integration/central/period_schedule_and_period.rs
- server/service/src/sync/test/integration/central/report.rs
- server/service/src/sync/test/integration/central/unit_and_item.rs
- server/service/src/sync/test/integration/central_server_configurations.rs
- server/service/src/sync/test/integration/errors.rs
- server/service/src/sync/test/integration/mod.rs
- server/service/src/sync/test/integration/omsupply_central/mod.rs
- server/service/src/sync/test/integration/omsupply_central/pack_variant.rs
- server/service/src/sync/test/integration/omsupply_central/test.rs
- server/service/src/sync/test/integration/remote/activity_log.rs
- server/service/src/sync/test/integration/remote/clinician.rs
- server/service/src/sync/test/integration/remote/document.rs
- server/service/src/sync/test/integration/remote/invoice.rs
- server/service/src/sync/test/integration/remote/location.rs
- server/service/src/sync/test/integration/remote/location_movement.rs
- server/service/src/sync/test/integration/remote/patient_name_and_store_and_name_store_join.rs
- server/service/src/sync/test/integration/remote/program_requisition.rs
- server/service/src/sync/test/integration/remote/requisition.rs
- server/service/src/sync/test/integration/remote/stock_line.rs
- server/service/src/sync/test/integration/remote/stocktake.rs
- server/service/src/sync/test/integration/remote/user_permission.rs
- server/service/src/test_helpers.rs
Links to #2062-3 (integration tests for omSupply central)
The updated docs should explain what this PR achieves.
* Add om_supply_central_graphql_operations to integration TestData struct, which also required adding Default spread on existing tests. This field allows mutating data in omSupply central (which needs to be started in `APP_SERVER__DEBUG_NO_ACCESS_CONTROL` mode, thank you @clemens-msupply for this field, made this functionality so much simpler (otherwise would need to create user, login etc..)
* Creates TestData for pack variant
* Adds omSupply central config test driver, which has a helper for running graphql query and for asking omSupply central to sync. 
Running integration tests as per integration test doc
See PR with docs for further explanation of omSupply central server …
> Central config server transition integration tests

- client/packages/common/src/intl/locales/en/replenishment.json
- client/packages/invoices/src/Returns/OutboundListView/AppBarButtons.tsx
- client/packages/invoices/src/Returns/api/api.ts
- client/packages/invoices/src/Returns/api/hooks/document/useInsertSupplierReturn.ts
Fixes #3008 
All this was already in the list view, but now connects the insert mutation on supplier selection and redirects to the resulting details view:
- On the outbound return list view, click `New Return`
- Supplier selection modal appears
- When you select a supplier, the mutation is called, and you are redirected to the detail page
> 3008 create outbound return from list view

- client/packages/common/src/intl/locales/en/distribution.json
- client/packages/invoices/src/Returns/InboundListView/AppBarButtons.tsx
- client/packages/invoices/src/Returns/api/api.ts
- client/packages/invoices/src/Returns/api/hooks/document/useInsertInboundReturn.ts
Fixes #3014 
Selecting a customer here now calls the insertInboundReturn mutation and redirects to the detail URL (page incoming lol)
- On the inbound returns list view, click `New Return`
- Customer selection modal appears
- When you select a customer, the insert mutation is called, and you are redirected to the detail page
> 3014 add new inbound return from list view

- client/packages/common/src/intl/locales/en/distribution.json
- client/packages/common/src/intl/locales/en/replenishment.json
- client/packages/common/src/types/schema.ts
- client/packages/invoices/src/InboundShipment/DetailView/DetailView.tsx
- client/packages/invoices/src/InboundShipment/DetailView/Toolbar.tsx
- client/packages/invoices/src/InboundShipment/api/hooks/index.ts
- client/packages/invoices/src/InboundShipment/api/hooks/utils/index.ts
- client/packages/invoices/src/InboundShipment/api/hooks/utils/useSelectedStockLineIds.ts
- client/packages/invoices/src/OutboundShipment/DetailView/DetailView.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/Toolbar.tsx
- client/packages/invoices/src/OutboundShipment/api/hooks/index.ts
- client/packages/invoices/src/OutboundShipment/api/hooks/utils/index.ts
- client/packages/invoices/src/OutboundShipment/api/hooks/utils/useSelectedStockLineIds.ts
- client/packages/invoices/src/Returns/api/api.ts
- client/packages/invoices/src/Returns/api/hooks/line/useInboundReturnLines.ts
- client/packages/invoices/src/Returns/api/operations.generated.ts
- client/packages/invoices/src/Returns/api/operations.graphql
- client/packages/invoices/src/utils.ts
- server/graphql/general/src/queries/generate_inbound_return_lines.rs
- server/graphql/general/src/queries/generate_outbound_return_lines.rs
Fixes #3038
In previous PRs I had conflated inbound/outbound shipment line ids and stock line ids. This PR corrects that, mapping to the selected stock line ids to be passed to the generate return line queries!
It felt easiest/cleanest to do this mapping in the useSelectedIds hooks - just return the stockLinesId of each selected line, rather than the selected line ids, and then having to map at a later point. Does the code read/flow ok to you?
It all still compiles/runs 🎉
> 3038 map to stock line ids

- client/packages/common/src/authentication/api/api.ts
- client/packages/common/src/authentication/api/hooks/index.ts
- client/packages/common/src/authentication/api/hooks/useAuthApi.ts
- client/packages/common/src/authentication/api/hooks/useIsCentralServer.ts
- client/packages/common/src/authentication/api/operations.generated.ts
- client/packages/common/src/authentication/api/operations.graphql
- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/types/schema.ts
- client/packages/host/src/Host.tsx
- client/packages/system/src/Item/DetailView/Tabs/PackVariants.tsx
- client/packages/system/src/Item/api/api.ts
- client/packages/system/src/Item/api/operations.generated.ts
- client/packages/system/src/Item/api/operations.graphql
- client/packages/system/src/Item/context/usePackVariant.ts
- server/graphql/general/src/lib.rs
- server/graphql/lib.rs
- server/graphql/tests/permissions.rs
- server/service/src/sync/synchroniser.rs
Fixes #2502 
* add isCentralServer graphql query (no permission check, should it have ?)
* move central server graphql mutations behind centralServer endpoint (idea is to have one place where isCentralServer is checked)
* add isCentralServer api query to front end, and useIsCentralServerOrWarning hook to help with central server checks
* disallow deleting of pack variant when user doesn't have permission (this was done for editing and for creating pack variants but not for delete)
* Silently ignore sync error to omSupply central server, this is just temporary, this point is in carry over issue, we can discuss this tomorrow as it's in the [carry over issue](https://github.com/msupply-foundation/open-msupply/issues/2821)
Start server in central server mode:
IS_CENTRAL_SERVER=true cargo run …
> 2502 restrict pack variant editing to central server

- server/repository/src/db_diesel/assets/asset.rs
- server/repository/src/db_diesel/assets/asset_catalogue_item.rs
- server/repository/src/db_diesel/assets/asset_internal_location_row.rs
- server/repository/src/db_diesel/assets/asset_location_row.rs
- server/repository/src/db_diesel/assets/asset_row.rs
- server/repository/src/db_diesel/assets/mod.rs
- server/repository/src/migrations/v1_08_00/assets/asset.rs
- server/repository/src/migrations/v1_08_00/assets/mod.rs
- server/repository/src/mock/mod.rs
Fixes #2972 
Adds the `asset` and `asset_internal_location` tables.
For MVP, we're considering leaving out locations but that would compromise MVP Goal #1
>Provide real-time visibility of functional storage capacity (used vs unused volume) of CCE at a national level with granularity down to the Service Delivery Points.
We could have a single location associated with the asset if we allowed hierarchical locations, which does exist, however I assume that's more work to bring in to the MVP than what I've currently done...
> 2972 create asset tables

- client/packages/inventory/src/Stocktake/api/hooks/line/useStocktakeLines.ts
- client/packages/inventory/src/Stocktake/api/hooks/line/useStocktakeSaveLines.ts
- client/packages/inventory/src/Stocktake/api/hooks/utils/useStocktakeApi.ts
Fixes #3048
The cache invalidation which is called when the stocktake is updated is using the stocktake number in the cache key
However the hook `useStocktakeLines` was using the stocktake id in the cache key, so wasn't seeing the update after the stocktake was saved.
There are more usages of number, so have renamed the cache parameter to number and updated the `useStocktakeLines` hook.
Open a stocktake, and add an item. This should show on clicking OK.
Edit a line, and update the counted number of packs - check that the value is updated in the table on clicking OK.
> Fix stocktake detail cache invalidation

- server/service/src/sync/translations/invoice.rs
Fixes #2728 
How to reproduce:
1) setup a mobile site, e.g Huff and sync with the central server (think this is needed otherwise the central server doesn't transfer invoices if the site is not old mSupply?)
2) setup an omSupply site e.g. Ravenclaw
3) send an outbound shipment from Ravenclaw to Huff (choose a unique reference to easily identify the shipment later). Set status to shipped. Sync.
4) stop the mobile site and "migrate" the Huff site to open mSupply (open it in omSupply)
Central should have a `transact` record now with type="si" and om_type="OUTBOUNT_SHIPMENT". This is because mSupply just copied the full outbound shipment for the transfer from Ravenclaw to Huff. This is a problem when integrating this record in omSupply because `om_type` is preferred over `type`, i.e. the …
> Remove all om_* fields from transfered generated in mSupply

- client/packages/common/src/intl/utils/IntlUtils.ts
- client/packages/common/src/ui/components/inputs/DatePickers/DateTimePickerInput/DateTimePickerInput.tsx
- client/packages/programs/src/JsonForms/common/components/DateTime.tsx
- client/packages/system/src/Encounter/DetailView/Toolbar.tsx
Fixes #3052
Make sure that the end time for encounters
Didn't do it in this PR since this is just a bug fix, but I think there should be some validations in place for end time so that the user doesn't choose a time that is before the start time.
> 3052 Cannot choose the time correctly in date-time picker

- client/packages/common/src/intl/currency/currency.test.tsx
- client/packages/common/src/intl/number/IntlNumber.ts
- client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NumberInputCell.tsx
- client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts
- client/packages/programs/src/JsonForms/components/EncounterLineChart.tsx
- client/packages/programs/src/JsonForms/components/QuantityDispensed.tsx
Fixes #2932 
This fixes the items listed in #2932, except for two of them (unticked), but they're covered by [this issue's suggested solution](https://github.com/msupply-foundation/open-msupply/issues/2918#issuecomment-1965489335).
The main problem I discovered is that the `format` method (in NumUtils), which uses `Intl.NumberFormat`, defaults to 3 dp. So I've just made set that to default to the maximum allowed (21 dp) and we can continue using our `.round()` method to handle precision.
Tested the main cases listed in the issue. However I haven't properly tested the two Programs components affected. All I did there was remove the `type="number"` attribute, so I think it should be fine but if anyone has Programs set up on their system and can confirm it's okay, that'd be great.
> #2932 Number fixes

- client/packages/common/src/types/schema.ts
- client/packages/system/src/Asset/api/api.ts
- client/packages/system/src/Asset/api/operations.generated.ts
- client/packages/system/src/Asset/api/operations.graphql
Fixes a bug where asset queries are trying to use a store_id which doesn't exist in graphql
> Remove store_id from catalogue queries

- client/packages/common/src/intl/currency/currency.test.tsx
- client/packages/common/src/intl/currency/currency.ts
- server/graphql/general/src/queries/mod.rs
- server/repository/src/db_diesel/mod.rs
Fixes #3084
Displays currency in locale format. 
- mSupply
- om
> 3084 Currency display should be dependant on language

- client/packages/common/src/utils/environment/EnvUtils.ts
Fixes #3160 
Adds the new returns routes to EnvUtils so we get page titles in the browser tabs, and adds a placeholder for links to docs.
i.e:
We don't have any public docs for returns yet, but when we do, we should update the docs link to point to them!
> Add page titles and placeholder docs links

- client/packages/coldchain/src/Monitoring/ListView/TemperatureBreach/TemperatureBreachList.tsx
- client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/TemperatureChart.tsx
- client/packages/coldchain/src/Monitoring/ListView/TemperatureLog/TemperatureLogList.tsx
- client/packages/coldchain/src/Sensor/Components/SensorLineForm.tsx
- client/packages/coldchain/src/Sensor/ListView/ListView.tsx
- client/packages/coldchain/src/common/utils.ts
- client/packages/common/src/intl/locales/en/coldchain.json
Fixes #3055 & #3030
Updates the temperature formats to use `Intl.NumberFormat` and handle the undefined values that were being returned in sensor modal
> 3055 & 3030 cold chain display

- client/packages/common/src/intl/locales/en/dispensary.json
- client/packages/common/src/intl/locales/en/distribution.json
Fixes #2917
Quick fix to change the stock expired allocation message
Update docs screenshot
> 2917 Cannot allocate expiry message not clear enough

- client/packages/common/src/ui/components/inputs/TextInput/BasicTextInput.tsx
- client/packages/invoices/src/InboundShipment/DetailView/Toolbar.tsx
- client/packages/invoices/src/InboundShipment/ListView/ListView.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/Toolbar.tsx
- client/packages/invoices/src/OutboundShipment/ListView/ListView.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/Toolbar/Toolbar.tsx
- client/packages/requisitions/src/RequestRequisition/ListView/ListView.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/Toolbar.tsx
- client/packages/requisitions/src/ResponseRequisition/ListView/ListView.tsx
Fixes #3079
** Ignore branch name was created for another bug and forgot to change 🙄 and renaming will close PR again **
Adds tooltip to invoice/requisition list views and detail header for comments/references since long references/comments get cut off.
> Inbound shipments: long references not visible when status is "shipped" #3079

- client/packages/coldchain/src/Monitoring/ListView/TemperatureBreach/TempereatureBreachCells.tsx
- client/packages/common/src/ui/components/popover/PaperPopover/PaperPopoverSection.tsx
Fixes #3076 
Stops comment from overflowing in cold chain pop over
> 3076 coldchain breach comment overflow

- server/graphql/programs/src/queries/program_event.rs
- server/graphql/types/src/types/program/encounter.rs
- server/graphql/types/src/types/program/program_enrolment.rs
- server/service/src/programs/encounter/encounter_updated.rs
- server/service/src/programs/encounter/suggested_next_encounter.rs
- server/service/src/programs/program_event.rs
Not directly part of #2857
Some small refactoring that I noticed while working on #2357. In other places the allowed_ctx permission check is done in the service, so I did the same for program events. Previously, it made it hard to validate that permissions are taken into account correctly.
> 2857 program event clean up

- client/packages/programs/src/JsonForms/components/Search/SearchWithUserSource.tsx
Fixes #3051
Fix the patient check.
> 3051 Doesn't select the searched entry from list in program enrolment form

- client/packages/system/src/Patient/Encounter/CreateEncounterModal.tsx
Fixes #3157 
Disable the modal save button when creating an encounter
I couldn't reproduce it myself. @nisha-dangol ?
> Disable the modal save button when creating an encounter

- client/packages/coldchain/src/index.ts
- client/packages/common/src/intl/utils/IntlUtils.ts
- client/packages/host/webpack.config.js
- client/packages/programs/package.json
Fixes #2813 
The required change is to remove common package from the module federation shared bundles. The intention was that each package could use the federated version, the unintended consequence is that weback is unable to tree shake because it doesn't know what is required or not from that bundle. The entire common package was bundled up, all 8MB of it.
Tracked down to [this commit](https://github.com/msupply-foundation/open-msupply/pull/2568/commits/c52b31970bf730e0c9e5402e5759b6a9a21418b9#diff-b142eb1f4548423b3c912cf3b5570e8d2d5a823f5eb09da7607cfb845608e130)
The PR action should show if this works or not. Otherwise you could run the bundle analyzer plugin and see what size you get
> Reduce bundle size

- server/server/src/lib.rs
- server/server/src/sync_on_central/mod.rs
Moves the `central_server_only` middleware to be called inside a `Scope` otherwise it appears to apply more widely than I realised
See if you can login :)
> Fix central_server_only middleware wrap

- client/packages/programs/src/JsonForms/components/QuantityDispensed.tsx
Fixes #3142 
Don't show the end of supply date when no data has been entered yet.
- Create new encounter
- end of supply should not show until the "Pill count (at start)" and/or "Quantity of pills dispensed" has been entered.
- end of supply should show when entering 0
> Fix end of supply display

- client/packages/programs/src/JsonForms/common/components/Text.tsx
- client/packages/system/src/Patient/DefaultPatientSchema.json
Fixes #3126
Sets firstName and lastName to required for the default patient schema. This also required to unset empty text fields, e.g. when deleting all text from a text input the data field is set to undefined. This is needed because an empty string passes the required test.
I tested a bit and I think this should be fine...
> 3126 mandatory patient fields 2

- client/packages/common/src/ui/layout/tables/components/Header/ColumnPicker.tsx
Fixes #3125 
Removed arrow function return to make columns hide.
> Table Hide/Show columns selector not mapping selection correctly #3125

- client/packages/system/src/Patient/PatientView/Footer.tsx
- client/packages/system/src/Patient/PatientView/PatientView.tsx
Fixes #2541
Enables the cancel button on patient detail view and also show confirmation when user clicks on the cancel button if they have unsaved changes.
> 2541 can't close a patient without first editing something

- client/packages/common/src/ui/components/inputs/DatePickers/BaseDatePickerInput/BaseDatePickerInput.tsx
Fixes #2926
Fix position of the datetime popper, so that it doesn't move when selecting dates.
https://github.com/msupply-foundation/open-msupply/assets/61820074/1b781609-9e0e-4664-ab88-8e4fbecb7a9c
> 2926 Datepicker moves if it is to close to the edge

- client/packages/common/src/ui/layout/tables/utils/ColumnUtils.test.ts
- client/packages/common/src/ui/layout/tables/utils/ColumnUtils.ts
Fixes #3029
Handles the case if there are now lines, i.e. return "" instead of "multiple"
See issue description
> Return empty string instead of "multiple" if there are no lines

- client/packages/common/src/hooks/useQueryParams/types.ts
- client/packages/common/src/hooks/useQueryParams/useQueryParams.test.tsx
- client/packages/common/src/hooks/useQueryParams/useQueryParamsStore.tsx
- client/packages/common/src/hooks/useUrlQuery/useUrlQuery.ts
- client/packages/common/src/hooks/useUrlQuery/useUrlQueryParams.ts
- client/packages/common/src/ui/layout/tables/columns/types.ts
- client/packages/common/src/ui/layout/tables/components/Header/Header.stories.tsx
- client/packages/common/src/ui/layout/tables/components/Header/Header.tsx
- client/packages/common/src/ui/layout/tables/hooks/useColumns/useColumns.tsx
- client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts
- client/packages/invoices/src/InboundShipment/api/hooks/line/useInboundItems.ts
- client/packages/invoices/src/OutboundShipment/DetailView/columns.ts
- client/packages/invoices/src/OutboundShipment/ListView/ListView.tsx
- client/packages/invoices/src/OutboundShipment/api/api.ts
- client/packages/invoices/src/Prescriptions/DetailView/columns.ts
- client/packages/system/src/Encounter/ListView/columns.ts
- client/packages/system/src/Patient/ContactTrace/Components/ListView.tsx
Fixes #3112 
The bug has been introduced here:
https://github.com/msupply-foundation/open-msupply/pull/2638/files#r1426169816
The problem was that `asc` is mapped to an empty query string. This means when there was no sort direction because of that, the initial direction was always used.
- Fixes some lint warnings (first commit)
- Fixes the sort problem
Note: the initial sort direction is not used now...
> 3112 fix sort direction

- client/packages/common/src/api/GqlContext.tsx
- client/packages/common/src/authentication/api/api.ts
- client/packages/common/src/intl/locales/en/app.json
- client/packages/host/src/components/Login/Login.tsx
Fixes #3254
Improved message if db is locked on sign in... open for message suggestions
> 3254 User Login fails If sqlite database is locked for writing

- client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx
- client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
Fixes #3288
When we refactored the NumberInputCell, we set the default `min` to `1` as that was the more common case in the implementations. However, this means we need to explicitly set `min=0` in the places that need it. 
Working for stocktakes
@roxy-dao can you think of any other places this might be an issue?
> #3288 Fix for 0 value in stocktake count

- server/service/src/asset/tests/insert_log.rs
Context was incorrectly created causing a `FOREIGN KEY constraint failed` error on store_id.
Turns out `asset_id` was used instead of `store_id`
> Fix asset_log test

- client/packages/common/src/types/schema.ts
- client/packages/programs/src/JsonForms/components/Search/SearchWithUserSource.tsx
- client/packages/system/src/Patient/Components/utils.ts
- server/graphql/programs/src/queries/patient_search.rs
- server/graphql/programs/src/queries/patient_search_central.rs
- server/graphql/types/src/types/program/patient.rs
- server/repository/src/db_diesel/patient.rs
- server/service/src/programs/patient/search.rs
- server/service/src/programs/patient/search_central.rs
Fixes #2109
Unify name_or_code and identifier filter for patient (i.e. add `OR` name filtering to identifier and remove name_or_code)
> 2109 Patient query fails for name_or_code AND identifier

- client/packages/common/src/ui/components/navigation/Tabs/DetailTabs.tsx
Fixes #3213
Fixes underline being in funky places
> 3213 Selected tab underline doesn't move correctly with SidePanel open/close

- server/repository/src/db_diesel/item.rs
- server/repository/src/db_diesel/master_list_line.rs
- server/service/src/invoice/inbound_shipment/add_from_master_list.rs
- server/service/src/invoice/outbound_shipment/add_from_master_list.rs
- server/service/src/requisition/request_requisition/add_from_master_list.rs
- server/service/src/stocktake/insert.rs
Fixes #3269
Removes service items when adding from Master List.
Quick fix until Service Charge KDD done and we decide what to do with service charges.
> 3269 remove service charge when adding from master list

- client/packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.ts
Fixes #3174 
Without increasing the column width `TooltipTextCell` can display up to 8 char. Plus there is a tooltip now:
Note, I made a comment regarding padding:
https://github.com/msupply-foundation/open-msupply/issues/3174#issuecomment-2002643639
TooltipTextCell doesn't have this padding for which reason I kept the column width.
Also should we use TooltipTextCell as a default? Probably other columns suffer the same problem?
> Use a TooltipTextCell to display batch columns

- client/packages/programs/src/JsonForms/common/components/Number.tsx
- client/packages/programs/src/JsonForms/stripEmptyAdditions.test.ts
- client/packages/programs/src/JsonForms/stripEmptyAdditions.ts
Fixes #3050
- Enables decimal values for the JSONFroms Number input. This was not part of the issue but it wasn't possible to enter the height in meter...
- Fix the underlying problem: stripEmptyAdditions re-added deleted primitive data fields
As described in the issue, save height reload and then delete the height. The save button should be enabled now.
> 3050 fix height input

- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditTable.tsx
- client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/PrescriptionLineEditTable.tsx
Fixes #3246
Have vertical scroll on table instead of in whole modal.
https://github.com/msupply-foundation/open-msupply/assets/61820074/46ed0b76-54fe-4d3b-9066-67d0be2e45fb
> 3246 Vertical scroll in modals breaks the rounded corners

- client/packages/invoices/src/InboundShipment/api/hooks/utils/useSelectedStockLineIds.ts
- client/packages/invoices/src/Returns/InboundDetailView/DetailView.tsx
- client/packages/invoices/src/Returns/api/api.ts
- client/packages/invoices/src/Returns/api/hooks/document/useInboundReturn.ts
- client/packages/invoices/src/Returns/api/hooks/document/useInbounds.ts
- client/packages/invoices/src/Returns/api/hooks/document/useInsertInboundReturn.ts
- client/packages/invoices/src/Returns/api/hooks/document/useInsertOutboundReturn.ts
- client/packages/invoices/src/Returns/api/hooks/document/useOutboundReturn.ts
- client/packages/invoices/src/Returns/api/hooks/document/useOutbounds.ts
- client/packages/invoices/src/Returns/api/hooks/index.ts
- client/packages/invoices/src/Returns/api/hooks/line/index.ts
- client/packages/invoices/src/Returns/api/hooks/line/useDeleteSelectedInboundLines.ts
- client/packages/invoices/src/Returns/api/hooks/line/useGenerateInboundReturnLines.ts
- client/packages/invoices/src/Returns/api/hooks/line/useInboundReturnRows.ts
- client/packages/invoices/src/Returns/api/hooks/line/useUpdateInboundReturnLines.ts
- client/packages/invoices/src/Returns/api/hooks/utils/useReturnsApi.ts
- client/packages/invoices/src/Returns/api/operations.generated.ts
- client/packages/invoices/src/Returns/api/operations.graphql
- client/packages/invoices/src/Returns/modals/InboundReturn/InboundReturn.tsx
- client/packages/invoices/src/Returns/modals/InboundReturn/ItemSelector.tsx
- client/packages/invoices/src/Returns/modals/InboundReturn/ReturnQuantitiesTable.tsx
- client/packages/invoices/src/Returns/modals/InboundReturn/ReturnSteps.tsx
- client/packages/invoices/src/Returns/modals/InboundReturn/useDraftInboundReturnLines.ts
- client/packages/invoices/src/Returns/modals/OutboundReturn/ReturnQuantitiesTable.tsx
- client/packages/invoices/src/Returns/modals/ReturnReasonsTable.tsx
Fixes #3189
Implements the add by item/edit line version of the inbound return edit modal, and updates the table cells to be inputs:
- Add a new inbound return
- From the detail view, click Add Item
- Select an item
- Ok & Next, input reason/comment, OK
> 3189 add lines by item

- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/intl/locales/en/inventory.json
- client/packages/common/src/intl/locales/en/replenishment.json
- client/packages/common/src/intl/locales/es/inventory.json
- client/packages/common/src/intl/locales/es/replenishment.json
- client/packages/common/src/intl/locales/fr/inventory.json
- client/packages/common/src/intl/locales/fr/replenishment.json
- client/packages/common/src/intl/locales/pt/inventory.json
- client/packages/common/src/intl/locales/pt/replenishment.json
- client/packages/common/src/intl/locales/ru/inventory.json
- client/packages/common/src/intl/locales/ru/replenishment.json
- client/packages/common/src/intl/locales/tet/inventory.json
- client/packages/common/src/intl/locales/tet/replenishment.json
- client/packages/common/src/ui/layout/tables/components/Header/Header.tsx
Fixes #3173 
- Add an ellipsis to prevent label overflow
- Put the description in the header tooltip (to show the full label if the label is too long
Test as described in issue or set "label.location" to a long label
> Handle long column labels in table headers

- client/packages/system/src/Report/api/hooks/utils/usePrintReport.ts
Fixes #3328 
The report iframe was suddenly displayed in the bottom left corner (firefox and chrome) even though I haven't seen this before.
Hiding the frame fixes the issue while still renders the report correctly.
Test if reports are still showing correctly.
> Hide the report printing frame to prevent it from being rendered

- client/packages/inventory/src/Stocktake/DetailView/SidePanel.tsx
- client/packages/inventory/src/Stocktake/ListView/ListView.tsx
- client/packages/invoices/src/InboundShipment/DetailView/SidePanel/AdditionalInfoSection.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/SidePanel/AdditionalInfoSection.tsx
- client/packages/invoices/src/Prescriptions/DetailView/SidePanel/AdditionalInfoSection.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/AdditionalInfoSection.tsx
Fixes #911
Add created datetime to the side panel and also localise the stocktake list view created datetime for consistency.
I've noticed that some datetimes throughout the app might not be localised and have created an issue here to fix it... #3357. Currently the tooltip stocktake date is different from the created datetime since its not localised... probably also want to discuss if we want this enabled some time since stocktake date can differ from created datetime
> 911 show created date in the detail panel for invoice, requisition, stocktake windows

- client/packages/invoices/src/utils.ts
Fixes #3363
Consolidate frontend and backend logic for outbound shipment deletion. Have allowed deletion until status is `Picked` since stock does get added back on.
Have updated docs to match
> Allow outbound shipments to be deleted until picked

- server/service/src/sync/test/mod.rs
- server/service/src/sync/translation_and_integration.rs
- server/service/src/sync/translations/master_list_line.rs
- server/service/src/sync/translations/mod.rs
Fixes #3306
Adds support to delete master_list_lines. The delete request were coming from the central server but weren't handled by omSupply.
See issue on how to reproduce the bug
> Implement master_list_line try_translate_pull_delete

- server/Cargo.toml
- server/cli/Cargo.toml
- server/graphql/plugin/Cargo.toml
- server/graphql/programs/Cargo.toml
- server/graphql/sensor/Cargo.toml
- server/service/Cargo.toml
Fixes #3340 
You can run graphql test!
Needs testing on Android in case something broke with the changes?
Weirdly rust is building a newer version of `async-graphql-actix-web` than we specify in our workspace. 
Seems like this version only works if rusttls is included?
> Add rusttls to workspace features to fix graphql tests

- client/packages/system/src/MasterList/api/api.ts
- server/graphql/general/src/queries/master_list.rs
- server/graphql/general/src/queries/tests/master_lists.rs
- server/repository/src/db_diesel/master_list.rs
- server/repository/src/mock/full_master_list.rs
- server/service/src/master_list/mod.rs
- server/service/src/master_list/query.rs
- server/service/src/master_list/tests/query.rs
- server/service/src/stocktake/insert.rs
Fixes #3361
Filters master lists by store in backend since this should only be limited to the current store.
> 3361 master list

- server/Cargo.lock
- server/graphql/asset_catalogue/src/lib.rs
- server/graphql/reports/src/lib.rs
- server/graphql/reports/src/printing.rs
- server/report_builder/src/build.rs
- server/report_builder/src/lib.rs
- server/repository/Cargo.toml
- server/repository/src/db_diesel/mod.rs
- server/repository/src/db_diesel/report_query.rs
- server/repository/src/migrations/v1_08_00/central_omsupply.rs
- server/repository/src/migrations/v1_08_00/pack_variant.rs
- server/repository/src/migrations/v1_08_00/sync_file_reference.rs
- server/service/src/asset/update.rs
- server/service/src/auth.rs
- server/service/src/report/definition.rs
- server/service/src/report/report_service.rs
- server/service/src/sync/api_v6/core.rs
- server/service/src/sync/translation_and_integration.rs
Fixes most of #2853 
- Add support to the report builder cli to specify SQL queries (sqlite and postgres) (see doc comment on new params)
- `query_json` helper method for SQLite and Postgres to do raw queries returning the result as a JSON object.
-  The print_report_definition endpoint requires ServerAdmin permissions now since it effectively allows the caller to execute arbitrary queries now(!)
There is a new test for the query_json method. Test with SQLite and Postgres.
Furthermore, there is this branch in the report repo:
https://github.com/msupply-foundation/open-msupply-reports/tree/2853-sql-reports
There is a report under `examples/SQLReport`
To run it create a `config.yaml` in the root directory of the repo like:
```yaml
url: "http://localhost:8000"
username: "..."
password: "..." …
```
> 2853 sql reports

- server/graphql/types/src/types/outbound_return_line.rs
- server/service/src/invoice/outbound_return/generate_outbound_return_lines.rs
Fixes #3326 
Includes the quantity already in the return in the available qty for return.
Adding new item:
Set value to 5:
Save. Click row to re-open modal, available to return is still 10:
> 3326 qty available for return should include amount already in return

- server/graphql/lib.rs
- server/graphql/playground.html
Fixes #3378
Simply brings the changes through from the original PR.
You can now login if you use the /graphql endpoint. Doesn't help me with [graphiql](https://cloud.hasura.io/public/graphiql] which is what I normally use.. might be time to switch over though. the login is super useful.
https://github.com/msupply-foundation/open-msupply/assets/9192912/60820c3a-6785-4db2-962c-592c8c303084
or
> Add login to graphql playground

- client/packages/system/src/MasterList/ListView/AppBarButtons.tsx
- server/repository/src/mock/full_master_list.rs
- server/service/src/master_list/tests/query.rs
- server/service/src/stocktake/insert.rs
Fixes #3361
To fix revert. Export button for master list should only show master lists for store
> Catalogue   master lists   export exports all master lists, not just the ones the store has visibility to #3361

- client/packages/system/src/Stock/Components/Repack/RepackModal.tsx
Fixes #3408
Disable save button if input has been cleared
> 3408 Repacks: 'Number of packs to repack' field is not required

- server/repository/src/migrations/v1_08_00/invoice_required_currency_id.rs
Fixes #3438
Separate SQLite and postgres migrations
I've tested a demo datafile from 1.7 to this branch on postgres and sqlite.
It's nice to keep things the same between SQLite and Postgres where possible but this feels like a good chance to use postgres features which aren't available in sqlite.
> Bug fix making currency_id required

- client/packages/common/src/ui/components/inputs/Select/Select.tsx
- client/packages/host/src/components/LanguageMenu.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditForm.tsx
- client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/PrescriptionLineEditForm.tsx
Fixes #3387
Don't allow users to clear language
> Don't allow clearing of languages

- client/packages/dashboard/src/widgets/ReplenishmentWidget.tsx
Fixes #3386
Show all suppliers regardless of external or internal when creating an inbound shipment from dashboard.
> 3386  Show all suppliers when creating inbound shipment from dashboard

- server/graphql/general/src/queries/store.rs
- server/repository/src/db_diesel/store.rs
- server/repository/src/mock/name_store_join.rs
- server/service/src/sync/translations/special/name_merge.rs
Fixes #3276 
When names are merged, this makes sure that name_store_joins that are effectively duplicates are deleted.
You must sync with each merge until [#3441](https://github.com/msupply-foundation/open-msupply/issues/3441) is done. Otherwise earlier merges will override later merges. e.g.
Create 3 customers, then merge 3->2->1 and THEN sync. The remote site will still have 3 visible, as the later merge overrode it in the buffer.
> 3276 delete duplicate name store joins on merge

- client/packages/dashboard/src/widgets/DistributionWidget.tsx
- client/packages/dashboard/src/widgets/ReplenishmentWidget.tsx
- client/packages/dashboard/src/widgets/StockWidget.tsx
- client/packages/inventory/src/Stocktake/DetailView/SidePanel.tsx
- client/packages/inventory/src/Stocktake/api/hooks/document/useStocktakeDelete.ts
- client/packages/invoices/src/InboundShipment/DetailView/SidePanel/SidePanel.tsx
- client/packages/invoices/src/InboundShipment/ListView/AppBarButtons.tsx
- client/packages/invoices/src/InboundShipment/api/hooks/document/useInboundDelete.ts
- client/packages/invoices/src/InboundShipment/api/hooks/document/useInsertInbound.ts
- client/packages/invoices/src/OutboundShipment/DetailView/SidePanel/SidePanel.tsx
- client/packages/invoices/src/OutboundShipment/ListView/AppBarButtons.tsx
- client/packages/invoices/src/OutboundShipment/api/hooks/document/useOutboundDelete.ts
- client/packages/invoices/src/OutboundShipment/api/hooks/document/useOutboundInsert.ts
- client/packages/invoices/src/Prescriptions/DetailView/SidePanel/SidePanel.tsx
- client/packages/invoices/src/Prescriptions/ListView/AppBarButtons.tsx
- client/packages/invoices/src/Prescriptions/api/hooks/document/usePrescriptionDelete.ts
- client/packages/invoices/src/Prescriptions/api/hooks/document/usePrescriptionInsert.ts
- client/packages/requisitions/src/RequestRequisition/DetailView/SidePanel.tsx
- client/packages/requisitions/src/RequestRequisition/ListView/AppBarButtons.tsx
- client/packages/requisitions/src/RequestRequisition/api/hooks/document/useDeleteRequests.ts
- client/packages/requisitions/src/RequestRequisition/api/hooks/document/useInsertProgramRequest.ts
- client/packages/requisitions/src/RequestRequisition/api/hooks/document/useInsertRequest.ts
- client/packages/requisitions/src/ResponseRequisition/DetailView/AppBarButtons/CreateShipmentButton.tsx
- client/packages/requisitions/src/ResponseRequisition/api/hooks/utils/useCreateOutboundFromResponse.ts
Fixes #2229
Refactor to move all navigation out of hooks.
> 2229 move navigation out of delete hooks

- client/packages/system/src/Patient/CreatePatientModal/FetchPatientModal.tsx
- client/packages/system/src/Patient/CreatePatientModal/PatientResultsTab.tsx
- client/packages/system/src/Patient/CreatePatientModal/useFetchPatient.ts
- client/packages/system/src/Patient/ListView/AppBarButtons.tsx
- client/packages/system/src/Patient/api/hooks/utils/usePatientApi.ts
- client/packages/system/src/Sync/api/hooks/index.ts
- client/packages/system/src/Sync/api/hooks/utils/index.ts
- client/packages/system/src/Sync/api/hooks/utils/useSyncStatus.ts
- server/service/src/programs/patient/search_central.rs
Part of #3143 
- Refactor/create a hook to fetch a patient. I found the previous implementation a bit messy and hope this makes it clearer.
- Enable LIKE patient search for central server patients
There are still some issues I like to look at, at a later stage because I can't figure them out right now:
- After moving the patient over to the local site. The search endpoint fails to return it even though it is in the database and a full page reload fixes it!
- I can't get tanquery to refetch the main patient list automatically even though I invalidated the query key...
> 3143 fetching patient from central

- client/packages/invoices/src/InboundShipment/DetailView/Footer/StatusChangeButton.tsx
- server/repository/src/db_diesel/invoice_line_row.rs
- server/service/src/invoice/inbound_shipment/update/generate.rs
- server/service/src/invoice/inbound_shipment/update/mod.rs
- server/service/src/processors/transfer/shipment/create_inbound_shipment.rs
Fixes #3458
Fixes receiving stock not more than once during stock transfer.
- Setup multiple oms sites along with msupply desktop sites and the central sync server.
- Make visible of those sites' active stores among each other from the central sync server.
- Create an outbound shipment against one of those remote site from an another remote site and sync.
- Sync from another site and in the inbound shipment list you'll see a new inbound shipment from your supplying store.
- Now process that shipment and confirm it.
- Check item's stock, note it down.
- Again to goto the same inbound shipment and click confirm verified and again check the stock of that item.
or
> 3458 Fix receiving stock more than once in the stock transfer

- client/packages/common/src/intl/currency/currency.ts
- client/packages/common/src/intl/number/IntlNumber.ts
- client/packages/common/src/intl/utils/index.ts
Fixes #3511
The number component change introduced the use of `maximumFractionDigits` : setting the value to `21` which according to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat#maximumfractiondigits) should be in the range 0-20 inclusive.
Have added a const and updated the two usages. Am confused, bc I've done this already, somewhere, but can't remember where or find it now! 
To repro, I had to:
- `yarn build`
- `cargo run`
- `yarn electron:start`
When I ran `electron:start-local` there wasn't a problem 🤷 
> Unable to load Inbound shipments list view

- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/columns.ts
Fixes #3242
Removes dup columns that got put in during conflict and resize some columns to be smaller... with FC the scroll bar still shows up... but everything fits? 😭
> 3242 Outbound shipment line edit modal truncating important column values, over crowded with horizontal scroll

- server/service/src/sync/api/common_records.rs
Fixes #3441
Change the `sync_buffer.record_id` value to be a new uuid for merge records to avoid it overriding upserts of the target records being updated.
- Have a primary server and an OMS remote site initialised
- On the primary create 2 items, sync
- Merge one into the other
- Sync OMS - should integrate records without error and the "kept" item should be shown in item list.
> 3441 ensure sync buffer merge records don't override upserts/delete

- client/packages/coldchain/src/Monitoring/ListView/TemperatureBreach/TemperatureBreachList.tsx
- client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/TemperatureChart.tsx
- client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/TemperatureTooltipLayout.tsx
- client/packages/coldchain/src/Monitoring/ListView/TemperatureLog/TemperatureLogList.tsx
- client/packages/coldchain/src/Sensor/Components/SensorLineForm.tsx
- client/packages/coldchain/src/Sensor/ListView/ListView.tsx
- client/packages/coldchain/src/common/utils.ts
Fixes #3277
The hook `useFormatTemperature` was not following a standard pattern which resulted in the 'more hooks than previous render' error ([310](https://react.dev/errors/310?invariant=310))
Have changed to be a hook function which returns a function, rather than a fn which is called directly.
1. `yarn build`
2. `cargo run`
3. `yarn electron:start` 
and then try to use the temperature chart. I imported a fridge tag to get some data, and then adjusted the date filter so that the chart showed something
> Correct hook implementation

- client/packages/invoices/src/Returns/InboundListView/ListView.tsx
- client/packages/invoices/src/Returns/OutboundListView/ListView.tsx
- client/packages/invoices/src/utils.ts
Fixes #3308
~~Putting this as a "Draft" PR initially, as I'm thinking of consolidating a couple of the "isDisabled" methods in `utils.ts` -- just waiting for clarification~~ Left as is for now.
Implements "disabled" rows in list view for completed returns. Have used the same criteria for disabled as the respective shipments use -- assume this is correct?
Check returns lists -- any past "shipped" should be disabled (i.e greyed out, but still clickable)
The Shipments List views made a separate for `useDisableOutboundRows` etc. I haven't done this, as all it is is a wrapper around `useEffect` -- so I've just used `useEffect` directly in the component. Seems more straightforward to me.
> #3308 Implement disabling of completed returns

- server/service/src/processors/transfer/shipment/update_outbound_shipment_status.rs
Fixes #3525 
Stops the processor from updating status if source shipment is `New` as source shipment should only be `New` if it is being transferred from OG. OMS -> OMS transfers should follow the OMS status sequence.
or
> 3525 Outbound shipment status is automatically switching back to New in case of stock-transfer (to desktop-store)

- server/service/src/invoice/outbound_shipment/update/generate.rs
Fixes #3543
Include service charge amount in the grand total calculation for the outbound shipment.
1. Create a outbound with some line. Better to have line totals
2. More> Add service charges - some values so that `Grand total`>`Line total`
3. Confirm the shipment to Shipped status
4. The grand-total is adjusted to line-total
or
> 3543 Fix outbound shipment not including service charge in total

- client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts
- client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/columns.ts
- client/packages/invoices/src/OutboundShipment/DetailView/columns.ts
- client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/columns.ts
- client/packages/invoices/src/Prescriptions/DetailView/columns.ts
- client/packages/invoices/src/Returns/modals/OutboundReturn/ReturnQuantitiesTable.tsx
- client/packages/system/src/Item/Components/PackVariant/PackVariantCell.tsx
- client/packages/system/src/Stock/ListView/ListView.tsx
Some warning I noticed while working on another issue. Fixes two warning by using the correct naming convention:
React Hook "usePackVariant" cannot be called inside a callback.
A function with a name starting with an uppercase letter should only be
used as a constructor.
> Fix two warnings by renaming getPackVariantCell

- client/packages/coldchain/src/Equipment/ListView/CreateAssetModal.tsx
Fixes #3461
Start open-mSupply in central server mode e.g. `IS_CENTRAL_SERVER=true cargo run`
Open Inventory-> Assets -> New Asset
Check store is at the opt
> Put store at the top of asset creation on central server!

- server/graphql/reports/src/printing.rs
- server/report_builder/src/build.rs
- server/report_builder/src/lib.rs
- server/repository/src/db_diesel/report_query.rs
- server/service/src/report/definition.rs
- server/service/src/report/mod.rs
- server/service/src/report/report_service.rs
- server/service/src/report/string_or_vec.rs
Fixes #3420 
It's now possible to have 0 or 1 GraphGL queries + multiple sql queries. (See issue for the motivation)
Old reports should still work. I also updated the `examples/SQLReport` report in the `open-msupply-reports` repo to give a full example.
> Support multiple SQL report queries

- client/packages/common/src/ui/components/inputs/Autocomplete/Autocomplete.tsx
- client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts
- client/packages/invoices/src/OutboundShipment/DetailView/Toolbar.tsx
- client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/columns.ts
- client/packages/system/src/InventoryAdjustmentReason/Components/InventoryAdjustmentReasonSearchInput.tsx
- client/packages/system/src/Name/Components/CustomerSearchInput/CustomerSearchInput.tsx
- client/packages/system/src/Name/ListView/ListView.tsx
Fixes #3477
Found these while doings docs and was fixing them along the way but though I'll just get this fix in since there's already an issue for it.
This PR fixes some columns/inputs that have changed. Probably a better way to fix this but was just doing this to make the docs screenshot look better >.>
> 'Code' column title is not visible under Replenishment -> Suppliers #3477

- client/packages/common/src/intl/locales/en/inventory.json
- client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts
Part of #3285
Improves the error message and highlight the correct error columns, i.e. "Counted Pack" is not highlighted if there is a SnapshotCountCurrentCountMismatch error.
Please see issue for more details
> Improve/fix SnapshotCountCurrentCountMismatch error

- client/packages/coldchain/src/Equipment/DetailView/Toolbar.tsx
Fixes #3460
What it says on the tin. Was thinking that when the sub-catalogue changes are merged we could add the catalogue to that toolbar area. For now though, this tidies up the issue.
Shouldn't show make/model for non-catalogue assets.
> Hide make/model for non-catalogue assets

- client/README.md
- client/package.json
- client/packages/config/src/config.ts
- client/packages/host/webpack.config.js
- client/packages/inventory/src/Stocktake/DetailView/Toolbar.tsx
- client/packages/system/src/Stock/Components/StockLineEditModal.tsx
- client/packages/system/src/Stock/ListView/AppBarButtons.tsx
Fixes #3604
Adds a feature flag to hide inventory adjustments features for v2.0.0.
- Start with usual `yarn start-local` 
- Start with the below script:
```sh
yarn start-local -- -- --env FEATURE_INVENTORY_ADJUSTMENTS=true
```
- You should now see:
This still feels like the fastest way to a feature flag for now, but if it's something we're going to use more of, the `-- -- --env` feels super clunky. Maybe should set up .env file? Is that worth doing now?
> Add inventory adjustments feature flag for v2.0.0

- server/service/src/sync/translations/store_preference.rs
Fixes #3575 
Fix parsing a pref record. And then decide if the pref record should be integrated or not.
pref entry in the sync_buffer table should look like this now (instead of errors):
> Fix parsing pref records

- server/graphql/types/src/types/temperature_log.rs
- server/repository/src/db_diesel/filter_sort_pagination.rs
- server/repository/src/db_diesel/temperature_breach.rs
- server/repository/src/db_diesel/temperature_breach_config.rs
- server/repository/src/db_diesel/temperature_log.rs
- server/repository/src/db_diesel/temperature_log_row.rs
- server/repository/src/diesel_macros.rs
- server/service/src/sensor/berlinger.rs
- server/service/src/sensor/query.rs
- server/service/src/sensor/update.rs
Fixes #2594
Simplifies https://github.com/msupply-foundation/open-msupply/pull/2629 by:
* Reducing the logic in associating temperature breaches to just check by start and end date time on breach
* Adds test for validating this logic
* Adds filters to help with this task
* Run the tests in repo.
* Try to import: https://github.com/msupply-foundation/temperature-sensor/blob/main/data/FridgeTag%202L/130500109088_202206081014.txt via cold chain/sensor UI. Then you should see that temperature logs are linked to breaches (by temperature and start/end end time of the breach)
cold-chain/monitoring?tab=Breaches&sort=startDatetime&dir=desc&startDatetime=2022-06-04+00%3A59_2022-06-04+23%3A59
cold-chain/monitoring?tab=Log&sort=datetime&dir=desc&datetime=2022-06-04+00%3A01_2022-06-04+23%3A59
Please …
> 2594 link temperature logs to breaches suggestion

- client/packages/requisitions/src/RequestRequisition/ListView/AppBarButtons.tsx
Fixes #3534
Fixes the redirect for Internal Orders upon creation
1.
2.
> Nothing sent to query when creating Internal Order #3534

- client/packages/coldchain/src/Equipment/ListView/CreateAssetModal.tsx
Fixes #3627 
The autocomplete was setting the filter on click, which then reloaded data, resetting the filter.. 
Fixed by testing the reason for the input change.
As per the issue:
* Open the create asset modal
* Click on a catalogue item
> Stop infinite reloading

- client/packages/coldchain/src/Equipment/DetailView/Tabs/Documents.tsx
- client/packages/coldchain/src/Equipment/DetailView/UpdateStatusButton.tsx
- server/Cargo.lock
- server/Cargo.toml
- server/server/Cargo.toml
- server/server/src/authentication.rs
- server/server/src/lib.rs
- server/server/src/print/label.rs
- server/server/src/print/mod.rs
- server/server/src/static_files.rs
- server/server/src/support/mod.rs
- server/server/src/sync_on_central/mod.rs
- server/service/Cargo.toml
- server/service/src/sync/api_v6/mod.rs
- server/service/src/sync/api_v6/upload_file.rs
- server/service/src/sync/file_sync_driver.rs
- server/service/src/sync/file_synchroniser.rs
- server/service/src/sync/sync_on_central/mod.rs
- server/util/Cargo.toml
- server/util/src/file.rs
Fixes #3601
Requests to upload, download files now have improved authentication
For remote_server the endpoints are just checking if the user is logged in or not.
For sync, we're using sync_v5 credentials similar to the other central sync requests.
Bit of local testing which seems ok...
Could/should apply the Logged in Function logic to import fridge tag, and sqlite file downloads.
SQLite download need to retain the permissions check too.
> 3601 authorisation required for sync file endpoints

- client/packages/common/src/ui/components/inputs/TextInput/NumericTextInput.tsx
- client/packages/common/src/ui/components/portals/AppFooter/AppFooter.test.tsx
- client/packages/config/src/config.ts
Fixes #3644 
Allows front-end tests to run.
Also discovered a regression in NumericTextInput which caused its test to fail, which I've fixed.
There is still one test failing -- AppFooter.test.tsx, no idea what's going on here, doesn't look like anything's changed recently, will have to wait for another issue: #3658
Run `yarn test` -- should all pass except for the previously mentioned AppFooter test.
> 3644 Fix Storybook with Feature Flags/Numeric Text fix

- server/service/src/sensor/berlinger.rs
Fixes fridge tag test... we were using seconds in a milliseconds filter 😁
> use milliseconds for temp breach config millisecond filter 😅

- server/service/src/sync/translations/asset_catalogue_item.rs
Fixes flaky test for `test_sync_pull_and_push` not all dependencies (AKA foreign keys) had been included in the Asset Catalogue Item Translations
Run `cargo test` multiple times as this wasn't always failing depending on the order of operations in sync.
1.
2.
> Include all foreign key dependancies in Asset Catalogue Item Translation

- client/packages/common/src/intl/context/IntlContext.tsx
- client/packages/common/src/ui/layout/tables/components/DataRow/DataRow.tsx
- client/packages/common/src/ui/layout/tables/components/index.tsx
- client/packages/host/public/index.html
- client/packages/host/webpack.config.js
- server/server/src/serve_frontend.rs
Fixes #3066
Thought that it would be good to get these improvements in before they're too stale.
* Reduce the DataTable element count
* Add the viewport element
* Implement caching in actix_web
* Implement the translation caching, as per https://github.com/msupply-foundation/health-supply-hub/pull/762
It lifts the lighthouse score, hopefully improves performance too. Now looking at this for the dashboard:
Essentially checking that the site is running correctly. 
1.
2.
> Performance improvements

- client/packages/invoices/src/OutboundShipment/ListView/ListView.tsx
Fixes #3092
Sort outbound shipments by number instead of created date
Do we want this for inbound/prescriptions as well?
1.
2.
> Change Outbound Shipment list default sort from "Created" to "Number"? #3092

- client/packages/requisitions/src/ResponseRequisition/DetailView/AppBarButtons/AppBarButtons.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/Footer/CreateShipmentButton.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/Footer/Footer.tsx
Fixes #2787
Moved the button, and made it blue to be consistent with other footer buttons.
We had a discussion about this one, the resolution that I remember was that we'd move the button.
An additional thought - what about asking the user if they'd like to finalise?
If so, should we default the checkbox to unchecked? or checked?
Currently the behaviour is exactly as it was, with the button shifted.
1. The screenshots of this page need updating
> Move requisition create shipment button

- client/package.json
Fixes #3695
Change to use `yarn start-local` as the default, instead of `yarn start-remote`
Try running `yarn start` and verify that this is hitting your local server, and not the demo server.
> Default to local server

- client/packages/programs/src/JsonForms/components/IdGenerator.tsx
- client/packages/system/src/Patient/CreatePatientModal/CreatePatientModal.tsx
Fixes #3581
Show that code is required for patient and disable buttons if there is no code
1.
2.
> 3581 code required on patient creation but there is no indication

- client/packages/system/src/Patient/Components/PatientSearchModal/PatientSearchModal.tsx
Fixes #3568
Shows search message for patient search modal if search result is 0.
1.
2.
> 3568 Current patient selection modal makes it seem like the store has 0 patients

- client/packages/system/src/Name/DetailModal/DetailModal.tsx
Fixes #3428
Removes breadcrumbs from the detail modal so that suffix is not changed.
I like this more than setting the breadcrumbs in the background:
Current behaviour where breadcrumbs changes:
Proposed behaviour where breadcrumbs is static when opening modal:
> 3428 remove breadcrums from supplier modal

- server/repository/src/db_diesel/assets/asset_catalogue_item.rs
- server/repository/src/db_diesel/assets/asset_catalogue_item_row.rs
- server/repository/src/migrations/v2_00_00/assets/asset_catalogue_item.rs
- server/service/src/catalogue/delete.rs
- server/service/src/catalogue/insert.rs
- server/service/src/sync/test/test_data/asset_catalogue_item.rs
Fixes #3675 
Adds soft delete for asset catalogue items.
The prevents a bug with sync if the catalogue item is deleted centrally but used remotely.
See issue for reproduction steps.
To add the new column to the database, you'll need to run this command...
`ALTER TABLE asset_catalogue_item add column  deleted_datetime TIMESTAMP;`
1. Import a new asset catalogue item (On central server)
2. Sync your remote site
4. Create an asset on the remote site using the new catalogue item
5. Before syncing to central, delete the catalogue item from central
6. Sync to central server
7.  Check that the asset show up in the central server
> Soft Delete for Asset Catalogue Items

- server/service/src/sync/remote_data_synchroniser.rs
Fixes #3692
Advances the v6 push cursor after initialisation. Now # of records to push on first post-initialisation sync is same for v5 and v6:
After initialisation, we were advancing the remote (v5) push cursor, but not the v6 cursor, resulting in lots of records to push to v6 on first post-initialisation sync. 
1.
2.
> advance v6 push cursor after initialisation

- server/repository/src/migrations/v2_00_00/assets/asset_log.rs
- server/repository/src/migrations/v2_00_00/sync_file_reference.rs
Part of #3654
Adds missing pg enums for assets and file sync. This is much easier to add now than to ALTER the table in 2.1.0
Please check enums match the Rust types, i.e. the variants and the Rust type should match the PG type for the Diesel 2.0 update.
> Add missing postgres enums

- client/packages/system/src/Item/DetailView/DetailView.tsx
Fixes #3563
Passes item id to the master list tab in the item page. Might have disappeared during a merge conflict? 
1.
2.
> 3563 Item id isn't being sent to query to display master lists in Item detail view

- client/packages/config/src/config.ts
- client/packages/host/webpack.config.js
- client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts
- client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditForm.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditTable.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/columns.ts
- client/packages/invoices/src/OutboundShipment/DetailView/columns.ts
- client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/PrescriptionLineEditForm.tsx
- client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/columns.ts
- client/packages/invoices/src/Prescriptions/DetailView/columns.ts
- client/packages/invoices/src/Returns/InboundDetailView/columns.ts
- client/packages/invoices/src/Returns/OutboundDetailView/columns.ts
- client/packages/invoices/src/Returns/modals/InboundReturn/ReturnQuantitiesTable.tsx
- client/packages/invoices/src/Returns/modals/OutboundReturn/ReturnQuantitiesTable.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEditForm.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEditForm.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/columns.ts
- client/packages/system/src/Item/DetailView/DetailView.tsx
- client/packages/system/src/Item/context/usePackVariant.ts
- client/packages/system/src/Stock/Components/StockLineForm.tsx
- client/packages/system/src/Stock/ListView/ListView.tsx
- server/service/src/pack_variant/query.rs
Fixes #3684
Adds feature flagging of pack variant features.
As per issue... Pack Variant UI was rushed in the end, we need more time to consider if this is what we want. This PR adds a toggle for pack variant column/UI changes.
Pack variants enabled: 
Disabled:
Also when disabled, brings back the "in packs of" labels in prescription/outbound shipment edit line modal:
And the packs/units toggle in Internal Order modal:
Also comments out the `mostUsePackVariant` logic in the backend, as this was raised as a maybe performance issue (especially as it was running against all items even when no variants were defined..) - seeing as the UI will be hidden for now, have commented out so we don't need to investigate performance at this stage. 
Have added a feature flag, but this only hides the `Pack …
> 3684 pack variant feature flag

- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/hooks/useDraftOutboundLines.tsx
Fixes #3704
Combined stock lines frmo invoice lines with stock lines from item availableStockLines (which filters out totalNumberOfPack == 0) when creating draftLines in OS line edit
1. Create an `Outbound Shipment` 
2. Add invoice line
3. Issue all stock from stock line
4. Change status to `Picked`
5. Go back to invoice line
6. See that stock line has disappeared
Also it's good to check that no duplicate lines appear in OS line edit. Issue some stock in new status and refresh page
> 3704-Fix-fully-issued-lines-dissapearing-in-outbound-shipment

- client/packages/system/src/ContactTrace/DetailView/Footer.tsx
Fixes #3584 
Use onClick callback correctly. Bit tricky one because this is not obvious.
From commit message:
```
onClick has an event parameter, this parameter got silently passed
forward to the onSave method which interpreted it as a boolean.
```
Maybe a good practice it s to not pass "function pointers" around but always create a new arrow method and call the target manually? @mark-prins
> Fix onClick callback handling

- client/packages/dashboard/src/widgets/StockWidget.tsx
Fixes #3757
Pass correct requisition number when creating IO from dashboard
1.
2.
> 3757 Open mSupply hangs when you order form Dashboard

- client/packages/common/src/ui/components/inputs/TextInput/NumericTextInput.test.tsx
- client/packages/common/src/ui/components/inputs/TextInput/NumericTextInput.tsx
- client/packages/host/src/Admin/LabelPrinterSettings.tsx
- client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/PrescriptionLineEditForm.tsx
Fixes #3536
Fixed issue. Allowed quantity to be erased, but it still resets to `0` rather than empty, as it causes problems to pass `undefined` to the `allocate` method.
Also... found *another* regression with the numeric input component, which I've fixed. I've also added some more tests for this so we don't keep getting these regressions.
See inline comments
- Run `yarn test numeric` and confirm all tests pass
- If you feel like it, run `yarn storybook`, go to the Numeric inputs and check they still behave as expected
> #3536 Prescription input quantity fix

- client/packages/invoices/src/Returns/modals/InboundReturn/AddBatch.tsx
- client/packages/invoices/src/Returns/modals/InboundReturn/ReturnSteps.tsx
Fixes #3730 
Disables the add batch button on the reason step for Inbound Returns:
You can't add new batches from the return step (batches with return quantity == 0 are filtered out, which any added batches would have!)
Users need to go back to the `Select quantity` step to add new batches.
1. Update screenshot for return reason step
> 3730 disable add batch button on inbound return reason step

- client/packages/common/src/ui/components/inputs/TextInput/BasicTextInput.tsx
- client/packages/common/src/ui/components/inputs/TextInput/NumericTextInput.tsx
Fixes #3538
Sets the `inputmode` for the NumericTextInput the `numeric`, so the number pad opens on tablet, rather than alphanumeric keyboard:
Should fix for all number inputs...
1.
2.
> 3538 number pad for number inputs

- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEditForm.tsx
Fixes #3393
Conditionally render requested quantity inputs on internal order, only once item has been set. Item picker now maintains focus, with correct keyboard:
Stacked on #3763 to make it slightly easier to validate (enables number pad for numeric quantity inputs)
1.
2.
> only render quantity inputs after item is set

- client/packages/coldchain/src/Equipment/ListView/Toolbar.tsx
- client/packages/coldchain/src/Equipment/api/hooks/document/useAssets.ts
- client/packages/common/src/intl/locales/en/coldchain.json
Fixes #3743 
The API filter has changed from `code` to `assetNumber`. This PR adjusts the front end.
Note, I wasn't able to repro the bug as raised.
1.
2.
> Add asset number to equipment filter

- client/README.md
- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/ui/components/errors/GenericErrorFallback.tsx
Fixes #3515 
Adds link to navigate back to home from error
I was a bit dissatisfied with working through how to test this because a lot of errors thrown will not be caught by our error handler. 
A future issue could be more comprehensive error catching with this provider.
@Roxy I wonder how you were able to trigger the error in this way? 
Regardless this will allow users to navigate back to home where their current url triggers the error for whatever reason.
> Add home button to error boundary

- client/packages/coldchain/src/Equipment/DetailView/Tabs/Summary.tsx
Fixes #3758
Two fixes in here:
* Filter out duplicates of the location ids before saving the draft
* Removed duplicates from the available options
One outstanding issue, which I won't fix here.
If you assign a location, save the asset; then remove the location and save; the location is no longer available to be selected from the list. Refreshing the page will repopulate the list and allow the location to be added again.
The issue here is that the Autocomplete component is managing its value internally and not updating as expected when removing. 
1.
2.
> prevent duplicates

- client/packages/coldchain/src/Equipment/ListView/ListView.tsx
- client/packages/common/src/ui/components/inputs/DatePickers/DateTimePickerInput/DateTimePickerInput.tsx
Fixes #3744
Add the installation date column. 
As a side bonus, fixes the `DateTimePickerInput` which was not allowing manual entry of date strings
1.
2.
> add installation date column

- client/packages/system/src/Stock/Components/StockLineForm.tsx
Fixes #2931
Change the expiry and barcode inputs to use a buffered input, and assign the value from the draft directly.
This version has come from @roxy-dao's [comment](https://github.com/msupply-foundation/open-msupply/pull/3756#issuecomment-2097151642) - I rebased and that didn't go well, so have had to create a new branch and cherry pick instead.
1.
2.
> Update stock line on scan

- client/packages/coldchain/src/Equipment/ListView/CreateAssetModal.tsx
- client/packages/dashboard/src/api/api.ts
Fixes #3740 
Handle two causes of a crash: 
* When using an infinite query, undefined is returned for one or more of the pages
* The `stockCounts` query returns null or undefined
This is almost impossible to replicate - to cause the issue I've updated `useInfiniteAssets` in order to return an invalid result within the array:
```
const result = useInfiniteQuery(api.keys.paramList(params), ({ pageParam }) =>
api.get.list({ ...params, ...pagination, ...pageParam })
);
return { ...result, data: { ...result.data, pages: [undefined] } };
```
Simply deleting the auth cookie or invalidating the query in some way ( incorrect filter, for example ) is not enough! That will return null for the `data` prop and won't return invalid pages.
1.
2.
> Handle app crash

- client/packages/system/src/InventoryAdjustmentReason/Components/InventoryAdjustmentReasonSearchInput.tsx
Fixes #3567
Only show the `required` asterisk if the reason is actually required (because counted packs is different):
1.
2.
> Hide required asterisk when inv adj reason is disabled

- client/packages/host/src/components/Navigation/ColdChainNav.tsx
- client/packages/host/src/components/Navigation/DispensaryNav.tsx
Fixes #3667
Use correct condition to to show if the dispensary or cold chain navs have been opened
1. Maybe the GOTO part of coldchain and dispensary needs updating? 🤷🏻 
2. Other GOTOs that show coldchain and dispensary?
> Use correct condition for app nav's activeness

- client/packages/requisitions/src/RequestRequisition/DetailView/Toolbar/Toolbar.tsx
Fixes #3801
Forces height on grid so that the filter and actions align 👀 
1. Maybe screenshots if they're misaligned
2.
> 3801 Internal Order Page has misaligned "Filter Items" searchbox and "Actions" drop down

- server/repository/src/migrations/v2_00_00/assets/asset.rs
Fixes #3800
This removes the unique constraint on asset number
See issue description to explain why this is needed.
In future, we should probably ensure we don't have unique constraints on non-id fields, as SQLite upsert logic is triggered on any unique constraint, no just on the id field. Especially with sync we need to be careful as duplicated records can come from different sites and might not go through service layer upsert logic.
To test this you'll need to either re-initialise OMS Central server as this is a database change...
> 3800 sync assets fails with duplicate asset numbers

- client/packages/system/src/Asset/AssetLogReasons/ListView.tsx
Fixes #3760
Swap Reason <-> Status in log reasons
1. Screenshots for asset reasons
2.
> 3760 Catalogue -> Assets -> Log Reasons -> swap Reason and Status around

- client/packages/common/src/ui/forms/Detail/InputWithLabelRow.tsx
- client/packages/system/src/Name/DetailModal/DetailModal.tsx
Fixes #3426
Make the supplier name website look like another, disabled text input
I tried to make it same with and height and same look as the other text inputs.
There are three cases to consider:
- no website
- short website
- long website
> Make the supplier name website look like another, disabled text input

- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditForm.tsx
- client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/PrescriptionLineEditForm.tsx
- client/packages/invoices/src/StockOut/utils.tsx
Fixes #3736
Prevents the auto allocation from triggering when the `issue quantity` input field loses focus:
https://github.com/msupply-foundation/open-msupply/assets/55115239/a4bb2112-5171-4f66-949b-366bba05f5b4
NumericTextInput component calls the handleIssueQuantityChange on blur, which was triggering auto allocation even though we've not actually changed the value.
- Also fixes for prescriptions, as same bug was there
Somewhat curious for thoughts on whether this could/should be the NumericTextInput's responsibility, to only call the onChange handler from `onBlur` if there actually is a change? 🤷‍♀️ If I were passing an onChange handler to a component, I wouldn't expect it to fire on blur in the first place, but if it does, I would expect it to be because the change in focus has …
> 3736 bug: OS issue expired line value disappears on click

- client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEdit.tsx
Fixes #3540 
Adds the `useKeyboardHeightAdjustment` hook to Response Requisition modal, so the modal height adjusts when the keyboard opens:
1.
2.
> add useKeyboardHeightAdjustment to response line edit modal

- server/service/src/location/tests/query.rs
Fixes broken asset test
Makes sure the tests use an asset associated with a store when assigning a store location.
This is my bad, obviously didn't run tests after PR https://github.com/msupply-foundation/open-msupply/pull/3807
> Fix asset test

- client/packages/common/src/hooks/useDrawer/useDrawer.ts
Fixes #3442
Collapse non-active nav sections when clicked a second time:
https://github.com/msupply-foundation/open-msupply/assets/55115239/e06a8eba-f19d-41a7-936a-f4bf4f25d6ed
1.
2.
> 3442 collapse drawers on secondary click

- client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NumberInputCell.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEdit.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/hooks/useDraftOutboundLines.tsx
- client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/PrescriptionLineEdit.tsx
- client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/PrescriptionLineEditForm.tsx
Fixes #3532
- Resets issue quantity to 0 if you change items for Prescription/OS (and clears any warnings)
- Prevents allocation warnings from clearing until you make a change to an issue packs quantity
- Adds debouncing to prescription issue quantity input (immediate auto allocation prevented being able to clear it!)
Stacked on #3814, because #3736 reallocation issue was also mentioned in this issue. But now have realised that maybe I should rebase off develop, seeing this issue was actually slated for 2.1.0... thoughts?
Resets issue quantity to 0 if you change items for Prescription/OS (and clears any warnings)
Prevents allocation warnings from clearing until you make a change to an issue packs quantity
Adds debouncing to prescription issue quantity input (immediate auto allocation …
> 3532 issue stock not clearing values

- client/packages/common/src/ui/components/navigation/Tabs/DetailTab.tsx
- client/packages/common/src/ui/layout/tables/DataTable.tsx
- client/packages/inventory/src/Stocktake/DetailView/ContentArea/ContentArea.tsx
Fixes #3579
Literally a 1 line fix -- but took a while to figure it out 🙄
(This might be my smallest PR yet!)
Load a table that has more than 1 page of content and is wider than the available viewport.
Scroll to the side, confirm that the Pagination bar stays in place and doesn't scroll with it.
> # 3579 Fix Pagination bar side-scrolling

- client/packages/coldchain/src/Equipment/ImportAsset/EquipmentImportModal.tsx
- client/packages/coldchain/src/Equipment/ImportAsset/ImportReviewDataTable.tsx
- client/packages/coldchain/src/Equipment/ImportAsset/ReviewTab.tsx
- client/packages/coldchain/src/Equipment/ImportAsset/UploadTab.tsx
- client/packages/common/src/intl/locales/en/coldchain.json
- client/packages/common/src/intl/locales/en/common.json
Fixes #3742 
Adds warnings for fields where they fail to parse
Adds a warning column for cold chain equipment input for values which failed to parse but won't block the import
This is for non essential fields to flag to the user when they failed to parse.
I've also made this column optional only to only appear when there are no errors so as to not clog up the review table space.
Currently only installation date will flag warnings if it fails to parse.
Other text fields won't receive this warning because they don't require formatting.
Open open mSupply with vaccine module
Try importing some cold chain equipment where the date field is not a date such as this file:
[equipment upload template_2024-04-16 (1).csv](https://github.com/msupply-foundation/open-msupply/files/15257060/equipment.uploa …
> Add warnings for fields for fields if they fail to parse

- server/server/src/print/label.rs
- server/service/src/print/jetdirect.rs
Fixes #3849
Two issues with the printer response:
* The printer was timing out on the initial telnet connection
* There is now an additional linebreak at the end of the response i.e. 
```
"\u{2}030,0,0,0290,000,0,0,0,000,0,0,0\u{3}\r\n\u{2}001,0,0,0,1,2,4,0,00000000,1,000\u{3}\r\n\u{2}1234,0\u{3}\r\n"
```
the validation was checking for exactly 3 lines of response. I've changed that to fail if less than 3.
Increased the timeout from 500ms to 1s
1.
2.
> Fix the zebra tester 🦓 ✅ 

- client/packages/common/src/ui/components/buttons/FlatButton/FlatButton.tsx
- client/packages/common/src/ui/components/popover/ClickPopover/ClickPopover.tsx
- client/packages/common/src/ui/components/popover/PaperPopover/PaperClickPopover/PaperClickPopover.tsx
- client/packages/host/src/components/Footer/LanguageSelector.tsx
- client/packages/host/src/components/Login/Login.tsx
Fixes #3751 
Adds selectors for username & password on login and the language menu and language buttons.
You can test by cloning [this repo](https://github.com/mark-prins/open-msupply-screenshot) and running `yarn shoot` which will try to log you in and take some screenshots.
Commenting out the line 
```
.setChromeOptions(options.addArguments('--headless=new'))
```
which is in `index.js` will allow chrome to run interactive, so that you can see what's going on.
1.
2.
> Add component selectors

- client/packages/common/src/intl/locales/en/replenishment.json
- client/packages/requisitions/src/RequestRequisition/DetailView/Footer/StatusChangeButton.tsx
Fixes #3527
Don't allow users to send Internal Orders if there are only placeholder lines or if there are no lines
1.
2.
> 3527 You can confirm outbound shipments with only placeholder lines

- client/packages/coldchain/src/Equipment/ListView/CreateAssetModal.tsx
Fixes #3858
Show correct error if asset number already exists
1.
2.
> 3858 CCEI module: No details in error message when creating CCE with duplicate asset numbers

- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/ui/layout/tables/columns/CheckboxSelectionColumn.tsx
- client/packages/common/src/ui/layout/tables/components/Cells/TooltipTextCell/TooltipTextCell.tsx
- client/packages/common/src/ui/layout/tables/components/Header/Header.tsx
- client/packages/common/src/ui/layout/tables/components/tooltipPlacement.ts
Fixes #3853 
Add a tooltip to avoid an empty tooltip to show up.
First I checked if we have data for a tool tip and if not set it to `null` (`packages/common/src/ui/layout/tables/components/Header/Header.tsx`)
However, thought having a tooltip is good solution as well...
- Go to a table and hover over the selection header checkbox
- Tooltip should show
> Add tooltip to the select/unselect all column header

- server/service/src/invoice/inbound_return/update/generate.rs
- server/service/src/invoice/inbound_return/update/mod.rs
Fixes #3877
Introduces stock when an inbound return status is updated from `New`/`Picked`/`Shipped`, straight to `Verified`.
(It was only being introduced when changed to Delivered!)
1.
2.
> 3877 introduce stock when set straight to verified

- client/packages/invoices/src/InboundShipment/DetailView/Footer/OnHoldButton.tsx
- client/packages/invoices/src/InboundShipment/api/hooks/index.ts
- client/packages/invoices/src/InboundShipment/api/hooks/utils/index.ts
- client/packages/invoices/src/InboundShipment/api/hooks/utils/useIsInboundHoldable.ts
- client/packages/invoices/src/utils.ts
Fixes #3526 (at least partially, still not taken store pref into account, please see my question in the issue)
The incoming invoice with status Shipped can now be put on hold. However, @mark-prins should it always be possible to put it on hold if it is not Verified?
> Enable hold button for "Shipped" invoices

- client/packages/common/src/ui/components/inputs/TextInput/NumericTextInput.tsx
- client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEditForm.tsx
- client/packages/system/src/Item/Components/PackVariant/PackVariantEntryCell.tsx
Fixes #3834
Updates:
- Internal order requested quantity to allow for 0 quantity input
- Updates pack size input (PackVariantEntryCell) for Inbound Shipment and Inbound Return, to allow clearing the value while typing, and then reset to the min value (e.g. 1) on blur
- Allows pack quantity field to be set to 0 in inbound shipments (you can't save the modal, but at least you can clear the input in order to change e.g. 1 to 2!)
1.
2.
> 3834 clear number inputs to 0

- client/packages/coldchain/src/Equipment/DetailView/Tabs/StatusLogs.tsx
- client/packages/inventory/src/Stocktake/DetailView/SidePanel.tsx
- client/packages/invoices/src/InboundShipment/DetailView/SidePanel/AdditionalInfoSection.tsx
- client/packages/invoices/src/InboundShipment/DetailView/SidePanel/RelatedDocumentsSection.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/SidePanel/AdditionalInfoSection.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/SidePanel/RelatedDocumentsSection.tsx
- client/packages/invoices/src/Prescriptions/DetailView/SidePanel/AdditionalInfoSection.tsx
- client/packages/invoices/src/Returns/InboundDetailView/SidePanel/AdditionalInfoSection.tsx
- client/packages/invoices/src/Returns/InboundDetailView/SidePanel/RelatedDocumentsSection.tsx
- client/packages/invoices/src/Returns/OutboundDetailView/SidePanel/AdditionalInfoSection.tsx
- client/packages/invoices/src/Returns/OutboundDetailView/SidePanel/RelatedDocumentsSection.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/SidePanel.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/AdditionalInfoSection.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/RelatedDocumentsSection.tsx
- client/packages/system/src/Encounter/DetailView/SidePanel.tsx
Fixes #3895
Users can be unknown if they are new users since they don't get synced back to Open mSupply. It is also possible to migrate existing data with no user_ID saved in the table. 
This PR shows a dash if the username is unknown. This has been made consistent throughout the app 
1. Maybe the side panel screenshots if they show unknown user
2.
> 3895 Username no longer being displayed in sidepanels

- client/packages/coldchain/src/Equipment/DetailView/Tabs/Summary.tsx
Fixes #3674
Since all locations aren't available on Central Server, we hid the Location section of the Assets on central server, unless they relate to the currently logged in store.
Central Server - Logged in Store
Central Server - Other store
> 3674 assets locations dont show on central server

- server/repository/src/migrations/v2_00_00/assets/asset_log.rs
Fixes #3739 
Removes foreign key from `asset_log` to `user_account` so if a user isn't available on central OMS it doesn't prevent sync from happening.
Roxy's PR https://github.com/msupply-foundation/open-msupply/pull/3431 to sync user information could potentially solve this? But doesn't appear to be working for me.
This PR msupply suggests that changes to user account might not trigger sync?
https://github.com/msupply-foundation/msupply/pull/14538
> 3739 remove foreign key for user

- server/service/src/sync/settings.rs
> NOTE: should only be merged once mSupply PR https://github.com/msupply-foundation/msupply/pull/14649 is merged, or sync will break...
Adding required field item_name is a breaking change for the sync API. We should therefore bump sync version to ensure compatibility with mSupply central. 
1.
2.
> bump sync version (after item_name addition)

- client/packages/invoices/src/OutboundShipment/DetailView/columns.ts
- client/packages/invoices/src/Prescriptions/DetailView/columns.ts
- client/packages/requisitions/src/RequestRequisition/ListView/ListView.tsx
- server/service/src/sync/translations/invoice.rs
Fixes #3893
Correctly map repack status and confirmed datetime. Nw and sg repacks should be handled by OG
1.
2.
> 3893 correctly map repack times and status

- server/repository/src/mock/invoice.rs
- server/service/src/invoice/inbound_return/update/generate.rs
- server/service/src/invoice/inbound_shipment/update/generate.rs
- server/service/src/invoice/inbound_shipment/update/mod.rs
Fixes #3829
Issue was that the delivered_datetime was being overwritten on Delivered -> Verified.
- Uses `match` statement rather than status index to determine whether to update delivered/verified datetime.
- This makes the status change logic more readable, and prevents the delivered_datetime being updated when setting to `Verified`
I've seen both in different places... should `delivered_datetime` be set if we go straight from `New` to `Verified`?
If not, we need to update the ledger query to handle this possibility! Currently we get no ledger line if we go straight to verified 👀 
Or can check by going to the inbound shipment detail view, look in dev tools at the `inboundByNumber` query, check the timestamps on the inbound shipment: 
1.
2.
> 3829 inbound delivery date updated when verified

- client/packages/common/src/utils/numbers/NumUtils.test.ts
- client/packages/common/src/utils/numbers/NumUtils.ts
- client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts
- client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/columns.ts
- client/packages/invoices/src/OutboundShipment/DetailView/columns.ts
- client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/columns.ts
- client/packages/invoices/src/Prescriptions/DetailView/columns.ts
- client/packages/invoices/src/Returns/InboundDetailView/columns.ts
- client/packages/invoices/src/Returns/OutboundDetailView/columns.ts
- client/packages/system/src/Stock/ListView/ListView.tsx
Fixes #3705
Avoids some visual problems with pack_size being a float. For example, 110.4 * 29 = 3201.6000000000004 is displayed as 3201.6 now.
I didn't make the pack_size editable as a float though. Or do you think we should do it now?
Please have a look for other `pack_size: float` related issues in the UI that I might have missed.
To create a decimal pack size, create a stocktake in OG mSupply an edit an item to have decimal pack size. This stock line can then be sent to the omSupply site.
> Avoid float precision problems when multiplying pack sizes

- .github/ISSUE_TEMPLATE/bug_report.md
Adds new `needs daily triage` label to bug report issue template.
This allows the release management team to know which newly reported bugs need to be triaged each day. Especially if this responsibility is shared, will help to stop people doubling up on work.
Any hotfix bugs (and high severity?) can then be assigned immediately, while others can wait for usual weekly triage.
1.
2.
> add needs daily triage label to bug report issues

- client/packages/common/src/intl/locales/en/app.json
- client/packages/common/src/intl/locales/ru/app.json
- client/packages/host/src/components/AppDrawer/AppDrawer.tsx
Fixes #3941
Removes the label on the `AppDrawerIcon`
1. Central server images
> Remove label

- server/repository/src/migrations/v2_00_00/mod.rs
Fixes #3914
- Makes sure the code that updates `requisition_line.item_name` and `stock_take_line.item_name` does not resync all lines accidentally.
I added tests for temperature logs too, it appears in 1.7 -> 2.0 they are not touched/resynced.
> 3914 prevent resyncing line records

- client/packages/invoices/src/InboundShipment/api/api.ts
- client/packages/invoices/src/OutboundShipment/api/api.ts
Fixes #3949
Correctly map tax -> taxPercentage so you can add a service line with a tax percentage set 😅 
1.
2.
> 3949 fix taxPercentage mapping for service charges

- client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NumberInputCell.tsx
- client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
- client/packages/invoices/src/Returns/modals/InboundReturn/ReturnQuantitiesTable.tsx
- client/packages/invoices/src/Returns/modals/OutboundReturn/ReturnQuantitiesTable.tsx
- client/packages/invoices/src/StockOut/utils.tsx
Fixes #3950
Backspace to 0 now works for tax input in the two service charge modals:
https://github.com/msupply-foundation/open-msupply/assets/55115239/f383cdfa-28c2-419d-8b76-ebfd5023ff17
Removes the default min=1 on the NumberInputCell, because everywhere except the service charge tax cells, we were explicitly setting min=0, and we actually don't want a min of 1 for service charge tax either 😅 
1.
2.
> make min=0 the default for number input cell

- client/packages/coldchain/src/Equipment/DetailView/Tabs/Summary.tsx
- client/packages/common/src/intl/locales/en/app.json
- client/packages/common/src/types/schema.ts
- client/packages/system/src/Sync/api/api.ts
- server/graphql/general/src/sync_api_error.rs
- server/repository/src/db_diesel/sync_log_row.rs
- server/repository/src/migrations/v2_01_00/mod.rs
- server/repository/src/migrations/v2_01_00/v6_sync_api_error_code.rs
- server/service/src/sync/README.md
- server/service/src/sync/api/core.rs
- server/service/src/sync/api_v6/core.rs
- server/service/src/sync/api_v6/download_file.rs
- server/service/src/sync/api_v6/mod.rs
- server/service/src/sync/api_v6/upload_file.rs
- server/service/src/sync/central_data_synchroniser_v6.rs
- server/service/src/sync/file_synchroniser.rs
- server/service/src/sync/settings.rs
- server/service/src/sync/site_info.rs
- server/service/src/sync/sync_on_central/mod.rs
- server/service/src/sync/sync_status/logger.rs
- server/service/src/sync/synchroniser.rs
Fixes #3111
Adds version check for V6 sync API:
Also will create a PR in the docs repo for the new version matrix!
1. Version matrix
2.
> 3111 oms central sync versioning

- client/packages/common/src/ui/layout/tables/components/Cells/CurrencyInputCell/CurrencyInputCell.tsx
Fix #3968
Fix the pricing display for zero-stock items in Stocktake batch pricing tab
A simple one-liner. The `CurrencyInput` can't handle a `null` value, so have just added a fallback to `0`.
No point going much further with this for now, would like to re-factor Currency input properly at some point: #3959 
- Start a new stocktake from a master list (all items probably)
- Find a stock line that has a "Snapshot Packs" value of 0
- Open it, go to pricing tab
- Should display `$0.00` for both prices
> #3968 Stocktake pricing fix

- client/packages/common/src/ui/layout/tables/components/Cells/CurrencyCell.tsx
Fixes #3981
Similar to #3975 (fixes $NaN in currency inputs) this fixes currency display cell:
1.
2.
> 3981 fix $NaN currency display for outbound shipment placeholder lines

- client/packages/coldchain/src/Equipment/DetailView/Tabs/Summary.tsx
- client/packages/common/src/types/schema.ts
- client/packages/system/src/Name/Components/DonorSearchInput/DonorSearchInput.tsx
- client/packages/system/src/Name/Components/DonorSearchInput/index.ts
- client/packages/system/src/Name/Components/index.ts
- client/packages/system/src/Name/api/api.ts
- client/packages/system/src/Name/api/hooks/document/index.ts
- client/packages/system/src/Name/api/hooks/document/useDonors.ts
- client/packages/system/src/Name/api/hooks/index.ts
- client/packages/system/src/Name/api/hooks/utils/useNameApi.ts
- client/packages/system/src/Name/utils.ts
- server/graphql/general/src/queries/names.rs
- server/graphql/general/src/queries/tests/names.rs
- server/repository/src/db_diesel/name.rs
Fixes #3948
Adds a Donor selection for each asset, stored as a nameId against the record.
(See issue if you need help setting up donors in mSupply)
> 3948 asset donor field name lookup

- client/.eslintrc.js
- client/tsconfig.json
Fixes `../../tsconfig.json(31,5): error TS5023: Unknown compiler option 'prefer-const’`
It looks like this should have been an eslint rule not a compiler option?
Does this still achieve the original goal?
DEV ONLY (no docs or testing required)
> Move prefer const to eslintrc

- server/graphql/general/src/queries/tests/names.rs
Fixes
```
error[E0027]: pattern does not mention field `code_or_name`
--> graphql/general/src/queries/tests/names.rs:170:17
|
170 |               let NameFilter {
|  _________________^
171 | |                 id,
172 | |                 name,
173 | |                 code,
...   |
187 | |                 is_donor,
188 | |             } = filter.unwrap();
| |_____________^ missing field `code_or_name`
|
```
Fixes a test case
DEV ONLY no testing required
> Fix graphql_get_names test

- client/packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.ts
- server/graphql/general/src/queries/tests/names.rs
- server/service/src/sync/test/test_data/master_list_line.rs
- server/service/src/sync/translations/master_list_line.rs
Fixes #4013
Ignore orphaned master list lines
1.
2.
> 4013 Ignore orphaned master list lines

- client/packages/config/src/config.ts
- client/packages/host/src/components/AppDrawer/AppDrawer.tsx
- client/packages/host/webpack.config.js
Adds feature flag to hide GAPS `Manage` section/pages on central server.
Most other GAPS work is either pretty integrated into existing assets stuff (and probably fine to be there for a test build) or in a feature branch at this point.
This is just to hide in progress work from a test build for Inventory Adjustments, when time comes for RC build the feature toggle may be more fine grained!
1.
2.
> gaps feature flag

- server/repository/src/db_diesel/name.rs
- server/service/src/name.rs
Fixes #4014
Filters all patients out for names by default since there's a separate endpoint to get patients
1.
2.
> 4014 You can query patient data without View Patients permission (via name query)

- client/packages/common/src/authentication/AuthContext.tsx
Fixes #3823
Don't swap to default store when syncing.
1.
2.
> 3823 Syncing user causes store to swap to default store

- client/packages/common/src/intl/context/IntlContext.tsx
Fixes #3995
Default the language version to appVersion if LANG_VERSION not available
Honestly maybe just using app version would be fine?? Looks like this was introduced by @mark-prins, maybe you have thoughts?
This felt like the quickest way to get something going...
1.
2.
> default lang version to app version if not defined

- client/packages/common/src/hooks/useNativeClient/useNativeClient.ts
Fixes #4048 
Swallows KeepAwake errors if they arise, so initialisation screen can finish loading.
On initial load, KeepAwake was throwing a "not available" error, and so from the initialise hook, setIsInitialising(false) was never being called.
The form is disabled until isInitialising is set to false, so the form was never being enabled.
Seeing as the KeepAwake piece is helpful, but not critical to any workflow, I think the best solution is just to swallow the error and move on.
You can now type as expected:
TBH I have no idea why keep awake is not available on initial load. It's available after refresh (i.e. I refreshed with dev tools, then everything worked fine), but you can't just refresh easily in android app.
It's working fine in main/2.0?? Wonder if there was a dependency upgrade …
> swallow keep awake errors

- client/packages/common/package.json
- client/packages/common/src/utils/functions/FnUtils.ts
- client/yarn.lock
- server/Cargo.lock
- server/util/Cargo.toml
- server/util/src/uuid.rs
Using uuid v7 improves write and improves read performance for sequential reads.
Fixes #4038
> Use uuid v7 instead of v4

- client/packages/coldchain/src/Equipment/DetailView/DetailView.tsx
- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/intl/locales/fr/common.json
Fixes #4045
Change translation to Status History. Thought it would be nice to get in before users start asking why the tab changed XD
1. Any screenshot that shows the status log in equipment page
2.
> Change translation from status log to status history
