msupply-foundation/open-msupply

- server/graphql/document/src/queries/patient.rs
- server/repository/src/db_diesel/document.rs
- server/repository/src/db_diesel/name.rs
- server/service/src/document/patient/patient_document_update.rs
- server/service/src/document/patient/query.rs
> Patient query fix

- server/cli/src/refresh_dates.rs
- server/repository/src/db_diesel/document.rs
- server/repository/src/db_diesel/json_schema.rs
Fixes #114 
Just updated the types 😉
> Postgres compilation

- client/packages/common/src/authentication/AuthContext.tsx
- client/packages/common/src/intl/locales/en/app.json
- client/packages/host/src/components/AuthenticationAlert.tsx
> #109 Separate errors for Timeout and Unauthenticated

- server/README.md
- server/repository/src/database_settings.rs
- server/repository/src/test_db.rs
- server/server/src/lib.rs
Closes #128 
Moved sqlite Write Ahead Log to run on server startup
> Change sqlite WAL Pragma execution to server_start init_sql

- server/android/src/android.rs
- server/cli/src/cli.rs
- server/graphql/core/src/test_helpers.rs
- server/graphql/general/src/queries/login.rs
- server/graphql/general/src/queries/logout.rs
- server/graphql/general/src/queries/refresh_token.rs
- server/repository/migrations/postgres/2022-02-11T15-00_create_key_value_store/up.sql
- server/repository/src/database_settings.rs
- server/repository/src/db_diesel/key_value_store.rs
- server/server/src/certs.rs
- server/server/src/configuration.rs
- server/server/src/lib.rs
- server/server/src/main.rs
- server/service/src/auth.rs
- server/service/src/auth_data.rs
- server/service/src/login.rs
- server/service/src/token.rs
> 140 users shouldnt be logged out on a server restart in development mode

- server/server/src/discovery.rs
> Fix merge fail

- server/service/src/auth.rs
Closes #189 
Added Tests for the PermissionDSL.
The PermissionsDSL allows you to specific combinations of permissions such as `PermissionDSL::Any(Permission::A,Permission::B)` which should mean either Permission::A or Permission::B should satisfy the permissions check.
Previously this was being evaluated incorrectly.
> Bug fix and tests for any() Permission Evaluation

- server/graphql/core/src/loader/document.rs
- server/graphql/core/src/loader/document_registry.rs
- server/graphql/core/src/loader/loader_registry.rs
- server/graphql/document/src/lib.rs
- server/graphql/document/src/mutations/patient/insert.rs
- server/graphql/document/src/mutations/patient/update.rs
- server/graphql/document/src/queries/document.rs
- server/graphql/document/src/queries/patient.rs
- server/graphql/document/src/types/document.rs
- server/graphql/document/src/types/encounter.rs
- server/graphql/document/src/types/mod.rs
- server/graphql/document/src/types/program.rs
- server/repository/src/db_diesel/document.rs
- server/repository/src/db_diesel/filter_sort_pagination.rs
- server/repository/src/diesel_macros.rs
- server/service/src/document/document_registry/mod.rs
- server/service/src/document/patient/mod.rs
- server/service/src/document/patient/query.rs
- server/service/src/document/patient/update.rs
- Adds StringFilter (currently needed for starts_width queries, not needed if using a separate patient -> doc table)
- Add document_registry node to the DocumentNode, e.g. to get the ui schema for the given document
- Add patients -> programs -> encounter nodes to the PatientNode
- Add single patient endpoint
Closes #136
> 136 patients endpoint

- server/graphql/document/src/queries/patient.rs
- server/service/src/document/patient/mod.rs
- server/service/src/document/patient/patient_document_update.rs
- server/service/src/document/patient/query.rs
- server/service/src/document/patient/update.rs
> Fix patients total count

- server/graphql/document/src/mutations/patient/insert.rs
- server/graphql/document/src/mutations/patient/update.rs
- server/repository/src/mock/form_schema.rs
- server/repository/src/mock/mod.rs
- server/server/src/sync/init_programs_data.rs
- server/server/src/sync/mod.rs
- server/server/src/sync/synchroniser.rs
- server/service/src/document/document_service.rs
- server/service/src/document/patient/update.rs
Add some default program schemas, document_registry entries and patients
Closes #171
> 171 default program data

- client/package.json
- client/packages/common/src/intl/locales/en/app.json
- client/packages/host/src/components/Footer/Footer.tsx
Fixes #223 
That was too simple.. so I've added a tooltip as well 🤷
> Show store name

- server/graphql/document/src/lib.rs
- server/graphql/document/src/queries/mod.rs
- server/graphql/document/src/queries/patient_search.rs
- server/service/src/document/patient/mod.rs
- server/service/src/document/patient/search.rs
> Add basic patient search API (exact match only)

- client/packages/common/src/types/schema.ts
- client/packages/common/src/ui/forms/JsonForms/api/hooks/document/useDocument.ts
- client/packages/common/src/ui/forms/JsonForms/api/hooks/utils/index.ts
- client/packages/common/src/ui/forms/JsonForms/api/hooks/utils/useDocumentApi.ts
- client/packages/common/src/ui/forms/JsonForms/api/operations.generated.ts
- client/packages/common/src/ui/forms/JsonForms/api/operations.graphql
- client/packages/common/src/ui/forms/JsonForms/useJsonForms.tsx
- client/packages/system/src/Patient/DetailView/DetailView.tsx
- client/packages/system/src/Patient/api/api.ts
- client/packages/system/src/Patient/api/hooks/document/index.ts
- client/packages/system/src/Patient/api/hooks/document/useInsertPatient.ts
- client/packages/system/src/Patient/api/hooks/document/useUpdatePatient.ts
- client/packages/system/src/Patient/api/hooks/index.ts
- client/packages/system/src/Patient/api/hooks/utils/usePatientApi.ts
- client/packages/system/src/Patient/api/operations.generated.ts
- client/packages/system/src/Patient/api/operations.graphql
- server/graphql/document/src/types/document_registry.rs
- server/service/src/document/patient/patient_document_update.rs
> 151 save patient changes

- client/packages/common/src/ui/components/inputs/TextInput/numeric/NonNegativeNumberInput.tsx
- client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NonNegativeIntegerCell.tsx
- client/packages/common/src/ui/layout/tables/components/Cells/TextInputCell/TextInputCell.tsx
- client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEdit.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditForm.tsx
Fixes #287 
Does what it says really.. there's a couple of files required, so have put in the PR without offroads.
Tested that inbounds and outbounds are both now focussing as I'd expect.
> Focus input cell

- server/graphql/invoice/src/mutations/inbound_shipment/delete.rs
- server/graphql/invoice_line/src/mutations/inbound_shipment_line/line/delete.rs
- server/graphql/invoice_line/src/mutations/outbound_shipment_line/line/delete.rs
> #272 Rewrite graphql invoice deletion tests

- server/graphql/invoice/src/mutations/inbound_shipment/insert.rs
- server/graphql/invoice_line/src/mutations/inbound_shipment_line/line/insert.rs
- server/graphql/invoice_line/src/mutations/outbound_shipment_line/line/insert.rs
- server/service/src/invoice/inbound_shipment/insert/mod.rs
- server/service/src/invoice_line/inbound_shipment_line/insert/mod.rs
> #285 rewrite graphql invoice insert tests

- client/packages/common/src/types/schema.ts
- client/packages/system/src/Patient/api/api.ts
- client/packages/system/src/Patient/api/operations.generated.ts
- client/packages/system/src/Patient/api/operations.graphql
- server/graphql/document/src/lib.rs
- server/graphql/document/src/queries/patient_search.rs
> Return a patient search connector from the patient search endpoint

- server/graphql/invoice/src/mutations/inbound_shipment/update.rs
- server/graphql/invoice_line/src/mutations/inbound_shipment_line/line/update.rs
- server/graphql/invoice_line/src/mutations/outbound_shipment_line/line/update.rs
- server/service/src/invoice/inbound_shipment/update/mod.rs
- server/service/src/invoice_line/inbound_shipment_line/update/mod.rs
> #290 rewrite graphql update invoice tests

- server/android/Cargo.toml
- server/repository/Cargo.toml
- server/service/Cargo.toml
Fixes #268 
I had to specifically request the `macros` in the service in order to build the report builder
> Specify tokio features in service

- client/packages/common/src/authentication/api/api.ts
- client/packages/common/src/authentication/api/hooks/useAuthApi.ts
- client/packages/common/src/intl/locales/en/app.json
Fixes #341 
Have added a translatable message, so that we can update easily. Am logging an error to the console, which is probably enough for now? 
Helps me out anyway..
> Log auth error & update messaging

- server/graphql/invoice/src/mutations/inbound_shipment/delete.rs
- server/repository/src/mock/invoice.rs
- server/service/src/invoice/inbound_shipment/delete/mod.rs
- server/service/src/invoice/inbound_shipment/insert/mod.rs
- server/service/src/invoice/inbound_shipment/update/mod.rs
- server/service/src/invoice/mod.rs
> #312 update service tests for inbound invoice

- client/packages/system/src/Patient/CreatePatientModal/CreatePatientModal.tsx
Must have happen during a merge...
> Fix bug from previous merge

- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/utils.ts
Fixes #361 
The issue is only when updating using the quantity which uses auto allocation. Updating rows individually is working.
> Quantity allocation

- server/graphql/invoice/src/mutations/outbound_shipment/add_from_master_list.rs
- server/graphql/invoice_line/src/mutations/inbound_shipment_line/line/insert.rs
- server/graphql/invoice_line/src/mutations/outbound_shipment_line/line/insert.rs
- server/graphql/invoice_line/src/mutations/outbound_shipment_line/unallocated_line/insert.rs
- server/graphql/invoice_line/src/mutations/outbound_shipment_line/unallocated_line/update.rs
- server/graphql/location/src/mutations/delete.rs
- server/graphql/types/src/types/invoice_line.rs
- server/repository/src/db_diesel/invoice_line.rs
- server/service/src/invoice/outbound_shipment/update/generate.rs
- server/service/src/invoice/outbound_shipment/update/mod.rs
closes #358 
I really like test driven dev for things like this, i've added the test first, it failed, then fixed test.
I've also added stock line to invoice line repository query, there was actually an issue to do that in remote server repo, and it makes the logic in update/generate of osline a bit nicer. Also renamed some things
> 358 fix bug with reduction of total number of packs in outbound shipment status change

- client/.vscode/launch.json
> Add a chrome debug config to launch.json

- client/packages/common/src/hooks/useUrlQuery/useUrlQuery.ts
- client/packages/common/src/hooks/useUrlQuery/useUrlQueryParams.ts
- client/packages/common/src/ui/layout/tables/DataTable.tsx
Fixes #390 
🤦‍♂️ Hoo boy. glad that no one saw me do that
> Stale column headers

- server/graphql/invoice_line/src/mutations/inbound_shipment_line/line/update.rs
- server/graphql/invoice_line/src/mutations/inbound_shipment_line/service_line/update.rs
- server/graphql/invoice_line/src/mutations/outbound_shipment_line/line/delete.rs
- server/graphql/invoice_line/src/mutations/outbound_shipment_line/line/update.rs
- server/graphql/invoice_line/src/mutations/outbound_shipment_line/service_line/update.rs
- server/graphql/invoice_line/src/mutations/outbound_shipment_line/unallocated_line/update.rs
- server/repository/src/mock/invoice.rs
- server/repository/src/mock/invoice_line.rs
- server/service/src/invoice_line/inbound_shipment_line/update/mod.rs
- server/service/src/invoice_line/inbound_shipment_service_line/update/mod.rs
- server/service/src/invoice_line/outbound_shipment_line/delete/mod.rs
- server/service/src/invoice_line/outbound_shipment_line/delete/validate.rs
- server/service/src/invoice_line/outbound_shipment_line/insert/mod.rs
- server/service/src/invoice_line/outbound_shipment_line/update/mod.rs
- server/service/src/invoice_line/outbound_shipment_service_line/update/mod.rs
- server/service/src/invoice_line/outbound_shipment_unallocated_line/update.rs
> #337 update tests for service -> outbound shipment lines

- client/package.json
- server/graphql/invoice/src/mutations/inbound_shipment/add_from_master_list.rs
- server/graphql/invoice_line/src/mutations/inbound_shipment_line/line/update.rs
- server/graphql/invoice_line/src/mutations/outbound_shipment_line/line/update.rs
- server/graphql/types/src/types/item.rs
- server/service/src/invoice/inbound_shipment/add_from_master_list.rs
- server/service/src/invoice/outbound_shipment/add_from_master_list.rs
- server/service/src/requisition_line/chart/mod.rs
- server/service/src/sync_processor/test.rs
With test fixes form https://github.com/openmsupply/open-msupply/pull/394, and more test fixes
> Merge from main

- server/service/src/invoice/inbound_shipment/insert/mod.rs
- server/service/src/invoice/inbound_shipment/update/mod.rs
- server/service/src/invoice/outbound_shipment/delete/mod.rs
- server/service/src/invoice/outbound_shipment/insert/mod.rs
- server/service/src/invoice/outbound_shipment/update/mod.rs
- server/service/src/invoice_line/inbound_shipment_line/delete/mod.rs
- server/service/src/invoice_line/inbound_shipment_line/insert/mod.rs
- server/service/src/invoice_line/inbound_shipment_line/update/mod.rs
- server/service/src/invoice_line/outbound_shipment_line/delete/mod.rs
- server/service/src/invoice_line/outbound_shipment_line/insert/mod.rs
- server/service/src/invoice_line/outbound_shipment_line/update/mod.rs
- server/service/src/invoice_line/outbound_shipment_unallocated_line/update.rs
Closes #396 
Also updated some NotThisStoreInvoice tests 👀
> #396 extra tests for outbound shipment line

- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/types/schema.ts
- client/packages/system/src/Patient/CreatePatientModal/PatientFormTab.tsx
- client/packages/system/src/Patient/CreatePatientModal/PatientResultsTab.tsx
- client/packages/system/src/Patient/DetailView/DetailView.tsx
- client/packages/system/src/Patient/hooks/useCreatePatientStore.ts
- server/graphql/document/src/queries/patient_search.rs
- server/service/src/document/patient/query.rs
- server/service/src/document/patient/search.rs
Adds id (code), gender and dob to the patient search. Extend api to support the new fields.
Open questions:
[#407](https://github.com/openmsupply/open-msupply/issues/407)
[#408](https://github.com/openmsupply/open-msupply/issues/408)
Closes #355
> 355 improve patient creation modal

- client/packages/common/src/ui/forms/JsonForms/JsonForm.tsx
- client/packages/common/src/ui/forms/JsonForms/components/FirstItemArray.tsx
- client/packages/common/src/ui/forms/JsonForms/components/index.ts
- server/service/src/sync/program_schemas/patient_ui_schema.json
> Add Array control that only shows the first item in an array

- client/packages/common/src/ui/forms/JsonForms/components/Date.tsx
- client/packages/common/src/ui/forms/JsonForms/components/DateOfBirth.tsx
- client/packages/system/src/Patient/CreatePatientModal/PatientFormTab.tsx
> Pass the correct value to the date picker input

- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/types/schema.ts
- client/packages/common/src/ui/forms/JsonForms/components/Array.tsx
- client/packages/common/src/ui/forms/JsonForms/components/Boolean.tsx
- client/packages/common/src/ui/forms/JsonForms/components/Date.tsx
- client/packages/common/src/ui/forms/JsonForms/components/DateOfBirth.tsx
- client/packages/common/src/ui/forms/JsonForms/components/Group.tsx
- client/packages/common/src/ui/forms/JsonForms/components/Label.tsx
- client/packages/common/src/ui/forms/JsonForms/components/Select.tsx
- client/packages/common/src/ui/forms/JsonForms/components/Text.tsx
- client/packages/system/src/Patient/DetailView/DetailView.tsx
- client/packages/system/src/Patient/ListView/ListView.tsx
- client/packages/system/src/Patient/api/operations.generated.ts
- client/packages/system/src/Patient/api/operations.graphql
- server/graphql/document/src/queries/patient.rs
- server/repository/migrations/postgres/2021-08-15T10-00_create_name_table/up.sql
- server/repository/migrations/sqlite/2021-08-15T10-00_create_name_table/up.sql
- server/repository/src/db_diesel/name_row.rs
- server/service/src/document/patient/patient_updated.rs
- server/service/src/document/patient/update.rs
- server/service/src/document/schemas/patient.json
- server/service/src/sync/init_programs_data.rs
- server/service/src/sync/integration_tests/name.rs
- server/service/src/sync/program_schemas/patient.json
- server/service/src/sync/program_schemas/patient_ui_schema.json
- server/service/src/sync/translation_central/name.rs
- server/service/src/sync/translation_central/test_data/name.rs
- server/service/src/sync/translation_remote/name.rs
- server/service/src/sync/translation_remote/test_data/name.rs
- I show the deceased flag in the patient list view right now. Eventually this can be removed or replace by a general patient status flag but though it good to show which information we have at this stage.
- JSONForms controls are not shown if the hidden flag is set (needed for isDeceased json schema rule)
Note, json schema / ajv (not JSONForms) ignores rules based on undefined values. For this reason the `isDeceased: boolean` is required, i.e. it needs to be set to make the ui schema rule work.
https://github.com/ajv-validator/ajv/issues/913
Closes #418
> 418 deceased patient

- client/packages/common/src/ui/forms/JsonForms/components/Select.tsx
- client/packages/system/src/Patient/CreatePatientModal/PatientResultsTab.tsx
- client/packages/system/src/Patient/hooks/useCreatePatientStore.ts
- server/service/src/document/schemas/patient.json
- server/service/src/sync/program_schemas/patient.json
- server/service/src/sync/program_schemas/patient_ui_schema.json
> 407 json schema enum screaming snake case

- server/repository/migrations/postgres/2021-11-05T10-00_create_sync_buffer_table/up.sql
- server/repository/src/db_diesel/changelog_row.rs
- server/service/src/sync/api/core.rs
- server/service/src/sync/remote_data_synchroniser.rs
- server/service/src/sync/synchroniser.rs
- server/service/src/sync/test/mod.rs
- server/service/src/sync/translation_and_integration.rs
> 338 PR review changes up to 333

- client/packages/common/src/ui/forms/Detail/InputWithLabelRow.tsx
- client/packages/common/src/ui/forms/JsonForms/components/Boolean.tsx
- client/packages/common/src/ui/forms/JsonForms/components/Date.tsx
- client/packages/common/src/ui/forms/JsonForms/components/DateOfBirth.tsx
- client/packages/common/src/ui/forms/JsonForms/components/Group.tsx
- client/packages/common/src/ui/forms/JsonForms/components/IdGenerator.tsx
- client/packages/common/src/ui/forms/JsonForms/components/Select.tsx
- client/packages/common/src/ui/forms/JsonForms/components/Text.tsx
- client/packages/common/src/ui/forms/JsonForms/styleConstants.ts
@CarlosNZ this seems to fix the current layout but you might have had something with it in mind?
Related to https://github.com/openmsupply/open-msupply/issues/424
> Remove GROUP_MAX_WIDTH to fix some group control issues

- client/packages/common/src/ui/components/navigation/Tabs/DetailTabs.tsx
- client/packages/common/src/ui/components/navigation/Tabs/Tabs.tsx
- client/packages/common/src/ui/components/navigation/Tabs/index.ts
- client/packages/common/src/ui/layout/tables/DataTable.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/DetailView.tsx
- client/packages/system/src/Location/Components/LocationSearchInput.tsx
- client/packages/system/src/Log/Components/ListView.tsx
Closes #23
A refactor of the tabs usage, to reduce the amount of stuff to add to each detail view
> Refactor detail tabs

- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/intl/utils/DateUtils.ts
- client/packages/inventory/src/Stocktake/DetailView/DetailView.tsx
- client/packages/invoices/src/InboundShipment/DetailView/DetailView.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/DetailView.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/DetailView.tsx
- client/packages/system/src/Log/Components/ListView.tsx
Closes #23
Adds the log and tabs to 
- Requisitions
- Internal orders
- Inbound shipments
- Stocktakes
> Add audit log to all areas

- client/packages/system/src/Patient/DetailView/PatientTab.tsx
- client/packages/system/src/Patient/DetailView/ProgramEnrolment/ListView.tsx
- client/packages/system/src/Patient/DetailView/ProgramEnrolment/api/hooks/document/useProgramEnrolments.ts
> 453 fix enrolment query

- client/packages/common/src/types/schema.ts
- client/packages/common/src/ui/forms/JsonForms/JsonForm.tsx
- client/packages/common/src/ui/forms/JsonForms/api/api.ts
- client/packages/common/src/ui/forms/JsonForms/api/hooks/document/index.ts
- client/packages/common/src/ui/forms/JsonForms/api/hooks/document/useAllocateNumber.ts
- client/packages/common/src/ui/forms/JsonForms/api/hooks/index.ts
- client/packages/common/src/ui/forms/JsonForms/api/hooks/utils/useAllocateNumberApi.ts
- client/packages/common/src/ui/forms/JsonForms/api/operations.generated.ts
- client/packages/common/src/ui/forms/JsonForms/api/operations.graphql
- client/packages/common/src/ui/forms/JsonForms/components/IdGenerator.tsx
- server/graphql/document/src/lib.rs
- server/graphql/document/src/mutations/allocate_number.rs
- server/graphql/document/src/mutations/mod.rs
- server/service/src/auth.rs
- server/service/src/sync/program_schemas/hiv_care_program_ui_schema.json
- server/service/src/sync/program_schemas/patient_ui_schema.json
> 430 enrolment patient

- client/packages/invoices/src/InboundShipment/DetailView/ContentArea/ContentArea.tsx
- client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts
- client/packages/invoices/src/OutboundShipment/DetailView/AddFromMasterListButton.tsx
- client/packages/invoices/src/utils.ts
- server/configuration/example.yaml
- server/service/src/report/default_queries.rs
- server/service/src/report/report_service.rs
Closes #415
Just a few misc items. I've decided not to address the line removal issues - the behaviour is a little odd in the context of placeholder rows, but is consistent for normal rows. Thought to leave the server changes for later, so that we can discuss properly before implementing those.
Allowing editing of the placeholder rows on inbounds will require changes to the server - this currently throws an error if you try to edit, which is why the f/e is deleting those lines and not allowing edits.
The removal when allocating lines in outbounds is also a deliberate implementation, so have left that for now too.
> Add from master lists improvements

- client/packages/common/src/intl/locales/en/app.json
- client/packages/common/src/ui/forms/JsonForms/components/IdGenerator.tsx
- client/packages/common/src/ui/forms/JsonForms/useJsonForms.tsx
- client/packages/config/src/routes.ts
- client/packages/host/src/Site.tsx
- client/packages/host/src/components/AppBar/AppBar.tsx
- client/packages/host/src/components/AppBar/SectionIcon.tsx
- client/packages/host/src/components/AppDrawer/AppDrawer.tsx
- client/packages/host/src/components/Navigation/PatientNav.tsx
- client/packages/host/src/components/Navigation/index.ts
- client/packages/host/src/routers/DispensaryRouter.tsx
- client/packages/host/src/routers/index.ts
- client/packages/system/src/Patient/CreatePatientModal/PatientResultsTab.tsx
- client/packages/system/src/Patient/ListView/ListView.tsx
- client/packages/system/src/Patient/Service/Service.tsx
> 464 patient side menu

- server/graphql/general/src/queries/tests/master_lists.rs
Master list test was failing due to insensitive filter
> Fix master list test

- server/graphql/document/src/lib.rs
- server/graphql/document/src/queries/encounter.rs
- server/graphql/document/src/queries/encounter_extract_field.rs
- server/graphql/document/src/queries/mod.rs
- server/service/src/document/encounter/extract_encounter_fields.rs
- server/service/src/document/encounter/extract_fields.rs
- server/service/src/document/encounter/mod.rs
> 476 encounter extract fields api

- server/server/src/lib.rs
- server/service/src/sync/synchroniser.rs
> #122 After initialisation restarting server goes to bootstrap unless we can reach central

- client/.github/workflows/bundle-size-diff.yaml
- client/package.json
- client/packages/host/package.json
- server/Cargo.toml
The frontend github action was broken since it requires the stats.json file.
This PR adds a build-dev script which is used in the github action
Closes #512
> 512 fix fe ci

- client/packages/system/src/Encounter/DetailView/DetailView.tsx
- client/packages/system/src/Encounter/DetailView/Toolbar.tsx
- client/packages/system/src/Patient/JsonForms/useJsonForms.tsx
Don't auto save encounter details but use the save button
Closes #542
> Save general encounter data using save button

- client/packages/common/src/types/schema.ts
- client/packages/system/src/Patient/JsonForms/api/api.ts
- client/packages/system/src/Patient/JsonForms/api/hooks/document/useEncounterFields.ts
- client/packages/system/src/Patient/JsonForms/api/hooks/utils/useDocumentApi.ts
- client/packages/system/src/Patient/JsonForms/api/operations.generated.ts
- client/packages/system/src/Patient/JsonForms/api/operations.graphql
- client/packages/system/src/Patient/JsonForms/components/EncounterLineChart.tsx
> Query encounter fields by patient id

- server/repository/migrations/postgres/2021-12-10T10-00_number_table/up.sql
- server/repository/migrations/sqlite/2021-12-10T10-00_number_table/up.sql
- server/repository/src/db_diesel/number_row.rs
- server/repository/src/mock/number.rs
- server/repository/src/tests.rs
- server/service/src/number.rs
- server/service/src/sync/integration_tests/number.rs
- server/service/src/sync/translation_remote/number.rs
- server/service/src/sync/translation_remote/test_data/mod.rs
- server/service/src/sync/translation_remote/test_data/number.rs
Closes #468 (Generate Customer Numbers for Programs)
Related to #451
> Allow custom numbers for Programs

- client/packages/common/src/types/schema.ts
- client/packages/system/src/Patient/JsonForms/api/api.ts
- client/packages/system/src/Patient/JsonForms/api/hooks/document/useAllocateNumber.ts
- client/packages/system/src/Patient/JsonForms/api/hooks/utils/useAllocateNumberApi.ts
- client/packages/system/src/Patient/JsonForms/api/operations.generated.ts
- client/packages/system/src/Patient/JsonForms/api/operations.graphql
- server/graphql/document/src/lib.rs
- server/graphql/document/src/mutations/allocate_number.rs
- server/service/src/auth.rs
> 451 use program number service

- client/packages/system/src/Patient/Encounter/DetailModal.tsx
- client/packages/system/src/Patient/PatientView/AddButton.tsx
- client/packages/system/src/Patient/PatientView/PatientView.tsx
- client/packages/system/src/Patient/ProgramEnrolment/Components/DetailModal.tsx
- client/packages/system/src/Patient/ProgramEnrolment/Components/ListView.tsx
- client/packages/system/src/Patient/hooks/usePatientModalStore.ts
> 527 modal state problem

- server/repository/migrations/postgres/2022-04-27T13-00_create_document_table/up.sql
- server/repository/migrations/sqlite/2022-04-27T13-00_create_document_table/up.sql
> Add a document name index

- client/packages/system/src/Patient/Encounter/DetailModal.tsx
- client/packages/system/src/Patient/PatientView/PatientView.tsx
- client/packages/system/src/Patient/ProgramEnrolment/Components/DetailModal.tsx
This reverts commit 187e68d6d0f53aa8a1f6430b208ba3c28a560a53.
I was a bit too quick, I realized that returning null doesn't unmount the component.
> Revert "Add unmount logic into the detail modals"

- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/ui/forms/JsonForms/JsonForm.tsx
- client/packages/common/src/ui/forms/JsonForms/components/Array.tsx
- client/packages/common/src/ui/forms/JsonForms/components/CategorizationTabLayout.tsx
- client/packages/common/src/ui/forms/JsonForms/components/Group.tsx
- client/packages/common/src/ui/forms/JsonForms/components/Number.tsx
- client/packages/system/src/Encounter/DetailView/DetailView.tsx
- client/packages/system/src/Patient/JsonForms/components/EncounterLineChart.tsx
- server/service/src/sync/program_schemas/hiv_care_encounter.json
- server/service/src/sync/program_schemas/hiv_care_encounter_ui_schema.json
- Better array support for string enum arrays
- Ask before removing item from an array
Closes #487
> 487 array layout

- server/service/src/document/Programs.md
Add some general overview over the program module.
I plan to add some issues to flesh out the plan about program permissions and sync as well.
> Add some program overview docs

- client/packages/common/src/hooks/useUrlQuery/useUrlQueryParams.ts
- client/packages/common/src/ui/forms/JsonForms/components/Array.tsx
- client/packages/common/src/ui/forms/JsonForms/components/Boolean.tsx
- client/packages/common/src/ui/forms/JsonForms/components/CategorizationTabLayout.tsx
- client/packages/common/src/ui/forms/JsonForms/components/Number.tsx
- client/packages/common/src/ui/forms/JsonForms/components/Select.tsx
- client/packages/common/src/ui/forms/JsonForms/styleConstants.ts
- client/packages/system/src/Encounter/DetailView/DetailView.tsx
- client/packages/system/src/Patient/JsonForms/components/EncounterLineChart.tsx
- client/packages/system/src/Patient/ListView/ListView.tsx
- server/service/src/sync/program_schemas/hiv_care_encounter_ui_schema.json
- server/service/src/sync/program_schemas/hiv_testing_encounter_ui_schema.json
Fixes various smaller issues:
- updates schema
- layout spacing in the category modal
- more consistent margins
- wider left column in forms
- fix encounter query in the encounter chart
- fix initial sort in useUrlQueryParams hook (@mark-prins please double check)
- React warning for unstable values
Closes #567
> Layout fixes

- server/repository/src/database_settings.rs
> Remove postgres patch

- server/graphql/programs/src/mutations/update_document.rs
- server/repository/migrations/postgres/2022-04-27T13-00_create_document_table/up.sql
- server/repository/migrations/sqlite/2022-04-27T13-00_create_document_table/up.sql
- server/repository/src/db_diesel/document.rs
- server/repository/src/mock/document.rs
- server/service/src/document/document_service.rs
- server/service/src/document/raw_document.rs
- server/service/src/programs/encounter/insert.rs
- server/service/src/programs/encounter/update.rs
- server/service/src/programs/patient/update.rs
- server/service/src/programs/program_enrolment/upsert.rs
> Add optional patient column to documents

- server/server/src/lib.rs
- server/service/src/sync/synchroniser.rs
> 606 "sever" to "server"

- server/service/src/processors/mod.rs
> Processor driver to preserve order of processors

- client/packages/common/src/authentication/AuthContext.tsx
- client/packages/common/src/authentication/api/operations.generated.ts
- client/packages/common/src/authentication/hooks/usePermissionCheck.ts
- client/packages/common/src/types/schema.ts
- client/packages/host/src/Admin/Settings.tsx
- client/packages/host/src/components/AppDrawer/AppDrawer.tsx
Closes #620 
- Rename UserPermissionNodePermission in FE
- Update schema
> Dynamic permission schema change + renaming in FE

- server/service/src/sync/init_programs_data.rs
Fixes #625 
The patient did not have a `name_store_join` record, so the insert validation failed.
Unfortunately, the `name_store_join` table has a foreign key which requires the `name` record to exist first. So I've added directly to the `name`, created the `name_store_join` and then updated as per.
This isn't ideal - but is temporary and only used to create the test program data.
> Create demo program patients

- build/windows/demo/launch.bat
- build/windows/demo/local.yaml
- build/windows/installers-build.bat
- build/windows/omsupply-build.bat
- build/windows/omsupply_demo.suf
- build/windows/omsupply_server.suf
Closes #627 
Builds a demo installer 😉 
- modified the omsupply build batch file to build the executable version of the `remote_server` ( rather than the windows-service version )
- created a `.suf` to build the installer
- copies the exe
- copies a sqlite database which has synchronised against the demo server
- copies a `local.yaml` which allows running under http and has the logging configured
- starts the server and browses to the web app
- create a shortcut on the desktop which starts the server
- modified the installer task in jenkins to build the installer
> Demo installer

- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/ui/components/inputs/TextInput/PasswordTextInput.tsx
- client/packages/common/src/ui/components/inputs/TextInput/index.ts
- client/packages/common/src/ui/icons/Eye.tsx
- client/packages/common/src/ui/icons/EyeOff.tsx
- client/packages/common/src/ui/icons/Icon.stories.tsx
- client/packages/common/src/ui/icons/index.ts
- client/packages/host/src/Admin/Setting.tsx
- client/packages/host/src/Admin/SyncSettings.tsx
- client/packages/host/src/components/Login/LoginTextInput.tsx
Closes #654 #662 
Adds the password visibility eye and a caps lock warning for good measure.
> Improve password usability

- server/repository/src/db_diesel/changelog/test.rs
- server/repository/src/db_diesel/invoice_row.rs
- server/repository/src/db_diesel/location_row.rs
- server/server/src/set_icon.rs
- server/service/src/invoice/outbound_shipment/update/generate.rs
- server/service/src/invoice_line/inbound_shipment_service_line/insert/validate.rs
- server/service/src/invoice_line/outbound_shipment_service_line/update/mod.rs
- server/service/src/processors/transfer/requisition/create_response_requisition.rs
- server/service/src/processors/transfer/requisition/test.rs
- server/service/src/processors/transfer/shipment/create_inbound_shipment.rs
- server/service/src/processors/transfer/shipment/test.rs
- server/service/src/sync/test/test_data/master_list.rs
- server/service/src/sync/test/test_data/master_list_line.rs
- server/service/src/sync/test/test_data/master_list_name_join.rs
- server/service/src/sync/test/test_data/name_store_join.rs
- server/service/src/sync/test/test_data/report.rs
- server/windows/src/windows.rs
> #619 Their reference and comment to transfer as per mSupply 

- server/service/src/sync/program_schemas/hiv_care_encounter.json
- server/service/src/sync/program_schemas/hiv_care_encounter_ui_schema.json
Closes #652 
As requested. Have also saved changes to the programschemas repo
> Rearrange who

- client/README.md
- client/codegen.yml
- client/package.json
- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/intl/locales/fr/common.json
- client/packages/common/src/intl/utils/DateUtils.ts
- client/packages/common/src/types/schema.ts
- client/packages/common/src/ui/components/errors/ErrorWithDetails.tsx
- client/packages/common/src/ui/components/inputs/TextInput/numeric/NonNegativeIntegerInput.tsx
- client/packages/common/src/ui/components/inputs/TextInput/numeric/NonNegativeNumberInput.tsx
- client/packages/common/src/ui/components/inputs/TextInput/numeric/NumericTextInput.tsx
- client/packages/common/src/ui/components/inputs/TextInput/numeric/PositiveNumberInput.tsx
- client/packages/common/src/ui/layout/tables/columns/EditableQuantityColumn.tsx
- client/packages/common/src/utils/formatters/formatters.ts
- client/packages/common/src/utils/numbers/NumUtils.test.ts
- client/packages/common/src/utils/numbers/NumUtils.ts
- client/packages/host/src/Admin/SyncSettings.tsx
- client/packages/host/src/Host.tsx
- client/packages/host/src/Site.tsx
- client/packages/host/src/components/Sync/Sync.tsx
- server/.gitignore
- server/graphql/general/src/queries/sync_status.rs
- server/repository/migrations/postgres/2022-06-21-013225_create_log_table/up.sql
Closes #688 
This implements changes for the simpler items on the list.
There are three remaining items - have created issues for those and they can be managed independently of the main issue.
Hopefully nothing too controversial in this PR - really just tidying up a few things, and implementing suggestions.
The error display is now using a tooltip. I'm not totally convinced about the two icons.. but ok for now I think.
> Manual sync extra

- client/packages/dashboard/src/widgets/StockWidget.tsx
- client/packages/invoices/src/InboundShipment/Dashboard/Widget.tsx
- client/packages/invoices/src/InboundShipment/api/hooks/document/useInsertInbound.ts
- client/packages/invoices/src/OutboundShipment/Dashboard/Widget.tsx
- client/packages/requisitions/src/RequestRequisition/api/hooks/document/useInsertRequest.ts
Closes #708 
- Enabled Inbound Shipment button on dashboard. 
- Have name hooks render only when modal is opened to avoid conflicts with customer/supplier
> 708 consistent dashboard button navigation

- server/service/src/stocktake/update.rs
Closes #720 
After discussion ended up as a one line PR 😭 
Expiration date now saves to stock line if changed in stocktake
> 720 Issues with stocktake

- client/packages/system/src/Patient/CreatePatientModal/PatientFormTab.tsx
> Check date validity

- decisions/version-compatibility.md
Would require a placeholder issue for implementation of this before merging
> Add KDD for versions and compatibility

- client/packages/common/src/hooks/useBreadcrumbs/useBreadcrumbs.tsx
- client/packages/common/src/ui/components/navigation/Breadcrumbs/Breadcrumbs.tsx
- client/packages/host/src/components/AppBar/SectionIcon.tsx
Fixes #732 
Just another merge conflict for when we bring in the features branch..
> Heading for admin pages

- decisions/migrations.md
- decisions/version-compatibility.md
Originated from issue linked in the KDD, and there was a suggestion made that KDD would be a great place to reference when there are questions or enquires about migration and the direction we've chosen (i agree)
> Add KDD for migrations

- client/packages/host/src/Admin/Settings.tsx
- client/packages/host/src/components/AppVersion.tsx
- client/packages/host/src/components/Initialise/InitialiseLayout.tsx
- client/packages/host/src/components/Login/LoginLayout.tsx
- client/packages/host/src/components/index.ts
Closes #744 
Lifted out the app version from Admin and added to Login and Initialise screens
> Show app version on login & init

- client/packages/common/src/intl/locales/en/common.json
- client/packages/system/src/Encounter/ListView/columns.ts
- server/service/src/sync/program_schemas/hiv_testing_encounter.json
- server/service/src/sync/program_schemas/hiv_testing_encounter_ui_schema.json
> Fix spelling / label

- client/packages/common/src/intl/locales/en/app.json
- client/packages/common/src/ui/forms/JsonForms/components/Text.tsx
- client/packages/host/src/CommandK.tsx
- server/service/src/sync/init_programs_data.rs
- server/service/src/sync/program_schemas/patient_ui_schema.json
Fixes parts of #655 
- remove mother
- ui pattern definition for national health id number
> 655 patient registration 1

- client/packages/common/src/types/schema.ts
- client/packages/invoices/src/OutboundShipment/DetailView/Toolbar.tsx
- client/packages/invoices/src/OutboundShipment/api/api.ts
- client/packages/invoices/src/OutboundShipment/api/hooks/document/index.ts
- client/packages/invoices/src/OutboundShipment/api/hooks/document/useOutboundUpdateName.ts
- client/packages/invoices/src/OutboundShipment/api/hooks/index.ts
- client/packages/invoices/src/OutboundShipment/api/operations.generated.ts
- client/packages/invoices/src/OutboundShipment/api/operations.graphql
- server/schema.graphql
Closes #762 
Use new endpoint for name change in Outbound Shipments
> Changing supplier/customer on shipments can cause strife for sync fe

- client/packages/common/src/utils/regex/RegexUtils.tsx
- client/packages/system/src/Stock/ListView/ListView.tsx
Fixes #773 
A nice easy one to review 😉
> Fix regex utils ( new stocktake :: item search input )

- server/graphql/invoice/src/mutations/inbound_shipment/update.rs
- server/graphql/invoice/src/mutations/outbound_shipment/update_name.rs
- server/service/src/invoice/inbound_shipment/add_from_master_list.rs
- server/service/src/invoice/inbound_shipment/delete/mod.rs
- server/service/src/invoice/inbound_shipment/delete/validate.rs
- server/service/src/invoice/inbound_shipment/update/validate.rs
- server/service/src/invoice/outbound_shipment/add_from_master_list.rs
- server/service/src/invoice/outbound_shipment/delete/mod.rs
- server/service/src/invoice/outbound_shipment/delete/validate.rs
- server/service/src/invoice/outbound_shipment/update/validate.rs
- server/service/src/invoice/outbound_shipment/update_name/validate.rs
- server/service/src/invoice/validate.rs
- server/service/src/invoice_line/inbound_shipment_line/delete/validate.rs
- server/service/src/invoice_line/inbound_shipment_line/insert/validate.rs
- server/service/src/invoice_line/inbound_shipment_line/update/validate.rs
- server/service/src/invoice_line/inbound_shipment_line/validate.rs
- server/service/src/invoice_line/inbound_shipment_service_line/delete/validate.rs
- server/service/src/invoice_line/inbound_shipment_service_line/insert/validate.rs
- server/service/src/invoice_line/inbound_shipment_service_line/update/validate.rs
- server/service/src/invoice_line/outbound_shipment_line/delete/validate.rs
- server/service/src/invoice_line/outbound_shipment_line/insert/validate.rs
- server/service/src/invoice_line/outbound_shipment_line/update/validate.rs
- server/service/src/invoice_line/outbound_shipment_line/validate.rs
- server/service/src/invoice_line/outbound_shipment_service_line/delete/validate.rs
- server/service/src/invoice_line/outbound_shipment_service_line/insert/validate.rs
- server/service/src/invoice_line/outbound_shipment_service_line/update/validate.rs
- server/service/src/invoice_line/outbound_shipment_unallocated_line/delete.rs
- server/service/src/invoice_line/outbound_shipment_unallocated_line/insert.rs
- server/service/src/invoice_line/outbound_shipment_unallocated_line/update.rs
- server/service/src/invoice_line/validate.rs
Closes #795 
- Remove From trait from invoice/invoice line mapping
> Refactor invoice/invoice line error mapping

- client/packages/system/src/Name/Components/NameOptionRenderer/NameOptionRenderer.tsx
> 782 Specify unique key prop on option list components

- client/packages/invoices/src/OutboundShipment/Dashboard/Widget.tsx
- server/graphql/general/src/queries/invoice_counts.rs
- server/service/src/dashboard/invoice_count.rs
Outbound count was showing all outbound invoices instead of filtering by store
> Add filter by store id to outbound count

- server/service/src/invoice/outbound_shipment/update_name/generate.rs
- server/service/src/invoice/outbound_shipment/update_name/mod.rs
Closes #809 
Transfer the activity log into the new invoices. 
Currently, the activity logs for the old invoice - both outbound and inbound are still stored in the database since we have not implemented deletes for activity log, and deletes aren't sync to mSupply. Will need to do something about this 🤔 (Not a big deal, just a lot of entries)
> #809 Name change invoices don't have log

- decisions/Android machine_uid.md
> Create Android machine_uid.md

- client/packages/system/src/Patient/JsonForms/components/BMI.tsx
> Fix infinity bug for bmi

- .gitignore
- server/service/src/sync/init_programs_data.rs
- server/service/src/sync/program_schemas/hiv_care_program.json
- server/service/src/sync/program_schemas/hiv_care_program_ui_schema.json
- server/service/src/sync/program_schemas/patient.json
- server/service/src/sync/program_schemas/patient_ui_schema.json
Takes care of most of the simple elements in #644. I've made new issues for the more involved ones.
@clemens-msupply we might have to co-ordinate our Prettier settings as a lot of the changes here are just auto-formatting.
> #644(1) HIV Care and treatment enrolment updates

- server/service/src/sync/translations/name.rs
Was missing empty_str_as_option import in translation/name.rs
> Programs missing import

- README.md
Fixes #900 
Some basic instructions of how to get a build of mSupply
> README build instructions

- client/packages/common/src/ui/components/inputs/DatePickers/BaseDatePickerInput/BaseDatePickerInput.tsx
Closes #868 
Change calendar highlight to blue instead of orange. Did this in develop, so will need to update programs with develop again soon~
> 868 Calendar select color

- server/service/src/programs/schemas/patient.json
- server/service/src/sync/init_programs_data.rs
- server/service/src/sync/program_schemas/patient.json
- server/service/src/sync/program_schemas/patient_ui_schema.json
Closes #682 
- Move fields around to match with request 
- Added a relationship field to Next of Kin
> 682 programs patient registration form layout

- client/packages/programs/src/JsonForms/common/components/Array.tsx
- client/packages/programs/src/JsonForms/common/components/Autocomplete.tsx
- client/packages/programs/src/JsonForms/common/components/ConditionalSelect.tsx
- client/packages/programs/src/JsonForms/common/components/Date.tsx
- client/packages/programs/src/JsonForms/common/components/DateTime.tsx
- client/packages/programs/src/JsonForms/common/components/Group.tsx
- client/packages/programs/src/JsonForms/common/components/Number.tsx
- client/packages/programs/src/JsonForms/common/components/Select.tsx
- client/packages/programs/src/JsonForms/components/QuanityPrescribed.tsx
- client/packages/programs/src/JsonForms/useJsonForms.tsx
- server/service/src/sync/program_schemas/hiv_care_encounter.json
- server/service/src/sync/program_schemas/hiv_care_encounter_ui_schema.json
Implements some of the low hanging fruits from #843 
- Also did some style and alignment updates for various select and autocomplete boxes... (opinion welcome)
- Also pass on enable flags to various components (needed for JSONForms rules)
> 843 arv medication section

- server/Cargo.lock
- server/README.md
- server/cli/Cargo.toml
- server/cli/src/cli.rs
- server/data/reference1/users.txt
- server/service/src/settings_service.rs
- server/service/src/sync/mod.rs
- server/service/src/sync/sync_status/logger.rs
- server/service/src/sync/sync_status/mod.rs
closes #904 
CLI updates:
* fix some comments
* make sure we get site_id correctly and store it in initialisation export, and set it on import
* set sync status correctly (through sync log)
Other
* Quick comment in readme about sync setting in yaml file during initialisation from export
* Re exported reference data file json (site_id was added, I used data file from demo server, specifically the one in `demo_primary.zip` in data file folder)
> 904 update cli for initialisation from file

- client/packages/common/src/types/schema.ts
- client/packages/common/src/ui/components/inputs/TextInput/numeric/PositiveNumberInput.tsx
- client/packages/programs/src/JsonForms/common/components/Number.tsx
- client/packages/programs/src/JsonForms/components/AdherenceStatus.tsx
- client/packages/programs/src/JsonForms/components/EncounterLineChart.tsx
- client/packages/programs/src/JsonForms/components/IdGenerator.tsx
- client/packages/programs/src/JsonForms/components/QuanityPrescribed.tsx
- client/packages/programs/src/JsonForms/useDocumentLoader.ts
- client/packages/programs/src/JsonForms/useJsonForms.tsx
- client/packages/programs/src/api/api.ts
- client/packages/programs/src/api/hooks/document/index.ts
- client/packages/programs/src/api/hooks/document/useEncounterById.ts
- client/packages/programs/src/api/hooks/document/useEncounterPrevious.ts
- client/packages/programs/src/api/hooks/index.ts
- client/packages/programs/src/api/hooks/utils/useDocumentRegistryApi.ts
- client/packages/programs/src/api/hooks/utils/useEncounterApi.ts
- client/packages/programs/src/api/operations.generated.ts
- client/packages/programs/src/api/operations.graphql
- client/packages/programs/src/index.ts
- client/packages/system/src/Patient/CreatePatientModal/CreatePatientModal.tsx
- client/packages/system/src/Patient/api/api.ts
- client/packages/system/src/Patient/api/hooks/document/useProgramEncounters.ts
- client/packages/system/src/Patient/api/hooks/utils/usePatientApi.ts
- client/packages/system/src/Patient/api/operations.generated.ts
- client/packages/system/src/Patient/api/operations.graphql
- client/packages/system/src/Patient/hooks/usePatientCreateStore.ts
- server/service/src/sync/program_schemas/hiv_care_encounter.json
- server/service/src/sync/program_schemas/hiv_care_encounter_ui_schema.json
To test:
- go to earliest encounter and set "Quantity prescribed" to 7 (Quantity prescribed is actually pills on hand after the current encounter, better name?)
- save
- got to next encounter and modify pills remaining
Also includes:
- some API clean up
- Numeric min value input fixes
> 909 adherence status control

- client/packages/common/src/intl/utils/DateUtils.ts
- client/packages/common/src/ui/components/inputs/TextInput/numeric/PositiveNumberInput.tsx
- client/packages/common/src/utils/numbers/NumUtils.ts
- client/packages/programs/src/JsonForms/components/AdherenceStatus.tsx
Fix max api number regression and add some time constants
Follow up from #909
> 909 number input fixes

- server/cli/src/refresh_dates.rs
- server/service/src/sync/sync_serde.rs
- server/service/src/sync/sync_status/status.rs
- server/service/src/sync/sync_status/test.rs
> Fix sync status tests

- client/packages/common/src/ui/components/inputs/TimePickers/TimePickerInput/TimePickerInput.tsx
- client/packages/common/src/ui/icons/User.tsx
- client/packages/programs/src/JsonForms/common/components/Array.tsx
- client/packages/programs/src/JsonForms/common/components/Autocomplete.tsx
- client/packages/system/src/Encounter/DetailView/Toolbar.tsx
Fixes #856 (programs bits)
**Patients**
**JSON forms**
> UI review items part II

- decisions/2023-01-11_report_arguments.md
> Add KDD for Report arguments

- client/package.json
- client/packages/host/src/Host.tsx
- client/packages/host/src/components/AppVersion.tsx
> #1005 Fix wrong app version display in ui

- build/windows/omsupply_server.suf
> #1004 Fix rust link lib for postgres

- server/service/src/sync/test/test_data/name_store_join.rs
- server/service/src/sync/translations/name_store_join.rs
closes #1037 
I've made a [build](https://drive.google.com/file/d/1PzbEJ4d61-yZpjiv2DY_y51M91osMsar/view?usp=sharing), not sure how to manage them, would be great to discuss with @mark-prins what we do with RC builds
> Ignore name_store_join.name_is_customer/supplier in sync

- decisions/android-framework.md
closes #916 
This is a draft KDD, likely needs more input from the rest of the team
> Add android platform KDD

- client/packages/android/app/build.gradle
- package.json
closes: https://github.com/openmsupply/open-msupply/issues/1054
~~Draft~~ PR for android version from package.json
> Android app version from package.json

- server/service/src/sync/program_schemas/hiv_care_encounter_ui_schema.json
> Update name in the ARV section

- client/packages/host/src/components/Navigation/DispensaryNav.tsx
Update programs branch for changes from #1022
> Use AppNavSection for the Dispensary entry

- server/repository/src/db_diesel/name.rs
> Temporary remove enrolment join from name query

- client/packages/common/src/hooks/useUrlQuery/useUrlQueryParams.ts
- client/packages/common/src/intl/locales/en/patients.json
- client/packages/common/src/types/schema.ts
- client/packages/common/src/ui/components/inputs/SearchBar/SearchBar.tsx
- client/packages/system/src/Patient/ListView/ListView.tsx
- client/packages/system/src/Patient/ListView/Toolbar.tsx
- client/packages/system/src/Patient/api/hooks/document/usePatients.ts
Adds a first name and identifier search input field.
Future work:
- Discuss search UX?
- Search for DOB?
- Search by string like "C.Zei"?
Closes #1014
> 1014 patient simple search UI

- decisions/2022-12-12_patient_and_program_transfer.md
Initial draft KDD to collect some ideas. Also contains a summary on how patients are searched and accessed in current mSupply, please let me know if I got something wrong.
The KDD is quite wide but I think its good to have the wider picture and to develop the general idea for how things can be done.
> Add draft KDD for patient and program sync/transfers

- client/packages/system/src/Patient/Encounter/ListView.tsx
Fixes #1101 
I broke it when doing the hooks refactoring.
> Fix patient encounter query

- client/packages/common/src/types/schema.ts
- client/packages/system/src/Report/api/hooks/document/useReports.ts
- client/packages/system/src/Report/api/operations.generated.ts
- client/packages/system/src/Report/api/operations.graphql
- client/packages/system/src/Report/components/ReportSelector.tsx
- server/graphql/reports/src/reports.rs
- server/repository/migrations/postgres/2023-01-16T10-00_report_secondary_context_and_arg_schema_v1.0.5/up.sql
- server/repository/migrations/sqlite/2023-01-16T10-00_report_secondary_context_and_arg_schema_v1.0.5/up.sql
- server/repository/src/db_diesel/report.rs
- server/repository/src/db_diesel/report_row.rs
- server/service/src/report/report_service.rs
- server/service/src/sync/init_programs_data.rs
- server/service/src/sync/test/test_data/report.rs
- server/service/src/sync/translations/report.rs
> 1059 rename context2 to sub context

- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditTable.tsx
Fixes #1050 
Just updated the buffer if the line has updated
> Update OS placeholder

- client/packages/system/src/Patient/Encounter/CreateEncounterModal.tsx
- server/graphql/programs/src/queries/encounter.rs
- server/graphql/programs/src/types/encounter.rs
- server/repository/migrations/postgres/2022-06-07T17-00_create_encounter_table/up.sql
- server/repository/migrations/sqlite/2022-06-07T17-00_create_encounter_table/up.sql
- server/repository/src/db_diesel/encounter.rs
- server/repository/src/db_diesel/encounter_row.rs
- server/service/src/programs/encounter/encounter_schema.rs
- server/service/src/programs/encounter/encounter_updated.rs
- server/service/src/programs/encounter/update.rs
- server/service/src/programs/encounter/validate_misc.rs
- server/service/src/programs/schemas/encounter.json
- server/service/src/programs/schemas/patient.json
- server/service/src/programs/schemas/program_enrolment.json
- server/service/src/sync/init_programs_data.rs
- server/service/src/sync/program_schemas/hiv_care_encounter.json
- server/service/src/sync/program_schemas/hiv_care_program.json
- server/service/src/sync/program_schemas/hiv_testing_encounter.json
- server/service/src/sync/program_schemas/hiv_testing_program.json
- server/service/src/sync/program_schemas/patient.json
- server/service/src/sync/program_schemas/routine_immunisation_3month_encounter.json
- server/service/src/sync/program_schemas/routine_immunisation_5month_encounter.json
- server/service/src/sync/program_schemas/routine_immunisation_6weeks_encounter.json
> 1133 encounter created datetime

- client/packages/common/src/types/schema.ts
- client/packages/programs/src/api/operations.generated.ts
- client/packages/programs/src/api/operations.graphql
- server/graphql/programs/src/types/document.rs
> 676 add user node

- client/packages/programs/src/JsonForms/common/JsonForm.tsx
- client/packages/programs/src/JsonForms/common/components/Spacer.tsx
- client/packages/programs/src/JsonForms/common/components/index.ts
- server/service/src/sync/program_schemas/hiv_testing_encounter_ui_schema.json
Closes #1154 
Very simple component, implemented in `hiv_testing_encounter_ui_schema.json` as per the issue mockup.
Two options available:
- `margin` (default: `20`)
- `hideDivider` (default: `false`) -- so we can create spacers without a line if we want to
> #1154 Spacer component

- client/__mocks__/barcode_scanner.ts
- client/jest.config.js
- client/packages/common/src/intl/currency/currency.test.tsx
- client/packages/common/src/ui/layout/tables/components/DataRow/DataRow.test.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/hooks/useNextItem.test.tsx
- client/packages/system/src/Item/api/operations.generated.ts
Fixes #1170 
_Nothing special required_
> Fix f/e test suite

- server/service/src/sync/program_schemas/hiv_testing_encounter_ui_schema.json
> Improve the JSONForms rule for the testing encounter

- client/packages/programs/src/JsonForms/common/components/Array/Generic.tsx
- server/repository/src/db_diesel/name.rs
- server/service/src/programs/encounter/update.rs
- server/service/src/sync/program_schemas/hiv_care_encounter.json
Closes #932 
Change Prophylaxis Medication into a drop down list
Go to dispensary => encounter => ARV/Medication to see drop down list for prophylaxis medication
> 932 prog] control] array of strings

- client/packages/system/src/Patient/ProgramEnrolment/Components/ListView.tsx
Fixes #1179 
Displays program name in the list view
- Status still pending change since decision hasn't been made for it yet
> Load document name for list view

- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/hooks/useDraftOutboundLines.tsx
Fixes #1175 
The item prop of the placeholder was not being updated when the item changes
Follow the steps in the issue
- Create and outbound shipment
- Add an item 'x'
- Change the item to 'y', selecting one with some stock
- Enter a value for more stock than you have, click `Allocate`
- Click `OK`
What you should see is a placeholder for the item 'x' and a stock line for item 'x'
> Update item on placeholder

- client/packages/common/src/types/schema.ts
- server/graphql/general/src/lib.rs
- server/graphql/general/src/queries/mod.rs
- server/graphql/general/src/queries/store_preference.rs
- server/service/src/auth.rs
Fixes #1249 
Endpoint to query for store preferences
Call endpoint to see all store preferences
- Will need to update programs with develop once this is merged
> 1249 API to get store preferences 

- server/service/src/sync/init_programs_data.rs
- server/service/src/sync/program_schemas/hiv_care_encounter.json
- server/service/src/sync/program_schemas/hiv_care_encounter_ui_schema.json
Fixes #828
- Record the systolic and diastolic values separately for blood pressure
- Also moved BMI up, since it's calculated from height and weight.
- Go to an Care Encounter and see values... or change values
> 828 record blood pressure in two values

- server/README.md
Update docs for installing the remote server on a fresh ubuntu VM image
Part of #1246
> Ubuntu setup docs

- client/packages/common/src/intl/locales/en/patients.json
- client/packages/programs/src/JsonForms/useJsonForms.tsx
- client/packages/system/src/Patient/CreatePatientModal/CreatePatientModal.tsx
Fixes #1291 
Sorry thought #1285 was a different bug... think this fixes related problem though, since #1285 wasn't fully fixed.
> 1291 patient creation improvements

- client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/InboundLineEditForm.tsx
Fixes #1272 
Per docs: https://www.i18next.com/translation-function/plurals#languages-with-multiple-plurals
> #1272 - Inbound shipment, Adding item, Missing label `Item`

- build/windows/omsupply_server.suf
Fixes #1320
If the `GetKeyNames` call fails for some reason it returns `nil`
Otherwise it returns an empty table. When the result is `nil` - don't try to access properties of it.
Built the installer and tested after uninstalling existing version and updating the registry keys manually.
> Check for nil tables when installing server

- server/service/src/sync/program_schemas/patient_ui_schema.json
Fixes #1329
Fixes #1331 
Smaller fixes to the patient ui schema.
> Update patient ui schema

- client/packages/programs/src/JsonForms/common/components/Number.tsx
- server/service/src/sync/program_schemas/hiv_care_encounter.json
Fixes #1288
Adds a max/min value for blood pressure
Try to enter a number greater than 999 for blood pressure
> 1288 Change number input pattern to max number in schema

- client/packages/programs/src/JsonForms/common/JsonForm.tsx
- client/packages/programs/src/JsonForms/common/components/Header.tsx
- client/packages/programs/src/JsonForms/common/components/Label.tsx
- server/service/src/sync/init_programs_data.rs
- server/service/src/sync/program_schemas/hiv_care_encounter_ui_schema.json
- server/service/src/sync/program_schemas/hiv_care_program_ui_schema.json
- server/service/src/sync/program_schemas/hiv_testing_encounter.json
- server/service/src/sync/program_schemas/hiv_testing_encounter_ui_schema.json
- server/service/src/sync/program_schemas/hiv_testing_program_ui_schema.json
- server/service/src/sync/program_schemas/routine_immunisation_program_ui_schema.json
Fixes #1334
Unifies enrolment form titles (added an h1 title for modals since the other one has too much bottom padding), remove some fields from the program enrolment form, rename/shuffle HIV testing encounter fields.
Go to HIV testing Encounter.
One of the requests needs discussing
> 1334 programs hiv testing and counselling workflow 

- client/packages/programs/src/JsonForms/common/components/Header.tsx
- server/service/src/sync/program_schemas/hiv_care_program_ui_schema.json
- server/service/src/sync/program_schemas/hiv_testing_program_ui_schema.json
- server/service/src/sync/program_schemas/routine_immunisation_program_ui_schema.json
Fixes #1408
Requested in https://github.com/openmsupply/open-msupply/pull/1385#discussion_r1145504420
> Refactor Header.tsx to use zod

- server/service/src/programs/patient/patient_updated.rs
- server/service/src/programs/patient/upsert.rs
- server/service/src/programs/program_enrolment/program_enrolment_updated.rs
- server/service/src/programs/program_enrolment/upsert.rs
- server/service/src/programs/update_program_document.rs
- server/service/src/sync/integrate_document.rs
Review fixes for comment from previous PRs of issue #1247
> Review fixes for document sync PRs

- server/repository/migrations/postgres/2023-03-27T10-00_user_permission_remove_user_id_constraint/down.sql
- server/repository/migrations/postgres/2023-03-27T10-00_user_permission_remove_user_id_constraint/up.sql
- server/repository/migrations/sqlite/2023-03-27T10-00_user_permission_remove_user_id_constraint/down.sql
- server/repository/migrations/sqlite/2023-03-27T10-00_user_permission_remove_user_id_constraint/up.sql
- server/service/src/programs/encounter/encounter_updated.rs
- server/service/src/sync/sync_buffer.rs
- server/service/src/sync/test/integration/central/mod.rs
- server/service/src/sync/test/integration/central/test.rs
- server/service/src/sync/test/integration/remote/mod.rs
- server/service/src/sync/test/integration/remote/test.rs
- server/service/src/sync/test/integration/remote/user_permission.rs
- server/service/src/sync/test/test_data/user_permission.rs
- server/service/src/sync/translations/mod.rs
Follow up for #1275
Ideally would have some migration tests, which would be easy to do using the new migration code. However, since I am unsure about the final release version its a bit difficult to add the migration there...
> 1275 permission sync fixes

- server/service/src/sync/translations/report.rs
Fixes #1414 
Updates the report translation to include `sub_context` and `argument_schema_id`
> 1381 report translations

- server/repository/src/db_diesel/document_registry.rs
Quick fix for a bug discovered while reviewing #1353 (thanks @mark-prins )
> 1353 db query fix

- server/service/src/sync/program_schemas/hiv_care_encounter_ui_schema.json
Fixes #1441
Add pregnancy section back to HIV Care & Treatment
> Programs / HIV Care & Treatment worflow: "Pregnancy" section missing 

- server/service/src/sync/program_schemas/patient_ui_schema.json
Fixes #1424
Pre-populated options for contact address province and region
> 1424 Address dropdowns 

- server/service/src/programs/schemas/patient.json
- server/service/src/sync/program_schemas/patient.json
- server/service/src/sync/program_schemas/patient_ui_schema.json
Fixes #1426 
Added employment status which contains all the options for occupation and made occupation into a free text field
Go to patient UI to see new fields
> #1426 Add occupation details 

- client/packages/common/src/authentication/AuthContext.tsx
- client/packages/common/src/authentication/api/operations.generated.ts
- client/packages/common/src/authentication/api/operations.graphql
- client/packages/common/src/types/schema.ts
- client/packages/host/src/CommandK.tsx
- client/packages/host/src/components/AppDrawer/AppDrawer.tsx
- client/packages/host/src/components/Navigation/DispensaryNav.tsx
- server/graphql/types/src/types/user.rs
- server/repository/migrations/postgres/2023-03-30-220342_update_store_table_with_store_mode/down.sql
- server/repository/migrations/postgres/2023-03-30-220342_update_store_table_with_store_mode/up.sql
- server/repository/migrations/sqlite/2023-03-30-220349_update_store_table_with_store_mode/down.sql
- server/repository/migrations/sqlite/2023-03-30-220349_update_store_table_with_store_mode/up.sql
- server/repository/src/db_diesel/store_row.rs
- server/repository/src/migrations/templates/add_data_from_sync_buffer/mod.rs
- server/repository/src/migrations/templates/data_and_schema/mod.rs
- server/repository/src/migrations/templates/data_migration/mod.rs
- server/repository/src/migrations/v1_01_01/mod.rs
- server/repository/src/migrations/v1_01_01/remove_sqlite_check/mod.rs
- server/service/src/sync/test/test_data/report.rs
- server/service/src/sync/test/test_data/store.rs
- server/service/src/sync/translations/store.rs
Fixes #1462 
Hides dispensary column in side bar if store is not dispensary, same for cmd+K patient.
Have one store that is dispensary and one a store, swap between the two
or
> 1462 only show dispensary menu when store is a dispensary

- client/packages/system/src/Encounter/ListView/columns.ts
Fixes #1474 
Just removed the columns, not much to it.
> #1474 Remove program-status column

- client/packages/programs/src/JsonForms/common/components/Array/FirstItemArray.tsx
- client/packages/programs/src/JsonForms/common/components/Array/common.tsx
- client/packages/programs/src/JsonForms/common/components/Spacer.tsx
- client/packages/programs/src/JsonForms/components/DateOfBirth.tsx
Fixes #1228 
Adds missing visiblity and disabled behaviour to components that should have them.
There wasn't many :) 
Hasn't really, but should be pretty clear from the context -- only added in a couple of places, and they're all just copied from other components.
> Add missing visible/enabled

- client/packages/programs/src/hooks/usePatientCreateStore.ts
- client/packages/system/src/Patient/PatientView/PatientView.tsx
- server/service/src/programs/program_enrolment/program_schema.rs
- server/service/src/programs/schemas/program_enrolment.json
- server/service/src/sync/init_programs_data.rs
- server/service/src/sync/program_schemas/program_enrolment.json
Fixes #1470 
Defaults all program enrolment statuses to `Active`
See any enrolment form
> 1470 unable to enrol into testing program 

- server/service/src/programs/Programs.md
Part of #1472
Just update the readme...
> Update program permission readme

- client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useStocktakeLineEdit.ts
- client/packages/inventory/src/Stocktake/index.ts
- client/packages/inventory/src/index.ts
Fixes #1492
Corrected an import to fix the resolution error
Try to click on stocktakes
> Fix import in InventoryService

- client/packages/system/src/Patient/PatientView/AddButton.tsx
- client/packages/system/src/Patient/PatientView/AppBarButtons.tsx
- client/packages/system/src/Patient/PatientView/PatientView.tsx
> Disable Add and Print button if patient isn't saved yet

- server/service/src/programs/program_event.rs
- server/service/src/programs/update_program_document.rs
> 1537 program event fixes

- client/packages/common/src/types/schema.ts
- client/packages/system/src/Stock/Components/StockLineForm.tsx
- client/packages/system/src/Stock/api/operations.generated.ts
- client/packages/system/src/Stock/api/operations.graphql
Fixes #1398 
Adds location to stock line
- Have locations at current store
- Edit stock line location
or
> 1398 update location from stock view 

- client/packages/system/src/Item/ListView/ListView.tsx
Fixes #1558 
Add unit to item view
or
> 1558 Add a "Unit" column in Catalog > Items > Items list view 

- client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts
- client/packages/invoices/src/OutboundShipment/DetailView/columns.ts
Fixes #1559
Adds unit to inbound shipment detail view + move outbound shipment unit column after item name
or
> 1559 Add a "Unit" column in Inbound Shipment detailed view 

- server/repository/src/mock/test_requisition_repository.rs
- server/service/src/sync/test/integration/remote/invoice.rs
- server/service/src/sync/test/integration/remote/mod.rs
- server/service/src/sync/test/integration/remote/program_requisition.rs
- server/service/src/sync/test/integration/remote/requisition.rs
- server/service/src/sync/test/integration/remote/test.rs
- server/service/src/sync/test/mod.rs
- server/service/src/sync/test/test_data/program_requisition_settings.rs
- server/service/src/sync/translations/invoice_line.rs
- server/service/src/sync/translations/program_requisition_settings.rs
Fixes #1548 
Integration tests for program requisitions
Run integration tests
or
> 1548 program requisitions   integration + extra tests for program tables 

- client/packages/common/src/ui/components/inputs/TextInput/BasicTextInput.tsx
- client/packages/system/src/Location/ListView/LocationEditModal/LocationEditModal.tsx
Fixes #1382 
Location modal feel
> #1382 location modal window improvement

- server/service/src/requisition/request_requisition/insert_program.rs
Adds todo messages for  #1599 
Nothing really, just helpful hints for who ever works on issue #1599 
N/A
> 1599 todos

- client/packages/common/src/intl/locales/en/inventory.json
- client/packages/common/src/types/schema.ts
- client/packages/common/src/ui/components/inputs/TextInput/InputWithLabelRow.tsx
- client/packages/inventory/src/Stocktake/ListView/CreateStocktakeButton.tsx
- client/packages/system/src/Stock/api/hooks/index.ts
- client/packages/system/src/Stock/api/hooks/line/index.ts
- client/packages/system/src/Stock/api/hooks/line/useSortedStockLines.ts
- client/packages/system/src/Stock/api/hooks/utils/useStockApi.ts
- server/graphql/stocktake/src/mutations/insert.rs
- server/service/src/stocktake/insert.rs
Fixes #1588 
Allows the user to create a master list with items that have stock
Try to create a master list with items that have stock
or
> 1588 stocktake add all item with stock at once

- client/packages/common/src/hooks/useNativeClient/useNativeClient.ts
- client/yarn.lock
Fixes #1607 
The changes made to reduce the bundle size meant that `testing.tsx` was being included in the `electron.ts` compilation. That in turn caused some import errors.
I've imported directly from `lodash` to get around this.
Just `yarn electron:build`
I've upgraded electron & electron-forge in the dependencies PR and changed the config to typescript etc. no need to worry about that now..
> Electron build

- server/android/README.md
@mark-prins you mentioned you had problems to build aarch64 as well. This fixed it for me... Not sure if you had the same problem?
> Add build fix instruction for aarch64 on Linux

- client/packages/electron/forge.config.ts
- client/packages/electron/package.json
- client/yarn.lock
#1242
Fixes the electron build on linux
> Remove MakerDeb and MakerRpm from the electron forge.config.ts

- server/graphql/types/src/types/barcode.rs
- server/repository/src/db_diesel/barcode_row.rs
- server/service/src/requisition/request_requisition/insert_program.rs
Fixes #1620
Auto generate requisition lines if created from a program.
Create a program requisition and see auto generated lines for items in the program's master list.
or
> 1620 program requisitions not pre populated with program items

- client/.eslintrc.js
I had some false positive with the current configuration, hope this is better now...
> Improve liniting for unused vars

- client/packages/common/src/ui/layout/tables/columns/PaginationRow/PaginationRow.test.tsx
- client/packages/common/src/ui/layout/tables/components/Expand/MiniTable.tsx
- client/packages/common/src/ui/layout/tables/context/TableContext.test.tsx
- client/packages/common/src/ui/layout/tables/context/TableContext.tsx
- client/packages/common/src/utils/testing/testing.tsx
- client/packages/inventory/src/Stocktake/DetailView/DetailView.tsx
- client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEdit.tsx
- client/packages/inventory/src/Stocktake/ListView/ListView.tsx
- client/packages/invoices/src/InboundShipment/DetailView/DetailView.tsx
- client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/InboundLineEdit.tsx
- client/packages/invoices/src/InboundShipment/DetailView/modals/InboundServiceLineEdit/InboundServiceLineEdit.tsx
- client/packages/invoices/src/InboundShipment/ListView/ListView.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/DetailView.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEdit.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundServiceLineEdit/OutboundServiceLineEdit.tsx
- client/packages/invoices/src/OutboundShipment/ListView/ListView.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/DetailView.tsx
- client/packages/requisitions/src/RequestRequisition/ListView/ListView.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/DetailView.tsx
- client/packages/requisitions/src/ResponseRequisition/ListView/ListView.tsx
- client/packages/system/src/Item/DetailView/Tabs/MasterLists.tsx
- client/packages/system/src/Item/ListView/ListView.tsx
- client/packages/system/src/Location/ListView/ListView.tsx
- client/packages/system/src/MasterList/DetailView/DetailView.tsx
- client/packages/system/src/MasterList/ListView/ListView.tsx
- client/packages/system/src/Name/ListView/ListView.tsx
- client/packages/system/src/Stock/ListView/ListView.tsx
Fixes #1597 
Fixes the checkbox issues
All thanks to @mark-prins
> #1597 update table store state

- .github/ISSUE_TEMPLATE/bug_report.md
- client/packages/requisitions/src/RequestRequisition/DetailView/Toolbar/Toolbar.tsx
- client/packages/requisitions/src/RequestRequisition/ListView/ListView.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/Toolbar.tsx
- client/packages/requisitions/src/ResponseRequisition/ListView/ListView.tsx
- client/packages/requisitions/src/utils.ts
Fixes #1688 
Just a quick tidy of approval status translation usage. Update the method name, which was not reflecting what it actually did
Offroad:
The issue templates annoy me, having to select and delete text every time is a minor irritation.
How about changing the platform to this:
> Update approval status translation

- client/packages/requisitions/src/RequestRequisition/api/operations.generated.ts
- client/packages/requisitions/src/RequestRequisition/api/operations.graphql
- client/packages/requisitions/src/utils.ts
Fixes #1701
Grey out requisitions that are pending or denied in Requisition View
- Have a pending or denied requisition
- Click on Requisition in sub-menu
- See that requisitions which are pending or denied is greyed out
> 1701 Pending approval response requisition appears as editable in list

- client/packages/common/src/hooks/useEditModal/useEditModal.ts
- client/packages/invoices/src/OutboundShipment/DetailView/AppBarButtons.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/DetailView.tsx
Fixes #1755 
The change from draftItem to a Draft which contains the item has caused an issue with the modal state.
Add an item using the scanner; test that normal usage of adding items and editing items works as expected.
> Allow item selection when barcode scan doesn't match

- client/packages/requisitions/src/RequestRequisition/DetailView/columns.ts
Fixes #1778
Fix approved packs calculation 👀 
or
> 1778 [User Training Feedback] Internal Order: "Approved packs" = "Requested" (units) - calculated field not working 

- server/repository/src/db_diesel/barcode_row.rs
Fixes #
Fix broken barcode test.
Cargo test
> Fix barcode test

- server/service/src/sync/test/integration/remote/location_movement.rs
- server/service/src/sync/translation_and_integration.rs
- server/service/src/sync/translations/location_movement.rs
- server/service/src/sync/translations/mod.rs
Fixes #1446
Just implement a review comment from previous PR...
> Remove unused location_movement delete support

- build/windows/demo/local.yaml
- build/windows/omsupply_server.suf
- build/windows/omsupply_standalone.suf
- client/packages/android/app/src/main/AndroidManifest.xml
- client/packages/android/app/src/main/assets/capacitor.config.json
- client/packages/android/app/src/main/java/org/openmsupply/client/FileManager.java
- client/packages/android/app/src/main/java/org/openmsupply/client/MainActivity.java
- client/packages/android/app/src/main/java/org/openmsupply/client/NativeApi.java
- client/packages/common/src/hooks/useNativeClient/types.ts
- client/packages/common/src/hooks/useNativeClient/useNativeClient.ts
- client/packages/electron/src/electron.ts
- client/packages/electron/src/preload.ts
- client/packages/electron/src/shared.ts
- client/packages/host/src/Admin/LogFileModal.tsx
- client/packages/host/src/components/Android.tsx
- server/configuration/example.yaml
- server/server/src/logging.rs
Fixes #1277
Added a `Save` button which will allow saving of the log to a directory on the tablet.
I've decided not to do the 'email logs' , or all of the other bits. Those will come in when we implement api / ui for all platforms.
https://github.com/openmsupply/open-msupply/assets/9192912/6a816c7d-57f8-4be6-8208-aef5396f192d
Have been using a samsung tablet, creating debug and release builds and testing.
> 1277 log viewer android

- client/package.json
- client/packages/electron/package.json
- client/packages/electron/src/electron.ts
- client/packages/electron/updateElectronVersion.js
- client/packages/system/src/Stock/Components/Repack/RepackEditForm.tsx
- client/packages/system/src/Stock/api/hooks/line/useInsertRepack.ts
- client/packages/system/src/Stock/api/hooks/line/useRepack.ts
- client/packages/system/src/Stock/api/hooks/line/useRepacksByStockLine.ts
Fixes #1685 
Implemented the electron menu, with some shenanigans to get typescript to play ball.
I've also added a wee node script to update the package version for electron, so that the correct version is displayed.
On mac:
On windows:
There's no app / about menu on windows, like there is on mac. A more common paradigm is to have the about on the help menu, so that's what I've done:
The 'about' window looks terrible on windows - it would be possible to implement a much nicer one, using something like the [electron-about-window](https://www.npmjs.com/package/electron-about-window) package. I decided that this is a nicety that we can live without for now.
I built a version of this on the open mSupply demo server, you can see the result if you RDP to that, and look under electron/out
_No …
> Add an electron menu

- client/package.json
- client/packages/android/README.MD
- client/packages/common/src/authentication/AuthContext.tsx
- client/packages/host/src/Site.tsx
- client/packages/system/src/Location/Components/index.ts
- client/packages/system/src/Stock/Components/Repack/RepackEditForm.tsx
- client/packages/system/src/Stock/api/hooks/line/useInsertRepack.ts
- client/packages/system/src/Stock/api/hooks/line/useRepack.ts
- client/packages/system/src/Stock/api/hooks/line/useRepacksByStockLine.ts
Fixes part of #1906 
Some minor tweaks to tidy the feature branch ahead of merging in.
> Tidy features branch

- .gitignore
- README.md
- client/.eslintrc.js
- client/package.json
- client/packages/android/app/src/main/java/org/openmsupply/client/NativeApi.java
- server/docs/content/docs/M1/how_to_m1.md
Closes #1906 
Brings through some of the non-functional changes made in the feature branch.
> Patient programs: non-functional updates

- client/packages/common/src/authentication/api/hooks/useLogin.ts
- client/packages/common/src/hooks/useBreadcrumbs/useBreadcrumbs.tsx
- client/packages/common/src/hooks/useDialog/useDialog.tsx
- client/packages/common/src/hooks/useEditModal/useEditModal.test.tsx
- client/packages/common/src/hooks/useUrlQuery/useUrlQueryParams.ts
- client/packages/common/src/intl/currency/currency.ts
- client/packages/common/src/intl/number/IntlNumber.ts
- client/packages/common/src/intl/utils/DateUtils.ts
- client/packages/common/src/intl/utils/IntlUtils.ts
- client/packages/common/src/styles/RTLProvider.test.tsx
- client/packages/common/src/styles/RTLProvider.tsx
- client/packages/common/src/styles/useAppTheme.ts
- client/packages/common/src/ui/components/buttons/FlatButton/FlatButton.tsx
- client/packages/common/src/ui/components/buttons/standard/ShrinkableBaseButton.tsx
- client/packages/common/src/ui/components/buttons/standard/SplitButton.stories.tsx
- client/packages/common/src/ui/components/modals/BasicModal/BasicModal.tsx
- client/packages/common/src/utils/object/ObjUtils.ts
- client/packages/common/src/utils/regex/RegexUtils.test.ts
- client/packages/common/src/utils/regex/RegexUtils.tsx
- client/packages/host/src/components/Footer/Footer.tsx
- client/packages/host/src/components/Footer/LanguageSelector.tsx
- client/packages/host/src/components/LanguageMenu.tsx
Fixes #1904 
Merging in the common hooks and utils from the programs feature so that we can run a quick functional test in isolation.
Have run unit tests and had a quick run through the site as a whole.
The main change is in the intl usage. Check that the language can be changed and that formatting is working ok.
The query search params have changed, so sorting and filtering would be good to check too.
Breadcrumbs
> Merge common hooks and utils from programs feature

- client/packages/common/src/ui/components/buttons/IconButton/IconButton.tsx
- client/packages/common/src/ui/components/inputs/Autocomplete/Autocomplete.tsx
- client/packages/common/src/ui/components/inputs/DatePickers/BaseDatePickerInput/BaseDatePickerInput.tsx
- client/packages/common/src/ui/components/inputs/DatePickers/DatePickerInput/DatePickerInput.tsx
- client/packages/common/src/ui/components/inputs/SearchBar/SearchBar.tsx
- client/packages/common/src/ui/components/inputs/TextInput/BasicTextInput.tsx
- client/packages/common/src/ui/components/inputs/TextInput/TextInput.stories.tsx
- client/packages/common/src/ui/components/inputs/TextInput/numeric/NonNegativeIntegerInput.tsx
- client/packages/common/src/ui/components/inputs/TextInput/numeric/NonNegativeNumberInput.tsx
- client/packages/common/src/ui/components/inputs/TextInput/numeric/NumericTextInput.tsx
- client/packages/common/src/ui/components/inputs/TextInput/numeric/PositiveNumberInput.tsx
- client/packages/common/src/ui/components/loading/BasicSpinner/BasicSpinner.tsx
- client/packages/common/src/ui/components/navigation/Breadcrumbs/Breadcrumbs.tsx
- client/packages/common/src/ui/components/navigation/Tabs/DetailTabs.tsx
- client/packages/common/src/ui/components/steppers/HorizontalStepper/HorizontalStepper.tsx
- client/packages/common/src/ui/components/steppers/WizardStepper/WizardStepper.tsx
- client/packages/common/src/ui/forms/Detail/InputWithLabelRow.tsx
- client/packages/common/src/ui/icons/Icon.stories.tsx
- client/packages/common/src/ui/icons/MinusCircle.tsx
- client/packages/common/src/ui/icons/User.tsx
- client/packages/common/src/ui/icons/index.ts
- client/packages/common/src/ui/layout/tables/columns/EditableQuantityColumn.tsx
- client/packages/common/src/ui/layout/tables/components/Cells/CheckboxCell/ReadOnlyCheckboxCell.tsx
- client/packages/common/src/ui/layout/tables/components/Cells/CheckboxCell/index.ts
- client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/PositiveNumberInputCell.tsx
- client/packages/common/src/utils/numbers/NumUtils.ts
- client/packages/host/src/Admin/SyncSettings.tsx
Fixes #1905 
Basically just copied these components across too, and checked that tests run, site compiles and app looks ok..
> Feature merge: common components

- client/packages/common/src/hooks/useUrlQuery/useUrlQuery.ts
- client/packages/common/src/hooks/useUrlQuery/useUrlQueryParams.ts
- client/packages/common/src/ui/components/navigation/Tabs/DetailTabs.tsx
- client/packages/programs/src/api/hooks/document/useProgramEnrolments.ts
- client/packages/programs/src/api/hooks/index.ts
- client/packages/system/src/Encounter/ListView/ListView.tsx
- client/packages/system/src/Patient/Encounter/EncounterSearchInput.tsx
- client/packages/system/src/Patient/Encounter/ListView.tsx
- client/packages/system/src/Patient/PatientView/AppBarButtons.tsx
- client/packages/system/src/Patient/PatientView/PatientView.tsx
- client/packages/system/src/Patient/ProgramEnrolment/Components/ListView.tsx
Fixes #1863
Added async to the program mutation... error seems to be gone for me 🤔 
- Enrol patient into program
- Start encounter but don't finish it
- Click out of the encounter creation modal
- Go back to program tab and things should load as expected
> 1863 Database error when viewing Programs tab after starting but not saving a new encounter

- server/service/src/requisition/program_settings/README.md
Fixes #1656
Wasn't sure where to put this, so decided to use the service folder.
https://github.com/openmsupply/open-msupply/blob/1656-program-requisition-internal-documentation/server/service/src/requisition/program_settings/README.md
> Internal docs for program requisition

- client/packages/common/src/types/schema.ts
- client/packages/programs/src/api/api.ts
- client/packages/programs/src/api/hooks/utils/useDocumentRegistryApi.ts
- client/packages/programs/src/api/operations.generated.ts
- client/packages/programs/src/api/operations.graphql
Fixes #1827 
Front end changes for filtering document registries by store
> Frontend changes for filtering document registries

- client/packages/system/src/Patient/CreatePatientModal/CreatePatientModal.tsx
Fixes #1886 (Note the number in the branch name is incorrect, sorry)
This is the super-simple version of this. It simply disables the "Ok & Next" button until something has been entered in either the first or last name fields.
Perhaps this could also allow for the National ID or NUIC fields too? Is it likely that patients would be searched just by either of those?
> #1866 Patient creation search restriction

- server/graphql/programs/src/mutations/program_enrolment/insert.rs
- server/graphql/programs/src/mutations/program_enrolment/update.rs
- server/graphql/programs/src/queries/program_enrolment.rs
- server/repository/src/db_diesel/program_enrolment.rs
Follow up for #1516
This fixes some graphql issues I noticed while working on the import script. There are some more changes coming in https://github.com/openmsupply/open-msupply/issues/1944 so no detailed tested are required at this stage...
> Fix graphql program enrolment endpoints

- server/graphql/batch_mutations/src/batch_prescription.rs
- server/graphql/invoice/src/mutations/prescription/mod.rs
- server/graphql/invoice_line/src/mutations/prescription_line/mod.rs
- server/service/src/invoice/prescription/batch.rs
Fixes #2003
Fixes imports broken in prescription batch PR. Server should run now.
Run server/tests
> 2003 Prescription Batch Merge Fix

- client/packages/common/package.json
- client/packages/programs/package.json
- client/yarn.lock
Closes #1903
Gave up on trying to remove the package. The @jsonforms/material-renderers is expecting the icons package to be included, while not including it.
However, noticed that the icons package was added to common, and should instead be alongside the jsonsforms package, so have moved it to programs.
Have `yarn install` and `yarn build` to check that the f/e still compiles.
> Move dependency

- client/packages/common/src/hooks/useNativeClient/useNativeClient.ts
- client/packages/electron/package.json
- client/packages/electron/webpack.main.config.ts
- client/packages/host/package.json
- client/packages/host/src/components/AuthenticationAlert.tsx
- client/packages/requisitions/src/RequestRequisition/api/operations.generated.ts
- client/packages/system/src/Patient/ListView/ListView.tsx
- client/packages/system/src/Sync/api/operations.generated.ts
- client/yarn.lock
- server/graphql/batch_mutations/src/batch_prescription.rs
- server/graphql/invoice/src/lib.rs
- server/graphql/invoice/src/mutations/prescription/mod.rs
- server/graphql/invoice_line/src/lib.rs
- server/graphql/invoice_line/src/mutations/prescription_line/mod.rs
Fixes #2027 
The recent changes have resulted in additional aliased imports being required of `useNativeClient` and this has the effect of breaking the desktop build.
To resolve - I've implemented the `TsconfigPathsPlugin` which we have already used in the host build, which adds in all the alias values from tsconfig. Currently there is only one alias added to the webpack config and this is no longer sufficient.
Along the way I regenerated the graphql codegen, and then fixed the resulting output. As part of the generation, I noticed warnings with the server build, so have fixed those too.
Test that the electron build works. 
> Fix desktop build

- server/repository/src/migrations/mod.rs
- server/repository/src/migrations/v1_02_00/context_table.rs
Thanks Andrei! Will merge this in.
> Repository free migrations

- server/service/src/sync/test/integration/central/document_registry.rs
- server/service/src/sync/test/integration/remote/program_requisition.rs
- server/service/src/sync/translations/document.rs
- server/service/src/sync/translations/document_registry.rs
Fixes #1944
Updates integration tests
- Setup central server from latest mSupply `develop` branch
- Run integration tests
The tests were a bit flaky in that there were constant problems with the hardware id not matching. I didn't manage to run all integration test though... any idea why? (document and document_registry run through though)
> 1944 update sync translations

- .gitignore
- server/.gitignore
"___template_needs_update.marker" files in various test_output dirs should be ignored. Move the entry to the server/.gitignore file
> Move ___template_needs_update.marker to correct .gitignore file

- build/windows/omsupply-build.bat
- build/windows/omsupply_demo.suf
Fixes #2069 
The sqlite exe name has been changed, but the demo suf file hadn't been update.
Updated the suf file on jenkins and ran build.
You can do this - run manually on jenkins, or simply add a tag starting with 'v' to any branch and push to origin.
> Correct the sqlite exe name in the demo build

- server/graphql/programs/src/mutations/patient/insert.rs
- server/graphql/programs/src/mutations/patient/update.rs
- server/graphql/programs/src/mutations/program_patient/insert.rs
- server/graphql/programs/src/mutations/program_patient/update.rs
- server/service/src/programs/encounter/insert.rs
- server/service/src/programs/encounter/update.rs
- server/service/src/programs/patient/mod.rs
- server/service/src/programs/patient/patient_updated.rs
- server/service/src/programs/patient/update_patient.rs
- server/service/src/programs/patient/upsert_program_patient.rs
- server/service/src/programs/program_enrolment/upsert.rs
Fixes https://github.com/openmsupply/open-msupply/issues/2023
This was partially started in an earlier PR but I missed a few case :-( No functional changes just renames of service methods.
> Fix missing patient / program_patient service method renames

- client/packages/common/src/ui/components/inputs/DatePickers/BaseDatePickerInput/BaseDatePickerInput.tsx
Fixes #2153 
The actual issue has already been resolved, but only in the `develop` branch, which is why the demo server isn't seeing the fix.
Just because I looked at it, I've added the fix done - which is a different approach to the current fix. I've used the `DateUtils` as that is already handling string/null/invalid dates - so the usage is simpler and it keeps logic in a single place.
Add an expiry date to a row in an inbound shipment, then try to edit the row. Demo server will throw an error, this version will not.
> Inbound shipment row - expiry date error

- client/packages/system/src/Patient/DefaultPatientUISchema.json
Fixes #2165 
Make the generic patient gender selection look less angry... 
**Don't have programs set up.** 
Found this while fixing transgender bug... was quick fix so 🤷🏻
> 2165 Nicely format text for generic patient creation 

- client/packages/common/src/hooks/useDialog/useDialog.tsx
- client/packages/common/src/hooks/useNativeClient/types.ts
- client/packages/common/src/ui/components/inputs/Switch/Switch.tsx
- client/packages/common/src/ui/components/popover/ClickPopover/ClickPopover.tsx
- client/packages/common/src/ui/components/popover/HoverPopover/HoverPopover.tsx
- client/packages/common/src/ui/components/popover/PaperPopover/index.ts
- client/packages/common/src/ui/forms/Detail/NumericTextDisplay.tsx
- client/packages/common/src/ui/layout/tables/components/DataRow/DataRow.stories.tsx
- client/packages/common/src/utils/testing/testing.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/modals/TaxEdit.tsx
- client/packages/programs/src/JsonForms/common/JsonForm.tsx
- client/packages/programs/src/JsonForms/common/components/Array/Notes.tsx
- client/packages/programs/src/JsonForms/common/components/CategorizationTabLayout.tsx
- client/packages/programs/src/JsonForms/components/AdherenceScore.tsx
- client/packages/programs/src/JsonForms/components/Search/SearchWithDocumentSource.tsx
- client/packages/programs/src/JsonForms/components/Search/SearchWithUserSource.tsx
- client/packages/programs/src/JsonForms/components/Search/useSearchQueries.tsx
- client/packages/system/src/Item/Components/StockItemSelectModal/StockItemSelectModal.tsx
> Fix some any warnings

- server/cli/src/refresh_dates.rs
get_timestamp_fields entry was missing...
> Fix test postgres tests

- client/packages/system/src/Patient/Components/PatientOptionRenderer/PatientOptionRenderer.tsx
Fixes #2182 
Displays birthdate in patient search modal.
> Display birth date in patient search

- client/packages/common/src/ui/components/domain/Dashboard/StatsPanel.tsx
- client/packages/common/src/ui/components/navigation/AppNavLink/AppNavLink.tsx
Fixes #2222 
Found another couple of minor things to update with the theme. Have targeted main, so that I can update the demo server with the changes.
- The hover text colour of the left hand nav links can now be updated
- the icons on the dashboard now use the secondary colour, not a hard-coded blue
Check the current theme on the demo server. Hover text should be black, and the icon colour on the dashboard orange.
> Update theme again

- client/packages/common/src/hooks/useUrlQuery/useUrlQueryParams.ts
- client/packages/system/src/Encounter/ListView/ListView.tsx
- client/packages/system/src/Encounter/ListView/columns.ts
- client/packages/system/src/Patient/Encounter/ListView.tsx
Fixes #2204 
Fix encounter list sorting issue
1. Go to Dispensary>Encounters
2. Try to sort the encounters list
> 2204 Fix encounter list sorting issue

- client/packages/programs/src/JsonForms/common/components/Date.tsx
Fixes #2220 
Fixes patient search with invalid date of birth value
Follow the reproduce steps in its issue
> 2220 Fix patient search with invalid dob

- server/service/src/stocktake/insert.rs
> Change stocktake date

- server/repository/src/db_diesel/program_event_row.rs
- server/service/src/programs/program_event.rs
Fixes #3221
Add a test case for failing real world setup and provide a fix.
- Run tests
- Optional revert fix and check "bad" output in the database
> Add program event test + fix

- client/packages/system/src/Encounter/DetailView/DetailView.tsx
- client/packages/system/src/Patient/Encounter/ListView.tsx
Fixes #2295 
Fix encounter list record sorting
- Goto Encounter list > click any patient
- Then click that patient back from the breadcrumb link at the left top to back to the encounter list
- No any errors will show up
> 2295 Fix encounter list sorting error

- server/repository/src/db_diesel/temperature_breach_config.rs
- server/service/src/temperature_breach_config/tests/query.rs
> Fix sort order for sqlite/postgres

- server/graphql/types/src/types/activity_log.rs
- server/repository/src/db_diesel/activity_log_row.rs
- server/repository/src/migrations/v1_05_00/activity_log.rs
- server/repository/src/migrations/v1_05_00/mod.rs
- server/repository/src/migrations/v1_05_00/permissions_preferences.rs
- server/service/src/sensor/update.rs
Fixes #2277
Logs change to sensor location
> 2277 Add ability to upsert sensor location and log location changes 

- client/packages/coldchain/src/Monitoring/ListView/TemperatureBreach/TemperatureBreachList.tsx
- client/packages/coldchain/src/Monitoring/ListView/TemperatureLog/TemperatureLogList.tsx
- client/packages/coldchain/src/Monitoring/api/TemperatureLog/hooks/document/useTemperatureLogs.ts
- client/packages/coldchain/src/Sensor/ListView/ListView.tsx
- client/packages/coldchain/src/Sensor/api/hooks/document/useSensors.ts
- client/packages/common/src/hooks/useQueryParams/types.ts
- client/packages/common/src/hooks/useQueryParams/useQueryParamsStore.tsx
- client/packages/common/src/hooks/useUrlQuery/useUrlQueryParams.ts
- client/packages/inventory/src/Stocktake/api/hooks/document/useStocktakes.ts
- client/packages/invoices/src/InboundShipment/ListView/ListView.tsx
- client/packages/invoices/src/InboundShipment/api/hooks/document/useInbounds.ts
- client/packages/invoices/src/OutboundShipment/api/hooks/document/useOutbounds.ts
- client/packages/invoices/src/Prescriptions/api/hooks/document/usePrescriptions.ts
- client/packages/requisitions/src/RequestRequisition/ListView/ListView.tsx
- client/packages/requisitions/src/RequestRequisition/api/hooks/document/useRequests.ts
- client/packages/requisitions/src/ResponseRequisition/ListView/ListView.tsx
- client/packages/requisitions/src/ResponseRequisition/api/hooks/document/useResponses.ts
- client/packages/system/src/Item/ListView/ListView.tsx
- client/packages/system/src/Item/api/hooks/useItems/useItems.ts
- client/packages/system/src/MasterList/ListView/ListView.tsx
- client/packages/system/src/MasterList/api/hooks/document/useMasterLists.ts
- client/packages/system/src/Patient/ListView/ListView.tsx
- client/packages/system/src/Patient/ListView/Toolbar.tsx
- client/packages/system/src/Report/ListView/ListView.tsx
- client/packages/system/src/Stock/ListView/ListView.tsx
- client/packages/system/src/Stock/api/hooks/line/useStockLines.ts
Fixes #2386
Implement the date filters and allow filtering with multiple keys and conditions. Some code from HSH
- Go to Patient
- Try the different filters available
> 2386 implement date and number filter in frontend

- client/packages/plugins/README.md
- decisions/version-compatibility.md
Fixes #2372
A readme for the plugin framework, and development process. And some offroads - minor spelling updates in another readme
> 2372 plugins readme

- client/README.md
Fixes #0
Always getting confused about the client package hierarchy, so I thought I add some notes about it so that I can look it up...
> Add some notes about the client package hierarchy

- server/graphql/sensor/src/mutations/update.rs
- server/repository/src/db_diesel/temperature_breach.rs
- server/repository/src/db_diesel/temperature_breach_row.rs
- server/server/src/cold_chain/mod.rs
- server/server/src/cold_chain/temperature_breach.rs
- server/service/src/sensor/update.rs
- server/service/src/temperature_breach/insert.rs
- server/service/src/temperature_breach/mod.rs
- server/service/src/temperature_breach/update.rs
- server/service/src/temperature_breach/validate.rs
Fixes #2362 
Adds the endpoint which allows breaches to be upserted.
You can create a `PUT` request in postman and try to post this as a body:
```
[
{
"id": "04318dd6-ec0a-437d-b031-21153f4b96a0",
"sensorId": "824f2b4a-efbd-4f7b-87e9-7a036abbf50f",
"startTimestamp": 1697594730,
"acknowledged": true,
"thresholdMaximumTemperature": 5,
"thresholdMinimumTemperature": 4,
"thresholdDuration": 0,
"type": "HOT_CONSECUTIVE"
}
]
```
You can also point a tablet to your oms server. The logs will tell you if there's a problem, and you can check the database to see if breaches have been inserted successfully.
remember to login first if testing with postman (or similar).
The tablet will handle login - you may have to run the server with your local IP though - I'm using my IP as the `host` config entry.
> 2362 api temperature breach

- client/.eslintrc.js
- client/packages/common/src/hooks/useDeleteConfirmation/useDeleteConfirmation.ts
- client/packages/common/src/intl/context/IntlContext.tsx
- client/packages/common/src/ui/components/menus/DropdownMenu/DropdownMenu.stories.tsx
- client/packages/common/src/ui/layout/tables/DataTable.tsx
- client/packages/common/src/utils/types/TypeUtils.ts
- client/packages/electron/src/keyboardScanner/keyboardScanner.ts
- client/packages/electron/updateElectronVersion.js
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEdit.tsx
- client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/PrescriptionLineEdit.tsx
- server/util/src/to_inline_init.js
Fixes #2427
Adds the `no-console` lint option and updates code 
Try to commit a change which has 'console.log' in it
> add linter option

- client/packages/host/src/Host.tsx
- client/packages/system/src/Item/context/useUnitVariant.ts
> Suggestion

- client/packages/common/src/hooks/useUrlQuery/useUrlQueryParams.ts
- client/packages/common/src/utils/formatters/formatters.test.ts
- client/packages/common/src/utils/formatters/formatters.ts
Fixes #2438
Brings in Roxy's change from #2429 into v1.5.0
Try to filter cold chain info by date
> Return iso string to api for timezones + fix tests

- client/packages/coldchain/src/Sensor/Components/SensorLineForm.tsx
- client/packages/system/src/Location/Components/LocationSearchInput.tsx
Fixes #2426 
Reviewed - and the issue isn't an issue in develop now.
This PR is to remove the option which removes the removal option 😜 
Remove location should be available and working for 
- Stock lines
- Repacks
- Sensors
> Update LocationSearchInput props

- client/packages/programs/src/JsonForms/components/Search/SearchWithUserSource.tsx
- client/packages/programs/src/JsonForms/components/Search/usePatientSearchQuery.tsx
- client/packages/programs/src/schema_types.ts
> Add a PatientSchema type

- client/packages/android/app/src/main/java/org/openmsupply/client/NativeApi.java
- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/ui/discovery/DiscoveredServers.tsx
- client/packages/electron/src/electron.ts
- client/packages/host/package.json
- client/packages/host/src/components/Sync/ServerInfo.tsx
- client/packages/host/src/components/Sync/Sync.tsx
- client/yarn.lock
Fixes #2479
Displays the current server URL in text and QR format on the sync page, to allow for simpler setup of the cold chain app sync:
**Browser**
**Android**
**Desktop**
I also tried using the [qrcode.react](https://github.com/zpao/qrcode.react) package so that I could embed the mSupply guy as an image in the QR code, but the QR (even without the image) was being read less reliably, so have used the [react-qr-code](https://www.npmjs.com/package/react-qr-code) package
I've had to tweak the server discovery for android so that it returns an IP which isn't the loopback IP, as per:
Have run the site in various modes:
- website (develop)
- website (hosted by server)
- android (client)
- android (server)
- desktop (mac, client)
Have checked that the QR code can be read using my phone and a …
> Show server URL & QR

- client/packages/common/src/ui/components/domain/Dashboard/StatsPanel.tsx
- client/packages/common/src/ui/components/domain/Dashboard/Widget.tsx
- client/packages/host/src/components/AppBar/AppBar.tsx
Fixes #1684
Changes dashboard to display better in cramped screens when the app bar is open
Open dashboard with a small screen (1024px wide laptop) 
Some inline comments
> 1684 refactor dashboard styline

- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/ui/components/navigation/AppNavLink/AppNavLink.tsx
- client/packages/host/src/components/AppDrawer/AppDrawer.tsx
Fixes #1834 
Adds confirmation modal to navLink for logout button
> 1834 logout confirmation

- server/service/src/programs/program_event.rs
Fixes #2560 
Fixes a program event bug and adds a test case for the failing setup.
Also refactor the existing tests to use a new `events()` helper method where possible.
Run test, with and without fix
> 2560 program event remove stack fix

- server/graphql/stocktake_line/src/mutations/insert.rs
- server/graphql/stocktake_line/src/mutations/update.rs
- server/repository/src/db_diesel/stocktake_line.rs
- server/repository/src/db_diesel/stocktake_line_row.rs
- server/repository/src/migrations/v1_06_00/mod.rs
- server/repository/src/migrations/v1_06_00/stocktake_line_add_item_link_id.rs
- server/service/src/stocktake/update.rs
Fixes #2551
Add `item_link_id` to stocktake line repos... didn't see any views that used stocktake lines....
> 2551 item merging stock take line

- client/packages/android/app/src/main/java/org/openmsupply/client/NativeApi.java
Fixes #2500 
A last minute change in a previous PR added a `finally` block - turns out that the finally is _always_ executed, so in this case, the server IP is always resolved to `127.0.0.1`
After removing the `finally` it's working fine
> Server IP resolution

- client/packages/common/src/intl/currency/currency.test.tsx
- client/packages/common/src/intl/utils/IntlUtils.ts
- client/packages/common/src/styles/ThemeProvider.tsx
- client/packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.test.ts
Fixes #2640 
Fixes the tests - two issues due to the plugin framework changes:
- The syntax of the import of mui ThemeProvider
- changes to i18n which weren't re-rendering the language as it should have been
Running tests with `yarn test` - all will pass now.
> Fix front end tests

- server/repository/src/db_diesel/clinician.rs
- server/repository/src/db_diesel/clinician_link_row.rs
- server/repository/src/db_diesel/clinician_row.rs
- server/repository/src/db_diesel/clinician_store_join_row.rs
- server/repository/src/db_diesel/mod.rs
- server/repository/src/migrations/v1_06_00/clinician_link.rs
- server/repository/src/migrations/v1_06_00/clinician_store_join_add_clinician_link_id.rs
- server/repository/src/migrations/v1_06_00/indexes.rs
- server/repository/src/migrations/v1_06_00/mod.rs
Fixes #2454
- Create clinician_link table
- Add `clinician_link_id` to clinician_store_join
- Make sure tests are still working
> 2454 clinician merging clinician link, clinician store join and clinician

- server/repository/src/db_diesel/program_requisition/program_supplier.rs
- server/service/src/requisition/program_settings/mod.rs
Fixes #2671
Fix broken tests was fixed in another branch but that's heading to the feature branch...
Run both sqlite and postgres tests to make sure they're still running
> 2671 Fix tests

- client/packages/common/src/ui/layout/tables/utils/ColumnUtils.test.ts
- client/packages/common/src/ui/layout/tables/utils/ColumnUtils.ts
- client/packages/common/src/ui/layout/tables/utils/index.ts
- client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts
- client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts
- client/packages/invoices/src/OutboundShipment/DetailView/columns.ts
- client/packages/invoices/src/Prescriptions/DetailView/columns.ts
Fixes #2651
As part of this, I was concerned at the amount of boilerplate used in column definitions, so I've added a couple of helpers, which has simplified the column code.
Check that the data tables in these areas are still displaying correctly:
- Stocktake : Detail view
- Inbound Shipment : Detail view
- Outbound Shipment : Detail view
- Prescriptions : Detail view
There is a lot more that could be done to simplify the column generation. This change will at least reduce duplication of logic and makes field selection much easier.
> Add column helpers

- client/.eslintrc.js
Fixes #2441 
That's odd, I thought that I'd already done this 🤷 
or
> Warn on dependencies for hooks

- server/server/src/upload_fridge_tag.rs
Fixes #2696 
Handles (valid) rename error case.
Have the feeling there must be a method or crate for it but couldn't find it and it was easy to implement...
Fridge tag upload should still work when upload temp dir and app_data directory are on the same mountpoint/device.
> Copy fridge tag file if rename failed

- server/repository/src/db_diesel/clinician_link_row.rs
- server/repository/src/db_diesel/encounter.rs
- server/repository/src/db_diesel/encounter_row.rs
- server/repository/src/migrations/v1_06_00/encounter_add_clinician_link_id.rs
- server/repository/src/migrations/v1_06_00/indexes.rs
- server/repository/src/migrations/v1_06_00/mod.rs
Fixes #2565
- Adds clinician_link_id to encounter 
- Make sure tests still work
> 2565 Clinician merging: encounter

- client/packages/coldchain/src/Monitoring/ListView/TemperatureBreach/TemperatureBreachList.tsx
Fixes #2678
Displays the comment column.
I thought perhaps to rename the column to 'Acknowledgement comment' but that felt clumsy, and then the name is also different to the modal where the field is called 'comment'. So it's just comment.
Best to piggy back on #2692 and test this after testing that.
It adds a new column, worth checking to see if this is visible in documentation screenshots and if the list of columns is in the docs, in which case add this column too please.
> added comment column

- server/repository/src/db_diesel/name_link_row.rs
- server/repository/src/db_diesel/stock_line.rs
- server/repository/src/db_diesel/stock_line_row.rs
- server/repository/src/migrations/v1_06_00/mod.rs
- server/repository/src/migrations/v1_06_00/stock_line_add_supplier_link_id.rs
Fixes #2682
Supplier link id for stock line
Run tests
> 2682 Name merging: stock_line.supplier_id

- server/service/src/sync/translations/invoice_line.rs
Fixes #2635 
Translate invoice_line.item_link_id to item_id when pushing sync
Just automated tests
> 2635 invoice_line.item_link_id translation and tests

- server/repository/src/db_diesel/barcode_row.rs
- server/repository/src/migrations/v1_06_00/barcode_add_manufacturer_link_id.rs
- server/repository/src/migrations/v1_06_00/mod.rs
- server/service/src/sync/test/test_data/barcode.rs
Fixes #2684
manufacturer_link_id for barcode... Didn't join the name_link table with barcode to add filters since it's not being used right now... 
Run tests
> 2684 name merging barcode.manufacturer

- server/repository/src/db_diesel/name_link_row.rs
- server/repository/src/db_diesel/patient.rs
- server/repository/src/db_diesel/program_enrolment.rs
- server/repository/src/db_diesel/program_enrolment_row.rs
- server/repository/src/migrations/v1_06_00/indexes.rs
- server/repository/src/migrations/v1_06_00/mod.rs
- server/repository/src/migrations/v1_06_00/patient_id_indices.rs
- server/repository/src/migrations/v1_06_00/program_enrolment_add_patient_link_id.rs
- server/repository/src/migrations/v1_06_00/requisition_line_add_item_link_id.rs
- server/repository/src/migrations/v1_06_00/stock_line_add_supplier_link_id.rs
Fixes #2732
patient_link_id for program enrolments
Run tests
> 2732 Name merging: program_enrolments.patient_id

- client/packages/coldchain/src/Monitoring/ListView/TemperatureBreach/Toolbar.tsx
Fixes #2707
Displays the unacknowledged toggle by default on the breach list view
or
> Default unacknowledged toggle

- server/graphql/general/src/queries/temperature_chart.rs
Fixes #2708
Iterate over the chart data and for points that have a breach associated, use the breach max_or_min temperature instead of the averaged temperature value.
This allows breach indicators to show the 'correct' value i.e. the value which you see when viewing the breach. If there isn't a breach, then the averaging behaves as normal.
I also tried increasing the number of datapoints - going up to 300 ( 24h of data, with 5 min logging interval = 288 data points ) displays the breaches correctly using the example data given.. but is incredibly slow. too slow to use.
So, I went with option 2. This is fast enough, and has minimal impact. Looks even better when combined with the fix for #2711 as well:
You might find it useful to test with the omsupply_vaccine.zip sqlite file which is in …
> Show the breach temperature as the point temperature

- server/graphql/general/src/queries/temperature_chart.rs
Fixes #2711
Filters out breach ids which have already been added to the chart - so that we only see the first instance of a breach on the chart.
To test - you might find this database helpful: `omsupply_vaccines.zip` in [this google drive folder](https://drive.google.com/open?id=1e7475Z9J-j1KnferOQOrcYSSTnFp9wtk&usp=drive_fs)
If you login to the Rural Pharmacy using Admin user, you should see this:
> Display unique breaches on temperature chart

- server/repository/src/merging.md
My current understanding of how merging and link tables work, so this might be a bit wrong...
> Start some merging docs

- build/windows/omsupply_demo.suf
- build/windows/omsupply_desktop.suf
- build/windows/omsupply_server.suf
- build/windows/omsupply_standalone.suf
Fixes #2737
Sets the install path to be the currently installed location, if an upgrade is detected.
- Install a previous version into a non-standard folder. 
- Install this version: you should see the upgrade process and it will detect the current folder
> Detect path when running an upgrade

- client/packages/common/src/ui/components/inputs/Filters/DateFilter.tsx
- client/packages/common/src/ui/components/inputs/Filters/EnumFilter.tsx
- client/packages/common/src/ui/components/inputs/Filters/NumberFilter.tsx
- client/packages/common/src/ui/components/inputs/Filters/TextFilter.tsx
- client/packages/common/src/ui/components/inputs/Filters/styleConstants.ts
Part of #2382
Just a bit of refactoring to pull filter text sx to common source and re-use
> Unify filter sx

- server/repository/src/db_diesel/barcode_row.rs
- server/repository/src/db_diesel/clinician_link_row.rs
- server/repository/src/db_diesel/clinician_row.rs
- server/repository/src/db_diesel/encounter.rs
- server/repository/src/db_diesel/encounter_row.rs
- server/repository/src/db_diesel/item_row.rs
- server/repository/src/db_diesel/location_row.rs
- server/repository/src/db_diesel/master_list_line_row.rs
- server/repository/src/db_diesel/master_list_name_join.rs
- server/repository/src/db_diesel/master_list_row.rs
- server/repository/src/db_diesel/name_link_row.rs
- server/repository/src/db_diesel/name_row.rs
- server/repository/src/db_diesel/name_store_join.rs
- server/repository/src/db_diesel/name_tag_join.rs
- server/repository/src/db_diesel/period/period_row.rs
- server/repository/src/db_diesel/program_enrolment_row.rs
- server/repository/src/db_diesel/program_requisition/program_row.rs
- server/repository/src/db_diesel/stock_line_row.rs
- server/repository/src/migrations/v1_06_00/encounter_add_patient_link_id.rs
- server/repository/src/migrations/v1_06_00/mod.rs
- server/service/src/sync/integrate_document.rs
Fixes #2735 
patient_link_id for encounters
Run tests
> 2735 name merging encounters.patient

- client/packages/coldchain/src/Monitoring/api/TemperatureNotification/hooks/document/useTemperatureNotifications.ts
Fixes #2762 
Commit was not pushed 🙄 
or
> MILLISECONDS > MS

- server/graphql/types/src/types/barcode.rs
- server/repository/src/db_diesel/barcode.rs
- server/service/src/sync/translations/barcode.rs
Fixes #2767
Pushes correct name.id for barcode
Run tests
> Name merging barcode.manufacturer id translator get actual name.id

- server/service/src/sync/translations/clinician_store_join.rs
Fixes #2769
Pushes correct clinician id
... there's actually no mock data for clinician... there are plenty of tests for the other push merges, but lemme know if you want me to create some mock data and add the test (:
> Clinician merging: clinician_store_join.clinician_id translator get actual clinician.id

- server/repository/src/db_diesel/clinician_link_row.rs
- server/repository/src/mock/clinician.rs
- server/repository/src/mock/mod.rs
- server/service/src/sync/test/mod.rs
- server/service/src/sync/translation_and_integration.rs
- server/service/src/sync/translations/mod.rs
- server/service/src/sync/translations/special/clinician_merge.rs
- server/service/src/sync/translations/special/mod.rs
Fixes #2771 
Adds clinician merge message translator/handler
- Run tests
> 2771 clinician merging handle clinician merge sync messages

- package.json
- server/repository/src/db_diesel/contact_trace_row.rs
- server/repository/src/db_diesel/document.rs
- server/repository/src/migrations/mod.rs
- server/repository/src/migrations/v1_07_00/document_owner_name_link_id.rs
- server/repository/src/migrations/v1_07_00/mod.rs
- server/service/src/sync/translations/document.rs
Fixes #2754
Implements merge support for document.owner_link_id
Starts a new 1.7 migration folder, can revert if you don't want to do it yet...
> Update document owner_name_link_id

- server/repository/src/db_diesel/name_store_join.rs
- server/repository/src/db_diesel/program_requisition/program_supplier.rs
- server/repository/src/db_diesel/store_row.rs
- server/repository/src/mock/name_store_join.rs
- server/repository/src/mock/test_name_query.rs
- server/repository/src/mock/test_name_store_id.rs
- server/service/src/invoice/inbound_shipment/insert/mod.rs
- server/service/src/invoice/inbound_shipment/update/mod.rs
- server/service/src/invoice/outbound_shipment/insert/mod.rs
- server/service/src/invoice/outbound_shipment/update/mod.rs
- server/service/src/invoice/outbound_shipment/update_name/mod.rs
- server/service/src/invoice/prescription/insert/mod.rs
- server/service/src/programs/patient/patient_updated.rs
- server/service/src/requisition/program_settings/mod.rs
- server/service/src/requisition/request_requisition/update/test.rs
- server/service/src/sync/test/test_data/name_store_join.rs
- server/service/src/sync/test/test_data/special/name_to_name_store_join.rs
- server/service/src/sync/translations/name_store_join.rs
Part of #2759
Mostly just test updates + trivial changes
> Rename name_link_id for NameStoreJoinRow

- server/repository/src/db_diesel/item.rs
- server/repository/src/db_diesel/master_list_name_join.rs
- server/repository/src/db_diesel/name_tag_join.rs
- server/repository/src/db_diesel/program_requisition/program_requisition_settings.rs
- server/repository/src/db_diesel/program_requisition/program_supplier.rs
- server/repository/src/mock/full_master_list.rs
- server/repository/src/mock/name_tag.rs
- server/repository/src/mock/test_master_list_repository.rs
- server/repository/src/tests.rs
- server/service/src/dashboard/item_count.rs
- server/service/src/invoice/inbound_shipment/add_from_master_list.rs
- server/service/src/invoice/outbound_shipment/add_from_master_list.rs
- server/service/src/requisition/program_settings/mod.rs
- server/service/src/requisition/request_requisition/add_from_master_list.rs
- server/service/src/sync/test/test_data/master_list_name_join.rs
- server/service/src/sync/test/test_data/name_tag_join.rs
- server/service/src/sync/translations/master_list_name_join.rs
- server/service/src/sync/translations/name_tag_join.rs
Part of #2759
Mainly test updates...
> Rename name_link_id for NameTagJoinRow and MasterListNameJoinRow

- .github/ISSUE_TEMPLATE/refactor.md
Adds a template for refactoring issues.
Also comes with an associated wiki page - https://github.com/msupply-foundation/open-msupply/wiki/Refactoring
Very open to feedback and improvement here!
Hopefully this is a good first cut...
I've tried to include the examples inside the template but maybe better to have some more examples elsewhere?
> Refactor issue template

- server/graphql/core/src/loader/requisition_line.rs
- server/graphql/core/src/loader/requisition_supply_status.rs
- server/graphql/requisition/src/mutations/request_requisition/add_from_master_list.rs
- server/graphql/requisition/src/mutations/request_requisition/use_suggested_quantity.rs
- server/graphql/requisition/src/mutations/response_requisition/supply_requested_quantity.rs
- server/graphql/requisition/src/query_tests/requisition_loaders.rs
- server/graphql/requisition_line/src/mutations/request_requisition_line/insert.rs
- server/graphql/requisition_line/src/mutations/request_requisition_line/update.rs
- server/graphql/requisition_line/src/mutations/response_requisition_line/update.rs
- server/graphql/types/src/types/requisition_line.rs
- server/repository/src/db_diesel/changelog/test.rs
- server/repository/src/db_diesel/requisition_line/requisition_line.rs
- server/repository/src/db_diesel/requisition_line/requisition_line_row.rs
- server/repository/src/mock/test_remaining_to_supply.rs
- server/repository/src/mock/test_requisition_line_repository.rs
- server/repository/src/mock/test_requisition_queries.rs
- server/repository/src/mock/test_requisition_service.rs
- server/service/src/item_stats.rs
- server/service/src/processors/transfer/requisition/create_response_requisition.rs
- server/service/src/processors/transfer/requisition/test.rs
- server/service/src/requisition/request_requisition/add_from_master_list.rs
- server/service/src/requisition/request_requisition/generate.rs
- server/service/src/requisition/requisition_supply_status.rs
- server/service/src/requisition_line/chart/mod.rs
- server/service/src/requisition_line/request_requisition_line/insert.rs
- server/service/src/requisition_line/response_line_stats/mod.rs
- server/service/src/requisition_line/response_line_stats/response_line_stats.rs
- server/service/src/sync/test/test_data/requisition_line.rs
- server/service/src/sync/translations/requisition_line.rs
> Rename item_link_id for requisition lines

- client/packages/common/src/styles/theme.ts
- client/packages/host/src/components/Login/LoginLayout.tsx
Fixes #2877
I had to add this in order to make a demo theme look nice. Just a minor tweak to allow specifying the `background-size` property on the login screen LHS
You can try with the custom theme in [this folder](https://drive.google.com/open?id=1IBM2SmyfQQdRzh341CXONX4rk7Bl6QjZ&usp=drive_fs)
> Add option for login layout background image size

- server/graphql/types/src/types/program/encounter.rs
- server/repository/src/db_diesel/encounter.rs
- server/repository/src/db_diesel/encounter_row.rs
- server/service/src/programs/encounter/encounter_fields.rs
- server/service/src/programs/encounter/encounter_updated.rs
- server/service/src/programs/encounter/update.rs
- server/service/src/sync/integrate_document.rs
Fixes #2840 and #2843
action bump2
> 2840 link column rename encounter

- server/graphql/core/src/loader/program_enrolment.rs
- server/graphql/types/src/types/program/program_enrolment.rs
- server/repository/src/db_diesel/patient.rs
- server/repository/src/db_diesel/program_enrolment.rs
- server/repository/src/db_diesel/program_enrolment_row.rs
- server/service/src/programs/encounter/insert.rs
- server/service/src/programs/program_enrolment/program_enrolment_updated.rs
- server/service/src/programs/program_enrolment/upsert.rs
- server/service/src/sync/integrate_document.rs
> Rename patient_link_id for ProgramEnrolmentRow

- server/repository/src/db_diesel/clinician.rs
- server/repository/src/db_diesel/clinician_store_join_row.rs
- server/service/src/invoice/prescription/update/mod.rs
- server/service/src/sync/translations/clinician_store_join.rs
> Rename clinician_link_id for ClinicianStoreJoinRow

- server/architecture.md
Fixes #2858 
Add some docs about the backend layers. Question: is there a better place/dir to put these files? There are a couple of files scattered throughout the repo...
> Add some more docs about the used backend layers

- client/packages/common/package.json
- client/packages/common/src/intl/utils/DateUtils.test.ts
- client/packages/common/src/intl/utils/DateUtils.ts
- client/packages/common/src/utils/formatters/formatters.test.ts
- client/packages/programs/src/JsonForms/common/components/Date.tsx
- client/packages/programs/src/JsonForms/components/DateOfBirth.tsx
- client/yarn.lock
Adds hotfix from [2912](https://github.com/msupply-foundation/open-msupply/pull/2922/files) to develop
> #2912 hot fix

- server/repository/src/migrations/v1_08_00/assets/asset_catalogue_item.rs
- server/service/src/auth.rs
Fixes #2995 
Create some placeholder permissions so that we can consume them when making the graphQL changes.
Just check that it looks ok
> Create permissions for assets

- server/service/src/sync/test/test_data/barcode.rs
Fixes #3031
Added the `parentID` to the legacy barcode test data.
`cargo test --package service --lib -- sync::translations::barcode::tests::test_barcode_translation --exact --nocapture`
`cargo test --package service --lib -- sync::test::pull_and_push::test_sync_pull_and_push --exact --nocapture`
or, wait for the github test action to run 😉 
> Fix barcode tests

- client/packages/coldchain/src/Monitoring/ListView/TemperatureBreach/TemperatureBreachList.tsx
- client/packages/coldchain/src/Monitoring/ListView/TemperatureBreach/Toolbar.tsx
- client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/useTemperatureChartData.ts
- client/packages/coldchain/src/Monitoring/ListView/TemperatureLog/TemperatureLogList.tsx
- client/packages/coldchain/src/Monitoring/ListView/TemperatureLog/Toolbar.tsx
- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/intl/locales/es/common.json
- client/packages/inventory/src/Stocktake/ListView/CreateStocktakeButton.tsx
- client/packages/system/src/Location/ListView/Toolbar.tsx
- client/packages/system/src/Stock/ListView/ListView.tsx
- client/packages/system/src/Stock/ListView/Toolbar.tsx
Fixes #3040
Change location filters to filter by code instead of name
or
> 3040 Location filter is for location name, but the code is shown in the list view

- server/server/src/lib.rs
> Comment out middleware

- client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEdit.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditTable.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/columns.ts
- server/Cargo.lock
Fixes #3230
FC sell price column was moved in Outbound Shipments with PV merge. Have moved it back
> 3230 Currency tweeks

- server/service/src/invoice/inbound_return/generate_lines.rs
> use Consolidate generating inbound line

- client/packages/coldchain/src/Equipment/Components/Status.tsx
- client/packages/coldchain/src/Equipment/Components/index.ts
- client/packages/coldchain/src/Equipment/ListView/ListView.tsx
- client/packages/coldchain/src/Equipment/api/operations.generated.ts
- client/packages/coldchain/src/Equipment/api/operations.graphql
- client/packages/common/src/intl/locales/en/coldchain.json
- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/styles/theme.ts
- client/packages/common/src/types/schema.ts
- client/packages/common/src/utils/types/TypeUtils.ts
- server/graphql/asset/src/types.rs
- server/graphql/core/src/loader/asset_status.rs
- server/graphql/core/src/loader/loader_registry.rs
- server/graphql/core/src/loader/mod.rs
- server/repository/src/db_diesel/assets/asset_log.rs
- server/repository/src/db_diesel/assets/asset_log_row.rs
- server/repository/src/migrations/v1_08_00/assets/asset_log.rs
- server/repository/src/migrations/v1_08_00/assets/latest_asset_log.rs
- server/repository/src/migrations/v1_08_00/assets/mod.rs
Fixes #3140 
Adds a loader to get the current status of an asset and shows the status in the equipment list like this:
For this, I've manually created asset logs which are associated to my equipment. Alternatively, you could wait until the next PR if you want to have the UI for adding, or use the API directly.
_Part of the CCEI feature_
> Equipment list to show Status

- client/packages/invoices/src/Returns/api/hooks/line/useGenerateInboundReturnLines.ts
- client/packages/invoices/src/Returns/modals/InboundReturn/useDraftInboundReturnLines.ts
Slotting in as part of #3170 👍
> more direct data call

- server/repository/src/migrations/v1_07_00/changelog_add_name_link_id.rs
- server/repository/src/migrations/v1_07_00/name_store_join_add_name_link_id.rs
Fixes #3279
Add missing name_store_join triggers
Run tests and make sure everything migrates/runs properly
> Triggers for name store join

- client/packages/coldchain/src/Equipment/DetailView/DetailView.tsx
- client/packages/coldchain/src/Equipment/DetailView/Tabs/StatusLogs.tsx
- client/packages/coldchain/src/Equipment/DetailView/Tabs/Summary.tsx
- client/packages/coldchain/src/Equipment/api/api.ts
- client/packages/coldchain/src/Equipment/api/hooks/index.ts
- client/packages/coldchain/src/Equipment/api/hooks/log/index.ts
- client/packages/coldchain/src/Equipment/api/hooks/log/useAssetLogs.ts
- client/packages/coldchain/src/Equipment/api/operations.generated.ts
- client/packages/coldchain/src/Equipment/api/operations.graphql
- client/packages/coldchain/src/Equipment/utils.ts
- client/packages/common/src/intl/locales/en/coldchain.json
- client/packages/common/src/types/schema.ts
- client/packages/common/src/ui/icons/Icon.stories.tsx
- client/packages/common/src/ui/icons/UserCircle.tsx
- client/packages/common/src/ui/icons/index.ts
Fixes #2985 
Fills out the `Status Logs` tab, and also adds the `Log` tab for the activity log.
Create some status logs and see if they are visible.
Part of the asset / CCEI feature
> Asset logs list

- client/packages/common/src/types/schema.ts
- client/packages/invoices/src/Returns/InboundDetailView/Footer/OnHoldButton.tsx
- client/packages/invoices/src/Returns/InboundDetailView/Footer/StatusChangeButton.tsx
- client/packages/invoices/src/Returns/InboundListView/ListView.tsx
- client/packages/invoices/src/Returns/api/api.ts
- client/packages/invoices/src/Returns/api/hooks/document/index.ts
- client/packages/invoices/src/Returns/api/hooks/document/useUpdateInboundReturn.ts
- client/packages/invoices/src/Returns/api/hooks/index.ts
- client/packages/invoices/src/Returns/api/operations.generated.ts
- client/packages/invoices/src/Returns/api/operations.graphql
- server/graphql/invoice/src/lib.rs
- server/graphql/invoice/src/mutations/inbound_return/mod.rs
- server/graphql/invoice/src/mutations/inbound_return/update.rs
- server/repository/src/mock/invoice.rs
- server/repository/src/mock/invoice_line.rs
- server/service/src/invoice/inbound_return/mod.rs
- server/service/src/invoice/inbound_return/update/generate.rs
- server/service/src/invoice/inbound_return/update/mod.rs
- server/service/src/invoice/inbound_return/update/validate.rs
- server/service/src/invoice/mod.rs
- server/service/src/invoice/outbound_return/update/generate.rs
Fixes #3185
Adds the `updateInboundReturn` mutation. Wires up the status/onHold/colour changes from frontend too.
Automated tests in the service layer.
- From the Inbound Return list view
- From the detail view
See inline comments
> 3185 update inbound return

- client/packages/common/src/types/schema.ts
- client/packages/invoices/src/Returns/InboundDetailView/AppBarButtons.tsx
- client/packages/invoices/src/Returns/OutboundDetailView/AppBarButtons.tsx
- server/graphql/reports/src/reports.rs
- server/repository/src/db_diesel/report_row.rs
- server/repository/src/migrations/v1_08_00/mod.rs
- server/repository/src/migrations/v1_08_00/return_context_types.rs
- server/service/src/report/default_queries.rs
Fixes #3190
- Adds print button to outbound return detail view
- Adds new report context types for returns
I've created a bit of a dummy report template... how best to share? SQL insert statement?
Not sure how much time to spend on this right now - the basics are in place that if someone wanted to create a returns report, they could. 
However, the Invoice DefaultQuery is probably insufficient... I'd imagine you would want to include return reasons in a returns report! I think for this, we'd need to create a return_reasons loader, against the return_reason_id on the invoice resolver. Should this be done now, or wait until someone decides they want this report?
Also, how _do_ we load new reports into the central server?
> 3190 print returns

- server/graphql/asset/src/lib.rs
- server/graphql/asset/src/mutations/insert.rs
- server/service/src/asset/tests/insert.rs
- server/service/src/asset/tests/update.rs
> Fix broken backend tests

- server/Makefile.toml
- server/README.md
Adds the cargo watch script I was playing with from last RnD day to omSupply repo 😎 
Install global deps if required, then run `cargo make watch` from the `server` directory.
Make some backend file changes, the server should restart.
Current server should be available until new version has been compiled.
> RnD cargo watch

- server/Cargo.lock
- server/repository/src/db_diesel/changelog/changelog.rs
- server/repository/src/db_diesel/mod.rs
- server/repository/src/db_diesel/sync_file_reference_row.rs
- server/repository/src/migrations/v1_08_00/mod.rs
- server/repository/src/migrations/v1_08_00/sync_file_reference.rs
- server/server/Cargo.toml
- server/server/src/middleware/content_length_limit.rs
- server/server/src/middleware/mod.rs
- server/server/src/static_files.rs
- server/service/src/report/report_service.rs
- server/service/src/static_files.rs
Fixes #3164
Allows uploading files to server which will be registered for sync.
Each file is associated with a `table_name` and `record_id` which the sync process will use to determine where the files should be synced to/from.
This PR doesn't include any of the sync code, this will be a later PR.
A new endpoint is available which has this structure...
`/sync_files/{table_name}/{record_id}`
To get an uploaded file you can call
http://{YOURSERVERURL}:{YOURPORT}/sync_files/{table_name}/{record_id}?id={FILE_ID}
To upload a file you need to use a multipart upload.
In Postman this looks something like this...
This will return the uploaded file id.
Right now we don't have any security implemented on this.
Thinking maybe should look at https://github.com/msupply-foundation/open-msupply/issues/3002 …
> 3164 file uploads backend

- client/packages/system/src/MasterList/api/api.ts
- server/graphql/general/src/queries/master_list.rs
- server/graphql/general/src/queries/tests/master_lists.rs
- server/repository/src/db_diesel/master_list.rs
- server/repository/src/mock/full_master_list.rs
- server/service/src/master_list/mod.rs
- server/service/src/master_list/query.rs
- server/service/src/master_list/tests/query.rs
- server/service/src/stocktake/insert.rs
Fixes #
Reverts the master list changes pushed to 1.7 since issue was created from an old version. Was unnecessary and can't find master lists for other stores. 
or
> Revert master list changes

- client/packages/common/src/utils/environment/EnvUtils.ts
- client/packages/system/src/Clinician/ClinicianSearchInput.tsx
- client/packages/system/src/Patient/Components/PatientSearchInput/PatientSearchInput.tsx
Fixes #3589
Add doc paths for sync, admin, patients, encounter and prescriptions
> Update doc links #3589

- server/service/src/sync/test/test_data/invoice.rs
- server/service/src/sync/translations/invoice.rs
Fixes #3609
Also improves the error log message
> Handle invoice status "FN" and "fn"

- server/service/src/sync/translations/requisition.rs
Fixes #3576
Please ask for used datafile if you want to test.
> Handle requisition status "nw"

- server/repository/src/db_diesel/assets/asset_catalogue_item_property.rs
- server/repository/src/db_diesel/assets/asset_catalogue_item_property_row.rs
- server/repository/src/db_diesel/assets/asset_catalogue_property.rs
- server/repository/src/db_diesel/assets/asset_catalogue_property_row.rs
- server/repository/src/db_diesel/assets/mod.rs
- server/repository/src/db_diesel/changelog/changelog.rs
- server/repository/src/migrations/v2_00_00/assets/asset_catalogue_data.rs
- server/repository/src/migrations/v2_00_00/assets/asset_catalogue_properties.rs
- server/repository/src/migrations/v2_00_00/assets/mod.rs
- server/service/src/sync/test/test_data/asset_catalogue_item_property.rs
- server/service/src/sync/test/test_data/asset_catalogue_property.rs
- server/service/src/sync/test/test_data/mod.rs
- server/service/src/sync/translations/asset_catalogue_item.rs
- server/service/src/sync/translations/asset_catalogue_item_property.rs
- server/service/src/sync/translations/asset_catalogue_property.rs
- server/service/src/sync/translations/mod.rs
Fixes #3474
Adds the catalogue property and catalogue item property tables. 
Adds the data as a migration step.
includes the tables in sync from central - required if new catalogue items are imported with properties attached.
* Ran tests
* Ran the migration on a new database (pg + sqlite)
* Tested on an existing database
The property and item property tables should be populated and linked to catalogue items.
> Asset catalogue item properties

- server/cli/src/refresh_dates.rs
- server/service/src/sync/test/test_data/invoice_line.rs
- server/service/src/sync/translations/invoice_line.rs
Fixes #3611 
Ignores bad optionId data.
> Ignore bad optionID = "0" when translating invoice_lines

- server/service/src/sync/translations/invoice.rs
- server/service/src/sync/translations/invoice_line.rs
- server/service/src/sync/translations/mod.rs
- server/service/src/sync/translations/stock_line.rs
- server/service/src/sync/translations/stocktake_line.rs
- server/service/src/sync/translations/utils.rs
Fixes #3620
Validate location/barcode ids for invoice_line, stock_line and stocktake_line
I only fixed cases that I noticed in real datafiles, there might be other location_id references as well, could do them later...
> 3620 validate location barcode ids

- decisions/2024-03-18_central_server_code_base.md
Sorry no link to an issue, this has been talked about in a few meeting and in dev process chat:
Resources:
https://github.com/msupply-foundation/open-msupply-internal/discussions/47
https://github.com/msupply-foundation/open-msupply-internal/discussions/48
> KDD central server codebase

- server/service/src/sync/translations/invoice.rs
- server/service/src/sync/translations/utils.rs
Part of #2620
I was too quick merging my previous PR before @mark-prins finished his review. This contains his suggestions.
> Fix spelling

- server/graphql/Cargo.toml
Enables postgres feature from graphql crate for graphql_reports crate when feature flag is set
1.
2.
> Feature control for reports

- client/packages/host/src/CommandK.tsx
Fixes #3522
Changed logout key to `l, o` LogOut? >.>
1.
2.
> 3522 Shortcut key for master list g+m will logged you out

- decisions/2024-04-15_decimal_pack_size.md
Fixes #3618 
Read the [KDD](https://github.com/msupply-foundation/open-msupply/blob/3618-decimal-pack-size-kdd/decisions/2024-04-15_decimal_pack_size.md), agree, suggest changes, make yer case!
High priority! This is a long term blocker for Team Tauhou working on migrating from legacy systems.
> #3618 decimal pack size kdd

- client/packages/common/src/ui/layout/tables/components/Header/Header.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEdit.tsx
Fixes #3531
Fixes pack variants translations in outbound and prescription line edit 
1.
2.
> 3531 Translations breaking

- server/service/src/sync/central_data_synchroniser_v6.rs
- server/service/src/sync/remote_data_synchroniser.rs
- server/service/src/sync/synchroniser.rs
Fixes #3692
Well actually I already had a PR to fix #3692 (this one #3720) but then I realised after the fact that the remote data synchroniser was in fact not a great place to do v6 related things from, so here I am moving it :)
See #3720 for test
1.
2.
> advance v6 cursor from v6 synchroniser

- server/repository/src/migrations/v2_00_00/sync_file_reference.rs
Followup on #3706 
Add error handling. Still have a couple of warnings in this branch and missed this one...
> 3706 handle error

- server/repository/src/db_diesel/program_event.rs
- server/repository/src/migrations/v2_00_00/sync_file_reference.rs
- server/repository/src/mock/document.rs
- server/repository/src/tests.rs
- server/server/src/cold_chain/temperature_breach.rs
- server/server/src/cold_chain/temperature_log.rs
- server/service/src/document/document_service.rs
- server/service/src/programs/program_event.rs
- server/service/src/sync/central_data_synchroniser_v6.rs
- server/service/src/sync/integrate_document.rs
- server/service/src/sync/translations/name.rs
- server/service/src/sync/translations/requisition.rs
- server/service/src/temperature_excursion.rs
Cleanup of #2881 
Fix all warning, mostly from chrono but some that I believe existed in the develop branch before.
> Fix warnings

- client/packages/coldchain/src/Equipment/ListView/ListView.tsx
- client/packages/coldchain/src/Equipment/ListView/Toolbar.tsx
- client/packages/coldchain/src/Equipment/api/api.ts
- client/packages/coldchain/src/Equipment/api/hooks/document/useAssets.ts
- client/packages/common/src/types/schema.ts
- client/packages/system/src/Stock/api/operations.generated.ts
- server/graphql/asset/src/types.rs
- server/repository/src/db_diesel/assets/asset.rs
- server/repository/src/db_diesel/assets/asset_log.rs
- server/repository/src/db_diesel/assets/asset_log_row.rs
- server/repository/src/db_diesel/assets/asset_row.rs
- server/repository/src/db_diesel/diesel_schema.rs
Fixes #3741
Adds sorting for `store` and `asset number` to equipment and as a bonus a `functional status` filter too~
https://github.com/msupply-foundation/open-msupply/assets/61820074/3ff2cba3-987a-4170-92b9-2d0762c6ba7c
1. Possibly screenshots? idk
2.
> 3741 cannot sort the list in equipment table

- server/service/src/programs/encounter/encounter_updated.rs
Part of #3624
This was an actual bug. When encounters are deleted the events are removed correctly now.
Our test machines are actually too fast and this test only failed if there was some slowdown, i.e. when test stretches from one millisecond to the next millisecond.
I added some hard-coded timestamps now to simulate a couple of test-cases.
> Fix encounter updated test

- client/package.json
- client/packages/common/src/ui/components/inputs/DatePickers/BaseDatePickerInput/BaseDatePickerInput.tsx
- client/yarn.lock
Fixes #2926
Update mui-x-datepickers dependancy... doesn't seem to be any breaking changes. Has been changes to the popper so no longer have to fix it into position since popper behaves differently now 👀 
Maybe good to test on desktop app too since that's having the most trouble 👀 
1.
2.
> 2926 Datepicker moves if it is to close to the edge

- client/packages/common/src/ui/components/navigation/Tabs/DetailTab.tsx
- client/packages/common/src/ui/layout/tables/DataTable.tsx
- client/packages/inventory/src/Stocktake/DetailView/ContentArea/ContentArea.tsx
Fixes #3869
Brings in the changes from #3837
and check that the pagination component is full screen width and overlays the table
1.
2.
> Pagination side scrolling

- server/service/src/print/label.rs
Fixes #3889
On re-reading the zebra ZPL language spec, the field data requires error correction and character encoding values:
It would appear that the first couple of characters are being taken as flags and discarded from the content.
1.
2.
> Adjust QR code command

- server/repository/src/db_diesel/changelog/changelog.rs
Fixes #3624
The failing postgres tests were actually caused by a real bug! This bug could result in completely ignoring entries from the change log when the cursor was advanced too early...
To investigate the failing transfer tests, I printed out which cursors have been handled by the processor and the latest cursor of the failing transfer requisition row was not handled.
Also note that the test where only failing in Postgres. Postgres default isolation level is Read Committed (Serializable in Sqlite).
The failing tests are running independent test cases in parallel. This is what could have happened:
1) Process 1 adds to the changelog (cursor 1)
2) Process 1 finishes tx (cursor 1 becomes visible)
3) Process 2 adds to the changelog (cursor 2) but takes longer than to finish the tx
5) …
> Lock changelog table when retrieving changelogs (postgres)

- client/packages/common/src/utils/environment/EnvUtils.ts
Fixes #3954
Adds doc links
1.
2.
> 3954 Link to documentation broken

- package.json
Bumps package json for patch release
> bump package json version

- server/repository/src/migrations/v2_00_00/mod.rs
main was merged back into develop - no conflicts but this param wasn't caught 😅
> run_without_change_log_updates compilation fix

- server/service/src/sync/test/test_data/store.rs
- server/service/src/sync/translation_and_integration.rs
- server/service/src/sync/translations/document_registry.rs
- server/service/src/sync/translations/invoice.rs
- server/service/src/sync/translations/invoice_line.rs
- server/service/src/sync/translations/master_list_name_join.rs
- server/service/src/sync/translations/report.rs
- server/service/src/sync/translations/requisition.rs
- server/service/src/sync/translations/special/name_to_name_store_join.rs
- server/service/src/sync/translations/stocktake.rs
- server/service/src/sync/translations/store.rs
Fixes #3606
Displays the ignored message in sync buffer since it's only currently being logged in the logs which might not be enabled for a lot of devs XD. 
1.
2.
> 3606 sync buffer integration error show when item was ignored

- package.json
Bump version for patch release
> bump version for v2.0.2

- client/tsconfig.json
Part of #2154
Wanted to get this in since very guilty of doing this when switching from backend to frontend 👀 
Pending: Imports - not working so will look into it later when more time
1.
2.
> 2154 Linter rule for const and warning for indirect external package imports

- project-words.txt
- server/cli/src/refresh_dates.rs
- server/repository/src/migrations/v2_01_00/assets/asset_catalogue_data.rs
- server/repository/src/migrations/v2_01_00/assets/asset_property_data.rs
- server/repository/src/migrations/v2_01_00/assets/mod.rs
- server/service/src/catalogue/tests/query_catalogue_item.rs
Fixes #3866
Fixes #3929
Fixes #3866
Adds the asset properties that can be entered for Cold Rooms & Fridge Freezers
For the catalogue items we also need to add new properties but thinking I might leave them till after re-factoring those? 
For Cold Rooms we need 
- Energy source
- Refrigerant type(s)
- 
See
> 3866 add support for registering new cce category cold rooms and freezer rooms

- client/packages/invoices/src/OutboundShipment/DetailView/ContentArea.tsx
- client/packages/invoices/src/Returns/OutboundDetailView/ContentArea.tsx
Fixes #3989
From https://github.com/msupply-foundation/open-msupply/pull/4025#issuecomment-2146649142 for main
1.
2.
> 3989 Outbound shipment detail view column headers not fixed #4025

- package.json
Bump version for patch release
> Patch release v.2.0.3

- server/repository/src/test_db/postgres.rs
> Fix Postgres test warnings

- server/repository/src/mock/context.rs
- server/repository/src/mock/program.rs
Fix Postgres tests
I guess we should add the forgein key constraint to Sqlite as well though...
> Add missing immunisation context + refactor

- server/repository/src/migrations/v2_01_00/activity_log.rs
- server/repository/src/migrations/v2_01_00/program.rs
- server/service/src/program/insert_immunisation.rs
- server/util/src/constants.rs
Fixes postgres tests with the immunisation program work
Went with a single context for now, for all immunisations.
We could add something in the future around parent programs in context but for now keeping it simple.
`cargo test --features=postgres`
1.
2.
> Bug fix postgres tests

- client/packages/system/src/Report/ListView/ListView.tsx
Fixes #4082
Increase the column width (requested by @louisaw123 )
Also fixes some warnings.
> Fix report name column width + fix warnings

- server/service/src/demographic/insert_demographic_indicator.rs
- server/service/src/demographic/update_demographic_indicator.rs
- server/service/src/demographic/validate.rs
Fixes #4101
Updates verbose check to same pattern used in immunisation programs.
This is a validation check refactor only to match existing patterns
> Update demographic_indicator validation checks

- server/service/src/sync/test/test_data/name_oms_fields.rs
Fixes push and pull test - sorry didn't run after final changes 😭 
Just needed to reference an existing name in the mock data 
1.
2.
> fix test data for name_oms_fields

- client/packages/common/src/intl/locales/en/coldchain.json
- client/packages/common/src/types/schema.ts
- client/packages/system/src/Immunisation/ImmunisationProgramDetailView/ImmunisationProgramDetailView.tsx
- client/packages/system/src/Immunisation/ImmunisationProgramDetailView/VaccineCourseCreateModal.tsx
- client/packages/system/src/Immunisation/ListView/ImmunisationProgramCreateModal.tsx
- client/packages/system/src/Immunisation/ListView/ListView.tsx
- client/packages/system/src/Immunisation/api/hooks/useImmunisationProgram.ts
- client/packages/system/src/Immunisation/api/operations.generated.ts
- client/packages/system/src/Immunisation/api/operations.graphql
- server/graphql/programs/src/mutations/immunisation/insert.rs
Fixes #4125
Various fixes for Immunization programs/vaccine courses creatiom UI
- handling name already exists error when creating immunisation programs
- clearing inputs on modal close
- fixing the name of the create vaccine course modal
- Go to programs -> Immunizations
- Click `New Program`
- Type something in the name
- Click cancel
- Click `New Program` again
- TEST: Input has cleared
- Create an Immunization program
- Try to create another one with the same name
- TEST: you see error text under the input that the program already exists
- Click on one of the programs
- Click `Add new vaccine course`
- TEST: modal title is now "Add new vaccine course"
- Type something in the name
- Click cancel
- Click `Add new vaccine course` again
- TEST: Input has cleared
1.
2.
> 4125 Immunization programs create UI fixes

- server/repository/src/migrations/mod.rs
- server/repository/src/migrations/templates/add_data_from_sync_buffer/mod.rs
- server/repository/src/migrations/templates/adding_table/mod.rs
- server/repository/src/migrations/templates/data_and_schema/mod.rs
- server/repository/src/migrations/templates/data_migration/mod.rs
- server/repository/src/migrations/v1_07_00/mod.rs
- server/repository/src/migrations/v2_00_00/mod.rs
Fixes #4173
This is a very dev focussed PR, but fixes a bug where migrations fail due to additional columns being added just during test migrations (examples)
I've moved the examples to be included in the main migration list.
Some of the examples (particularly the sync mapping one could probably be updated to be clearer, or maybe they could all be entirely removed as real world examples now exist?)
1. Delete your template databases (rm __* in `repository/test_output/`)
2. Run `cargo test --package repository --lib -- migrations::v2_01_00 --show-output`
3. See tests failed before and now pass
1.
2.
> Remove conditional test migrations from migration list

- build/mac/open_msupply_server.sh
- server/README.md
- server/server/src/configuration.rs
- server/service/src/sync/test/integration/README.md
Fixes #4187
See commits
Try with `APP_` <- config does not apply
Try with `APP__` <- config applies
> 4187 Add config env variable override to docs and build script

- client/packages/host/src/api/hooks/settings/namePropertyData.ts
Fixes #4165 
Adds new options for gas and kerosene
1.
2.
> Update GAPS Enums for Gas and Kerosene

- client/packages/common/src/ui/components/portals/AppFooter/AppFooter.tsx
Fixes #3827
Removes the 0 padding on footer container
1. Do you want to be pedantic? Go through all the screenshots 🤣 
2.
> 3827 Footer being real cosy with nav

- client/packages/common/src/utils/environment/EnvUtils.ts
Adds links to the docs + the little tab window titles for demographics and immunisations pages :)
1.
2.
> add page title/docs links for gaps pages

- client/packages/common/src/utils/environment/EnvUtils.ts
MIssed a link fix in yesterday's changes 😁 Administration has changed to `Settings`
1.
2.
> administration -> settings

- client/packages/common/src/intl/locales/en/coldchain.json
Fixes #4205
Changed wording of enabled for gaps calculations checkbox:
1. Update vaccine course detail view screenshots - they're still showing the dose schedule so need redoing anyway
2.
> 4205 vaccine course enabled wording

- client/packages/system/src/IndicatorsDemographics/DetailView/AppBarButtons.tsx
- client/packages/system/src/IndicatorsDemographics/DetailView/GrowthRow.tsx
- client/packages/system/src/IndicatorsDemographics/DetailView/IndicatorsDemographics.tsx
- client/packages/system/src/IndicatorsDemographics/DetailView/utils.tsx
- client/packages/system/src/IndicatorsDemographics/api/hooks/document/useDemographicProjection.ts
- client/packages/system/src/IndicatorsDemographics/api/hooks/document/useDemographicProjections.ts
Fixes #4171
Cleans up a number of `as [Type]` usages throughout the Demographics page
1.
2.
> 4171 remove as type usage

- .github/workflows/client-tests.yaml
Fixes #4104
This adds an action which runs the client tests on the creation of a PR which affects the `/client` folder
I've tested in a copy of the repo made in my personal GH account.
You can clone the open-msupply repo and create a PR to see it in action. And/or run the action manually .
Should be no impact on process flow or development, this is an informational item which runs and displays the status of f/e testing only, as per the other actions.
1.
2.
> add client tests action

- client/packages/system/src/Asset/ImportCatalogueItem/UploadTab.tsx
Fixes #4215
Removes duplicates from asset catalogue import csv
1.
2.
> 4215 asset import template has duplicates

- server/repository/src/db_diesel/changelog/changelog.rs
- server/service/src/sync/test/integration/central/name_and_store_and_name_store_join.rs
- server/service/src/sync/test/integration/central/unit_and_item.rs
- server/service/src/sync/test/integration/errors.rs
- server/service/src/sync/test/integration/remote/clinician.rs
- server/service/src/sync/test/integration/remote/patient_name_and_store_and_name_store_join.rs
- server/service/src/sync/test/integration/remote/program_requisition.rs
- server/service/src/sync/test/integration/remote/requisition.rs
- server/service/src/sync/test/integration/remote/stocktake.rs
Fixes integration tests from 2.1 changes
1.
2.
> Fix integration tests

- server/repository/src/migrations/v2_01_00/store_add_name_link_id.rs
Fixes #4238
Hmmm * (all records) was causing a migration error for store_mode, so have stated what needs inserting.
1.
2.
> 4238 Can't upgrade from 2.0.3 to 2.1

- client/packages/host/src/api/hooks/settings/namePropertyData.ts
Fixes #4231
Fixes typo in facility properties
1.
2.
> 4231 fix properties typo

- server/service/src/stocktake/update.rs
Fixes #3935
When you add lines to a stocktake, if you don't enter a counted number of packs for that line, it will be pruned when you finalise. However, if you changed other batch information on that line, the stock like was being updated!
This PR prevents changes being made to stock lines from stocktake lines that haven't been counted.
1.
2.
> 3935 prevent update of stock line when counted packs is none

- client/packages/system/src/IndicatorsDemographics/DetailView/utils.tsx
Fixes #4356
Fixes mapping of demographic indicator rows - values were being displayed in the wrong columns
1.
2.
> 4356 map demographic data to correct columns

- client/packages/coldchain/src/Monitoring/ListView/TemperatureBreach/TemperatureBreachList.tsx
- client/packages/coldchain/src/Monitoring/ListView/TemperatureLog/TemperatureLogList.tsx
- client/packages/coldchain/src/Sensor/ListView/ListView.tsx
- client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.tsx
- client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
- client/packages/requisitions/src/RequestRequisition/ListView/ListView.tsx
- client/packages/requisitions/src/ResponseRequisition/ListView/ListView.tsx
- client/packages/system/src/Immunisation/ImmunisationProgramDetailView/ImmunisationProgramDetailView.tsx
Fixes #4381 
Fixes the accessor for the target demographic. 
Went on a bit of a rampage after that, and 'tidied' a few other accessors while checking for other problems.
1.
2.
> Show the target demographic

- server/service/src/cold_chain/query_temperature_breach.rs
Fixes #3033
Provides a min or max temperature for an excusion breaches.
If the excursion contains record above and below the limits, the last min or max will be taken.
I don't think these are really used but does solve at least one potential reason for missing the min/max value.
This doesn't directly address the concerns in the original issue as this wasn't for excursion events.
However, as per Roxy's investigation the temperature_log row are missing from the database in these cases.
I haven't been able to recreate that with my setup, and there have been a number of improvements to both CCA and OMS to reduce the chance of this happening since.
Most importantly:
https://github.com/msupply-foundation/open-msupply/pull/2913
But also: …
> Add min/max for excursions

- client/packages/host/src/components/Navigation/ProgramsNav.tsx
- client/packages/programs/src/RnRForms/ListView/ListView.tsx
- client/packages/programs/src/utils.ts
Fixes #4510
Adds status to RnR form list view
This follows the same pattern as in other parts of the app (ie outbound shipments)
1.
2.
> 4510 add status to rn r form

- server/Cargo.lock
- server/service/Cargo.toml
- server/service/src/report/report_service.rs
Fixes #4514
Change crate to scraper. Scraper had an update last week with the changes that fix the error.
1.
2.
> 4514 Export to excel crashes server with DEBUG log level

- client/packages/reports/src/DetailView/AppBarButton.tsx
Fixes #4590
Disable export on android
1.
2.
> 4590 Disable export button on Android

- client/packages/requisitions/src/RnRForms/DetailView/RnRFormLine.tsx
Fixes #4602 
Just rounds the display values. 
The AMC part is already handled - the confusion may have come about because the period length was 3mo in one of the examples.
1.
2.
> Round numbers when displayed in R&R forms

- server/service/src/sync/settings.rs
- server/service/src/sync/sync_on_central/mod.rs
Fixes #4614 
Bump sync version so remote site on v2.2.0+ will get an error syncing to central <v2.2.0 (as we added R&R forms to sync API):
1. Update required versions matrix
> 4614 update v6 sync version

- server/graphql/types/src/types/program/rnr_form_line.rs
- server/repository/src/db_diesel/rnr_form_line.rs
- server/repository/src/db_diesel/rnr_form_line_row.rs
- server/repository/src/migrations/v2_02_00/fix_rnr_form_line_columns.rs
- server/repository/src/migrations/v2_02_00/mod.rs
- server/repository/src/mock/rnr_form.rs
- server/service/src/rnr_form/finalise.rs
- server/service/src/rnr_form/generate_rnr_form_lines.rs
- server/service/src/rnr_form/tests/generate_rnr_form_lines.rs
- server/service/src/rnr_form/tests/insert.rs
- server/service/src/rnr_form/tests/update.rs
- server/service/src/rnr_form/update.rs
- server/service/src/sync/test/test_data/rnr_form_line.rs
Fixes #4596
Removes reference constraint on requisition_line_id 
item_id -> item_link_id
1.
2.
> 4596 fix R&R form line reference columns

- client/packages/system/src/ContactTrace/DetailView/DetailView.tsx
Fixes #4380
Fixes perpetual render causing app crash on the contact trace page
Maybe should sneak this into 2.2? 
1.
2.
> 4380 fix contact trace page crashing

- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/columns.ts
- client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/columns.ts
Fixes #4601
Make expiry cell bigger
1.
2.
> 4601 Expiry dates are not readable in the issue stock window

- client/packages/common/src/types/schema.ts
- client/packages/system/src/Stock/Components/Ledger/useLedgerColumns.ts
- client/packages/system/src/Stock/api/operations.generated.ts
- client/packages/system/src/Stock/api/operations.graphql
- server/graphql/general/src/queries/ledger.rs
- server/repository/src/db_diesel/ledger.rs
- server/repository/src/migrations/views/mod.rs
Fixes #4072
Add invoice number to ledger
1. ledger 
2.
> 4072 add 'invoice number' column to ledger view

- client/packages/invoices/src/Prescriptions/DetailView/ContentArea.tsx
- client/packages/invoices/src/Returns/CustomerDetailView/ContentArea.tsx
Fixes #3926
Scrollbar at the bottom in detail view for prescriptions and customer returns
1.
2.
> 3926 Scrollbar is not fixed in outbound & prescription window

- server/Cargo.lock
- server/Cargo.toml
Fixes #4694
As per commit: 
https://docs.rs/reqwest/latest/reqwest/index.html#optional-features
`gzip: Provides response body gzip decompression.`
This should be very safe and I did test for Android build.
If test is needed, i would suggest checking earlier version of Android app, checking how much mobile data is used, re-initialising and check again with this version of the app, also re-initialisng and check and compare mobile data usage
1.
2.
> 4694 Enable gzip in reqwest

- server/cli/src/test_connection.rs
- server/service/src/sync/settings.rs
- server/service/src/sync/test/test_data/master_list.rs
- server/service/src/sync/test/test_data/program_requisition_settings.rs
- server/service/src/sync/translations/program_requisition_settings.rs
Fixes #4652
Translates is_immunisation from mSupply 
You will need this mSupply branch: https://github.com/msupply-foundation/msupply/pull/15168
1.
2.
> 4652 translate is immunisation program

- server/repository/src/db_diesel/item.rs
- server/repository/src/db_diesel/master_list_line_row.rs
- server/repository/src/migrations/v2_02_02/master_list_line.rs
- server/repository/src/migrations/v2_02_02/mod.rs
- server/repository/src/mock/full_master_list.rs
- server/repository/src/tests.rs
- server/service/src/dashboard/item_count.rs
- server/service/src/invoice/inbound_shipment/add_from_master_list.rs
- server/service/src/invoice/outbound_shipment/add_from_master_list.rs
- server/service/src/requisition/request_requisition/add_from_master_list.rs
- server/service/src/stocktake/insert.rs
- server/service/src/sync/test/test_data/master_list_line.rs
- server/service/src/sync/translations/master_list_line.rs
Fixes #4703 (Part 2)
Adds `master_list_line` pricing to OMS
Part 3 & maybe 4 to come...
> Sync master list line prices to OMS

- build/windows/installers-build.bat
- build/windows/omsupply-android.bat
- build/windows/omsupply-build.bat
- build/windows/omsupply-electron.bat
- build/windows/omsupply-prepare.bat
Fixes #4707 
Adds the android build steps to the windows batch files
Strictly speaking this isn't a windows function, but I've included it in the batch scripts so that the commands are in version control.
The configuration on jenkins is:
* download the [ndk](https://developer.android.com/ndk/downloads) and sdk [command line tools](https://developer.android.com/studio#command-line-tools-only)
* Set up the following folder structure in the root of C:
* android
* sdk
* cmdline-tools
* latest ( the command line tools download, extracted, with the unzipped directory renamed from `cmdline-tools` to `latest` and copied to `cmdline-tools` )
* ndk ( the downloaded ndk is extracted here, note: on jenkins I kept the version in the name too, so this is ndk-r27) 
* add an environment variable …
> Automate android build

- client/packages/common/src/types/schema.ts
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/hooks/useDraftOutboundLines.tsx
- client/packages/invoices/src/OutboundShipment/api/hooks/utils/index.ts
- client/packages/invoices/src/OutboundShipment/api/hooks/utils/useGetDiscountPercentage.ts
- client/packages/invoices/src/OutboundShipment/api/hooks/utils/useGetDiscountPrice.ts
- client/packages/invoices/src/OutboundShipment/api/operations.generated.ts
- client/packages/invoices/src/OutboundShipment/api/operations.graphql
- client/packages/invoices/src/StockOut/utils.tsx
- server/graphql/general/src/lib.rs
- server/graphql/general/src/queries/discount.rs
- server/graphql/general/src/queries/master_list.rs
- server/graphql/general/src/queries/mod.rs
- server/graphql/general/src/queries/tests/master_lists.rs
- server/repository/src/db_diesel/master_list.rs
- server/repository/src/db_diesel/master_list_line_row.rs
- server/repository/src/db_diesel/master_list_row.rs
- server/repository/src/migrations/v2_02_02/master_list.rs
- server/repository/src/migrations/v2_02_02/master_list_line.rs
- server/service/src/lib.rs
- server/service/src/pricing/discount.rs
- server/service/src/pricing/mod.rs
- server/service/src/pricing/tests/discount.rs
- server/service/src/pricing/tests/mod.rs
- server/service/src/service_provider.rs
- server/service/src/sync/test/test_data/master_list.rs
- server/service/src/sync/test/test_data/master_list_line.rs
- server/service/src/sync/translations/master_list.rs
- server/service/src/sync/translations/master_list_line.rs
Fixes #4703 (Part 3)
Changes from `discount` to `discount_percentage` to make the use of the column clearer (slightly)
Assuming a 20% discount is entered as `20` in this column.
Adds a hook to look up & apply the discount from the backend when viewing stockline to allocate
**Outbound Shipment**
Would be nice to show the discount in the UI somehow... Maybe a new issue?
Outbound Shipment
> Apply discounts to Outbound Shipments

- server/service/src/pricing/item_price.rs
Fixes #4703
Puts an exception in for dispensing to ignore discounts
Will do one more PR with clean ups from previous PR.
> 4703-dispensing

- server/graphql/core/src/loader/vaccine_course_dose_by_vaccine_course.rs
- server/graphql/programs/src/mutations/vaccination/insert.rs
- server/graphql/types/src/types/item.rs
- server/repository/src/db_diesel/item_row.rs
- server/repository/src/db_diesel/vaccine_course/vaccine_course_dose.rs
- server/repository/src/db_diesel/vaccine_course/vaccine_course_dose_row.rs
- server/repository/src/migrations/v2_03_00/add_doses_to_item.rs
- server/repository/src/migrations/v2_03_00/add_vaccine_doses_to_item.rs
- server/repository/src/migrations/v2_03_00/mod.rs
- server/repository/src/mock/encounter.rs
- server/repository/src/mock/item.rs
- server/repository/src/mock/program_enrolment.rs
- server/repository/src/mock/stock_line.rs
- server/repository/src/mock/vaccination.rs
- server/repository/src/mock/vaccine_course.rs
- server/service/src/sync/test/test_data/item.rs
- server/service/src/sync/translations/item.rs
- server/service/src/vaccination/insert/generate.rs
- server/service/src/vaccination/insert/mod.rs
- server/service/src/vaccination/insert/validate.rs
- server/service/src/vaccination/validate.rs
- server/service/src/vaccine_course/query.rs
- server/service/src/vaccine_course/test/update.rs
Fixes #4712
If a vaccination is given, automatically create a prescription to dispense the dose:
> 4712 create prescription from vaccination

- client/packages/system/src/Report/api/hooks/useGenerateReport.ts
Fixes #4783
Move the hook call to be within a hook
Unsure why no one else has complained about this?
It happens for me on every report generation.
1.
2.
> Fix reports hook

- client/packages/common/src/intl/locales/en/common.json
- client/packages/system/src/Report/components/ReportArgumentsModal.tsx
Fixes #4804 
Changes wording of report modal
You can view the modal to see all is in working order
https://docs.msupply.foundation/docs/getting_started/report/
> 4776 Add report title wording changes

- server/service/src/sync/translations/invoice_line.rs
Fixes #4784
Wasn't saving total_before_tax (which is what is being used to save/display service charges) when translating service lines. Since lines only have 1 type, have used invoice to check if it is an Inbound or Outbound Shipment to get the correct pricing.
2.
1.
2.
> 4784 After migration the price on service charges does not show

- client/packages/invoices/src/Returns/SupplierDetailView/SidePanel/RelatedDocumentsSection.tsx
Fixes #4683
Fix return translations
1.
2.
> 4683 Broken translation: Supplier/outbound returns linked shipment

- server/graphql/invoice_line/src/mutations/outbound_shipment_line/line/insert.rs
- server/graphql/invoice_line/src/mutations/outbound_shipment_line/line/update.rs
- server/graphql/tests/permissions.rs
> test fixes for 2.2.2

- server/repository/src/db_diesel/vaccine_course/vaccine_course_dose.rs
- server/repository/src/db_diesel/vaccine_course/vaccine_course_dose_row.rs
- server/repository/src/migrations/v2_03_00/add_vaccine_course_dose_deleted_datetime.rs
- server/repository/src/migrations/v2_03_00/mod.rs
- server/repository/src/migrations/views/mod.rs
- server/repository/src/mock/vaccine_course.rs
- server/service/src/sync/test/test_data/vaccine_course_dose.rs
- server/service/src/vaccine_course/insert.rs
- server/service/src/vaccine_course/query.rs
- server/service/src/vaccine_course/test/update.rs
- server/service/src/vaccine_course/update.rs
Fixes #4657 
Soft deletes vaccine course doses, so you can edit a vaccine course now 🎉 
1.
2.
> 4657 vaccine course dose soft delete

- server/service/src/stock_line/historical_stock.rs
> Use total for back ledge calculation

- build/windows/omsupply_desktop.suf
- build/windows/omsupply_server.suf
Fixes #4879
Replace the hard coded paths to the test connection binaries in the server suf
Have requested a new build
1.
2.
> Adjust test connection binary paths for server installer

- client/packages/invoices/src/Returns/CustomerDetailView/Toolbar.tsx
Fixes #4901
Hook bug fix removes hook out of function and gives default id = ''
Test as per #4901 with:
Steps to reproduce the behaviour:
1. Create a customer return
2. Add a line
3. Select the line
4. Actions -> Delete
5. See **no** error
1.
2.
> 4901 Bug fix - call hook out of function with default id

- server/service/src/invoice/prescription/update/generate.rs
> 4900 backdated datetime(pr review suggestion)

- client/packages/config/src/routes.ts
- client/packages/host/src/components/AppDrawer/AppDrawer.tsx
Fixes #4860 
Adds external links to docs (and for other external links if and when we want to add them)
You can test this by changing the user language in OMS and trying the app drawer links to docs
1.
2.
> Adds localised links to docs

- client/packages/common/src/intl/utils/IntlUtils.ts
Fixes #4981
Add PT as a language selection option
1. Maybe if language selection is available anywhere... update those screenshots
2.
> Add PT option

- client/packages/common/src/intl/locales/en/common.json
Fixes #4997
Tweek report pref description
1. Screenshot of the filter modal 
2.
> 4997 Notification prefs wording fix

- client/packages/system/src/Vaccination/Components/SelectBatch.tsx
Fixes #4916
Per issue comment - not fixing anything up in the transactions (i.e. still can end up with 0.00000000001) but instead of rounding that down to 0, show `<1` and disable the line:
Could also just hide the line, but I think better to show user that there is an unusable line sitting there, prompting them to clean up with stocktake/adjustment?
1.
2.
> 4916 batches with <1 doses remaining are showing as 0

- client/packages/common/src/types/schema.ts
- client/packages/system/src/Vaccination/Components/SelectItemAndBatch.tsx
- client/packages/system/src/Vaccination/api/operations.generated.ts
- client/packages/system/src/Vaccination/api/operations.graphql
- client/packages/system/src/Vaccination/api/useVaccination.ts
- server/graphql/types/src/types/stock_line.rs
- server/repository/src/db_diesel/vaccine_course/vaccine_course_item.rs
- server/repository/src/db_diesel/vaccine_course/vaccine_course_item_row.rs
- server/repository/src/migrations/v2_03_00/add_vaccine_course_item_deleted_datetime.rs
- server/repository/src/migrations/v2_03_00/mod.rs
- server/repository/src/mock/vaccine_course.rs
- server/service/src/sync/test/test_data/vaccine_course_item.rs
- server/service/src/vaccine_course/update.rs
Fixes #4999
Adds soft deletes for vaccine course items. Remote sites can now be initialised! 🙈 
1.
2.
> #4999 soft delete vaccine course item

- server/report_builder/README.md
partially Fixes [4800](https://github.com/msupply-foundation/open-msupply/issues/4800) docs requirement.
Note: docs will probably need further updating when we finalise front end + doc syncing methods from OMS central server.
No code changes
Is docs 🎸
> Add standard reports docs

- package.json
- server/repository/src/migrations/v2_03_00/remove_stops_from_report_ids.rs
Fixes #
Migration tried to update ID, but foreign keys weren't update yet.
Since this is just for RC, I think it's fine if we have a few duplicated records so I've removed that line from the migration
Sorry I didn't test my suggestion properly :(
1.
2.
> Fix rc migration

- build/windows/omsupply_server.suf
- build/windows/omsupply_standalone.suf
Fixes #5070
Updates the default Log Level in our installers to Info.
This will provide a lot more info to our support team when investigating any issues.
Untested :(
Will need to run a build through Jenkins to test, then install a fresh copy...
1.
2.
> Update default log level to Info

- client/packages/reports/src/DetailView/DetailView.tsx
- client/packages/system/src/Report/components/ReportArgumentsModal.tsx
- server/Cargo.toml
- server/server/Cargo.toml
Fixes #5090
Adds check so set to loading isn't called if report arguments do not change
Attempt to replicate issue in #5090
> 5090 bug fix eternal loading 

- .github/workflows/server-tests.yaml
- server/README.md
Fixes #5029
Runs `cargo clean --package repository` before each test run
We might need to do a full clean sometimes...
> clean repository crate on server tests

- server/service/src/sync/test/test_data/stocktake.rs
> fix stocktake tests again

- client/packages/requisitions/src/RnRForms/DetailView/AppBarButtons.tsx
- client/packages/requisitions/src/RnRForms/DetailView/DetailView.tsx
- client/packages/requisitions/src/RnRForms/DetailView/SidePanel.tsx
Fixes #4727
Adds more detail panel to R&R form:
This is just adding the panel, will add reference and comment in sep PR
1.
2.
> add side panel to R&R

- server/repository/src/migrations/v2_04_00/add_manual_requisition_line_fields.rs
> fix migration

- .github/workflows/client-bundle-size-diff.yaml
- client/packages/system/src/Item/DetailView/DetailView.tsx
Fixes #4761
Fixes CI bundle size check
1.
2.
> 4761 fix CI bundle diff

- server/graphql/item_variant/src/mutations/delete.rs
- server/graphql/item_variant/src/mutations/upsert.rs
- server/graphql/types/src/types/item.rs
Fixes #5239
Update the doses Option from float to int
There were a couple of warnings when compiling too, so have tidied those.
1.
2.
> Fix compilation and tidy warnings

- client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.tsx
- client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEdit.tsx
- client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx
- client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts
- client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/InboundLineEdit.tsx
- client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabLayout.tsx
- client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEdit.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/columns.ts
- client/packages/invoices/src/OutboundShipment/DetailView/columns.ts
- client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/PrescriptionLineEdit.tsx
- client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/columns.ts
- client/packages/invoices/src/Prescriptions/DetailView/columns.ts
- client/packages/invoices/src/Returns/CustomerDetailView/columns.ts
- client/packages/invoices/src/Returns/SupplierDetailView/columns.ts
- client/packages/invoices/src/Returns/modals/CustomerReturn/ReturnQuantitiesTable.tsx
- client/packages/invoices/src/Returns/modals/SupplierReturn/ReturnQuantitiesTable.tsx
- client/packages/invoices/src/StockOut/hooks/usePackSizeController.test.tsx
- client/packages/invoices/src/StockOut/hooks/usePackSizeController.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/ItemCharts/ConsumptionHistory.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/ItemCharts/StockEvolution.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/columns.ts
- client/packages/requisitions/src/ResponseRequisition/DetailView/columns.ts
- client/packages/system/src/Item/Components/PackSize/PackSizeQuantityCell.tsx
- client/packages/system/src/Item/DetailView/DetailView.tsx
- client/packages/system/src/Item/DetailView/Toolbar/Statistics.tsx
- client/packages/system/src/Item/DetailView/Toolbar/Toolbar.tsx
- client/packages/system/src/Item/ListView/ListView.tsx
> 999 delete pack variant(quantity input suggestion)

- client/packages/common/src/hooks/useConfirmOnLeaving/useConfirmOnLeaving.ts
- client/packages/common/src/index.ts
- client/packages/host/src/Host.tsx
- package.json
Fixes #5274
Uses useBlocker to prevent navigation on back button as well as in page navigation
1.
2.
> 5274 back button not confirming when form dirty

- server/service/src/location/tests/update.rs
- server/service/src/location/update.rs
Adds default to location tests, affected by the `cold_storage_type` should have been picked up in Code Review (sorry!)
Not much to see here...
1.
2.
> Fix location tests

- client/packages/system/src/Location/ListView/LocationEditModal/LocationEditModal.tsx
Fixes #5306
Frontend test work now...
Perhaps, this is why @mark-prins always worries about import paths?
1.
2.
> Fix frontend tests in develop

- client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NumberInputCell.tsx
- client/packages/system/src/Item/DetailView/Tabs/ItemVariants/ItemPackagingVariantsTable.tsx
- client/packages/system/src/Item/api/hooks/useItemVariant/useItemVariant.ts
> non zero input

- server/repository/src/db_diesel/indicator_value.rs
- server/repository/src/db_diesel/indicator_value_row.rs
Fixes #5337 
Just tweaking structs
> 5337 make indicator_value structs consistent

- server/repository/src/db_diesel/indicator_value.rs
- server/repository/src/db_diesel/indicator_value_row.rs
- server/repository/src/migrations/v2_04_00/indicator_value_create_table.rs
- server/service/src/sync/test/test_data/indicator_value.rs
- server/service/src/sync/translations/indicator_value.rs
Fixes #5360
Just renaming a field to better reflect info
> 5360 rename indicator_value.supplier_store_id to store_id

- client/packages/coldchain/src/Equipment/ImportAsset/ImportReviewDataTable.tsx
- client/packages/coldchain/src/Equipment/ListView/ListView.tsx
Fixes #5447
Added ColumnFormat.Date to installation date column in Equipment list view to have the date display as DD/MM/YYYY
Change needed as date was displaying as YYYY-MM-DD
1.
2.
> Update installation date column in Equipment ListView.tsx

- client/packages/coldchain/src/Equipment/ImportAsset/ImportReviewDataTable.tsx
- client/packages/coldchain/src/Equipment/ListView/ListView.tsx
Fixes #5447
Was supposed to go into 2.4.0. Original PR has already been approved
> 5447 fix equipment date format

- client/packages/common/src/ui/components/inputs/Autocomplete/Autocomplete.tsx
Fixes #5406
Fix issue where temperature label does not appear unless the temperature input field is interacted with
Change needed as label name needs to always display
1.
2.
> Add temperature label to location temperature input

- server/service/src/asset/insert.rs
Fixes #5467 
Display appropriate error message when user attempts to import existing asset 
From this:
To this:
1.
2.
> Update AssetNumberAlreadyExists error message

- server/service/src/localisations.rs
Fixes #4856 
Fix fail to parse JSON error when running cargo test
Added a line to localisations.rs (thanks @jmbrunskill)
Changes needed to remove error when cargo test is run
The following errors/warnings are still present when running cargo test
For devs
For Testers
1.
2.
> Fix fail to parse json "index.ts" when running cargo test

- client/packages/programs/src/JsonForms/components/Prescription/StockLineTable.tsx
Fixes #5609
Extremely trivial -- should have just used this component the first time!
> 5609 JSON Forms prescription -- validate quantities

- server/service/src/sync/translations/invoice_line.rs
Fixes #5230
Sync return reasons
1.
2.
> Sync return reasons

- server/Cargo.lock
- server/Cargo.toml
- server/report_builder/README.md
- server/reports/expiring-items/2_3_0/convert_data_js/package.json
- server/reports/item-usage/2_3_0/convert_data_js/package.json
- server/reports/stock-status/2_3_0/convert_data_js/package.json
- server/reports/stock-status/2_3_0/package.json
Fixes #5312
This took a bit of time to investigate, first there was an issue with parsing large json inside extism js function, this was fixed by https://github.com/extism/js-pdk/issues/107, and extism-js reinstall helped, as per: https://github.com/extism/js-pdk?tab=readme-ov-file#install-script (@fergie-nz @roxy-dao I think you might have been the only two with js-pdk installed, can you please re-install)
After that I was getting error with linking, updating extism package helped (I'll try to replicate and make an issue)
https://github.com/extism/js-pdk/issues/108
Try to run item usage report with @mariyamsupply data file
1.
2.
> Fix issue with extism js bundle

- client/packages/common/src/ui/components/charts/NewValueBar/NewValueBar.stories.tsx
Fixes #5697
Storybook was failing to build due to a duplicated story name
1.
2.
> Only one story and straight to bed!

- client/packages/common/src/intl/locales/tet/replenishment.json
Fixes #5696
Adds tetum translations for R&R Form
There was a request to remove strength, haven't done that one yet as I'm not sure if it's what we want for other use cases?
1.
2.
> Add R&R form tetum translations

- client/packages/requisitions/src/ResponseRequisition/DetailView/IndicatorEdit/IndicatorEditPage.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/IndicatorsTab.tsx
Fixes #5624
Also related to [docs changes](https://github.com/msupply-foundation/msupply_docs/pull/130)
Adds comment to explain presence of front end filtering for when values don't exist
No functional changes. No testing required
Docs updated in linked PR.
> Add comments for FE filter

- server/service/src/processors/transfer/invoice/mod.rs
- server/service/src/processors/transfer/mod.rs
- server/service/src/processors/transfer/requisition/mod.rs
> Move log system error up to super

- server/repository/src/db_diesel/abbreviation.rs
- server/repository/src/db_diesel/abbreviation_row.rs
- server/repository/src/db_diesel/mod.rs
- server/repository/src/migrations/v2_05_00/abbreviation_create_table.rs
- server/repository/src/migrations/v2_05_00/mod.rs
- server/service/src/sync/test/test_data/abbreviation.rs
- server/service/src/sync/test/test_data/mod.rs
- server/service/src/sync/translations/abbreviation.rs
- server/service/src/sync/translations/mod.rs
Fixes #5645 
Adds migration, repo and sync logic for the `abbreviation` table
> 5645 abbreviations table

- server/cli/src/refresh_dates.rs
- server/repository/src/db_diesel/changelog/changelog.rs
- server/repository/src/db_diesel/mod.rs
- server/repository/src/db_diesel/system_log_row.rs
- server/repository/src/migrations/v2_04_01/mod.rs
- server/repository/src/migrations/v2_04_01/system_log_table.rs
- server/service/src/activity_log.rs
- server/service/src/processors/transfer/invoice/mod.rs
- server/service/src/processors/transfer/invoice/update_outbound_invoice_status.rs
- server/service/src/processors/transfer/mod.rs
- server/service/src/processors/transfer/requisition/mod.rs
- server/service/src/sync/test/test_data/mod.rs
- server/service/src/sync/test/test_data/system_log.rs
- server/service/src/sync/translations/mod.rs
- server/service/src/sync/translations/system_log.rs
> 2.4.1 to develop

- client/packages/common/src/intl/currency/currency.ts
Fixes #5777
Adds XOF, XAF and CDF currencies.
Believe in yourself 
;)
1. the unit is XOF
2. the price is rounded to 0 dp
1. the unit is X**A**F
2. the price is rounded to 0 dp
1. the unit is CF
2. the price is rounded to 2 dp
- [ x ] **No documentation required**: no user facing changes or a bug fix which isn't a change in behaviour
1.
4.
> add XOF currency

- server/reports/item-usage/2_3_0/src/stockOnOrder.sql
Fixes #5799 
Make sure item usage report works on postgres flavour
1.
2.
> Fix item usage report in postgres

- client/packages/common/src/intl/currency/currency.ts
- server/reports/expiring-items/2_3_0/convert_data_js/src/utils.js
- server/reports/expiring-items/2_3_0/convert_data_js/src/utils.test.ts
- server/reports/expiring-items/2_3_0/manifest.json
- server/reports/item-usage/2_3_0/manifest.json
- server/reports/item-usage/2_3_0/src/stockOnOrder.sql
- server/reports/stock-status/2_3_0/src/template.html
Fixes #2434543654645675634243242
1.
2.
> 2.4.2 into develop

- server/cli/src/cli.rs
- server/report_builder/README.md
- server/server/src/lib.rs
Fixes #5182 
Adds more verbose logging for ease of tracing reports.
Adds println to expose javascript logs from within wasm functions for more easy debugging.
console.log, console.error, and console.info are all exposed as println! in the server terminal.
> 5182 add logging to reports

- server/cli/src/refresh_dates.rs
- server/repository/src/db_diesel/contact_form.rs
- server/repository/src/db_diesel/email_queue_row.rs
- server/repository/src/db_diesel/mod.rs
- server/repository/src/migrations/v2_05_00/add_email_queue_table.rs
- server/repository/src/migrations/v2_05_00/mod.rs
- server/service/src/invoice/inbound_shipment/add_from_master_list.rs
- server/service/src/invoice/inbound_shipment/generate.rs
Fixes #5690 
Create email queue table and add migration
Changes needed as part of GEDSI project to add contact form which sends requests to support
Sidequest to fix https://github.com/msupply-foundation/open-msupply/pull/5759#discussion_r1886107764 here 6efc405aeefef5c7f5d58e9fdb7d65ccf6169923
1.
2.
> 5690 create email queue table

- client/packages/invoices/src/Prescriptions/DetailView/SidePanel/PatientDetails.tsx
> Use local state

- client/packages/common/src/utils/environment/EnvUtils.ts
Fixes #5871 
Update external link to go directly to introduction page
Changes needed as part of GEDSI
1.
2.
> Update external docs link

- client/packages/common/src/intl/locales/en/common.json
- client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts
- client/packages/invoices/src/OutboundShipment/DetailView/columns.ts
Fixes #5780
Added a new column to display the total price for each row in Inbound Shipments. Improved the wording to clarify whether the price value is a Cost Price or a Sell Price: Cost Price for inbound shipments and Sell Price for outbound shipments.
1.
2.
> 5780 inbound Shipment table does not show total cost

- client/packages/system/src/Item/DetailView/Tabs/ItemLedger.tsx
Fixes #5979
Adds number of packs label
1.
2.
> 5979 Item ledger missing label

- server/service/src/requisition/program_settings/customer_program_settings/map.rs
- server/service/src/requisition/program_settings/supplier_program_settings/map.rs
Fixes #5987
Don't compare `None` elmis code
1.
2.
> 5987 fix tests

- client/packages/requisitions/src/RequestRequisition/DetailView/DetailView.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/IndicatorEdit/IndicatorEditPage.tsx
Fixes #5995 
Fixes request requisition queries for indicator values
> Query with user customer store name id

- server/README.md
- server/cli/src/test_connection.rs
- server/service/src/lib.rs
Fixes #5925
Adds mail test connection step to test_connection tool
1.
2.
> 5925 test mail connection

- client/packages/common/src/intl/locales/en/common.json
- client/packages/system/src/Patient/CreatePatientModal/FetchPatientModal.tsx
- client/packages/system/src/Patient/CreatePatientModal/useFetchPatient.ts
Fixes #5669
Add error message when v6 not configured and stop infinite polling feedback loop
1.
2.
> 5669 Fix patient lookup failure

- client/packages/config/src/routes.ts
Fixes #6011 
Update route so that when language is Portuguese, user guides external link navigates to Portuguese version of docs
1.
2.
> Update route to navigate to portuguese docs when lang is portuguese

- client/packages/common/src/intl/locales/tet/common.json
Fixes #5696
Add requested translation to Tetum
1.
2.
> #5696 Add requested to tetum

- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestEditPage.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseEditPage.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEdit.tsx
- client/packages/system/src/Item/Components/ListItems/ListItems.tsx
Fixes #6021
Remove extra div that was creating 2nd scrollbar
1.
2.
> Remove extra div

- server/service/src/invoice/update_picked_date.rs
> Dont update if picked datetime not changed

- client/packages/common/src/ui/components/errors/GenericErrorFallback.tsx
- client/packages/host/src/Host.tsx
Fixes #6049
Brings back this guy when something goes wrong:
I left the old error boundary in Host, as high as we can have it, for things that go wrong in those common providers. But we needed to provide another one inside the router.
1.
2.
> Fix error boundary

- client/packages/host/src/CommandK.tsx
Fixes #
Quick fix for now until a solution is provided. I keep getting redirected when I wanna copy!
1.
2.
> update command c shortcut

- server/reports/inbound/2_5_0/src/template.html
Fixes #6221
Fix dateOrNA macro for inbound report
1.
2.
> Fix dateOrNA macro for inbound report

- client/packages/common/src/intl/locales/en/common.json
- client/packages/requisitions/src/RequestRequisition/ListView/ProgramRequisitionOptions.tsx
- client/packages/requisitions/src/ResponseRequisition/ListView/ProgramRequisitionOptions.tsx
- server/service/src/requisition/program_settings/common.rs
> Main to  dev

- .github/README.md
Reference to where to look in the wiki for github actions information
> Add a link to the wiki in the github folder.

- client/packages/programs/src/schema_types.ts
- server/service/src/programs/patient/patient_schema.rs
- server/service/src/programs/patient/patient_updated.rs
- server/service/src/programs/schemas/patient.json
Fixes #6410
Updates backend NextOfKin schema field to match the frontend one, and the one on base patient in programschemas repo now (in PR)
1.
2.
> 6410 fix backend patient schema

- client/packages/common/src/plugins/usePluginEvents.ts
- client/packages/common/src/types/schema.ts
- server/graphql/plugin/src/plugin_data/mutations/update.rs
- server/repository/src/migrations/v2_06_00/plugin_data.rs
> PR suggestions

- .github/pull_request_template.md
Fixes #999
Adds a checklist section to the PR Review Template
The idea is to remind the reviewer of responsibilities. Keen to hear if these things are useful and if the idea is good one...
> Add a checklist to PR template

- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestEditPage.tsx
Fixes #6079 
When a user is entering information to an internal order, the 'Next' button now responds on the first click, instead of the second - and saves any changes to the field as expected.
Each time the user clicked next it would appear to be 'clicked' however the action actually being taken was 'unblur' then 're-render the page' - thus the 'next' action wasn't getting called until the second time it was clicked. This was also occurring with changes to other fields on the same page, and with the 'previous' button.
The response edit page now has a wrapper and an inner, and the wrapper handles loading state/page refreshing, and returns the page inner. This fix is the same as the fix in #5867, though the issues presented differently.
1.
2.
> Prevent needing to double-click 'Next' when adding items to Internal Orders

- client/packages/common/src/ui/layout/tables/components/Cells/MultiNumberInputCell/MultiNumberInputCell.tsx
- client/packages/programs/src/VaccineCourseEditModal/VaccineCourseEditModal.tsx
Fixes #6615
Fixes age input widths:
1.
2.
> 6615 fix vaccine course age cells

- client/packages/host/src/components/Login/hooks.ts
Fixes #6521
Remove whitespace from username input field on submission
Change needed as OG trims whitespace so aligning OMS functionality
I'm not sure if the change on the frontend is enough? It seems to be working as expected.
1.
2.
> 6521 Remove whitespace from username input

- client/packages/common/src/ui/components/inputs/TextInput/BasicTextInput.tsx
- client/packages/system/src/Encounter/DetailView/DetailView.tsx
Fixes #6605 
Fixes #6654
Stops time pickers erroring when clicked
Also fixes the flickery loading of encounter UI, sorry for side quest 😁 
And for the loading
1.
2.
**Tests Pass**
> 6605 fix time picker crash

- client/packages/common/src/ui/components/inputs/Autocomplete/Autocomplete.tsx
- client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteWithPagination.tsx
- client/packages/common/src/ui/components/inputs/Select/Select.tsx
- client/packages/common/src/ui/components/inputs/TextInput/BasicTextInput.tsx
Some of #6332 (this one https://github.com/msupply-foundation/open-msupply/issues/6332#issuecomment-2677356857)
I was in the area, but thought should be separate PR
1.
2.
**Tests Pass**
> 6332 location/autocomplete mui fixes

- client/packages/programs/src/JsonForms/common/components/Autocomplete.tsx
- client/packages/programs/src/JsonForms/common/components/Group.tsx
- client/packages/programs/src/JsonForms/components/DateOfBirth.tsx
Fixes #6592
Allows clearing of autocomplete fields in JSON forms.
Also fixed the date of birth bc she was jank and squish like this:
1.
2.
**Tests Pass**
> 6592 clearable json form fields

- client/packages/programs/src/JsonForms/components/Search/usePatientSearchQuery.tsx
Fixes #6594
Program patients were only having their `document` fields returned from patient search, which has `firstName` and `lastName`, but not `name`, which is what is being used for the next of kin selector.
Updates the query to merge base patient fields with extra `document` ones
1.
2.
**Tests Pass**
> 6594 link program patients as next of kin

- client/packages/host/public/index.html
Fixes #6571
Updated the base index.html file used in webpack to tell the browser to use UTF-8
Why this changed is still a mystery, but this seems to fix it so I'm not digging deeper.
Could be MUI6? Could an errant Windows Character in our code somewhere
Browsers make a guess as to the content encoding if not explicitly told what to do, and that can go wrong...
Dev Test
QA Test
1.
2.
**Tests Pass**
> Tell the browser to use UTF-8

- client/packages/system/src/Stock/api/hooks/useStockLine.ts
Fixes #6582
The save button was disabled on load but would become enabled onClick anywhere on the page. Update save button behaviour to remain disabled when state ```!isDirty```. 
Changes needed as otherwise flow is confusing for user
1.
2.
**Tests Pass**
> 6582 Update save button to stay disabled if no changes made

- client/packages/system/src/Item/api/api.ts
Fixes #6001 
Adds a filter to the relevant query in order to remove items which are not active and not visible, which I believe includes deleted items.
I am concerned that this filter may not exclude all deleted items. I did my best to verify it, but couldn't find a way to gaurantee it would always work. My tests were all successful, but because I couldn't find out exactly what happens when you delete an item in 4D and then sync that change to Open mSupply, I can't be sure. Is there any way to make sure, do you think?
Thanks!
**Tests Pass**
> Remove Deleted Items from Vaccine List

- client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditForm.tsx
Fixes #6889
This is just a quick duplication of th #6718 PR as that was accidentally merged to `develop` rather than the RC branch. 😳
> Remove conditional

- client/packages/common/src/ui/layout/tables/components/Cells/TextInputCell/TextInputCell.tsx
- client/packages/programs/src/VaccineCourseEditModal/VaccineCourseEditModal.tsx
Fixes #6630
Disables save button while course name or dose labels are empty, adds asterisks to communicate:
1.
2.
**Tests Pass**
> 6630 prevent saving empty vaccine courses

- client/packages/common/src/ui/components/footer/ActionsFooter.tsx
Fixes #5914
Adds ability to clear action footer
1.
2.
**Tests Pass**
> Clear selected option

- client/packages/coldchain/src/Equipment/ListView/CreateAssetModal.tsx
Fixes #6227 
I tested the idea when looking at the issue and this fixes what I think the problem is, so have just put the PR in. It's a very low priority, just trying to tick off an issue.
The `Type` input is disabled if you are adding a non-catalogue asset and have not yet selected a category.
1.
2.
**Tests Pass**
> Disable asset type when creating non-catalogue asset

- client/packages/common/src/ui/components/popover/PaperPopover/PaperClickPopover/PaperClickPopover.tsx
Fixes #6270
Hide popover on backdrop click
1.
2.
**Tests Pass**
> Hide on backdrop click

- client/packages/config/src/config.ts
- client/packages/host/src/Admin/Settings.tsx
- client/packages/host/webpack.config.js
Fixes #6765 
Add a feature flag to hide the accordion containing incomplete printer configuration settings
is not used for/connected to anything at this stage - can reopen later when label printing work continues. Is separate to the 'devices' accordion
- Go to Settings
- See that 'Printers' is not in the accordion headings
1.
2.
**Tests Pass**
> 6765 Hide printer config accordion

- client/packages/invoices/src/Prescriptions/LineEditView/LineEditView.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEdit.tsx
Fixes #4907 
After adding a 'new' item and navigating away/saving, the user won't be routed back to creating a new item if they use the back button - the 'new' route is overridden by the following route with the item id
This has been added to the following Edit Views:
- Requisitions
- Internal Orders
- Prescription
1.
2.
**Tests Pass**
> 4970 - Back button prevent navigation back to new item

- server/service/src/vaccine_course/update.rs
Fixes #6631 
Allows the user to clear the demographic field from the Vaccine Course modal, and the changes save
I'm unsure why this 'backup' value was there in the first place? May have unintended side effects somewhere 👀 
1.
2.
**Tests Pass**
> 6631 Make demographic clearable in vaccine course

- client/packages/common/src/intl/locales/en/common.json
- client/packages/programs/src/JsonForms/common/components/Autocomplete.tsx
- client/packages/programs/src/JsonForms/common/components/Boolean.tsx
- client/packages/programs/src/JsonForms/common/components/ConditionalSelect.tsx
- client/packages/programs/src/JsonForms/common/components/Date.tsx
- client/packages/programs/src/JsonForms/common/components/DateTime.tsx
- client/packages/programs/src/JsonForms/common/components/Group.tsx
- client/packages/programs/src/JsonForms/common/components/Number.tsx
- client/packages/programs/src/JsonForms/common/components/Select.tsx
- client/packages/programs/src/JsonForms/common/components/Text.tsx
- client/packages/programs/src/JsonForms/components/DateOfBirth.tsx
- client/packages/programs/src/JsonForms/components/IdGenerator.tsx
- client/packages/programs/src/JsonForms/components/Search/SearchWithUserSource.tsx
- client/packages/system/src/Patient/CreatePatientModal/DefaultCreatePatientUISchema.json
- client/packages/system/src/Patient/PatientView/DefaultPatientUISchema.json
Fixes #6779
Translates default patient UI schemas.
Create:
Edit:
@roxy-dao how best to notify translators? Only one required is `label.code2`
1.
2.
**Tests Pass**
> 6779 translate default patient UI schema

- client/packages/common/src/hooks/useConfirmOnLeaving/useConfirmOnLeaving.ts
Fixes #5825
As mentioned in [this comment](https://github.com/msupply-foundation/open-msupply/issues/5825#issuecomment-2695827269), the issue has become more severe since originally reported, as it creates an infinite re-render. 
This ended up being due to a change in [this commit](https://github.com/msupply-foundation/open-msupply/issues/5825#issuecomment-2695827269) where the `setIsDirty` function is now being returned from the `useConfirmOnLeaving` hook. This caused `setIsDirty` to be unstable, returning a new instance on every render, which in turn caused the `useFormActions` hook to return a new object, etc. causing a loop in the Prescription component.
I'm not particularly happy with this fix, but it works, and it's small. I tried a `useCallback()` to return the `setIsDirty`, but …
> #5825 Fix contraception method/prescription selection reset

- client/packages/invoices/src/Prescriptions/DetailView/Toolbar.tsx
Keeps the field order consistent with older versions & the docs
1.
2.
**Tests Pass**
> Rearrange date and clinician in prescriptions

- client/packages/invoices/src/Prescriptions/ListView/ListView.tsx
Fixes #6828
This PR adds a reference column to the prescriptions' list view.
I noticed that some of the sorting arrows (you know, those little arrows that go after the column's title, that point down when the column is descending order and point up when it is in ascending order) are actually to the left of some of the column titles, and some are to the right.
I didn't spend time fixing it as it seems minor and would probably take me a while, but it might be worth a follow-up issue if one isn't made already.
**Tests Pass**
> 6828 add reference column to prescriptions

- client/packages/host/src/components/SiteInfo.tsx
Fixes #6364 
Fix siteInfo alignment on android login page
1.
2.
**Tests Pass**
> 6364 Fix siteInfo alignment Android

- server/service/src/requisition/request_requisition/use_suggested_quantity.rs
Outstanding for issue #6069. For pr #6860 
Update test for ```use_suggested_quantity.rs```
```Dev```
1.
2.
**Tests Pass**
> Fix test for pr #6860

- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/types/schema.ts
- client/packages/system/src/Stock/Components/InventoryAdjustment/InventoryAdjustmentModal.tsx
- client/packages/system/src/Stock/Components/NewStockLineModal.tsx
- client/packages/system/src/Stock/api/hooks/useInventoryAdjustment.ts
- client/packages/system/src/Stock/api/operations.generated.ts
- client/packages/system/src/Stock/api/operations.graphql
- server/graphql/inventory_adjustment/mutations/insert.rs
- server/graphql/stock_line/src/mutations/insert.rs
- server/graphql/stocktake_line/src/mutations/insert.rs
- server/graphql/stocktake_line/src/mutations/mod.rs
- server/graphql/stocktake_line/src/mutations/update.rs
- server/graphql/types/src/types/inventory_adjustment_reason.rs
Fixes #6731 
Handle error on frontend when a reason is not provided where reason is required when adding/adjusting stock.
```New Stock```
```Stock Adjustment```
1.
2.
**Tests Pass**
> 6731 Handle error when no reason provided for adding/adjusting stock

- client/packages/system/src/IndicatorsDemographics/DetailView/PopulationColumn.tsx
Fixes #6617 
Floor calculated population count so that it does not display as a decimal
1.
2.
**Tests Pass**
> 6617 Floor calculated population count

- client/packages/system/src/Patient/PatientView/Footer.tsx
Fixes #6793 
Add icon for create/save button
1.
2.
**Tests Pass**
> 6793 Add icon for create/save button patientView

- client/packages/system/src/Patient/ListView/Toolbar.tsx
Fixes #6863
1.
2.
**Tests Pass**
> Fix filtering gender

- client/packages/common/src/ui/components/inputs/Autocomplete/Autocomplete.tsx
- client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteList.tsx
- client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteMulti.tsx
- client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteWithPagination.tsx
Fixes #6970
Base no options
1.
2.
**Tests Pass**
> Default no options translation

- client/packages/system/src/Encounter/ListView/columns.ts
Fixes #6700 
Update column arrangement for encounters list view. Move status column to the left of additional info. Reduce width of additional info column.
1.
2.
**Tests Pass**
> 6700 Update column arrangement encounters

- client/packages/coldchain/src/Mobile/Equipment/CardListView.tsx
- client/packages/coldchain/src/Mobile/Equipment/DetailView/DetailView.tsx
- client/packages/coldchain/src/Mobile/Equipment/DetailView/Footer.tsx
- client/packages/coldchain/src/Monitoring/ListView/AppBarButtons.tsx
- client/packages/coldchain/src/common/ImportFridgeTag.tsx
Fixes #6950 
Extracted the existing logic and component used Importing a Fridge Tag into its own file. Named `ImportFridgeTag` within the `common` directory of `coldchain`.
1.
2.
**Tests Pass**
> 6950 Add import fridge tab to equipment mobile view

- client/packages/system/src/Stock/Components/InventoryAdjustment/InventoryAdjustmentModal.tsx
- client/packages/system/src/Stock/Components/Ledger/useLedgerColumns.ts
Fixes #6745 
Allow up to two decimal places to be entered as part of a stock adjustment . Chose two as this is used in other places such as prescriptions
Related issue https://github.com/msupply-foundation/open-msupply/issues/4214
Noticed some weird behaviour with decimals in vaccine items specifically - related to https://github.com/msupply-foundation/open-msupply/issues/6941 and have added further info there
I believe this change makes the bug visible & reproducible in a new area, rather than being the underlying reason for the bug
1.
2.
**Tests Pass**
> 6745 - Allow decimal places in stock adjustment

- client/packages/requisitions/src/RequestRequisition/ListView/ProgramRequisitionOptions.tsx
Fixes #6148 
Fixes #6922 
Re-orders the Program Requisition Selection to first select the Supplier, then filter program by available programs for that supplier.
This one got a bit out of hand, and had some confusion...
The main bug fix is de-duplicating the supplier list on program requisitions.
The issue was introduced when we started matching both masterlists and elmis codes, this meant that the same supplier could show up multiple times in the list.
I fixed that with this commit, that I accidentally commited to the RC branch, so doesn't show in the diff.
https://github.com/msupply-foundation/open-msupply/commit/2654541670b0344fd703acfd9ba0b92f5d3b5ed1
If there's any issues with it, then we can fix it here.
I also as requested by @alainsussol I also changed the modal to select the …
> Program Internal Orders Fixes

- client/packages/android/build.gradle
Fixes #
Bump down gradle version from 8.9.0 to 8.2.1 to match the version in cordova_android_plugin.
1.
2.
**Tests Pass**
> revert gradle version

- client/packages/common/src/ui/components/inputs/CurrencyInput/CurrencyInput.tsx
Fixes #6920
This is just a quick fix to add some rounding to the value displayed. Internally the "react-currency-input-field" package we use only truncates, it doesn't round, which can lead to inconsistencies like the one highlighted in this issue.
I'm fairly sure this doesn't break anything else, but it'd be good to have a think and see if there are any places where this doesn't work so well.
**Tests Pass**
> #6920 Correct rounding for Currency input

- client/packages/requisitions/src/RequestRequisition/DetailView/IndicatorEdit/IndicatorLineEdit.tsx
Fixes #7004
Hide indicators customer info if does not exist
1.
2.
**Tests Pass**
> Hide indicator customer info if not exist

- client/packages/system/src/Encounter/DetailView/Footer.tsx
Small missing translation fix that has remained undetected for 3 years!
Change hard-coded string to translation key
**Tests Pass**
> Tiny translation fix

- server/graphql/types/src/types/master_list.rs
Fixes #7050 
Added `discountPercentage` field in the `invoiceLines` endpoint under `item` node. It would be used to get invoice line's item's master list discount percentage value in the Comoros Facture client report. See more: https://github.com/msupply-foundation/open-msupply-reports/pull/170#discussion_r2010765912
```graphql
query invoice_lines(
$storeId: String!
$invoiceId: String!
) {
invoiceLines(
storeId: $storeId
filter: { invoiceId: { equalTo: $invoiceId } }
) {
... on InvoiceLineConnector {
nodes {
item {
masterLists(storeId: $storeId) {
discountPercentage
}
}
}
}
}
```
1.
2.
**Tests Pass**
> 7050 add discountPercentage field value in invoiceLines endpoint

- client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteList.tsx
- client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteMulti.tsx
- client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteWithPagination.tsx
Fixes #6981 (again!)
Replacement PR for https://github.com/msupply-foundation/open-msupply/pull/7049
> 6981 (replacments) Additional translations for loading

- server/repository/src/db_diesel/preference_row.rs
- server/service/src/sync/test/test_data/mod.rs
- server/service/src/sync/test/test_data/preference.rs
- server/service/src/sync/translations/mod.rs
- server/service/src/sync/translations/preference.rs
Fixes #6839 
Preferences sync
Kinda tests pass sorta scenario ;)
**Tests Pass**
> 6839 preference table sync

- client/packages/invoices/src/Prescriptions/DetailView/columns.ts
Fixes #7044
Adds a Prescribed Quantity Column when enabled in store prefs.
I haven't done anything about the Insurance Status yet, as I think we need a bit of design
1.
2.
**Tests Pass**
> 7044 prescribed qty column

- server/Cargo.lock
- server/graphql/Cargo.toml
- server/graphql/lib.rs
- server/graphql/preference/Cargo.toml
- server/graphql/preference/src/lib.rs
- server/graphql/types/src/types/mod.rs
- server/graphql/types/src/types/preferences.rs
- server/repository/src/db_diesel/preference.rs
- server/repository/src/db_diesel/preference_row.rs
- server/service/src/lib.rs
- server/service/src/preference/mod.rs
- server/service/src/preference/preferences/README.md
- server/service/src/preference/preferences/complex_pref.rs
- server/service/src/preference/preferences/mod.rs
- server/service/src/preference/preferences/use_payments_in_prescriptions.rs
- server/service/src/service_provider.rs
- server/service/src/store_preference.rs
Fixes #6840
Adds service and graphql layers for querying preferences.
Adds a couple of example prefs so we can get a sense of it - are there any actual prefs we are working to add?
```gql
query prefs {
preferences(storeId: "80004C94067A4CE5A34FC343EB1B4306") {
usePaymentsInPrescriptions
complexPref {
somethingHere
somethingElse
}
}
}
```
1.
2.
**Tests Pass**
> 6840 prefs query

- client/packages/common/src/ui/components/inputs/DatePickers/DateTimePickerInput/DateTimePickerInput.tsx
- client/packages/invoices/src/Prescriptions/ListView/NewPrescriptionModal.tsx
- client/packages/system/src/Patient/Encounter/CreateEncounterForm.tsx
Fixes #4998 
Hide time tab from datetime picker in ```New Prescription``` and ```New Encounter``` modal.  
I made changes based on this: https://mui.com/x/react-date-pickers/custom-components/#tabs
```
By default, the tabs are hidden on desktop, and visible on mobile. This behavior can be overridden by setting the hidden prop
```
I set the ```hidden``` prop to ```true``` for both prescriptions and encounters. 
Thanks @aimee-mcneil-melville for brainstorming! 
I tried to set the ```hidden``` prop to ```true``` for the base ```DateTimePickerInput.tsx``` component but that change wasn't coming through for the new encounter datepicker.
@mark-prins I wasn't quite sure how to implement your suggestion of using the ```showTime``` prop to display either ```DateTimePicker``` or ```DatePicker``` …
> 4998 Hide time tab from datepicker

- client/packages/coldchain/src/Equipment/ImportAsset/UploadTab.tsx
Just a follow-up PR to [this one](https://github.com/msupply-foundation/open-msupply/pull/7060), implementing a neat little refactor Carl suggested, for the purpose of more awesomer code.
> Refactor for awesomeness

- client/packages/coldchain/src/Equipment/ImportAsset/EquipmentImportModal.tsx
- client/packages/coldchain/src/Equipment/ListView/AddFromScannerButton.tsx
- client/packages/coldchain/src/Equipment/ListView/CreateAssetModal.tsx
- client/packages/common/src/intl/locales/en/common.json
Fixes #7069 
This PR adds a new translation key specifically for the 'asset created' message displayed on the logs of coldchain assets, so it can have a translation that fits this specific context.
Now it looks like this:
Have a nice day ;)
Cheers!
**Tests Pass**
> Use a new translation key

- server/service/src/sync/settings.rs
Fixes #
Fixing wrong version bumped https://github.com/msupply-foundation/open-msupply/pull/7061#discussion_r2017682122
1.
2.
**Tests Pass**
> Bump correct version

- server/repository/src/migrations/v2_06_01/change_vaccination_date_to_nullable.rs
Fixes #
Inserts from old table inserting into the wrong columns
1.
2.
**Tests Pass**
> Vax table fix

- client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteList.tsx
- client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteMulti.tsx
- client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteWithPagination.tsx
- client/packages/invoices/src/InboundShipment/ListView/AppBarButtons.tsx
- client/packages/invoices/src/Prescriptions/DetailView/columns.ts
- server/cli/src/plugins.rs
- server/repository/src/migrations/v2_06_01/change_vaccination_date_to_nullable.rs
- server/repository/src/migrations/v2_06_01/mod.rs
- server/repository/src/migrations/v2_06_01/remove_plugins.rs
Merges latest 2.6.1 RC to develop
1.
2.
**Tests Pass**
> 2.6.1 develop

- client/packages/common/src/intl/locales/fr/common.json
- client/packages/invoices/src/utils.ts
- client/packages/system/src/Patient/CreatePatientModal/CreatePatientModal.tsx
Fixes #7104
Translation fixes for...
Create patient
Note: this is slightly different to the requested text, I've re-used the key from here:
@alainsussol @Cyrilbrites is this ok? Can they both be updated to the same, or do we need two sets of translations for this?
Prescription export statuses
Payment `change`
1.
2.
**Tests Pass**
> 7104 translation fixes

- client/packages/invoices/src/Prescriptions/DetailView/SidePanel/PrescriptionDetailsSection.tsx
- client/packages/invoices/src/Prescriptions/DetailView/Toolbar.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/ProgramInfoSection.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/Toolbar/Toolbar.tsx
Fixes #7155 
Move programs back to the main window for requisitions.
**Requisitions**
**Prescriptions**
1.
2.
**Tests Pass**
> 7155 move program to main window

- client/packages/common/src/types/schema.ts
- client/packages/system/src/Manage/Preferences/api/operations.generated.ts
- client/packages/system/src/Manage/Preferences/api/operations.graphql
- client/packages/system/src/Manage/Preferences/api/useAvailablePreferences.ts
- server/graphql/preference/src/lib.rs
Fixes #7167
WHOOPS SORRY (turns out its a good idea not to develop with `debug_no_access_control` on 😅 
Adds store id to the query so auth can be validated lol
1.
2.
**Tests Pass**
> 7167 fix permission denied on prefs page

- server/repository/src/migrations/v2_06_01/change_vaccination_date_to_nullable.rs
#7172
Removes them refs that got added back 
How to ensure this doesn't happen in future? If writing these kinds of migrations, recommend using tool like DBeaver to output SQL for latest schema, rather than copying from our migrations, we do change things often...
1.
2.
**Tests Pass**
> 7172 remove reference constraints from vaccination migration

- client/packages/plugins/backendCommon/utils.ts
Fixes #7075
I also re-generated bundle straight into this PR: https://github.com/msupply-foundation/civ-plugins/pull/4
This bundle: https://github.com/msupply-foundation/civ-plugins/blob/584a86fae4f6bf63ba8b7713111b6b8ed9a9bcbf/bundle.json
When i was testing the use case in issue I created outbound shipment and inventory adjustment in omSupply then backdated them with SQL browser. I noticed 2024-09-08 04:12:27.398858 was failing to deserialize correctly, which failed ledger check. Fixed helper and re-generated plugin bundle
Need civ setup, as per the issue, I will leave @alainsussol to test, main point is that extra columns must be visible on requsitions, try create requisition for period, make sure there is zero stock for an item. Create adjustment and outbound shipment, backedate those …
> Fix error in deserializing sql date for plugins

- package.json
Version bump cos can't push directly to base branch :)
> 2.6.1 RC6 -- version bunmp

- server/service/src/sync/test/test_data/invoice_line.rs
> 7203 furx terst

- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditTable.tsx
Fixes #6312 
Move column to the right by one so that it aligns with packSize column of the table
1.
2.
**Tests Pass**
> 6312 Align placeholder row packSize column

- client/packages/common/src/ui/components/inputs/TextInput/InputWithLabelRow.tsx
- client/packages/system/src/Vaccination/Components/VaccinationModal.tsx
Fixes #6696
Add required prop to common "InputWithLabelRow" component so that we can add a required flag to alert user why "Ok" button is disabled when stating that a vaccine has NOT been given
I don't think it should but hopefully this doesn't affect the use of the component in other areas.
1.
2.
**Tests Pass**
> 6696 Add required indicator

- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
Fixes #7198 
Re adds requisition as params into RequestEditPage.  This was a merging conflict issue arising from [this pr](https://github.com/msupply-foundation/open-msupply/pull/6899)
**Tests Pass**
> 7198 fix test builds failing

- package.json
> 2.7.0 RC1 release

- server/Cargo.lock
- server/android/src/android.rs
- server/android/src/lib.rs
- server/server/src/main.rs
- server/windows/Cargo.toml
- server/windows/src/windows.rs
Fixes #7262
Fix window build
1.
2.
**Tests Pass**
> Recursion limit

- package.json
Bump version for next RC build
> 2.7.0 RC2 release version bump

- client/packages/invoices/src/Prescriptions/DetailView/SidePanel/AdditionalInfoSection.tsx
- client/packages/invoices/src/Prescriptions/DetailView/SidePanel/PrescriptionDetailsSection.tsx
Multi-issue PR (Main issue is #6188 with #6407 and #5035 as linked issues)
This PR Fixes #6188 (Actually the issue that is fixed is #6407 - unable to replicate #6188 and #5035 - only written this way to satisfy sync labels action)
Add debounced value callback for prescription comment field input so that updatePrescription does not fire for each keystroke.
https://github.com/user-attachments/assets/7ad61090-ddc4-40c3-be9c-7901d417a7f5
1.
2.
**Tests Pass**
> 6188-6407-5035 Add debounced value callback for prescription comment field

- client/packages/common/src/intl/locales/en/common.json
- client/packages/system/src/Asset/AssetLogReasons/LogReasonCreateModal/LogReasonCreateModal.tsx
- client/packages/system/src/Asset/api/hooks/useAssetLogReason.ts
- client/packages/system/src/Asset/utils.ts
Fixes #7300
Removes status check since it's defaulting in the seed anyways... not sure why it was added and should have checked while refactoring instead of copy-pasting 👀. Status now being displayed.
1.
2.
**Tests Pass**
> 7300 unable to create log reason

- client/packages/common/src/ui/components/inputs/DatePickers/DateTimePickerInput/DateTimePickerInput.tsx
Fixes #7241
PR has already been approved. Was supposed to go into 2.7 but got into develop instead >.>
1.
2.
**Tests Pass**
> 7241 Translate datetime picker

- package.json
> v2.7.0-RC3 -- bump version

- client/packages/common/src/types/schema.ts
- client/packages/invoices/src/Prescriptions/api/operations.generated.ts
- client/packages/invoices/src/Prescriptions/api/operations.graphql
- client/packages/system/src/Item/api/operations.generated.ts
- client/packages/system/src/Item/api/operations.graphql
- client/packages/system/src/Vaccination/api/operations.generated.ts
Fixes #6767 
Adds the warning node type into the stockline node within the operations.graphql for prescription line and item
This appears to be a duplication as warnings are in the item node, and the stockline node contains the item node so it is required there also
Including warnings in both areas allows correct compilation
1.
2.
**Tests Pass**
> Fix yarn compilation/item warnings graphql

- client/packages/invoices/src/Returns/SupplierListView/AppBarButtons.tsx
Fixes #7342 
Navigates via ID.
Related to [refactor issue](https://github.com/msupply-foundation/open-msupply/pull/6899)
**Tests Pass**
> 7342 navigate via id

- client/packages/android/README.MD
Fixes #7217 
Make some changes to the android readme
Slightly different setup with 32bit included, numbered steps for rust setup, and folder structure diagram
1.
2.
**Tests Pass**
> Android readme update

- client/packages/invoices/src/Returns/CustomerListView/AppBarButtons.tsx
Fixes #7341
Adds navigate via id rather than invoice number
**Tests Pass**
> 7341 add navigate via

- package.json
> 2.7.0-RC5 Bump version

- server/repository/src/migrations/v2_07_00/change_vaccination_date_to_not_nullable.rs
> Handle result for vax date to not nullable migration

- client/packages/common/src/intl/locales/en/common.json
- client/packages/invoices/src/InboundShipment/DetailView/AddButton.tsx
- client/packages/invoices/src/InboundShipment/DetailView/AppBarButtons.tsx
- client/packages/invoices/src/InboundShipment/api/hooks/utils/useAddFromMasterList.ts
- server/repository/src/mock/invoice.rs
- server/service/src/invoice/inbound_shipment/add_from_master_list.rs
Fixes #7363 
Changes verifying check to allow for shipped and delivered inbound shipments to be delivered.
**Tests Pass**
> Update verifying functions

- client/packages/common/src/ui/components/inputs/Filters/DateFilter.tsx
- client/packages/common/src/ui/components/inputs/Filters/dateFilter.test.tsx
Fixes #7356
Constrain date filter ranges correctly:
Unit tests added...
1.
2.
**Tests Pass**
> 7356 cant edit date filter

- client/packages/coldchain/src/Equipment/ImportAsset/UploadTab.tsx
Fixes #
Removes `useAssetData` from `UploadTab` component. 
1.
2.
**Tests Pass**
> remove unused hook

- client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteWithPagination.tsx
Fixes #7194
This is a duplicate of PR https://github.com/msupply-foundation/open-msupply/pull/7194 to go into 2.8 instead of 2.7
**Tests Pass**
> 7194 [Redo] Add overflow handling to listbox

- server/service/src/sensor/berlinger.rs
Fixes #7456
It skips over any fridge tag temperature logs that are not possible to convert to the local time zone.
It also defaults any breach times to use the unconverted time if time conversion isn't possible, it shouldn't really do this but more complex error handling would be messy here.
This isn't an ideal solution, we probably need to design a better fix, given this isn't going to happen again for the demo server, we can probably leave this, or we can merge this to improve the situation.
1.
2.
**Tests Pass**
> 7456 skip and log bad fridge tag records

- client/packages/common/src/authentication/api/hooks/usePreference.ts
Fixes #
Missing quotes to make storeId string
1.
2.
**Tests Pass**
> Fix pref query

- client/packages/common/src/ui/discovery/ManualServerConfig.tsx
Fixes #7541 
This PR ensures that tablets can connect remote servers.
It does this by changing the value of isLocal to false when you are configuring a manual connection to a server.
The value of isLocal was originally set to true. I didn't know why but after testing that you can still connect to a local server through a manual connection, the consensus was that it is safe to set to false now. It might be worth taking a look at to make sure it's not a breaking change.
**Tests Pass**
> Set isLocal to false for manual server config

- client/packages/inventory/src/Stocktake/ListView/CreateStocktakeButton.tsx
- client/packages/system/src/MasterList/Components/MasterListSearchInput.tsx
- client/packages/system/src/MasterList/Components/index.ts
Fixes #6705
Replace `Select` dropdown list component with `Autocomplete` component
- Used existing `LocationSearchInput` to replace Location `Select`
- Created new `MasterListSearchInput`component to replace Master List `Select` (this was done because all other instances where we select master lists uses `MasterListSearchModal`- seemed liked bad user experience to have a modal open inside another modal)
- Modelled `MasterListSearchInput` off `LocationSearchInput`
- This change now also allows for clearing selection  
Changes needed so that we can accommodate large lists and also to be more consistent with rest of the app.
`Master List selection field with popover open - shows full string`
`Master List selection field after selection - shows ellipsis when text overflows`
`Location …
> 6705 master list name hidden swap select for autocomplete

- client/packages/common/src/ui/components/inputs/SearchBar/SearchBar.tsx
- client/packages/common/src/ui/layout/tables/index.ts
- client/packages/requisitions/src/RnRForms/DetailView/ContentArea.tsx
- client/packages/requisitions/src/RnRForms/DetailView/Footer.tsx
- client/packages/requisitions/src/RnRForms/DetailView/RnRFormLine.tsx
- client/packages/requisitions/src/RnRForms/DetailView/Search.tsx
- client/packages/requisitions/src/RnRForms/api/hooks/useRnRFormContext.ts
- client/packages/requisitions/src/RnRForms/utils.ts
Fixes #7602
Fixes #7609
Adds search to R&R:
Also fixes column headers so info tooltip is the whole cell. And a few move arounds...
1. R&R form docs
2.
**Tests Pass**
> 69 internal rnr search

- server/service/src/requisition/program_settings/customer_program_settings/prepare.rs
Fixes #7671 
Fixes unit tests on 2.7.2 branch.
Now we want to show all order types even when no periods are available (filtering has been removed).
This adjusts tests to reflect this change.
**Tests Pass**
> Fixes prepare tests

- server/repository/src/db_diesel/name_tag.rs
Fixes #7547
Fixing bug where name tag filter was ignored
1.
2.
**Tests Pass**
> 7547 fix name tag filter

- client/packages/coldchain/src/Mobile/Equipment/CardListView.tsx
Fixes #7667
Replaces hard coded button text with the translation equivalent
Images below are result of changes.  Button no longer shows hard coded text of "Add Asset".
1.
2.
**Tests Pass**
> 7667 add translation for new asset button gaps mobile view

- server/service/src/preference/mod.rs
- server/service/src/preference/preferences/mod.rs
- server/service/src/store_preference.rs
Fixes #7659
Adds comments for how to access prefs from the backend
1.
2.
**Tests Pass**
> Adds a get_preference function to backend

- client/packages/system/src/ActivityLog/Components/ListView.tsx
Fixes #7680
This was previously removed by me, sorry, it was in DetailView, and we didn't use provider for main table, so thought it was safe.
Log tab in RnR form should work
1.
2.
**Tests Pass**
> Add table provider around activity log for rnr form

- server/service/src/requisition/program_settings/customer_program_settings/prepare.rs
Fixes #7778 
After much mucking around I noticed there _is_ a unique key in this mock data that we can sort by.
- I also at one point was going to add an `id` to `ProgramSettings`, however looked like I was going to have to update 500 files maybe so I didn't
- Until I noticed the unique key I was going to sort by master_list_id `then` by `orderTypes[0].id`.
- This test is still flakey if someone adds more data and makes the unique key not unique anymore
not needed/dev automated 
**Tests Pass**
> 7778 fix failing postgres test

- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/hooks/useOpenedWithBarcode.ts
Fixes https://github.com/msupply-foundation/open-msupply/actions/runs/15100426658/job/42440580662
1.
2.
**Tests Pass**
> fix item id

- client/packages/programs/src/JsonForms/components/PeriodSearch.tsx
- client/packages/programs/src/JsonForms/components/ProgramSearch.tsx
- server/graphql/stocktake/src/stocktake_queries.rs
- server/repository/src/db_diesel/stocktake.rs
Fixes #7750
Adds clearable filters to period search and program search components.
Also makes program search more generic.
Some of the conditional logic is a bit strange - I think could do with a refactor to make these components more generic.
**Tests Pass**
> 7750 add program id filter to stocktake query

- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/intl/locales/pt/common.json
- client/packages/common/src/types/schema.ts
- client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.tsx
- client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts
- client/packages/invoices/src/InboundShipment/DetailView/DetailView.tsx
- client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/ContentArea.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEdit.tsx
- client/packages/invoices/src/OutboundShipment/api/hooks/line/useOutboundRows.ts
- client/packages/invoices/src/Prescriptions/DetailView/DetailView.tsx
- client/packages/invoices/src/Prescriptions/DetailView/columns.ts
- client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditForm.tsx
- client/packages/invoices/src/Prescriptions/LineEditView/columns.ts
- server/graphql/preference/src/upsert.rs
- server/graphql/types/src/types/preferences.rs
- server/service/src/preference/mod.rs
- server/service/src/preference/preferences/manage_vaccines_in_doses.rs
- server/service/src/preference/preferences/mod.rs
- server/service/src/preference/types.rs
- server/service/src/preference/upsert.rs
Fixes #7818 
Rename `DisplayVaccinesInDoses` pref to `ManageVaccinesInDoses`
No change to underlying functionality.
I did notice that when I'm on a page (e.g stocktake detail view) and toggle the pref on, it doesn't refresh and I don't see `doses per unit` column. I have to do a manual refresh to see the column. 
Ensure you can see store preferences
1.
2.
**Tests Pass**
> 7818 Rename "DisplayVaccinesInDoses" to "ManageVaccinesInDoses"

- client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEdit.tsx
- client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTabs.tsx
- client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabLayout.tsx
Fixes #7824
Renames location tab to other now that donor is also there:
1. screenshots
2.
**Tests Pass**
> 7824 locations tab to other

- client/packages/common/src/hooks/useSimplifiedTabletUI/useSimplifiedTabletUI.ts
- client/packages/common/src/ui/layout/tables/columns/DosesPerUnitColumn/DosesPerUnitColumn.tsx
- client/packages/invoices/src/DoseQtyColumn.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/columns.ts
Fixes #7394  partially
Second issue to follow with more indepth simplified UI changes - this is an MVP which only adds conditional column display for 2.8 release
Adds default do not display columns when simplified tablet ui condition met.
Note that 'doses per unit' and 'doses' column may show unexpectedly in mobile view due to known bug detailed  [here](https://github.com/msupply-foundation/open-msupply/issues/7834)
**Tests Pass**
> 7394 Add MVP simplified mobile UI changes Outbound shipment detail view

- client/packages/common/src/intl/locales/en/common.json
Fixes #7733 
Change the section heading in the Distribution column of dashboards from `Shipments` to `Outbound Shipments`
This heading label isn't used elsewhere so the change does not impact anything else 
1.
2.
**Tests Pass**
> Outbound Shipments Label

- client/packages/common/src/types/schema.ts
- client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts
- client/packages/invoices/src/InboundShipment/api/api.ts
- client/packages/invoices/src/InboundShipment/api/operations.generated.ts
- client/packages/invoices/src/InboundShipment/api/operations.graphql
- client/packages/system/src/Stock/Components/Campaign/CampaignSelectorColumn.tsx
- server/graphql/types/src/types/invoice_line.rs
Fixes #7890 
Shows campaign in Inbound Shipments Detail view 
1.
2.
**Tests Pass**
> 7890 added campaign in inbound shipment detail view

- client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/InboundLineEdit.tsx
- client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
Fixes #7392 
MVP for inbound line edit view
- Remove tabs and hide columns as requested
- VVM status shown on simplified view if enabled and item is vaccine
1.
2.
**Tests Pass**
> 7392 Simplified UI Inbound Line Edit MVP

- client/packages/system/src/Item/DetailView/Tabs/MasterLists.tsx
- client/packages/system/src/MasterList/ListView/ListView.tsx
Fixes #7850 #7852 
Filter Master List with the Store ID. Before the filtering, it would either show all of the Master List or none at all, depending on the page that you're in. 
_**Master List Page**_
_**Item's Master List Tab**_
**_Check in OG mSupply what Master List you have turned on for the Store_**
1.
2.
**Tests Pass**
> filter master list by store id

- server/graphql/invoice_line/src/mutations/outbound_shipment_line/line/insert.rs
- server/graphql/invoice_line/src/mutations/outbound_shipment_line/line/update.rs
- server/graphql/invoice_line/src/mutations/prescription_line/insert.rs
- server/graphql/invoice_line/src/mutations/prescription_line/update.rs
- server/service/src/invoice/update_picked_date.rs
- server/service/src/invoice_line/save_stock_out_item_lines/mod.rs
- server/service/src/invoice_line/stock_out_line/insert/mod.rs
- server/service/src/invoice_line/stock_out_line/update/mod.rs
Fixes #7936
Fixes #7930
Updates backend prescription `auto_pick` to use the `update_prescription` service method, which includes the logic to remove the quantities from SOH!
1.
2.
**Tests Pass**
> 7936 prescription units in stock increasing

- client/packages/common/src/types/schema.ts
- client/packages/system/src/Manage/Campaigns/api/hooks/useCampaigns.ts
- client/packages/system/src/Manage/Campaigns/api/operations.generated.ts
- client/packages/system/src/Manage/Campaigns/api/operations.graphql
- server/graphql/lib.rs
Fixes #7968
Can assign campaign on a remote site
**Central Site**
**Remote Site**
1.
2.
**Tests Pass**
> 7968 be able to assign campaign on remote site

- client/packages/common/src/types/schema.ts
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/columns.tsx
- client/packages/invoices/src/OutboundShipment/api/hooks/useSaveOutboundLines.ts
- client/packages/invoices/src/StockOut/api/operations.generated.ts
- client/packages/invoices/src/StockOut/api/operations.graphql
- client/packages/system/src/Manage/Campaigns/api/hooks/useCampaigns.ts
- project-words.txt
- server/graphql/invoice_line/src/mutations/outbound_shipment_line/line/insert.rs
- server/graphql/invoice_line/src/mutations/outbound_shipment_line/line/update.rs
- server/graphql/invoice_line/src/mutations/outbound_shipment_line/save_item_lines.rs
- server/graphql/invoice_line/src/mutations/prescription_line/insert.rs
- server/graphql/invoice_line/src/mutations/prescription_line/save_item_lines.rs
- server/graphql/invoice_line/src/mutations/prescription_line/update.rs
- server/graphql/types/src/types/draft_stock_out_line.rs
- server/repository/src/db_diesel/invoice_line_row.rs
- server/service/src/invoice/inventory_adjustment/adjust_existing_stock/generate.rs
- server/service/src/invoice/supplier_return/insert/generate.rs
- server/service/src/invoice/supplier_return/update_lines/generate.rs
- server/service/src/invoice_line/get_draft_outbound_lines.rs
- server/service/src/invoice_line/outbound_shipment_unallocated_line/allocate/generate.rs
- server/service/src/invoice_line/save_stock_out_item_lines/generate.rs
- server/service/src/invoice_line/save_stock_out_item_lines/mod.rs
- server/service/src/invoice_line/stock_out_line/insert/generate.rs
- server/service/src/invoice_line/stock_out_line/insert/mod.rs
- server/service/src/invoice_line/stock_out_line/update/generate.rs
- server/service/src/invoice_line/stock_out_line/update/mod.rs
- server/service/src/stocktake/update/generate.rs
- server/service/src/vaccination/generate.rs
Fixes #7910
Adds a column to display the "Campaign" in the Outbound Shipment "Line Edit" modal:
Only displays if there are campaigns defined in the system
Was quite a bit more work than originally anticipated, as I had to add to the invoice line mutations to set the campaign ID when they are added or updated. The "campaign" can be fetched from the Stock line when the item is first being added to the invoice, but subsequent displays need to fetch it from the invoice line (that's the way the current queries work, so makes sense to include it in existing functionality).
1. Campaigns
**Tests Pass**
> 7910 Show campaign in Outbound Shipment

- client/packages/common/src/intl/currency/currency.ts
- client/packages/common/src/intl/number/IntlNumber.ts
- client/packages/system/src/Stock/Components/InventoryAdjustment/InventoryAdjustmentModal.tsx
- client/packages/system/src/Stock/Components/Repack/RepackEditForm.tsx
Fixes #https://github.com/msupply-foundation/open-msupply-internal/issues/83#issuecomment-2939513232
- Parse function wasn't correctly parsing out separators 
- Added support for STN currency 
1.
2.
**Tests Pass**
> Pt number & currency support

- client/packages/common/src/hooks/useSimplifiedTabletUI/useSimplifiedTabletUI.ts
Fixes #7970
Increase breakpoint threshold so that tablets with a larger screen size (E.g samsung A8) have simplified UI view
Tested using a virtual device with the following specs:
- 10.5"
- 1920 x 1200 px 
1.
2.
**Tests Pass**
> 7970 increase simplified ui breakpoint threshold 

- client/packages/common/src/types/schema.ts
- client/packages/programs/src/VaccineCourseEditModal/VaccineCourseEditModal.tsx
- client/packages/programs/src/api/hooks/useVaccineCourse.ts
- client/packages/programs/src/api/operations.generated.ts
- client/packages/programs/src/api/operations.graphql
- server/graphql/types/src/types/vaccine_course.rs
- server/graphql/vaccine_course/src/mutations/insert_vaccine_course.rs
- server/graphql/vaccine_course/src/mutations/update_vaccine_course.rs
- server/repository/src/db_diesel/vaccine_course/vaccine_course_row.rs
- server/repository/src/migrations/v2_08_00/mod.rs
- server/repository/src/migrations/v2_08_00/rename_vaccine_course_is_active_to_use_in_gaps.rs
- server/repository/src/migrations/views/mod.rs
- server/service/src/sync/test/test_data/vaccine_course.rs
- server/service/src/vaccine_course/insert.rs
- server/service/src/vaccine_course/test/delete.rs
- server/service/src/vaccine_course/test/insert.rs
- server/service/src/vaccine_course/test/query.rs
- server/service/src/vaccine_course/test/update.rs
- server/service/src/vaccine_course/update.rs
Fixes #7999
Have opened this issue to update GAPS dashboards https://github.com/msupply-foundation/msupply-dashboard/issues/249
There is a breaking change to the graphQL API... I think changing the insert/update inputs is okay, should be central only mutation, and I'm not aware of reports/integrations against vaccine_course, definitely not with is_active taken into consideration... so probably safe?
1.
2.
**Tests Pass**
> 7999 rename vaccine course is active

- server/Cargo.lock
- server/graphql/clinician/Cargo.toml
- server/graphql/clinician/src/lib.rs
- server/graphql/clinician/src/mutations/insert.rs
- server/graphql/clinician/src/mutations/mod.rs
- server/graphql/lib.rs
- server/service/src/clinician/mod.rs
Part 2 of #8017
Expose graphql endpoint for inserting clinician
Run this in a GQL Playground, passing in store ID param:
```gql
mutation create ($storeId: String!) {
insertClinician(
storeId: $storeId
input: {
id: "test"
code: "ABC"
initials: "AB"
lastName: "bestie"
}
) {
id
}
}
```
1.
2.
**Tests Pass**
> 8017 expose insert clinician mutation via graphql

- package.json
- server/service/src/sync/test/test_data/stock_line.rs
- server/service/src/sync/translations/stock_line.rs
Fixes #
Updates the main branch
1.
2.
**Tests Pass**
> V2.7.7 to main

- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/utils/environment/EnvUtils.ts
- client/packages/config/src/routes.ts
- client/packages/host/src/components/Navigation/DispensaryNav.tsx
- client/packages/host/src/routers/DispensaryRouter.tsx
- client/packages/programs/src/api/api.ts
- client/packages/programs/src/api/operations.generated.ts
- client/packages/programs/src/api/operations.graphql
- client/packages/system/src/Clinician/ListView/ListView.tsx
- client/packages/system/src/Clinician/ListView/columns.ts
- client/packages/system/src/Clinician/ListView/index.ts
- client/packages/system/src/Clinician/Service/Service.tsx
- client/packages/system/src/Clinician/Service/index.ts
- client/packages/system/src/Clinician/index.ts
- client/packages/system/src/Patient/index.ts
Fixes #8065
Adds clinician list view:
1.
2.
**Tests Pass**
> 8065 clinician list view

- client/README.md
- client/packages/common/src/ui/components/inputs/GenderInput/GenderInput.tsx
- client/packages/common/src/ui/components/inputs/GenderInput/index.ts
- client/packages/common/src/ui/components/inputs/index.ts
- client/packages/common/src/utils/index.ts
- client/packages/common/src/utils/mappers/gender.ts
- client/packages/common/src/utils/mappers/index.ts
- client/packages/requisitions/src/RnRForms/DetailView/SidePanel.tsx
- client/packages/system/src/Clinician/ListView/ListView.tsx
- client/packages/system/src/Clinician/ListView/columns.ts
- client/packages/system/src/Clinician/NewClinicianModal.tsx
- client/packages/system/src/Clinician/api/useInsertClinician.ts
- client/packages/system/src/Patient/CreatePatientModal/PatientResultsTab.tsx
- client/packages/system/src/Patient/ListView/ListView.tsx
- client/packages/system/src/Patient/PatientView/PatientSummary.tsx
- client/packages/system/src/Patient/PatientView/index.ts
- client/packages/system/src/Patient/index.ts
Fixes #8061
Adds missed gender input 😁 
1.
2.
**Tests Pass**
> 8061 clinician gender input

- server/service/src/preference/preferences/use_simplified_mobile_ui.rs
Fixes #8291
Make simplified UI pref off by default
1.
2.
**Tests Pass**
> 8291 Default simplified UI pref to be off

- client/packages/system/src/Manage/Reports/api/operations.graphql
Fixes #8316 
Fixes the erroneous GraphQL mutation in front-end  -- it was expecting a return node, which is not what the actual endpoint returns.
I didn't look too deeply into the functionality of report uploading, but I checked with @fergie-nz who confirmed that we don't need anything returned in this case.
**Tests Pass**
> #8316 Fix Graphql generate schema

- .github/workflows/create-nightly-tags.sh
- .github/workflows/nightly-automated-builds.yaml
Partially Fixes #8056
Wrote a Github Action that is triggered at 6:30 at night. The action generates two tags. One for develop and the other for the latest RC branch
The GH Action will only take effect if its on the default branch of a repo. Meaning while its a PR. It theoretically should never run. 
From Github docs: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule
```
This event will only trigger a workflow run if the workflow file is on the default branch.
Scheduled workflows will only run on the default branch.
```
1.
2.
**Tests Pass**
> 8056 nightly automate builds gh action create tags

- client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/InboundLineEdit.tsx
- client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabLayout.tsx
- client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
- client/packages/invoices/src/InboundShipment/api/hooks/index.ts
- client/packages/invoices/src/InboundShipment/api/hooks/useDraftInboundLines.tsx
Fixes #7889 
Added the ability to delete a batch line for Inbound Shipments
1.
2.
**Tests Pass**
> 7899 no easy way to delete a batch line in inbound shipments

- client/packages/common/src/intl/locales/fr/common.json
- client/packages/common/src/ui/components/inputs/DateTimePickers/DateTimePickerInput/DateTimePickerInput.tsx
- client/packages/common/src/ui/components/inputs/DateTimePickers/styles.ts
- client/packages/programs/src/JsonForms/common/components/DateTime.tsx
- client/packages/programs/src/JsonForms/components/DateRange.tsx
Part of https://github.com/msupply-foundation/open-msupply-reports/issues/218
Stops the helper text from expanding the date filters~
1.
2.
**Tests Pass**
> Ordered vs received variance

- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/types/schema.ts
- client/packages/invoices/src/Prescriptions/DetailView/SidePanel/SidePanel.tsx
- server/graphql/types/src/types/permissions.rs
- server/repository/src/db_diesel/user_permission_row.rs
- server/repository/src/migrations/v2_09_00/add_can_cancel_finalised_invoices_user_permission.rs
- server/repository/src/migrations/v2_09_00/mod.rs
- server/service/src/login.rs
Fixes #7565
Only users with the permission `cancel finalised invoices` turned on can cancel a prescription.
1.
2.
**Tests Pass**
> 7565 restrict permission cancelling to users with can cancel finalised invoices user permission

- server/repository/src/migrations/views/mod.rs
Fixes #8412
Re-orders the view drops
the `stock_line_ledger` view depends on `stock_movement` so it needs to be dropped first
1.
2.
**Tests Pass**
> reorder view drop

- client/packages/invoices/src/StockOut/allocateQuantities.test.ts
- client/packages/invoices/src/StockOut/allocateQuantities.ts
- package.json
Fixes #8394
After typing `50` tablets, system rounded up to 100 units - no negative placeholder, total shows correct (100):
@jmbrunskill you triaged this into 2.9, I'm wondering if we should cherry pick into 2.8 as well?
1.
2.
**Tests Pass**
> 8394 Prevent negative placeholders after Outbound Shipment autoallocation

- client/packages/system/src/Report/components/ReportSelector.tsx
Fixes #8460 
Catches errors when printing forms
1.
2.
**Tests Pass**
> 8460 catch print report errors

- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/types/schema.ts
- client/packages/common/src/ui/components/buttons/FlatButton/FlatButton.tsx
- client/packages/common/src/ui/components/footer/ActionsFooter.tsx
- client/packages/invoices/src/Prescriptions/DetailView/Footer/Footer.tsx
- client/packages/programs/src/JsonForms/common/components/Select.tsx
- client/packages/programs/src/JsonForms/common/components/tests/Select.test.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/DetailView.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEditModal.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestedSelection/RequestedSelection.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/DetailView.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseEditModal.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/SuppliedSelection/SupplySelection.tsx
- client/packages/system/src/Patient/CreatePatientModal/DefaultCreatePatientUISchema.json
- client/packages/system/src/Patient/PatientView/DefaultPatientUISchema.json
- server/graphql/preference/src/upsert.rs
- server/graphql/types/src/types/preferences.rs
- server/server/src/print/label.rs
- server/service/src/preference/mod.rs
- server/service/src/preference/preferences/mod.rs
- server/service/src/preference/preferences/order_in_packs.rs
- server/service/src/preference/types.rs
- server/service/src/preference/upsert.rs
- server/service/src/print/jetdirect.rs
> 2.9 to dev

- client/packages/invoices/src/InboundShipment/api/hooks/line/useDeleteSelectedLines.ts
- client/packages/invoices/src/InboundShipment/api/hooks/mapErrorToMessageAndSetContext.ts
- client/packages/invoices/src/InboundShipment/api/hooks/useDraftInboundLines.tsx
Fixes #8457
Allows deleting new batches
Shows error messages when deleting batches that can't be deleted
- And secondly
1.
2.
**Tests Pass**
> 8457 cant delete inbound shipment batches

- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/types/schema.ts
- client/packages/system/src/Manage/Preferences/EditPage/EditPreference.tsx
- server/Cargo.lock
- server/graphql/preference/Cargo.toml
- server/graphql/preference/src/upsert.rs
- server/graphql/types/src/types/preferences.rs
- server/service/src/localisations.rs
- server/service/src/preference/mod.rs
- server/service/src/preference/preferences/custom_translations.rs
- server/service/src/preference/preferences/mod.rs
- server/service/src/preference/types.rs
- server/service/src/preference/upsert.rs
Part 1 of #5061 
Adds new pref for custom translations 
Adds text field renderer for first pass, able to save custom translations if you paste in a valid JSON object :) 
Not applying the translations yet :)
1.
2.
**Tests Pass**
> 5061 custom translations configure pref

- client/packages/system/src/Encounter/DetailView/Toolbar.tsx
- client/packages/system/src/Patient/Encounter/CreateEncounterForm.tsx
Fixes #8553
Allow adding and saving of clinicians on encounters, where the clinician doesn't have a first name
1.
2.
**Tests Pass**
> Add Clinician to encounters

- .github/scripts/get_team_assign_label_milestone.py
- .github/workflows/get_team_assign_label_milestone.yaml
Fixes #
Assigns team labels and next milestones if no milestone or a cooldown milestone... think it should be working... tested on another private repo.
If assignee is removed then team labels are removed~
Can probably add some error handling...
1.
2.
**Tests Pass**
> Assign label and milestone

- client/packages/common/src/ui/components/buttons/standard/LoadingButton.tsx
- client/packages/common/src/ui/components/inputs/TextInput/NumericTextInput.tsx
- client/packages/common/src/ui/forms/Detail/NumericTextDisplay.tsx
- client/packages/common/src/ui/layout/tables/columns/DifferenceColumn.tsx
- client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NumberCell.tsx
- client/packages/invoices/src/DoseQtyColumn.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditTable.tsx
- client/packages/invoices/src/Prescriptions/LineEditView/hooks/useClosedSummary.ts
- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestedSelection/RequestedSelection.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/columns.ts
- client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ContentLayout.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEdit.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/SuppliedSelection/SupplySelection.tsx
- client/packages/requisitions/src/RnRForms/ListView/RnRFormCreateModal.tsx
- client/packages/requisitions/src/common/ModalContentLayout.tsx
- client/packages/requisitions/src/common/utils.test.ts
- client/packages/requisitions/src/common/utils.ts
- client/packages/system/src/Item/Components/PackSize/PackQuantityCell.tsx
- client/packages/system/src/Item/DetailView/Tabs/General.tsx
- client/packages/system/src/Stock/Components/InventoryAdjustment/InventoryAdjustmentModal.tsx
- client/packages/system/src/Stock/Components/Repack/RepackEditForm.tsx
- client/packages/system/src/Stock/Components/StockLineForm.tsx
> 2.9.1 to dev

- client/packages/common/src/intl/locales/en/common.json
- server/repository/src/migrations/v2_10_00/add_supply_level_to_name_properties.rs
Fixes issue starting the app if you already have gaps initialised
This just ignored the error which is the easy fix.
Alternatively we could actually check before running?
1.
2.
**Tests Pass**
> Warn but don't error when inserting default name properties

- client/packages/common/src/types/schema.ts
- server/graphql/programs/src/types/program.rs
- server/repository/src/db_diesel/program_requisition/program.rs
- server/repository/src/db_diesel/program_requisition/program_row.rs
Fixes #8623
Adds item_id filter to programs query
```gql
query ProgramsForItem {
programs(
storeId: "YOUR_STORE_ID"
filter: { itemId: { equalTo: "YOUR_ITEM_ID" } }
) {
... on ProgramConnector {
nodes {
id
name
}
}
}
}
```
1.
2.
**Tests Pass**
> 8623 query programs by item

- client/packages/config/src/config.ts
- client/packages/host/src/components/Navigation/ReplenishmentNav.tsx
- client/packages/host/webpack.config.js
Fixes #8182
This reverts commit eb127dc77cc49fcdf493b876dbfe06c01f152e90.
Removes the purchase order feature flag so purchcase orders will be available in RC versions
1.
2.
**Tests Pass**
> Revert "Add feature flag"

- server/cli/src/test_connection.rs
Fixes #4719
Was looking to see if the issue could be closed easily - and found that opengl isn't available on windows when running in a remote session.. the GUI works ok on a real machine.
Would recommend closing the issue 😢 and just making the URL switch change, as recommended in the issue. that's all that this PR does.
1.
2.
**Tests Pass**
> Rewrite test url in connection checker

- client/packages/system/src/Report/components/ReportArgumentsModal.tsx
Implement a dynamic import of the JSON Forms renderers into the ReportArgumentsModal -- fixes the problem that these components were being loaded as `undefined` due to a circular import dependency (they're being imported from `'@openmsupply-client/programs'` into "system" package, which shouldn't be allowed -- only the other way round).
It's not a great solution, but a more robust fix will require a substantial refactor -- have created an issue to follow up on that: https://github.com/msupply-foundation/open-msupply/issues/8807
**Tests Pass**
> Quick fix for broken reports loading

- client/packages/common/src/intl/locales/en/common.json
- client/packages/inventory/src/Stocktake/DetailView/ChangeLocationModal.tsx
- client/packages/system/src/Location/Components/LocationSearchInput.tsx
- client/packages/system/src/Location/api/hooks/useLocationList.ts
Fixes #8860
Disables the dropdown when the type restrictions conflict:
Also adds the volume filters:
1.
2.
**Tests Pass**
> 8860 location dropdown not clearing

- server/service/src/stocktake_line/validate.rs
Fixes #8893
Adds CVW options to those accepted by backend for negative adjustments 🫠 
1.
2.
**Tests Pass**
> 8893 closed vial wastage reasons arent accepted

- client/package.json
Fixes #8938 
Remove parallel flag from ESLint Command Script
To be honest, I'm still getting my head around this. From what I'm gathering online and AI, this seems to be a V8 Caching and Memory issue. Our ESLint command is running in parallel which might be consuming too much memory and cache available in GitHub Actions compared to our local machines which have access to full system resources - hence why it's hard to replicate locally.
Switched ESLint to sequential execution to resolve V8 caching/memory issues in GitHub Actions. **This is just an assumption but if it works then nice!** We are obviously trading speed for reliability - that being said execution time shouldn't increase by much.
Reference: https://github.com/nodejs/node/issues/51555
Thanks Claude for visualising: 
1.
2.
The …
> 8938 flaky client code checks

- server/repository/src/migrations/views/inbound_shipment_stock_movement.rs
- server/repository/src/migrations/views/inventory_adjustment_stock_movement.rs
- server/repository/src/migrations/views/invoice_line_stock_movement.rs
- server/repository/src/migrations/views/mod.rs
- server/repository/src/migrations/views/outbound_shipment_stock_movement.rs
- server/repository/src/migrations/views/stock_line_ledger.rs
- server/repository/src/migrations/views/stock_movement.rs
Fixes #8809 
Adds the first lot of 5 views.
1.
2.
**Tests Pass**
> Refactor the first lot of 5 views

- client/packages/common/src/ui/components/inputs/Filters/EnumFilter.tsx
Fixes #8531
Allow any enum filters (status, type etc) clearable without removing the filter. This applies throughout the app
The issue suggested adding `X` in the corner, the base component that the enum selection uses already had functionality for the `Clear selection` option. This is also consistent design with the filter menu 
I noticed that in the Item Ledger Filter, after clearing I was unable to immediately scroll in the list. This was not an issue elsewhere. Had a look into fixing it but didn't find a solution so far - likely cause it that it is in a tab?
1.
2.
**Tests Pass**
> Make Enum filters (status, type) clearable

- server/repository/src/db_diesel/activity_log_row.rs
- server/repository/src/migrations/v2_10_00/mod.rs
- server/repository/src/migrations/v2_10_00/rename_cold_storage_type_activity_log_enum.rs
Fixes #8957 
Allow saving a location type on item variants
Renames the activity log type to align with system-wide rename from cold_storage_type to location_type
Renamed both postgres and sqlite, though only postgres threw the error
1.
2.
**Tests Pass**
> 8957 Update location type on item variants

- client/packages/purchasing/src/purchase_order/DetailView/Toolbar.tsx
Wasn't condensing on small screen:
Now will:
1.
2.
**Tests Pass**
> Purchase order toolbar doesn't condense

- server/repository/src/migrations/views/contact_trace_name_link_view.rs
- server/repository/src/migrations/views/invoice_stats.rs
- server/repository/src/migrations/views/mod.rs
- server/repository/src/migrations/views/purchase_order_stats.rs
- server/repository/src/migrations/views/vaccination_course.rs
Fixes #8809 
Refactors fifth lot of 4 views. And that's the last of them!
It also removes the legacy drop and rebuild functions, and clears up comments etc.
1.
2.
**Tests Pass**
> Refactor fifth lot of 4 views

- server/repository/src/migrations/views/changelog_deduped.rs
- server/repository/src/migrations/views/contact_trace_name_link_view.rs
- server/repository/src/migrations/views/invoice_stats.rs
- server/repository/src/migrations/views/latest_asset_log.rs
- server/repository/src/migrations/views/latest_document.rs
- server/repository/src/migrations/views/mod.rs
- server/repository/src/migrations/views/purchase_order_stats.rs
- server/repository/src/migrations/views/report_document.rs
- server/repository/src/migrations/views/report_encounter.rs
- server/repository/src/migrations/views/report_patient.rs
- server/repository/src/migrations/views/report_program_enrolment.rs
- server/repository/src/migrations/views/report_program_event.rs
- server/repository/src/migrations/views/report_store.rs
- server/repository/src/migrations/views/requisitions_in_period.rs
- server/repository/src/migrations/views/vaccination_card.rs
- server/repository/src/migrations/views/vaccination_course.rs
Fixes #8809
Refactors the third lot of 6 views
1.
2.
**Tests Pass**
> Refactor the third lot of 6 views

- client/packages/system/src/Manage/Preferences/Components/CustomTranslations/CustomTranslationsModal.tsx
- client/packages/system/src/Manage/Preferences/EditPage/EditPreference.tsx
- client/packages/system/src/Manage/Preferences/api/useEditPreference.ts
Fixes #8966
Adds handling unsuccessful saves to the preferences page.
1.
2.
**Tests Pass**
> 8966 preference error handling

- server/service/src/sync/translations/invoice.rs
Fixes #9006
See issue for context, immediate fix for potential ledger issue with old data
1.
2.
**Tests Pass**
> 9006 shipped inbounds show in item ledger

- package.json
Our installers have been saying 2.10 develop, which is very confusing because anything going into develop now will be for 2.11!
1.
2.
**Tests Pass**
> Update develop version

- client/packages/host/src/components/Sync/SyncModal.tsx
Fixes #9042
Much like #4616 - something with translations/refs not being available... quick fix is to not invalidate the custom translations when the sync modal first mounts 🤷‍♀️ 
I don't really know why, but I fear finding out could be a rabbit hole. The fact that this has happened twice though, perhaps some investment in better understanding/composition would be worthwhile...
1.
2.
**Tests Pass**
> 9042 layout going haywire

- client/packages/android/capacitor.config.local.json
Fixes my being too keen with the git add
1.
2.
**Tests Pass**
> remove accidental file

- standard_reports/README.md
Fixes #7291
Makes some restructuring changes to reports readme
Some small changes to sections fleshing out details including adding a troubleshooting section.
> Report readme update

- server/graphql/invoice/src/invoice_queries.rs
- server/repository/src/db_diesel/invoice.rs
Fixes #255 
This filter update is needed to support the case where we can filter invoices via Program ID. 
Through your go to GraphQL playground
1.
2.
**Tests Pass**
> 255 add program_id as a filter option for invoices

- server/service/src/apis/permissions.rs
- server/service/src/login.rs
Fixes #8994
See issue for discussion, I misunderstood original requirement...
Its unclear whether requirement is actually around an admin user _finalising_ the shipment, or marking as ready to receive. The new permission is only needed if its around the delivered/received status.
We have an existing permission for finalising inbound shipments/supplier invoices, so should use that for this case - makes migrating sites from OG to OMS easier in future.
Follow up issue can be created based on outcome, if we want the new permission around "ready for receipt".
1.
2.
**Tests Pass**
> 8994 quick fix: map Verify Inbound Shipment to finalise SI permission

- client/packages/common/src/intl/locales/en/common.json
- client/packages/purchasing/src/purchase_order/DetailView/Footer/StatusChangeButton/StatusChangeButton.tsx
- client/packages/purchasing/src/purchase_order/DetailView/Footer/utils.ts
Fixes #9032 
Updated the logic that checks for empty lines for a PO. It was using an outdated check - have updated to be checking if any of the lines doesn't have a set value for `requestedNumberOfUnits`.
1.
2.
**Tests Pass**
> 9032 The PO with only placeholder items can be confirmed and finalised

- client/packages/invoices/src/Returns/CustomerListView/AppBarButtons.tsx
- client/packages/invoices/src/Returns/CustomerListView/ListView.tsx
- client/packages/invoices/src/Returns/SupplierListView/AppBarButtons.tsx
- client/packages/invoices/src/Returns/SupplierListView/ListView.tsx
Fixes #9156
Prevents creating a new supplier or customer return from the `Nothing here` area in list view
These are controlled by the `Disable manual returns` store pref in OMS, and the following prefs on OG - `Return stock from customer invoices` and `Return stock from supplier invoices`
This is not directly related to the `Create supplier credits` pref mentioned in the issue :)
1.
2.
**Tests Pass**
> 9156 Disable Manual Returns with permission

- client/packages/common/src/ui/layout/tables/material-react-table/commonProps.ts
- client/packages/common/src/ui/layout/tables/material-react-table/index.ts
- client/packages/common/src/ui/layout/tables/material-react-table/useMaterialTableColumns.tsx
- client/packages/common/src/ui/layout/tables/material-react-table/usePaginatedMaterialTable.ts
- client/packages/invoices/src/OutboundShipment/ListView/ListView.tsx
Fixes #9129
Implements a common mechanism for handling the various types of filters we have. Currently just handles text, enum and date range, but that covers most of the cases I think.
I created a new hook to parse the column info, but it allows us to just specify a general filter type in *our* column definitions, and the hook converts that into the more detailed shape required by MRT, as well as providing "updater" functions for updating the URL query correctly.
Also implemented the reverse, where the URL query is converted back into the "filter state" requried by MRT so they can stay in sync with each other.
As far as pagination and sorting goes, I didn't really change anything, I just extracted them into named handler functions inside the hook.
I'm not sure I've got the use of …
> #9129 Table sorting and filtering

- client/packages/coldchain/src/Monitoring/api/TemperatureNotification/hooks/useTemperatureNotificationList.ts
- client/packages/coldchain/src/Sensor/api/hooks/useSensorList.ts
- client/packages/coldchain/src/Sensor/api/operations.generated.ts
- client/packages/coldchain/src/Sensor/api/operations.graphql
- client/packages/common/src/types/schema.ts
Fixes #9121 
Only queries temperature notification details if logged user has sensor query permission enabled.
1.
2.
**Tests Pass**
> 105 fix coldchain notification consistent pop up

- client/packages/common/src/ui/layout/tables/material-react-table/index.ts
- client/packages/common/src/ui/layout/tables/material-react-table/types.ts
- client/packages/common/src/ui/layout/tables/material-react-table/useBaseMaterialTable.tsx
- client/packages/common/src/ui/layout/tables/material-react-table/usePaginatedMaterialTable.ts
- client/packages/invoices/src/OutboundShipment/DetailView/DetailView.tsx
Fixes #9195
Add optional column description in column menus:
If not defined, not there:
1.
2.
**Tests Pass**
> 9195 add optional column decription to column menu

- client/packages/system/src/Patient/CreatePatientModal/FetchPatientModal.tsx
- client/packages/system/src/Patient/CreatePatientModal/PatientResultsTab.tsx
- client/packages/system/src/Patient/CreatePatientModal/useCreatePatientForm.tsx
Fixes #9018 
The code added to manage creating for a patient then added to prescription didn't handle the download case.
Now this code has an onDownload function which automatically selects the patient after the download is complete
Took way way too long to fix this, definitely out of touch with frontend but there's a lot of sliders, modals, and different processes going on here. Still some rough edges like the tool tip which says 
1.
2.
**Tests Pass**
> 9018 download patient

- client/packages/system/src/Stock/Components/StockLineForm.tsx
Fixes #8925
Fix vvm status defaulting during stock line edit - blank VVM was being changed to Stage 1, causing form state to be dirty, and prompting confirm on leave.
Once VVM pref is on, it should use default vvm value when _creating_ the stock line. But for existing stock lines, these might not have a vvm status set, and that should be a valid state :)
1.
2.
**Tests Pass**
> 8925 view stock confirm on leave even with no edits

- client/packages/system/src/Stock/ListView/AppBarButtons.tsx
- client/packages/system/src/Stock/ListView/ListView.tsx
- client/packages/system/src/Stock/api/hooks/useExportStockList.ts
Fixes #9039
If view stock list is filtered:
CSV export has same entries:
Won't worry about exports in other areas - this wasn't requested, and going forward we might be able to use export functionality from the new table library anyway 🚀 
1.
2.
**Tests Pass**
> 9039 Filter CSV export based on page filters

- client/packages/common/src/ui/components/loading/InlineProgress/InlineProgress.tsx
- client/packages/system/src/Location/ListView/ListView.tsx
Fixes #9001
Adds volume used to location list view:
1. Location list view
2.
**Tests Pass**
> 9001 show volume used in list view

- server/service/src/report/convert_to_excel.rs
- standard_reports/README.md
Fixes #9389
Set BG color in report:
Would probably recommend, doing the logic for which colour to set, in the convert_data method. Then can just pass the hex code direct into both style prop for HTML, and excel-bg-color attribute.
Considered just pulling the `style` attribute off the cell, looping through it and seeing if there was any we knew how to parse... but that parsing is a bit more involved. Could be worth re-considering in future? Or happy to give it more of a play now if it would feel valuable?
1.
2.
**Tests Pass**
> 9389 custom bg color

- client/packages/common/src/ui/layout/tables/material-react-table/useBaseMaterialTable.tsx
- client/packages/common/src/ui/layout/tables/material-react-table/useSimpleMaterialTable.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/columns.ts
Sorry, just noticed this was missing when writing up table documentation. Just adds a "Select" filter to the VVM status column.
**Tests Pass**
> Tables -- Add filter to VVM status

- client/packages/requisitions/src/RequestRequisition/DetailView/IndicatorEdit/IndicatorEditPage.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/IndicatorEdit/IndicatorEditPage.tsx
- client/packages/requisitions/src/common/ListIndicators.tsx
Fixes #9116
- Change requisition id in crumbs to be requisition number
- Swap code and name
1.
2.
**Tests Pass**
> 9116 Internal Order - Indicators display

- build/windows/omsupply-android.bat
- build/windows/omsupply-build.bat
- build/windows/omsupply-electron.bat
- build/windows/omsupply-prepare.bat
Fixes #9172
Using blocks instead of a single-line if statement... could be possible that the single-line statement is doing something creative before its fully terminated 👀 . Can't say, I've tried building on my windows with fake failures and both single/block statements work for me 🤷🏻 
Are we needing alerts...? I saw that #9067 attempted telegram alerts which got removed?
1.
2.
**Tests Pass**
> 9172 Jenkins builds intermittently don't include frontend

- client/packages/host/src/components/Navigation/DistributionNav.tsx
- client/packages/host/src/components/Navigation/InventoryNav.tsx
- client/packages/host/src/components/Navigation/ManageNav.tsx
- client/packages/host/src/components/Navigation/ReplenishmentNav.tsx
Fixes #9355
Updates nav order per [requested](https://docs.google.com/spreadsheets/d/1k8lBLSufn_eQrNy0dtTDT61Nc0PdzLgGuOlQ7X4QVGU/edit?gid=1099079720#gid=1099079720)
1. Probably good to put docs pages in the order they are in the app..
2.
**Tests Pass**
> 9355 update sub nav sort order

- client/packages/inventory/src/utils.ts
Fixes broken build heh sorry!
1.
2.
**Tests Pass**
> remove missed stocktake date

- client/packages/purchasing/src/purchase_order/DetailView/utils.ts
Fixes #9402
I updated and standardized the base fields across all CSV columns to ensure they match consistently, and added a helper method to process the provided information.
1.
2.
**Tests Pass**
> 9402 purchase order modal export columns should match import columns

- client/packages/requisitions/src/RequestRequisition/DetailView/columns.tsx
Fixes #8844
Adds sorting to MOS column in Internal Order detail view
1.
2.
**Tests Pass**
> 8844 Add sort value to mos column

- server/Cargo.lock
- server/repository/Cargo.toml
- server/repository/src/database_settings.rs
Fixes #8374
urlencode postgres passwords so you can use special characters
1.
2.
**Tests Pass**
> 8374 can't handle special characters in postgres credentials during db connection
