- client/packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.ts
- client/packages/system/src/Item/DetailView/Tabs/MasterLists.tsx
- client/packages/system/src/MasterList/ListView/ListView.tsx
- server/repository/src/db_diesel/requisition_line/requisition_line_row.rs
Fixes #3992
Change row sizes for master list name/description + add tooltip
1.
2.
> 3992 unable to see full description of a master list in item   master list or in master list page

- client/packages/system/src/IndicatorsDemographics/DetailView/IndicatorsDemographics.tsx
- client/packages/system/src/IndicatorsDemographics/DetailView/NameColumn.tsx
- client/packages/system/src/IndicatorsDemographics/DetailView/PercentageColumn.tsx
- client/packages/system/src/IndicatorsDemographics/DetailView/PopulationColumn.tsx
- client/packages/system/src/IndicatorsDemographics/DetailView/utils.test.ts
- client/packages/system/src/IndicatorsDemographics/DetailView/utils.tsx
- client/packages/system/src/IndicatorsDemographics/api/hooks/document/useDemographicIndicators.ts
Fixes #4074
Adds the fifth year.
Also have fixed an issue where the base / general population was being zeroed when the %growth was adjusted.
1.
2.
> Add the fifth year

- client/packages/host/src/components/AppDrawer/AppDrawer.tsx
- client/packages/host/src/components/Navigation/CatalogueNav.tsx
- client/packages/host/src/components/Navigation/ManageNav.tsx
- client/packages/host/src/components/Navigation/ProgramsNav.tsx
- client/packages/host/src/routers/CatalogueRouter.tsx
- client/packages/host/src/routers/ManageRouter.tsx
Fixes #4078
Moves the demographics menu item
Have also changed the icon for Programs and moved Manage to the bottom, as I'd rather have it there. It'll be lost if we add stuff after it.
1.
2.
> Move demographics

- client/packages/system/src/ContactTrace/DetailView/LinkPatientModal.tsx
Fixes #4106 
Use a static LinkPatientModal to avoid recreating it on each render
- Setup patient programs...
- Enter a name in the Family /partner information
- Click the link button to open the modal
- The previously entered name should now be prepopulated (this was broken as well)
- When typing in the filter input the Modal should not flicker
- You should also not lose focus on the current input field
@roxy-dao the video in the docs could be updated now...
> Use a static LinkPatientModal to avoid recreating it on each render

- server/Cargo.lock
- server/repository/Cargo.toml
- server/service/src/programs/program_event.rs
Fixes #4090
An event stack can have events that all have the same  active_start_datetime. When picking the latest active_end_datetime from the stack we thus have to sort by active_end_datetime and not by active_start_datetime.
I noticed this sort order before but thought sorting by ActiveStartDatetime works as well, but it doesn't...
I tried to create test case for it but its a bit tricky because I couldn't easily trick the DB to give me the event in the wrong order. I also attempted to add a comment about it in the code, but the comment didn't make sense to me when reading it because in the context where I did the changes it is more logical to sort by ActiveEndDatetime  in the first place.
However, this is the test that failed when I inserted the event in reverse order into the DB and …
> 4090 program event order

- client/packages/common/src/types/schema.ts
- client/packages/system/src/Patient/ListView/ListView.tsx
- client/packages/system/src/Patient/api/operations.generated.ts
- client/packages/system/src/Patient/api/operations.graphql
- server/graphql/programs/src/queries/patient.rs
- server/graphql/reports/src/printing.rs
- server/graphql/types/src/types/program/patient.rs
- server/graphql/types/src/types/user.rs
- server/repository/src/db_diesel/patient.rs
Fixes #3642
Adds `created date` column to patients and allow users to use this to sort patients (defaults: newest created patient -> oldest)
Was unsure where to put the column... Didn't want it to be too right since it might be hidden on smaller screens...
Should the central search screen also return newest to oldest patients...?
1. Screenshots showing the whole patients page
2.
> 3642 patient search results display in created date order

- client/packages/system/src/Patient/api/hooks/utils/useCentralPatientSearch.ts
Fixes #4087 
Checks if the input object is empty, i.e. has no keys like `first: undefined`.
Could have also added the check on the server but was easier to do in js...
Think it requires the png programs module to be configure to be able to select the NUIC.
- Search only by NUIC or now input params at all
- The returned list should not include central server results
> Disable centralPatientSearch query if the input params object is empty

- client/packages/system/src/Name/api/api.ts
- server/service/src/name/query.rs
Fixes #4079
Filters the facilities list to only include stores.
Turns out the names query was overwriting the `type` to filter out patients - fixed this compose the two filters instead 😅 
There are actually two store filters on name...
1. `isStore` - this checks whether we have a store for that name, via the `name_store_join`
2. `NameType` of `STORE` - name type from mSupply (i.e. as opposed to Facility, Patient...)
Currently I'm using option 2, would you say this is correct?
In the datafile that I'm using, it doesn't seem to matter, like there aren't any names with the `NameType` of `STORE` that don't have a linked store. Or facilities that DO have a linked store. But wanted to check if that is possible?
Though the little store icon on the left hand side is derived from `isStore`... so …
> 4079 facilities list should only include stores

- client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEditForm.tsx
Fixes #3934
Add tooltip to requisition item name
1.
2.
> 3934 Item name is cut off in requisition line edit modal

- client/packages/system/src/Asset/ImportCatalogueItem/UploadTab.tsx
Fixes #4012
Embarassingly easy fix in the end, I switched the example output to use the the property key instead of name, which fixes the issue.
Basically papaparse doesn't correctly parse csv header rows when they contain commas.
Was relying on a simple split on `,` the error was confusing though, as it appeared to suggest it couldn't find the right closing quote in an escape sequence. 
There's an issue in papaparse for this already.
https://github.com/mholt/PapaParse/issues/1052
1.
2.
> Fix asset catalogue import with properties

- client/packages/common/src/intl/locales/en/coldchain.json
- client/packages/system/src/Immunisation/VaccineCourseView/VaccineCourseView.tsx
Fixes #4159 
Removes mini table from vaccine course detail view (as is not required at this stage)
You can see new view at:
Programs -> Immunisations -> Vaccine courses -> Detail view
1.
2.
> Comment out table relevant fields

- client/packages/system/src/Immunisation/VaccineCourseView/VaccineCourseItemSelect.tsx
- client/packages/system/src/Immunisation/VaccineCourseView/VaccineCourseView.tsx
- client/packages/system/src/Immunisation/api/operations.generated.ts
- client/packages/system/src/Immunisation/api/operations.graphql
Fixes #4109
Small UI changes to vaccine course detail view.
Added baseYear to vaccineCourse graphql call so that we can see baseYear in default display name in vaccineCourseDetailView.
Later might not be relevant when we refactor indicators to have different projections for different base years.
1.
2.
> Add baseYear to demographicIndicator graphql call for consistent display

- client/packages/system/src/ReturnReason/Components/ReturnReasonSearchInput.tsx
Fixes #3729
Disables return reason if no reason is configured
1.
2.
> 3729 Returns: if there is no 'Reason' configured on mSupply, you still can type to search

- server/repository/src/migrations/v2_01_00/ledger.rs
Fixes #4185
Just drops the view so that `stock_movement` can be dropped, as per the script.
Only an issue if `consumption` was updated to be dependent on `stock_movement`, so not a big problem
> Drop consumption view in migration

- client/packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.ts
- client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts
- client/packages/invoices/src/InboundShipment/ListView/ListView.tsx
- client/packages/invoices/src/OutboundShipment/ListView/ListView.tsx
- client/packages/invoices/src/Returns/InboundListView/ListView.tsx
- client/packages/invoices/src/Returns/OutboundListView/ListView.tsx
Fixes #3425
Fix column widths so that the whole name shows for column
1. Check to see if any of the screenshots have cut off column names
2.
> 3425 Column titles/headers truncated throughout app despite plenty of screen space

- client/packages/coldchain/src/Equipment/ImportAsset/EquipmentImportModal.tsx
- client/packages/coldchain/src/Equipment/ImportAsset/UploadTab.tsx
- client/packages/coldchain/src/Equipment/utils.ts
- client/packages/common/src/intl/locales/ru/coldchain.json
- client/packages/system/src/Asset/ImportCatalogueItem/UploadTab.tsx
- client/packages/system/src/Asset/index.ts
- client/packages/system/src/index.ts
- client/packages/system/src/utils.ts
Fixes #4086 
Adds bulk import of custom fields to cold chain equipment
You can try this out by importing new asset items.
Example csv should 
1.
2.
> 4086 add custom properties to cold chain equipment csv import

- server/repository/src/migrations/v2_01_00/assets/asset_property_data.rs
Fixes #4203
Removes voltage stabilizer for insulated containers:
1.
2.
> 4203 remove voltage stabilizer for insulated containers

- server/graphql/invoice_line/src/mutations/inbound_shipment_line/line/insert.rs
- server/graphql/invoice_line/src/mutations/inbound_shipment_line/line/update.rs
- server/graphql/invoice_line/src/mutations/outbound_shipment_line/line/update.rs
- server/graphql/invoice_line/src/mutations/prescription_line/update.rs
- server/service/src/invoice_line/stock_in_line/insert/mod.rs
- server/service/src/invoice_line/stock_in_line/insert/validate.rs
- server/service/src/invoice_line/stock_in_line/update/mod.rs
- server/service/src/invoice_line/stock_in_line/update/validate.rs
- server/service/src/invoice_line/stock_in_line/validate.rs
Fixes #4194
Allows stock in values greater than 0 (rather than greater than 1) 
Fixes stocktake issue where you couldn't increase by a decimal number of packs less than one (e.g. 0.5)
1.
2.
> 4194 increase stock by less than one

- package.json
- server/repository/src/migrations/version.rs
Fixes #4217
A somewhat exploratory PR for an issue that is technically still asking for triage love. 
The problem with having the semantically versioned rc in the `package.json` is that the version is used to update the database and run migrations. 
My suggestion here is to simply strip that final section from the semver in package.json, such that `2.10.00-rc1` is displayed on the front end unaltered, but interpreted by the API as `2.1.00`
This gives the following:
_login screen_
_settings screen_
Why is this required? It allows testers to know which version they are running.
1.
2.
> Display RC version

- client/packages/common/src/ui/components/inputs/TextInput/BasicTextInput.tsx
Fixes #4152
*PLEASE NOTE: I had a moment of dyslexia and mis-named my branch as `4125-`* 🙄
Quite a subtle problem here. Turns out that the Mui `sx` prop can actually be an *array* of SX objects as well as a single SX object. What was happening here is that the `sx` styles for the "textField" slotProps in the DateTimePickerInput were being converted to such an array before being passed down to the BasicTextInput component (presumably due to additional styles being injected internally by the Mui DateTimePicker component). And then, when we merged the `sx` objects, the resulting prop was not correct (I think it turned array indexes into object keys, which is why it never threw an error).
Solution here is to just put the SX object into a flattened array when merging, regardless, so that it …
> #4152 Date filter label fix

- client/packages/coldchain/src/Equipment/DetailView/DetailView.tsx
- client/packages/coldchain/src/Equipment/types.ts
- client/packages/system/src/Store/api/api.ts
- client/packages/system/src/Store/api/hooks/document/useStores.ts
- client/packages/system/src/Store/api/hooks/utils/useStoreApi.ts
Fixes #4229
Fixes ability to edit assets with no store on central server.
The error was a bit of a weird one, about locations - you need a store defined to set locations, and we were sending an empty array (Some) instead of undefined (None)
1.
2.
> 4229 assets with no store cant be edited

- client/packages/coldchain/src/Equipment/ListView/CreateAssetModal.tsx
Fixes #3885
Before, entering some search value in the catalogue item input, backspacing and then entering again, caused duplicates like this:
Working now:
1.
2.
> 3885 fix catalogue item autocomplete duplicates

- server/service/src/processors/transfer/invoice/common.rs
- server/service/src/processors/transfer/invoice/test.rs
Fixes #4020
Applies the sell price from the outbound to the transferred inbound, to match functionality in mSupply:
1.
2.
> 4020 map sell prices through on invoice transfer

- .github/workflows/client-tests.yaml
- client/packages/coldchain/src/Equipment/ImportAsset/EquipmentImportModal.tsx
- client/packages/coldchain/src/Equipment/ImportAsset/UploadTab.tsx
- client/packages/coldchain/src/Equipment/utils.ts
- client/packages/common/src/ui/components/inputs/TextInput/NumericTextInput.tsx
- client/packages/system/src/Asset/ImportCatalogueItem/UploadTab.tsx
- client/packages/system/src/Asset/index.ts
- client/packages/system/src/Immunisation/VaccineCourseView/VaccineCourseView.tsx
- client/packages/system/src/IndicatorsDemographics/DetailView/GrowthRow.tsx
- client/packages/system/src/index.ts
- client/packages/system/src/utils.ts
Fixes #4219
Allows decimal inputs to wastage rate and coverage rate
These already allowed floats in the backend, so just changed mui props.
Also add % unit inline for these fields
You can view these changes in Immunisations -> program -> vaccine course -> 
Then look at coverage rate and wastage rate fields
1.
2.
> Add unit and allow decimals to vaccine course view fields

- client/packages/system/src/InventoryAdjustmentReason/api/hooks/document/useInventoryAdjustmentReason.ts
- client/packages/system/src/ReturnReason/api/hooks/document/useReturnReasons.ts
Fixes #3696
Removes caching of return/inventory adjustment reasons, so that they update after sync
1.
2.
> 3696 remove caching of reasons

- client/packages/common/src/intl/locales/en/coldchain.json
Fixes #3806
Remote RTMD from translation for BlueMaestro
1. Update any screenshots that say mSupply RTMD for sensors
2.
> 3806 Cold chain: Rename mSupply sensor type

- client/packages/invoices/src/StockOut/utils.tsx
Fixes #4175
Allow decimal inputs for Outbound Shipments + Prescriptions
Do we want to display available number of packs in decimals in the search bar?
Also, still don't get why pack size of 1 can have decimal packs? Probably want to change this in stocktake too, so have left this up for discussion.
1.
2.
> 4175 Can't enter exact decimal value under 'Pack Qty Issued' column in item-line in Outbounds

- client/packages/common/src/authentication/api/hooks/useLogin.ts
- client/packages/common/src/authentication/api/operations.generated.ts
- client/packages/common/src/authentication/api/operations.graphql
- client/packages/common/src/types/schema.ts
- client/packages/host/src/components/Footer/StoreSelector.tsx
- server/graphql/types/src/types/user.rs
- server/repository/src/db_diesel/store_row.rs
- server/repository/src/migrations/v2_01_00/mod.rs
- server/repository/src/migrations/v2_01_00/store_add_name_link_id_and_is_disabled.rs
- server/service/src/sync/translations/store.rs
Fixes #3874
1. Migration to add `is_disabled` to store
2. In store selector at the bottom left of the screen: Disable store + add on hold text
3. Filter out disabled store from most recent credentials 
Note for testers: Will need to delete database and reinitialise since there has been a migration change to store..
Sorry I accidentally merged develop into the branch and couldn't rebase cleanly again 👀 
1. Add a note about disabled stores
4.
> 3874 you can perform transactions on disabled oms store

- client/packages/common/src/intl/locales/en/distribution.json
- client/packages/requisitions/src/ResponseRequisition/DetailView/ReponseStats/ResponseStoreStats.tsx
Fixes #2780
Show no stock available message if no SOH, incoming or stock on order. Have to check all conditions since the bar will show if one of those is not 0
I toyed with the idea of making it red to pop up more... what do you think? 👀 
1. Add to documentation
2.
> 2780 requisition no bar graph shown if soh = 0

- client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NumberInputCell.tsx
- client/packages/system/src/IndicatorsDemographics/DetailView/IndicatorsDemographics.tsx
- client/packages/system/src/IndicatorsDemographics/DetailView/PopulationColumn.tsx
Fixes #4263 #4265
Formats the numbers:
and makes the pop input wider. It now fits the max integer value we allow:
1.
2.
> Add commas to demographic numbers

- client/packages/common/src/ui/components/buttons/standard/DialogButton.tsx
- client/packages/system/src/Stock/DetailView/DetailView.tsx
- client/packages/system/src/Stock/DetailView/Footer.tsx
Fixes #4067
Change button to `Close`. If stock line has been edited, prompt user that they will lose all their data if they continue or redirect back to Stock page.
1. Screenshots for Stock page
2.
> 4067 view stock 'cancel/close' button disabled

- client/packages/common/src/intl/utils/DateUtils.ts
- client/packages/system/src/IndicatorsDemographics/DetailView/IndicatorsDemographics.tsx
- client/packages/system/src/IndicatorsDemographics/api/hooks/document/useDemographicProjectionUpsert.ts
Fixes #4264
Demographics projections (growth rates) weren't being invalidated after save. On the first time you created the demographics, if you hit the save button twice or more before refreshing, it wouldn't know to update - it would try to do another insert (resulting in an error)
This PR invalidates the projections query after upsert of demographics, so second save does an update correctly!
1.
2.
> 4264 demographic growth rates not saving

- client/packages/system/src/Asset/ListView/ListView.tsx
Fixes #4286
For all sites except central server, hide the select column in asset catalogue: 
1.
2.
> remove selection column for remote sites

- server/service/src/processors/transfer/invoice/common.rs
- server/service/src/processors/transfer/invoice/test.rs
- server/service/src/processors/transfer/invoice/update_inbound_invoice.rs
Fixes #3738
Ended up fixing a few things!
The issue: comments/references weren't being transferred on update (only on insert). I.e. if you set these things before setting outbound to picked, they were transferred, but if you update them between picked and shipped, the changes do not map through. I also updated transport reference and tax percentage to transfer through on updates as well.
THEN I found a few bugs along the way, which honestly, I'm not sure how we didn't find them before??
- Service charge lines have no cost price per pack, nor pack size... so when running `convert_invoice_to_single_pack`, we would end up with a `NaN` and transfers stopped working completely?!
- Transferred service charge totals were showing as 0, becuase they were being calculated as `cost_price_per_pack * …
> 3738 transfer comment and reference updates

- client/packages/common/src/types/schema.ts
- client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditForm.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditForm.tsx
- client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/PrescriptionLineEditForm.tsx
- client/packages/invoices/src/Returns/modals/OutboundReturn/ItemSelector.tsx
- client/packages/system/src/Item/Components/StockItemSearchInput/StockItemSearchInput.tsx
- client/packages/system/src/Item/api/api.ts
- client/packages/system/src/Item/api/hooks/useItemStockOnHand/useItemStockOnHand.tsx
- client/packages/system/src/Item/utils.ts
- server/graphql/general/src/queries/item.rs
- server/repository/src/db_diesel/item.rs
- server/repository/src/db_diesel/stock_line.rs
- server/repository/src/db_diesel/stock_on_hand.rs
Fixes #4024
Makes non-visible items available in various places if you have some stock on hand for that item.
Honestly uncertain about the composition of the filters - typically the filter object is composed as an AND filter, so its a bit funky here to use it as an OR... especially because I can imagine wanting an AND version in future (give me the visible items that have stock on hand.) I tried to make it clear what was happening with comments/naming, but could I do something different?
Per [this comment](https://github.com/msupply-foundation/open-msupply/issues/4024#issuecomment-2185564264) in the issue, I'm not 100% sure where we should/shouldn't include the "invisible items with stock" throughout the app, hasn't been clarified yet, but thought I'd get the implementation in place, …
> 4024 stock lines not included in search

- server/service/src/sync/api/common_records.rs
- server/service/src/sync/central_data_synchroniser.rs
- server/service/src/sync/central_data_synchroniser_v6.rs
- server/service/src/sync/remote_data_synchroniser.rs
- server/service/src/sync/sync_on_central/mod.rs
Fixes #3859 
Add transaction around all sync buffer upserts. 
I've been trying to test the speed of this, but my local og server is inconsistent (consecutive re-sync take anywhere from 50seconds to 3minutes, with both transaction and non transaction sync buffer upserts).
There was however some research done into this, and it was tested that transactions improve SQlite mutations quite a bit: 
https://github.com/msupply-foundation/open-msupply/blob/d60c38e945c07c70850740ea1a83d0cf7bd68bd1/server/service/src/sync/translation_and_integration.rs#L324C1-L327C71
Sorry the change could have been smaller, but i deliberately changed the cursors naming from cursor (for both start and current) to start_cursor and end_cursor
Should be captured by unit tests and normal sync tests
No docs required
> 3859 Upsert sync buffer in transaction

- client/packages/host/src/components/Navigation/DispensaryNav.tsx
- server/repository/src/db_diesel/patient.rs
Fixes #4324
Sort patient by created date time when navigating from App Drawer
1.
2.
> 4324 Error when navigating back to patients list via breadcrumb 

- client/packages/system/src/IndicatorsDemographics/DetailView/GrowthRow.tsx
- client/packages/system/src/IndicatorsDemographics/DetailView/PercentageColumn.tsx
- client/packages/system/src/Name/ListView/Facilities/ListView.tsx
Fixes #4270
Removes the 'house' icon from the facility list - as all records in the list are stores, the icon simply adds confusion.
Offroad request: increase the number of decimal places in the demographic entry screen from 2 to 4 which might avoid one of the [numeric text input issues](https://github.com/msupply-foundation/open-msupply/issues/4213)
1.
2.
> Facility list house icon

- client/packages/coldchain/src/Equipment/api/api.ts
- client/packages/coldchain/src/Equipment/api/hooks/document/useAssets.ts
Fixes #4235
On remote sites, you could see assets for all the stores at that site.
This fix restricts that to only the store you are logged in to.
1.
2.
> 4235 non-central stores should only see their assets

- server/service/src/sync/translations/invoice.rs
Fixes #4271
Map new CC correctly
1.
2.
> 4271 customer-credit from OG should not be mapped as outbound-return

- server/service/src/sync/translations/invoice_line.rs
Fixes #4273 
The `item_code` was coming through, not as `None` but as an empty string.
I've handled the `None` and `is_empty()` as equivalent, and requiring calculation. Would be nice to have some sort of serde deserialize [empty_as_none](https://docs.rs/serde_with/1.4.0/serde_with/rust/string_empty_as_none/index.html) to handle this. surprised it hasn't come up before?
The result is this: the translation handles the new invoice as a new invoice and the pricing works:
1.
2.
> Line totals migration

- server/graphql/invoice/src/mutations/outbound_shipment/insert.rs
- server/repository/src/db_diesel/requisition/requisition_row.rs
- server/service/src/sync/translations/invoice.rs
- server/service/src/sync/translations/invoice_line.rs
- server/service/src/sync/translations/requisition.rs
- server/util/src/test_helpers.rs
Fixes #4306 
Fixes #4305 
Both fixes are relate to existing transfers being migrated to omSupply (inbound shipment and response requisition from existing mSupply mobile store to omSupply store)
There is a check during integration of invoice lines that stock line exists, and if it doesn't we ignore it. Stock line is only added to invoice line in omSupply when inbound shipment is delivered, but in mobile placeholder stock line is id added (either in mobile or during inbound shipment generation in mSupply central). Actually this check was already added but during find_one_by_id refactor it was missed (I went through all of the find_one_by_id and made sure this is not a problem somewhere else, you'll see some minor changes due to this). So added is_some() check on top of is_ok()
For …
> 4306 4305 Fix transfer migrations from mobile

- client/packages/common/src/ui/icons/BarChart2.tsx
- server/service/src/demographic/insert_demographic_indicator.rs
- server/service/src/stocktake/update.rs
Fixes #3947
Logs stocktake changes to stock line... also found a couple bugs along the way. I did the changes on finalised since the stocktake lines get pruned when they are finalised and any changes to stock line that hasn't been counted will be reverted....
The stock line doesn't get invalidated when updating stocktake...
1.
2.
> 3947 stock line changes from stocktake not captured in activity log

- client/packages/common/src/utils/pricing/PricingUtils.ts
- client/packages/invoices/src/OutboundShipment/DetailView/SidePanel/PricingSection.tsx
Fixes #4280
Use tax percentage from invoice to calculate stock tax since we don't do stock tax by line... and also refactor effective tax to return correct tax percentage for service charges.
1.
2.
> 4280 tax displays incorrectly on totals below $1 in outbound shipments

- client/packages/android/app/src/main/java/org/openmsupply/client/ExtendedWebViewClient.java
Fixes #4373
I found that native capacitor plugins were not always available, sometimes they were there and sometimes not. On tablet with dev options on and usb debugging plugged in I could inspect app while it was running with chrome using 'chrome://inspect'. Managed to see a pattern, when adding [console.log here](https://github.com/msupply-foundation/open-msupply/blob/f8dacaf0164d5e8c3442ff54067870ae40ecf19d/client/packages/android/app/src/main/java/org/openmsupply/client/ExtendedWebViewClient.java#L66), and it seem when the log was showing after bugsnag was mounted, web app was not able to recognise native functionality, but when the log was showing before bugsnag mounted log, native functionality worked as expected. This lead me to thing that capacitor JS injection was happening late, …
> Mount capacitor js to web view onLoadResource

- client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.tsx
Fixes #3485
Counted number of packs was still showing 0 for me since the line totals always have some number or 0. So the `-` for uncounted packs was only showing up when you didn't group stocktake by item.
Now checking that every line is either null or undefined to allow `-` to show up for uncounted rows.
1. Done
2.
> 3485 When creating a new stocktake with `Items with stock` checked ON, the counted packs should be equal to the snapshot packs instead of 0

- client/packages/host/src/api/hooks/settings/namePropertyData.ts
Fixes #3700
Adds Zero Dose and Penta 3 as name properties
What is this for or what does it mean? Sorry I'm not sure :)
1.
2.
> Add zero dose and Penta 3

- client/packages/system/src/Name/DetailModal/DetailModal.tsx
Fixes #3993
Allows users to see the full address of a supplier or customer. Had to limit the amount of rows to display because of a sizing error (which apparently is safe to ignore) but thought to play it safe 🤷🏻 . 
1. Update supplier + customer modal screenshots
2.
> 3993 Can't see Supplier/Customer's full address

- client/packages/system/src/Stock/Components/Repack/RepackModal.tsx
- client/packages/system/src/Stock/DetailView/DetailView.tsx
- server/service/src/login.rs
Fixes #4382
Only using `Enter Inventory Adjustment` permissions for inventory adjustments like with how repacks uses `
Create Repack Or Split Stock` since we don't allow edits. The IAs and Repacks go from draft -> finalised.
1. Update permissions page
2.
> 4382 user permissions not working for inventory adjustment and repack

- client/packages/common/src/ui/components/inputs/TextInput/TaxEdit.tsx
Fixes #3964
Val wasn't being updated when tax was updated, so have used useEffect to prompt change.
https://github.com/msupply-foundation/open-msupply/assets/61820074/29fb9e66-0036-4dfb-b28a-25375c345b06
1.
2.
> 3964 Tax Edit modal value is not updated if you edit tax percentage from service line edit modal

- client/packages/common/src/types/schema.ts
- client/packages/invoices/src/Prescriptions/api/operations.generated.ts
- client/packages/invoices/src/Prescriptions/api/operations.graphql
- server/graphql/batch_mutations/src/batch_prescription.rs
- server/graphql/general/src/queries/names.rs
- server/graphql/general/src/queries/tests/names.rs
- server/graphql/invoice/src/mutations/prescription/insert.rs
- server/graphql/invoice/src/mutations/prescription/update.rs
- server/graphql/types/src/types/name.rs
- server/repository/src/db_diesel/name.rs
- server/service/src/invoice/prescription/insert/mod.rs
- server/service/src/invoice/prescription/insert/validate.rs
- server/service/src/invoice/prescription/update/mod.rs
- server/service/src/invoice/prescription/update/validate.rs
- server/service/src/name/query.rs
- server/service/src/validate.rs
Fixes #4161
Removes hardcoded patient filtering from the name service layer and have moved this to the repository layer, and remove is_patient filter and Patient from NameNodeType. 
Prescription insert/update now use a `check_patient_exists` for patient validation instead of the `check_other_party` function.
1.
2.
> 4161 Hardcode filtering out of patients from names query

- client/packages/coldchain/src/Equipment/ImportAsset/EquipmentImportModal.tsx
Fixes #4399
There are two conversions of the import object made prior to sending to the API.
The first of these was stripping out some of the properties - I've refactored to take all props and only override those that need to be.
1.
2.
> Save the replacement date of an imported equipment item

- client/packages/requisitions/src/RequestRequisition/DetailView/columns.ts
- client/packages/requisitions/src/ResponseRequisition/DetailView/columns.ts
- client/packages/system/src/Item/Components/PackVariant/PackVariantQuantityCell.tsx
Fixes #4180
Allows `Requested`, `Supply`, `Issued` and `Remaining` to be displayed in 2 decimal places with ellipsis if there are more than 2 dp to indicate to users that there is a tooltip
1.
2.
> 4180 customer requisition doesn’t accept the decimal values that came form msupply sites via internal orders and remote auth

- client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NumberCell.tsx
- client/packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.ts
- client/packages/common/src/utils/numbers/NumUtils.test.ts
- client/packages/common/src/utils/numbers/NumUtils.ts
- client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts
- client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/columns.ts
- client/packages/invoices/src/OutboundShipment/DetailView/columns.ts
- client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/columns.ts
- client/packages/invoices/src/Prescriptions/DetailView/columns.ts
- client/packages/invoices/src/Returns/InboundDetailView/columns.ts
- client/packages/invoices/src/Returns/OutboundDetailView/columns.ts
- client/packages/system/src/Item/Components/PackVariant/PackVariantQuantityCell.tsx
- client/packages/system/src/Item/ListView/ListView.tsx
- client/packages/system/src/Stock/ListView/ListView.tsx
Fixes #4365 
Only display values at 2 dp and hide longer decimal places with tooltip
1.
2.
> 4365 the decimal will get too long in outbound shipments

- client/packages/reports/src/DetailView/AppBarButton.tsx
- client/packages/reports/src/DetailView/DetailView.tsx
Fixes #4451
Adds print button to report detail view
** Will update testing instructions in epic after MVP done**
1.
2.
> 4451 Print button for report detail view 

- server/service/src/sync/api/common_records.rs
- server/service/src/sync/central_data_synchroniser.rs
- server/service/src/sync/central_data_synchroniser_v6.rs
- server/service/src/sync/remote_data_synchroniser.rs
- server/service/src/sync/sync_on_central/mod.rs
Fixes #4466
In a recent refactor we changed how we set the `source_site_id` on sync buffer rows. #4040
However, one function was hard coded to set this to none, resulting in incorrect setting of this source_site_id
Anything else we might have missed?
1.
2.
> Include source site id sync buffer rows after v6 push to OMS Central

- server/repository/src/db_diesel/changelog/changelog.rs
- server/repository/src/db_diesel/rnr_form_line_row.rs
- server/service/src/sync/api/common_records.rs
- server/service/src/sync/central_data_synchroniser.rs
- server/service/src/sync/central_data_synchroniser_v6.rs
- server/service/src/sync/remote_data_synchroniser.rs
- server/service/src/sync/sync_on_central/mod.rs
- server/service/src/sync/test/test_data/mod.rs
- server/service/src/sync/test/test_data/rnr_form.rs
- server/service/src/sync/test/test_data/rnr_form_line.rs
- server/service/src/sync/translation_and_integration.rs
- server/service/src/sync/translations/mod.rs
- server/service/src/sync/translations/rnr_form.rs
- server/service/src/sync/translations/rnr_form_line.rs
Fixes #4457
Syncs R&R Forms to OMS Central Server, doesn't do anything fancy like create response requisitions or transfers.
Both `rnr_form` and `rnr_form_line` are considered remote data.
> 4457 sync rr forms central server v6

- server/service/src/sync/test/integration/README.md
- server/service/src/sync/test/integration/central/unit_and_item.rs
- server/service/src/sync/test/integration/omsupply_central/asset.rs
- server/service/src/sync/test/integration/omsupply_central/mod.rs
- server/service/src/sync/test/integration/omsupply_central/test.rs
- server/service/src/sync/test/integration/transfer/mod.rs
- server/service/src/sync/test/integration/transfer/requisition.rs
- server/service/src/sync/test/integration/transfer/returns.rs
- server/service/src/sync/test/integration/transfer/shipments.rs
Helper for validating #4466 in develop this test fails, but in the following PR it passes: https://github.com/msupply-foundation/open-msupply/pull/4463
Current omSuppy <-> omSupply central integration tests are limited to central data. Added remote data tester (basically a copy of existing [remote test for syncing with mSupply](https://github.com/msupply-foundation/open-msupply/blob/af61d89f9aa1541ed382e0d9d251e4bbd1f6605a/server/service/src/sync/test/integration/remote/mod.rs#L39-L107). Added one test case for asset row
We talked with @jmbrunskill briefly, when do we add sync integration test ? For now have the following:
* At least one integration test should be added for a records type (i.e. for omSupply central data -> pack_variant one for omSupply remote data -> asset, transfers -> …
> 4466-integration-test-for-remote-omsupply-data

- server/repository/src/migrations/v1_06_00/is_sync_update.rs
Fixes #3875
Changing warning to be a log::debug!
Shouldn't happen in production anymore, and is confusing seeing it in developer logs now and again...
1.
2.
> Remove 1.2 Migration Warning

- client/packages/programs/src/RnRForms/DetailView/AppBarButtons.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/AppBarButtons/AppBarButtons.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/AppBarButtons/AppBarButtons.tsx
- client/packages/system/src/Report/api/hooks/useReportList.ts
- client/packages/system/src/Report/components/ReportSelector.tsx
Fixes #4415 
R&R report PR [here](https://github.com/msupply-foundation/open-msupply-reports/pull/76) - use the upsert script there to insert the report and test this PR.
This PR adds filtering of Requisition subcontexts, so only R&R report shows on R&R page, and it doesn't show on other requisition pages.
1.
2.
> filter report contexts for r&r forms

- server/repository/src/db_diesel/stock_on_hand.rs
- server/repository/src/migrations/v2_02_00/mod.rs
- server/repository/src/migrations/v2_02_00/stock_on_hand_add_total_stock.rs
- server/service/src/rnr_form/generate_rnr_form_lines.rs
- server/service/src/rnr_form/tests/finalise.rs
- server/service/src/sync/test/test_data/rnr_form_line.rs
Fixes #4472
Adds total_stock_on_hand to stock_on_hand view
Changes RnR Form logic to use total_stock_on_hand
Also fixed an RnR Form test.
There's another unrelated test failing though.
1.
2.
> Fix opening balance for first R&R Form when stock is reserved.

- client/packages/common/src/types/schema.ts
- client/packages/programs/src/JsonForms/components/Search/SearchWithUserSource.tsx
- client/packages/system/src/Patient/CreatePatientModal/PatientResultsTab.tsx
- client/packages/system/src/Patient/ListView/ListView.tsx
- client/packages/system/src/Patient/PatientView/PatientSummary.tsx
- server/graphql/programs/src/mutations/patient/insert.rs
- server/graphql/programs/src/mutations/patient/update.rs
- server/graphql/programs/src/queries/patient_search.rs
- server/graphql/types/src/types/clinician.rs
- server/graphql/types/src/types/name.rs
- server/graphql/types/src/types/program/contact_trace.rs
- server/graphql/types/src/types/program/patient.rs
Fixes #4161
Move GenderInput/Type from name type to patient type and also formatted gender in frontend to remove the `_` (: 
1.
2.
> 4161 relocate gender input

- client/packages/reports/src/DetailView/DetailView.tsx
- client/packages/reports/src/ListView/ListView.tsx
- client/packages/reports/src/components/ReportWidget.tsx
- client/packages/system/src/Report/components/ReportArgumentsModal.tsx
- client/packages/system/src/Report/components/ReportSelector.tsx
Fixes #4497
Move report args out of react fragment
1.
2.
> 4497 Report args modal backdrop blackening

- client/packages/requisitions/src/RequestRequisition/ListView/ListView.tsx
- client/packages/requisitions/src/ResponseRequisition/ListView/ListView.tsx
Fixes #4386
Hides program requisition columns if program doesn't exist
1. Screenshots for requisition list views
2.
> 4386 Hide program related columns in Requisition

- client/packages/programs/src/RnRForms/DetailView/AppBarButtons.tsx
- client/packages/system/src/Report/api/hooks/usePrintReport.ts
Fixes #4416
Implements Export button on R&R form page, to export the data to Excel.
You'll need this version of the report: https://github.com/msupply-foundation/open-msupply-reports/pull/78 ... plz also review 🙏 
1.
2.
> allow export of R&R form to excel

- server/service/src/rnr_form/generate_rnr_form_lines.rs
- server/service/src/rnr_form/tests/generate_rnr_form_lines.rs
Fixes #4509 
If there is no transaction data for the period, and the closing balance is 0, we were setting stock out duration to be the length of the period... 
However for the current use case, R&R forms are used without consumption data tracked in OMS, so we should default this duration to 0 and let the user input the duration.
Feels like a future improvement, but wondered about checking whether there were _any_ transactions in the period, for any item, rather than by item... can imagine that if you _were_ tracking transactions, and you had some items with no transactions, then you _would_ want the stock out duration to be set 🤷‍♀️ 
1.
2.
> Set R&R line stock out duration to 0 if no transactions

- server/repository/src/db_diesel/name_row.rs
Fixes #4516
Name row type enum was renamed, but database still treats it as name_type. This PR renames it via attribute 
Unit tests with postgres feature would fail without this change
> Change postgres type for name row type enum

- client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts
Fixes #4349
Set location code when grouping by item
1.
2.
> 4349 Replenishment -> Inbound Shipment: Locations are not shown properly when the view is grouped by item 

- client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NumberCell.tsx
Fixes #4536
An innocuous change in #4403 - the value of a NumberCell can be undefined, but the tooltip is using `value.toString()`
The change is to account for undefined / null values.
1.
2.
> Check for undefined value in NumberCell

- client/packages/programs/src/JsonForms/common/components/Text.tsx
Partially Fixes #4464
Should fix issue for existing report, there is underlying issue in the debouncing of inputs and performance, please see linked issue. 
I've updated some reports to use this prop: https://github.com/msupply-foundation/open-msupply-reports/pull/79
This shouldnt' close the issue, and issue can be changed to look at the debouncing overall, as we've been able to replicate it in the program module
Upsert one of the reports with ./upsert.sh script. Try to quickly item code or name and press OK. Filter should be respected in the report
> Add useDebounce option to text input

- client/packages/common/src/intl/locales/en/reports.json
- client/packages/reports/src/ListView/ListView.tsx
Fixes #4506
Add Nothing here with a message to contact support about setting up reports if there are no reports.
1.
2.
> 4506 Reports page is blank if the reports aren't configured

- client/packages/electron/package.json
- client/packages/electron/src/electron.ts
- client/packages/electron/webpack.main.config.ts
- client/yarn.lock
- package.json
Waiting for 2.2.00-TEST-2-4531 build on Jenkins to validate this fix
Fixes #4531 
In the node-hid version 3.0.0 it looks like there is new packaging of the app: https://github.com/node-hid/node-hid/releases/tag/v3.0.0, I didn't want to get too stuck into why it's different and just decided to revert the node-hid upgrade from this PR: https://github.com/msupply-foundation/open-msupply/pull/4374 
There are some suggestion on what to do with electron, but we have more then one native module (I am pretty sure the discovery package also uses native code), so I don't think [this fix](https://github.com/node-hid/node-hid/issues/526) would work.
The change here should only revert
Sorry looks like i committed the version changes in both package.json, would need to be changed to next RC before …
> 4531 fix client build

- client/packages/invoices/src/InboundShipment/DetailView/SidePanel/PricingSection.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/SidePanel/PricingSection.tsx
Fixes #4394
List service charges in the side panel
1. Could add a note about this in docs
2.
> 4394 view service charges in more detail such as the types of service charged

- client/packages/common/src/ui/components/navigation/Breadcrumbs/Breadcrumbs.tsx
- client/packages/host/src/CommandK.tsx
- client/packages/reports/src/DetailView/DetailView.tsx
Fixes #4494
Removed topLevel from urlParts if there are more than 1 element in urlParts... if we want Report/{Report Name} probably best to move reports out of top level? But it's easy enough to get to reports from Nav, so probably fine? 
Also added shortcut for reports (g+r) and removed border from iframe
1.
2.
> Reports UI

- server/service/src/sync/translations/stocktake_line.rs
Fixes #3910
mSupply creates UUID for stock line in stocktakes if new batches are added, so null stock line id for stocktake line if it doesn't exist. 
1.
2.
> 3910 Post migration from desktop, previous 'sg' stocktakes have missing lines

- client/packages/common/src/intl/locales/en/replenishment.json
- client/packages/common/src/ui/components/inputs/TextInput/BasicTextInput.tsx
- client/packages/common/src/ui/layout/tables/index.ts
- client/packages/requisitions/src/RnRForms/DetailView/ContentArea.tsx
- client/packages/requisitions/src/RnRForms/DetailView/DetailView.tsx
- client/packages/requisitions/src/RnRForms/DetailView/Footer.tsx
- client/packages/requisitions/src/RnRForms/DetailView/RnRFormLine.tsx
- client/packages/requisitions/src/RnRForms/api/hooks/index.ts
- client/packages/requisitions/src/RnRForms/api/hooks/useRnRForm.ts
- client/packages/requisitions/src/RnRForms/api/hooks/useRnRFormContext.ts
Fixes #4568
The `RnRFormLine` component is rendered 3x for every row, on every update.
This is sluggish on android and increasingly so the more lines you have.
I've hobbled the dirty state, as this contributes a render cycle - now the blue dot shows, but there's no global state, so there's no info snack telling you to update. I figure that if you are editing, then the row isn't confirmed and so the finalise button will still prompt.
I had also moved the `useConfirmOnLeaving` hook into the footer as this adds a render cycle when it updates. This is now on every row, and while I'm worried that this adds overhead, it seems to run ok.
Have added the loading indicator to the row. 
With the changes, when you edit a row the row itself renders - previously all rows were re-rendered. 
When you …
> Prevent R&R line rerenders

- client/packages/coldchain/src/Equipment/api/hooks/document/useAssets.ts
Fixes #4471
Use callback to check if site is central server. 
1.
2.
> 4471 Equipment list not showing properly when reloading the page in browser

- client/packages/common/src/intl/locales/en/reports.json
- client/packages/common/src/ui/forms/Detail/InputWithLabelRow.tsx
- client/packages/programs/src/JsonForms/common/JsonForm.tsx
- client/packages/programs/src/JsonForms/common/components/Date.tsx
- client/packages/programs/src/JsonForms/common/components/Number.tsx
- client/packages/programs/src/JsonForms/common/components/Text.tsx
- client/packages/system/src/Report/components/ReportArgumentsModal.tsx
Fixes #4499
Added some css props to the numbers and text input to get the args modal for expiring items looking nicely without effecting other areas using the same component... The rest of the fixes asked for in the latter half of the issue has been fixed already.
1.
2.
> 4499 expiring items report UI review 

- client/packages/common/src/intl/locales/en/reports.json
- client/packages/reports/src/DetailView/DetailView.tsx
- client/packages/system/src/Report/api/hooks/useGenerateReport.ts
Fixes #4587 & #4589
Cover print structure error and change the spinner to a nothing here with the error message.
1.
2.
> 4587 basic reports error shows eternal loading indicator

- server/repository/src/db_diesel/rnr_form_line_row.rs
- server/repository/src/db_diesel/rnr_form_row.rs
Fixes #4604
Allows R&R forms to be re-initialised for remote sites
Adds store ID to changelogs for rnr_form and rnr_form_line, so that when reinitialising (pulling from central v6), central server sends those changelogs (they are filtered by active stores on site)
1.
2.
> 4604 Fix R&R forms not being pulled on initialisation

- client/packages/inventory/src/Stocktake/DetailView/AppBarButtons.tsx
- client/packages/invoices/src/InboundShipment/DetailView/AppBarButtons.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/AppBarButtons.tsx
- client/packages/invoices/src/Returns/InboundDetailView/AppBarButtons.tsx
- client/packages/invoices/src/Returns/OutboundDetailView/AppBarButtons.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/AppBarButtons/AppBarButtons.tsx
- client/packages/requisitions/src/RequestRequisition/api/hooks/utils/useAddFromMasterList.ts
- client/packages/requisitions/src/ResponseRequisition/DetailView/AppBarButtons/AppBarButtons.tsx
- client/packages/requisitions/src/RnRForms/DetailView/AppBarButtons.tsx
- client/packages/system/src/Patient/PatientView/AppBarButtons.tsx
Fixes #4616
I tracked this as far as the call to `useTranslation('reports')` which then causes the reports namespace to be loaded - but due to the timing / placement in the DOM of the ReportArgumentsModal this is loaded after the app bar portal is rendered:
which means that you get a ref for the portal, and then, without the div being unloaded, the ref is `null` 🤷 
a simple fix is to load the reports namespace earlier, so I've lifted that and used it in the appbar components.
A similar problem with internal orders, where the `distribution` namespace was being used, for a component which is in the `replenishment` section; a new namespace is loaded and the portal refs disappear.
So, no conclusive understanding of what's gone wrong - this at least will fix the problem.
Check the following …
> Adjust translation namespace calls

- client/packages/system/src/MasterList/DetailView/ContentArea.tsx
- client/packages/system/src/MasterList/api/api.ts
Fixes #4578
Allow sorting by master list line code
https://github.com/user-attachments/assets/a2d353ff-6e6a-44f6-879e-bc493289e6b5
1.
2.
> 4578 Catalogue -> Master List Lines: Code sorting does not work

- client/packages/common/src/intl/locales/en/catalogue.json
- client/packages/system/src/Item/DetailView/Tabs/MasterLists.tsx
Fixes #4437
Change message for item that isn't linked to master list 
1. Message for no master list linked to item
2.
> 4437 Add some helpful message under 'Master List' tab of item details window for invisible items

- server/repository/src/db_diesel/assets/asset_catalogue_item.rs
Fixes #4567
Filter out deleted assets
1.
2.
> 4567 Catalogue -> Assets -> the count does not update when deleting assets

- server/service/src/invoice_line/stock_in_line/insert/generate.rs
- server/service/src/invoice_line/stock_in_line/update/generate.rs
Fixes #4559
OG docs only talk about converting to 1 when receiving stock, so have removed this for Inventory Adjustments. 
1.
2.
> 4559 Total/Available SoH number looks wrong after stocktake for existing lines whose packsize is greater than 1

- client/packages/common/src/ui/layout/skeletons/DetailFormSkeleton.tsx
- client/packages/host/src/Site.tsx
Fixes #4434
Adds fall back to lazy loading routers
Adds loading indicating skeleton which matches more closely the second loading of list views which is likely to occur with slower internet.
You can test this by navigating to any of the changed routes with throttle enabled in dev tools
1.
2.
> Add fallback to loading indicator for lazy loads

- client/packages/system/src/Patient/PatientView/DefaultPatientUISchema.json
Fixes #3641 (again 🙄)
Updated the default (fallback) Patient UI schema to use the proper "Date of birth" component rather than generic date picker.
If you have an existing Programs schema installed (eg PNG), you won't see the default one (hence why we missed this the first time). In order to test/confirm, go to `PatientView.tsx` and change line 112 temporarily to:
```ts
const patientRegistry = DEFAULT_SCHEMA;
```
> #3641 (2) Fix default patient schema DOB component

- server/service/src/rnr_form/finalise.rs
Fixes #4641
Populates the sent date of the generated internal order
1.
2.
> Populate internal order sent date

- server/service/src/stock_line/query.rs
Fixes #4588 
Requires for fix in report repo: https://github.com/msupply-foundation/open-msupply-reports/pull/87
Extend pagination for stock line
Ideally we would have no pagination for reports or have a way to grab individual pages, added to reports epic to think about in the future.
Run  stock usage, stock detail, expiring items and stock status reports for data file where there are more then 100 items and stock lines, should see all rows.
Can add items with this (for sqlite):
```sql
WITH RECURSIVE
cnt(x) AS (VALUES(1) UNION ALL SELECT x+1 FROM cnt WHERE x<1000)
insert into item(id, code, name, type, legacy_record) select lower(hex(randomblob(16))), 'gen ' || lower(hex(randomblob(16))) , 'gen ' || lower(hex(randomblob(16))) , 'STOCK', ''  FROM cnt;
insert into item_link(id, item_id) …
```
> 4588 Extend pagination on stock lines for reports

- client/packages/system/src/Stock/Components/Ledger/useLedgerColumns.ts
Fixes #4429
Don't allow sort for ledger columns
1.
2.
> 4429 Remove column sorting on ledger

- client/packages/common/src/ui/components/inputs/DatePickers/DateTimePickerInput/DateTimePickerInput.tsx
Fixes #4628 
Removes the seconds from out date/time picker UI so that the time portion isn't so cluttered in the mobile aspect: 
You can use inspect::change layout to mobile to view the mobile version
1.
2.
> Remove seconds from DatePicker UI

- client/packages/invoices/src/InboundShipment/DetailView/Toolbar.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/Toolbar.tsx
- client/packages/invoices/src/Prescriptions/DetailView/Footer/StatusChangeButton.tsx
- client/packages/invoices/src/Prescriptions/DetailView/Toolbar.tsx
- client/packages/invoices/src/Returns/CustomerDetailView/Toolbar.tsx
- client/packages/invoices/src/Returns/SupplierDetailView/Toolbar.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/Toolbar/Toolbar.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/Toolbar/ToolbarActions.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/Toolbar/ToolbarDropDown.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/Toolbar.tsx
Fixes #1633
Disable actions that aren't available. Thought of disabling whole action bar if user can't interact with it, but we now have returns, so have decided to just disable the action for unification. Also fixed dup return in prescriptions
1.
2.
> 1633 disable actions if invoice/requisition is uneditable

- server/repository/src/db_diesel/item.rs
Fixes #4592 
Looks like we needed extra filter by store id for item stock on hand visibility check
I added extra test that fails without this change
Have two stores on the same site, add extra item and new master list to one of the stores, check that it is not shown for second store. Now add some stock for that item in the store, item should remain invisible in second store
> 4592 Add store id to item visibility stock on hand filter

- client/packages/system/src/Name/ListView/Facilities/FacilityEditModal.tsx
- client/packages/system/src/Name/ListView/Facilities/ListView.tsx
Fixes #4647
Move properties hook to modal since it needs to be used when clicking edit in footer and when editing from listview.
1.
2.
> 4647 GAPS: Store Properties are saved but doesn't show up

- client/packages/common/src/ui/components/inputs/Filters/FilterMenu.tsx
Fixes #4233
Prevents the ordering of active filters being changed when they are updated
The problem was in the `useEffect` that runs when the filters are changed -- they were being recreated using the overall filter definitions list and following that ordering (it's the order they show up in the Filter Menu), and if the user had instantiated the filters in a different order, this would be overwritten.
Solution is to check the existing "activeFilters" and only add new filters (if they're in the URL) if not already active.
- Follow the steps in the [original issue](#4233) to see the the problem. However, note that the problem occurs whenever you load the filters in a different order to how they are listed in the menu, not just with the "range" filters as suggested in the issue.
- Switch to …
> #4233 Fix filter layout ordering

- client/packages/coldchain/src/Equipment/ListView/Toolbar.tsx
Fixes #3767
As requested by @adamdewey 
Default filters for equipment: 
- Store
- Category
- Functional status
- Asset number
- Serial number
1. Default filters for equipment? 
2.
> 3767 Cold Chain -> Equipment -> most useful filters not shown by default

- server/service/src/requisition/response_requisition/create_requisition_shipment/generate.rs
Fixes #2389
Carry over response requisition reference to outbound
1.
2.
> 2389 Carry customer reference field through from requisition to outbound shipment

- client/packages/common/src/utils/files/FileUtils.ts
- client/packages/reports/src/DetailView/DetailView.tsx
Fixes #4686
See comments/descriptions in commit
downloadFile is also used in PDF download, which is actually never used, we should delete that at some point.
reportArgs is a dependency to useCallback, but it's an object, was tempted to refactor.
I wonder if iframe can solve the issue we had with file download on android ¯\_(ツ)_/¯ 
Try to export a report in electron app (omSupply client), chrome and firefox, all should work.
For dev test, this issue is replicable if you run `yarn electron:start`, you would need to re-build front end `yarn build` and then restart server
> Download excel report export via iframe

- server/Cargo.lock
- server/README.md
- server/android/src/android.rs
- server/cli/Cargo.toml
- server/cli/src/backup/README.md
- server/cli/src/backup/backup.rs
- server/cli/src/backup/mod.rs
- server/cli/src/backup/restore.rs
- server/cli/src/cli.rs
- server/cli/src/lib.rs
- server/configuration/example.yaml
- server/service/src/settings.rs
- server/service/src/test_helpers.rs
Fixes #4662 
Original PR is here, please make sure all comments are address in that PR as well: https://github.com/msupply-foundation/open-msupply/pull/4664
Adds restore and backup cli scripts, please see [readme](https://github.com/msupply-foundation/open-msupply/blob/81092014a6efa0421953027cb011073969f446b2/server/cli/src/backup/README.md) for more details
I originally had backup folder and pg_bin_dir as cli arguments, after talking to Kahn we thought it would be best in configurations
There are bunch of carry overs and improvements that we should consider doing, i'll try to relocate to another issue:
There is `database_path` settings, which i think is not used (it's not used for sqlite i think, but makes more sense for sqlite?), if it's used for sqlite need to adjust cli -> It is used, …
> 4662 om supply backups

- client/packages/common/src/hooks/useDetailPanel/useDetailPanel.tsx
- client/packages/common/src/intl/locales/en/app.json
- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/intl/locales/en/replenishment.json
- client/packages/host/src/CommandK.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/OrderInfoSection.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/SidePanel.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/Toolbar/Toolbar.tsx
Fixes #3797
Removes some content from the toolbar, so it doesn't take up too much space on narrower screens:
And moves it to the side panel:
Had a brief play with the "show some kind of info popup the first time" side quest, but felt it was taking a bit long. Think we can do a separate issue for that if we find it to be a priority!
On tablet/small window:
1. Internal order screenshots/where to find info should be updated
2. Program requisitions as well
> 3797 move internal order toolbar content to side panel

- package.json
- server/repository/src/migrations/mod.rs
- server/repository/src/migrations/v2_02_01/add_store_ids_to_existing_rnr_form_changelogs.rs
- server/repository/src/migrations/v2_02_01/mod.rs
- server/repository/src/migrations/v2_03_00/mod.rs
Fixes #4687
Adds migration to populate rnr_form and rnr_form_line changelogs with store ID.
There is a test in the migrations
1.
2.
> 4687 hotfix populate changelog store ids

- server/cli/src/backup/README.md
- server/cli/src/backup/backup.rs
- server/cli/src/backup/mod.rs
- server/cli/src/cli.rs
- server/configuration/example.yaml
- server/service/src/settings.rs
Fixes #4696
Add max_number_of_backups to configuration file and uses it in backup script, please see additions to README.md + cli docs 
Do a few backups.
Set max_number_of_backups in configuration file to something low
Do a few more backups and check that only specified number of backups remain (in chronological order)
Make sure to check use case where max_number_of_backups is higher then current number of backups
> Add backup cleanup to backup script

- client/packages/system/src/Encounter/DetailView/DetailView.tsx
Fixes #4250
Check jsonData status as well since status doesn't get changed until the `Save` button is pressed. Thing the modal prompt was implemented to remind users to tick off pass encounters as visited, so have kept it as is and not displaying any modal for cancelled appointments.
1.
2.
> 4250 Status set as cancelled but pop up for save encountered as visited appears

- package.json
- server/graphql/general/src/queries/tests/master_lists.rs
- server/repository/src/db_diesel/item.rs
- server/repository/src/db_diesel/master_list_row.rs
- server/repository/src/migrations/mod.rs
- server/repository/src/migrations/v2_02_02/master_list.rs
- server/repository/src/migrations/v2_02_02/mod.rs
- server/repository/src/migrations/v2_03_00/mod.rs
- server/repository/src/mock/full_master_list.rs
- server/repository/src/mock/test_master_list_repository.rs
- server/repository/src/mock/test_requisition_service.rs
- server/repository/src/tests.rs
- server/service/src/dashboard/item_count.rs
- server/service/src/invoice/inbound_shipment/add_from_master_list.rs
- server/service/src/invoice/outbound_shipment/add_from_master_list.rs
- server/service/src/requisition/request_requisition/add_from_master_list.rs
- server/service/src/stock_line/tests/query.rs
- server/service/src/sync/test/test_data/master_list.rs
- server/service/src/sync/translations/master_list.rs
Fixes #4703 (Part 1)
Adds two new fields to `master_list`
Adds translation tests for new fields (using the same names are in mSupply when it is updated)
Updates test cases to use default values for master list fields.
Using these new fields will be in the next PR...
> Add is_default_price_list and discount to master list

- client/packages/common/src/intl/locales/en/dispensary.json
- client/packages/programs/src/api/api.ts
- client/packages/programs/src/api/operations.generated.ts
- client/packages/programs/src/api/operations.graphql
- client/packages/system/src/Encounter/DetailView/DetailView.tsx
Fixes #4709
Adds new tab to immunisation program encounters, to initially show the vaccine card (actually vaccine card to come 😉)
1.
2.
> add vax card tab for immunisation program encounters

- client/packages/common/src/types/schema.ts
- client/packages/system/src/Report/api/hooks/useGenerateReport.ts
- client/packages/system/src/Report/api/operations.generated.ts
- client/packages/system/src/Report/api/operations.graphql
- server/graphql/reports/src/lib.rs
- server/graphql/reports/src/print.rs
- server/service/src/report/report_service.rs
Fixes #4720 
Adds front end language to report generation translation function
1.
2.
> Pass front end language to report generation

- server/repository/src/db_diesel/changelog/changelog.rs
- server/repository/src/db_diesel/demographic_indicator_row.rs
- server/repository/src/db_diesel/vaccine_course/vaccine_course_dose_row.rs
- server/repository/src/db_diesel/vaccine_course/vaccine_course_item_row.rs
- server/repository/src/db_diesel/vaccine_course/vaccine_course_row.rs
- server/repository/src/migrations/v2_03_00/add_vaccine_course_changelog_table_names.rs
- server/repository/src/migrations/v2_03_00/mod.rs
- server/service/src/sync/test/test_data/demographic_indicator.rs
- server/service/src/sync/test/test_data/mod.rs
- server/service/src/sync/test/test_data/vaccine_course.rs
- server/service/src/sync/test/test_data/vaccine_course_dose.rs
- server/service/src/sync/test/test_data/vaccine_course_item.rs
- server/service/src/sync/translations/demographic_indicator.rs
- server/service/src/sync/translations/mod.rs
- server/service/src/sync/translations/vaccine_course.rs
- server/service/src/sync/translations/vaccine_course_dose.rs
- server/service/src/sync/translations/vaccine_course_item.rs
Fixes #4729
Adds vaccine course data to v6 sync so it is accessible for remote sites
> 4729 sync out vaccine course data

- client/packages/common/src/types/schema.ts
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/columns.ts
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/hooks/useDraftOutboundLines.tsx
- client/packages/invoices/src/OutboundShipment/api/api.ts
- client/packages/invoices/src/utils.ts
- server/graphql/invoice_line/src/mutations/outbound_shipment_line/line/insert.rs
- server/graphql/invoice_line/src/mutations/outbound_shipment_line/line/update.rs
- server/service/src/invoice_line/stock_out_line/insert/generate.rs
- server/service/src/invoice_line/stock_out_line/insert/mod.rs
- server/service/src/invoice_line/stock_out_line/update/generate.rs
- server/service/src/invoice_line/stock_out_line/update/mod.rs
Fixes #4763
I think this covers off the important things from earlier code reviews, let me know if I missed something.
Didn't do the test `with_service_provider` refactor for now, might be good to create a refactor issue for that, and go through doing a big update, so people tend to copy the new pattern instead of the old?
Two new issues raised from my testing, not sure if we go through triage first?
> 4763 cleanup pricing discounts

- server/repository/src/db_diesel/stock_movement.rs
- server/service/src/stock_line/historical_stock.rs
- server/service/src/stock_line/mod.rs
- server/service/src/stock_line/tests/historical_stock.rs
- server/service/src/stock_line/tests/mod.rs
Fixes #4474
New function `get_historical_stock_lines` and test case
- I'm using the stock movement view, does that miss stock that's just allocated rather than actually picked/sent etc?
- Does inventory adjustments or stock takes mean we need to account for something differently?
- Are there any test cases/scenarios I've missed?
- Is it safe to just adjust available_packs as I'm doing? Do we need to do something with total packs too?
- Is the overall approach/math valid? What am I missing?
I think there is a potential for a temporary ledger issue with this approach.
We need to take the minimum stock level as the available amount (the latest stock level might not be the minimum)
Will update this in another PR...
1.
2.
> 4774 backlog prescription entry backdated stock levels service

- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/intl/locales/en/distribution.json
Fixes #4811
Fix translation namespace missing from common
I've found it snuck in [here](https://github.com/msupply-foundation/open-msupply/commit/7474f03d7c068c7b55cf1d40e57e02aeb09f8477)
No reason that I can see that other strings would be affected - but does highlight our not quite type safe locale keys as this is hard to see and trace.
Maybe an RnD project to make sure we don't encounter gaps like this in future?
You can check this by going to internal orders and adding from master list
no documentation changes required
> fix translations -  Move string to common

- package.json
- server/graphql/general/src/queries/master_list.rs
- server/repository/src/db_diesel/master_list.rs
- server/service/src/pricing/item_price.rs
Fixes #4825 
Finds the best available discount for an item's discount.
1.
2.
> 4825 fix handling of 0 discount masterlists

- server/graphql/programs/src/mutations/vaccination/insert.rs
- server/repository/src/mock/vaccination.rs
- server/service/src/vaccination/get_vaccination_card.rs
- server/service/src/vaccination/insert/mod.rs
- server/service/src/vaccination/insert/validate.rs
- server/service/src/vaccination/update/mod.rs
- server/service/src/vaccination/update/validate.rs
- server/service/src/vaccination/validate.rs
Fixes #4713
Just adds logic to check that the previous dose has been when attempting to insert a vaccination.
I refactored the `get_related_vaccinations` method so that it takes a vaccination dose input rather than a vaccination, as the vaccination doesn't yet exist when inserting. The output of the method (previous dose, next dose) remains unchanged, we just get there a different way.
Update tests confirmed still working. Not sure if I should add another case for the Insert?
> #4173 Prevent dose skipping

- client/packages/programs/src/JsonForms/common/components/DateTime.tsx
Fixes #4721
Date is already being formatted in component so don't need to format twice.
1.
2.
> 4721 Program enrolment date not populated in edit modal

- client/packages/common/src/ui/components/portals/AppBarButtons/AppBarButtons.tsx
Fixes #4691
Was trying to find where the padding/margin was... but looks like it was a min-height set on some element... so have added padding to account for wrapping in App Bar Button
1.
2.
> 4691 Wrapped AppBarButtons have no margin

- client/packages/invoices/src/Returns/SupplierDetailView/Toolbar.tsx
Fixes #4684
Disable supplier selection if supplier return was created from inbound shipment.
1.
2.
> 4684 Can change the other party (supplier) of automatic supplier returns

- client/packages/invoices/src/Prescriptions/DetailView/Toolbar.tsx
- server/service/src/invoice/prescription/insert/generate.rs
- server/service/src/invoice/prescription/update/generate.rs
Fixes #4864
Aligns datepicker with rest of the inputs in dispensing.
Defaults `prescription date` to created datetime
Sets picked_date to prescription date if we change the date time for a prescription (by setting it at verified time)
Disables date input after verified
Do we still want the prescription date in the more tab?
> 4864 back date UI

- client/packages/common/src/intl/locales/en/dispensary.json
- client/packages/common/src/styles/theme.ts
- client/packages/common/src/types/schema.ts
- client/packages/system/src/Vaccination/Components/VaccineCardTable.tsx
- client/packages/system/src/Vaccination/api/operations.generated.ts
- client/packages/system/src/Vaccination/api/operations.graphql
- server/graphql/types/src/types/program/vaccination_card.rs
- server/service/src/vaccination/get_vaccination_card.rs
- server/util/src/constants.rs
Fixes #4805
(In Draft cos there's one Rust compilation error in the GraphQL layer that I can't quite resolve)
- Returns "status" from server as an enum value "Given", "NotGiven", "Pending", "Late" or `null`, based on patient age/vax status etc.
- Front-end maps this enum value to appropriate display chip instead of just the boolean `given` field
See inline comments
> #4805 Vaccination card statuses

- client/packages/requisitions/src/ResponseRequisition/ListView/ListView.tsx
Fixes #4685
Disables sort by number of shipments created from requisitions. 
1.
2.
> 4685 Requisitions: number of shipments sort actually sorts by requisition num 

- client/packages/common/src/types/schema.ts
- client/packages/system/src/Vaccination/Components/VaccinationModal.tsx
- client/packages/system/src/Vaccination/Components/getSwitchReason.test.ts
- client/packages/system/src/Vaccination/Components/getSwitchReason.ts
- client/packages/system/src/Vaccination/api/useVaccination.ts
- server/graphql/programs/src/mutations/vaccination/update.rs
- server/service/src/vaccination/generate.rs
- server/service/src/vaccination/update/generate.rs
- server/service/src/vaccination/update/mod.rs
- server/service/src/vaccination/update/validate.rs
Fixes #4883
Ensures invoices are updated when facility is changed from this facility to other.
Also fixes the `record historic transaction` toggle showing up when it shouldn't
ALSO
1.
2.
> 4883 create return when not this facility

- client/packages/inventory/src/Stocktake/DetailView/ContentArea/ContentArea.tsx
- client/packages/inventory/src/Stocktake/DetailView/Toolbar.tsx
- client/packages/inventory/src/Stocktake/api/hooks/line/useStocktakeRows.ts
Fixes #3175
Remove the `group by item` toggle in stocktake. Another issue has been created for group by to be refactored in backend
1. Any mention of group by in stocktake docs
2. Screenshots showing the group by item toggle
> 3175 Stocktake: something's wrong with the pagination

- client/packages/common/src/intl/currency/currency.ts
Fixes #4910
Possible fix for adding the KMF currency for Comoros
Couldn't figure out how to test this...
I can't change the default currency in my mSupply, and I can't seem to change currency in Mac OS either.
I did try this incantaion...
`defaults write NSGlobalDomain AppleLocale -string "en_US@currency=KMF`
And set my language to `en_US` but it didn't apply. It's possible I need to restart?
> 4910 add support for kmf as a currency

- client/packages/system/src/Encounter/DetailView/DetailView.tsx
Fixes #4819
Return undefined if status is not Pending since we aren't covering Visited or Cancelled Encounter statuses
https://github.com/user-attachments/assets/bd628c20-3886-4757-81b8-a27d44c1ce31
Logical statuses are derived from `Encounter Status: Pending` and are not saved in the database. 
If start datetime is greater than now then the logical status  = Scheduled
If less than now then logical status = Missed
P.S... Don't think the users should be able to change status to Visited if encounter is scheduled for the future...
1.
2.
> 4819 'Encounter missed' warning doesn't disappear until refresh

- client/packages/invoices/src/Prescriptions/DetailView/columns.ts
Fixes #4764
Previously the unit price was shown as the sum of all the pack price per line.
Now it shows the average...
We maybe should just show [Multiple] if there are different prices?
Should the title be updated to show average?
> Show Average unit price in prescriptions

- client/packages/common/src/intl/utils/DateUtils.ts
- client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/hooks/useDraftPrescriptionLines.tsx
- client/packages/invoices/src/Prescriptions/DetailView/Toolbar.tsx
- client/packages/invoices/src/StockOut/utils.tsx
Fixes #4900
Removes default of `allocated_date` to `created_date`
Shows today's date in the Date Picker (even though no date is specified in backend)
Defaults the time of a backdating to midnight local time (from the frontend)
Adjusts the Total Stock in store to show as the total stock in store plus what allocated in this line.
This mi required because prescription lines automatically go to `picked` but this means they are removed from the stock line, it's not then clear how the stock line can be adjusted.
Doing a separate PR for adding a `backdated_datetime` into the backend and some logic cleanup
> 4900 improve stock numbers backdated

- client/packages/common/src/ui/layout/tables/components/Cells/CurrencyCell.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/columns.ts
Fixes #4765
- Corrects the calculation for unit price.
- Defaults all price to 10 dp to show in tooltip (displays @ 2dp with ellipsis)
- Pack qty now gets the correct total
- Pack size now shows multiple if the batches are different sizes.
1. Maybe screenshots? 
2. Description of columns to avoid confusion?
> 4765 outbound shipment unit price incorrect, when multiple lines are grouped

- client/packages/programs/src/VaccineCourseEditModal/VaccineCourseEditModal.tsx
Fixes #4884 (sort of)
All it does currently is:
- remove the min/max constraints
- set the new min default to the previous dose maximum
I had started to add some additional constraints (max must be more than min, doses can't overlap), but have stopped that for now for two reasons:
- we're probably going to update this UI anyway, as per #4928, which would make this unnecessary for now
- I encountered a limitation of the `useBufferState` hook, where it doesn't update the local state value if the external data has been *reverted* to it's existing value after a user input change. So we'd need to either change this, or find a way to pass the *full* data set into the cell so we can compare rows within the cell.
> #4884 Vax config age range improvement

- client/packages/invoices/src/InboundShipment/DetailView/Footer/StatusChangeButton.tsx
Fixes #4941
Moves the early returns to below the hook calls, so we don't get the "rendered fewer hooks than the previous render" crash
1.
2.
> 4941 inbound shipment crashes when status changed to delivered

- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/intl/locales/fr/common.json
- client/packages/common/src/intl/locales/fr/reports.json
- client/packages/system/src/Report/components/ReportArgumentsModal.tsx
Partially fixes: https://github.com/msupply-foundation/open-msupply-reports/issues/105
Adds french translations that relate to general reports. For report filter modal and for report category headers
These translations are in develop, but I had to manually insert them here, location of json file was change and argument/filter modal title was not translated yet in 2.2.3 
Check translation of report categories in french language and report filter modal (note the filters themselves are not translated here, but the modal title and the dscirption should be)
1.
2.
> 105-report-translations

- server/repository/src/db_diesel/stock_line.rs
- server/service/src/stocktake/delete/mod.rs
- server/service/src/stocktake/update/mod.rs
- server/service/src/stocktake_line/update/mod.rs
Fixes #243253643513
Soz... thought I got them all...
1.
2.
> Remove unused imports

- client/packages/common/src/intl/currency/currency.ts
Fixes #4977
Fixes app crashing if spanish language is selected.
This fixes the urgent issue (the app crashing) but when we deploy to different spanish speaking regions, we make need to refine - some countries use `,` as the decimal separator, others use `.` 👀 
1.
2.
> 4977 Spanish currency crash

- server/service/src/vaccine_course/delete.rs
- server/service/src/vaccine_course/test/delete.rs
Fixes #4924
Soft deletes vaccine course doses when vaccine course is soft deleted
1.
2.
> delete doses on course delete

- client/packages/system/src/Patient/PatientView/PatientView.tsx
Fixes #4912
Parse of estimated date of birth in the json data since the insert and update patient input doesn't contain this field.
1.
2.
> 4912 Can't create/edit patients with a Date of Birth

- client/packages/common/src/types/schema.ts
- client/packages/system/src/IndicatorsDemographics/api/api.ts
- client/packages/system/src/IndicatorsDemographics/api/hooks/utils/useDemographicApi.ts
- client/packages/system/src/IndicatorsDemographics/api/operations.generated.ts
- client/packages/system/src/IndicatorsDemographics/api/operations.graphql
- server/graphql/demographic/src/lib.rs
Fixes #4963
- Use the QueryDemographics permission for all demographic query endpoints (this requires no permission to view)
- Fixes the `__typename` error
- Passes in store_id to check user has correct permission for store
QueryDemographics no longer requires permission, so should never get the permission denied pop up in vaccination... but will need to refactor this bit of code if permission does change in the future.
1.
2.
> 4963 demographic permissions

- client/packages/system/src/Stock/Components/InventoryAdjustment/InventoryAdjustmentModal.tsx
Fixes #4996 
Adds the keyboard height adjustment to inventory adjustment modal for android
Refactor issue created: #5009
1.
2.
> 4996 inventory adjustment modal height fix

- server/service/src/processors/transfer/requisition/test.rs
Fixes #4608 
Turned out to be a simple fix, but was very hard to debug and track down.
Basically the problem turned out to be that in the test case, we were first updating the status of the request requisition to approved, then updating the approved quantities second. This created a short period of time, where if the processor ran, it could get the updated status for the request requisition and process the lines even though these hadn't been updated yet.
I'm pretty confident that we always have lines inserted before updating invoices, although I'm a bit worried about sync.
It will update the invoice first I think, but does do it in a transaction now, and calls the processor only after sync is finished so *I think* we're ok, 
*Keen for input/confirmation that we don't have the same …
> Fix intermittent test failure for transfers

- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/types/schema.ts
- client/packages/system/src/Patient/PatientView/PatientView.tsx
- client/packages/system/src/Vaccination/Components/VaccineCardTable.tsx
- client/packages/system/src/Vaccination/api/operations.generated.ts
- client/packages/system/src/Vaccination/api/operations.graphql
- server/graphql/types/src/types/program/vaccination_card.rs
- server/repository/src/db_diesel/program_enrolment_row.rs
- server/repository/src/migrations/v2_03_00/add_store_id_to_program_enrolment.rs
- server/repository/src/migrations/v2_03_00/mod.rs
- server/repository/src/mock/form_schema.rs
- server/service/src/programs/program_enrolment/program_enrolment_updated.rs
- server/service/src/programs/program_enrolment/program_schema.rs
- server/service/src/programs/schemas/program_enrolment.json
- server/service/src/sync/integrate_document.rs
Fixes #5014
Hides the vaccination card for patients that have been fetched from another facility, where they were already enrolled in the immunisation program.
This prevents the patient being inadvertently enrolled/vaccinated twice!
1. Probably should be mentioned that this is the behaviour if patients are fetched. We don't support vaccinations across multiple facilities at this time
2.
> 5014 can give wrong vaccinations on new site

- client/packages/common/src/intl/locales/en/programs.json
- client/packages/common/src/ui/layout/tables/components/Cells/MultiNumberInputCell/MultiNumberInputCell.tsx
- client/packages/programs/src/VaccineCourseEditModal/VaccineCourseEditModal.tsx
- client/packages/system/src/Vaccination/Components/VaccineCardTable.tsx
Fixes #5003 
Fixes #5016
Adds a max value of 11 to the months input on dose modal, so it doesn't start updating the years field if months >= 12.
Left the code that would update the years if months max was not set, possibly useful behaviour somewhere? 🤷‍♀️ 
and wording fix for #5016
1.
2.
> 5003 months years input fix

- package.json
- server/Cargo.lock
- server/Cargo.toml
- server/android/Cargo.toml
- server/server/Cargo.toml
- server/server/src/main.rs
- server/windows/Cargo.toml
- server/windows/src/windows.rs
Fixes #5046
Add panic log to 2.2, similar to #4666, this would allow windows service to log panic.
Also increment version to 2.2
Testing would require a way to panic while service is running, and do it withing the main thread (not just graphql endpoint), this is a bit hard to do but we do have a service that is crashing, build can be validated there
> Add log on panic to 2.2

- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/hooks/useDraftOutboundLines.tsx
- client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/hooks/useDraftPrescriptionLines.tsx
- client/packages/invoices/src/StockOut/hooks/usePackSizeController.test.tsx
- client/packages/invoices/src/StockOut/utils.test.ts
- client/packages/invoices/src/StockOut/utils.tsx
Fixes #4936 
Changes the code for creating draftStockOutLines to decide when to adjust stock levels based on 
Logic should be
Available Stock show is the total of the available stock in store (e.g total stock - allocated to other invoices) plus the amount  you have allocated or picked on this invoice line.
Total stock (in store) is also adjusted to include what you have allocated to this line too, once the invoice is in the picked state.
This is because by updating that line you can adjust the total stock and or available stock levels, so we need to show the adjusted stock levels to avoid confusion about how much you can or can't allocate to the invoice.
Any status things I'm missing?
Is there some kind of magic logic from before that I've missed?
Is there some documentation on this that …
> Use invoice status to adjustStockLines

- package.json
- server/server/src/lib.rs
- server/service/src/app_data.rs
Fixes #5053
Uses global constant RwLock to get and set hardware id
Would need to create a carry over refactor issue to:
* Remove app data service and set and get hardware id from the const
* Remove hardware id from settings and use set hardware id in android ?
* For non android, first time get_hardware_id is called get system hardware id ? 
* Above would allow integration test to work without too much extra (with this change I think integration tests will be broken)
Sync for existing sites does not break and existing hardware id is used
1.
2.
> 5053-Store-hardware-id-in-memory

- server/service/src/sync/translations/stocktake.rs
Fixes #4766
Populates stocktake finalised datetime in translators
1.
2.
> 4766 When migrating a finalised stocktake there's no finalised date

- server/repository/src/migrations/constants.rs
- server/repository/src/migrations/v2_04_00/add_expected_lifespan_to_assets.rs
- server/repository/src/migrations/v2_04_00/mod.rs
Fixes #3908
Adds migrations to add a new property for lifespan to the asset catalogue.
Existing asset catalogue items get a 10 year default, all new items need to have this entered to work.
No frontend changes needed!
1.
2.
> Asset Property for lifespan, Default existing assets to 10 years

- client/packages/coldchain/src/Equipment/Components/Status.tsx
- client/packages/coldchain/src/Equipment/ListView/Toolbar.tsx
- client/packages/coldchain/src/Equipment/utils.ts
- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/styles/theme.ts
- client/packages/common/src/types/schema.ts
- client/packages/system/src/Asset/utils.ts
- server/graphql/asset/src/types/asset_log.rs
- server/repository/src/db_diesel/assets/asset_log_row.rs
- server/repository/src/migrations/v2_04_00/add_unserviceable_status_to_asset_status_enum.rs
- server/repository/src/migrations/v2_04_00/mod.rs
Fixes #4759 
Add "Unserviceable" status value to `StatusType` enum (and related) in back-end, and make available as a selectable option in front-end.
I notice the asset list view at `/catalogue/assets` doesn't show the status column, nor a filter for it. Should it?
> #4759 Add new equipment status: "Unserviceable"

- server/graphql/requisition/src/lib.rs
- server/graphql/requisition/src/mutations/response_requisition/insert.rs
- server/graphql/requisition/src/mutations/response_requisition/mod.rs
- server/service/src/requisition/mod.rs
- server/service/src/requisition/response_requisition/insert.rs
- server/service/src/requisition/response_requisition/mod.rs
Part of #5118
Service and endpoint to create response requisitions (normal).
1.
2.
> 5118 add service + endpoint to create a response requisition

- client/packages/host/src/api/hooks/settings/namePropertyData.ts
Fixes #3917 
Adds packaging level preference to facility properties:
I think most of this will be covered by James #5208 PR... will review if any areas of the issue are missing after!
1.
2.
> 3917 add packaging level to facility properties

- client/packages/common/src/types/schema.ts
- client/packages/system/src/Name/Components/ManufacturerSearchInput/ManufacturerSearchInput.tsx
- client/packages/system/src/Name/api/api.ts
- client/packages/system/src/Name/api/hooks/document/index.ts
- client/packages/system/src/Name/api/hooks/document/useManufacturers.ts
- client/packages/system/src/Name/api/hooks/index.ts
- server/graphql/general/src/queries/names.rs
- server/graphql/general/src/queries/tests/names.rs
- server/repository/src/db_diesel/name.rs
Fixes #5248 
Allows selecting manufacuturers in Item Variants
Nothing too controversial here I hope!
1.
2.
> 5248 gaps manufacturer list

- client/packages/common/src/intl/utils/DateUtils.test.ts
- client/packages/common/src/intl/utils/DateUtils.ts
- client/packages/common/src/ui/components/inputs/Filters/DateFilter.tsx
- client/packages/programs/src/JsonForms/common/components/Date.tsx
- client/packages/programs/src/JsonForms/components/DateOfBirth.tsx
- client/packages/system/src/Patient/PatientView/PatientSummary.tsx
- client/packages/system/src/Stock/Components/StockLineForm.tsx
- client/packages/system/src/Stock/ListView/ListView.tsx
Fixes #5247
Note: in order to see the problem (and the solution), you'll probably need to set your computer's timezone to something that is still in "yesterday".
Okay, so the problem is that the values in question are "naive" dates (i.e. timezone is irrelevant), but the date filters and Patient summary were using the `getDateOrNull` method, which assumes a time stamp of "00:00:00" if not is specified, so dates get converted to the day before if local timezone is still in "yesterday" relative to UTC.
There was a method to return a "naive" version of the date, which I've used, but made a couple of small changes to it:
- changed the name from `getLocalTime` to `getNaiveDate` (it's kind of the opposite of "get local time", so I found the current name confusing/misleading)
- moved the method …
> #5247 Naive date fix

- client/packages/android/build_remote_server_libs.sh
- client/packages/android/package.json
- server/android/.cargo/config.toml
Fixes Android build (I think)
This build only targets `armv8`/`aarch-line-android` e.g. 64bit tablets
I think this is probably ok due to our docs already stating you need a 64bit android version???
Arm 32 was failing to build `cranelift` due to this error.
`cranelift-codegen v0.110.3`
```
error when identifying target: "no supported isa found for arch `armv7`”
```
Which we think was introduced with WASM for the reports...
1.
2.
> Build for 64bit android only

- client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/InboundLineEditForm.tsx
Fixes #5289
Very small fix required to make item clearable. It was only running the `onChangeItem` function if the input had a truthy value, so when clearing, the `null` input wasn't being handled.
There's still some outstanding weirdness involving the debouncing when searching the item input, but that's on all item searches, so we can look at that later if we think it's a problem
> #5289 Clear inbound item selection

- client/packages/common/src/hooks/useConfirmOnLeaving/useConfirmOnLeaving.ts
Fixes #5285
Uses the confirmation modal rather than the `confirm` method, giving:
Patients, when changing tabs:
R&R form, when navigating away from page:
Have used the confirmation modal.
It looks a little nicer
I think this should be targeted for develop, there's no urgency to get it into the patch release. Have just targeted the patch branch to make the PR cleaner to read, ahead of it being merged back into develop.
1.
2.
> Improve confirm on leaving modal

- server/service/src/sync/translations/activity_log.rs
- server/service/src/sync/translations/name.rs
- server/service/src/sync/translations/stocktake_line.rs
Fixes #5282
Initialising from reference data was failing due to a missing `om_date_of_death`.
I've fixed a couple of other errors too such as missing fields on `activity_log` and `stock_take_line`
There's still a few other sync errors but don't seem to critical...
Are we ok with defaults for these fields?
At some point we might need to update the reference data file, but this seemed like a nice quick fix...
1.
2.
> 5282 Allow initialisation from export

- client/packages/invoices/src/Prescriptions/DetailView/Toolbar.tsx
Fixes #5164
This seems too simple, but it appears to fix the problem! 🤷‍♂️
I just changed the `onChange` prop the DatePicker to `onAccept`, so the `handleDateChange` function doesn't get called when the picker opens (which it does on Mobile)
Haven't tested on Tablet specifically. However, can replicate the problem by changing to a mobile layout with browser DevTools, and this fix works for that.
> #5164 Fix Prescriptions DatePicker/Confirmation conflict

- server/graphql/item_bundle/src/mutations/upsert.rs
- server/repository/src/mock/item_variant.rs
- server/service/src/invoice_line/stock_in_line/insert/validate.rs
- server/service/src/invoice_line/stock_in_line/update/validate.rs
- server/service/src/item/bundled_item/test/mod.rs
- server/service/src/item/bundled_item/upsert.rs
- server/service/src/item/packaging_variant/upsert.rs
- server/service/src/lib.rs
- server/service/src/stock_line/update.rs
Fixes #5300
Adds validations for bundled items upsert
Anything else missing?
Should some of these be strucutured errors?
If so should we change that once we have UI?
1.
2.
> Bundled Item Validations

- client/packages/invoices/src/Prescriptions/DetailView/Toolbar.tsx
- server/service/src/invoice/prescription/update/generate.rs
Fixes #5325
We're now comparing if a `backdated date` is in the future, rather than if just greater than created date.
We're displaying the following dates in the frontend (in order)
`backdated_datetime`
`picked_datetime`
`created_datetime`
We could handle the situation where we're backdating to a date after created_date differently, but simply setting the other fields such as `picked_date`, as it's kind of not backdated. 
This ways simpler though, which I like...
1.
2.
> Improve handing of backdated date

- package.json
- server/repository/src/db_diesel/changelog/changelog.rs
- server/repository/src/db_diesel/item_row.rs
- server/service/src/sync/translations/item.rs
Fixes #5100
For adding all the GAPS data, it's much simpler if we can do that all from one script from OMS central. So adds the `to_sync_record` implementation for items, so new items can be created and synced to legacy from OMS central. 
Will leave with you @jmbrunskill, whether you think best to add data via DB script or if we want more code changes for this issues to try and add through the service layer + get the changelogs etc. for free?
1.
2.
> 5100 sync items to legacy

- client/packages/common/src/types/schema.ts
- client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
- client/packages/invoices/src/Returns/modals/CustomerReturn/ReturnQuantitiesTable.tsx
- client/packages/requisitions/src/ResponseRequisition/api/operations.generated.ts
- client/packages/system/src/Item/api/hooks/useItemVariant/index.ts
- client/packages/system/src/Item/api/hooks/useItemVariant/useIsItemVariantsEnabled.ts
- client/packages/system/src/Item/api/hooks/useItemVariant/useItemVariant.ts
- client/packages/system/src/Item/api/hooks/useItemVariant/useItemVariantsConfigured.ts
- client/packages/system/src/Item/api/operations.generated.ts
- client/packages/system/src/Item/api/operations.graphql
- client/packages/system/src/Stock/Components/StockLineForm.tsx
- server/graphql/item_variant/src/lib.rs
- server/graphql/lib.rs
Fixes #5362
Hides the item variant column on inbound modals/the stock detail page, if no item variants have been configured.
Make sure it feels okay to be hiding/showing base on there being _any_ variants set up, rather than for the item in question?
1.
2.
> 5362 hide item variants if none configured

- client/packages/common/src/intl/locales/en/common.json
- client/packages/system/src/Stock/Components/Ledger/useLedgerColumns.ts
Fixes #4935
Change number column to say Invoice no.:
Wrapping looks a bit silly on other pages like outbound shipment - Should those continue to only say `Number`?
1.
2.
> 4935 Change ledger number column to "invoice no."

- client/packages/invoices/src/Returns/CustomerDetailView/SidePanel/AdditionalInfoSection.tsx
- client/packages/invoices/src/Returns/CustomerDetailView/Toolbar.tsx
- client/packages/invoices/src/Returns/api/hooks/document/useCustomerReturn.ts
Fixes #4952 
Updated useCustomerReturn hook so any change in state would create a draft object for the CustomerReturnFragment. This is then patched in so the correct message banner will display when the status is changed from shipped to delivered
> change buffered state to draft

- client/packages/coldchain/src/Equipment/ListView/AddFromScannerButton.tsx
- client/packages/coldchain/src/Equipment/api/api.ts
- client/packages/coldchain/src/Equipment/api/hooks/document/index.ts
- client/packages/coldchain/src/Equipment/api/hooks/document/useAsset.ts
- client/packages/coldchain/src/Equipment/api/hooks/index.ts
- client/packages/coldchain/src/Equipment/api/operations.generated.ts
- client/packages/coldchain/src/Equipment/api/operations.graphql
- client/packages/common/src/types/schema.ts
- client/packages/common/src/utils/BarcodeScannerContext.tsx
- server/graphql/asset/src/lib.rs
- server/graphql/asset/src/types/asset.rs
- server/graphql/asset/src/types/gs1.rs
- server/graphql/asset/src/types/mod.rs
- server/service/src/asset/mod.rs
- server/service/src/asset/parse.rs
- server/util/src/gs1.rs
Fixes #5390
I tried to make minimal changes for this, but it should allow us to scan GS1 formatted barcodes and create assets from them. 
Maybe/probably should remove the parsing of human readable string? Figured I'd leave it there for now as it might come in handy, and I didn't want to have to re-create data for all my tests cases and aiming for minimal changes here :)
Thoughts on this?
> NOTE, scanning these 2d Matrixes in github `dark mode` or with a black background doesn't work well...
> NOTE: in general scanning 2d Matrixes seems much less reliable than QR Codes, need to have camera straight on for example
Scan a GS1 formatted Data Matrix here (Note: or create your own for testing)
PQS Asset Type: E003/002
Serial Number: S12345678 …
> 5390 correctly handle gs1 2d data matrix format

- client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/PrescriptionLineEdit.tsx
Fixes #4915 
Changed the OK button for creating/editing a prescription from a Dialog button to a Loading button. Uses loading state to prevent clicking OK multiple times, therefore preventing the action that leads to the error.
Updated to match the original button with color, aria label. New loading icon is blue to match buttons
If the OK button was clicked more than once whilst loading, the api was called more than once creating the 'Line already exists' error
> Change OK button to Loading Button type

- server/repository/src/db_diesel/filter_sort_pagination.rs
- server/repository/src/db_diesel/indicator_value.rs
Fixes #5422
- Return all indicator values
1.
2.
> 5422 indicator api not retrieving an indicator value

- client/packages/android/README.MD
- client/packages/android/app/src/main/java/org/openmsupply/client/ExtendedWebViewClient.java
- client/packages/android/app/src/main/java/org/openmsupply/client/NativeApi.java
- client/packages/android/app/src/main/java/org/openmsupply/client/RemoteServer.java
Fixes #5383 
This behaviour with Android 11/12 isn't entirely consistent, this appears to be an improvement over the old method at least.
After much re-discovery of how things work and various attempts to fix similar issues.
E.g. https://github.com/msupply-foundation/open-msupply/pull/4390
I've changed the logic for the `ExtendedWebViewClient` to generate the javascript to inject on App Start and at page_load (as a backup method).
It seemed like in my emulators that the code that registers the plugins, and the web view constractor run concurrently so ordering of operations can't be guarenteed.
Here's what the `logcat` output looks like now.
```
2024-11-15 17:15:53.901  7282-7282  Capacitor               org.openmsupply.client               D  Starting BridgeActivity
2024-11-15 …
```
> 5383 Android - Load Plugins after they've be registered properly

- client/packages/requisitions/src/ResponseRequisition/DetailView/DetailView.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/AppBarButtons.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/Footer.tsx
- client/packages/requisitions/src/ResponseRequisition/ListView/AppBarButtons.tsx
- client/packages/system/src/Item/Components/ListItems/ListItems.tsx
Fixes #5448
Don't replace history in Response Requisition navigation 
1.
2.
> 5448 Navigating back from editing requisition line goes back to requisition list rather than to the requisition being modified

- client/packages/coldchain/src/Equipment/ImportAsset/UploadTab.tsx
- client/packages/common/src/intl/locales/en/common.json
Fixes #5423
Show info popup when trying to download CCE template on android:
1. Could mention that download is not available on android. Also fine to leave I think 😁 
2.
> 5423 cant download CCE template on android

- client/packages/system/src/Location/Components/LocationSearchInput.tsx
> 5442 Include location type in selected location option

- server/graphql/reports/src/print.rs
- server/reports/expiring-items/2_3_0/src/template.html
- server/reports/item-usage/2_3_0/src/template.html
- server/reports/stock-detail/2_3_0/manifest.json
- server/reports/stock-detail/2_3_0/src/template.html
- server/reports/stock-status/2_3_0/src/template.html
- server/service/src/report/report_service.rs
Fixes #5443
Also fixes other reports not loading due to standard reports not being re-run and generated, and report builder not working
* Fix expiry report (it was failing if any 'batch' names are null)
* Change access of 'data' in template to be from 'data' rather then nested 'data' @fergie-nz this was fixed in the wasm sorting PR, but not in template, can you please re-test in your PRs (maybe worth having a checklist before PR is merged, like, run your own test, check diff again, etc..)
* re-generate standard reports -> this file should not be in our repo, we should re-run report generation during build.
Although this PR fixes report in dev env, there seems to be an error on android in built APK:
Doing a quick investigate, hold of merge, i might fix it in this PR
The last commit: …
> 5443 Fix expiring reports

- server/graphql/general/src/queries/item.rs
- server/repository/src/db_diesel/item.rs
Fixes #5367
Adds category ID to item filter, to use from custom JSON form component
Note: we currently only join at, and therefore support search by, lowest level category - this is all we need for RH module... but where should I capture this? Don't want someone confused trying to filter by higher level category and it not working?
You can test with this query - compare results with item search in 4D:
```gql
query itemByCategoryId($storeId: String!, $categoryId: String!) {
items(
storeId: $storeId
filter: { categoryId: $categoryId }
) {
... on ItemConnector {
nodes {
id
name
}
}
}
}
```
1.
2.
> 5367 add category id to item filter

- server/repository/src/db_diesel/item_variant/bundled_item.rs
- server/repository/src/diesel_macros.rs
- server/service/src/item/item_variant/delete.rs
- server/service/src/item/item_variant/test/mod.rs
Fixes #5461 
Soft deleted bundled items when variants are deleted
1.
2.
> 5461 delete bundled items when item variant deleted

- client/packages/requisitions/src/ResponseRequisition/DetailView/columns.ts
Fixes #5471
Get correct supply quantity
1.
2.
> 5471 Requisition's supply quantity is incorrect

- client/packages/system/src/Item/Components/ColdStorageTypeInput/ColdStorageTypeInput.tsx
Fixes #5410
Added option label to the Cold Storage component, to include min/max temperatures.
Aligned this to match the display in List View
Needed as when making a selection user could only see the name of the cold store, not the temperature range
Screenshot 2024-11-21 at 12 10 08 PM
This component is also used in the Item Variant Modal. My current setup doesn't allow viewing this in localhost, so please view this too
I noticed the label 'Temperature' only appears when the dropdown is selected or has a value. Had a look at fixing it, found an easy fix but would change the design. New design would be in line with other modals
Options:
Update to bigger labels on this PR
Update to bigger labels on a new issue
Look for a way to fix the existing tiny label
New Temperature label example - …
> Add min/max to temperature dropdown

- client/packages/system/src/Clinician/ClinicianSearchInput.tsx
- client/packages/system/src/Patient/Encounter/CreateEncounterModal.tsx
- client/packages/system/src/Patient/Encounter/EncounterSearchInput.tsx
Fixes #4967 
Improved the appearance of the new Encounter window
- Align the beginning of input fields
- Expand text input fields to take up the width of the space
Visit Date is not an expandable field, it also can't go at the top (Encounter type needs to be the first entry). Open to suggestions on further improvements
I have not addressed validation appearance in this PR. To be done in  #4299 Standardise the appearance of required fields across omSupply
1.
2.
> 4967 new encounter window appearance

- server/windows/src/windows.rs
Fixes #5069
A manual rebase from #5490 
Removed the extraneous hook and tested on the mac mini.
before:
```
2024-11-20 15:54:40.721921100 [ERROR] <windows\src/windows.rs:72>:panic occurred PanicHookInfo { payload: Any { .. }, location: Location { file: "C:\\Users\\Administrator\\AppData\\Local\\Jenkins\\.jenkins\\workspace\\omSupplyMain\\server\\server\\src/lib.rs", line: 89, col: 10 }, can_unwind: true, force_no_backtrace: false }
2024-11-20 15:54:40.723844500 [ERROR] <windows\src/windows.rs:72>:panic occurred PanicHookInfo { payload: Any { .. }, location: Location { file: "library\\core\\src\\panicking.rs", line: 221, col: 5 }, can_unwind: false, force_no_backtrace: false }
```
after:
```
2024-11-20 22:12:24.065151100 [ERROR] <log_panics:130>:thread '<unnamed>' panicked at 'called …
```
> Windows panic

- client/packages/system/src/Item/Components/ColdStorageTypeInput/ColdStorageTypeInput.tsx
- client/packages/system/src/Location/ListView/ListView.tsx
Fixes #5408 
Change the separator between Min and Max temperature to the word 'to' instead of '-'
'-' is the same symbol used for negative values, so using 'to' as the separator increases readability
Change in locations list view:
Change in locations edit/add view:
- [] **Part of an epic**: documentation will be completed for the feature as a whole
1. Screenshots updated for UI
2.
> update temperature spacer from '-' to 'to'

- client/packages/common/src/intl/locales/en/common.json
- client/packages/system/src/Item/DetailView/Tabs/ItemVariants/ItemVariantModal.tsx
- client/packages/system/src/Item/DetailView/Tabs/ItemVariants/ItemVariantsTab.tsx
- client/packages/system/src/Location/ListView/ListView.tsx
- client/packages/system/src/Location/ListView/LocationEditModal/LocationEditModal.tsx
- server/repository/src/db_diesel/cold_storage_type.rs
Fixes #5409
Changes the rust query to filter out all cold storage types with a min tempereature = 0 and a max temperature = 0, so that they are not displayed on the front end.
Changes the label of...
- the 'storage type' column in inventory>locations,
- the 'temperature' selector dropdown in the inventory>locations>add location menu
- the 'temperature' in catalogue>detail view>item variants
- the 'temperature in catalogue>detail view> item variant>add variant menu
...to 'cold storage type' to avoid confusion.
This required a new 'label.cold-storage-type', which requires translation.
Have a nice day :)
> 5409 hide temperature ranges if unspecified

- server/service/src/requisition/response_requisition/update.rs
Fixes #5538
Adds not checking for requested == suggested when extra fields aren't set up in store preferences.
> Add check for if extra fields in requisition showing

- client/packages/coldchain/src/Equipment/utils.ts
Fixes #5479 
Add UTC as a suffix to ```created date / time``` and ```modified date / time``` headers in the export csv 
Add UTC as string inside a template literal so that it can work alongside existing translation
Changes needed as time displayed in the equipment log is different to what is displayed in the export file. Clearer label will explicitly state difference is because time is in UTC
1.
2.
> Add UTC to date columns in export file

- client/packages/system/src/Stock/Components/NewStockLineModal.tsx
Fixes #5253
When creating a new stock line, update new item pack size to use item's pre-defined default pack size number
Thanks Laché!
1.
2.
> Update new stock item pack size to use item default

- client/packages/system/src/Item/DetailView/Tabs/ItemVariants/ItemVariantsTab.tsx
Fixes #5410
Allows the user to view the temperature range along with the cold storage type in an item variant in detail view
Is it worth setting a centralised definition for the temperature range display value? (Option renderer?)
It's used in three places, so would need to find and update them all separately if they need changing
1.
2.
> add temperature range to item variants detail

- client/packages/coldchain/src/Equipment/DetailView/DetailView.tsx
- client/packages/coldchain/src/Equipment/api/hooks/document/useAssetUpdate.ts
Fixes #5415
Fixes issue with locations not being available to select when deleting and re-adding locations from assets.
2 problems
First, that after saving an asset, we didn't invalidate the location query and there for didn't see the locations as unassigned.
Second, if deleting a location, if before saving you wanted to add that back in you couldn't.
Pre-exising locations show up at the end of the list.
It might be nice if they were at the top, or we sorted them or something.
Doesn't feel important enough to spend time on to me...
See video in the issue to see how to re-create the issues.
1.
2.
> Bugfixes for asset locations

- client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseEditPage.tsx
Fixes #5562
Show spinner if current item isn't populated and NothingHere if the itemId isn't in the URL
https://github.com/user-attachments/assets/c2d338ed-39df-4a02-955f-3bbd5c5a59e9
1.
2.
> Basic spinner if current item isn't populated yet

- client/packages/common/src/ui/components/buttons/standard/DialogButton.tsx
- client/packages/common/src/ui/components/navigation/ListOptions/ListOptions.tsx
Fixes #5463
- Make list smaller to fit better on screens
- Make variant for previous button same as next button
- Keep current selected item in view when navigating between items
https://github.com/user-attachments/assets/4c1b7238-145e-4f1a-aa37-61e7c49906de
1.
2.
> 5463 manual requisitions some UI improvements to consider

- server/service/src/requisition/response_requisition/insert_program.rs
Part of #5458
Suggested, available and AMC was being calculated incorrectly for response requisitions as they are supposed to be the customer's values not the supplier's, so have removed them for now until discussion in 5458 is concluded.
1.
2.
> Don't calculated suggested quantity

- client/packages/common/src/hooks/useQueryParams/types.ts
- client/packages/common/src/types/schema.ts
- client/packages/invoices/src/index.ts
- client/packages/programs/src/JsonForms/components/Prescription/Prescription.tsx
- client/packages/system/src/Item/Components/StockItemSearchInput/StockItemSearchInput.tsx
- client/packages/system/src/Item/api/api.ts
- client/packages/system/src/Item/api/hooks/useItemStockOnHand/useItemStockOnHand.tsx
- client/packages/system/src/Item/utils.ts
- server/graphql/general/src/queries/item.rs
- server/repository/src/db_diesel/item.rs
- server/repository/src/db_diesel/item_category_row.rs
Fixes #5560
@lache-melvin I've made a new branch `5264-json-forms-prescriptions-2.4.1` which is correctly branched off 2.4.1 and has the fixes for #5551 in it. So now basing this PR of that so it's just the new changes.
Adds support for filtering the Prescription items list by category (name). The category is defined elsewhere in the JSON schema, so this component requires an `itemCategoryPath` option to tell it where to look. If not defined, the item list will show all.
Have updated the UI Schema in the Program schemas repo to reflect these changes, so you'll need to re-import that (I think just the UI schema has changed). (Branch still `djibouti_family_planning`)
You'll also need to add categories and assign some items to them. The category names are:
You can try excluding one of the …
> #5560 JSON Forms Prescription -- category filtering

- server/repository/src/db_diesel/cold_storage_type.rs
Fixes #5409
Correctly filters out only location_types with min and max temperature both 0.0.
E.g. you can now have a temperature range that goes from 0 to 15 for example.
Should have pick this up in code review.
Was actually worried about this and I thought I'd tested it... Here: https://github.com/msupply-foundation/open-msupply/pull/5518#pullrequestreview-2453186364
Not sure what happened!
1.
2.
> 5409 fix location filter

- client/packages/requisitions/src/ResponseRequisition/DetailView/IndicatorEdit/IndicatorEditPage.tsx
Fixes #5610
Disables link in the indicators breadcrumbs as its only needed to load the correct indicators on the page and doesn't link to anything separately.
1.
2.
> Disable breadcrumb link for indicators

- client/packages/inventory/src/Stocktake/api/hooks/line/useStocktakeDeleteSelectedLines.ts
Fixes #5492
isGrouped logic has been removed in the frontend but wasn't removed from the delete selection >.>. This PR allows you to delete stocktake lines.
1.
2.
> 5492 unable to delete lines from a stocktake

- server/repository/src/migrations/v2_04_00/fix_asset_log_reasons_postgres.rs
- server/repository/src/migrations/v2_04_00/mod.rs
Fixes #5583
Fixes an error that only shows up when running a postgres server with open-mSupply.
The reason drop down when doing an asset status update, wasn't populating correctly and errors where thrown
I haven't created a test but would have been good to have one to pick this up originally.
Not sure how much we need to test everything?
Surprised the sync test didn't have a problem, I guess it's not actually persisting it to the db...
1.
2.
> 5583 error operator does not exist text asset log status on asset status page

- client/packages/requisitions/src/ResponseRequisition/DetailView/DetailView.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/IndicatorEdit/IndicatorLineEdit.tsx
Fixes #5634 & #5635
Defaults to 0 if NaN input and hide indicators tab if no indicators
Next:
1.
2.
> 5635 when emptying an hiv indicator from it's default value, it is replaced by a strange text value and you can't change it easily to a valid value

- client/packages/requisitions/src/ResponseRequisition/DetailView/IndicatorEdit/IndicatorEditPage.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/IndicatorEdit/IndicatorLineEdit.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/IndicatorEdit/ListIndicators.tsx
Fixes #5619
Show description + code for HIV indicators and code for regimen.
1.
2.
> 5619 indicators should show indicator line name 

- client/packages/coldchain/src/Equipment/DetailView/Tabs/Summary.tsx
- server/graphql/asset/src/mutations/update.rs
- server/service/src/asset/insert.rs
- server/service/src/asset/update.rs
- server/service/src/asset/validate.rs
Fixes #5392
This is the simplest version of this -- it just makes the Asset number editable after the asset is created. I'll make a follow-up issue to get user input on scanning, as that's a bit more involved and could do with some further planning to make it work nicely.
I notice we're not enforcing unique-ness for Asset number. Should it be?
> Allow editing of asset number

- server/service/src/sync/README.md
Add to sync docs example commits for v6 sync. I realised that there was already somethings like this for asset log reason, but this one is strictly for V6 sync central data sync, would be great to also differentiate other commit examples by type. 
I found this commits based examples of adding different layers very useful, would be great to have one common area for all the different examples like this (yes a bit to maintain but I think saves time on training in the future)
> Add example of v6 central data sync

- client/packages/android/app/src/main/jniLibs/armeabi-v7a/.gitignore
- client/packages/android/build_remote_server_libs.sh
- package.json
- server/android/.cargo/config.toml
Fixes #
Migrates the changes for building 64 bit only android from 2.4
Adds the `opt-level = "s"` flag to reduce the compiled build size...
Here's an APK to try out
https://drive.google.com/file/d/14oAuLnzkPlEvUDEP8LGoIW5-goWcWNgD/view?usp=sharing
1.
2.
> Reduce apk size

- client/packages/host/src/Admin/DisplaySettings.tsx
- client/packages/host/src/Admin/SettingTextArea.tsx
- client/packages/host/src/Admin/Settings.tsx
- client/packages/host/src/Admin/SettingsSection.tsx
- client/packages/host/src/components/AppDrawer/AppDrawer.tsx
Fixes #5599
- Makes the Settings icon in the app drawer available to every user.
- Hides all of the Settings sections except Display settings from every non-admin.
- Hides all the Display settings except the Language settings from every non-admin.
Is it secure: could a malicious party force the custom theme or logo sections, or other settings sections, to be visible somehow?
[ ] log in as an admin and check that all settings sections are visible
[ ] log in as a user with minimum permissions and check that the setting icon is available, but ONLY display settings are visible, and within those settings only language is visible.
[x] **Part of an epic**: documentation will be completed for the feature as a whole
> 5599 adjust settings page permissions

- client/packages/system/src/Encounter/DetailView/DetailView.tsx
Fixes #5691
Resets the `deleteRequest` value to avoid the infinite loop over the `useEffect` function.
I think the `useEffect` chaining using the `deleteRequest` intermediate value is not great React usage, but changing that is a bit of a bigger job so won't do that now. The problem is we can't easily update the data using JSON Forms' `setData` method and then immediately save that changed data in a single render. Something to figure out another time...
> 5691 Encounter delete fix

- server/graphql/types/src/types/item_stats.rs
- server/reports/item-usage/2_3_0/convert_data_js/input.json
- server/reports/item-usage/2_3_0/convert_data_js/output.json
- server/reports/item-usage/2_3_0/convert_data_js/src/utils.js
- server/reports/item-usage/2_3_0/convert_data_js/src/utils.test.ts
- server/reports/item-usage/2_3_0/src/expiringInSixMonths.postgres.sql
- server/reports/item-usage/2_3_0/src/expiringInSixMonths.sqlite.sql
- server/reports/item-usage/2_3_0/src/expiringInTwelveMonths.postgres.sql
- server/reports/item-usage/2_3_0/src/expiringInTwelveMonths.sqlite.sql
- server/reports/item-usage/2_3_0/src/query.graphql
- server/reports/item-usage/2_3_0/src/stockOnOrder.sql
- server/service/src/item_stats.rs
Fixes #5579
Fixes queries to show data item usage report.
You can test this by removing the existing item-usage report in your database, rebuilding standard reports, and then upserting the updated report. Note starting the server will automatically upsert built report.
I write this here because documentation of these commands isn't comprehensive now.
Also added totalStockOnHand to item stats query. This is what is being used on stockLine list view and OG reports for 'in stock' column. Previously was using availableStockOnHand which caused discrepancy.
For reviewers - the fastest way to get the new report is like so:
```
cargo build &&  ./target/debug/remote_server_cli build-standard-reports && ./target/debug/remote_server_cli upsert-reports-json
```
Which will rebuild and upsert reports …
> Fix queries on item usage report

- server/graphql/general/src/queries/item.rs
- server/graphql/stock_line/src/lib.rs
- server/reports/expiring-items/2_3_0/convert_data_js/src/convert_data.js
- server/reports/expiring-items/2_3_0/src/query.graphql
- server/reports/item-usage/2_3_0/convert_data_js/src/convert_data.js
- server/reports/item-usage/2_3_0/src/query.graphql
- server/reports/stock-detail/2_3_0/argument_schemas/arguments.json
- server/reports/stock-detail/2_3_0/argument_schemas/arguments_ui.json
- server/reports/stock-detail/2_3_0/convert_data_js/src/convert_data.js
- server/reports/stock-detail/2_3_0/src/query.graphql
- server/reports/stock-status/2_3_0/convert_data_js/src/convert_data.js
- server/reports/stock-status/2_3_0/src/query.graphql
- server/repository/src/db_diesel/stock_line.rs
Fixes #5025
Removes hidden items from report rendering.
There might be some confusion about what visible means for items in oms. We don't sync the hidden boolean from OG. in OMS visible means being part of a masterlist which is visible on the store.
I've updated explanations in comments.
Also graphql report queries updated to only show items both active and with stock on hand.
I think this should be sufficient because items cannot be hidden on OG if there is stock available.
Also added default sorting ascending and by item name on all reports
For reviewers - the fastest way to get the new report is like so:
```
cargo build &&  ./target/debug/remote_server_cli build-standard-reports && ./target/debug/remote_server_cli upsert-reports-json
```
Which will rebuild and upsert reports to the …
> 5025 hidden items showing on item usage and stock details reports

- client/packages/programs/src/JsonForms/components/DateOfBirth.tsx
Fixes #5438 
Fix issue where date picker age in days was off by 1 day before 1pm NZ time
Note the timezone (The issue "corrects" itself after 1pm NZ time so I have set my timezone to LA so that it is a day behind)
1.
2.
> Update to use getNaiveDate instead of getDateOrNull

- client/packages/common/src/ui/components/inputs/TextInput/NumericTextInput.tsx
- client/packages/requisitions/src/RnRForms/DetailView/RnRFormLine.tsx
Fixes #5733
Couldn't enter negative values in R&R forms on samsung tablet!
This PR switches back to alphanumeric keyboard, so users have access to the `-` key as needed.
R&R form and demographic growth rates are the only two places where we allow entering negative values... it feels a shame to remove the simplicity of the numeric keyboard everywhere for these two cases?
Considered something like `inputMode = allowNegative ? "text" : "numeric"` - but this was quite ick as you clicked through negative and non-negative fields in the R&R form. Probably best just to be consistent, but curious for thoughts! 😢 
Other interim solution for demo has been to install Gboard app, and set this as default keyboard. This keyboard has `-` key and allows us to keep the numeric keyboard. But I don't think …
> 5733 remove numeric input mode for number inputs

- client/packages/common/src/intl/locales/en/common.json
- server/graphql/types/src/types/item_stats.rs
- server/reports/expiring-items/2_3_0/convert_data_js/input.json
- server/reports/expiring-items/2_3_0/convert_data_js/output.json
- server/reports/expiring-items/2_3_0/convert_data_js/src/utils.js
- server/reports/expiring-items/2_3_0/convert_data_js/src/utils.test.ts
- server/reports/expiring-items/2_3_0/src/template.html
- server/reports/item-usage/2_3_0/convert_data_js/input.json
- server/reports/item-usage/2_3_0/convert_data_js/output.json
- server/reports/item-usage/2_3_0/convert_data_js/src/utils.js
- server/reports/item-usage/2_3_0/convert_data_js/src/utils.test.ts
- server/reports/item-usage/2_3_0/src/query.graphql
- server/reports/item-usage/2_3_0/src/template.html
- server/service/src/item_stats.rs
Fixes #5579 
- Adds AMC column to expiring items report
- Prevents negative numbers for stock at risk on expiring items report
- Prevents negative numbers for stock on order in item usage report
- Update item usage in stock to be available stock, not total stock. Also update column header
- Update test suite
You can test this by deleting old reports in database, then running:
```
cargo build &&  ./target/debug/remote_server_cli build-standard-reports && ./target/debug/remote_server_cli upsert-reports-json
```
Later will need to update documentation to explain how fields are calculated in OMS reports.
> 5579 fix remaining report bugs

- server/reports/stock-status/2_3_0/src/template.html
Fixes https://github.com/msupply-foundation/open-msupply-reports/issues/123
Out of stock calculation was wrong
1.
2.
> Fix out of stock calculation

- server/service/src/invoice/inbound_shipment/add_from_master_list.rs
- server/service/src/invoice/inbound_shipment/generate.rs
Fixes #5561
Fix issue where items added to inbound shipment from masterlist had a default pack size of 1 instead of item default pack size
1.
2.
> Update inbound shipment generate.rs to use default item packsize

- client/packages/common/src/ui/layout/tables/components/tooltipPlacement.ts
Fixes #4892 
The current placement of the tooltip obscures or hides data entry fields. To fix this issue we are to move up the placement of the tooltip from bottom to the top. 
1.
2.
> change tooltip placement to top

- client/packages/coldchain/src/Equipment/ListView/ListView.tsx
- client/packages/common/src/ui/layout/tables/columns/CheckboxSelectionColumn.tsx
- client/packages/inventory/src/Stocktake/ListView/ListView.tsx
- client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts
- client/packages/invoices/src/InboundShipment/ListView/ListView.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/columns.ts
- client/packages/invoices/src/OutboundShipment/ListView/ListView.tsx
- client/packages/invoices/src/Prescriptions/DetailView/columns.ts
- client/packages/invoices/src/Prescriptions/ListView/ListView.tsx
- client/packages/invoices/src/Returns/CustomerDetailView/columns.ts
- client/packages/invoices/src/Returns/CustomerListView/ListView.tsx
- client/packages/invoices/src/Returns/SupplierDetailView/columns.ts
- client/packages/invoices/src/Returns/SupplierListView/ListView.tsx
- client/packages/programs/src/ImmunisationProgramDetailView/ImmunisationProgramDetailView.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/columns.ts
- client/packages/requisitions/src/RequestRequisition/ListView/ListView.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/columns.ts
- client/packages/requisitions/src/ResponseRequisition/ListView/ListView.tsx
- client/packages/system/src/Asset/AssetLogReasons/ListView.tsx
- client/packages/system/src/Asset/ListView/ListView.tsx
- client/packages/system/src/Location/ListView/ListView.tsx
Fixes #5655
Move selection to be first column and also rename ```'selection'``` to ```genericColumnKey.Selection```
Changes needed to make it easier for user to select rows in list view
No screenshot for programs
Note sure why padding is being added to the left of the column in Inventory -> Locations and Stocktakes
1.
2.
> Move selection to be first column in list view tables

- client/packages/common/src/intl/locales/pt/common.json
Fixes #5748 
Fixes the display issue caused by log and ledger being the same word in portuguese.
Before:
After:
Complete love ends all fears.
> change portuguese translation of log

- server/service/src/asset/parse.rs
Fixes potential issue of missing waranty dates in GS1 codes
Especially since this standard isn't verified yet, we need to allow this to be empty when scanning a GS1 Matrix Barcode for assets
Makes waranty dates optional
Haven't create a test GS1 for this but I think the code change is safe.
1.
2.
> Handle optional gs1 warranty dates

- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestEditPage.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/hooks.tsx
Fixes #5852
Adds switch for item packs vs requested quantity in internal order line edit.
Side note - RequestLineEditForm.tsx isn't used anywhere. I wonder can we get rid of this to reduce codebase size?
> Add switch for item packs

- client/packages/common/src/ui/layout/tables/components/Header/Header.tsx
Fixes #5235
I modified the tooltips for header cells, so that now, if a description of the column has been shown, the label is not shown - if the description has already been shown, showing the label will not add anything. 
That prevents things being repetitive
I changed the tooltips so that now it says 'sort by [column label in lower case]' - before it did not transform it to lower case. Is this ok?
Is it worth creating an issue for this - at the moment, you get tooltips for every single entry in a table, which add no information, and stop you interacting with what's covered by them. Here are some examples:
This one stops you clicking on two lines:
These tooltips don't add information, and might lead to confusion due to their position:
This one gives you no new information but stops you …
> modify the tooltips of table column headers

- client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseEditPage.tsx
Fixes #5857 
Adding an item to a requisition can sometimes cause the browser to enter an infinite loading state. This is due to race conditions in the code.
The loading check relies on `isLoading || !currentItem` to determine if data has been fetched and if `currentItem` is populated. However, `currentItem` is derived from the fetched data, and there’s a moment when `isLoading` becomes false (data fetched), but `currentItem` is still empty. This timing mismatch triggers the issue.
As seen as well with the length of the array return from data. Lines grows in size once data is retrieved.
Removing `currentItem` from the loading check fixes the infinite loading state issue.
1.
2.
> remove currentItem loading check

- client/packages/system/src/Item/DetailView/Tabs/ItemVariants/ItemVariantModal.tsx
Fixes part 2 of #5554 
Autofocusses the first input of the add variant modal, to make it more keyboard friendly.
1.
2.
> autofocus first input in add variant modal

- client/packages/system/src/Item/DetailView/Tabs/ItemVariants/ItemVariantsTab.tsx
Fixes Part 1 of #5554
Adds a create new variant link on the catalogue>item>variants tab, if there are no variants present.
The capitalisation seems a bit dodgy. It seems all the 'create a new one' links will be similar. Using a function called toLocaleLowerCase() in the NothingHere.tsx file can solve this - should I create an issue to do that?
1.
2.
> add link to create new variant if none

- server/service/src/sync/settings.rs
- server/service/src/sync/sync_on_central/mod.rs
Fixes #5911 
A new translation got added to our Sync function, specifically syncing Contact Form from Remote Server to Central Server. With this change we are also required to bump the V6 sync version in settings and `Max_version` in `sync_on_central` mod file by 1
1.
2.
> bump v6 sync version

- client/packages/invoices/src/Prescriptions/LineEditView/hooks/useDraftPrescriptionLines.tsx
Fixes #5920
The new Prescriptions UI doesn't show the On Hold Column, instead we just won't show any on hold batches at all.
Did this as a front end change, I think it should be fine to do here rather than making backend changes and filters on the historical stock. Also makes it possible to show on hold easily again. There isn't usually a lot of stock on hold so a backend filter shouldn't be a big deal IMHO.
1.
2.
> 5920 prescriptions filter out on hold stock

- client/packages/common/src/ui/components/navigation/AppNavLink/AppNavLink.tsx
- client/packages/common/src/ui/components/navigation/Breadcrumbs/Breadcrumbs.tsx
- client/packages/common/src/utils/environment/EnvUtils.ts
- client/packages/config/src/routes.ts
- client/packages/host/src/CommandK.tsx
- client/packages/host/src/Site.tsx
- client/packages/host/src/components/AppBar/SectionIcon.tsx
- client/packages/host/src/components/AppDrawer/SyncNavLink.tsx
- client/packages/host/src/components/Sync/SyncModal.tsx
- client/packages/host/src/components/Sync/SyncModalContext.ts
- client/packages/host/src/components/Sync/SyncModalProvider.tsx
- client/packages/host/src/components/Sync/index.tsx
- client/packages/host/src/components/Sync/useSyncModal.ts
- client/packages/system/src/Sync/api/hooks/utils/useSyncInfo.ts
Fixes #5386
I've been testing lately and have found it annoying having to navigate to another page, sync and return to where I was working.
This scratches an itch essentially.
What it does it move the sync page into a modal, which can then be called either by pressing CTRL+ALT+S or by bringing up CMD+K and typing 'sync' or by pressing the sync nav item.
The 'Synchronise' button is focussed by default, so you can press Space or Enter when the modal shows to start synchronisation. Pressing Esc will close the modal - or clicking the close button (top right of modal).
This is how it looks - first pressing Control+Alt+S and then Escape, and secondly by clicking with the mouse:
https://github.com/user-attachments/assets/4130ae12-34bd-4ba1-9f32-5851e95c56f8
And I'm ignoring this little issue.. …
> Move sync to a modal

- server/repository/src/migrations/version.rs
Fixes #5937
Adds some default values, so that the Version from_str won't fail if the version isn't perfect
This was annoying when your database has old data, with a version of `1.0` for a report. The version conversion causes the report query to fail.
1.
2.
> Add some safety to version from string conversion

- server/service/src/sync/translations/program_requisition_settings.rs
Fixes #5949
Defaults elmis_code in translation
In mSupply:
- Create master lists and enable "This master list is a program" for them
- In record browser change the programSettings field to be an object with no "elmisCode" field (Empty object is fine)
In OMS:
- Sync from mSupply
- Master list should sync and show up in master list page
1.
2.
> 5949 Integration problem when syncing mSupply master lists for programs when no "elmisCode" set

- client/packages/programs/src/JsonForms/components/Prescription/StockLineTable.tsx
Fixes #5846
The actual labelling to "units" had already been done -- this just updates the functionality to properly handle units for the input and display.
See inline comments
- Create prescription data for Family Planning encounter (as per previous PR, eg. https://github.com/msupply-foundation/open-msupply/pull/5581)
- Input some values to issue, ensuring you can't enter more than the available quantity
- Close the modal, and "Save"
- Should see "Prescription created" notification
- Go to the newly created prescription and ensure all values are consistent with what you entered previously (in terms of units/packs)
> #5846 Fix Stock issue quantities for JSON Forms prescription

- client/packages/system/src/Item/Components/ListItems/ListItems.tsx
Fixes #5957
I don't think this is a complete solution, more a quick fix to get rid of the duplicate for 2.5 release.
I've made it match the designs (for Prescriptions at least), but there's still an inconsistency in how the "New" link works between Prescriptions and Internal orders. For internal orders, it seems to work more like a "button" in that it just provides a temporary stock selector which is then immediately added to the order (and re-directed), whereas in Prescriptions it remains in local state until explicitly "Saved", so the user stays on the "New" page until the entire item is filled it.
So I think we need to make this behaviour consistent and agree on a standard pattern for this component, but that will require a bit of discussion. We also need to consider how to easily …
> #5957 Remove duplicate "New item" link

- client/packages/invoices/src/Prescriptions/DetailView/Toolbar.tsx
- client/packages/invoices/src/Prescriptions/api/operations.generated.ts
- client/packages/invoices/src/Prescriptions/api/operations.graphql
Fixes #5969 
Fixes #5964
Changes the shape of the graphql query for Prescriptions to expicitly call `otherPartyId` `patientId`
I think this is a nice solution than https://github.com/msupply-foundation/open-msupply/pull/5965
But open to feedback
1.
2.
> Update to use patientId instead of otherPartyId in dispensing

- client/packages/invoices/src/Prescriptions/DetailView/ContentArea.tsx
- client/packages/invoices/src/Prescriptions/DetailView/columns.ts
Fixes #5967
Adds back the expanding rows. Not sure why it was deleted but I need screenshots for the docs and found that the expansion column was there but the underlying functionality was not.
Given that the rows are grouped by item I think it important to retain the expansion.
1. The documentation already says that this should work
> Restore row expansion in prescription detail view

- client/packages/common/src/ui/components/buttons/standard/BaseButton.tsx
- client/packages/common/src/ui/components/buttons/standard/ShrinkableBaseButton.tsx
Fixes #5919 
Update app bar buttons to show disabled state clearly
Just need to check that this change hasn't broken base button or shrinkable base button anywhere else
1.
2.
> 5919 Update app bar button to display disabled buttons clearly

- server/service/src/requisition/request_requisition/insert_program.rs
- server/service/src/requisition/response_requisition/insert_program.rs
Fixes #5951
Fixes to use customer store name id rather than other party (which could be the supplier) store name id for indicator values.
I was struggling to get tests working with time available and removed them [here](https://github.com/msupply-foundation/open-msupply/pull/5718/commits/bdaace5b41b05d57c474f3dbd851618e961a6c55). I wonder if worthwhile adding these in and including tests to cover correct assignment of store_id, name_id, etc.
> Add generating with customer_name_id

- client/packages/host/src/components/Footer/UserDetails.tsx
Fixes #5886 
Remove width prop for paperclick modal so that long emails can be accommodated. Increase label width so that label and text no longer overlaps.
As label width is currently fixed we will need to keep an eye on whether any new translations will cause the label and text to overlap.
1.
2.
> 5886 improve logout modal

- client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts
Fixes #4591 
Fix issue where cost per unit was not being calculated correctly when items were not grouped. 
1.
2.
> Update cost per unit when items not grouped

- server/repository/src/migrations/v2_05_00/add_contact_form_processor_pg_enum_type.rs
- server/repository/src/migrations/v2_05_00/mod.rs
Fixes #6016 
Adds the PG enum type I forgot 🙈 
1.
2.
> 6016 add pg enum type for contact form processor cursor

- client/packages/common/src/ui/components/modals/ConfirmationModal/ConfirmationModal.tsx
- client/packages/common/src/ui/components/modals/ConfirmationModal/ConfirmationModalProvider.tsx
- client/packages/invoices/src/Prescriptions/DetailView/Toolbar.tsx
Fixes #6014
The date wasn't being saved if it was input via the text input (as opposed to the Date picker). This was due to the input only having an `onAccept` handler rather than `onChange`. This was done to fix an earlier change where the `onChange` method would run as soon as the Date picker opened on Mobile, and then cause a conflict with the confirmation modal.
There was a mistake in the `onChange` method when comparing dates -- we can't just use `===` to compare Date objects's values, so the early return from `onChange` when the date hasn't changed wasn't working. We should have just fixed that originally, rather than changing to `onAccept`, so have done that here, which solves the main issue.
Have also added another state value `"dateValue"` for the current prescription date, which …
> #6014 Handle date change properly

- client/packages/host/src/CommandK.tsx
Fixes #5424
Use modifiers for shortcuts: 
| condition | shortcut | action |
|--------|--------|------------|
| | Close the more info panel | Control+Shift+M |
| | Easter egg  | Control+Shift+E |
| dispensing store & vaccine module pref | Go to: Cold chain equipment | Alt+E |
| dispensing store & vaccine module pref | Go to: Cold chain monitoring | Alt+C |
| | Go to: Customer Requisition | Alt+R |
| | Go to: Dashboard | Alt+D |
| | Go to: Inbound Shipments | Alt+I |
| | Go to: Internal orders | Alt+Shift+O |
| | Go to: Items | Alt+I |
| | Go to: Master Lists  | Alt+M |
| | Go to: Outbound Shipments | Alt+O |
| dispensing store | Go to: Patients | Alt+Control+P |
| dispensing store  | Go to: Prescriptions | Alt+P |
| | Go to: Reports | Alt+R | 
| | Go to: Stock | Alt+S |
| | Go to: …
> 5424 Add modifiers to the CMD+K global shortcuts

- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
Fixes #5582 
Update ```Requested quantity``` to round up to next integer and update ```Suggested quantity``` to round to 2 decimal places.
Before
After
1.
2.
> 5582 Add rounding to internal order request edit

- client/packages/system/src/Item/DetailView/Tabs/ItemLedger.tsx
- server/service/src/requisition/request_requisition/requisition_item_info.rs
Fixes #6070
Fix calculation for ledger adjustment + localise date
Second:
1.
2.
> 6070 Localise ledger date + fix adjustment calculation

- client/packages/invoices/src/Prescriptions/DetailView/columns.ts
- client/packages/invoices/src/Prescriptions/LineEditView/LineEditView.tsx
- client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditForm.tsx
- client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditTable.tsx
- client/packages/invoices/src/Prescriptions/LineEditView/hooks/usePrescriptionLineEditRows.ts
- client/packages/invoices/src/StockOut/utils.tsx
Fixes #6083 #6090 #6061 #6059
(There's one more dispensing hotfix (#6078), but that'll require a bit more thinking about, so will do separately.)
Four small fixes for the above issues.
I've done each in a different commit, so you can review them individually if you like:
#6083 e249b567c5
#6090 d6767fb83d
#6061 9b825cdb5a
#6059 3953898422
I've also mentioned the issue # in my review comments below.
See review comments for more details
These are all really tiny, so please just refer to the original issues and confirm behaviour is fixed when doing the "How to reproduce" steps.
> #6083 #6090 #6061 #6059 Prescription hotfixes x4

- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
Fixes #6019
From specs
```
Note that the new columns have already been added to program based requisitions.
Implement the store permissions for
Keep requisition lines with zero requested quantity on finalise
Use consumption and clients stock data in internal orders
```
Showing extra columns only if the user has the `use consumption data` pref turned on.
1.
2.
> IO extra columns show with use consumption data pref

- client/packages/common/src/ui/components/buttons/standard/DialogButton.tsx
- client/packages/system/src/Stock/DetailView/Footer.tsx
Fixes #6092 
Add save icon and update ```shouldShrink``` to ```false```for buttons in View Stock detail view footer
1.
2.
> 6092 Add icon and update shouldShrink

- server/reports/stock-take-with-quantity/2_3_0/src/template.html
- server/reports/stock-take-without-quantity/2_3_0/src/template.html
Fixes #6097
Rename stocktake reports to have correct name
1.
2.
> 6097 Stocktake with quantity and without quanity seem to be wrong way around?

- client/packages/system/src/Store/components/StoreSearchInput/StoreSearchInput.tsx
Fixes #6114 
Adding a new asset crashes when navigating away from the import modal. The issue occurs because the `usePaginatedStores` data briefly returns an empty page length. A length check has been added to handle this case
https://github.com/user-attachments/assets/3409ea0a-1e8e-4c6b-972a-cb8684bcd5dd
1.
2.
> 6114 adding new asset crashes

- client/packages/common/src/ui/components/navigation/ListOptions/ListOptions.tsx
- client/packages/invoices/src/Prescriptions/LineEditView/LineEditView.tsx
- client/packages/invoices/src/Prescriptions/LineEditView/NavBar.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/IndicatorEdit/Footer.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/IndicatorEdit/IndicatorEditPage.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/IndicatorEdit/IndicatorLineEdit.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/Footer.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestEditPage.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/IndicatorEdit/Footer.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/IndicatorEdit/IndicatorEditPage.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/IndicatorEdit/IndicatorLineEdit.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/Footer.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseEditPage.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEdit.tsx
- client/packages/requisitions/src/common/ListIndicators.tsx
- client/packages/system/src/Item/Components/ListItems/ListItems.tsx
Fixes #6078
Turns out the `ref` definition in `<ListOptions>` was calling `scrollIntoView` on every re-render, which was pulling the whole page up.
I've changed it to define the ref in a parent component, and passed it down to the ListOptions, and also defined a `scrollIntoView` method which calls `scrollIntoView()` on that ref from the Nav Bars (Prev/Next buttons).
Also, this problem was affecting *all* `<ListOptions>` implementations, so have made the same fix (in addition to Prescriptions) for:
- Requisitions
- Internal Orders
- Indicators for both of the above
There's a lot of duplicate code, plus the different implementations of the Navigation bars are inconsistent, so hopefully can consolidate this a bit better with #5973 .
Go to a prescription "Line Edit View" with a decent number …
> #6078 Prevent unnecessary scrolling

- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
Fixes #6128
Save requested quantity on blur if user is requesting in packs 
1.
2.
> 6128 Internal order editing requested packs does not save changes

- client/packages/system/src/Item/DetailView/Tabs/ItemLedger.tsx
- client/packages/system/src/Stock/Components/Ledger/useLedgerColumns.ts
Fixes #6075
Concat type + invoice num in ledgers... should change the header? I think it's fine... 🤷🏻 
1. ledger ss updates
2.
> 6075 'Invoice Number' column can be clearer

- server/repository/src/migrations/v2_05_00/mod.rs
- server/repository/src/migrations/v2_05_00/remove_vaccination_user_account_fk.rs
Fixes #5986 
Add migratoin to drop user_account fk constraint from vaccination table. Vaccinations given by new users on remote sites now show up in the vaccination table.
1.
2.
> 5986 Add migration to drop user_account fk constraint

- server/graphql/invoice/src/mutations/prescription/update.rs
- server/service/src/invoice/prescription/update/mod.rs
Follow-up to #5977 to fix tests broken by clinician_id field to NullableUpdate.
I think @jmbrunskill wanted to have a quick look at the `unwrap()` to try and improve it.
- Run `cargo test` -- should all pass
> #5977(2) Fix prescription update tests

- client/packages/invoices/src/Prescriptions/DetailView/columns.ts
Fixes #6088
Dispensing `directions` pop over not longer shows batch numbers, and only one directions section is shown
UI looks a little bit untidy. could be Cleaned up at some point.
1.
2.
> 6088 dispensary directions popover shows batch but unclear this is batch

- client/packages/host/src/components/Sync/SyncModal.tsx
- client/packages/system/src/Patient/Components/PatientSearchInput/PatientSearchInput.tsx
Fixes #5155 
Updated the `Autocomplete` component within `PatientSearchInput` to use the `value` prop instead of the defaultValue prop. This change effectively converts the `Autocomplete` component to a controlled component, which aligns with our desired behaviour.
https://github.com/user-attachments/assets/67d7d79f-2ba9-4bc8-9db7-b2d9586c70a8
1.
2.
> 5155 patient info update not showing in prescription

- client/packages/common/src/hooks/useNativeClient/useNativeClient.ts
- client/packages/host/src/components/SiteInfo.tsx
Fixes #5102 
Tablet - Shouldn't be able to change servers if a user decides to initialise via the Server.
When initializing or going through the Client, users can change the server without any issues. However, initializing through the Server causes an authentication issue when a user tries to change servers.
1.
2.
> 5102 cannot change servers tablet

- client/packages/requisitions/src/RequestRequisition/DetailView/IndicatorEdit/IndicatorLineEdit.tsx
Fixes #6147 
Hide indicator information if there is none
1.
2.
> 6147 Indicators details show Nothing here where there is no customer to show. This text should be hidden

- client/packages/system/src/Stock/ListView/ListView.tsx
- client/packages/system/src/Stock/api/hooks/useStockList.ts
Fixes #4015
Display master list names in stock view and allow the user to filter by master list
1. Stock screenshots
2.
> 4015 Allow filtering "View Stock Page" by master list

- client/packages/system/src/Patient/Encounter/CreateEncounterModal.tsx
Fixes #5818
Redirecting to Encounter if the datetime is less than right now (with 5 minute buffer). Have also allowed users to select a time to save in the start datetime so they don't have to go into future encounters to configure this
1.
2.
> 5818 Creating a new encounter does not take you to a newly created encounter, instead keeps you on a landing page

- client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseEditPage.tsx
Fixes #6199
Don't show add item option if requisition is created from an internal order
1.
2.
> 6199 Able to add items to a non-manual requisition 

- client/packages/host/src/components/Sync/SyncModal.tsx
Fixes #5956 
All query keys are invalidated after a manual sync has finished
The result of this is when the sync modal is closed, whichever page the user is on will refresh and show any updated records immediately. This is what a user might expect to happen after intentionally syncing
1.
2.
> Invalidate Graphql Queries After Sync

- client/packages/invoices/src/Returns/modals/SupplierReturn/ReturnQuantitiesTable.tsx
Fixes #5121 
Rounds decimal ```Quantity to return``` input value down to nearest integer.
https://github.com/user-attachments/assets/da7ae1e2-96f3-444e-ae89-9613e91dd561
1.
2.
> 5121 Floor decimal quantity to return

- server/server/src/discovery.rs
Fixes #5018 (hopefully?)
Catches the panic on discovery, and just logs an error.
We still probably want to get a proper fix, and possibly re-try adding discovery
Not 100% sure if this solved the issue as it's not happening for me here at home at the moment.
Would be good for someone to test it who's having the problem regularly...
Branched off V2.5.0 RC branch as that is where I was seeing the problem more regularly.
@andreievg  also suggested we could do add a configuration file to disable discovery.
Thought I'd try this first to see if it helps...
1.
2.
> Catch panic in discovery

- client/packages/common/src/intl/locales/en/common.json
- client/packages/system/src/IndicatorsDemographics/DetailView/IndicatorsDemographics.tsx
- client/packages/system/src/IndicatorsDemographics/DetailView/utils.tsx
Fixes #6181
I've changed from looking at the current year as the base for projections to assume we always base it off 2024.
Not an ideal solution but good enough for the 2.5 hotfix I think.
Also fixes the missing headers for the years, which might have been broken by MUI6 upgrade???
Anyway, it's now Year 1, 2, 3, 4, 5 instead of the actual years as it doesn't make sense when hard coded...
The intention was to allow the system to capture different scenarios for different years, so for example you could do your planning for 2020, then come back in to 2025 an start a new round of planning without loosing what you'd saved in 2020.
However, this haven't been fully implemented, and part of the system were assuming the 2024 base year and other parts were just looking at the calendar date. Now …
> Hack: Always use base year 2024 for demographic projections

- server/repository/src/db_diesel/item_variant/packaging_variant.rs
Fixes #5808 
Change the ordering in the packaging variant from 'id' to 'packaging_level' so that the tables are in order: 1, 2, 3
This appeared in this imported data set as the packaging variant id is a UUID. Variants created in the front end are created in order due to the modal layout - I could not reproduce this bug without the imported data.
This would have the potential to be recreated any time a user has imported item variant data
1.
2.
> Item variants: Packaging tables ordering

- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/hooks.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/hooks.tsx
Fixes #6119 #6212 
Disable next button when adding a new item in line edit view so that it doesn't go to undefined page/infinite spinner.
1.
2.
> 6119/6212 Disable next button when adding new item (internal order + manual requisition)

- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
Fixes #6185 
When backspacing a value in Internal Order -> New Item -> Requested Quantity, the empty value populates as 'NaN'
Added a NaN check, if the value is not a number it will show '0'. The user will then be able to type in the field with the new number
1.
2.
> fix internal order value after backspace

- client/packages/programs/src/JsonForms/components/DateOfBirth.tsx
Fixes #5869
Don't convert selected value to naivedate
1.
2.
> Don't convert dob to naivedate

- server/graphql/core/src/loader/item_stats.rs
- server/service/src/backend_plugin/examples/amc/amc.js
- server/service/src/backend_plugin/types/amc.rs
- server/service/src/dashboard/item_count.rs
- server/service/src/invoice_line/stock_out_line/update/mod.rs
- server/service/src/item_stats.rs
- server/service/src/requisition/request_requisition/generate.rs
Fixes #5826
Removes the ItemStatsFilter type, replacing my a list of item_ids
This makes the calling service for the AMC Plugin simplier and less risk of changes not being covered correctly.
This means that callers of item_stats will need to know the items in advance but that seems to be the case in all our use cases.
1.
2.
> Change amc plugin interface to take item_ids list instead of filter

- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/ui/components/buttons/standard/SplitButton.tsx
- client/packages/system/src/Encounter/DetailView/DetailView.tsx
- client/packages/system/src/Encounter/DetailView/Footer.tsx
- client/packages/system/src/Encounter/DetailView/SidePanel.tsx
- client/packages/system/src/Encounter/DetailView/StatusChangeButton.tsx
- client/packages/system/src/Encounter/DetailView/Toolbar.tsx
Fixes #6272
Make status change/delete workflows of encounters match those of other features.
Removes status change and delete from toolbar. 
Adds delete button to side panel, and status change to footer:
Pre-requisite to hooking into status change logic within vax card.
1.
2.
> 6272 move status change to footer

- client/packages/android/README.MD
- client/packages/android/app/src/main/java/org/openmsupply/client/NativeApi.java
While reviewing: https://github.com/msupply-foundation/open-msupply/pull/6065 I really needed a wy to run in debug mode on mobile, which was previously working and is documented here https://github.com/msupply-foundation/open-msupply/blob/830127818f2efab0ea3ab112157b2592641b1673/client/packages/android/README.MD#L114
try building android `android:build:debug` and then using visual studio code to run it, then follow instructions in android/readme.md to get hot reload on mobile
Non debug should work
> Always revert to debug url if debug mode

- client/packages/common/src/intl/locales/en/common.json
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/columns.ts
- client/packages/invoices/src/Prescriptions/LineEditView/hooks/useDraftPrescriptionLines.tsx
- client/packages/invoices/src/StockOut/utils.tsx
Fixes #5147 
Update onhold stocklines to not be counted towards available stock when adding items to prescriptions or when adding items to outbound shipments
Thanks @lache-melvin  for unblocking!
Please check different configurations of item or location on hold to ensure that the correct values are coming through.
Also does the value in the dropdown need to be updated?
```Prescriptions```
```Outbound Shipments```
1.
2.
> 5147 fix on hold items counted towards available stock

- client/packages/coldchain/src/Equipment/DetailView/AppBarButtons.tsx
- client/packages/coldchain/src/Monitoring/ListView/AppBarButtons.tsx
- client/packages/common/src/ui/components/buttons/standard/LoadingButton.tsx
- client/packages/common/src/ui/components/buttons/standard/SplitButton.tsx
- client/packages/system/src/Patient/PatientView/AddButton.tsx
Fixes #5806 
Added specified variant type to the two buttons found in testing that hadn't updated to new coloring of orange icon with black text
Added a default variant type to the Loading Button to catch any in the future
Cold Chain -> Equipment -> Detail View
Cold Chain -> Monitoring
Side Quest:
Updated the Split button to have rounded corners on the right hand side
This was mentioned in #6276 - I am not set up on encounters currently to test in this area but this is a split button from Inbound Shipment -> Detail View
1.
2.
> Change the button style (orange text on white) to have black text

- client/packages/common/src/ui/components/buttons/standard/ShrinkableBaseButton.tsx
Fixes #6005
Fixes buttons that are orange and not showing icons (without hover). Icons were displaying as orange on orange background, where the icons should be white
I had a look at if there was a quick refactor as the icons colors are now being controlled by two different components, and the icons being in parent components to these. This is probably a separate refactor issue though
Buttons that had an orange background, also had an orange icon which was not visible. Icon is now white
1.
2.
> update icon color to white on orange buttons

- client/packages/system/src/Item/Components/StockItemSearchInput/StockItemSearchInput.tsx
Fixes #6287
Maybe? fixes #6291 @roxy-dao I can't replicate?
1.
2.
> 6287 fix missing item value

- client/packages/coldchain/src/Equipment/DetailView/DetailView.tsx
- client/packages/coldchain/src/Monitoring/ListView/AppBarButtons.tsx
- client/packages/common/src/hooks/useConfirmOnLeaving/useConfirmOnLeaving.stories.tsx
- client/packages/common/src/hooks/useConfirmOnLeaving/useConfirmOnLeaving.ts
- client/packages/common/src/ui/components/navigation/Tabs/DetailTabs.tsx
- client/packages/host/src/Site.tsx
- client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/InboundLineEdit.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/hooks/useDraftOutboundLines.tsx
- client/packages/invoices/src/Prescriptions/LineEditView/LineEditView.tsx
- client/packages/programs/src/JsonForms/useFormActions.tsx
- client/packages/programs/src/JsonForms/useJsonFormsHandler.tsx
- client/packages/requisitions/src/RnRForms/DetailView/DetailView.tsx
Fixes #6321
useBlocker can only have one active instance at a time. In encounters, there were two blockers (one from JSON form, one from `DetailTabs`) - so neither were working. You could edit encounter, then navigate away without saving with no warning.
This updates the implementation so that we can register multiple blockers in as many places as we need, and this informs the one `useBlocker` call at the base of the app. 
Actually ended up fixing the detail tabs so that it doesn't use the confirm on leaving hook - see comment - but will have the same multiple blockers rendered problem with my next vax card PR. Just didn't want this bloat in that PR 🙏 
1.
2.
> fix confirm on leaving with multiple blockers

- client/packages/common/src/hooks/useUrlQuery/useUrlQueryParams.ts
- client/packages/common/src/intl/locales/en/common.json
- client/packages/invoices/src/Prescriptions/ListView/ListView.tsx
- client/packages/invoices/src/Prescriptions/ListView/Toolbar.tsx
Fixes #6159 
Adds filters to the prescription list view, so now you can filter by patient name, invoice number and prescription date.
Since the search box was there to search by patient name, and that's now done by the filter, I removed the search box because it seemed to be redundant.
Have a nice day :)
- [ x ] **Part of an epic**: documentation will be completed for the feature as a whole
- [ x ] **These areas should be updated or checked**: New filters for the prescriptions list view.
> 6159 add filters to prescription list view

- client/packages/system/src/Encounter/DetailView/DetailView.tsx
- client/packages/system/src/Encounter/DetailView/ScheduleNextEncounterModal.tsx
- client/packages/system/src/Encounter/DetailView/helpers.test.ts
- client/packages/system/src/Encounter/DetailView/helpers.ts
Fixes #6263
Use next vaccination date for encounter suggested date:
1.
2.
> 6263 suggest next date from vax card

- client/packages/common/src/intl/locales/en/common.json
- client/packages/requisitions/src/RequestRequisition/ListView/ProgramRequisitionOptions.tsx
- client/packages/requisitions/src/ResponseRequisition/ListView/ProgramRequisitionOptions.tsx
- server/service/src/requisition/program_settings/common.rs
Fixes #6230
Up max periods shown historically/future. Also add message to clearly state why periods are missing from selection.
1.
2.
> 6230 not all periods shows up on first load

- client/packages/common/src/intl/locales/en/common.json
- client/packages/invoices/src/Prescriptions/ListView/AppBarButtons.tsx
- client/packages/system/src/Patient/Components/PatientSearchModal/PatientSearchModal.tsx
- client/packages/system/src/Patient/CreatePatientModal/CreatePatientModal.tsx
- client/packages/system/src/Patient/CreatePatientModal/PatientResultsTab.tsx
- client/packages/system/src/Patient/PatientView/PatientView.tsx
- client/packages/system/src/Patient/utils.ts
Fixes #6177
Added functionality to create a patient through the prescription window. A "Create Patient" button has been added to the prescriptions section, which opens a modal for creating a new patient. After filling out the form in the modal, the user is redirected to the Patient form, as a patient code is required for creation. Once the patient is created, the user is redirected back to the prescriptions page.
https://github.com/user-attachments/assets/7bc77f4d-d64d-4c39-82a0-f56348db1aba
1.
2.
> 6177 create patient from prescription window

- server/android/src/android.rs
- server/configuration/base.yaml
- server/configuration/example.yaml
- server/server/src/lib.rs
- server/service/src/settings.rs
- server/service/src/test_helpers.rs
Fixes #5018 
Adds a new option you can put in your local.yaml file to turn on/off discovery.
The default `Auto` will disable discovery in Debug Build (normal workflow for devs)
```
server:
discovery: Auto 
```
```
server:
discovery: Enabled 
```
```
server:
discovery: Disabled
```
Haven't removed my old `catch_panic_unwind` code in this PR, should I?
1.
2.
> Add config option to disable discovery

- client/.husky/pre-commit
This was just annoying me when working on `server` code. Why lint something that hasn't been changed?
> Only run pre-commit lint if there are actually changes in the client dir

- client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditForm.tsx
- client/packages/invoices/src/Prescriptions/api/hooks/usePrescriptionLines.ts
- client/packages/invoices/src/StockOut/utils.test.ts
- client/packages/invoices/src/StockOut/utils.tsx
Fixes #6353 
This improves the logic for assigning the prescribed quantity. Instead of assigning it to each issued line, it only assigns the prescribed quantity to the first line that is issued.
https://github.com/user-attachments/assets/3ecb44f4-8cd3-407c-8d5f-3e9a6c738417
Check the network tab or through GraphQL Network plugin to check which issued line prescribed quantity is getting assigned to.
1.
2.
> 6353 prescribed quantity improvements

- server/repository/src/db_diesel/patient.rs
Fixes #6366
Looks like the "gender" and "date_of_birth" fields had the wrong "sort" method applied, and it was trying to COLLATE the result on a field where collate makes no sense.
Have changed to `apply_sort` rather `apply_sort_no_case` for those two fields (same as what's already on "date_of_death" and "created_date_time".
> #6366 Fix patient sorting

- client/packages/invoices/src/Prescriptions/DetailView/AppBarButton.tsx
Fixes #6341 
Adds a 'Print Labels' button to the App Bar of Prescriptions -> Detail View. This will be connected to an API to print the directions for all prescription items
- Is not yet hooked up to do anything when clicked
- Will then need to be connected to loading state, which will show the spinner icon when loading
Testing on functionality will be done once this is connected to the API
1.
2.
> Print Labels Button in App Bar

- client/packages/common/src/intl/locales/en/common.json
For #6283 
Adds translation for stock-to-date report name
Does this report need a "how to read this report" message?
1.
2.
> 6283 Add stock-to-date report name translation

- client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditForm.tsx
Fixes #5978 
Disables pluralisation in line edit view. (Did you read the title? What did you expect? 😜)
Which means that now there are no silly 's'ses like in this sentens.
Now it looks like this for items without units:
And like this for items with units:
Have a nice day :)
Thanks!
> Disable pluralisation in prescription line edit view

- client/packages/common/src/intl/locales/en/common.json
- client/packages/invoices/src/Prescriptions/DetailView/Footer/StatusChangeButton.tsx
- client/packages/invoices/src/Prescriptions/DetailView/Payments/PaymentsModal.tsx
- client/packages/invoices/src/Prescriptions/DetailView/Payments/index.ts
Fixes #6176
This PR sets up the necessary groundwork to render various text fields in the payments modal. This modal will only be displayed when the cost is greater than $0 upon finalise/verified. Currently, it only shows the total amount that a patient is required to pay.
The remaining fields can be added once #6289 have been worked on
1.
2.
> 6176 payments modal select insurance

- client/packages/common/src/ui/components/inputs/TextArea/TextArea.tsx
- client/packages/common/src/ui/components/inputs/TextInput/NumericTextInput.tsx
- client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NumberInputCell.tsx
- client/packages/host/src/Admin/SettingTextArea.tsx
- client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditForm.tsx
- client/packages/invoices/src/StockOut/utils.tsx
Fixes #6449
Restores the border on the settings inputs
It's another MUI6 problem. 
* The slotProps needed to be on the `input` rather than the `htmlInput`
* Within the props, the `sx` provided by the caller was being overwritten 
The borders were missing and it's hard to see where the input is now!
Fix the background colour on the numeric inputs for prescriptions. These are showing as grey and should be white:
- Check other usages to see if they look ok:
1.
2.
> restore the border

- server/service/src/requisition/common.rs
- server/service/src/requisition/request_requisition/insert_program.rs
- server/service/src/requisition/response_requisition/insert_program.rs
When checking for maximum program orders for a period
Fixes #6422
Previously back end checks for if maximum orders per program requisition period didn't take into account different suppliers or customers.
This PR adds a filter for for other_party_name_id during check for maximum orders per period reached. This is added in both request and response program requisitions.
Now checks for orders per period are on a per customer basis.
On develop branch:
On new branch:
1.
2.
> Add check exclusive of other customer or supplier stores

- decisions/2024-12-03_preferences.md
> Preferences KDD

- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEdit.tsx
Fixes #6086
Add their/our stock on hand label instead of just stock on hand for Requisitions and Internal Orders + show our stock on hand for Requisitions
1. Screenshots for requisition and internal order line edit page
2.
> 6086 Unclear which store's SOH & AMC are shown when clicking on an item in Requisitions

- client/packages/common/src/intl/locales/en/common.json
- client/packages/requisitions/src/RequestRequisition/DetailView/Footer/StatusChangeButton.tsx
Fixes #6459
Don't allow users to finalise Internal Orders if:
1. There are no lines
2. All lines have requested quantity = 0
1.
3.
> 6459 Can send blank internal orders 

- client/packages/reports/src/utils.ts
Fixes #6385 
Alternative front end translation manipulation so that raw name is displayed when translation function goes to fallback.
I had wondered about changing translation to work on code rather than name, and have the name field as an optional override. This would allow consolidation of translation manipulation into less places.
However, this is so much more simple and is backwards compatible, so opted for this option.
Allows reports to show raw name field as name without adding client specific translation strings for custom reports.
> Refactor utils to have overridable name as displaying report name

- client/packages/common/src/hooks/useConfirmOnLeaving/useConfirmOnLeaving.ts
- client/packages/common/src/ui/components/inputs/Autocomplete/Autocomplete.tsx
- client/packages/programs/src/JsonForms/common/JsonForm.tsx
- client/packages/programs/src/JsonForms/common/components/ToolbarLayout.tsx
- client/packages/programs/src/JsonForms/common/components/index.ts
- client/packages/programs/src/JsonForms/common/index.ts
- client/packages/system/src/Encounter/DetailView/AppBarButtons.tsx
- client/packages/system/src/Encounter/DetailView/DetailView.tsx
- client/packages/system/src/Encounter/DetailView/Toolbar.tsx
Fixes #6267
Also little side quest for section one of #6332
Moves `Type of visit` from modal on the encounter `Details` tab, to the toolbar!
I AM aware that if you make your screen too small, some of this jank ensues:
However upcoming issues are to remove some of the fields, so it will end up like this so I think we gucci:
1.
2.
> 6267 add toolbar rendered encounter fields

- client/packages/common/src/plugins/usePluginEvents.ts
- client/packages/common/src/types/schema.ts
- server/graphql/plugin/src/lib.rs
- server/graphql/plugin/src/plugin_data/mutations/insert.rs
- server/graphql/plugin/src/plugin_data/mutations/mod.rs
- server/graphql/plugin/src/plugin_data/mutations/update.rs
- server/graphql/plugin/src/plugin_data/query.rs
- server/graphql/plugin/src/types.rs
- server/repository/src/db_diesel/plugin_data.rs
- server/repository/src/db_diesel/plugin_data_row.rs
- server/repository/src/migrations/v2_06_00/plugin_data.rs
- server/service/src/auth.rs
- server/service/src/plugin/mod.rs
- server/service/src/plugin_data/insert.rs
- server/service/src/plugin_data/update.rs
Fixes #6540
Changes the structure of the pluginData to allow more generic plugin data contexts without code code changes such as adding new types to postgres.
It also allows plugin data without storeId to allow central config for plugins
This change loosens up permissions for accessing plugin data, as the Resource Mapping has been removed.
I've made non-store records only editable from central server for now,
And made plugin_code a required field for any plugin queries, so it's not possible to access all the plugin data without knowing their code  at least.
>Note: this issue is probably only for Developer Testing
1.
2.
> Refactor plugin data structure

- client/packages/common/src/intl/locales/en/common.json
- client/packages/invoices/src/Prescriptions/DetailView/SidePanel/PrescriptionDetailsSection.tsx
- client/packages/invoices/src/Prescriptions/DetailView/SidePanel/SidePanel.tsx
Fixes #6510 
Adds functionality to the sidebar of Prescriptions' detail view. It now has inputs for
- program
- clinician
- reference
- dispensing date
within a new section called 'Prescription Details'.
Here's a screenshot:
1. You may have noticed that we also have a section called 'Additional info' that might be good to combine with Prescription Details. I wasn't sure this was desired, which is why I didn't do it, but it will be easy to do if it is desired, all I need to do is revert a commit and un-comment-out some code. Just let me know.
2. If you update the reference, date or clinician in the toolbar, it doesn't update in the sidebar and vice versa. It will only change when you refresh the page. This means that it is possible to input two different values, which conflict when saving …
> 6510 add fields to prescription more panel

- server/server/src/print/label.rs
- server/server/src/print/mod.rs
- server/service/src/auth_data.rs
- server/service/src/print/label.rs
- server/service/src/token_bucket.rs
Fixes #6542 
Adds API for _very_ basic label printing. The API shape itself may change a lot in the future, though!
I lost an embarrassingly long time trying to figure out why on earth my bearer tokens weren't going through (as that's how we auth the gql API):
```
Denied(
NotAuthenticated(
"Missing auth token",
),
)
```
Turns out the printing API and some file sync use cookies instead! Can't think of why we need to auth schemes. Perhaps the auth cookie had some extra data in it beyond `token`, though JWTs themselves hold extra data so it's a bit of a nesting doll situation there.
Anyway if you want to test this you need an API client that can include a cookie, like `curl` or insomnia.
Your cookie must have this JSON content shape:
```json
{
"token": …
```
> #6542 dispensary label printing 

- server/graphql/batch_mutations/src/batch_prescription.rs
- server/graphql/invoice/src/mutations/prescription/insert.rs
- server/service/src/invoice/prescription/insert/generate.rs
- server/service/src/invoice/prescription/insert/mod.rs
- server/service/src/invoice/prescription/invoice_date_utils.rs
- server/service/src/invoice/prescription/mod.rs
- server/service/src/invoice/prescription/update/generate.rs
- server/service/src/vaccination/generate.rs
Fixes #6545
Adds two new fields in Prescriptions
1.
2.
> Prescription Creation with more fields!

- client/packages/common/src/intl/utils/DateUtils.ts
- client/packages/common/src/types/schema.ts
- client/packages/programs/src/JsonForms/components/PeriodSearch.tsx
- client/packages/programs/src/api/hooks/usePeriodList.ts
- client/packages/programs/src/api/operations.generated.ts
- client/packages/programs/src/api/operations.graphql
- server/graphql/programs/src/lib.rs
- server/graphql/programs/src/queries/program.rs
- server/graphql/types/src/types/period.rs
- server/repository/src/db_diesel/period/period.rs
- server/service/src/program/query.rs
- server/service/src/rnr_form/schedules_with_periods.rs
Fixes #6533
Defaults shown periods to 15 and only show past periods. 
1.
2.
> 6533 pagination for period

- server/graphql/general/src/queries/ledger.rs
As part of #6343
Reverting changes from PR https://github.com/msupply-foundation/open-msupply/pull/6514
Changes needed as filter no longer being used. @roxy-dao found a better solution for filtering by datetime
1.
2.
> Remove datetime filter from ledger.rs

- client/packages/system/src/ReturnReason/Components/ReturnReasonSearchInput.tsx
Fixes #6517
Removes the custom renderer... it's the same as the AutoComplete input but with extra padding??
1.
2.
> 6517 App crashes when I click on disabled Reason dropdown Supplier return edit modal

- server/cli/src/refresh_dates.rs
FIx for failing Postgres test.
Fixes the "refresh_dates" test to handle the new "cancelled_datetime" field.
Something to note: when running the test in isolation by clicking the test runner in VSCode, a compilation error occurs:
```
Compiling graphql_stock_line v0.1.0 (/Users/carl/GitHub/open-msupply/server/graphql/stock_line)
error[E0308]: mismatched types
--> graphql/reports/src/print.rs:332:9
|
331 |     let data = query_json(
|                ---------- arguments to this function are incorrect
332 |         &ctx.get_settings().database,
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `&StorageConnection`, found `&DatabaseSettings`
|
= note: expected reference `&StorageConnection`
found reference `&DatabaseSettings`
note: function defined here
--> …
```
> v2.6.0 Postgres tests fix

- client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditForm.tsx
- client/packages/invoices/src/Prescriptions/api/hooks/utils.tsx
Fixes #6612 
Prescribed Quantity gets overriden on initial changes of its input. This is happening due to the logic that's within a `useEffect`.  It has a dependency that gets updated when we initially change prescribed quantity. Which re-triggers the prescribed quantity logic that's only meant to run on initial load.
Moved the initial setting of prescribed quantity logic to its own `useEffect` without any dependencies. Triggering the logic only on initial load
https://github.com/user-attachments/assets/9788dca0-5642-4e02-a5da-b794825bc653
1.
2.
> 6612 prescribed quantity gets overriden

- client/packages/common/src/types/schema.ts
- server/graphql/core/src/loader/vaccine_course.rs
- server/graphql/types/src/types/vaccine_course_dose.rs
- server/graphql/vaccine_course/src/vaccine_course_queries.rs
- server/repository/src/db_diesel/vaccine_course/vaccine_course.rs
Fixes #6398
We soft delete vaccine courses/doses, so that we can still show these doses in a patient's vaccine card if they have already received them (even if future patients should no longer receive them)
We were handling when doses were deleted from a course, but not if a whole course was deleted. This PR adds an `include_deleted` filter to the vaccine courses, when querying a vaccine course dose.
Dose from deleted course can now load:
1.
2.
> 6398 display existing doses from deleted vaccine courses

- client/packages/common/src/ui/components/errors/NothingHere.tsx
- client/packages/system/src/Item/DetailView/Tabs/ItemVariants/ItemVariantsTab.tsx
Fixes #6441 (maybe???)
Change the way we open the modal to be consistent with the other button.
Not sure why it would matter though...
This probably isn't the right fix, I don't understand how we have different behaviour with this change!
1.
2.
**Tests Pass**
> 6441 fix add item variant

- server/repository/src/db_diesel/report_row.rs
- server/repository/src/migrations/v2_06_00/reinitialise_reports.rs
Fixes #6668
Update fragment to set context to be enum for postgres.
Changing fragment name will mean it will re-run
Custom report will be lost, but that is ok
For some reason this migration did not run so we had to add it again
https://github.com/msupply-foundation/open-msupply/blob/342394370b71b799f9af617022f128262a9a5427/server/repository/src/migrations/v2_00_00/returns/return_context_types.rs#L8-L9
Make sure reports work in postgres
> 6668 fix context type in report migration

- client/packages/requisitions/src/RequestRequisition/DetailView/IndicatorEdit/CustomerIndicatorInfo.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/IndicatorEdit/IndicatorLineEdit.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/IndicatorEdit/IndicatorLineEdit.tsx
- client/packages/requisitions/src/utils.ts
Fixes #6496
The labels were being provided with a string that is supposed to be a translation key, but isn't.
I've changed the utility method to return a LocaleKey rather than a string, as that can be used as a string when required. It does remove the fallback, but we only have comment and value so I think it's ok.
1.
2.
> Translate labels

- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEdit.tsx
Fixes #6552
Issuing pack size straight from the batch line wasn't updating the dirty state, thus the api call never gets called 😅 
1.
2.
**Tests Pass**
> Set is dirty state when updating quantity

- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/intl/locales/pt/common.json
- client/packages/common/src/intl/locales/ru/common.json
- client/packages/programs/src/JsonForms/components/ProgramSearch.tsx
Fixes #
Fixes the required option in Program Search.
1.
2.
**Tests Pass**
> Make Program Search options optional

- server/cli/src/cli.rs
- server/cli/src/test_connection.rs
- server/service/src/apis/login_v4.rs
- server/service/src/login.rs
- server/service/src/sync/sync_user.rs
Fixes #5032 
This PR https://github.com/msupply-foundation/msupply/pull/16188 adds `siteName` to the login API to allow filtering by site, reducing the store permission records sent to just those of active stores on the site.
I could have made the API a set of store IDs instead. Maybe that'd have been better. 
1.
2.
**Tests Pass**
> 5032 add siteName to OG login v4 requests

- client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditForm.tsx
Fixes #6689
This seems to fix the problem. I'm not sure why the conditional was put there originally, but it caused the `setDefaultDirection("")` to skip out the "New" case. Now we just clear all these fields when the item switches.
**Tests Pass**
> #6689 Always clear directions abbreviation field

- client/packages/common/src/intl/utils/DateUtils.ts
- client/packages/invoices/src/Prescriptions/DetailView/Payments/PaymentsModal.tsx
- client/packages/system/src/Patient/apiModern/hooks/useInsurances.ts
Fixes #6677 (& #6692)
I just did the quick and dirty approach here and filtered out in the front-end rather than creating a whole new Filter structure on the server. Seemed acceptable given that the insurance list for a given patient should be pretty short and doesn't involve any pagination.
Also squeezed in a quick fix for #6692, since it's literally a one word change.
See inline 
**Tests Pass**
> #6677 Don't show expired or inactive insurances in Prescription payment

- client/packages/common/src/intl/locales/en/common.json
- client/packages/programs/src/VaccineCourseEditModal/VaccineCourseEditModal.tsx
Fixes #4884 
Adds this validation check before save ("OK")
I could make the other validation nice and indicate which row is nasty.
Will make an issue for renaming the columns Min/Max age to match the errors and flag stakeholders.
1.
2.
**Tests Pass**
> 4884 vaccine age range fixes

- server/service/src/sync/test/test_data/invoice.rs
- server/service/src/sync/translations/invoice.rs
Fixes #6504
Syncs the two new fields for "invoice" -- `cancelled_datetime` and `is_cancellation`, update tests.
We still need to add the functionality to properly link an invoice with its "cancellation" counterpart and update the `cancelled_datetime` in OMS, but we thought this would be better done in a processor once sync is completed. Will create a follow-up issue for that.
Paired with @jmbrunskill on this.
**Tests Pass**
> #6504 Sync Prescription is_cancellation and cancelled_datetime fields

- client/packages/common/src/intl/context/IntlContext.tsx
- client/packages/electron/src/home.tsx
- client/packages/host/src/Host.tsx
Fixes #6637
Initialises the i18n-next singleton outside of React, as intended usage. 
It's initialisation doesn't trigger a re-render, it's only because child components are re-rendering/querying the Intl context again that they end up with updated values. Higher in the component tree = higher risk that it is not initialised when you are first rendered.
This was the case with getting language settings in time to configure date translations. I wonder if this was also the actual cause of that translation keys on the discovery page bug?
Months now translated
1.
2.
**Tests Pass**
> 6637 fix date translations

- server/cli/src/cli.rs
Fixes #6527 
Fixes `show-report` cli command where test-config file was moved in restructure.
Now looks in the correct place.
You can test this report by trying to show a report with the show command using default test-config file location :
For example:
`cargo build && ./target/debug/remote_server_cli show-report --path ~"/Documents/GitHub/open-msupply-reports/clients/Ivory-Coast/satisfaction_per_program/2_6_0"` 
Where the relative location of the report repo may differ.
**Tests Pass**
> 6527 change test config default search location

- client/packages/system/src/Patient/CreatePatientModal/DefaultCreatePatientUISchema.json
- client/packages/system/src/Patient/PatientView/Footer.tsx
- client/packages/system/src/Patient/PatientView/PatientView.tsx
Fixes #6349 
JSON forms has an isDirty check on navigation baked in. So we don't need the extra custom one :)
1.
2.
**Tests Pass**
> 6349 fix double confirm

- client/packages/system/src/Patient/PatientView/PatientView.tsx
Fixes #6160
Disable Save button while required fields rendered:
This adds extension to the new patient documents, which allows the validation of custom fields before save/correct rendering of the errors under the fields. 
I think the issue was actually poorly configured JSON schema, can't seem to replicate error text showing but save but enabled now. 
data: [required-test.json](https://github.com/user-attachments/files/19020192/test.json)
ui: [required-test-ui.json](https://github.com/user-attachments/files/19020194/test.json)
1.
2.
**Tests Pass**
> 6160 disable patient save while fields required

- client/packages/invoices/src/Prescriptions/ListView/ListView.tsx
- client/packages/invoices/src/Prescriptions/ListView/Toolbar.tsx
- server/graphql/invoice/src/invoice_queries.rs
- server/repository/src/db_diesel/invoice.rs
Fixes #6706
- Added a new input field to the Invoice filter (createdOrBackdatedDatetime) to explicitly filter by this field (which is what the front-end is showing in the table
- Update front-end filters to use this field when filtering by date
Considered doing some more complex logic in back-end, but after discussion with @jmbrunskill this was considered the simplest way to fix the immediate bug.
**Tests Pass**
> #6706 Make prescription date filtering consistent with date shown in table

- client/packages/invoices/src/Prescriptions/DetailView/hooks/utils.tsx
- server/service/src/print/label.rs
Fixes #6768 
- Only print clinician if it exists
- 3 lines for details, 5 line for item directions+warning
- Some layout tweaks
Gist of the layout as per rendering on Labelary previewer:
A crude example of what that might look like (just duplicated field content on FE):
**Tests Pass**
> 6768 labels undefined clinician and trunc

- client/packages/system/src/Patient/PatientView/PatientView.tsx
Fixes #6772, #6774 
Aligns the saved data structure with the schema so that it can save correctly
The user can add next of kin, edit phone, address etc to a fetched patient and it will save with the new information
There was a comment in issue #6772 about no space between the code and hyphen in the next of kin dropdown. I had a look to fix this but was not an obvious/related fix. Probably best as a separate issue!
1.
2.
**Tests Pass**
> 6772 Save changes on patient

- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/intl/locales/fr/common.json
- client/packages/common/src/ui/components/inputs/Autocomplete/Autocomplete.tsx
- client/packages/common/src/ui/components/inputs/DatePickers/BaseDatePickerInput/BaseDatePickerInput.tsx
- client/packages/invoices/src/Prescriptions/DetailView/AppBarButton.tsx
- client/packages/system/src/Patient/Insurance/InsuranceModal.tsx
- client/packages/system/src/Patient/Insurance/InsurancePolicySelect.tsx
- client/packages/system/src/Patient/Insurance/InsuranceProvidersSelect.tsx
- client/packages/system/src/Patient/apiModern/hooks/useInsurancesPolicies.ts
Fixes #6766 
and most of #6604
Removes duplicate history button
Shows Required symbols for fields in Insurance modal
The french selection issue from #6604 is probably plugin related so, will look at that separately
1.
2.
**Tests Pass**
> 6604 dispensing fixes

- client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteWithPagination.tsx
- client/packages/programs/src/Components/PatientProgramSearchInput.tsx
- client/packages/programs/src/JsonForms/components/PatientProgramSearch.tsx
- client/packages/programs/src/JsonForms/components/PeriodSearch.tsx
- client/packages/programs/src/JsonForms/components/ProgramSearch.tsx
- client/packages/programs/src/api/hooks/usePeriodList.ts
Fixes #6784 & Fixes #6760
Retain program/period information when re-filtering 
https://github.com/user-attachments/assets/61c12fa1-1524-4486-8f23-6819feec35de
Also fixes periods not loading correctly
https://github.com/user-attachments/assets/33a34ee2-a977-4b2e-80ef-2136b1406811
1.
2.
**Tests Pass**
> 6784 report arguments selected program is not repopulated

- server/repository/src/migrations/v2_06_00/report_fix_prescriptions_report_code.rs
Fixes #6824 
Removes report changelog records, as there's a risk they could cause issues with sync due to re-initialising reports in the database.
This logic should probably be in an updated `reinitialise_reports` migraiton fragment, however there's code in there to add types to postgres which would need to be run conditionally in QA environments so I thought it was better here.
We can possibly get away with not having htis in the release, however I'm not sure if we might have some issues with some 2.5 - 2.6 upgrades? Feels safer to delete I think...
1.
2.
**Tests Pass**
> Remove report changelogs

- client/packages/invoices/src/Prescriptions/DetailView/SidePanel/PrescriptionDetailsSection.tsx
- client/packages/invoices/src/Prescriptions/DetailView/Toolbar.tsx
Fixes #6792 & #6815
For Prescription detail view:
- Moves Clinician back to main Toolbar (from Side Panel)
- Remove "Date" from side panel as it's just a duplicate of the Toolbar one
Removed a bit of commented out code that was leftover from recent dispensing changes.
**Tests Pass**
> #6792 #6815 Re-shuffle Prescription Toolbar and Sidebar items

- client/packages/host/src/CommandK.tsx
- client/packages/host/src/Host.tsx
Fixes #6829
Turns out that when the DialogButton component is rendered inside the confirmation modal, it actually gets rendered outside the main component tree of the DOM, so it's not with the `<CommandK>` Provider boundary, and so attempts to register shortcuts with KBar's `useRegisterActions` throw an error.
Have now moved the `<KBarProvider>` to the top the of the Provider tree in `Host.tsx`, and decoupled it from the `CommandK` file where we define and provide a custom implementation of KBar.
**Tests Pass**
> #6829 Fix for Kbar context error

- client/packages/requisitions/src/RequestRequisition/DetailView/IndicatorEdit/CustomerIndicatorInfo.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/IndicatorEdit/IndicatorLineEdit.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
- client/packages/system/src/Item/DetailView/Tabs/ItemLedger.tsx
- server/repository/src/db_diesel/indicator_value.rs
- server/service/src/requisition/common.rs
- server/service/src/requisition/request_requisition/indicator_information.rs
- server/service/src/requisition/request_requisition/insert_program.rs
- server/service/src/requisition/response_requisition/insert_program.rs
Part 1 #6764
- Filter outindicator info by customers with stores since we don't create indicators for customers without stores, so shouldn't show them
- Fix bug with limiting orders 
- Remove number from ledger
Other requests in issue pending confirmation
1. Item Ledger screenshots
2.
**Tests Pass**
> 6764 internal orders review

- server/service/src/sync/translations/invoice_line.rs
Fixes #6712 
OG/Mobile remote sites munge null fields to empty values e.g. strings to `""`. This breaks inbound shipment invoice line FK constraints in OMS when a OG supplier remote site makes a CI to a OMS site. Unless the FK field has     `#[serde(deserialize_with = "empty_str_as_option_string")]`!
Suppliers on OG central server will not exhibit this bug, it must be a remote site OG supplier (or old mobile)
**Tests Pass**
> 6712 safely deserialise invoice_line.item_variant_id

- client/packages/common/src/intl/locales/en/common.json
- client/packages/host/src/components/Sync/SyncModal.tsx
- server/service/src/requisition/request_requisition/use_suggested_quantity.rs
Fixes #6069 
Update suggested quantitiy button to only update requested quantities with suggested quantities if requested quantity value is 0
I couldn't find anything that states that response requisitions has the same functionality of using suggested quantities to update requested quantity. If I'm wrong in how I've understood it, then happy to find and make the change in this PR.
1.
2.
**Tests Pass**
> 6069 fix suggested quantities replacing requested quantities - internal order

- client/packages/invoices/src/Returns/CustomerDetailView/Footer/StatusChangeButton.tsx
Fixes #6819
Changes status check since transfer invoices can never be `New` we should be checking that the status is `Shipped` to enable `Delivered` and `Verified` statuses
1.
2.
**Tests Pass**
> 6819 The confirm delivered option of customer returns is greyed out when it has been created from returning stock from another store

- client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteList.tsx
Fixes #6818
This just ensures the "Autocomplete" is opened, rather than relying on the value returned from `useOpenStateWithKeyboard` hook
I'm not particularly happy with this fix, but I think it will take too long to investigate more thoroughly, and this works.
I'm reasonably sure that we don't actually need the `useOpenStateWithKeyboard` hook and that the root of the problem is to do with this: https://github.com/msupply-foundation/open-msupply/issues/6311. But fixing that will require a bit more time.
Equally important here is that we haven't caused any regressions. Please ensure the modal behaves correctly, by which I mean:
Please check that behaviour in the following scenarios, on both Android AND desktop browser:
The PR Reviewer(s) should fill out this section before approving the …
> 6818 Fix autocomplete appearance on Android

- server/repository/src/db_diesel/assets/asset_row.rs
- server/service/src/asset/delete.rs
Fixes #5314 
- Adds delete sync for assets
- Remote sites can delete their assets. This is synced to OMS central server.
- Central server can delete assets from any site. This is synced to remote sites.
Repeat the above steps for each permutation of creation and deleting:
Create from central - delete from remote
Create from remote - delete from central
Create from remote - delete from remote
In all cases the asset will show up on both when created from either central and remote when created, and will be removed from both when deleted from either.
**Tests Pass**
> Add soft delete translations

- client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditForm.tsx
Fixes #6895 
Removes rounding to no decimals from prescription prescribed quantity display.
You can more easily view changes without new linting changes [here](https://github.com/msupply-foundation/open-msupply/compare/53c6b07271bc0e64962a45717574b72ea2a210ce...c694f1e940236352115c8128870232e25daa9d0d)
Values passed around retain all information; they were just getting rounded before front end display.
**Tests Pass**
> 6895 don't round displayed prescribed quantity

- server/service/src/sync/test/test_data/invoice.rs
- server/service/src/sync/translations/invoice.rs
Fixes #6224
If a transaction comes in via sync,and we don't have the associated user_id, a default user is created with blank details
I haven't really tested this with a real scenario, I assume that's ok as @alainsussol  can test his real world scenario?
See issue #6224 for testing steps
1.
2.
**Tests Pass**
> 6224 create dummy users on sync

- client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx
Fixes #6891
stocktake line edit move expiry date column to right of batch column
1. Need to update images to reflect new column order in docs
2. And column description markdown tables and/or lists
**Tests Pass**
> 6891 stocktake line edit move expiry date column to right of batch column

- client/packages/system/src/Patient/CreatePatientModal/PatientResultsTab.tsx
- client/packages/system/src/Patient/ListView/ListView.tsx
- client/packages/system/src/Patient/PatientView/index.ts
Fixes #6863
- Translate gender in list view and in the search modal
- Change deceased in search modal to a dot cell to match with list view
1.
2.
**Tests Pass**
> 6863 patient list view gender & deceased fields are not translated to respective languages

- client/packages/host/src/components/Navigation/ColdChainNav.tsx
Fixes #6931 
Restores missing Cold Chain items in AppDrawer, but only conditionally (i.e. dont' show on Mobile)
**Tests Pass**
> #6391 Fix missing Cold chain nav items

- client/packages/system/src/Patient/PatientView/AddButton.tsx
- client/packages/system/src/Patient/PatientView/AppBarButtons.tsx
- client/packages/system/src/Patient/PatientView/PatientDetailView.tsx
- client/packages/system/src/Patient/PatientView/PatientView.tsx
Fixes #6889 
If insuranceProviders are available, the tab should show for insurance, even if the Uses Program Module is turned off.
Side Quest: I've moved `PatientDetailView` to its own file. `PatientView` had a lot going on for it, navigating can be a bit overwhelming
If you have insurance providers in your store and programs module is on
If you don't have insurance providers in your store and programs module is off
If you don't have insurance providers in your store but programs module is on
1.
2.
**Tests Pass**
> 6889 enable insurance tab even when program module off

- client/packages/common/src/ui/components/errors/NothingHere.tsx
- client/packages/system/src/Location/Components/LocationSearchInput.tsx
Fixes #6729 
Fix check for an undefined location so that "remove" option does not show in list if no location selected.
Sidequest:
Update colours based on @mariyamsupply feedback for nothing here view to make link colour consistent with other links and message more accessible.
1.
2.
**Tests Pass**
> 6729 fix remove option when no location selected

- client/packages/system/src/Encounter/DetailView/Toolbar.tsx
- client/packages/system/src/Patient/Encounter/CreateEncounterForm.tsx
- client/packages/system/src/Vaccination/Components/VaccinationModal.tsx
Fixes #6694 
- Hides the clinician search input if there are no clinicians configured
- Becomes visible if a clinician is added in OG
Encounter Modal
Encounter Toolbar
Vaccine Modal
ClinicianSearchInput is in three other places currently:
- Vaccination Modal
- New Prescription Modal
- Prescriptions Detail View (Toolbar)
Unsure if it's in the plans or not, but if we were to create the same changes in all of these, we could then pass the clinician data to the search input, rather than calling it through the api in the modal/toolbar and then again when using the search input
1.
2.
**Tests Pass**
> conditionally hide clinicians from encounters

- client/packages/invoices/src/Prescriptions/DetailView/SidePanel/AdditionalInfoSection.tsx
- client/packages/invoices/src/Prescriptions/DetailView/SidePanel/PatientDetails.tsx
- client/packages/invoices/src/Prescriptions/DetailView/SidePanel/PrescriptionDetailsSection.tsx
- client/packages/system/src/Program/ProgramSearchInput.tsx
Fixes #6795 
Makes background of the diagnosis input in the prescriptions' sidebar white.
Make the width of the inputs consistent.
Further work might be done to improve the sidebar as other problems do remain (e.g. the spacing between the input labels and the inputs is inconsistent).
The intention is that this PR will get RC2.6.1 over the line in time.
**Tests Pass**
> 6795 prescription sidebar styling

- client/packages/system/src/Vaccination/Components/SelectBatch.tsx
Fixes #6758 
Two changes within the vaccine batch selection table:
- Fixed the alignment of the table headers with table columns
- disabled the checkbox if there is only one batch of the vaccine item 
The checkbox was already auto-selected and unable to be unticked, this adds the visual 'greyed out' so the user knows it is unable to be changed, vs with multiple batches it can be changed
Multiple batches
One batch
1.
2.
**Tests Pass**
> 6758 Vaccine dose UI updates

- server/service/src/sync/translations/requisition.rs
- server/util/src/constants.rs
Fixes #6915
Use 30 instead of days in month const. Min threshold seems to be correct and doesn't need changing
1.
2.
**Tests Pass**
> 6915 Target MOS is slightly different after migration

- client/packages/programs/src/JsonForms/components/Search/SearchWithUserSource.tsx
Fixes #6600
Filter out current patient from the next of kin search
1.
2.
**Tests Pass**
> 6600 Able to link yourself as a patient in Next of Kin

- server/service/src/sync/translations/program_requisition_settings.rs
Fixes #6896
Save deleted_datetime based on inactive field for program master lists
1.
2.
**Tests Pass**
> 6896 Deleting an immunization program master list in OG is not reflected in OMS

- server/service/src/sync/test/test_data/invoice_line.rs
- server/service/src/sync/translations/invoice_line.rs
Fixes #5713
Fixes stock line 
Not sure if this fixes it... but added a test and it seems fine? 
1.
2.
**Tests Pass**
> 5713 empty inbound shipment sent to oms site

- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/intl/locales/fr/common.json
- client/packages/programs/src/JsonForms/common/components/Autocomplete.tsx
- client/packages/system/src/Patient/ContactTrace/Components/ContactTraceSearchInput.tsx
Fixes #6970
Adds no options translations. 
1.
2.
**Tests Pass**
> 6970 translations 'no options' text when no options are shown needs to be translatable

- client/packages/coldchain/src/Equipment/ListView/AppBarButtons.tsx
- client/packages/coldchain/src/Equipment/ListView/ListView.tsx
- client/packages/common/src/intl/locales/en/common.json
Fixes #6939 
When an accounts permissions View/Edit/Add assets are disabled. They can still click on the import button and access the modal for it. 
Applied the use of the hook `useCallbackWithPermission` to return a helpful message to the user that they don't have the right permission to take this action.
Ensure that `View assets` and `Add/Edit assets` are turned **off** the account that you're currently logged in.
1.
2.
**Tests Pass**
> 6939 use callback permission hook for import button click

- client/packages/host/src/Admin/SyncSettings.tsx
Fixes #3406
Reduce site password field width in sync settings so that it aligns with name and url fields
1.
2.
**Tests Pass**
> 3406 Reduce site password field width in sync settings

- server/server/src/static_files.rs
- server/server/src/upload.rs
- server/server/src/upload_fridge_tag.rs
- server/service/src/static_files.rs
- server/service/src/sync/sync_on_central/mod.rs
Fixes #6997 & #7014
Modifies the server's `upload_sync_file` endpoint function to handle an array of files rather than just the first one in the `formData` array.
**Tests Pass**
> #6997 #7014 Multiple file upload

- client/packages/requisitions/src/RequestRequisition/DetailView/Footer/StatusChangeButton.tsx
Fixes #6856
Only generate comment for Internal Orders if the user has remote auth enabled
1.
2.
**Tests Pass**
> 6856 Auto-generated comment field is not relevant for all (and is unclear)

- client/packages/coldchain/src/Equipment/DetailView/Footer/Footer.tsx
- client/packages/coldchain/src/Equipment/ImportAsset/UploadTab.tsx
- client/packages/coldchain/src/Equipment/utils.ts
Fixes #6280 
This PR makes sure that the needs replacement field of cold chain equipment is correctly imported and exported.
It achieves this by adding a formatting function to the 'needs replacement' field in one of the functions that processes the data imported from the csv data.
You'll find that function in line 336 of client/packages/coldchain/src/Equipment/ImportAsset/UploadTab.tsx.
It seems the side bug of the issue (that sometimes a blank was inserted instead of 'false' in the needs replacement column in the exported CSV file) was resolved as well as, when I checked it, it seemed that false was consistently added to the correct rows in the CSV file.
**Tests Pass**
> 6280 fix exporting and importing coldchain equipment

- client/packages/invoices/src/InboundShipment/ListView/AppBarButtons.tsx
Fixes #7057
Memorize createInvoice method and add as dependency to useEffect so it doesn't fire twice. 
1.
2.
**Tests Pass**
> 7057 create new inbound shipment firing twice and creates two shipments

- client/packages/common/src/hooks/useConfirmOnLeaving/useConfirmOnLeaving.ts
- client/packages/invoices/src/Prescriptions/LineEditView/LineEditView.tsx
Fixes #6321
Turns out custom check for confirm on leaving wasn't being used for refresh, have added this:
1.
2.
**Tests Pass**
> 6321 block prescription line edit refresh

- client/packages/electron/webpack.plugins.ts
Fixes #4858 
This is a re-do of https://github.com/msupply-foundation/open-msupply/pull/4946 which got closed due to no replication.
I'm suggesting we try this out on a build to see if it fixed issues that we're seeing.
Thanks @lache-melvin for the code and investigation...
Copies translation files to two locations for Electron (AKA Desktop)
Haven't tested this yet, but change looks safe so wanted to re-create the PR.
1.
2.
**Tests Pass**
> Possible fix for electron discovery missing translations

- package.json
Bump version to 2.6.1-RC5 (can't push directly due to branch protection)
> V2.6.1 RC5 Bump version

- server/repository/src/db_diesel/assets/asset_internal_location_row.rs
- server/service/src/asset/insert.rs
- server/service/src/asset/tests/insert.rs
- server/service/src/asset/tests/update.rs
Fixes #7001
Automatically creates a location for any newly created assets.
Location is named after the assetNumber.
I feel like it would be nice to have an asset `Name` field that we could use here?
Having a name like Fridge 1 would be much nicer than a location named asset ABCE1234 I don't think it would be meaningful.
@mark-prins @adamdewey  what do you think about that idea?
We also create an initial status log for the asset in the frontend code. Should we move this to the backend?
I suspect it might have been done this way to allow using the translations in the comment. I feel like we could probably just leave the comment blank? Or maybe it's ok how it is...
1.
2.
**Tests …
> Automatically create a location for new CCE assets

- server/graphql/programs/src/mutations/contact_trace/insert.rs
- server/graphql/programs/src/mutations/contact_trace/update.rs
- server/graphql/programs/src/mutations/program_enrolment/insert.rs
- server/graphql/programs/src/mutations/program_enrolment/update.rs
- server/graphql/programs/src/mutations/program_patient/insert.rs
- server/graphql/programs/src/mutations/program_patient/update.rs
- server/service/src/programs/contact_trace/upsert.rs
- server/service/src/programs/patient/upsert_program_patient.rs
- server/service/src/programs/program_enrolment/upsert.rs
Fixes #6030 
Fixed a typo in error messages relating to DocumentTypeDoesNotExit and PatientDocumentRegistryDoesNotExit
Both now say 'Exist' rather than 'Exit'
I found more instances of this than was in the original issue
These are backend errors only, and should not appear to a user. They had in the original issue, however this has not been replicated
Error expected to see in testing steps:
1.
2.
**Tests Pass**
> Fix typo in gql errors for document registry

- server/repository/src/db_diesel/insurance_provider_row.rs
- server/service/src/insurance_provider/query.rs
Fixes #6691
Adds option for filter for is_active in insurance_provider_row.
Replaces insurance provider query to search for find_all_active in stead of find_all
Not a sync related issue after all
I notice that we don't use any filtering for is_active in find_all in any of our row repositories, and would typically use a repository file to handle queries with filtering.
We do do find_active_by_id in row repositories, but never a list.
That being said, I'm not sure if what I've done is an acceptable pattern as it isn't used elsewhere.
I added this because adding a repository layer with query + filtering etc seemed like a lot of overhead if we aren't going to use any of the other functionality (pagination, custom filters, etc).
The PR Reviewer(s) should fill out this section before approving …
> Add find_all_active pattern

- client/packages/coldchain/src/Equipment/ListView/CreateAssetModal.tsx
- client/packages/host/src/components/Navigation/ColdChainNav.tsx
Fixes #7122 
Doesn't crash when accessing nested nodes
I'm wondering if the cold chain nav segment should be visible at all if the user doesn't have view asset permissions?
Is there a use case for seeing temperature logs without reference to the asset?
APK to test on android [here](https://drive.google.com/file/d/1oWbqp5jK1_u5b1RPA4Kt6Ix4lK0jCIKR/view?usp=drive_link)
Note mobile was also experiencing this crash so testing here would also be helpful (though they're using the same code)
**Tests Pass**
> 7122 fix permission error on cold chain equipment

- client/packages/common/src/ui/components/inputs/Filters/DateFilter.tsx
Fixes #5280 
Renders a select amount of years rather than 10,000
I've arbitrarily chosen the limit of 50 years ahead, and 120 years behind (to capture a reasonable date of birth option).
These values could be customised for a specific filter by passing in custom end ranges if we wanted to be more specific (ie it doesn't necessarily make sense to have a date of birth year option in the future).
This issue only fixes the described issue of render time
**Tests Pass**
> Prevents render of too many years

- client/packages/common/src/plugins/prescriptionTypes.ts
- client/packages/invoices/src/Prescriptions/DetailView/Payments/PaymentsModal.tsx
Fixes #7105
Updated the plugin behaviour so that the Error message goes away as soon as the entered value is enough to complete the payment.
Need to have this plugin branch checked out as well: https://github.com/msupply-foundation/civ-plugins/pull/5
**Tests Pass**
> #7105 Improve prescription payment error

- client/packages/plugins/backendCommon/utils.ts
Fixes #7147 
Fix plugin sql helpers to be plugin compliant.
I also found that json_agg will return [null] if there are no rows, which cause deserialization error, actually json_build_object is simpler, it's the same as sqlite
I've udpated [plugin examples](https://github.com/msupply-foundation/open-msupply-plugins/pull/14) to be postgres compliant too, you can grab that plugin repo, with generate and install command or just use [this bundle](https://github.com/msupply-foundation/open-msupply-plugins/blob/3980359242909713cee03389a30633689b3ba5f2/bundle.json) with `cargo run --bin remote_server_cli -- install-plugin-bundle -p bundle.json --url 'http://localhost:8000' --username admin --password pass`
Use postgres
You may need to delete your exisiting backend plugins before running above …
> 7147 Fix plugin sql helpers to be postgres compliant

- server/util/src/api_helper.rs
Fixes #7196
Adds total timeout of 5mins to sync http requests using the api helper. Long duration in case reading big response on low bandwidth, and otherwise covers all bases such as getting stuck writing body in the request.
read_timeout too of 30s. If it stops reading anything from the connection for over 30s we timeout. 
You will see an error like this. We can make it pretty by handling it properly later.
1.
2.
**Tests Pass**
> 7196 sync http request timeout

- client/packages/system/src/Stock/Components/InventoryAdjustment/InventoryAdjustmentModal.tsx
- client/packages/system/src/Stock/Components/StockLineForm.tsx
- client/packages/system/src/Stock/ListView/ListView.tsx
Fixes #6941 
This PR makes sure that Open mSupply rounds the pack quantities to 2 decimal places when it displays them.
It adds rounding functions to the pack quantities where they are displayed, in the:
- stock list view
- stock detail view
- inventory adjustment menu
Before (from a comment in the original issue discussion):
https://private-user-images.githubusercontent.com/163234798/424233451-cd0a0dae-81d0-416e-a327-7f42fa0d1b52.mov?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDM3Mjk3MjgsIm5iZiI6MTc0MzcyOTQyOCwicGF0aCI6Ii8xNjMyMzQ3OTgvNDI0MjMzNDUxLWNkMGEwZGFlLTgxZDAtNDE2ZS1hMzI3LTdmNDJmYTBkMWI1Mi5tb3Y_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRa …
> 6941 fix stock quantity rounding

- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditForm.tsx
Fixes #7113
Have shuffled the contents around a bit so that the alerts appear to the right of the "Issue" UI rather than push in in front of it:
Also tweaked padding and top-alignment to make it look okay with multiple alerts
Haven't addressed the "NaN" problem, as it seems to be due to a pack size being set to 0, as discussed in the original issue. Let me know if you find if/where this is not the case.
**Tests Pass**
> #7113 Outbound alerts layout

- client/packages/coldchain/src/Equipment/ImportAsset/EquipmentImportModal.tsx
- client/packages/system/src/Asset/ListView/Footer.tsx
- client/packages/system/src/Asset/api/hooks/index.ts
- client/packages/system/src/Asset/api/hooks/useAssetDelete.ts
- client/packages/system/src/Asset/api/hooks/useAssetList.ts
Fixes #7208 
Importing an asset or equipment CSV returns an error. This happens because `useTableStore` is called within `useAssetList`, which causes a bunch of re-renders. 
These re-renders occur due to the state or data in `useTableStore` being updated/populated when a new file is imported.
Created a `useAssetDelete` hook to separate the concern of managing `useTableStore's` state. Keeping `useTableStore` within `useAssetList` was causing unnecessary re-renders, so moving the delete logic to its own hook resolves this issue.
Applying memoization techniques (`useMemo`, `useCallback`) didn't produce any luck in terms of solving this issue, hence created a dedicated hook for it instead
1.
2. …
> 7208 fix import asset and equipment csv error

- client/packages/common/src/ui/components/inputs/DatePickers/DateTimePickerInput/DateTimePickerInput.tsx
Fixes #7241
Merge got rid of the translations in datetime picker
1.
2.
**Tests Pass**
> Translations: datepicker's buttons show in English #7241

- package.json
- server/repository/src/migrations/mod.rs
- server/repository/src/migrations/v2_06_02/mod.rs
- server/repository/src/migrations/v2_06_02/store_reintegrate_for_created_date.rs
- server/service/src/processors/transfer/invoice/create_inbound_invoice.rs
- server/service/src/processors/transfer/invoice/mod.rs
- server/util/src/api_helper.rs
Fixes #7249
Fixes #7200 
Fixes #7234 
- store table reintegrated to ensure store.created_date is populated
- only create transfers if the `linked_invoice_id` is blank
- remove `read_timeout` from sync http requests to avoid dropping connection when 4D is taking it's time flushing memory to DB.
---
---
**Tests Pass**
> 7249 2.6.2 migration reintegrate store, skip transfers on linked_invoice_id.is_some()

- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/intl/locales/fr/common.json
- client/packages/system/src/Patient/Insurance/InsuranceModal.tsx
Fixes #7225 partially
Fixes insurance related feedback changes
Adds insurance specific expiration date translation key
Changes discount rate to coverage rate key
**Tests Pass**
> Add translation changes for insurance

- server/graphql/types/src/types/program/encounter.rs
- server/repository/src/migrations/v2_07_00/mod.rs
- server/repository/src/migrations/v2_07_00/remove_encounter_clinician_constraint.rs
Fixes #7228
Store A (Site Y) created an encounter which has an associated clinician. 
Store B (Site Z) tries to pull the encounter, as it also has visibility of the patient.
Fixes 2 cases:
- No stores on Site Z have visibility of the linked clinician. The om_document failed sync translation, and no encounter was visible in store B
- A different store on Site Z has visibility of the linked clinician, but not Store B. The translation passes, you can see the encounter in the list view, but when you click it to go to the detail view, got not found error (as clinician not exist for store).
I tried to to add store_id to encounter create_filtered_query, and only left_join onto clinicians table where clinicians visible via clinician store join. But it was a diesel type error rabbit hole, felt I …
> 7228 cant access encounter if clinician not visible

- client/packages/invoices/src/Prescriptions/api/operations.generated.ts
- client/packages/invoices/src/Prescriptions/api/operations.graphql
- client/packages/programs/src/JsonForms/components/Prescription/PrescriptionInfo.tsx
- client/packages/system/src/Vaccination/Components/VaccinationModal.tsx
- client/packages/system/src/Vaccination/api/operations.generated.ts
- client/packages/system/src/Vaccination/api/operations.graphql
Fixes #7232
Hide link to prescription if the prescription was created at a different store. Both in vaccination cards and the reproductive health encounter UI
Feels like we should be disabling the facility input if the vax was given at another store... to eliminate someone accidentally changing it but 🤷🏻 
1. Document that the prescription link won't be available if it was created at another store
2.
**Tests Pass**
> 7232 unable to access linked prescription from vax card from another store

- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/intl/locales/fr/common.json
- client/packages/system/src/Report/api/hooks/usePrintReport.ts
Fixes #7235 
This PR makes the printing error messages translatable and adds a french translation for them.
**Tests Pass**
> Make print errors translatable and add translations

- server/repository/src/db_diesel/vaccination_row.rs
- server/service/src/vaccination/update/generate.rs
- server/service/src/vaccination/update/mod.rs
- server/service/src/vaccination/update/validate.rs
Part of #7285
Refactor update vaccination logic, use enum to determine valid updates to a vaccination.
Reasoning:
- It was already very confusing to follow the validation and generation logic in the vaccination updates
- This issue will be adding more constraints, what you can do as the "giving" store vs other store
- Some checks (like stock_line_exists) should really only need to run if you were to giving store, and are wanting to ungive, but they were running every time
- This should improve maintainability going forward
1.
2.
**Tests Pass**
> refactor: use enum for valid vaccination actions

- client/packages/system/src/Stock/DetailView/DetailView.tsx
Fixes #7186 
Display confirmation modal if user navigates away from or refreshes page with unsaved changes
Added a `useEffect` that syncs stockLine `isDirty` state with `useConfirmationOnLeaving` hook's internal `isDirty` state
https://github.com/user-attachments/assets/6db79f22-01b5-4aba-8a21-301a383c5b73
I did some reading and tried to see if I could do this without using the `useEffect`. Unfortunately, I wasn't able to figure that out. Please let me know if I've missed something! 
1.
2.
**Tests Pass**
> 7186 Add confirmation on leaving modal when navigating with unsaved changes - View stock

- server/service/src/sync/api_v6/core.rs
Fixes #7339
Adds the same timeout introduced in https://github.com/msupply-foundation/open-msupply/pull/7201 but to get_site_status api call
As per issue
1.
2.
**Tests Pass**
> 7339 Timeout on get_site_status v6 api call

- client/packages/common/src/ui/components/buttons/standard/SplitButton.tsx
Fixes #7278
Makes full menu item in new split button functionality clickable.
Previously only text was clickable.
(A good example of this is in inboundShipments -> open a shipment -> and see the 'add item' split button drop down
**Tests Pass**
> Split button drop down now clickable across entire component

- client/packages/system/src/Patient/apiModern/hooks/useInsurancesPolicies.ts
Fixes #7164 
Add `nameId` to insurance policies query keys, ensuring caching happens, and refetches when `nameId` changes
1.
2.
**Tests Pass**
> 7164 add name id into insurance policies query keys

- client/packages/system/src/Manage/Preferences/api/useEditPreference.ts
Fixes #7320 
This PR makes it so that if you change a preference, then navigate to the main preferences page, then go back to that preference, it will display the value you changed it to.
Before, it displayed the old value, the value you changed it from.
**Tests Pass**
> 7320 Reflect User-Made Changes to Preferences Without Leaving the Preferences Page

- client/packages/invoices/src/Prescriptions/api/hooks/usePrescription.ts
- client/packages/programs/src/JsonForms/components/Prescription/Prescription.tsx
Fixes #7327 (sort of)
I'm just putting in a temporary workaround to remove the immediate problem (for impending demo). Will need to get to the bottom of the React Query issues at some point
The bug **only appears in production builds**. I've narrowed this down to inconsistent behaviour in React Query -- the `loading` and `error` values are not being updated correctly after the invoice is not found (`loading` stays `true`, so the spinner never goes away).
So for now I've just hidden the "Loading" indicator completely. I tried a couple of other things, namely returning a custom loading property from the hook, but it caused other problems, so leaving that out for now.
I'll post a link to this PR in the Update Tanstack issue.
Must be tested on Production build:
- run `yarn build` from the …
> #7327 Prescription loading fix

- server/repository/src/migrations/v2_06_02/mod.rs
- server/repository/src/migrations/v2_07_00/change_vaccination_date_to_not_nullable.rs
- server/repository/src/migrations/v2_07_00/mod.rs
Fixes #7299 
In 2.6.1, vaccination date was allowed to be nullable (for not given records). This has been removed in 2.7, we always record the date for reporting. If you created vaccination records after 2.6.1, will null date, the change_vaccination_date_to_not_nullable migration will fail:
`UNKNOWN ("NOT NULL constraint failed: vaccination.vaccination_date      0"`
This PR Fixes a migration so it no longer breaks OMS when you update from v2.6.1 to v2.7.0.
The migration now deletes records in the vaccination table with null vaccination dates and their changelogs, so the vaccination date can then be made not null
This needs to be recorded in the release notes obviously, as data could be lost.
Specifically:
- Vaccinations with no date (which can only have been created in version 2.6.1) will …
> Delete records with null vaccination dates and their changelogs

- package.json
- server/service/src/number.rs
Fixes #7443
Prevents serial numbers lower than 1 being assigned
Unit tests now cover this case. To test manually:
1.
2.
**Tests Pass**
> 7443 assigned requisition number is 0

- build/windows/omsupply_server.suf
Fixes #7149
I went to Jenkins server opened up setup factor and found msupply-server job.  After some exploration found that the difference between server executable and cli executable was this:
I set always overwrite on cli, saved the suf, opened and copied it's content to my local vs code, noticed diff was <Overwrite>2 (from 1), applied that to other artifacts in suf, create tag to test `v2.6.3-TEST-7149`
Stand alone suf didn't have cli, so didn't change.
You can look through the rest of suf file, and see <Overwrite>2 for normal exe (look up a few xml nodes)
Check you server program files directory, seem that `cli` is old (modified date), upgrade the server, see cli modified is the same date as server exe
1.
2. …
> 7149 Always overwrite cli and tester executables when installing/updating omSupply server

- client/packages/common/src/intl/utils/DateUtils.ts
- client/packages/common/src/types/schema.ts
- client/packages/host/src/components/AppDrawer/SyncNavLink.tsx
- client/packages/host/src/utils.ts
- client/packages/system/src/Sync/api/operations.generated.ts
- client/packages/system/src/Sync/api/operations.graphql
- client/packages/system/src/Vaccination/api/operations.generated.ts
- server/graphql/general/src/queries/sync_status.rs
- server/service/src/sync/sync_status/status.rs
Fixes #6446 
No longer show the badge if there are simply pending records
If connection has failed for over a day show a warning icon with warning colour (orange)
If connection has failed for over 3 days show a warning icon with error colour (red)
If there is any error OTHER than an a connection error (i.e. unreachable due to bad internet) then immediately show a warning icon with error colour 
I've left some scaffolding for the opportunity to implement prefs for the warning/error thresholds. Can be another issue when we have time for it? If we care enough for it? heh.
Frankly, the red and orange colours don't look much different on such a small icon. I think this feature could be simplified as one threshold.
I think due to buttons not having borders the badges being on top right of the …
> 6446 nav sync badge after period of error

- client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEdit.tsx
Fixes #7455
Id being passed into the footer was the line id not the requisition id
1.
2.
**Tests Pass**
> 7455 Infinite loading in requisition when clicking on Next item

- client/packages/invoices/src/InboundShipment/ListView/AppBarButtons.tsx
- client/packages/invoices/src/InboundShipment/ListView/LinkInternalOrderModal.tsx
- client/packages/invoices/src/InboundShipment/api/hooks/document/index.ts
- client/packages/invoices/src/InboundShipment/api/hooks/document/useListInternalOrders.ts
- client/packages/invoices/src/InboundShipment/api/hooks/index.ts
Fixes #7434
Fixes cannot create inbound shipment when there are no internal orders to link AND store preference is to manually link inboundshipment to other party's internal order
**Tests Pass**
> Add can add when no internal orders exist

- server/util/src/api_helper.rs
Fixes #7410 
Extend sync api timeout to 30 minutes
See issue for more details
Can potentially replicate consistently on setup that @alainsussol had, or you can put a breakpoint in a sync method in 4d. Basically we allow up to 5 minutes (before this PR) for a round trip of a request, now it's extended to 30 minutes. 
1.
2.
**Tests Pass**
> 7410 Extend total timeout in sync api

- client/packages/invoices/src/Prescriptions/LineEditView/LineEditView.tsx
- client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEdit.tsx
- client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditForm.tsx
- client/packages/invoices/src/Prescriptions/LineEditView/hooks/useDraftPrescriptionLines.tsx
Fixes #7421
Fixes the onAllocate check, was enabling the save button based on _attempted_ allocated number of packs, instead of actual allocated packs. Shouldn't be able to save if num packs is 0 (unless prescribed quan is set)
Also fixes - couldn't backspace the prescribed quan field
And fixes setBreadcrumb, wasn't setting the prescription number if you refreshed/opened on the new item page.
This area realllly needs refactoring, we should just be saving the item we are currently looking at, with a draft state we can easily run validation against before save/disable the save button until valid.
But currently prescription draft contains a draft line for every item/stock line touched (you can switch items, it doesn't remove the previous draft lines) - so it's "valid" to have invalid lines …
> 7421 breadcrumbs show uuids

- .github/workflows/build-android-apk.yaml
Soz, lil side quest
When downloading our installers, they're all co-located because of Open_mSupply prefix, but these zip files were harder to find in downloads folder, just called "Universal_Build"
Adds prefix so all installers are together
Apologies, formatter had a field day - its actually just the names that changed
I think would be good to also put the version in the name? So if you download multiple, you can see which version they are for rather than `Open_mSupply_Universal_Build(2)`
Would require getting version in action outputs though - #7450 
1.
2.
**Tests Pass**
> add Open_mSupply prefix to APK zip files

- client/packages/invoices/src/Prescriptions/LineEditView/LineEditView.tsx
Fixes #7480
Triggers the breadcrumb useEffect when the URL item id changes, so it runs when we switch to `new` item.
Roxy commented in the issue, about one of the items remaining even after setting issue quantity to 0. This appears to only happen when the item has more than one stock line available 🫠 
Seems like pretty unlikely use case, and I think any fix would be yet another hack. Recommending we leave this one for now and consider the case when we clean up prescriptions properly?
1.
2.
**Tests Pass**
> 7480 prescription breadcrumb shows uuid on new item

- client/packages/android/app/build.gradle
Fixes #7496 
Ensures when a new version of the app is installed, the existing app is replaced, regardless of the build type. 
To achieve this, I removed the applicationIdSuffix from the arm64 and universal build flavors. This ensures that all app versions use the same applicationId as defined in the defaultConfig of the build.gradle file
When installing an apk on a device, the applicationId determines if the app is 'new' or not. If the applicationId matches exactly, the app will update. If the applicationId does not match exactly, a new version will be installed. As the versions had different suffixes, android could have each of these apps installed simultaneously
Apks with the same version number eg v2.7.0-RC7-arm64 and v2.7.0-RC7-universal can overwrite each other, however as standard …
> Prevent simultaneous installs by removing application id suffix

- client/packages/system/src/Vaccination/Components/useConfirmNoStockLineSelected.ts
- client/packages/system/src/Vaccination/api/useVaccination.ts
- server/service/src/programs/patient/README.md
Fixes #7501
Strips the update vaccination payload if you are editing a given vaccination from other stores. Save now works (API call is not trying to change more than it is permitted to).
I think this raises a bit of a design question - @andreievg would be keen to jam on this at some point...
We've designed our backend update mutations to support partial patches, but our frontend tends to send entire payloads. In this case this caused an error - frontend expected backend to only use the relevant fields, backend expected frontend only to send the permitted fields.
Nullable update also adds complexity if we actually always send the full payload. Useful for some kinds of records, e.g. when editing subset of values from the toolbar, and useful if we expect API to have other consumers than our …
> 7501 cant edit vaccine given at other store

- server/repository/src/migrations/v2_00_00/mod.rs
- server/repository/src/migrations/v2_00_00/remove_changelog_triggers.rs
Background. Sites that have been updated to version 1.7 were affected by a bug in SQLite that caused data corruption. 
This is most obviously seen when trying to upgrade past 1.7 as during the upgrade database triggers caused the change log to be updated for all existing invoices, this means that the system tries to re-sync records that are no longer valid.
Fixes #7506
Technically this isn't a real fix for that database corruption errors, however I think it should allow the upgrade to continue ok. It works by removing the database triggers on the invoice_line (and other tables) this means the updates to these tables don't get changelog records and are only synced to central server when they're actually updated by users.
It's safe to remove the triggers earlier as we know they're upgrading …
> Remove db triggers in version 2.0 instead of version 2.2

- server/repository/src/migrations/v2_00_00/remove_changelog_triggers.rs
- server/service/src/sync/translations/special/name_merge.rs
Fixes #7531 
There was conflict when trying to remove a postgres function. I resolved conflict by removing a trigger that relies on it, and then had other migration problem because removed postgres functions were used elsewhere, so just removed the removal (triggers are still removed though, and function is removed in future migration, as those were just copied to earlier migration to fix a separate issue)
1.
2.
**Tests Pass**
> 7531 fix borken postgres tests in 2.6.4

- server/service/src/invoice/prescription/update/generate.rs
- server/service/src/invoice/prescription/update/mod.rs
Fixes #7530 
Allow saving prescriptions with line items that have zero issued quantity. Previously, `update_prescription` removed any line items with a `number_of_packs` of zero. This change removes that logic to permit saving such prescriptions.
There's a bit of a gap of what I know about prescriptions. From what I conducted it is safe to remove the logic that prunes line items with zero issued quantity. Please let me know otherwise.
1.
2.
**Tests Pass**
> 7530 save prescription even when line items issued quantity zero

- server/repository/src/migrations/v2_07_00/remove_encounter_clinician_constraint.rs
Fixes postgres migration for removing `encounter_clinician_link_id_fkey` in postgres
Fixes SQL 
Changes the migration fragment 2
Now it should never fail as it uses the `IF EXISTS` command. I think that's ok though
1.
2.
**Tests Pass**
> Fixes postgres migration for removing `encounter_clinician_link_id_fkey` in postgres

- client/packages/common/src/intl/utils/DateUtils.test.ts
Sorry, no issue here, just a super-quick fix so the front-end tests don't fail. 
They're failing today because it's 1st May, and the DateUtils tests use the current date and there's discrepancies with month calculations as it ticks over to the new month.
Have changed the test to use Jest's Mock timers to set a fixed date as the current datetime, which makes the tests stable and not dependent on the current date.
> Fix DateUtils tests

- client/packages/common/src/types/schema.ts
- client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useDraftStocktakeLines.ts
- client/packages/inventory/src/Stocktake/api/hooks/line/useStocktakeLines.ts
- client/packages/inventory/src/Stocktake/api/hooks/line/useStocktakeRows.ts
- server/graphql/stocktake_line/src/stocktake_line_queries.rs
- server/repository/src/db_diesel/stocktake_line.rs
Fixes #7511 
The problem was that if some of the stock_lines for the item you are editing are on a separate page in the API response, the UI doesn't know that the stock line has been created and there for 
This fix feels a bit messy, I feel like an upsert from the backend might be a nice solution but it's a big change.
A slightly nicer solution would be to add an item_id filter to stocktake lines rather than relying on the existing itemNameOrCode filter.
Didn't do either of those right now to keep the fix small.
See testing steps in issue to re-create...
1.
2.
**Tests Pass**
> 7511 Fix unable to save stocktake line for an item

- client/packages/common/src/types/schema.ts
- client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditForm.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditForm.tsx
- client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditForm.tsx
- client/packages/invoices/src/Returns/modals/SupplierReturn/ItemSelector.tsx
- client/packages/system/src/Item/Components/StockItemSearchInput/StockItemSearchInput.tsx
- client/packages/system/src/Item/api/api.ts
- client/packages/system/src/Item/api/hooks/useItemStockOnHand/useItemStockOnHand.tsx
- client/packages/system/src/Item/utils.ts
- server/graphql/general/src/queries/item.rs
- server/repository/src/db_diesel/item.rs
Fixes reopened #5537
Adds an `has_stock_on_hand` filter to item search, so we only get the relevant results from backend. Can then remove the problematic frontend filter, which doesn't map well to paginated autocomplete.
Took me a while to track down the issue, we thought it was a problem with autocomplete, but it was actually the relationship with item query. We were querying all visible items (paginated) and then filter on frontend for items with stock.
Issue was happening in the case of:
- There are lots of items visible to your store (let's say 5000)
- You only have stock on hand for a few of them (say 200 items)
- Supplier return modal gets items in pages of 100 items
- Of that initial set of 100 visible items, on average, only 4 would have stock on hand
- Front end filters those …
> 5537 supplier return item search autocomplete not scrolling

- client/packages/programs/src/JsonForms/common/components/Text.tsx
- client/packages/programs/src/JsonForms/common/hooks/useJSONFormsCustomError.ts
Fixes #7569
This was actually a worse problem than what was described in the issue -- there was an infinite re-render going on due to the customErrors triggering a useEffect that in turn updated customErrors (I think).
I've mitigated this as much as I can for now, but I think this whole JSON Forms area needs a significant re-factor as there's all kinds of anti-patterns going on in it (such as returning un-memoized JSX from a hook, which causes a re-mount of child components on re-render). I think we could make this a lot more robust and less bug-prone with a few days cleanup.
I'm still not 100% sure I've totally fixed the issue, as I can still re-create the occasional bit of weirdness around the `isDirty` state update and the error messaging, but not sure if that's just my hot reloading, …
> 7569 FIx JSON Form telephone field

- server/graphql/playground.html
Fix for the recently broken GraphQL playground, which we access on `http://localhost:8000/graphql`
Problem was that the version of the graphiql package wasn't being specified in the script tag, but the style sheet tag specified version (3.0.6). And so when the library was updated to V4 a few days ago, we now get a mismatch between the script JS and the styles. 
I've removed the version specifier completely -- I think it should be fine to always fetch the latest stable version. Is there any reason not to?
ALSO...
I've fixed something that's been annoying me for a while -- I've wrapped the Login form in proper `<form>` tags, so that we can now submit using the "Enter" key, using default form behaviour.
Some auto-formatting changes in here. I suggest reviewing with the "Hide whitespace …
> Fix GraphiQL playground

- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/ui/components/inputs/Switch/Switch.tsx
- client/packages/system/src/Vaccination/Components/SelectBatch.tsx
- client/packages/system/src/Vaccination/Components/SelectItemAndBatch.tsx
- client/packages/system/src/Vaccination/api/useVaccination.ts
- server/service/src/vaccination/insert/validate.rs
- server/service/src/vaccination/update/generate.rs
- server/service/src/vaccination/update/validate.rs
Part of [70](https://github.com/msupply-foundation/open-msupply-internal/issues/70)
There was a change to auto-select batch if there is only one, this caused the batch to be sent into the API call and the insert function only checks if there's a stock line before creating an invoice!
This PR sets the batch to 'null' if the user is choosing to not record a stock transaction.
https://github.com/user-attachments/assets/eb7c6dd5-6d82-40ff-bf40-83736d0ece9d
Didn't do this part of the issue: 
```
- outcome of the toggle is unclear (does it put back stock, does it remove stock, does it keep stock unchanged ?
- confusing UI : all text look the same, all text has the same toggle
```
Feels like that needs UX input, but if using the same style/font/component for both recording and reverting is …
> 70 the toggle 'record stock transaction for past vaccination' doesn't work when a stockline is ticked

- client/packages/host/src/CommandK.tsx
Fixes #7092
The string shown as a placeholder for the CMD+K search box was not being translated.
The property used was `placeholder` but should have been `defaultPlaceholder`
1.
2.
**Tests Pass**
> Update component property

- server/graphql/item_variant/src/mutations/upsert.rs
- server/repository/src/db_diesel/item_variant/item_variant.rs
- server/repository/src/db_diesel/item_variant/item_variant_row.rs
- server/repository/src/db_diesel/item_variant/packaging_variant.rs
- server/repository/src/migrations/v2_08_00/add_doses_columns_to_item_variant.rs
- server/repository/src/migrations/v2_08_00/mod.rs
- server/repository/src/mock/item_variant.rs
- server/service/src/item/item_variant/upsert.rs
- server/service/src/sync/test/test_data/item_variant.rs
Fixes #7604
- Migrations to add `doses_per_unit` and `vvm_type` to item variants table. 
- Allow for upserting of these fields
- Make sure sync is still sync'in 
1.
2.
**Tests Pass**
> 7604 add doses per unit & vvm type to item variant table

- client/packages/common/src/intl/utils/DateUtils.test.ts
- client/packages/system/src/Stock/Components/StockLineForm.tsx
Fixes #7605 fixes #7540
- Add fallback value for totalNumberOfPacks so that undefined value does not throw error
- Remove available packs input field
EDIT - after requested changes
Available packs field still available on stock detail view but not in new stockline modal
~~I haven't applied the fix to the available packs field -> it seems redundant to add code that will only get removed later. We should also remove the available packs field as requested here #7540 but not sure if that needs to go into 2.7.1. I don't see why not~~
1.
2.
**Tests Pass**
> 7605 Add fallback to handle undefined value - fix crash on backspace NewStocklineModal

- client/packages/common/src/intl/context/IntlContext.tsx
Fixes #7515 (hopefully)
Our translation cache was set to update when we publish a new version, but there was a catch.
It was only doing it for English. If someone had already cached their french version the update might not apply until the cache is cleared or they wait 7 days!
I've also added the language version to they query string, which should help with caching on the backend if we want to turn that on too for remote clients (which I think might be a good idea)
1.
2.
**Tests Pass**
> Fix french translations not refreshing

- client/packages/common/src/intl/utils/DateUtils.ts
Fixes #7663 
Shows 'years' to age with label as opposed to just number.
Previously would only append 'month' or 'weeks' clarifier when age was less than 1.
Implements this change throughout the codebase where we use this function for consistency (not just in vaccine card.
Notably also makes this change in Patient Summary - but I think makes sense to have this here also.
**Tests Pass**
> 7663 show years for display age utils

- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/intl/locales/tet/common.json
- client/packages/requisitions/src/RnRForms/DetailView/ContentArea.tsx
- client/packages/requisitions/src/RnRForms/DetailView/DetailView.tsx
- client/packages/requisitions/src/RnRForms/DetailView/Footer.tsx
- client/packages/requisitions/src/RnRForms/DetailView/RnRFormLine.tsx
- client/packages/requisitions/src/RnRForms/DetailView/Search.tsx
- client/packages/requisitions/src/RnRForms/api/hooks/useRnRForm.ts
- client/packages/requisitions/src/RnRForms/api/hooks/useRnRFormContext.ts
Fixes #7608
Carry over issue: https://github.com/msupply-foundation/open-msupply/issues/7635
* Remove confirm column
* Remove strength column
* Since confirm column is removed, error needs to be shown somehow, when finalised, there is an indication that there is an error and we navigate to that line
* Search changed slightly, for performance, and since we need to scroll to the list in other areas
* We now save only the lines that have changed and don't have error (there is a carry over for error handling, and other things in this issue)
Confirm should not exist in RnR form, strength should not exist in RnR form. When there are errors you should be taken to the error when finalising.
1.
2.
**Issue …
> 7608 Remove confirm, strength and navigate to error when finalising

- client/packages/requisitions/src/RnRForms/DetailView/RnRFormLine.tsx
- client/packages/requisitions/src/RnRForms/DetailView/Search.tsx
- client/packages/requisitions/src/RnRForms/api/hooks/useRnRFormContext.ts
- client/packages/requisitions/src/RnRForms/utils.ts
Fixes #7636 
* Do starts with for search (restrict to max 10 found lines for highlighting)
* Make adjustments numeric inputs  (see issue)
RnR form search should be by 'starts with' of item code or name, adjustments input is numeric, resulting with easy skip/edit lines
1.
2.
**Tests Pass**
> 7363 RnR From demo related, search by starts with make adjustment numeric input

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/translation-context-split-request.md
Adds a template for translators to use to raise requests to split up translation keys into more for different contexts, so that they may have different strings to accommodate gendering and pluralisation of things in different languages a bit better
Tangentially, we probably need a more advanced system for complicated plurals.
> Add Translation Context Split Request

- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/types/schema.ts
- client/packages/system/src/Item/DetailView/DetailView.tsx
- client/packages/system/src/Item/DetailView/Tabs/ItemVariants/ItemVariantModal.tsx
- client/packages/system/src/Item/DetailView/Tabs/ItemVariants/ItemVariantsTab.tsx
- client/packages/system/src/Item/api/hooks/useItemVariant/useItemVariant.ts
- client/packages/system/src/Item/api/operations.generated.ts
- client/packages/system/src/Item/api/operations.graphql
- client/packages/system/src/Name/Components/ManufacturerSearchInput/ManufacturerSearchInput.tsx
- client/packages/system/src/Name/utils.ts
- server/graphql/core/src/simple_generic_errors.rs
- server/graphql/item_variant/src/mutations/upsert.rs
- server/graphql/types/src/types/item_variant.rs
- server/service/src/item/item_variant/test/mod.rs
- server/service/src/item/item_variant/upsert.rs
Fixes #7606
- Adds `doses_per_unit` and `vvm_type` to the `item_variant` table and sync.
- Allows these two columns to be upserted for vaccine items
- Update item variant UI to display these two columns for editing and viewing 
- Have also updated manufacturer and cold storage type to allow these inputs to be cleared
1.
2.
**Tests Pass**
> 7606 add doses per unit & vvm type to central server UI

- server/graphql/playground.html
Lol, I said when I [fixed this last week](https://github.com/msupply-foundation/open-msupply/pull/7618):
> I've removed the version specifier completely -- I think it should be fine to always fetch the latest stable version. Is there any reason not to?
Well, they proved me wrong and went and broke it again with v4.0.3 -- now the Explorer panel doesn't scroll!
So I've just fixed the version to 4.0.2 for now -- I guess we should test each version before upgrading rather than assuming new releases are solid.
> Fix GraphQL playground (Again!)

- server/repository/src/migrations/mod.rs
Fixes #
This is modelled off @noel-yeldos fix for views in his PR https://github.com/msupply-foundation/open-msupply/pull/7654/commits/2299f44b3516206b9d146b6950bf173916be3924
Since this is needed for https://github.com/msupply-foundation/open-msupply/pull/7718 I've split this out into it's own PR.
I've tested with 7718 and postgres and the tests all pass, so I think it's good.
I've added a check for if the views have been droped before re-creating.
If we haven't dropped any, we shouldn't need to recreate, and there's a warning message now too if the don't run view logic triggers we'll have something to trace back on.
1.
2.
**Tests Pass**
> Fix rebuilding views so it doesn't run on test cases

- client/packages/requisitions/src/RequestRequisition/api/hooks/utils/useAddFromMasterList.ts
Fixes #7749
Fixes the issue where we have to refresh the page after clicking on `Add from Master list` button. Invalidates the keys `onSuccess`
1.
2.
**Tests Pass**
> 7749 add from master list refresh

- client/packages/invoices/src/Prescriptions/LineEditView/columns.ts
- client/packages/system/src/Stock/ListView/ListView.tsx
Fixes #7676 
Adjust expiry date column so that values are not truncated
- Increase expiry date field width in prescription line edit form
- Increase expiry date field width in stock list view
`Stock List View - desktop browser`
`Prescription Line Edit - desktop browser`
`Stock List View - tablet portrait`
`Stock List View - tablet landscape`
`Prescription Line edit - tablet landscape`
`Prescription Line edit - tablet portrait`
I don't know if this is the most elegant solution as increasing width of the column makes it look a bit disjointed in the browser because of the extra space to the left of the expiry date values. Not sure if we need to adjust based on device type. Impact is low so not sure if worth addressing.
`View Stock`
`Prescription`
1.
2.
The PR Reviewer(s) should fill out this …
> 7676 fix expiry date column display

- server/graphql/playground.html
Looks like a mismatch between the GraphiQL version and the explorer plugin (which was updated 2 days ago).
I've fixed the version for both the main package and the exporer plugin (previously on did the main package), which should remain stable now.
Launch server, go to `http://localhost:8000/graphql` and check that it all works correctly
> Fix GraphiQL (again!)

- client/packages/common/src/ui/layout/tables/columns/types.ts
- client/packages/common/src/ui/layout/tables/components/Cells/TextInputCell/TextInputCell.tsx
- client/packages/programs/src/VaccineCourseEditModal/VaccineCourseEditModal.tsx
Fixes #7577
Adds custom debounce prop to text input cell so can manually change.
In this case (as not connected to API calls), have set to 0.
Wondered about making it 0 for all textinputCell, but wasn't sure if somewhere it was connected to an API call which might cause some issues, so just adding a custom prop.
**Tests Pass**
> Update text input debounce to more moderate value

- client/packages/coldchain/src/common/utils.ts
- client/packages/common/src/intl/currency/currency.ts
- client/packages/common/src/intl/number/IntlNumber.ts
Fixes #7735
* Creates `intlNumberFormat` method that replaces Intl.NumberFormat
* Adds tet override for number format to match english
From related issues:
I haven't been able to set my regional setting (this is not timezone setting), but if you are able to then set to Indonesia, you will see in ledger and other places that thousand's are separated by a dot. Similar example has been tested on Indonesia regional setting.
Need to also quickly check that number display still works correctly, try a french language
1.
2.
**Tests Pass**
> Override tet with en in Intl.NumberFormat

- client/packages/common/src/intl/locales/tet/common.json
- client/packages/requisitions/src/RnRForms/DetailView/RnRFormLine.tsx
- server/graphql/general/src/lib.rs
Fixes #7739 
Fixes: #7748 
Add translation and RnR form number formatting
Check tetum translation for RnR form consumption is 'Distribution'
Numbers are formatted with correct thousands separator, even for non editable columns in RnR form (try Tetum, comma, French, space, Portugese, dot), you can set up quickly [with this data file: ](https://drive.google.com/drive/u/1/folders/1N-haFv9ixg-z3crQViMDP4BW8ukF4rWq)
1.
2.
**Tests Pass**
> Add translation number formatting in RnR form

- client/packages/common/src/hooks/index.ts
- client/packages/common/src/hooks/useSimplifiedTabletUI/index.ts
- client/packages/common/src/hooks/useSimplifiedTabletUI/useSimplifiedTabletUI.ts
- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/types/schema.ts
- client/packages/common/src/ui/layout/tables/hooks/useColumnDisplayState.ts
- server/graphql/preference/src/upsert.rs
- server/graphql/types/src/types/preferences.rs
- server/service/src/preference/mod.rs
- server/service/src/preference/preferences/mod.rs
- server/service/src/preference/preferences/use_simplified_mobile_ui.rs
- server/service/src/preference/types.rs
- server/service/src/preference/upsert.rs
Fixes #7388.
Implemented with front-end hook as suggested [in this comment](https://github.com/msupply-foundation/open-msupply/issues/7388#issuecomment-2889279437).
All checks for whether to display UI with "simplifed" view should use this hook.
- Implemented `useSimplifiedMobileUi` preference on server
- Add "useSimplifiedTabletUI` hook on front-end which uses this preference plus two other conditions (see code)
Haven't actually implemented this anywhere yet, but it will be used in #7397 which will be available soo.
For now, I've just added a `console.log()` to display the value on any Table.
See additional comments in code review
**Tests Pass**
> #7388 Store pref for simplifed mobile UI

- client/packages/inventory/src/Stocktake/DetailView/ReduceLinesToZeroModal.tsx
- client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx
- client/packages/invoices/src/Returns/modals/ReturnReasonsTable.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEdit.tsx
- client/packages/system/src/ReasonOption/Components/ReasonOptionsSearchInput.tsx
- client/packages/system/src/Stock/Components/InventoryAdjustment/InventoryAdjustmentModal.tsx
- client/packages/system/src/Stock/Components/NewStockLineModal.tsx
Partly Fixes #7512 
- Move `useReasonOptions()` hook from `ReasonOptionsSearchInput` to parent components that are rendering `ReasonOptionsSearchInput` 
- Pass fetched data as props to `ReasonOptionsSearchInput`
Now data is fetched only once and not every time `ReasonOptionsSearchInput` is rendered
Note that fetching of item variants has not been fixed in this PR and will be fixed in another PR by @roxy-dao 
1.
2.
**Tests Pass**
> 7512 Prevent reasonOptions firing on scroll

- client/packages/plugins/api/index.ts
Fixes #7374 
Very tiny omission that should have gone into https://github.com/msupply-foundation/open-msupply/pull/7798 -- didn't notice the type error until trying to compile the plugin builder.
Have confirmed that the "install-plugin-bundle" and "generate-and-install-plugin-bundle" now work with front-end plugin bundles.
**Tests Pass**
> Fix plugin type error

- server/service/src/invoice_line/stock_in_line/update/generate.rs
Fixes #7894 
When updating the campaign on an Inbound Shipment Item, Stock Line's campaign doesn't update.
1.
2.
**Tests Pass**
> 7894 update stock line campaign id when inbound shipment updates

- client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
Fixes #7883
In inbound shipments, when `Packs received` is 0/cleared/nulled this will also update `Units received` and `Doses received` (if pref is on) to 0
Issue is specific to the `Manage in Doses pref` and vaccine items - however this bug was not specific to these and applied to all items. 
https://github.com/user-attachments/assets/b718abe9-7a60-4088-841a-bf02dd9e5537
1.
2.
**Tests Pass**
> null packs received updates units

- client/packages/system/src/Stock/api/hooks/useStockLine.ts
Fixes #7899
1.
2.
**Tests Pass**
> 7899 error when saving new stock without a campaign specified

- client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx
Fixes #7628 
Replace the Item Variant dropdown with the new popover Item Variant component. 
Use the `manageVaccinesInDoses` pref to render the doses column in the popover if the pref is on
If there are variants and the item is a vaccine (manageVaccinesInDoses is on):
If there are variants and the item is not a vaccine:
If there are no variants:
1.
2.
**Tests Pass**
> 7628 Set Item Variant on Stocktake

- client/packages/system/src/Stock/Components/StockLineForm.tsx
- client/packages/system/src/Stock/DetailView/DetailView.tsx
Fixes #7915 
- renders VVM status field based on pref in stocklineForm
- renders Status history tab based on pref
`Vaccine with VVM pref OFF`
`Vaccine with VVM pref ON`
The issue had also mentioned that the VVM status column was persisting in Outbound Line edit when the pref was OFF. I wasn't able to replicate that. Behaves as expected. 
`Pref ON`
`Pref OFF`
1.
2.
**Tests Pass**
> 7915 vvm status field showing incorrectly stock detail view

- server/repository/src/db_diesel/invoice_row.rs
- server/repository/src/db_diesel/ledger.rs
- server/service/src/ledger.rs
Fixes #7868 
Refactors item_ledger to prevent double counting of ledger items in cases where they occur at the same datetime.
Preserve multiple id query logic without mapping to keep functionality for reports which use this query
Add tests to ensure logic is stable
Note that the ledger balance is always calculated based on dateTime, which leads to strange displaying results if we sort by datetime in the front end in a reverse order from how we calculate the balance.
You can see this when you change the datetime order from ascending to descending in the item ledger tab of items.
Some ways the ledgers are out of order.
Unsure quite how to handle this, but I am thinking this is still better than the alternative of prematurely summing of total values.
The PR Reviewer(s) should fill out this …
> 7868 add running balance total for ledger queries

- server/service/src/sync/test/test_data/invoice.rs
- server/service/src/sync/translations/invoice.rs
Fixes #7765 
When migrating og data for si that has new status we should be translating status to shipped, including settings shipped datetime to created datetime
Added a translation test, which was a bit cumbersome, I think because of number of fields that need to be specified, so I used existing data, which still required a lot of work (but in the process i noticed the shipped date needs to be updated)
[This datafile](https://drive.google.com/drive/u/1/folders/1R-Z6CwJ7s099jYtne_Nta7I7Y906KMAy) has a transfer create in og, ready to be synced on initialisation. (user1 -> user1 for OG related stuff, like registering etc.. test -> pass for site initialisation test -> pass for omSupply user). You will need to check inbound shipment in trasnfertest store
Otherwise, create si in new status as …
> New status for og migrated inbound shipment to be considered as shipped

- server/cli/src/cli.rs
- server/cli/src/lib.rs
- server/cli/src/load_test.rs
Part of #7755 
Sets up basic CLI action and creates the sites on OG
There were utilities in integration tests, but I didn't think it was appropriate to turn on the integration tests flag to make them compile in a build. Though, I could extract them out into a common area...
I could also take this another direction and make a whole separate CLI tool, though that doesn't solve the code reuse mentioned above.
**Tests Pass**
> 7755 creating sites on OG

- client/packages/common/src/ui/components/loading/BasicSpinner/BasicSpinner.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditTable.tsx
- client/packages/invoices/src/Prescriptions/LineEditView/AutoAllocatePrescribedQuantityField.tsx
- client/packages/invoices/src/Prescriptions/LineEditView/LineEditView.tsx
- client/packages/invoices/src/Prescriptions/LineEditView/NavBar.tsx
- client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEdit.tsx
- client/packages/invoices/src/Prescriptions/api/hooks/useSavePrescriptionItemLineData.ts
- client/packages/invoices/src/StockOut/useAllocationContext.ts
Fixes #7996
Set prescribed quan in doses:
Switch to units - quantity adjusts accordingly:
Note that if you have item variants, when you switch to unit view, prescribed and issued may vary (as issued just adds up actual allocated units, prescribed changes dose to unit quantity based on default doses per unit).
I'm comfortable calling this an edge case, I think pretty low likelihood, and values are correct (so not really a bug anyway). Especially if variants may be changed. Just wanted to capture
1.
2.
**Tests Pass**
> 7996 change prescribed quan between doses and units

- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/intl/locales/fr/common.json
- client/packages/host/src/Admin/ConfigurationSettings.tsx
- client/packages/host/src/api/hooks/settings/namePropertyData.ts
Fixes #7590
Gaps store properties can now be initalised and re-initialised.
The language selected is based on your currently selected language.
Note: re-initialising might not work correctly depending on what changes have been done, it will upsert the records so won't remove anything existing.It also won't remap any previously entered values if you change languages
https://docs.google.com/document/d/1fWmzx57uwq4vopfWMhYA-PYKHgQqsfpAjgiBX-lNUNU/edit?tab=t.0
1.
2.
**Tests Pass**
> 7590 Translate GAPS Store properties into French

- server/service/src/stocktake_line/insert/mod.rs
- server/service/src/stocktake_line/update/mod.rs
Fixes #7951 
It should update Stock lines donor when Stocktakes lines donor gets added or updated
1.
2.
**Tests Pass**
> 7951 update stock line donor on stock take insert or update

- server/repository/src/db_diesel/demographic_row.rs
- server/repository/src/migrations/v2_08_00/add_population_percentage_to_demographic.rs
- server/repository/src/migrations/v2_08_00/mod.rs
- server/repository/src/migrations/views/mod.rs
- server/repository/src/mock/demographic.rs
- server/service/src/demographic/insert_demographic_indicator.rs
- server/service/src/demographic/update_demographic_indicator.rs
- server/service/src/sync/test/test_data/demographic.rs
Fixes #7992
- Migration to add "population_percentage" to "demographic" table
- Funcionality to automatically update that field whenever a "demographic_indicator" is added/edited
- Change "vaccination_course" view to use percentage from this field rather the demographic_indicator
Not much for QA to test here, other than confirming that the forecasting plugin works on a non-central system
Devs, check database is modified as expected
**Tests Pass**
> 7992 Add population percentage to demographic table

- client/packages/requisitions/src/RequestRequisition/api/hooks/utils/useAddFromMasterList.ts
Fixes #7926 
Fixes the issue where we have to refresh the page after clicking on `Add from Master list` button. Invalidates the keys `onSuccess`
1.
2.
**Tests Pass**
> 7926 add from master list refresh

- client/packages/common/src/intl/locales/en/common.json
- client/packages/requisitions/src/RequestRequisition/DetailView/ContentArea.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/DetailView.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/ModalContentPanels.ts
- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEditModal.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestedSelection/RequestedSelection.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/hooks.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/columns.ts
- client/packages/requisitions/src/RequestRequisition/api/hooks/line/useRequestLines.ts
- client/packages/requisitions/src/ResponseRequisition/DetailView/ContentArea.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/DetailView.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ContentLayout.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseEditModal.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEdit.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/SuppliedSelection/SupplySelection.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/hooks.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseStats/RequestStoreStats.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseStats/ResponseStoreStats.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/columns.ts
- client/packages/requisitions/src/ResponseRequisition/api/hooks/line/useResponseLines.ts
- client/packages/requisitions/src/common/ModalContentLayout.tsx
- client/packages/requisitions/src/common/utils.test.ts
- client/packages/requisitions/src/common/utils.ts
- client/packages/requisitions/src/utils.ts
- server/service/src/sync/test/test_data/store_preference.rs
- server/service/src/sync/translations/store_preference.rs
Fixes #7343
Sorry... the PR got bloated again ;-; pls forgive 🙇🏻‍♀️ 
- Lots of stylin' changes to try get components to align with each other and to get components to change dynamically with size... Note 1 below tho...
- Add loading spinner to Requisition and Internal Order modals
- Show placeholder lines in Requisition
- Added `doses per unit` row for Internal Order and Requisitions which will only show up if the user has the `Manage vaccines in doses` pref on and the item is a vaccine item
- Display helper text underneath components to display the value in doses based on the `item.doses` value
- Fix bug with newly created lines not correctly setting `isCreated` because it's still using the previous draft...
- Internal Order requested value should update depending on the packs / units …
> 7343 dose management display doses in internal order & requisition

- client/packages/common/src/intl/locales/en/common.json
- client/packages/system/src/ActivityLog/Components/ListView.tsx
Fixes #7752
Display nothing here message when no log entries to display
Changes needed for consistency.
1.
2.
**Tests Pass**
> #7752 Display nothing here message when no log entries to display 

- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEditModal.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestedSelection/RequestedSelection.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ContentLayout.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseEditModal.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEdit.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/SuppliedSelection/SupplySelection.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseStats/ResponseStoreStats.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseStats/utils.tsx
- client/packages/requisitions/src/common/ModalContentLayout.tsx
- client/packages/requisitions/src/common/utils.ts
Fixes #8052
- Full screen modal `X` button to cancel functions like the cancel button
- Dose number formatting for readability
1.
2.
**Tests Pass**
> 8052 requisitions full screen modal x not behaving like cancel

- client/packages/invoices/src/OutboundShipment/DetailView/Toolbar.tsx
Fixes #8059
It turns out that when switching the receiving store for an outbound shipment, the whole invoice is being deleted and a new one created. So rather than change that behaviour, I've just changed the front-end to re-direct to the new invoice ID after the update.
**Tests Pass**
> #8059 Fix errors when changing customer in Outbound Shipment

- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestedSelection/RequestedSelection.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ContentLayout.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/SuppliedSelection/SupplySelection.tsx
- client/packages/requisitions/src/common/ModalContentLayout.tsx
Fixes #8052
Hide doses for 0 units to save on real estate
1.
2.
**Tests Pass**
> Hide doses if 0 units

- client/packages/common/src/types/schema.ts
- client/packages/system/src/Item/api/operations.generated.ts
- client/packages/system/src/Item/api/operations.graphql
- server/graphql/general/src/queries/cold_storage_type.rs
- server/repository/src/db_diesel/cold_storage_type.rs
Fixes #6167
Reorder cold storage types to appear in desc order (based on minimum temperature)
The issue had only specified item variant cold storage type selector but I've made api return the list in descending so it will appear that way in all places that cold storage type selector is used. Seems like that's ok to me but happy to be told otherwise. 
Ensure you have cold storage location types set up in OG - Item -> show location types:
- your store will need to be on OG server to be able to edit location types
- I just moved a random store to OG server -> logged in as that store to og -> added the types -> and then moved store back to OMS server
1.
2.
**Tests Pass**
> #6167 Reorder cold storage types to appear in desc order

- client/packages/common/src/types/schema.ts
- server/graphql/types/src/types/permissions.rs
- server/repository/src/db_diesel/user_permission_row.rs
- server/repository/src/migrations/v2_09_00/add_mutate_clinician_permission.rs
- server/repository/src/migrations/v2_09_00/mod.rs
- server/service/src/auth.rs
- server/service/src/login.rs
Fixes #8116
Maps OG permission `AddEditPrescribers` to OMS permission `MutateClinician`
Not used as of yet, but shows in the schema under `UserPermission`, and appears in the graphql `permissions` object when logging in or syncing
1.
2.
**Tests Pass**
> #8116 Sync clinician mutate permission to OMS

- server/service/src/sync/test/test_data/invoice_line.rs
- server/service/src/sync/test/test_data/stock_line.rs
- server/service/src/sync/translations/invoice_line.rs
- server/service/src/sync/translations/stock_line.rs
Fixes #8142 (for 2.8.1)
Same as https://github.com/msupply-foundation/open-msupply/pull/8150
but add empty string support for oms_fields too
1.
2.
**Tests Pass**
> 8142 stock line import issue

- client/packages/host/src/Admin/ConfigurationSettings.tsx
- client/packages/host/src/api/hooks/settings/namePropertyData.ts
- client/packages/host/src/api/hooks/settings/namePropertyKeys.ts
- client/packages/host/src/api/hooks/settings/useConfigureNameProperties.ts
Fix #8167
Made sure to include the correct keys for "forecasting", not just the single "population_served" key.
Also renamed "population" keys to "forecasting" keys, as it's a bit more precise.
```sql
DELETE FROM name_property;
DELETE FROM property;
```
**Tests Pass**
> #8167 Fix forecasting store properties initialisation

- client/packages/invoices/src/OutboundShipment/DetailView/Toolbar.tsx
Fix #8085
The error was caused by the "back" button attempting to go to the old invoice URL, which no longer exists. This fix prevents that by "replacing" the url in the history when navigating after changing customer. However, if you go "back" from the line edit modal now, you'll be taken to the list view, which is not ideal, but it's consistent with how it works in a normal detail view (when not changing customer).
It doesn't really make sense to go "back" from a modal like this, as the URL hasn't actually changed. I think, ultimately, it would be good to add a url parameter to the url when opening modals (e.g. `?editItem=<id>`), so that you *can* go "back", but that's a much larger change and needs further discussion/planning.
The behaviour now should be exactly the same as it is when …
> #8085 Fix error when going back after changing customer

- server/graphql/core/src/loader/purchase_order_line.rs
- server/graphql/purchase_order_line/src/purchase_order_line_queries.rs
- server/service/src/purchase_order_line/mod.rs
- server/service/src/purchase_order_line/query.rs
Fixes #8225 
It fixes #8225 by modifying the purchase order line loader.
There was a hardcoded empty string for store_id. The loader then filtered by store_id and as a result no purchase order line would be returned if it corresponded to a purchase order with a store_id that wasn't an empty.
This hardcoded empty string was replaced with 'None', and the store_id field was made into an optional type to allow this.
Credit to @fergie-nz for the fix and diagnosis!
And now it works!
1.
2.
**Tests Pass**
> 8225 queries for purchase order lines always return nothing

- client/packages/inventory/src/Stocktake/api/api.ts
Fixes #8260
It assumes the item's default packsize when creating new lines, if the user hasn't entered a packsize
A nicer fix might be to actually update the packsize as seen in the frontend when the counted packs is updated?
Just in case there's some additional logic added for packsizes in future?
1.
2.
**Tests Pass**
> Use Default packsize for new lines in stocktake if not entered

- server/graphql/types/src/types/stocktake_line.rs
Fixes #8169
StocktakeLine struct already returns Reason Options, so have refactored this to use that instead since it's better for performance and less complex.
Probably a good idea to implement this everywhere where we are already getting the data from an sql query instead of using a loader for the reasons above + avoids N+1~
1.
2.
**Tests Pass**
> Remove ReasonOptionLoader from stocktake_line #8169

- client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx
- client/packages/system/src/ReasonOption/Components/ReasonOptionsSearchInput.tsx
Fixes #8259
Update `useMemo` dependency array for `columnDefinitions` so that variable changes trigger update without having to click OK
https://github.com/user-attachments/assets/7c7208e8-e42c-4f20-a50e-0b3d12180b5c
Not sure if all the dependencies need to be added.
1.
2.
**Tests Pass**
> #8259 fix/ Adding a reason in stocktake not always possible until clicking on Ok

- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/Allocation.tsx
Fixes #8258
When creating an outbound shipment, if there's only one existing packsize in stock, default to allocating in that packsize
Feels like this maybe should be done in Allocation Context somewhere, however this limits this just to the Outbound shipment page.
1. Allocation docs
2.
**Tests Pass**
> Default to allocating in packs if there's only one packsize

- client/packages/common/src/ui/components/inputs/Autocomplete/Autocomplete.tsx
- client/packages/system/src/Clinician/ClinicianSearchInput.tsx
Fixes #8211
Can create a clinician from within the clinicians search input
Is always visible - regardless of filtering
I first created this as a specific component, and then pulled out the logic to the common autocomplete - can see in commit history.
To add this functionality to another search component, the following will be needed:
- define the CreateOption object with an id, label, and _isAddOption flag
- define a handler for what needs to happen when this option is selected (open modal)
- pass both of these to the Autocomplete component
- conditions can be set eg createOption only to be passed through if there are no results from filtering
- popover open/closed state may need to be managed here as well
Changes to a common component - it should be set up so as to not interfere with any …
> 8211 Create Clinician From Within Search

- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/types/schema.ts
- client/packages/system/src/Clinician/CreateClinicianForm.tsx
- client/packages/system/src/Clinician/ListView/columns.ts
- client/packages/system/src/Clinician/useCreateClinician.ts
- server/graphql/clinician/src/mutations/insert.rs
- server/service/src/clinician/insert/generate.rs
- server/service/src/clinician/insert/mod.rs
- server/service/src/clinician/insert/validate.rs
Fixes #8292
Allow users to input mobile when adding a clinician and show this in the list view. Have restricted mobile to numbers only..
1.
2.
**Tests Pass**
> 8292 add clinician mobile number

- client/packages/invoices/src/Prescriptions/LineEditView/columns.tsx
Fixes #8280 
Updated the max calculation for `NumberInputCell` to use `availablePacks` * `packSize`.
1.
2.
**Tests Pass**
> 8280 prescriptions cant input correct amount of units

- client/packages/invoices/src/StockOut/Components/AutoAllocateIssueField.tsx
Fixes #8299 
Updates debounce time from 500 to 1000 (1 sec) after a user types. 
Took the time to think about how long our users actually take to type something. 1 second seems after a user type seems to be enough, but some might be new to typing and can be slower with typing. 
Anyways thought could start off with bumping debounce to 1 sec and wait for any user to mention anything about it
1.
2.
**Tests Pass**
> 8299 distributed quantity field gets automatically replaced by minimum pack size before the user finishes typing

- client/packages/requisitions/src/RnRForms/DetailView/RnRFormLine.tsx
- client/packages/requisitions/src/RnRForms/DetailView/helpers.test.ts
- client/packages/requisitions/src/RnRForms/DetailView/helpers.ts
- client/packages/requisitions/src/RnRForms/api/hooks/useRnRFormContext.ts
- package.json
- server/Cargo.lock
- server/graphql/programs/Cargo.toml
- server/graphql/programs/src/mutations/rnr_form/finalise.rs
- server/graphql/programs/src/mutations/rnr_form/update.rs
- server/service/src/rnr_form/finalise.rs
- server/service/src/rnr_form/tests/finalise.rs
- server/service/src/rnr_form/tests/update.rs
- server/service/src/rnr_form/update.rs
Fixes https://github.com/msupply-foundation/open-msupply-internal/issues/89
- Prevents finalisation of R&R form when initial or final balance is negative
- Fix frontend error mapping - was only checking draft/touched lines, but should validate all lines
1.
2.
**Tests Pass**
> 89 internal: negative R&R balances

- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEditModal.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestedSelection/RequestedSelection.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseEditModal.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEdit.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/SuppliedSelection/SupplySelection.tsx
Fixes #8235
Adds a bool to disable the buttons while debounce on child settles.
We really need a better way to handle disabling things if debounce hasn't settled... I'm sure this happens in a lot of places but less obvious than Internal Order / Requisitions... It's fine if you're typing slow but... if you are typing fast gg
1.
2.
**Tests Pass**
> 8235 Internal order Ok & Next does not add item

- server/repository/src/migrations/v2_08_03/invoice_received_status.rs
Fixes #4890
A stray `set` statement meant that statuses could go backwards on an upgrade.
1.
2.
**Tests Pass**
> Fix migration

- client/packages/system/src/Stock/api/hooks/useStockList.ts
Fixes #7705
Show stock regardless of if masterList exists on store.
Note - this query is only used on the stock ListView component - so restrictions on adding stock on a masterList not visible on the store remain
**Tests Pass**
> Remove filter that masterList exists on store

- client/packages/system/src/Stock/Components/InventoryAdjustment/InventoryAdjustmentModal.tsx
Fixes #7721 
If stock line is on hold, disabled the Ok button from being click for InventoryAdjustment. Also added a new field `On Hold` to help indicate to the user that a stock line is on hold
1.
2.
**Tests Pass**
> 7721 inform user that batch is on hold when making inventory adjustment

- client/packages/system/src/Name/ListView/Stores/StoreEditModal.tsx
Fixes #8201
Switched properties to be the first tab selected for the Store Edit Modal
1.
2.
**Tests Pass**
> 8201 switch store preference and properties tab

- client/packages/system/src/Program/ProgramSearchInput.tsx
Fixes #7084 
Update the Program Input to use the default background colour instead of white
This component is used in Prescriptions - `New Prescription Modal` and `Detail View - Toolbar` - default background is needed in both of these places
There is another ProgramSearchInput used elsewhere which didn't need any colour changes
Checked through the codebase and don't see other cases where a white background is being used but not needed
Other mentioned ones in PR - clinicians and reasons - are already fixed
1.
2.
**Tests Pass**
> 7084 Program input background colour consistency

- client/packages/system/src/Name/ListView/Stores/StoreEditModal.tsx
Fixes #7843
Don't show cancel button if the user is in the preference tab
1. Screenshots of the preference tab?
2.
**Tests Pass**
> 7843 In Store Preferences clicking the Cancel button doesn't prevent your change to be saved

- server/service/src/invoice_line/stock_in_line/insert/mod.rs
- server/service/src/invoice_line/stock_in_line/insert/validate.rs
Fixes #8403
Allows newly added stocklines to go inserted with invisible donors.
Very edge case situation but is affecting a client with migrations so was considered worth fixing for this usecase.
I'll raise a follow up issue to what should happen when donors are made invisible.
I haven't changed the `update.rs` logic in the same way. The justification for now is that its a nullable update, so it should only be set if they change the donor and then they should only see valid donors? But maybe I should change it as well to be consistent?
See bug issue for testing steps
1.
2.
**Tests Pass**
> 8403 donor not visible

- server/Cargo.lock
- server/graphql/Cargo.toml
- server/graphql/lib.rs
- server/graphql/logger.rs
- server/server/Cargo.toml
- server/server/src/middleware/mod.rs
Another part of #8137 
Was raised in discussion, that the HTTP logs are noisy, and not particularly helpful.
Moves them to `DEBUG` log level, and strips some of the user agent etc. noise from the format:
Our request logs are especially unhelpful, because the majority of our requests are graphql, so always to `/graphql`, and even when graphql returns an error, its still HTTP 200 status. We don't have access to the request/response body in the logger, just the headers, so this is about all the info we can show...
So logging the requests at all only really adds value for the REST requests we have. Maybe its helpful to see that requests are being received/responded to?
I'm wondering about something [like this](https://docs.rs/actix-web/latest/actix_web/middleware/struct.Logger.html#method.cust …
> 8137 Move HTTP logs to debug level, add graphql logs

- server/graphql/invoice_line/src/invoice_line_queries.rs
- server/repository/src/db_diesel/invoice_line.rs
- server/service/src/processors/transfer/invoice/create_inbound_invoice.rs
Fixes #8407
Need https://github.com/msupply-foundation/open-msupply-reports/pull/231. Allow filtering of program id on invoice lines & transferring the outbound shipment's program id to inbound shipments
```gql
query {
invoiceLines(storeId: "your-store-id", filter: { programId: { equalTo: "your-program-id" }}) {
... on InvoiceLineConnector {
nodes {
invoiceId
}
}
}
}
```
1.
2.
**Tests Pass**
> 8407 exf78   civ   fiche d'inventaire des ppi   a master list filter is missing

- server/graphql/core/src/generic_filters.rs
- server/graphql/core/src/lib.rs
- server/graphql/general/src/queries/inventory_adjustment_reason.rs
- server/graphql/general/src/queries/return_reason.rs
- server/repository/src/db_diesel/activity_log.rs
- server/repository/src/db_diesel/document_registry.rs
- server/repository/src/db_diesel/filter_sort_pagination.rs
- server/repository/src/db_diesel/name_row.rs
- server/repository/src/diesel_macros.rs
- server/service/src/programs/patient/search.rs
- server/service/src/sync/mod.rs
Fixes #8432 
Adds a new filter option to allow not_equal_to_or_null
The problem with recently changes to allow central server to sync on behalf of remote sites was that it's own changes were being ignored as they were set to null.
Basically when we say not equal to something in SQL, null records are excluded.
`SELECT * FROM changelog WHERE source_site_id <> 1 ` 
`SELECT * FROM changelog WHERE source_site_id <> 1 or source_site_id is null`
I think we don't need to worry about effects on non-central sites as it doesn't use the same filter now.
However, could it cause an issue with Central server?
What about the edge case of first sync after upgrading. Does it know that it's a central server fast enough?
Rather than adding this to equal filter should we create something special for changelog …
> Add no_equal_to_or_null filter option & use in central server sync

- client/packages/common/src/ui/components/inputs/TextInput/BasicTextInput.tsx
- client/packages/common/src/ui/components/panels/SlidePanel/SlidePanel.tsx
- client/packages/common/src/ui/components/steppers/HorizontalStepper/HorizontalStepper.tsx
- client/packages/common/src/ui/components/steppers/WizardStepper/WizardStepper.tsx
- client/packages/common/src/ui/forms/Detail/InputWithLabelRow.tsx
- client/packages/programs/src/JsonForms/common/components/Text.tsx
- client/packages/system/src/Clinician/CreateClinicianForm.tsx
- client/packages/system/src/Patient/CreatePatientModal/DefaultCreatePatientUISchema.json
- client/packages/system/src/Patient/CreatePatientModal/PatientFormTab.tsx
Fixes #8420
Make overflow on child only and tried to make some more space in the create patient modal...
The patient creation can do with some UI / UX rework... only can see the first name 
1.
2.
**Tests Pass**
> 8420 on tablet when creating a new patient some fields go outside the modal when virtual keyboard is up

- client/packages/common/src/ui/components/buttons/standard/SplitButton.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/Footer/Footer.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/Footer/StatusChangeButton.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/Footer/useCreateShipment.ts
- client/packages/requisitions/src/utils.ts
Fixes #8345
- Move the `Create Shipment` button to be within split buttons
- Users will have to manually click arrow and click finalise button if they want to finalise
- Allow different icons for split buttons
https://github.com/user-attachments/assets/4b951d96-0daa-40f6-a1b7-58775651440e
1. Update the behaviour of the buttons in Requisition documentation
2.
**Tests Pass**
> 8345 make the confirm finalise button in requisitions smaller   users are complaining clicking it and making errors

- client/packages/programs/src/JsonForms/common/components/Select.tsx
- client/packages/programs/src/JsonForms/common/components/tests/Select.test.tsx
- client/packages/system/src/Patient/CreatePatientModal/DefaultCreatePatientUISchema.json
- client/packages/system/src/Patient/PatientView/DefaultPatientUISchema.json
Fixes #8335. Review this at the same time https://github.com/msupply-foundation/programschemas/pull/39
Amends the JSON `Select` component so that it can load options from preference instead of a hardcoded set of enums. Did it this way to keep compatibility and also cause we really not be needing that many custom components...
https://github.com/user-attachments/assets/87cd6ddc-ef8b-4055-91f2-f29442868eb0
1.
2.
**Tests Pass**
> 8335 json forms dynamic gender component

- client/packages/android/app/src/main/java/org/openmsupply/client/FileManager.java
- client/packages/android/app/src/main/java/org/openmsupply/client/MainActivity.java
- client/packages/android/app/src/main/java/org/openmsupply/client/NativeApi.java
- client/packages/common/src/hooks/useNativeClient/types.ts
- client/packages/common/src/utils/files/FileUtils.ts
Fixes #8453
Converts base64 encoded data back to binary before saving on android... so the excel files are valid & can be opened 🫠 
1.
2.
**Tests Pass**
> 8453 excel exports are invalid files on android

- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/intl/locales/es/common.json
- client/packages/common/src/intl/locales/fr/common.json
- client/packages/common/src/intl/locales/pt/common.json
- client/packages/common/src/ui/layout/tables/components/Header/Header.tsx
- client/packages/invoices/src/InboundShipment/DetailView/AddButton.tsx
- client/packages/purchase_orders/src/DetailView/AppBarButtons/AddFromMasterListButton.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/AppBarButtons/AddButton.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/AppBarButtons/AddFromMasterListButton.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/AppBarButtons/AddFromMasterListModal.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/AppBarButtons/AppBarButtons.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/OrderInfoSection.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/Toolbar/Toolbar.tsx
Fixes #8048 & #8035 & #8364
- For now have moved tooltip to the bottom right of the text... moving it outside of the text doesn't work when there are a lot of columns.... (yes, it would look better being next to the text but not as a part of the text... but alas...)
- The text is forced to 2 rows of text and shows eclipses for text that will overflow... We need to stop making header names too long... My hot take is anything long should go into a description (need a better way to handle this than tooltips as well for tablets)
- Split buttons for adding from item / adding from master list
- Moved min / max MOS out of side panel
- Move things around in the toolbar to free up more real estate...
Should get input from designer for this doing forth...
1.
2.
The PR Reviewer(s) should fill out …
> Column header

- server/repository/src/db_diesel/name_row.rs
- server/repository/src/migrations/v2_09_00/mod.rs
- server/repository/src/migrations/v2_09_00/reintegrate_clinician_gender.rs
- server/service/src/sync/settings.rs
- server/service/src/sync/sync_serde.rs
- server/service/src/sync/test/test_data/clinician.rs
- server/service/src/sync/translations/clinician.rs
Fixes #8441
Updates clinician translators to use the `legacy_clinician_row.oms_fields` struct 
This is quirky.
- If the `oms_fields` are None, then use the old `female` boolean
- else use `oms_fields`...
- If `oms_fields.gender` is None then set gender to None (ignore `female`)
- If `oms_fields.gender` is Some _valid_ `GenderType` variant then set gender to it
- If `oms_fields.gender` is Some* _invalid_ `GenderType` variant (say from a future version of OMS syncing it to an older version site) then set gender to None (* will write comment in PR code but it's actually if there is any error)
- If on migration to new versions of OMS that add `GenderType` variants, we should write migrations that check query `clinician.gender == None` and then lookup the sync_buffer to see if there is a valid …
> 8441 clinician gender sync fix

- client/packages/invoices/src/Prescriptions/DetailView/AppBarButton.tsx
- client/packages/system/src/Patient/PatientView/AppBarButtons.tsx
- client/packages/system/src/Report/components/ReportSelector.tsx
- client/packages/system/src/Stock/Components/Repack/RepackModal.tsx
Fixes #8431
Removes the option to disable the report selector, as we generally always want to allow report or printing if the use can view.
Is there some reason why we do want to disable this? Examples seemed to be ok to me...
1.
2.
**Tests Pass**
> Remove disabled option from report selector

- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/ModalContentPanels.ts
- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ContentLayout.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEdit.tsx
Fixes #8497 
Hide doses display for days out of stock and months of stock
1.
2.
**Tests Pass**
> 8497 Internal Orders: Doses shouldn't be displayed for MOS

- client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/utils.tsx
- client/packages/system/src/Stock/Components/VVMStatusSearchInput/VVMStatusInputCell.tsx
- client/packages/system/src/Stock/Components/VVMStatusSearchInput/VVMStatusSearchInput.tsx
Fixes #8487 
Defaults vvm status to first vvm status for Inbound Shipment. Having a prop passed in since the cell will be re-used in Outbound Shipment.
1.
2.
**Tests Pass**
> 8487 VVM status set to first status level by default on an Inbound Shipment

- server/service/src/report/convert_to_excel.rs
Fixes #8415 
Before:
100 rows: 0.12s
1000 rows: 9.5s
10000 rows: 1123s 
It appears the vast majority of time is `Worksheet::insert_new_row()`. Perhaps quadratic if not exponential big O as for every row added I am guessing it executes `rebuild_map_and_indicies`, as the sheet grows this gets slower. Oof. Soooo I removed it:
After: 10000 rows 1.6s
(note our `apply_data_rows` is now a very minor player, and most of the time is in `scraper` code parsing the html rather than `umya` building the spreadsheet)
This appears to work correctly for item usage report which just does default direct mapping of html to excel, however I expect the current change to break footers if using a xlsx template. The intent with the insert rows is to push the footer rows of the template down. 
Turns out you can …
> 8415 improve report excel export performance

- client/packages/common/src/intl/locales/en/common.json
- client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts
- client/packages/invoices/src/InboundShipment/DetailView/DetailView.tsx
- client/packages/invoices/src/InboundShipment/DetailView/Footer/StatusChangeButton.test.ts
- client/packages/invoices/src/InboundShipment/DetailView/Footer/StatusChangeButton.tsx
- client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/InboundLineEdit.tsx
- client/packages/invoices/src/InboundShipment/api/api.ts
- client/packages/invoices/src/utils.test.ts
- client/packages/invoices/src/utils.ts
- server/graphql/logger.rs
- server/service/src/invoice/inbound_shipment/update/generate.rs
- server/service/src/invoice/inbound_shipment/update/mod.rs
Fixes #7841
Allow inbound shipments to be verified after setting received packs to 0.
Allow reducing received quantity to 0 in the edit modal.
1.
2.
**Tests Pass**
> 7841 cannot verify inbound shipment with lines with 0 quantity

- client/packages/common/src/intl/README.md
- client/packages/common/src/intl/context/IntlContext.tsx
- client/packages/common/src/intl/strings/IntlStrings.ts
- client/packages/host/src/components/Sync/SyncModal.tsx
- client/packages/system/src/Manage/Preferences/EditPage/EditPreference.tsx
- client/packages/system/src/Name/ListView/Stores/EditStorePreferences.tsx
Part 3 #5061
As you edit the global pref custom translations, invalidates the cached values so they are re-queried from the backend.
Note - translations aren't considered props to a component, so invalidating them doesn't cause them to re-render. Translations will be applied the next time the component is re-rendered.
When we do modal for entering translations, could consider refreshing the page on save? Not sure about on sync... 
1.
2.
**Tests Pass**
> 5061 invalidate translations on update

- client/packages/common/src/intl/locales/en/common.json
- client/packages/host/src/components/Navigation/ReplenishmentNav.tsx
- client/packages/purchase_orders/src/ListView/ListView.tsx
- client/packages/purchase_orders/src/api/operations.generated.ts
- client/packages/purchase_orders/src/api/operations.graphql
- client/packages/purchase_orders/src/utils.ts
Fixes #8216
Fully Delivered
Partially Delivered
Not Delivered
I've added the delivery status column as requested but to calculate it we really need to know how many lines are fully delivered which requires goods received integration so can't be fully done yet.
1.
2.
**Tests Pass**
> Tweak purchase order columns and add derived delivery status

- client/packages/system/src/Stock/Components/StockLineForm.tsx
- client/packages/system/src/Stock/Components/StyledInputRow.tsx
- client/packages/system/src/Stock/Components/VVMStatusSearchInput/VVMStatusInputCell.tsx
- client/packages/system/src/Stock/Components/VVMStatusSearchInput/VVMStatusSearchInput.tsx
- client/packages/system/src/Stock/api/hooks/useStockLine.ts
- client/packages/system/src/Stock/api/operations.generated.ts
- client/packages/system/src/Stock/api/operations.graphql
- server/service/src/invoice/inventory_adjustment/add_new_stock_line/insert.rs
Fixes #8007
- Allows user to input VVM status when introducing new stock in Inventory Adjustment. 
- This defaults to the 'best' status
- Read only component in the stock edit page
1.
2.
**Tests Pass**
> 8007 can't select vvm status when adding new stock line

- server/graphql/purchase_order/src/mutations/insert.rs
- server/graphql/purchase_order/src/purchase_order_queries.rs
- server/graphql/purchase_order_line/src/purchase_order_line_queries.rs
- server/service/src/auth.rs
Fixes #8624 
Implements permissions and auth for purchase orders' graphql API.
Enjoy your weekend!
**Tests Pass**
> 8624 Add permission mapping to resource

- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/types/schema.ts
- client/packages/common/src/ui/components/navigation/AppNavLink/AppNavLink.tsx
- client/packages/host/src/components/AppDrawer/SyncNavLink.tsx
- client/packages/system/src/Manage/Preferences/EditPage/EditPreference.tsx
- server/graphql/preference/src/upsert.rs
- server/graphql/types/src/types/preferences.rs
- server/service/src/preference/mod.rs
- server/service/src/preference/preferences/mod.rs
- server/service/src/preference/preferences/sync_records_display_threshold.rs
- server/service/src/preference/types.rs
- server/service/src/preference/upsert.rs
Fixes #8634 
as per [this comment](https://github.com/msupply-foundation/open-msupply/issues/8634#issuecomment-3130185025) (mostly -- I made a couple of other style tweaks, and kept the exising warning/error threshold functionality)
- Add `SyncRecordsDisplayThreshold` preference to server (integer value)
- Implement UI to edit preference:
- Update Sync badge to reflect this preference, plus changes desribed in issue, plus couple of extra style tweaks
Normal display -- sync is working and all records are synced (or number is below threshold):
(same as current)
When there is a *connection* error (e.g. out of range), not a more serious sync problem, we keep the UI change subtle, just by dulling the icon (Mark okay-ed this):
(The unpushed record count is below the threshold here)
Not …
> #8634 Sync badge updates

- server/service/src/rnr_form/finalise.rs
- server/service/src/rnr_form/tests/finalise.rs
Fixes #8641 and #8640
Defaults to snapshot values where nothing is manually entered
and
Populates requisition min/max MOS based on store pref:
1.
2.
**Tests Pass**
> 8640 & 8641 rnr default values not on internal order

- client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
Fixes #8682
Swap received and shipped columns as shipped means how many the supplier shipped and received is how many the customer received
1.
2.
**Tests Pass**
> 8682 inbound shipment swap shipped and received columns

- client/packages/programs/src/JsonForms/common/components/Date.tsx
- client/packages/programs/src/JsonForms/common/components/DateTime.tsx
Fixes #8537
I've removed the "actions" prop from *both* the "Date" and "DateTime" components to standardise their UIs -- now they'll both show an "OK" and a "Clear" button. (The DateTime one also offered a "Today" button, but this is not used anywhere else in the app and it defaults to the current date anyway, so seems unnecessary -- we can add it back as a UI Schema option later if it's needed).
This problem doesn't seem to be mobile device-related -- it's like this in browser too.
**Tests Pass**
> #8537 JSON Forms DatePicker "OK" button fix

- client/packages/common/src/intl/locales/en/common.json
- client/packages/common/src/intl/locales/fr/common.json
- client/packages/system/src/Encounter/DetailView/Footer.tsx
From @Rajajajaja 's [requests](https://docs.google.com/document/d/1TfkpMN1STVLOjbNm9MsO7OBDRZq1rvtknZS1TI_0jlw/edit?tab=t.cbq26y41gbmz).
Adds additional "Save progress" button for use in Encounters
I think this makes sense, and it can be put back to just plain old "Save" using custom translations if people don't think it should be different to normal "Save".
> Extra localised string for Encounters

- client/packages/common/src/intl/locales/en/common.json
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/Allocation.tsx
- client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEdit.tsx
- client/packages/invoices/src/StockOut/Components/AllocateInSelector.tsx
- client/packages/invoices/src/StockOut/useAllocationContext.ts
- client/packages/invoices/src/StockOut/utils.test.ts
- client/packages/invoices/src/StockOut/utils.ts
Fixes #8668
When selecting an outbound shipment line, auto allocate stock IF there is a placeholder and no stocklines have previously been allocated. This will ensure that whether the allocation type is in doses, units, or packs of X the placeholder will automatically be allocated when first opening the line
- If a line has been allocated, if won't be changed automatically if reopened
- Update to the allocation message to read better if allocation is in packs
- added a message for auto allocation
Bonus: fixes pack size selector being empty when no available pack sizes - instead show units:
1.
2.
**Tests Pass**
> 8668 auto allocate placeholders on open

- server/service/src/invoice_line/stock_in_line/insert/generate.rs
- server/service/src/invoice_line/stock_in_line/insert/mod.rs
- server/service/src/vaccination/insert/mod.rs
- server/service/src/vaccination/update/generate.rs
- server/service/src/vaccination/update/mod.rs
- server/service/src/vaccination/update/validate.rs
Fixes #8530
Previously there was an exception for packsize to 1 preference were it wasn't applied using the add stock mechanism.
This what's applied to customer returns though, so even though the invoice said to return a single dose to the line, it actually over-wrote the packsize breaking the ledger..
Now we're using a canceled prescription to reverse the existing prescription instead of customer returns for vaccinations
I've left in a change to the customer return with only over-writes customer returns when there's no existing stockline.
That is an extra db request though, so maybe better remove it?
1.
2.
**Tests Pass**
> Fix vaccine card returns that were over-ridding stock and packsize

- client/packages/invoices/src/OutboundShipment/DetailView/ExpandoTable.tsx
- client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/Allocation.tsx
- client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditForm.tsx
- client/packages/invoices/src/Prescriptions/LineEditView/hooks/useClosedSummary.ts
- client/packages/invoices/src/StockOut/Components/AllocateInSelector.tsx
- client/packages/system/src/Item/Components/StockItemSearchInput/StockItemSearchInput.tsx
Fixes #8042
Last one!
13. Collapsed view respects allocation lens:
https://github.com/user-attachments/assets/37a16b8a-80b3-418c-83a6-ba7f988f1ee2
15. Some fields say Doses per Unit, some say Doses per VI (whatever Unit we specify) -> change to only "doses per unit":
17. autofocus when selecting new item in prescription:
Bonus: fixes pack size selector being empty when no available pack sizes - instead show units:
1.
2.
**Tests Pass**
> 8042 UI ux pt 5

- server/service/src/stocktake/update/generate.rs
Fixes #https://github.com/msupply-foundation/open-msupply-reports/issues/242
Program id wasn't being populated on the invoice created from stocktake
1.
2.
**Tests Pass**
> Unusable master list doesn't seem to work

- client/packages/common/src/ui/components/navigation/AppNavLink/AppNavLink.tsx
Follow up for #8652 to restore the NavLink arrow padding
There was a change in #8652 to remove a `flexGrow` in order to make the sync badge attach to the icon rather than floating out on its own. That inadvertantly also made the Nav link arrows (chevron) no longer push out to the end of the button.
This fixes the latter, while keeping the intended spacing for the actual sync badge.
It may seem a bit hacky adding an empty `span` in order to create padding. However, I would argue that it's less so than what was there originally -- it was using the `Badge` container to add the flex-grow, even when there was no badge, which was confusing and unclear. At least it's now explicit where the extra padding is coming from.
I tried setting the width of the container to "100%" (or slightly less), but …
> Add spacer to re-instate padding

- server/repository/src/migrations/v2_09_02/mod.rs
- server/service/src/ledger_fix/ledger_fix_driver.rs
- server/service/src/processors/transfer/invoice/update_outbound_invoice_status.rs
- server/service/src/sync/translations/invoice.rs
Fixes #8654
* Stops updates of owned records via sync, inserts are allowed
* Stops updates of outbound shipment from inbound shipment to status below Delivered
I haven't added check for total below available, since we have ledger fix once a day now, i feel a bit more confident about it, and was worried that user/support/dev would get stumbled when dealing with that use case ? 
As per issue, i don't quite know what small data file to use, but the data file provided in issue would work, also test [steps in this one](https://github.com/msupply-foundation/msupply/issues/16945)
1.
2.
**Tests Pass**
> 8654 Stop updates of owned records in sync

- server/service/src/sync/test/test_data/purchase_order.rs
- server/service/src/sync/translations/purchase_order.rs
Fixes #8639 
Translates the is_authorised boolean to a new `Authorised` status in OMS.
Add status to oms_fields
1.
2.
**Tests Pass**
> Add authorised sync

- client/packages/common/src/intl/locales/en/common.json
- client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts
- client/packages/invoices/src/InboundShipment/DetailView/DetailView.tsx
- client/packages/invoices/src/InboundShipment/DetailView/Footer/StatusChangeButton.test.ts
- client/packages/invoices/src/InboundShipment/DetailView/Footer/StatusChangeButton.tsx
- client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/InboundLineEdit.tsx
- client/packages/invoices/src/InboundShipment/api/api.ts
- client/packages/invoices/src/utils.test.ts
- client/packages/invoices/src/utils.ts
- server/graphql/logger.rs
- server/service/src/invoice/inbound_shipment/update/generate.rs
- server/service/src/invoice/inbound_shipment/update/mod.rs
Fixes #7841
Applies #8459 to v2.9.3 (changes already merged into v2.10
1.
2.
**Tests Pass**
> 7841 allow verify inbound shipment with lines with 0 quantity

- client/packages/system/src/Manage/Campaigns/ListView/CampaignEditModal.tsx
Fixes #8741
Remove conversion to "naive date" when passing into the input - every call to `getNaiveDate` subtracts the timezone offset, so in NZ, that means every time you select a date, it would subtract 12hr. Therefore, every second click, changed to the previous day.
Instead, just pass the date straight into the input. It displays correctly. It is converted back to a naive date (date with no time zone info) by the hook, on save.
1.
2.
**Tests Pass**
> 8741 Campaign date selector shows incorrect dates

- server/repository/src/db_diesel/campaign/campaign_row.rs
- server/service/src/campaign/delete.rs
- server/service/src/sync/translations/campaign.rs
Fixes #8257 
Deleting a campaign syncs from Central server to remote sites
Deleted campaigns no longer visible on remote sites  - when viewing any stocklines that were associated with the campaign, campaign is no longer visible
Implemented as a soft delete, any campaigns previously deleted will still retain a changelog DELETE record that will not translate
Discussed creating a migration to clean these (changing delete to upsert in the changelog) however migrations do not run by central/remote type. The sync buffer for the remote site will retain "Translator for record not found" Deletes.  However, there is no user impact for these to remain
Moving this from 2.10 to 2.9.3 to lessen any possible instances of this occurring
1.
2.
The PR Reviewer(s) should fill out this section before …
> 8257 use soft delete for campaigns

- client/packages/common/src/utils/reasons/ReasonOptionUtils.test.ts
- client/packages/common/src/utils/reasons/ReasonOptionsUtils.ts
- client/packages/inventory/src/Stocktake/DetailView/ReduceLinesToZeroModal.tsx
- client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx
- client/packages/inventory/src/Stocktake/api/hooks/line/useZeroStocktakeLines.ts
- client/packages/invoices/src/Returns/modals/ReturnReasonsTable.tsx
- client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEdit.tsx
- client/packages/system/src/ReasonOption/Components/ReasonOptionsSearchInput.tsx
- client/packages/system/src/Stock/Components/InventoryAdjustment/InventoryAdjustmentModal.tsx
- client/packages/system/src/Stock/Components/NewStockLineModal.tsx
- client/packages/system/src/Stock/Components/StockLineForm.tsx
Fixes #8604 
Shows inventory adjustment reasons as follows:
1. If the item is a vaccine, the list of reasons shown are the Closed vial wastage reasons
2. if the item is a vaccine and the store is a dispensary, add Open vial wastage reasons to the list
3. For all other items the list of reasons shown are the Negative inventory adjustment reasons
1.
2.
**Tests Pass**
> 8604 closed vial reasons for vaccines

- server/repository/src/db_diesel/goods_received_line_row.rs
- server/repository/src/db_diesel/goods_received_row.rs
- server/repository/src/db_diesel/purchase_order_line_row.rs
- server/repository/src/db_diesel/purchase_order_row.rs
- server/service/src/sync/test/pull_and_push.rs
- server/service/src/sync/test/test_data/goods_received.rs
- server/service/src/sync/test/test_data/goods_received_line.rs
- server/service/src/sync/test/test_data/mod.rs
- server/service/src/sync/test/test_data/purchase_order.rs
- server/service/src/sync/test/test_data/purchase_order_line.rs
- server/service/src/sync/translations/goods_received.rs
- server/service/src/sync/translations/goods_received_line.rs
- server/service/src/sync/translations/purchase_order.rs
- server/service/src/sync/translations/purchase_order_line.rs
Fixes #8610
Sync deletes for pull / push: 
- Purchase orders & lines
- Goods received & lines
There's a weird side affect going on whereas if you delete the line, the costs in the purchase order has changed? I'm told that this is done in a view... but erm would suggest a change in architecture here @andreievg 
1.
2.
**Tests Pass**
> 8610 sync delete records

- client/packages/invoices/src/InboundShipment/api/api.test.ts
- client/packages/invoices/src/InboundShipment/api/api.ts
Fixes #8910
Adds test to expose bug, and fix - service line was being saved as both regular line and service line, causing a "line already exists" error.
1.
2.
**Tests Pass**
> 8910 cant save service lines

- client/packages/system/src/Location/Components/LocationSearchInput.tsx
- client/packages/system/src/Location/utils.test.ts
- client/packages/system/src/Location/utils.ts
Fixes #8902 
A location with no location type is now treated as an `invalid` location for an item that has a restricted location type set
1.
2.
**Tests Pass**
> 8902 locations with no restricted type are invalid

- client/packages/purchasing/src/goods_received/api/operations.generated.ts
- client/packages/purchasing/src/goods_received/api/operations.graphql
Fixes #8954 
Re-adds John's goodsreceivedline mutation, to fix yarn not compiling in the latest RC.
**Tests Pass**
> 8954 hotfix removed api query

- client/packages/coldchain/src/Monitoring/ListView/TemperatureBreach/Toolbar.tsx
- client/packages/coldchain/src/Monitoring/ListView/TemperatureLog/Toolbar.tsx
- client/packages/common/src/hooks/useUrlQuery/useUrlQueryParams.ts
- client/packages/common/src/intl/utils/DateUtils.ts
- client/packages/common/src/ui/components/inputs/DateTimePickers/DateTimePickerInput/DateTimePickerInput.tsx
- client/packages/common/src/ui/components/inputs/Filters/DateFilter.tsx
- client/packages/invoices/src/InboundShipment/ListView/Toolbar.tsx
- client/packages/invoices/src/OutboundShipment/ListView/Toolbar.tsx
- client/packages/invoices/src/Prescriptions/ListView/Toolbar.tsx
- client/packages/purchasing/src/purchase_order/ListView/ListView.tsx
- client/packages/purchasing/src/purchase_order/ListView/Toolbar.tsx
- client/packages/system/src/Encounter/ListView/Toolbar.tsx
- client/packages/system/src/Item/DetailView/Tabs/ItemLedger.tsx
Fixes #8533
Filters with a date correctly use either date or dateTime filter types
Filters with dateTime (often a created date or similar) works with timezones, so that the resulting records (with localised dates) match the filtered date selection. Several filters that were using date have now been updated to dateTime
Filters where only a date is needed (eg expiry, DOB) use 'date' only as they have no time element
Some refactoring for more robust date type handling, and clarity on handling for showTime. Comments to help developers choose the correct date type when implementing or updating filters 
For the second part of the issue, selecting the dates all worked correctly for me and I couldn't reproduce the behaviour shown in the second video. Possibly this is also related to timezones? 
- …
> 8533 date picker use dates in correct timezone

- client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
Fixes #8971
Was clearing in shipped pack size but with received pack size variable in the check... have moved this to received pack size. Not we're not re-populating the default sell price back if the pack size matches default... not sure if this is something we want and probably very edge case
1.
2.
**Tests Pass**
> Clear if received pack size changed not shipped

- server/repository/src/migrations/views/adjustments.rs
- server/repository/src/migrations/views/changelog_deduped.rs
- server/repository/src/migrations/views/consumption.rs
- server/repository/src/migrations/views/contact_trace_name_link_view.rs
- server/repository/src/migrations/views/inbound_shipment_stock_movement.rs
- server/repository/src/migrations/views/inventory_adjustment_stock_movement.rs
- server/repository/src/migrations/views/invoice_line_stock_movement.rs
- server/repository/src/migrations/views/invoice_stats.rs
- server/repository/src/migrations/views/item_ledger.rs
- server/repository/src/migrations/views/latest_asset_log.rs
- server/repository/src/migrations/views/latest_document.rs
- server/repository/src/migrations/views/mod.rs
- server/repository/src/migrations/views/outbound_shipment_stock_movement.rs
- server/repository/src/migrations/views/purchase_order_stats.rs
- server/repository/src/migrations/views/replenishment.rs
- server/repository/src/migrations/views/report_document.rs
- server/repository/src/migrations/views/report_encounter.rs
- server/repository/src/migrations/views/report_patient.rs
- server/repository/src/migrations/views/report_program_enrolment.rs
- server/repository/src/migrations/views/report_program_event.rs
- server/repository/src/migrations/views/report_store.rs
- server/repository/src/migrations/views/requisitions_in_period.rs
- server/repository/src/migrations/views/stock_line_ledger.rs
- server/repository/src/migrations/views/stock_movement.rs
- server/repository/src/migrations/views/stock_on_hand.rs
- server/repository/src/migrations/views/store_items.rs
- server/repository/src/migrations/views/vaccination_card.rs
- server/repository/src/migrations/views/vaccination_course.rs
Fixes #8809
Refactors the second lot of 6 views.
1.
2.
**Tests Pass**
> Refactor the second lot of 6 views

- client/packages/invoices/src/InboundShipment/DetailView/Footer/StatusChangeButton.test.ts
- client/packages/invoices/src/InboundShipment/DetailView/Footer/StatusChangeButton.tsx
- client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/InboundLineEdit.tsx
Fixes #8845
In the case where we have transfers from 2.8, then upgrade to 2.9/2.10 - those transfers will show shipped number of packs input as disabled (because it is a transfer) but the value of 0, because we didn't add that field until 2.10.
If its a transfer, 0 lines should be allowed.
1.
2.
**Tests Pass**
> 8845 cant receive 0 shipped packs lines from prev versions

- client/packages/common/src/intl/utils/IntlUtils.ts
- client/packages/host/src/components/Sync/SyncModal.tsx
- client/packages/system/src/Manage/Preferences/Components/CustomTranslations/CustomTranslationsModal.tsx
Fixes #8981 
Remote sites correctly sync new/updated/deleted custom translations
invalidateCustomTranslations function is now accessible as a util to be used when saving custom translations (central server) or syncing (remote site)
Looked into the order of queries to prevent refresh being required, even if invalidation of the translations happens prior to the sync invalidation, the translations are being returned after the re-render of the page. 
Low impact, it is unlikely the user will be on the page & sync when a translation is updated & it will still show on the next render
1.
2.
**Tests Pass**
> 8981 custom translations syncing to remote sites

- server/service/src/invoice_line/stock_out_line/insert/mod.rs
- server/service/src/invoice_line/stock_out_line/insert/validate.rs
- server/service/src/invoice_line/stock_out_line/update/validate.rs
- server/service/src/invoice_line/stock_out_line/validate.rs
Fixes #8993
When doing a stock reduction - we were doing the location validation based where the stock line _currently_ was, rather than where we are moving it to in the stocktake.
Note - this only applies to stock reduction - matching count and increasing stock should work successfully either way.
1.
2.
**Tests Pass**
> 8993 cant save stocktake with on hold location

- client/packages/common/src/ui/components/inputs/DateTimePickers/styles.ts
Fixes #9076
See PR for the change, but main point is to separate it from the drawer styling which is more likely to change.
This is consistent with NumericTextInput which uses this logic
```
sx: {
backgroundColor: props.disabled
? 'background.toolbar'
: 'background.menu',
},
```
I think a better solution is probably to create a new theme entriesd for disabledInput and enabledInput or something similar. We'd then need to go through all the places we've used menu and other similar colours to retrofit, felt like too much for now, a quick fix?
```
{
"palette": {
"drawerDivider": "#C60C30",
"primary": {
"main": "#C60C30",
"light": "#f3395d",
"dark": "#77071d",
"contrastText": "#fff"
},
"secondary": {
"main": "#002664",
"light": "#236E00",
"dark": "#001b46",
"contrastText": "#fff"
}, …
```
> Change datepicker to using theme.palette.background.menu styling, similar to other related components

- client/packages/common/src/ui/layout/tables/DataTable.tsx
- client/packages/common/src/ui/layout/tables/types.ts
- client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx
Fixes #8918 
Adds a gradient bottom to the bottom of batch table so you can see that there is more stuff down there if you scroll.
Maybe deploy this fix elsewhere? (See discussion in original issue.)
**Tests Pass**
> 8918 Not all batches show up when creating a stocktake for an item

- client/packages/programs/src/JsonForms/components/ProgramSearch.tsx
Fixes #9017
We want to retain `All programs` in the autocomplete when the user selects it
1.
2.
**Tests Pass**
> Retain program in selection

- client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ContentLayout.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEdit.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/utils.ts
Fixes #9040
If the requisition has been created by an Internal Order, then use the MOS from the internal order, else calculate it. Also round to 0dp to match how Internal Order is rounding.
1.
2.
**Tests Pass**
> 9040 requisition does not show the right mos of the customer as displayed in the internal order

- client/packages/common/src/types/schema.ts
- client/packages/purchasing/src/goods_received/DetailView/DetailView.tsx
- client/packages/purchasing/src/goods_received/DetailView/SidePanel.tsx
- client/packages/purchasing/src/goods_received/DetailView/Toolbar.tsx
- client/packages/purchasing/src/goods_received/api/hooks/utils.ts
- client/packages/purchasing/src/goods_received/api/operations.generated.ts
- client/packages/purchasing/src/goods_received/api/operations.graphql
- client/packages/purchasing/src/purchase_order/DetailView/SidePanel/OtherSection.tsx
- server/graphql/goods_received/src/mutations/update.rs
- server/graphql/goods_received/src/types.rs
- server/service/src/goods_received/update/generate.rs
- server/service/src/goods_received/update/mod.rs
Fixes #9061 
Fixes #9062
Can save the following fields on a goods received from detail view
Side panel: Donor, comment (linked issues)
Toolbar: Supplier reference, received date
Sorry this blew out a little.. These were all in varying half-done states, so included the extra fields whilst in the area
1.
2.
**Tests Pass**
> 9061 Save fields on goods received

- client/packages/purchasing/src/purchase_order/api/hooks/usePurchaseOrder.ts
Fixes #9100
Changed the detail view query to access the isLoading state correctly. This then allows the loading skeleton to be triggered when loading, instead of seeing the previously opened purchase order
1.
2.
**Tests Pass**
> 9100 Purchase order detail view query fix

- client/packages/requisitions/src/RequestRequisition/DetailView/columns.tsx
- client/packages/system/src/Item/Components/TableCell/NumericCell.tsx
- client/packages/system/src/Item/Components/TableCell/index.ts
- client/packages/system/src/Item/Components/index.ts
Fixes #9210 
Displays months of stock as a single decimal place, which aligns better with customer requirements and the inherent precision of the measure.
I created a new `NumericCell` component which does rounding but drops other `1.1..` precision and tool tips.
Looks like we're using PackSize Cell everywhere which really should be something more generic but 
Thoughts about naming? Should this have more configuration to enable it to replace `PackSizeCell` in future?
Should I just create a custom `MosCell` instead?
1.
2.
**Tests Pass**
> Round MOS to 1 dp

- client/packages/invoices/src/OutboundShipment/DetailView/Toolbar.tsx
- client/packages/invoices/src/Returns/CustomerListView/AppBarButtons.tsx
- client/packages/system/src/Name/SupplierDetailView/PurchaseOrder.tsx
Fixes #9188
Redirect user to purchase order from supplier on row click
1.
2.
**Tests Pass**
> 9188 Supplier's Purchase Order tab

- server/repository/src/db_diesel/purchase_order_line.rs
Fixes #9276
Updated the macro used against to sort by `purchaseOrderNumber`, was using `apply_sort_no_case` (I believe is used for strings) to just `apply_sort` (supports BigInt which is purchaseOrderNumber). 
1.
2.
**Tests Pass**
> 9272 clicking on outstanding lines leads to endless loading

- server/service/src/purchase_order/update/generate.rs
- server/service/src/purchase_order/update/test.rs
- server/service/src/purchase_order_line/update/mod.rs
- server/service/src/purchase_order_line/update/validate.rs
Fixes #9306 
Context: When a purchase order is in Sent status and the adjusted packs field is updated on a line, the purchase order status changes to Confirmed (Ready for Sending)
The line status will now also update when the adjusted packs is updated, from Sent to New. This is done separately to the order status, as multiple lines may need to be updated & should all have the line status update to New when changing a quantity
Allows changing of other fields when status is sent - relying on front end disabled fields. Line status changes are still validated server-side
If a line status is Closed, changing other lines or the purchase order status back to Sent does not impact the Closed line - it remains Closed.
If a line is Closed & Purchase order status has been taken back to Confirmed by …
> 9306 - Update line status when editing adjusted packs

- client/packages/system/src/Name/Components/DonorSearchInput/DonorSearchInput.tsx
Fixes #8425
Invisible donors that have been saved to stock lines before they became invisible are still shown as a value (but not as a selectable option)
1.
2.
**Tests Pass**
> 8425 Invisible donors disappear from stock lines

- client/packages/requisitions/src/RequestRequisition/DetailView/columns.tsx
- client/packages/requisitions/src/ResponseRequisition/DetailView/columns.ts
Fixes #8728
Sort by approved quantity in internal orders and requisitions
1.
2.
**Tests Pass**
> 8728 Sort by "Approved packs" in internal order

- client/packages/common/src/intl/locales/en/common.json
- client/packages/purchasing/src/purchase_order/DetailView/Toolbar.tsx
- client/packages/purchasing/src/utils.ts
Fixes #9305 
Added expected delivery date to the toolbar. This sets the expected delivery date for ALL of the lines. 
1.
2.
**Tests Pass**
> 9305 add expected delivery date to purchase order toolbar

- client/packages/common/src/ui/layout/tables/material-react-table/useBaseMaterialTable.tsx
- client/packages/common/src/ui/layout/tables/material-react-table/usePaginatedMaterialTable.tsx
- client/packages/common/src/ui/layout/tables/material-react-table/useTableDisplayOptions.tsx
Fixes #9181 (partially)
Addresses these issues from the [original list](https://github.com/msupply-foundation/open-msupply/issues/9181#issue-3392446149):
See inline comments for details
Check the above points and make sure they are correct/look acceptable/don't cause any problems
**Tests Pass**
> #9181 Additional table style tweaks

- client/packages/common/src/ui/components/inputs/CurrencyInput/CurrencyInput.tsx
- client/packages/common/src/utils/quantities/quantities.test.ts
- client/packages/system/src/Stock/Components/StockLineForm.tsx
Fixes #9381
The currency component was changed to a controlled component to get the sell price to update... which was messing with the decimals... have changed this back to an uncontrolled component and forced the currency input to re-render if the sell price has changed
1.
2.
**Tests Pass**
> 9381 not possible to enter decimals in pricing fields in stock line

- server/service/src/ledger_fix/fixes/delete_unused_orphan_stock_lines.rs
- server/service/src/rnr_form/generate_rnr_form_lines.rs
Fixes #9298
Previously we weren't including any stock allocated from today (utc time) in the stock we were removing from the pre-saved SOH view, now we use current time, which should include everything unless we somehow have future dated invocies.
Note:I feel like I've fixed this before, but maybe in different context? Makes sense to use some kind of shared logic for these kinds of operations that are being done in a few places now.
Was there another reason I'm not aware of for trying to use `today` rather than `now`?
There's a few ways to skin this cat now. Currently went for the smallest code diff, however could also do things like.
Consolidating all these things is probably a good refactor issue that I should create? Feel like we probably don't need/want it in a patch though?
1.
2.
The …
> 9298 Fix negative balance for RnR Forms

- server/server/src/lib.rs
Fixes #9413
Increases the upload JSON limit from 2MB to 10MB, should probably make this configurable from `config.yaml` but don't really want to do it right now when we have other things pressing?
Should also do something at the client end to make sure we don't create payloads that are too large, follow up issue?
Thanks for Claude, we have a nice python script to create a big message...
Please adapt for your own testing...
```
import sqlite3
import uuid
from datetime import datetime
db_path = "omsupply-database.sqlite"
size_in_bytes = 2 * 1024 * 1024 + 100  # Slightly over 2MB
large_message = "X" * size_in_bytes
log_id = str(uuid.uuid4())
log_type = "PROCESSOR_ERROR"
sync_site_id = 4
log_datetime = datetime.now().strftime("%Y-%m-%d %H:%M:%S.%f")
is_error = 1
conn = …
```
> Increase json parse limit for OMS central server sync requests

- server/service/src/sync/test/test_data/invoice.rs
- server/service/src/sync/translations/invoice.rs
Fixes #4840
Implement finalised date/time mapping to / from OG for invoices
1.
2.
**Tests Pass**
> 4840 invoice translate legacy finalised date/time

- client/packages/common/src/types/schema.ts
- client/packages/purchasing/src/purchase_order/api/operations.generated.ts
- client/packages/system/src/Stock/ListView/ListView.tsx
- client/packages/system/src/Stock/api/hooks/useStockList.ts
- server/graphql/stock_line/src/lib.rs
- server/repository/src/db_diesel/stock_line.rs
Fixes #7444 
- Add sort functionality on the `Pack cost` column of View Stock
- Disable sorting of `Total` column - as per issue comment is a calculated value so difficulty sorting with pagination
1.
2.
**Tests Pass**
> 7444 Sort by pack cost on stock line

- client/packages/system/src/Item/DetailView/DetailView.tsx
Fixes #8524
Corrects navigation from the item ledger
Inbound shipment navigation was being called before the navigation to `invoice type`. If the invoice type had a valid navigation, it would navigate to Inbound shipments and then the valid page eg outbound shipments. Not all invoice types can be navigated to eg inventory adjustment, so thees remained on Inbound shipment.
If the ledger item should not be navigated to, the row is not clickable and no navigation takes place
There is currently no difference on an invoice/invoice type level to differentiate between and inventory adjustment created by a stocktake, or an inventory adjustment created manually for the stockline. As there is no UI in place for viewing a manual inventory adjustment, invoices of this type this cannot navigate …
> 8524 Fix Item Ledger Navigation

- server/repository/src/db_diesel/item.rs
- server/repository/src/db_diesel/master_list.rs
- server/service/src/sync/translations/program_requisition_settings.rs
Fixes #7716
Populate deleted_datetime if master list was a program but is no longer a program. 
1.
2.
**Tests Pass**
> 7716 removing is program from a master list doesn't reflect correctly in oms
